### ISSUE TITLE
Language used in CLA

### ISSUE THREAD

**Issue by runningcode** [open-telemetry/community#1000]
Hi,
We (Gradle) would like to contribute to the opentelemetry project a badge to the readme. In reviewing the language of your CLA, we have some questions.
Who would be the best point of contact for this?
Cheers,
Nelson

**Comment by bhs** [comment]
You're welcome to ask the questions here if that helps. (To set expectations, the CLA is a Linux Foundation thing and we will not be able to customize terms for OTel)

**Comment by soskouy** [comment]
Hi, 

Would you please let us know who to get in touch with at Linux Foundation about the CLA? Their CLA states that we may submit works separately from our contribution under certain circumstances, and we want to know how best to follow these steps to advise them of additional license restrictions associated with the contribution.

Thanks,
Sanaz

**Comment by SergeyKanzhelev** [comment]
@caniszczyk what's the best way for @soskouy to ask the question?

**Comment by caniszczyk** [comment]
@SergeyKanzhelev have them email caniszczyk at linuxfoundation and we can setup a meeting

**Comment by bhs** [comment]
@soskouy and @runningcode , please see above ^^^ for your next step. I'm going to close this out in the meantime, reopen if there are other needs from the OTel crew. Thanks!
