### ISSUE TITLE
Add a link to OTel website under repo About section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/community#1002]
Add https://opentelemetry.io as the **Website** under **About**, as is done for most OTel repos. For example:

> <img width="325" alt="image" src="https://user-images.githubusercontent.com/4140793/158021593-283f25fc-d6cf-4a9b-9bdd-bdc85e8c1ab8.png">

/cc @caniszczyk @nate-double-u

**Comment by SergeyKanzhelev** [comment]
done.

**Comment by chalin** [comment]
Thanks @SergeyKanzhelev: one nit, could you drop the trailing slash?
