### ISSUE TITLE
REQUEST: New membership for @pavankrish123

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/community#1003]
### GitHub Username

@pavankrish123

### Requirements

- [X ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X ] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @bogdandrutu 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

I have been contributing to OpenTelemetry Collector's authentication plane for a while now. My contributions include 

1. Added client side extension framework for authentication, which involved defining new framework for exporters to authenticate and refactored all of the exporters to plug in the new interfaces.
2. I have also authored [OAuth2Extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension) and [BearerTokenExtension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/bearertokenauthextension) for which I am a official/default code reviewer for the module along with @jpkrohling. 
3. In addition to these I am actively contributing to any bugs/issues in OpenTelemetry Collector module and tracegen tool  

- PRs reviewed / authored

  1. [List of  Contributions for OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+is%3Aclosed+pavankrish123+is%3Amerged)
  2. [List of Contributions for OpenTelemetry Collector Contrib Repo](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+is%3Aclosed+pavankrish123+is%3Amerged)

- Issues responded to
  1. [Some recent comments](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=mentions%3A%40me+)
  2. [Some recent PRs code reviewed](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7307)

I have been contributing to the OpenTelemetry project for almost 18 months now and I would like to be a member. I will continue to contribute more in any way I can. Kindly approve my membership request

- SIG projects I am involved with
OpenTelemetry Collector and OpAMP SIGs 

Thanks, 
Pavan

**Comment by bogdandrutu** [comment]
+1

**Comment by jpkrohling** [comment]
Big +1 from me, thank you for your contributions around the auth features for the collector, @pavankrish123!

**Comment by bogdandrutu** [comment]
Invite sent
