### ISSUE TITLE
Collector SIG Recordings not Uploading to YouTube

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/community#1006]
I am not able to find any Collector SIG YouTube uploads for the March 2022.  The most recent video I can find is [2022-02-23](https://www.youtube.com/watch?v=h6n0SE0Jlmg).  This video was uploaded the day it was recorded, although I don't know what the cadence normally is.

**Comment by jpkrohling** [comment]
I just moved it there.

**Comment by alanwest** [comment]
@TylerHelmuth Take a look again. I'm a bit surprised you don't see a collector SIG recording for any date in March. I've been running the tool that makes the videos available. However, I did note that it's failed the past few days - maybe week, so there should be a slew of new recordings available.

**Comment by alanwest** [comment]
Hmm, well that is fishy... I do not see any videos for those dates that have not yet been published for the collector SIG.

I'm only privy to the process of making videos public that have been uploaded to YouTube. I'm beginning to wonder if the videos for the collector SIG are not being uploaded from Zoom to YouTube. @mtwo is this something you can confirm?

**Comment by mtwo** [comment]
I manage the meetings calendar, but I'm not actually involved with the video recording or upload process. @SergeyKanzhelev can you assist?

**Comment by dyladan** [comment]
Just checked and collector meetings are still not being uploaded. @mtwo are we sure the collector meetings are using the correct meeting link? If they are, then it is possible other SIGs which share the same link may also be affected

**Comment by alanwest** [comment]
I've observed this as well and yes I suspect that any meeting using the opentelemetry-meeting-3@cncf.io account is not getting uploaded.

There was some troubleshooting attempts noted in [this slack thread](https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1649874248367809), but seems there's still an issue.

I'm still game to dig into this issue if other folks don't have the time. I would just need someone to orient me to Zoom and/or Splain.

**Comment by alanwest** [comment]
Someone must have done something because I think this is the collector SIG from today https://youtu.be/jFjNEdSndhE. If someone can confirm, then I think this issue can be closed.

**Comment by djaglowski** [comment]
@alanwest, you are correct. This recording is from today.
