### ISSUE TITLE
REQUEST: New membership for TylerHelmuth

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/community#1007]
### GitHub Username

@TylerHelmuth

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dmitryax 
- @naseemkullah 
- @jack-berg 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/129
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/131
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/139
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/147
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/151
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/142
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/143
  - https://github.com/open-telemetry/opentelemetry-helm-charts/pull/148
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8547
  - https://github.com/open-telemetry/opentelemetry.io/pull/1211
  - https://github.com/open-telemetry/opentelemetry.io/pull/1123
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/3041
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/2963
  - https://github.com/open-telemetry/opentelemetry-python/pull/2493
- Issues responded to
  - https://github.com/open-telemetry/community/issues/1006
  - https://github.com/open-telemetry/opentelemetry-helm-charts/issues/135
  - https://github.com/open-telemetry/opentelemetry-helm-charts/issues/144
  - https://github.com/open-telemetry/opentelemetry-helm-charts/issues/141
  - https://github.com/open-telemetry/opentelemetry-helm-charts/issues/138
  - https://github.com/open-telemetry/opentelemetry-helm-charts/issues/114
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8188
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8242
  - https://github.com/open-telemetry/opentelemetry-js/issues/2816
  - https://github.com/open-telemetry/opentelemetry-dotnet/issues/2968 
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-collector

**Comment by dmitryax** [comment]
I support

**Comment by jack-berg** [comment]
I support!

**Comment by SergeyKanzhelev** [comment]
Welcome, @TylerHelmuth! Invite sent
