### ISSUE TITLE
REQUEST: New membership for tigrannajaryan

### ISSUE THREAD

**Issue by flands** [open-telemetry/community#101]
### GitHub Username

* Replace flands with tigrannajaryan as maintainer
* Make flands approver

### Organization you are requesting membership in

open-telemetry-service

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @flands 
- @bogdandrutu

**Comment by bogdandrutu** [comment]
I think this is a natural change since @flands needs only triager access for his work and he will not push that much code as @tigrannajaryan
