### ISSUE TITLE
Request to check OpenTelemetry GitHub organization audit logs

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1010]
We had a GitHub "release" go missing in the opentelemetry-java-instrumentation repository.

The tag was still there, but the GitHub "release" (e.g. with the release notes) went missing.

We have slack integration with GitHub releases, so you can see exactly when the release was made: https://cloud-native.slack.com/archives/C0150QF88FL/p1647559262755549

We have re-created the release: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.12.1

Here's the new slack notification from the re-created release: https://cloud-native.slack.com/archives/C0150QF88FL/p1648079559437609

We would like to know what happened if possible. I'm sort of afraid I might have accidentally deleted it thinking I was on my fork as I have been testing release automation lately.

**Comment by SergeyKanzhelev** [comment]
shared with you audit log for query `repo:open-telemetry/opentelemetry-java-instrumentation`. 

I looked thru recent activities and cannot find anything about tags. Docs doesn't say anything about tags and releases either: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization

**Comment by trask** [comment]
@SergeyKanzhelev thanks for sharing! I couldn't find anything about releases either. Closing, this was probably just my mistake anyways.
