### ISSUE TITLE
REQUEST: New membership for martinkuba

### ISSUE THREAD

**Issue by martinkuba** [open-telemetry/community#1011]
### GitHub Username

@martinkuba

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jack-berg  
- @tedsuo 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-specification/pull/2115
  - https://github.com/open-telemetry/opentelemetry-specification/pull/2192
  - https://github.com/open-telemetry/opentelemetry-specification/pull/2353
  - https://github.com/open-telemetry/oteps/issues/169
- SIG projects I am involved with
  - Client-side (RUM) Instrumentation

**Comment by jack-berg** [comment]
I support!

**Comment by SergeyKanzhelev** [comment]
@tedsuo liked the issue, assuming it equals to "I support". Welcome, @martinkuba! Invite sent
