### ISSUE TITLE
REQUEST: New membership for kdhamric

### ISSUE THREAD

**Issue by kdhamric** [open-telemetry/community#1018]
### GitHub Username

kdhamric

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tedsuo 
- may need second sponsor

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
Volunteering to help as a secondary for the technical project manager role which @tedsuo asked for last week.  Currently working on an open source testing tool based on OTEL tracing at Kubeshop and looking to contribute to the overall OpenTelemetry project.  Would be more in a triager role than code contribution.

**Comment by SergeyKanzhelev** [comment]
Please reopen issue when you have a second sponsor identified. Thank you!
