### ISSUE TITLE
REQUEST: New membership for rbailey7210

### ISSUE THREAD

**Issue by rbailey7210** [open-telemetry/community#1020]
### GitHub Username

e.g. (at)example_user

### Requirements

- [ X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tedsuo
- @reyang 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
I am involved with Spec SIG, Maintenance SIG, Collector SIG, and Instrumentation SIG

**Comment by reyang** [comment]
I support 👍

**Comment by tedsuo** [comment]
I support as well :)

**Comment by SergeyKanzhelev** [comment]
Welcome, @rbailey7210! Invite sent
