### ISSUE TITLE
Rust SIG meetings missing from calendar

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/community#1031]
The readme reports Rust SIG having meetings at alternating times(07:00 and 15:00 PT), but I can only find the latter times scheduled on the [web calendar](https://calendar.google.com/calendar/u/0/embed?src=google.com_b79e3e90j7bbsa2n2p5an5lf60@group.calendar.google.com).

Do the meetings happen or is the readme outdated?

**Comment by SergeyKanzhelev** [comment]
CC: @open-telemetry/rust-approvers

**Comment by TommyCpp** [comment]
Yeah I think the thought was to meet biweekly but the time didn't properly setup

**Comment by MikeGoldsmith** [comment]
I'd be up for attending/running the 7:00am PT (3:00pm UK) meeting.

**Comment by trask** [comment]
@open-telemetry/rust-approvers did you end up establishing a meeting time, or is it ok to remove the meeting time from the [README.md](https://github.com/open-telemetry/community#implementation-sigs) to avoid confusion? thx!
