### ISSUE TITLE
REQUEST: New membership for jmwilliams89

### ISSUE THREAD

**Issue by jmwilliams89** [open-telemetry/community#1036]
### GitHub Username

@jmwilliams89 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski
- @rmfitzpatrick

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project
- [Hadoop addition to java contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/210)
- [WildFly addition to java contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/224)
- [One of the original authors of stanza logging components](https://github.com/open-telemetry/community/issues/605#issuecomment-767904284)

**Comment by rmfitzpatrick** [comment]
I support

**Comment by djaglowski** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Hi @jmwilliams89! Apparently you've been a member of an organization for some time already. Welcome anyways! Let me know if I am missing something.
