### ISSUE TITLE
REQUEST: New membership for dsvanlani

### ISSUE THREAD

**Issue by dsvanlani** [open-telemetry/community#1037]
### GitHub Username

@dsvanlani

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @tigrannajaryan 

Each sponsor should reply to this issue with the comment "*I support*".

### List of contributions to the OpenTelemetry project

PRs:

- https://github.com/open-telemetry/opamp-go/pull/63
- https://github.com/open-telemetry/opamp-go/pull/59
- https://github.com/open-telemetry/opamp-spec/pull/64

Workgroups:
- I attend the Agent Management workgroup

**Comment by djaglowski** [comment]
I support

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @dsvanlani! Invite sent
