### ISSUE TITLE
Request for OpenTelemetry Community Demo Application SIG

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/community#1038]
As OpenTelemetry matures, customers are increasingly looking for guides on how to onboard their services to the new paradigm or demo applications so that they can try the new tools themselves.

Multiple telemetry providers have written their own demo applications but are wholly responsible for the development & ongoing support. All of the existing demos also do not have full language coverage.

We are requesting a formal Demo Application SIG with a weekly community meeting for working on a shared community demo application. 

Once approved, we'd like to have a weekly 45 min meeting on Mondays in an NA/EMEA friendly time at 0815 Pacific Time.

**Project features we would like to focus on include:**

- Improving the ease of running a demo application locally while enabling it to be run on various cloud vendor platforms
- Adding language examples for every supported OpenTelemetry language
- Instrumenting Traces & Metrics across all languages
- Potentially add logging support as a stretch goal
- Ensuring the demo application is kept up to date with new OpenTelemetry features
- Documentation to assist new customers getting onboarded to OpenTelemetry by demonstrating the full capabilities in the demo application
- Examining the feasibility of introducing backend platform services like Azure Blob Storage, AWS DocumentDB etc.
- Providing a load generator to simulate high frequency customer interactions

**Target Personas:**

- Application owners: Installers of instrumentation.

For more details see
https://docs.google.com/document/d/1nCV32KvYzowspjWk9ym6MoLOc-1D_RF-EcX7Dnf_VcE/edit?usp=sharing

cc: @mtwo, @arminru, @aabmass, @reyang, @jsirianni

**Comment by mtwo** [comment]
I support. Let's leave this up for a day or so for people to review, and then @cartersocha can create a PR to add this to the list of SIGs on the community page.

**Comment by reyang** [comment]
+1 I support.

**Comment by tigrannajaryan** [comment]
Do you need a github repo for this SIG? We will need the repo name, and the github usernames of initial maintainers and approvers to create one.

**Comment by cartersocha** [comment]
We will need one a repo once we agree on which existing demo application to start with. Then the existing app will be donated to OpenTelemetry & placed in that repo. I'll check with the channel to see what we want to call it

**Comment by austinlparker** [comment]
This is a great idea! Please keep web/comms SIG in mind; We can work w/y'all to get this integrated into the QuickStarts and other docs pages (and get it featured on the site).

**Comment by ahayworth** [comment]
I think this a fantastic idea.

**Comment by arminru** [comment]
I added an entry for May 2nd to the public calendar since there was confusion on whether there was a meeting today or not.
@cartersocha please let me know if I should keep the 2nd or update it to the 9th.

@mtwo Please create a Google Doc from the GC Google account for us to use as the meetings notes and add it to the entry.
In the past we had meeting notes created and owned by individual's Google accounts which is not ideal.

**Comment by mtwo** [comment]
Doc: https://docs.google.com/document/d/16f-JOjKzLgWxULRxY8TmpM_FjlI1sthvKurnqFz9x98/edit

**Comment by cartersocha** [comment]
@tigrannajaryan our maintainers / approvers are as follows:
Maintainers: myself (@cartersocha), @mtwo, @austinlparker, & waiting for confirmation from @arminru if he has the bandwidth. 
Approvers: @reyang, @mic-max, @jsirianni, & @julianocosta89

Repo name: opentelemetry-demo-webstore

**Comment by tigrannajaryan** [comment]
Repo created https://github.com/open-telemetry/opentelemetry-demo-webstore and approvers/maintainers added.

@lizthegrey, @bogdandrutu EasyCLA action does not show up in the main branch protection: https://github.com/open-telemetry/opentelemetry-demo-webstore/settings/branch_protection_rules/25424445

Anything I need to do to enable it?

**Comment by cartersocha** [comment]
Merged 💯 https://github.com/open-telemetry/community/pull/1046

**Comment by tigrannajaryan** [comment]
> @lizthegrey, @bogdandrutu EasyCLA action does not show up in the main branch protection: https://github.com/open-telemetry/opentelemetry-demo-webstore/settings/branch_protection_rules/25424445

I tried again and now I can see it. Enabled. All good.
