### ISSUE TITLE
REQUEST: New membership for @pichlermarc

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/community#1039]
### GitHub Username

@pichlermarc

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @vmarchaud 
- @blumamir 
- @Rauno56 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored:
  - https://github.com/open-telemetry/opentelemetry-js/pull/2893
  - https://github.com/open-telemetry/opentelemetry-js/pull/2871
  - https://github.com/open-telemetry/opentelemetry-js/pull/2820
  - https://github.com/open-telemetry/opentelemetry-js/pull/2734
  - https://github.com/open-telemetry/opentelemetry-js/pull/2681
  - https://github.com/open-telemetry/opentelemetry-js/pull/2733
  - https://github.com/open-telemetry/opentelemetry-js/pull/2685
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8848
  - https://github.com/open-telemetry/opentelemetry-python/pull/2533
  - https://github.com/open-telemetry/opentelemetry-specification/pull/2199
  - https://github.com/open-telemetry/opentelemetry-specification/pull/2210
  - https://github.com/open-telemetry/opentelemetry-proto-java/pull/4
  - https://github.com/open-telemetry/opentelemetry-proto-java/pull/3
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5310
- PRs reviewed:
  - https://github.com/open-telemetry/opentelemetry-js/pull/2725
  - https://github.com/open-telemetry/opentelemetry-js/pull/2686
  - https://github.com/open-telemetry/opentelemetry-js/pull/2634
  - https://github.com/open-telemetry/opentelemetry-js/pull/2743
  - https://github.com/open-telemetry/opentelemetry-js/pull/2695
  - https://github.com/open-telemetry/opentelemetry-js/pull/2829
  - https://github.com/open-telemetry/opentelemetry-js/pull/2821
  - https://github.com/open-telemetry/opentelemetry-js/pull/2889
  - https://github.com/open-telemetry/opentelemetry-js/pull/2890
- Issues responded to:
  - https://github.com/open-telemetry/opentelemetry-js/issues/2774
  - https://github.com/open-telemetry/opentelemetry-js/issues/2886
  - https://github.com/open-telemetry/opentelemetry-js/issues/2852
  - https://github.com/open-telemetry/opentelemetry-js/issues/2910
  - https://github.com/open-telemetry/opentelemetry-js/issues/2856
  - https://github.com/open-telemetry/opentelemetry-js/issues/2592
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7836
  - https://github.com/open-telemetry/opentelemetry-js/issues/2590
  - https://github.com/open-telemetry/opentelemetry-js/issues/2348
  - https://github.com/open-telemetry/opentelemetry-specification/issues/2186
  - https://github.com/open-telemetry/opentelemetry-js/issues/1812
  - https://github.com/open-telemetry/opentelemetry-js/issues/2591
- SIG projects I am involved with:
  - JavaScript
  - Specification

**Comment by Rauno56** [comment]
I support!

**Comment by vmarchaud** [comment]
I support !

**Comment by blumamir** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @pichlermarc! Invite sent
