### ISSUE TITLE
Support needed in open telemetry..

### ISSUE THREAD

**Issue by vijaypr1** [open-telemetry/community#1042]
Hi Team,
I m new to open telemetry and trying to export telemetry data to Apache Skywalking with otel collector..
Facing issue as described below::::
Was advised to check in open-telemetry forums, as below..
Pls. scroll down for error trace..
https://github.com/apache/skywalking/discussions/8938
=====
Hi Team,
I m new to Skywalking and currently exploring the same..
I m facing issue while exporting vm node metrics to sky walking for viewing... the screen is blank under VM section and none of the metrics are showing up
I have used skywalking 8.4 and has followed ::::: https://skywalking.apache.org/blog/2021-02-07-infrastructure-monitoring/
I have created the VM instance in GCP
Insalled and started node exporter -- ./node_exporter (the metrics are showing up correctly)
Downloaded Skywalking from distribution and started using startup.sh script under bin dir
All the node agent, skywalking OAP, otel exporter exists in the same vm..

As per the instruction i have created docker-compose.yaml, otel-collector-config.yaml, as given in the instructions and while running docker compose up, it is running but below error is noticed:::

otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:144
otel-collector_1 | 2022-04-23T11:45:41.047Z error exporterhelper/queued_retry.go:176 Exporting failed. Dropping data. Try enabling sending_queue to survive temporary failures. {"kind": "exporter", "name": "opencensus", "dropped_items": 5}
otel-collector_1 | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
otel-collector_1 | go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:176
otel-collector_1 | go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsExporter.func2
otel-collector_1 | go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:97
otel-collector_1 | go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeMetricsFunc.ConsumeMetrics
otel-collector_1 | go.opentelemetry.io/collector/consumer/consumerhelper/metrics.go:29
otel-collector_1 | go.opentelemetry.io/collector/service/internal/fanoutconsumer.metricsConsumer.ConsumeMetrics
otel-collector_1 | go.opentelemetry.io/collector/service/internal/fanoutconsumer/consumer.go:51
otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetrics).export
otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:285
otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:183
otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
otel-collector_1 | go.opentelemetry.io/collector/processor/batchprocessor/batch_processor.go:144
otel-collector_1 | 2022-04-23T11:45:41.047Z warn batchprocessor/batch_processor.go:184 Sender failed {"kind": "processor", "name": "batch", "error": "EOF"}

**Comment by codeboten** [comment]
Hi @vijaypr1, please open this issue in the OpenTelemetry Collector Contrib repository: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues

**Comment by tigrannajaryan** [comment]
Closing. Please open a bug at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues and provide the relevant details.
