### ISSUE TITLE
Feedback Requested - OpenTelemetry Community End User Surveys

### ISSUE THREAD

**Issue by sharrmander** [open-telemetry/community#1045]
The End User working group has created four surveys for the community and we are requesting feedback from the community on their content over the next two weeks (intend to publish surveys by May 13th ahead of KubeCon EU). Survey question content is contained in a google document for ease of collaboration during this feedback period. Links below, please provide your thoughts on the content -  but especially feedback on the questions and proposed distribution channels for the surveys too.

All surveys will be conducted via Google Forms and responses not containing PII will be made available for the community. The End User working group will analyze survey results on a recurring basis and make the insights gained known to the community. 

Thanks in advance for collaborating on this effort to bring your SIGs end user feedback!

### [Survey 1: Quarterly Feedback Survey](https://docs.google.com/document/d/1oExvgGD2DTqQ4PcMVOVFW-obMn5jkUQFZQ0UhB8U6SY/edit#)
This survey captures feedback on a regular recurring basis. This feedback is intended to provide high level metrics to trend over time on key aspects of project health and end-user satisfaction.

### [Survey 2: Installation and Configuration Survey](https://docs.google.com/document/d/1LbThIq7RWKuEEONaEpXHCyX-q0pJ8WUVUSd0Tz6rUEU/edit)
This survey captures feedback soon after an end-user installs or configures OpenTelemetry. This feedback is intended to help SIGs understand end-user challenges with adopting OTel. In the next iteration of this survey, we’d like to add SIG specific questions. There is a section of this survey document to add questions from your respective SIGs for inclusion. 

### [Survey 3: General Fast Feedback Survey](https://docs.google.com/document/d/1h7YA9s5giIBZ7gdomWErEhV6sZupEg0CXJwhvIqkgSg/edit) 

This survey is intended to capture feedback from end-users who either don’t know where to put their feedback or they work for a company which dissuades them from engaging in the open. This feedback, like all community survey data, is still transparent to the community, but it can be submitted anonymously. 

### [Survey 4: Vendor Mediated Survey](https://docs.google.com/document/d/1569kihrBHeQh9oxyzOLn1aliENNrDScZ3ofwB1bTm0U/edit)

This survey is intended to be submitted by back-end vendors who support OpenTelemetry, essentially funneling feedback to the community on behalf of their customers. This survey is intended to capture feedback that occurs in a vendor-context but doesn’t have a natural pathway to become visible to the community.

**Comment by trask** [comment]
hi @sharrmander! if you are still looking for visibility on this, it may help to raise it as a topic in the weekly maintainers meeting on Mondays at 9am

**Comment by codeboten** [comment]
Should this issue be closed or is there still work needed to move this along?

**Comment by svrnm** [comment]
with the end user SIG having their own repo and having run surveys already I agree that we can close this. if this is incorrect or if this should be moved to the enduser sig repo, please let me know.
