### ISSUE TITLE
REQUEST: New membership for tobiasstadler

### ISSUE THREAD

**Issue by tobiasstadler** [open-telemetry/community#1052]
### GitHub Username

@tobiasstadler

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @seemk
- @lalitb

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- open-telemetry/opentelemetry-cpp-contrib#123
- open-telemetry/opentelemetry-cpp-contrib#106
- open-telemetry/opentelemetry-cpp-contrib#98
- open-telemetry/opentelemetry-cpp-contrib#86
- open-telemetry/opentelemetry-cpp-contrib#80
- open-telemetry/opentelemetry-cpp-contrib#77
- open-telemetry/opentelemetry-cpp-contrib#76
- open-telemetry/opentelemetry-cpp-contrib#75
- open-telemetry/opentelemetry-cpp-contrib#74
- open-telemetry/opentelemetry-cpp-contrib#73
- open-telemetry/opentelemetry-cpp-contrib#72
- open-telemetry/opentelemetry-cpp-contrib#71
- open-telemetry/opentelemetry-cpp-contrib#61
- open-telemetry/opentelemetry-cpp-contrib#60
- open-telemetry/opentelemetry-cpp-contrib#59
- open-telemetry/opentelemetry-cpp-contrib#58
- open-telemetry/opentelemetry-cpp-contrib#57
- open-telemetry/opentelemetry-cpp-contrib#56

**Comment by seemk** [comment]
I support :slightly_smiling_face: Thanks for all the help!

**Comment by lalitb** [comment]
I support.

**Comment by arminru** [comment]
Welcome, @tobiasstadler! Invite sent.

**Comment by tobiasstadler** [comment]
Thank You!
