### ISSUE TITLE
REQUEST: New membership for @cartermp

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/community#1057]
### GitHub Username

@cartermp

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@chalin
@austinlparker 

### List of contributions to the OpenTelemetry project

PRs authored:
https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Acartermp
https://github.com/open-telemetry/opentelemetry-go/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Acartermp
https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Acartermp+is%3Amerged

Issues assigned: https://github.com/open-telemetry/opentelemetry.io/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Acartermp+

SIG: comms

**Comment by chalin** [comment]
I support.

(Thanks for the reminder re. the guidelines, @arminru!)

**Comment by austinlparker** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @cartermp!
