### ISSUE TITLE
REQUEST: New membership for @JaredTan95

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/community#1059]
### GitHub Username

@JaredTan95 

https://github.com/JaredTan95/

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tensorchen 
- @jpkrohling 
- @dmitryax

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+author%3AJaredTan95+is%3Aclosed
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls/JaredTan95
       - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6984
       - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7064
       - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7829
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7953
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8107
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8256
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8549
      - https://github.com/open-telemetry/opentelemetry-collector-releases/pull/101
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9406
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9418
      - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10180
- Issues responded to
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+assignee%3AJaredTan95+is%3Aclosed 
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+author%3AJaredTan95+is%3Aclosed

**Comment by dmitryax** [comment]
I support the request

**Comment by tensorchen** [comment]
I support the request

**Comment by bogdandrutu** [comment]
Invite sent

**Comment by JaredTan95** [comment]
> Invite sent

Thank you for your support and invitation. :-)
