### ISSUE TITLE
OT Slack invitation is no longer active

### ISSUE THREAD

**Issue by mechie** [open-telemetry/community#1061]
[The README](https://github.com/open-telemetry/community/blob/main/README.md#discussions) links to http://slack.cncf.io/ for joining the OT Slack. Unfortunately, it looks as though the invitation has been revoked or expired:
![a screenshot of slack.cncf.io. It reads "This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link."](https://user-images.githubusercontent.com/5685795/169562935-4b3071ff-dd18-45f8-b357-1a240605b017.png)

I'm interested in joining the Slack, could the invitation link be fixed? 

This shortened URL is also listed on [opentelemetry.io/community](https://opentelemetry.io/community/) ([source](https://github.com/open-telemetry/opentelemetry.io/blob/253da40aeab32fb4e9b2a6ac155fda223b4669ea/config.yaml#L97)), in case the resolution is to use some other link.

**Comment by arminru** [comment]
Hey @mechie!
I just accessed http://slack.cncf.io/ and it forwarded me to `https://cloud-native.slack.com/join/shared_invite/<...>` where I would be able to sign up using Email or some ID providers.
Can you try again please?

**Comment by mechie** [comment]
Thanks @arminru, it's working now! Guess it was a transient issue or something was updated, but either way glad it's resolved :grin:

**Comment by brianweet** [comment]
Doesn't seem to work for me:
https://slack.cncf.io redirects to `https://join.slack.com/t/clohttps://join.slack.com/t/cloud-native/shared_invite/zt-19ralsdu8-IQ8csDRCIQ6vbBfFJbB2yQud-native/shared_invite/zt-19ralsdu8-IQ8csDRCIQ6vbBfFJbB2yQ`
Even after removing the first part it doesn't work: https://join.slack.com/t/cloud-native/shared_invite/zt-19ralsdu8-IQ8csDRCIQ6vbBfFJbB2yQud-native/shared_invite/zt-19ralsdu8-IQ8csDRCIQ6vbBfFJbB2yQ

![image](https://user-images.githubusercontent.com/1263284/170021743-d3ff65ee-a1fe-4a99-b18c-cc698518121b.png)
