### ISSUE TITLE
REQUEST: New membership for @yuriolisa

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/community#1066]
### GitHub Username

@yuriolisa

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pavolloffay 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Fix Missing parameter on labels function (https://github.com/open-telemetry/opentelemetry-operator/pull/809)
- Check exposed svc ports (https://github.com/open-telemetry/opentelemetry-operator/pull/778)
- Storing upgrade status into events (https://github.com/open-telemetry/opentelemetry-operator/pull/707)
- Release v0.50.0 (https://github.com/open-telemetry/opentelemetry-operator/pull/850)

**Comment by pavolloffay** [comment]
I am happy to sponsor this membership.

**Comment by jpkrohling** [comment]
+1 from me

**Comment by arminru** [comment]
Invite sent and added to https://github.com/orgs/open-telemetry/teams/operator-approvers/members as per https://github.com/open-telemetry/opentelemetry-operator/issues/870.
Welcome @yuriolisa!
