### ISSUE TITLE
REQUEST: Create a new repository opentelemetry-sandbox-web-js

### ISSUE THREAD

**Issue by MSNev** [open-telemetry/community#1068]
### Affected Repository

Proposed name: opentelemetry-sandbox-web-js
https://github.com/open-telemetry/opentelemetry-sandbox-web-js

Also open to different name as long as the name highlights the temporary / non-production nature of any code generated from this repo.

### Requested changes

Creation of new repo

Default Admins should include 
- Existing opentelemetry-js repo admins
- At least @tedsuo, @dyladan 
- @MSNev (me) -- if appropriate

This repo / admins do not need any publishing permissions at this point, that can be requested as a follow up if/when necessary.

### Purpose

This is a request to have a new repository for creating non-production level experimental Web JS packages, this will include exploring refactoring options of the existing opentelemetry-js and it's api packages using specific optimizations to running in a browser environment, this will not include node support as it will only be focused on client runtime environments.

Reiterating that this is intended to be for experimental generation (and publishing) of short-lived (will not be long term maintained) packages purposes only and code will be explicitly not supported for production uses. Documentation on the repo will also call this out.

Why a new repo and not a folder or fork?

- This repo will need a different set of permissions to that of the primary repo's (eg. Triagers, Approvers and Maintainers of this repo should not have the same privs' in the primary repo's).
- Keep a link to the opentelemetry project rather than using 3rd party namespace / environment
- We will likely need to publish "sandbox" packages so they can be more easily consumed for testing against real world developer environments.

The ultimate outcome of experiments from this repo will be to
- Identify improvements that are contributed back to the production repo's
- Identify that the web requires it's own unique production repo (if it can't be housed in the existing JS ones)
- This repo will be either archived, contents remove or deleted.

### Expected Duration

I would expect that we should achieve the stated goals for the creation of this repo in 6-12 months

### Repository Maintainers

- @tedsuo, @dyladan 
- @MSNev (me), @martinkuba 

Suggested group name
- @open-telemetry/sandbox-web-js-maintainers

**Comment by yurishkuro** [comment]
Done https://github.com/open-telemetry/opentelemetry-sandbox-web-js/
