### ISSUE TITLE
Request: new approvers team

### ISSUE THREAD

**Issue by bryannaegele** [open-telemetry/community#1069]
We'd like to add an `erlang-contrib-approvers` child team to the `erlang-approvers` team. Each of the team members are not currently members of the org (applications incoming). Do we need to get them approved before creating the team or can it be created with zero members?

**Comment by SergeyKanzhelev** [comment]
as a child or as a parent? I think child means less members, I understand you want all `erlang-approvers` plus more members? Team can be created any time you want and`erlang-maintainers` will be set as team owners to add/remove approvers

**Comment by bryannaegele** [comment]
Correct, as a child. We're trying to give the contrib package maintainers permission to continue to manage their projects through this + codeowners but we can't set outside contributors as codeowners.

**Comment by SergeyKanzhelev** [comment]
discussed offline and done. https://github.com/orgs/open-telemetry/teams/erlang-contrib-approvers/
