### ISSUE TITLE
Assignees field restriction

### ISSUE THREAD

**Issue by thomashchan1** [open-telemetry/community#107]
Can we make sure the Assignees field can accommodate any contributor, and not restricted to only a selected few?

**Comment by SergeyKanzhelev** [comment]
you can assign to any member of Open-Telemetry organization. If you are not part of an organization yet, you can just mention in comments that you are taking the issue. This document describes how to become a member: https://github.com/open-telemetry/community/blob/master/community-membership.md

**Comment by tedsuo** [comment]
@SergeyKanzhelev are members the only ones allowed to pick up work? I thought we had an open project, where anyone was allowed to make PRs. It is not effective to have a process which only allows members to be assigned issues.

**Comment by SergeyKanzhelev** [comment]
@tedsuo it's not a setting we can flip. It's a GitHub limitation. Anybody can mention themselves and declare that they are picking this work. See https://github.com/open-telemetry/community/blob/master/CONTRIBUTING.md#issue-assignment-in-github

**Comment by thomashchan1** [comment]
@SergeyKanzhelev while this is a valid temporary workaround, to promote a truly open community, it's best to allow contributors to be able to assign themselves to issues/PRs without us being the traffic cop. And we cannot afford to be the bottleneck anyway. We probably want to continue to find solution to this issue, if appropriate.

**Comment by SergeyKanzhelev** [comment]
@thomashchan1 please suggest tools you think we can use to automate this. Which specific repository are you referring to? Perhaps this issue can be resolved by asking maintainers and approvers for the repo be more responsive.

**Comment by thomashchan1** [comment]
Thanks, @SergeyKanzhelev, I don't have tools in mind that can automate this. Believe this restriction applies to all repos. Asking maintainers and approvers to be more responsive is a workaround, but not a solution. That will also position them as bottleneck. @bogdandrutu took an action item today to help take a look at options. Thanks in advance.
