### ISSUE TITLE
REQUEST: New membership for @indrekj

### ISSUE THREAD

**Issue by indrekj** [open-telemetry/community#1070]
### GitHub Username

@indrekj

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bryannaegele
- @tsloughter 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- opentelemetry-erlang-contrib - Oban support ([commits](https://github.com/open-telemetry/opentelemetry-erlang-contrib/commits?author=indrekj))
- opentelemetry-erlang - Different fixes and improvements ([commits](https://github.com/open-telemetry/opentelemetry-erlang/commits?author=indrekj))
- opentelemetry-ruby - Que support and smaller contributions ([commits](https://github.com/open-telemetry/opentelemetry-ruby/commits?author=indrekj))
- Created Elixir [opentelemetry_function](https://github.com/salemove/opentelemetry_function) library
- Created Erlang/Elixir [opentelemetry_logger_metadata](https://github.com/salemove/opentelemetry_logger_metadata) library

**Comment by bryannaegele** [comment]
I support

**Comment by tsloughter** [comment]
I support as well

**Comment by SergeyKanzhelev** [comment]
Welcome, @indrekj! invite sent
