### ISSUE TITLE
REQUEST: New membership for haddasbronfman

### ISSUE THREAD

**Issue by haddasbronfman** [open-telemetry/community#1071]
### GitHub Username

e.g. (at)example_user

### Requirements

- [ v] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [ v] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ v] I have subscribed to the #otel-js & #otel-collector(https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ v] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ v] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ v] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @blumamir 
- @dyladan 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/778
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/865
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/896
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/897
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1015

**Comment by blumamir** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @haddasbronfman! Invite sent.

**Comment by haddasbronfman** [comment]
thanks!
