### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-demo-webstore

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1073]
### Affected Repository

[opentelemetry-demo-webstore](https://github.com/open-telemetry/opentelemetry-demo-webstore)

### Requested changes

Add `otel` username/password for Docker Hub as secrets to this repository.

### Purpose

We will be publishing container images to the OpenTelemetry Docker Hub account.
 
### Expected Duration

Forever

### Repository Maintainers

@open-telemetry/demo-webstore-maintainers

**Comment by arminru** [comment]
We have a new bot user https://hub.docker.com/u/otelbot now which is a member of the https://hub.docker.com/u/otel org:
https://github.com/open-telemetry/community/pull/1086 (Thanks, @tigrannajaryan!)

@austinlparker would an API token (https://docs.docker.com/docker-hub/access-tokens/) work for you as well or does the workflow you have in mind require using username+password? You would be able to just use the token instead of the password on the Docker CLI once set up as a secret in the repo.

**Comment by tigrannajaryan** [comment]
>@austinlparker would an API token (https://docs.docker.com/docker-hub/access-tokens/) work for you as well or does the workflow you have in mind require using username+password

Docker access token are essentially secondary passwords. The work in conjunction with the username. Just let me know where you need to use the username+password and I will generate a new token just for you and will input it where you need.

**Comment by austinlparker** [comment]
> >@austinlparker would an API token (https://docs.docker.com/docker-hub/access-tokens/) work for you as well or does the workflow you have in mind require using username+password
> 
> 
> 
> Docker access token are essentially secondary passwords. The work in conjunction with the username. Just let me know where you need to use the username+password and I will generate a new token just for you and will input it where you need.

Right now this is our release config -

```
registry: ghcr.io
username: ${{ github.repository_owner }}
password: ${{ secrets.GITHUB_TOKEN }}
```

So maybe add them as DOCKER_HUB_USERNAME and DOCKER_HUB_PASSWORD as secrets? Would it be possible to have it added as an org-wide secret, to avoid needing to repeat this for other repositories that wish to have access to Docker Hub?

**Comment by austinlparker** [comment]
This has been completed and is working -- thanks!
