### ISSUE TITLE
REQUEST: New membership for puckpuck

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/community#1075]
### GitHub Username

@puckpuck

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cartersocha 
- @austinlparker 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Regular participant and contributor to the Community Webstore Demo SIG
- Community Webstore Demo PR: https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/82
- Community Webstore Demo PR: https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/97
- Regular participant in the #otel-community-demo CNCF Slack Channel https://cloud-native.slack.com/archives/C03B4CWV4DA

**Comment by cartersocha** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @puckpuck! Invite sent
