### ISSUE TITLE
REQUEST: New membership for PeterF778

### ISSUE THREAD

**Issue by PeterF778** [open-telemetry/community#1077]
### GitHub Username

@PeterF778

### Requirements

- [ X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jack-berg
- @trask

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed:
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/352
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/226
https://github.com/open-telemetry/oteps/pull/168
https://github.com/open-telemetry/oteps/pull/175
https://github.com/open-telemetry/opentelemetry-specification/pull/2047

- SIG projects I am involved with
Consistent Sampling

**Comment by trask** [comment]
I support!

**Comment by jack-berg** [comment]
I support
