### ISSUE TITLE
REQUEST: New membership for osherv

### ISSUE THREAD

**Issue by osherv** [open-telemetry/community#1080]
### GitHub Username
@osherv

### Requirements

- [ V] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [ V] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ V] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ V] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ V] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ V] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@trask 
@blumamir 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4446
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4650
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/869

**Comment by blumamir** [comment]
I support

**Comment by trask** [comment]
I support!

**Comment by SergeyKanzhelev** [comment]
Welcome, @osherv! Invite sent
