### ISSUE TITLE
REQUEST: New membership for @gbbr

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/community#1081]
### GitHub Username

@gbbr

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi 
- @codeboten 
- @bogdandrutu 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- List of all PRs authored [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Agbbr+). List of all PRs involved in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+gbbr+).
- Issues I was involved in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+gbbr+).
- Planning to get involved with Collector SIG at first, maybe Go SDK too.

**Comment by bogdandrutu** [comment]
+1

**Comment by codeboten** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @gbbr! Invite sent

**Comment by mx-psi** [comment]
+1, late to the party but welcome Gabriel :)
