### ISSUE TITLE
REQUEST: New membership for @Frapschen

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/community#1082]
### GitHub Username

@Frapschen

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @JaredTan95 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10361
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11031
  - https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/138
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11049
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10922 
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls/Frapschen
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/126
  - https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/66
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10116

**Comment by djaglowski** [comment]
@Frapschen, I support. However, you will need to find a second sponsor who is an approver or maintainer.

**Comment by JaredTan95** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
@Frapschen thank you for submitting the request. Please find one more sponsor who meets the requirement and we will be happy to welcome you as a member.

**Comment by Frapschen** [comment]
OK， I will try

**Comment by TylerHelmuth** [comment]
@SergeyKanzhelev @Frapschen I support

**Comment by Frapschen** [comment]
> @SergeyKanzhelev @Frapschen I support

thx :)

**Comment by Frapschen** [comment]
> @Frapschen, I support. However, you will need to find a second sponsor who is an approver or maintainer.

thx

**Comment by arminru** [comment]
Welcome, @Frapschen! Invite sent.
