### ISSUE TITLE
REQUEST: New membership for @gouthamve

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/community#1087]
### GitHub Username

@gouthamve

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dashpole
- @Aneurysm9 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

I've also coordinated with various stakeholders to write the [Sparse Histograms in Prometheus and OpenTelemetry](https://docs.google.com/document/d/11z8hc_T4RHPHaXuWiETxGa81Ix89dBV5jh9byh9ySgE/edit#heading=h.i590hckffjkm) doc that is useful for various discussions around Histogram compatibility.

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7115
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7240
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8780
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9115
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9244
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9253
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9266
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9718
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11034

- Issues responded to

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4971
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4973
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4982
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4985
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4986
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5011
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5663
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5757
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5842
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6425
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6722
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7180
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7380
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7831
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8355
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8365
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8810
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9119
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9124
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9986
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10115

- SIG projects I am involved with
Prometheus WG

**Comment by dashpole** [comment]
"I support"

**Comment by jpkrohling** [comment]
I support

**Comment by arminru** [comment]
Welcome, @gouthamve! Invite sent.
