### ISSUE TITLE
Trademark name usage in ObservIQ distro

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#1093]
I noticed https://github.com/observIQ/observiq-otel-collector has named their version of the OpenTelemetry Collector as the observIQ OpenTelemetry Collector. From a project pov, this is an incorrect use for naming the ObserveIQ distro. Please see LF/CNCF trademark naming guidelines at https://www.linuxfoundation.org/trademark-usage/ 

cc: @open-telemetry/governance-committee

**Comment by djaglowski** [comment]
I've taken note and passed this along to the company. I'm certain no misuse was intended.

**Comment by dyladan** [comment]
Perhaps general guidance on this can be mentioned in whatever guide documentation we have for creating collector distributions?
