### ISSUE TITLE
Trademark name usage in SumoLogic distro for OTel

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#1096]
Noting https://github.com/SumoLogic/sumologic-otel-collector has named their version of the OpenTelemetry Collector as the SumoLogic OT Distro Collector. The distro name and docs at https://help.sumologic.com/03Send-Data/Sumo_Logic_OpenTelemetry_Distribution should be updated to be in compliance with naming conventions in the LF/CNCF trademark naming guidelines at https://www.linuxfoundation.org/trademark-usage/

cc: https://github.com/orgs/open-telemetry/teams/governance-committee

cc: @kumoroku

**Comment by kumoroku** [comment]
thanks for flagging. just to get a quick sense: in light of a quick grok of the trademark usage page along with other vendor's naming (`AWS Distro for OpenTelemetry` as well as `Splunk Distribution of OpenTelemetry Collector`) would `Sumo Logic Distribution of OpenTelemetry` be compliant?

**Comment by dyladan** [comment]
I think so. The example given for a correct use is <your product name> for <The Linux Foundation mark> which seems to be applicable to the example you just gave.

**Comment by alolita** [comment]
IANAL but the format "<company name> Distro for OpenTelemetry" is acceptable by the CNCF. 

@caniszczyk feel free to chime in.

**Comment by perk-sumo** [comment]
Thank you for bringing that to our attention, I'm working on fixing that.
We'll use the following name: `Sumo Logic Distribution for OpenTelemetry Collector`

**Comment by perk-sumo** [comment]
Name in the Github repository has been changed.
Also our help page has been changed as well: https://help.sumologic.com/03Send-Data/Sumo_Logic_Distribution_for_OpenTelemetry

@alolita I hope that resolves the issue at hand?

**Comment by trask** [comment]
thanks @perk-sumo!
