### ISSUE TITLE
REQUEST: Disband log-collection-* teams

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/community#1099]
The [opentelemetry-log-collection](https://github.com/open-telemetry/opentelemetry-log-collection) codebase has been copied into [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) and the former repo has been archived. The `log-collection-*` teams are no longer needed.

### Requested changes

Delete the following teams:
- @open-telemetry/log-collection-triagers 
- @open-telemetry/log-collection-approvers 
- @open-telemetry/log-collection-maintainers

**Comment by arminru** [comment]
Thanks for thinking about the cleanup, I deleted the teams as requested.
