### ISSUE TITLE
REQUEST: New membership for @hekike

### ISSUE THREAD

**Issue by hekike** [open-telemetry/community#110]
### GitHub Username

`hekike`

### Organization you are requesting membership in

(at)open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mayurkale22 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-node/pull/31
- https://github.com/open-telemetry/opentelemetry-node/issues/4
- https://github.com/open-telemetry/opentelemetry-node/issues/5
- https://github.com/open-telemetry/opentelemetry-node/issues/7
- https://github.com/open-telemetry/opentelemetry-node/issues/9
- https://github.com/open-telemetry/opentelemetry-node/issues/14
- https://github.com/open-telemetry/opentelemetry-node/issues/15
- opencensus-node SIG meetings

**Comment by SergeyKanzhelev** [comment]
welcome!

**Comment by hekike** [comment]
Thanks!
