### ISSUE TITLE
REQUEST: New membership for my-git9

### ISSUE THREAD

**Issue by my-git9** [open-telemetry/community#1101]
### GitHub Username
@my-git9

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi 
- @dmitryax 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12081
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11890
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11840
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11778
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11777
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11556
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11529
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11464
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11421
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11164
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11137
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11138
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11140
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11141
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11142
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11143
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11153
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11161
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11162
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10979
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10116
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9749
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10466
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10975

**Comment by dmitryax** [comment]
I support

**Comment by mx-psi** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome @my-git9!

**Comment by my-git9** [comment]
> Invite sent. Welcome @my-git9!

Thanks
