### ISSUE TITLE
REQUEST: New membership for rquedas

### ISSUE THREAD

**Issue by rquedas** [open-telemetry/community#1103]
### GitHub Username

@rquedas

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @austinlparker 
- @cartermp

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry.io/pull/1277
- https://github.com/open-telemetry/opentelemetry.io/pull/1288
- https://github.com/open-telemetry/opentelemetry.io/pull/1506

**Comment by cartermp** [comment]
I endorse!

**Comment by austinlparker** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @rquedas! Invite sent

**Comment by rquedas** [comment]
Thank you!
