### ISSUE TITLE
REQUEST: New membership for mottibec

### ISSUE THREAD

**Issue by mottibec** [open-telemetry/community#1104]
### GitHub Username
@mottibec

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @blumamir 
- @jpkrohling 

#### PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6910
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8114
- https://github.com/open-telemetry/opentelemetry-js/pull/2224
- https://github.com/open-telemetry/opentelemetry.io/pull/597

**Comment by jpkrohling** [comment]
I support

**Comment by blumamir** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @mottibec! Invite sent
