### ISSUE TITLE
REQUEST: New membership for @jeanbisutti

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/community#1108]
### GitHub Username

@jeanbisutti

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @mateuszrzeszutek 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored
  - [Runtime attachment additions - opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/354)
  - [Fix "URI is not hierarchical" during runtime attachment - opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/359) 
  - [Fix "Class path contains multiple SLF4J bindings" during runtime attachment - opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/380)
  - [Improve exception handling and documentation of runtime attachment - opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/388)
  - [sun.net.www.protocol.http.HttpURLConnection.getOutputStream0() will change httpUrlConnection's method type  - opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6053)
  - [Enable logging in the benchmark overhead  - opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6252)
  - [Add test on work stealing pool - opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6315)
 - Issues responded to
   - [sun.net.www.protocol.http.HttpURLConnection.getOutputStream0() will change httpUrlConnection's method type - opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4597)

**Comment by mateuszrzeszutek** [comment]
I support ✅

**Comment by trask** [comment]
I support!
