### ISSUE TITLE
REQUEST: New membership for boostchicken

### ISSUE THREAD

**Issue by boostchicken** [open-telemetry/community#1109]
### GitHub Username

@boostchicken

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Aneurysm9 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12324
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12179
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12327
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12328
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6341
- Issues responded to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12206
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12329
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5838
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10887
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6883

**Comment by jpkrohling** [comment]
I support

**Comment by Aneurysm9** [comment]
I support

**Comment by NareshChinnusamy** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @boostchicken! Invite sent
