### ISSUE TITLE
REQUEST: create ruby-contrib-approvers team

### ISSUE THREAD

**Issue by mwear** [open-telemetry/community#1111]
### Affected Repository
[https://github.com/open-telemetry/opentelemetry-ruby-contrib](https://github.com/open-telemetry/opentelemetry-ruby-contrib)

### Requested changes

We would like an @open-telemetry/ruby-contrib-approvers team created

### Purpose

This will allow us to manage approvers separately between the core and contrib repos.
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/ruby-contrib-maintainers

**Comment by mwear** [comment]
Thanks @tigrannajaryan! I don't appear to have permissions to add members. Can we make @ruby-contrib-maintainers a child team and add @robbkidd to @ruby-contrib-approvers?

**Comment by tigrannajaryan** [comment]
Done. You probably also need to add Approvers section to https://github.com/open-telemetry/opentelemetry-ruby-contrib#contributing

**Comment by ahayworth** [comment]
@tigrannajaryan I believe it is good to close. 👍 Thanks again! 😄

**Comment by plantfansam** [comment]
Thanks so much @tigrannajaryan
