### ISSUE TITLE
Change new contributor workflow settings for Rust 

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/community#1112]
Similar to #1023 , we'd like to change the [setting of approving workflow runs from public forks](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories) to 
```
Require approval for first-time contributors who are new to GitHub
```
to help new contributors.

Since we don't have access, can someone from TC help out? Thanks
cc @open-telemetry/rust-approvers

**Comment by arminru** [comment]
Hey @TommyCpp! I changed the setting as requested so we can give it a try.
Please keep an eye on it and let us know if you see any suspicious activity. Thank you.
