### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-demo-webstore

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1115]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-demo-webstore

### Requested changes

- Rename repository to `opentelemetry-demo`
- Rename approver and maintainer teams to `demo-approvers` and `demo-maintainers` respectively.
 
### Purpose

We would like to align the various namespaces of OpenTelemetry Demo artifacts, helm charts, and other published ephemera. The 'webstore' suffix is unneeded and causes confusion when our published images/artifacts use the generic 'demo' namespace.
 
### Repository Maintainers

- @open-telemetry/demo-webstore-maintainers

**Comment by reyang** [comment]
> ### Requested changes
> * Rename repository to `opentelemetry-demo`
> * Rename approver and maintainer teams to `demo-approvers` and `demo-maintainers` respectively.

Both are done. Please make corresponding changes in the [Community README.md](https://github.com/open-telemetry/community/blob/main/README.md) and other docs.

**Comment by arminru** [comment]
@austinlparker Please note that we might need to adapt the permissions for the API token used to push to Docker Hub. I think their scope is limited to certain repository/image names. If pushing doesn't work any more after changing the name please open another issue here.

cc @tigrannajaryan
