### ISSUE TITLE
REQUEST: New membership for @rochdev

### ISSUE THREAD

**Issue by rochdev** [open-telemetry/community#112]
### GitHub Username

@rochdev

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mayurkale22 
- @tylerbenson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-node/pull/2
  - https://github.com/open-telemetry/opentelemetry-node/pull/25
  - https://github.com/open-telemetry/opentelemetry-node/pull/32
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-node/pull/3
  - https://github.com/open-telemetry/opentelemetry-node/pull/4
  - https://github.com/open-telemetry/opentelemetry-node/pull/6
- SIG projects I am involved with
  - [opentelemetry-node](https://github.com/open-telemetry/opentelemetry-node)

**Comment by tylerbenson** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
@rochdev, welcome!
