### ISSUE TITLE
REQUEST: New membership for @jaronoff97

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/community#1120]
### GitHub Username

@jaronoff97

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @codeboten 
- @Aneurysm9 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/231
https://github.com/open-telemetry/opentelemetry-operator/pull/930
https://github.com/open-telemetry/opentelemetry-operator/pull/836
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1880
- PRs reviewed
https://github.com/open-telemetry/opentelemetry-operator/pull/653
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12586
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9416
- Issues responded to
https://github.com/open-telemetry/opentelemetry-operator/issues/998
https://github.com/open-telemetry/opentelemetry-operator/issues/985
- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-operator
https://github.com/open-telemetry/opentelemetry-helm-charts

**Comment by codeboten** [comment]
I approve 👍🏻

**Comment by Aneurysm9** [comment]
I approve :shipit:

**Comment by arminru** [comment]
Invite sent! Welcome, @jaronoff97!
