### ISSUE TITLE
REQUEST: New membership for @marcalff

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/community#1122]
### GitHub Username

@marcalff

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lalitb 
- @esigo 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored

  - open-telemetry/opentelemetry-cpp#1439

  - open-telemetry/opentelemetry-cpp#1441

  - open-telemetry/opentelemetry-cpp#1446

  - open-telemetry/opentelemetry-cpp#1462

  - open-telemetry/opentelemetry-cpp#1471

  - open-telemetry/opentelemetry-cpp#1491

  - open-telemetry/opentelemetry-cpp#1497

  - open-telemetry/opentelemetry-cpp#1524

  - open-telemetry/opentelemetry-cpp#1525

- PRs reviewed

  - open-telemetry/opentelemetry-cpp#1388

  - open-telemetry/opentelemetry-cpp#1408

  - open-telemetry/opentelemetry-cpp#1420

  - open-telemetry/opentelemetry-cpp#1458

  - open-telemetry/opentelemetry-cpp#1481

  - open-telemetry/opentelemetry-cpp#1487

  - open-telemetry/opentelemetry-cpp#1496

- Issues responded to

  - open-telemetry/opentelemetry-cpp#1520

  - open-telemetry/opentelemetry-cpp#1448

- SIG projects I am involved with

  - [Opentelemetry-cpp](https://github.com/open-telemetry/opentelemetry-cpp)

  - Attend the community meeting for [opentelemetry-cpp](https://docs.google.com/document/d/1i1E4-_y4uJ083lCutKGDhkpi3n4_e774SBLi9hPLocw/edit?usp=sharing) since June 29, 2022.

**Comment by lalitb** [comment]
I support.

**Comment by esigo** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @marcalff!
