### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-sandbox-web-js

### ISSUE THREAD

**Issue by MSNev** [open-telemetry/community#1129]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-sandbox-web-js

### Requested changes

Please give ma 'Admin' permissions to `@MSNev`

### Purpose

We have an automated workflow that needs access to a BOT_TOKEN (which doesn't currently exist in this repo), I have the token and need to be able to add it.
 
### Expected Duration

Should be about 1-2 weeks to validate the token and workflow is functional, will comment again on this issue once we are done so the permissions can be reverted.

### Repository Maintainers

- @open-telemetry/sandbox-web-js-maintainers

**Comment by arminru** [comment]
Permissions granted. Please let us know on here once you are done.

**Comment by arminru** [comment]
@MSNev ping 🙂

**Comment by MSNev** [comment]
Hey, while I've added the token already we are waiting for clarification on merging from the master branches which have expired CLA values (which is blocking the merging PR's that include the previously signed CLA's).

This occurs when the person who signed the CLA with a corp credentials move companies and removes that email from their github account. This (may) require admin privs to be able to bypass the CLA check for these initial merges. Hence why I've not replied yet to remove the admin privs

**Comment by MSNev** [comment]
@arminru CLA Issue is now resolved and I no longer need admin privileges.

**Comment by arminru** [comment]
Great, thank you.
I verified that the CLA branch protection is in place as required by the CNCF and revoked the admin permissions.
