### ISSUE TITLE
Can we remove the requirement for license headers?

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#113]
The license should already be defined at the root of each project, does each file really need such documentation as well?

Removing the headers would also make it much less hassle to update the license and copyright date when needed, since it would only need to be done in a single place.

**Comment by bogdandrutu** [comment]
I am not a lawyer so I cannot answer this question :(. I will ask around.

**Comment by SergeyKanzhelev** [comment]
here is quote from the license:

https://github.com/open-telemetry/community/blob/b6ff37b6b43236c0af3d3505920ddd4efed63c1a/LICENSE#L178-L201

So _I think_ it's required. @bogdandrutu let me know if you need help and I can ask layers in MS.

**Comment by bhs** [comment]
I'm going to ask a CNCF lawyerly person to comment on whether it's literally *required* or "just a recommended practice". If the latter, I am in agreement with @tylerbenson that it's a bunch of wasteful boilerplate that would be wonderful to remove :)

**Comment by caniszczyk** [comment]
It's not required but strongly recommended, it makes life easier for adoption and automated tooling which discovers license information.

The minimum should at least a line with an SPDX.org id... so "// Copyright 2019 OpenTelemetry Contributions, Licensed under Apache-2.0"

**Comment by tylerbenson** [comment]
@caniszczyk a single line is MUCH better.  I can accept that as a reasonable tradeoff even if some of the benefits I mentioned above would be invalidated.

@bhs How do we make the "single line attribution" the official policy?

**Comment by bogdandrutu** [comment]
Let me also double check with one lawyer from Google, I would suggest Microsoft do the same and any other company that may have some requirements. If no concerns from anyone then we should make it official. I would suggest to chat about this in the next board meeting.

**Comment by iredelmeier** [comment]
@caniszczyk is there specific tooling in mind? The license tools I've seen and used generally work well with a `LICENSE` file. However, I've obviously only seen a small subset of what's out there!

Also, how does this policy apply across file types? e.g., do Markdown files (the spec, docs, etc.) also need the header? What about if/when we end up with JSON files, which don't allow comments at all?

@tylerbenson @bhs I imagine that there's tooling out there for checking files, i.e., as a CI check.

Related to that, we should be able to set something up (a CI job) to automatically add whatever header where it's missing. However, I can imagine some UX issues, e.g., PRs would need to allow external edits.

**Comment by yurishkuro** [comment]
Governance committee recommendation:
* Keep full Apache header per CNCF recommendation https://github.com/cncf/foundation/blob/master/copyright-notices.md
* Remove the year from Copyright line to avoid maintenance overhead

**Comment by bogdandrutu** [comment]
Can we make this official by adding this to some contribution rules md file?

**Comment by carlosalberto** [comment]
I support @yurishkuro's suggestion, given the CNCF recommendation.

**Comment by tedsuo** [comment]
Following up on this. I will propose a clause to https://github.com/open-telemetry/community/blob/master/CONTRIBUTING.md stating that:

1. All code written for this project, or donated to this project, will have a single line license header, which reads:
```
 // Copyright 2019 OpenTelemetry Contributions, Licensed under Apache-2.0
```
2. This rule does not apply to 3rd party code copied from other languages. Licenses and headers must be retained for all code not donated with the consent of a member organization.

I'm not a lawyer, and I am sure questions like "what does consent mean?" are the next step in this journey... but I will create a basic PR just to get it moving.

**Comment by carlosalberto** [comment]
@tedsuo Do we really need to keep the year in the copyright? It would be nice to remove that requirement _if_ possible ;)

**Comment by yurishkuro** [comment]
We already have Governance Committee decision/recommendation https://github.com/open-telemetry/community/issues/113#issuecomment-595377568. It matches CNCF recommendations and the wildly accepted use of Apache license. Why do we need to diverge from it by replacing headers with one line?

**Comment by tedsuo** [comment]
@yurishkuro Apache Foundation also recommends this shorter header: http://www.apache.org/foundation/license-faq.html#Apply-My-Software

**Comment by andrewhsu** [comment]
I think it is important to note that this issue was opened by @tylerbenson who is employed by DataDog. I think the resolution of this issue will help unblock https://github.com/open-telemetry/opentelemetry-go-contrib/pull/15.

**Comment by tylerbenson** [comment]
I suggested this purely out of desire to reduce visual clutter in the codebase, not because of any ulterior motive.  I hate seeing PRs filled with just license headers. To that end, I would support either a single top level license file or the short 2 line license above each file. A 10 line header is excessive.

**Comment by yurishkuro** [comment]
Using the two-line header recommended by Apache is fine.

**Comment by bogdandrutu** [comment]
@yurishkuro can we close this issue with the following recommendation?
* Can use the full license headers with/without the year
* Can use the two-line header recommended by Apache with/without year

**Comment by SergeyKanzhelev** [comment]
Can you pls add a few words in this section: https://github.com/open-telemetry/community#license

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev I just filed this https://github.com/open-telemetry/community/pull/479 which adds a link to CNCF recommendations. I can it move to https://github.com/open-telemetry/community#license section if it is a better place for the link.

In addition to that we can clarify our choices further since CNCF allows for a few alternates for copyright headers.

**Comment by SergeyKanzhelev** [comment]
headers concerns both - license and copyright. So I think we need to extend the license section as well to talk about the headers. Or maybe merge these two section into "License and copyright"
