### ISSUE TITLE
Need help creating an event on the OpenTelemetry Public Calendar

### ISSUE THREAD

**Issue by musingvirtual** [open-telemetry/community#1130]
Greetings! I'm creating a monthly speaker event aimed at end users as part of my work in the end user working group, as detailed in [this blog post](https://github.com/open-telemetry/opentelemetry.io/pull/1618) and [these notes](https://docs.google.com/document/d/1FqEo2PfHPP8iZX_W-C3YgXFUjhfwmAhoREUE8ZJPJfc/edit?pli=1#heading=h.ip90glf2wys2).

If someone can create a calendar event for me, that will help contributors of the event be aware of the event and it will create a Zoom on the "official" account. If I create the Zoom link myself it will end up branded with my company's name which is not ideal.

Sharr, the maintainer of the End User Working Group, is currently away.  It's my understanding from [the notes on the public calendar](https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md) that maintainers are the only ones who have this permission, so I can't request the permission.

Is there anyone who has this permission who would be willing to do this for me?

Thanks!

**Comment by arminru** [comment]
Hey @musingvirtual!
I created an event for Aug 23rd. Please let me know if it looks good to you.
In the description I added a link to your blog post announcement but note that it will 404 until https://github.com/open-telemetry/opentelemetry.io/pull/1618 is merged.
The Zoom room I added is one of our shared rooms assigned by the CNCF. It should be set up so you can join any time but make sure to double-check beforehand that it works for you 🙂

**Comment by musingvirtual** [comment]
Thank you @arminru this is perfect really appreciate it!

**Comment by arminru** [comment]
Great, happy to help!

**Comment by musingvirtual** [comment]
Hi @arminru sorry to have a last-minute follow up question, but as this event has been advertised publicly, can you get me the host key for the meeting ([as mentioned in the public calendar document](https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md))? 

Want to make sure we have the appropriate tools to take care of it if there are any problems.  Thanks!

**Comment by musingvirtual** [comment]
You can DM it to me in the CNCF Slack
