### ISSUE TITLE
REQUEST: New membership for damemi

### ISSUE THREAD

**Issue by damemi** [open-telemetry/community#1132]
### GitHub Username

@damemi

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dashpole
- @djaglowski 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12158
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12157
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9713
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9679

- Issues responded to
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8249
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11436
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12072

- SIG projects I am involved with
- GCP exporters/collector contrib

**Comment by dashpole** [comment]
I support

**Comment by djaglowski** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @damemi! Invite sent
