### ISSUE TITLE
REQUEST: New membership for @rperry2174

### ISSUE THREAD

**Issue by Rperry2174** [open-telemetry/community#1133]
### GitHub Username
@rperry2174

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lizthegrey 
- @alolita

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-specification/pull/2621

- Issues responded to
https://github.com/open-telemetry/oteps/issues/139
https://github.com/cncf/tag-observability/issues/89

- SIG projects I am involved with
We've created a Profiling working group (that is in the process of being formalized hence this application)
[Weekly Meeting Notes](https://docs.google.com/document/d/1D-1MbT3MWpKM61JgVFx_TQi4vqWLLIZp6biK5MoHafI/edit#heading=h.lt3fqez5lhxo)
[Kickoff meeting recording](https://www.youtube.com/watch?v=iaOADKeMHYY&t=431s)

**Comment by alolita** [comment]
I support Ryan's membership request for joining OpenTelemetry as a contributor! Welcome @Rperry2174

**Comment by lizthegrey** [comment]
I support. A very belated welcome to our community!

**Comment by SergeyKanzhelev** [comment]
Welcome, @Rperry2174! Invite sent
