### ISSUE TITLE
REQUEST: Repository maintenance on wg-ebpf

### ISSUE THREAD

**Issue by yonch** [open-telemetry/community#1134]
### Affected Repository

https://github.com/open-telemetry/wg-ebpf

### Requested changes

- [x] Rename repository to `opentelemetry-ebpf` (or create a new repository and delete `wg-ebpf` if easier)
- [x] Create team `ebpf-maintainers`
- [x] Create team `ebpf-approvers`
- [x] Create team  `ebpf-triagers`
- [x] Remove team `wg-ebpf` (created as part of the workgroup)
- [x] Add `@yonch` as Maintainer to `ebpf-{maintainers, approvers,triagers}` (this should allow me to add the rest)
- [x] Give teams appropriate permissions to the repository (happy to do this if I have sufficient permissions)

Permission/Team work is done towards conforming with the [new repository howto](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md).
 
### Purpose

This is part of the ebpf donation to OpenTelemetry, approved in #733 . The `wg-ebpf` repository was created in #788 (cc @lizthegrey and @tigrannajaryan ).

We are preparing to move the authoritative repository for `opentelemetry-ebpf` code from https://github.com/flowmill/network-explorer . As a part of the move, teams need to be set up so the developers can continue to code, review and merge changes. 

Next step would be to verify that policies are enforced according to the [new repository howto](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md). If Maintainer permissions are sufficient to configure those we should be all set.
 
### Expected Duration

This request is for permanent changes.

### Repository Maintainers

not applicable. @tigrannajaryan had created a team `wg-ebpf` but it has not been in use.

**Comment by tigrannajaryan** [comment]
If you need any additional settings changes on the repo I can give you temporary Admin permission to set things up.

**Comment by yonch** [comment]
thank you @tigrannajaryan . Can you please check if @yonch is a maintainer in these teams? I don't seem to have the capability to invite to the teams..

Also how do OpenTelemetry maintainers usually configure pre-merge checks? Is that what the Admin privilege is used for?For example, we have been enforcing `clang-format` to format C++ code on some repos as a pre-merge check, will want to see how that can be configured here..

**Comment by tigrannajaryan** [comment]
@yonch Yes, you are a maintainer:
![image](https://user-images.githubusercontent.com/4194920/185207386-ae6336b5-723d-46d6-b053-cb4cca949796.png)

I am going to make you an Admin for now, so that you can set up the repo and invite others as needed.

**Comment by tigrannajaryan** [comment]
>Also how do OpenTelemetry maintainers usually configure pre-merge checks? Is that what the Admin privilege is used for?

Yes, I think it requires an Admin privilege. You have it now.

**Comment by yonch** [comment]
@tigrannajaryan verified that I'm part of `ebpf-maintainers` and `ebpf-maintainers` has "Maintain" role on `opentelemetry-ebpf`.

I think the [configuration howto](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md) also gives maintainers the "Maintain" role on _the teams_ so Maintainers can add team members to the teams. There is a "Role" filter on the team:

![image](https://user-images.githubusercontent.com/3083478/185223811-f4a8b2e2-a0fb-4da8-a22c-075c0e4efc47.png)

I think if you set @yonch to "Maintainer" role on the the three teams, I'd be able to do the rest.

Thank you for the Admin privileges on the repo! Will help figure out the pre-merge checks story for this repo.

**Comment by tigrannajaryan** [comment]
>I think if you set @yonch to "Maintainer" role on the the three teams, I'd be able to do the rest.

I don't know how to do it. I don't see a setting that allows that.

**Comment by tigrannajaryan** [comment]
OK, found it. Try now.

**Comment by yonch** [comment]
Great! Can verify Maintainer privileges on `ebpf-maintainers`.

The new repo set up also says "Every member of foo-maintainers should be included in foo-approvers and foo-triagers explicitly, with the "Maintainer" GitHub privileges. This allows repository maintainers to invite new approvers and triagers to the team."

should we get Maintainer permission on the other two teams (-approvers and -triagers) set up as well? Sorry for front-loading all of this work, just want to get it set up and not worry about bothering you about this in the future..

**Comment by tigrannajaryan** [comment]
>should we get Maintainer permission on the other two teams (-approvers and -triagers) set up as well?

No, approvers and triagers should not have a Maintainer permission. All maintainers _are_ automatically approvers and  triagers, that's why they should be included in those teams (and they already are), but the opposite is not true.

**Comment by yonch** [comment]
I think we're done with this. Sorry for leaving the issue open. Thank you @tigrannajaryan !
