### ISSUE TITLE
REQUEST: New membership for evan-bradley

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/community#1136]
### GitHub Username

@evan-bradley

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @TylerHelmuth 
- @dmitryax 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

**PRs authored**
- https://github.com/open-telemetry/opentelemetry-specification/pull/2706
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12972
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13120
- https://github.com/open-telemetry/opentelemetry.io/pull/1527
- https://github.com/open-telemetry/opentelemetry-specification/pull/2669
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12632
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12706

**Issues responded to**
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12476
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12482
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12193
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12975
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13251

**Issues created**
- https://github.com/open-telemetry/opentelemetry-python/issues/2793
- https://github.com/open-telemetry/opentelemetry-specification/issues/2708
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13390
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13391

**SIG projects I am involved with**
The OpenTelemetry Collector SIG

**Comment by TylerHelmuth** [comment]
I support

**Comment by dmitryax** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @evan-bradley!
