### ISSUE TITLE
Ensure security policy is available on all repos

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1137]
Planeposting, apologies for lack of links --

Someone raised a security vulnerability report for the collector (presumably) in slack. The security tab on the collector repo doesn't actually have the right security.md doc, it has one that specifies architecture/user concerns around security while operating the collector. 

Posting this issue to accomplish the following:

- ensure each repo has the correct security doc available through the security tab in GH
- ensure community repo has security/vuln reporting info linked from its readme

**Comment by hickeyma** [comment]
I was the person chatting on slack with @austinlparker @seankhliao @mhausenblas about this. I was looking for the Open Telemetry security policy but couldn't find it first off.

@seankhliao pointed me to the Go security tab:  https://github.com/open-telemetry/opentelemetry-go/security/policy. 

Upon further investigations I found that the 

- Collector security tab collector displays to the collector security documentation/guideline instead: https://github.com/open-telemetry/opentelemetry-collector/security/policy
- Community security tab displays the Open Telemetry security policy: https://github.com/open-telemetry/community/security/policy

**Comment by trask** [comment]
hey @austinlparker, it looks like this has been fixed in the collector repo, and I don't see any other repos overriding `SECURITY.md`:

https://github.com/search?q=org%3Aopen-telemetry+path%3A**%2Fsecurity.md&type=code
