### ISSUE TITLE
REQUEST: New membership for frzifus

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/community#1139]
### GitHub Username

@frzifus

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @pavolloffay 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12753
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12788
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12940
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13408
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13411
https://github.com/open-telemetry/opentelemetry-operator/pull/717
https://github.com/open-telemetry/opentelemetry-operator/pull/817
https://github.com/open-telemetry/opentelemetry-operator/pull/973
https://github.com/open-telemetry/opentelemetry-operator/pull/786

- Issues responded to
https://github.com/open-telemetry/opentelemetry-operator/issues/902
https://github.com/open-telemetry/opentelemetry-operator/issues/821

- SIG projects I am involved with
The OpenTelemetry Collector SIG

**Comment by jpkrohling** [comment]
I support

**Comment by pavolloffay** [comment]
I support @frzifus membership as well

**Comment by frzifus** [comment]
Hi @tigrannajaryan, @kovrus could you have please have a look or  is there something else i need to do? :)

**Comment by tigrannajaryan** [comment]
Membership invitation sent. Welcome @frzifus!
