### ISSUE TITLE
REQUEST: New membership for kovrus

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/community#1141]
### GitHub Username
@kovrus

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs authored

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12892
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12995
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12997
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12990
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13529 
- https://github.com/open-telemetry/opentelemetry-collector/pull/5896
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13298
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13325
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13326
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13383
- https://github.com/open-telemetry/opentelemetry-specification/pull/2745

#### Issues responded to

- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13158
- https://github.com/open-telemetry/opentelemetry-collector/issues/4814
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7945
- https://github.com/open-telemetry/opentelemetry-collector/issues/5733 

#### SIG projects I am involved with
OpenTelemetry Collector (contrib)

**Comment by TylerHelmuth** [comment]
I support

**Comment by jpkrohling** [comment]
I support

**Comment by arminru** [comment]
Hey @kovrus!
The section "SIG projects I am involved with" in your request is left empty.
Would it be accurate to mention the OpenTelemetry Collector (contrib) here?

**Comment by kovrus** [comment]
> Hey @kovrus! The section "SIG projects I am involved with" in your request is left empty. Would it be accurate to mention the OpenTelemetry Collector (contrib) here?

I'll update that.

**Comment by arminru** [comment]
Invite sent. Welcome, @kovrus!
