### ISSUE TITLE
REQUEST: New membership for eBPF Maintainers

### ISSUE THREAD

**Issue by yonch** [open-telemetry/community#1144]
### Background

We are preparing to move the authoritative eBPF repository from the `flowmill` GitHub org to the `open-telemetry` org, and would like to transition Maintainers. These have been past maintainers who intend to remain maintainers.

### GitHub Username

@bjandras
@jimwsplk

### Requirements

All are active contributors.

Those folks verified:
- I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)

### Sponsors

Preemptive apologies for the lack of experience with the process...

I believe this was discussed in the GC, which was ok with including TC members to sponsor/approve. (@tigrannajaryan we discussed multiple topics, hope I'm not confusing that convo..)

@open-telemetry/technical-committee

**Comment by reyang** [comment]
I support.

**Comment by yonch** [comment]
I support.

Thank you @reyang

**Comment by jsuereth** [comment]
I support

**Comment by tigrannajaryan** [comment]
@bjandras @jimwsplk Invitations sent. Welcome to Otel!
