### ISSUE TITLE
REQUEST: New membership for @kevinearls

### ISSUE THREAD

**Issue by kevinearls** [open-telemetry/community#1148]
### GitHub Username
@kevinearls

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @pavolloffay 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-operator/pull/1014
https://github.com/open-telemetry/opentelemetry-operator/pull/1003
https://github.com/open-telemetry/opentelemetry-operator/pull/984
https://github.com/open-telemetry/opentelemetry-operator/pull/945
https://github.com/open-telemetry/opentelemetry-operator/pull/735
https://github.com/open-telemetry/opentelemetry-operator/pull/225
(https://github.com/open-telemetry/opentelemetry-operator/pull/224
https://github.com/open-telemetry/opentelemetry-operator/pull/223
https://github.com/open-telemetry/opentelemetry-operator/pull/167
https://github.com/open-telemetry/opentelemetry-operator/pull/155
https://github.com/open-telemetry/opentelemetry-operator/pull/138
https://github.com/open-telemetry/opentelemetry-operator/pull/135
https://github.com/open-telemetry/opentelemetry-operator/pull/122
https://github.com/open-telemetry/opentelemetry-collector/pull/5315
https://github.com/open-telemetry/opentelemetry-collector/pull/2238
https://github.com/open-telemetry/opentelemetry-collector/pull/923
https://github.com/open-telemetry/opentelemetry-collector/pull/922
https://github.com/open-telemetry/opentelemetry.io/pull/1161
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10823

- Issues responded to
https://github.com/open-telemetry/opentelemetry-operator/issues/1011
https://github.com/open-telemetry/opentelemetry-operator/issues/942
https://github.com/open-telemetry/opentelemetry-operator/issues/931
https://github.com/open-telemetry/opentelemetry-operator/issues/969
https://github.com/open-telemetry/opentelemetry-operator/issues/943
https://github.com/open-telemetry/opentelemetry-operator/issues/922
https://github.com/open-telemetry/opentelemetry-operator/issues/906
https://github.com/open-telemetry/opentelemetry-collector-builder/issues/5

- SIG projects I am involved with

**Comment by jpkrohling** [comment]
I support!

**Comment by pavolloffay** [comment]
I support!

**Comment by bogdandrutu** [comment]
Invite sent
