### ISSUE TITLE
REQUEST: Repository maintenance on Collector Contrib

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1154]
Would it be possible for an admin to add `open-telemetry/opentelemetry-collector-contrib` to [this page](https://github.com/orgs/open-telemetry/teams/collector-contrib-triagers/repositories), triage role? I'm not an admin, I can't add it. 

Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/13387/187927843-6bb946b1-8ed2-4cd5-8971-d2560b5ccb64.png)

cc @evan-bradley

**Comment by jpkrohling** [comment]
The -releases repository should be kept there, as it inherits the privileges from -contrib.

**Comment by arminru** [comment]
Done!

**Comment by jpkrohling** [comment]
That was fast, thanks @arminru!
