### ISSUE TITLE
The new membership workflow is broken

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/community#1156]
As of September 2, 2002:

The last "REQUEST: New membership for <user>" issue that was successfully processed is:

https://github.com/open-telemetry/community/issues/1109

Any new membership request processed after July 13, 2002:
- contains an "invitation sent" message
- is closed
- has no effect, as invited accounts are not part of https://github.com/orgs/open-telemetry/people

@arminru, not sure about others, but in my case I never received an invitation link:

https://github.com/open-telemetry/community/issues/1122

The fact that there are so many requests with no apparent outcome since July 13 suggest that this is a systemic issue, not related to individual requests.

Looking forward to become an opentelemetry member, really.

Regards,
-- Marc

**Comment by arminru** [comment]
Hi Marc!
I just checked for the users in all requests between #1109 and now, and in fact all of them show up in https://github.com/orgs/open-telemetry/people except for you. Please try joining again, I just re-sent the invite.
If you still did not receive the email, please let me know.

**Comment by marcalff** [comment]
Thanks @arminru 

I got the invite, and accepted, thanks.

The weird part is that:
- before accepting, the https://github.com/orgs/open-telemetry/people link showed 146 persons, and recent members were *not* listed, I doubled checked again
- after accepting, I now see 342 persons in the org.

I guess this is because of the private / public membership permission.

Closing, as this is resolved.
Thanks.

**Comment by arminru** [comment]
Great!
Yes, that's correct. The private/public setting is a bit hidden and not part of the workflow of joining the org, so many don't set their membership to public apparently. As a member of the org like you are now, you can see all other members.
