### ISSUE TITLE
.NET Auto-Instrumentation SIG meeting recordings not uploaded

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/community#1157]
Ever since the .NET Auto-Instrumentation SIG changed meeting times and meeting IDs, our meeting recordings have not been getting uploaded. Other SIGs are successfully getting their meetings uploaded.

This issue is probably also related to #1006.

CC: @open-telemetry/dotnet-instrumentation-maintainers, @open-telemetry/dotnet-instrumentation-approvers

**Comment by arminru** [comment]
@alanwest @eddynaka can you take a look please?

**Comment by alanwest** [comment]
@arminru I suspect this is different from #1006. When I join the link from the calendar for the .NET auto-instrumentation SIG, I do not get the "recording in progress" announcement.

I'd guess that this is a Zoom configuration issue. Our [assets page](https://github.com/open-telemetry/community/blob/9e7a12f47a3056c0d6175194131483cc9995318d/assets.md#zoom-accounts) suggests @austinlparker @mtwo @tedsuo or @SergeyKanzhelev might be able to troubleshoot Zoom issues.

**Comment by zacharycmontoya** [comment]
As a regular attendee of the .NET auto-instrumentation SIG meeting, I can confirm that for at least the past two weeks, I have been receiving the "recording in progress" announcement, so I don't think that is the issue

**Comment by alanwest** [comment]
> As a regular attendee of the .NET auto-instrumentation SIG meeting, I can confirm that for at least the past two weeks, I have been receiving the "recording in progress" announcement, so I don't think that is the issue

Interesting, if Zoom is automatically recording the meeting then it may be an issue with Splain not uploading them to YouTube. We'll need someone with Splain knowledge to take a look.

There were 7 SIG meetings today so far including the .NET auto-instrumentation SIG, but only 6 recordings have made it to YouTube:

Log SIG: https://youtu.be/KeivZ_AhxcI
Client-Side SIG: https://youtu.be/ydPWYbGigSY
Collector SIG: https://youtu.be/jFjNEdSndhE 🥳 (this one had been missing for awhile - looks like #1006 can be closed out)
JS SIG: https://youtu.be/s_sEWzTCUX8
PHP SIG https://youtu.be/S8J6F0Px1FA
CPP SIG https://youtu.be/WAycAV0DrdY

**Comment by Kielek** [comment]
Do you have any updates? I cannot find yesterday recording, others are available.

**Comment by mtwo** [comment]
@amye looks like another Splain disconnection. Shall I file a service desk ticket?

**Comment by amye** [comment]
(1) If you need our (CNCF's) help, Servicedesk. We cannot track github. 
(2) In this exact instanct, support@splain.io is your better contact

**Comment by Kielek** [comment]
I have sent an email to splain.io.

@amye, @pjanotti and @mtwo are in CC field.

**Comment by mtwo** [comment]
This is now fixed for future recordings, not sure about past ones. The issue was that several months ago we added a fourth Zoom account and forgot to subscribe it to Splain. It's been subscribed and uploads should now occur on new meetings.

**Comment by Kielek** [comment]
The recording name looks differently, but IMO it is better than the previous one. I think that we can finally close the issue.
![image](https://user-images.githubusercontent.com/5972917/207820435-1e500e8e-548f-4e2d-b9bb-d408484fe37b.png)

**Comment by nrcventura** [comment]
Thanks everyone for helping to resolve this issue and getting the meeting name updated.
