### ISSUE TITLE
Get involved link should point to the mailing list

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#116]
This section:

> Get Involved
> There is a lot to do! If you are interested in getting involved, please get in touch via this simple form. We are a friendly, collaborative group and look forward to working together.

should point to the mailing list, not some custom form. See https://github.com/open-telemetry/community/pull/108

**Comment by mtwo** [comment]
Fixed in #108

**Comment by mtwo** [comment]
@SergeyKanzhelev you can close this ... I don't have permissions

**Comment by SergeyKanzhelev** [comment]
Get involved link still points to this form: https://docs.google.com/forms/d/e/1FAIpQLSfrqYLb4CYiLG5NyXwZDsWYNVMAVoAY6J4oNT1Q9TKGSGnI4Q/viewform

I think it will be better to point to the community list.

**Comment by mtwo** [comment]
Fixing

**Comment by mtwo** [comment]
#125 is ready for your review
