### ISSUE TITLE
Create a document for the Go auto-instrumentation SIG

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1160]
We started [this Google doc](https://docs.google.com/document/d/1P6am_r_cxCX1HcpDQlznrTrTOvwN2whshL0f58lXSWI/edit#) for the kick-off meeting. As we move to reoccurring SIG meetings we now need a doc owned by OTel.

**Comment by tigrannajaryan** [comment]
Is this is a dup of https://github.com/open-telemetry/community/issues/1147 ?

**Comment by MrAlias** [comment]
> Is this is a dup of #1147 ?

No, it is for a new SIG not covered in that linked issue (which is for already existing SIGs).

**Comment by tigrannajaryan** [comment]
@dyladan can you help create a document?

**Comment by dyladan** [comment]
Yes but I'm on vacation. I can do it Monday if nobody has done it by then

**Comment by trask** [comment]
hey @MrAlias! want to just transfer ownership of the document you linked above to the OpenTelemetry Governance Committee account? if so, follow the instructions from @dyladan in #1147

> ## Process to transfer ownership
>
> 1. Click the share button 
> 2. Invite cncf-opentelemetry-governance at lists.cncf.io to be an editor
> 3. Click the share button again
> 4. Click on the arrow next to the governance committee email and select "Transfer Ownership" 
> 5. Click "Send Invitation"

**Comment by MrAlias** [comment]
> hey @MrAlias! want to just transfer ownership of the document you linked above to the OpenTelemetry Governance Committee account? if so, follow the instructions from @dyladan in #1147

Cool! I've followed the process and an email should be sent.

**Comment by dyladan** [comment]
Accepted
