### ISSUE TITLE
Change the open-telemetry/otel-elections group to reflect the current working group

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1165]
Change the @open-telemetry/otel-elections group to reflect the current working group: @jpkrohling, @bogdandrutu, and @bhs (review)

**Comment by dyladan** [comment]
Looks like only @open-telemetry/technical-committee has permission to handle this sorry. Thought i might be able to do it since i was on last year's but no

**Comment by arminru** [comment]
I invited the missing members as requested and removed @alolita, @dyladan, and @lizthegrey (last year's committee).

![image](https://user-images.githubusercontent.com/7052238/189391184-aa21e975-7083-4d68-8fcd-3712004f5d50.png)
