### ISSUE TITLE
Upload voter rolls to the election software

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1167]
Either @bogdandrutu or @jpkrohling should work on this, perhaps with guidance from @lizthegrey, who did this last year.

**Comment by jpkrohling** [comment]
I just had a call with @lizthegrey and I believe I understand the process now: 

1. get the GitHub IDs from devstats' dashboard "Developer Activity Counts by Repository Group", selecting the time frame to "Last year". Note that "Developer" here is misleading, as everything (not only code) is counted here. Ideally, the time frame would start when the last election finished, up to the cut-off date for the new election.
2. filter out the people with less than 20 contributions
3. upload the GitHub IDs to Helios
4. update the announcement issue to mention the eligible people

I'll work on a script to automate the first item.

**Comment by jpkrohling** [comment]
Instead of a script, I think it's easier to just the data from the dashboard itself and filter out the data manually

1. Go to the "[Developer Activity Counts by Repository group](https://opentelemetry.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1)" dashboard
2. Select "Last year" as the time range
3. On the data panel, open the drop-down menu and click "Inspect", "Data"
![image](https://user-images.githubusercontent.com/13387/193104317-f392ce5c-282c-4810-8898-9c54a672138d.png)
4. Download the CSV file
5. Filter out the people with less than 20 contributions

Alternatively, edit the panel and add a `where sub.value >= 20` as the last line of the query, and do the same as above. The step 5 wouldn't then be necessary.

**Comment by jpkrohling** [comment]
This is the current voter roll. The file has the GitHub names in the first column and the number of contributions in the second. I uploaded it already to Helios and will prepare the GitHub comments soon, but perhaps one of you could do a sanity check first?

I have 5988 contributions, which is in line with my expectations.

[voter-roll.csv](https://github.com/open-telemetry/community/files/9678466/voter-roll.csv)

**Comment by lizthegrey** [comment]
yup, my contribution count about tracks too, and 500 active contributors feels right for our project

**Comment by jpkrohling** [comment]
I ended up creating a repository with all the information and scripts: https://github.com/jpkrohling/voter-roll-otel-elections
