### ISSUE TITLE
Offboard departing GC members and Onboard new GC members

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1169]
Either @bogdandrutu or @jpkrohling should work on this.

List of tasks to do, based on the comments from this issue:

- [x] Adding to the "OTel (internal) governance committee meeting" invitation
- [x] Adding to the #opentelemetry-gc channel
- [x] Inviting to the cncf-opentelemetry-governance mailing list
- [x] Add on slack to #opentelemetry-gc-tc and #opentelemetry-gc-alum
- [x] add to https://github.com/orgs/open-telemetry/teams/governance-committee/members
- [x] send PR to: https://github.com/cncf/foundation/blob/main/project-maintainers.csv
- [x] grant write permissions to GC meeting notes: https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8/edit#heading=h.8mwlusiri5yp
- [x] Update the community-members.md and and codeowners: https://github.com/open-telemetry/community/ 
- [x] Add to GC 1password

**Comment by jpkrohling** [comment]
Onboarding @trask by:

- [x] Adding to the "OTel (internal) governance committee meeting" invitation
- [x] Adding to the #opentelemetry-gc channel
- [x] Invited to the cncf-opentelemetry-governance mailing list

Is there anything else needed to onboard new members, @open-telemetry/governance-committee?

**Comment by trask** [comment]
thx @jpkrohling! I think also add me to https://github.com/open-telemetry/community/blob/main/CODEOWNERS?

**Comment by SergeyKanzhelev** [comment]
A few more items off the top of my head:

- [ ] #opentelemetry-gc-tc, opentelemetry-gc-alum
- [ ] add to https://github.com/orgs/open-telemetry/teams/governance-committee/members
- [ ] send PR to: https://github.com/cncf/foundation/blob/main/project-maintainers.csv
- [ ] grant write permissions to GC meeting notes: https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8/edit#heading=h.8mwlusiri5yp
- [ ] Update the readme: https://github.com/open-telemetry/community/blob/main/community-members.md#governance-committee

**Comment by jpkrohling** [comment]
Thanks for the list, @SergeyKanzhelev! I'll probably work on those items later this week.

**Comment by trask** [comment]
one more for future reference (@dyladan is doing this for me):

- [ ] Add to GC 1password

**Comment by arminru** [comment]
ping @codeboten 🙂

**Comment by jpkrohling** [comment]
I don't seem to have permission to change the GitHub group. Perhaps only the TC has access to it? Beyond that and the password store, @trask should have been fully onboarded once the linked PRs are merged.

cc @open-telemetry/technical-committee

**Comment by jpkrohling** [comment]
Based on https://github.com/open-telemetry/community/issues/1283, it might need updating as well.

**Comment by carlosalberto** [comment]
Added @trask to the GC group in Github.

**Comment by jpkrohling** [comment]
@carlosalberto, could you also please remove @lizthegrey? Once that is done, I believe this task is complete.

**Comment by arminru** [comment]
Thank you, @codeboten!

**Comment by arminru** [comment]
@jpkrohling It seems like @lizthegrey was already removed and the GH team reflects the current 9 members.
I'll resolve this issue then.

**Comment by lizthegrey** [comment]
Still need to remove departing GC members from mailing lists (I manually offboarded myself)

**Comment by jpkrohling** [comment]
I just double-checked, and I can confirm that there are only current board members there, along with 4 people from either the CNCF or the Linux foundation, which seems appropriate to me.
