### ISSUE TITLE
2022 Election Announcements 

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1173]
This issue will contain election announcements and the complete list of eligible voters. Subscribe to this issue if you wish to be notified of changes. Contact @open-telemetry/otel-elections if you have questions.

If you are not automatically detected as a member of standing and believe your contributions should make you eligible to vote, you may request an exemption by filling out a [registration form](https://forms.gle/mEDWyn6G7iCe4bvJ7).

People mentioned in this issue have been detected as members of standing, as [defined in the project's governance charter](https://github.com/open-telemetry/community/blob/main/governance-charter.md#members-of-standing). 

You can find more information about the voting process [here](https://github.com/open-telemetry/community/blob/main/elections/2022/governance-committee-election.md)

Due to the potential notification storm that this issue may cause, the conversation is locked. If you have concerns, please contact the group @open-telemetry/otel-elections, or any of the members (@jpkrohling or @bogdandrutu) individually. They are also available on the [CNCF Slack](http://slack.cncf.io/).

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @﻿1046102779
* @aabmass
* @aaron-ai
* @aaronontheweb
* @aateeqi
* @abe545
* @abelperezok
* @abhee11
* @abhide
* @aboguszewski-sumo
* @acm19
* @adilhusain-s
* @adriankostrubiak-tomtom
* @ahayworth
* @aishyandapalli
* @alanwest
* @albertteoh
* @alexvanboxel
* @allex1
* @alolita
* @alvinhom
* @amber0612
* @amoscatelli
* @andrewhr
* @andrewzenkov
* @andyfleming
* @andykellr
* @aneurysm9
* @antonblock
* @anupamdalmia10
* @anuraaga
* @anuragagarwal561994
* @aptomaketil
* @arhell
* @arielvalentin
* @arminru
* @armstrmi
* @arun-shopify
* @aschugunov
* @ash2k
* @ashu658
* @astencel-sumo
* @astitcher
* @atingchen
* @atoulme
* @austinlparker
* @avadhut123pisal
* @avillela
* @axw
* @ayandapalli

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @basti1302
* @beeme1mr
* @ben-natan
* @bennettsmith
* @bertysentry
* @bgranetzke
* @bhautikpip
* @bhs
* @billmeyer
* @binaryfissiongames
* @binjip978
* @bjandras
* @blacksmoke16
* @blumamir
* @bobstrecansky
* @bogdandrutu
* @boostchicken
* @bputt-e
* @bradfrosty
* @bradtopol
* @breedx-splk
* @brettmc
* @bronzedeer
* @brunobat
* @brushknight
* @bryan-aguilar
* @bryannaegele
* @bryce-b
* @bushwhackr
* @carlosalberto
* @carlosjgp
* @cartermp
* @cartersocha
* @cbandy
* @cedricziel
* @chalin
* @chenjazz
* @chenzhihao
* @chrisholmes
* @chrisrichardsevergreen
* @cijothomas
* @codeblanch
* @codeboten
* @coderpoet
* @cpheps
* @crobert-1
* @crobertson-conga
* @cuichenli
* @cyrille-leclerc
* @damemi

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @dashpole
* @davidgargti20
* @davidji99
* @davidmirza408
* @dchambers
* @debajitdas
* @deejgregor
* @deexitp-splunk
* @dehaansa
* @delanym
* @denisivan0v
* @deosu
* @derekkraan
* @diceride
* @dineshg13
* @dino-ma
* @diptochakrabarty
* @disq
* @djaglowski
* @djc
* @dloucasfx
* @dmathieu
* @dmitryax
* @dpauls
* @dszmigielski
* @duncan-tree-zhou
* @dvic
* @dwelch-spike
* @dyladan
* @eddieeldridge
* @eddynaka
* @edenfed
* @eedorenko
* @ejsmith
* @emaderer
* @enkelian
* @erichsueh3
* @ericmustin
* @esigo
* @evan-bradley
* @evantorrie
* @fatsheep9146
* @fbogsany
* @felixscheinost
* @ferd
* @flarna
* @frapschen
* @frefreak
* @frzifus
* @fscellos

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @fstab
* @galbash
* @garypwhite
* @gbbr
* @gcatanese
* @gfonseca-tc
* @gillg
* @gnm444
* @gouthamve
* @grahamlea
* @gregoryfranklin
* @grunet
* @gyliu513
* @habmic
* @haddasbronfman
* @halofour
* @hananiel
* @hanjm
* @hanyuancheung
* @hardproblems
* @hcoona
* @hdost
* @hecomp
* @hectorhdzg
* @hickeyma
* @hosamaly
* @howardyoo
* @hprajapati-splunk
* @hsmatulisgoogle
* @hughsimpson
* @hyunuk
* @iblancasa
* @indrekj
* @inikem
* @iomari
* @irizzant
* @itaygibel-helios
* @jack-berg
* @jackyshang12321
* @jamesjhpark
* @jamesmoessis
* @jamiedanielson
* @jaredtan95
* @jaronoff97
* @jcchavezs
* @jeanbisutti
* @jefchien
* @jeremydvoss
* @jessberg
* @jkamon

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @jkowall
* @jkwatson
* @jmacd
* @jmwilliams89
* @joaopgrassi
* @johnnyshields
* @jonahaapala
* @jonatan-ivanov
* @jonathan-s
* @jonathanwamsley
* @josephwoodward
* @jpeach
* @jpkrohling
* @jsalinaspolo
* @jscherer92
* @jsirianni
* @jspaleta
* @jsuereth
* @jsumners
* @jtescher
* @julianocosta89
* @junhaoyu-aws
* @jvilhuber
* @jvoravong
* @jwilm
* @kart
* @keep94
* @keisku
* @kenfinnigan
* @kentquirk
* @kevinearls
* @khyatigandhi6
* @kielek
* @kirrg001
* @kishannsangani
* @kittylyst
* @konig-corey
* @kovrus
* @kpratyus
* @kristinapathak
* @kserrania
* @ktmitton
* @kubawach
* @kumoroku
* @kw7oe
* @lachmatt
* @ladd
* @lalex
* @lalitb
* @laurit

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @laziobird
* @legendecas
* @leonsp-ai
* @lgfa29
* @liqiangz
* @lizthegrey
* @lmolkova
* @locmai
* @lonewolf3739
* @longility
* @longwuyuan
* @lquerel
* @luismiramirez
* @lzchen
* @m1o1
* @madvikinggod
* @malpi
* @manang-splunk
* @mapno
* @marcalff
* @mario-hofstaetter
* @martinkuba
* @mateuszrzeszutek
* @mat-rumian
* @mcmho
* @meastp
* @melbgirl
* @mentos1386
* @mhassan1
* @mic-max
* @mikegoldsmith
* @miry
* @mmanciop
* @mohitmahi
* @moh-osman3
* @morigs
* @mottibec
* @moviestoreguy
* @mplachter
* @mralias
* @mrod1598
* @msnev
* @mstumpfx
* @mtwo
* @mustafain117
* @mviitane
* @mwear
* @mx-psi
* @my-git9
* @nachobonafonte

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @naseemkullah
* @nathanielrn
* @navehmevorach
* @neelayu
* @nemoshlag
* @ness001
* @nevay
* @newly12
* @nhinsch
* @noahfalk
* @nordfjord
* @notcool11
* @nozik
* @nrcventura
* @nslaughter
* @nvolker
* @obecny
* @oberon00
* @ocelotl
* @oded-dd
* @oertl
* @ofek
* @ofek1weiss
* @ofirshmuel
* @omamoo
* @opentelemetrybot
* @oppegard
* @orloffv
* @osherv
* @overmeulen
* @owais
* @owent
* @oxeye-nikolay
* @patil-kshitij
* @paurushgarg
* @pavankrish123
* @pavolloffay
* @pcolazurdo
* @pcwiese
* @pdelewski
* @pellared
* @peterf778
* @petrie
* @phillipuniverse
* @pichlermarc
* @pirgeo
* @pjanotti
* @plantfansam
* @pmalek-sumo
* @pmcollins

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @pmm-sumo
* @povilasv
* @ppatierno
* @pragmaticivan
* @puckpuck
* @punya
* @pureklkl
* @pyohannes
* @radcortez
* @rahuldimri
* @rajkumar-rangaraj
* @ralphgj
* @rangelreale
* @rapphil
* @rassk
* @rauno56
* @rcjsuen
* @reese-lee
* @remram44
* @reugn
* @rex-remind101
* @reyang
* @ringerc
* @rjduffner
* @rkukura
* @rmfitzpatrick
* @robbkidd
* @robertlaurin
* @rockb1017
* @rogercoll
* @ronyis
* @rquedas
* @rubenruizdegauna
* @rubenvp8510
* @rypdal
* @saikrishna397
* @samimusallam
* @samudraneel24
* @sanketmehta28
* @schanjr
* @scheler
* @schmikei
* @secustor
* @seemk
* @sergeykanzhelev
* @sethamazon
* @sgracias1
* @shahargl
* @shalevr
* @sharrmander

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @sherlouk
* @shree007
* @siddhikhapare
* @silverlyra
* @sincejune
* @singku
* @sirzooro
* @sjs994
* @smashedtoatoms
* @sohampachpande
* @somalianivan
* @spencerdcarlson
* @spencerwilson
* @splunkericl
* @sprakhar97
* @srikanthccv
* @srprash
* @stefankurek
* @sumo-drosiek
* @sunface
* @sungwonh
* @svetlanabrennan
* @svrakitin
* @svrnm
* @sweetxiaodai
* @swetharavichandrancisco
* @swiatekm-sumo
* @symbianx
* @t2t2
* @tarekgh
* @tbble
* @tedsuo
* @tenaria
* @theanshul756
* @theletterf
* @thepeterstone
* @thiyagu55
* @thomsontan
* @tidal
* @tigrannajaryan
* @tillig
* @timothymothra
* @tjiuming
* @tobiasstadler
* @tomkerkhove
* @tommycpp
* @tonglil
* @trasc
* @trask
* @trivikr

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @tsloughter
* @tttoad
* @tuhao1020
* @twenzel
* @tydhot
* @tylerhelmuth
* @ugzuzg
* @umarkhan17
* @utpilla
* @vasireddy99
* @vibhavp
* @vincentfree
* @vineethreddy02
* @vishweshbankwar
* @vjsamuel
* @vmarchaud
* @vmihailenco
* @vreynolds
* @wajika
* @wallezhang
* @wangzlei
* @wdullaer
* @weyert
* @wgliang
* @willarmiros
* @wph95
* @xavierjohn
* @xiang17
* @xiangtianyu
* @xiaoweikin
* @xoscar
* @xp-1000
* @xsam
* @xyq175com
* @yadumathur
* @yamakaky
* @yangtaoran
* @yanivd
* @ydrozhdzhal
* @ymotongpoo
* @yoheyk
* @yonch
* @yotamloe
* @yuktea
* @yun-ting
* @yuriolisa
* @yurishkuro
* @yzeng25
* @zacharycmontoya
* @zackman0010

**Comment by jpkrohling** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @zeitlinger
* @zenmoto
* @zhouzhongzhi

**Comment by jpkrohling** [comment]
I have heard from different users that they are having trouble voting, and I believe this is happening because their usernames use a mixed case, where our data source (devstats) only provides usernames in lower case.

If you are attempting to vote and receive a "permission denied" message from Helios and your username has a mixed case, please ping me directly on Slack with your username, and I'll fix it right away. I'm sorry for this inconvenience (and for this new broadcast, I promise I'm trying to keep this at a minimum).

**Comment by alolita** [comment]
Thanks for clarifying @jpkrohling As Tigran mentioned, the instructions were not clear initially :-)

**Comment by jpkrohling** [comment]
This is a friendly reminder to cast your vote for the OpenTelemetry Governance Committee Election 2022. If you are listed in one of the first comments on this issue, you are eligible for voting.

IMPORTANT: remember to click "cast your vote" in the final step, or your ballot will not be received.

If you have trouble voting, let me (@jpkrohling) know in whatever media you can find me, although I prefer to be contacted via CNCF Slack for this purpose. When doing so, please inform your GitHub handle.

**Comment by jpkrohling** [comment]
This is a final reminder to cast your vote for the OpenTelemetry Governance Committee Election 2022. If you are listed in one of the first comments on this issue, you are eligible for voting.

IMPORTANT: remember to click "cast your vote" in the final step, or your ballot will not be received. Please, check the following screenshots, showing how to successfully cast your ballot. In the second step, make sure to select your candidates.

If you have trouble voting, let me (@jpkrohling) know in whatever media you can find me, although I prefer to be contacted via CNCF Slack for this purpose. When doing so, please inform your GitHub handle.

![Screenshot 2022-10-20 at 08-48-36 Helios Voting Booth - OpenTelemetry Governance Committee Election 2022](https://user-images.githubusercontent.com/13387/196944181-77f063bc-70ad-4aae-b8fb-7bdd08d0fd7a.png)

![Screenshot 2022-10-20 at 08-49-08 Helios Voting Booth - OpenTelemetry Governance Committee Election 2022](https://user-images.githubusercontent.com/13387/196944215-b4cae6f9-f365-42d5-898e-d438f24b102d.png)

![Screenshot 2022-10-20 at 08-49-22 Helios Voting Booth - OpenTelemetry Governance Committee Election 2022](https://user-images.githubusercontent.com/13387/196944244-f8f5e219-276c-4b29-9bae-ec4cb5718952.png)

![Screenshot 2022-10-20 at 08-49-31 Confirm Vote](https://user-images.githubusercontent.com/13387/196944268-11164c89-ecb7-48a6-ab98-a9319e47c8be.png)

![Screenshot 2022-10-20 at 08-49-47 Confirm Vote](https://user-images.githubusercontent.com/13387/196944295-7ec62f1e-9968-4399-8171-06ce44e5a622.png)

![Screenshot 2022-10-20 at 08-49-55 Confirm Vote](https://user-images.githubusercontent.com/13387/196944309-47876de2-8346-43d3-991e-b0b3993e7f75.png)

**Comment by jpkrohling** [comment]
The OpenTelemetry project is proud to announce the winners of the 2022 OpenTelemetry Governance Committee (GC) election! Before we get into the results, I’d like to share some statistics about the election!

This year, 513 project members were eligible to vote. Of those, 219 cast ballots, for a participation rate of nearly 43%! For comparison, the 2021 election saw 169 ballots cast with 386 eligible voters. Participation was roughly flat year-over-year, and we’re thrilled that we’ve welcomed so many new project members and maintained a high participation rate.

With that out of the way, please join me in congratulating @alolita, @dyladan, and @mtwo on their re-election! They will be joined by long-time contributor and maintainer of OpenTelemetry Java Instrumentation @trask! All will serve a two-year term.

We’d like to thank everyone who participated – candidates, voters, and the election organizers – for their efforts. You can find the [full results of the election here](https://vote.heliosvoting.org/helios/elections/76558134-3384-11ed-8688-02871af94755/view).

(originally posted here: https://opentelemetry.io/blog/2022/gc-election-results/)

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @4demos
* @aabmass
* @aaron-ai
* @abhiprasad
* @abhishek-569
* @abhisheksurve45
* @abinet18
* @abitrolly
* @aboguszewski-sumo
* @achetronic
* @adamkaczmarski
* @adam-kiss-sg
* @adamkubon
* @adamleantech
* @adnanrahic
* @adrianna-chang-shopify
* @adrielp
* @ag-ramachandran
* @ahayworth
* @aheling11
* @akats7
* @akochavi
* @akselallas
* @alanwest
* @albertored
* @albertteoh
* @alburthoffman
* @alexanderwert
* @alexvanboxel
* @allex1
* @alolita
* @am-kinetica
* @andreasgerstmayr
* @andrewhr
* @andriysidliarskiy
* @andykellr
* @aneurysm9
* @ankcorn
* @ankit01-oss
* @antonfirsov
* @antonjim-te
* @anunarapureddy
* @anuraaga
* @anuragagarwal561994
* @architjugran
* @arielvalentin
* @arik-dig
* @arjan-saly-tfs
* @arminru
* @asafm

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @asaharn
* @as-alstar
* @aschugunov
* @ash2k
* @astencel-sumo
* @astitcher
* @a-thaler
* @atingchen
* @atoulme
* @atshaw43
* @austinlparker
* @avadhut123pisal
* @avillela
* @avzis
* @ays7
* @bachittle
* @baliedge
* @bastbu
* @bertysentry
* @bgranetzke
* @bidetofevil
* @binaryfissiongames
* @bitomaxsp
* @bjandras
* @blakeroberts-wk
* @blumamir
* @bobstrecansky
* @bogdandrutu
* @bominrahmani
* @boostchicken
* @braydonk
* @breedx-splk
* @brettmc
* @brunobat
* @bryan-aguilar
* @bryannaegele
* @bryce-b
* @bryncooke
* @carlosalberto
* @carlossscastro
* @carolabadeer
* @cartermp
* @cartersocha
* @cedricziel
* @cforce
* @chalin
* @chancez
* @charlietle
* @cheempz
* @chenx1993

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @chigia001
* @chillorb
* @chinwendu20
* @chrislightfootwild
* @chrlic
* @chrroberts-pure
* @chrsmark
* @cijothomas
* @cluas
* @cmergenthaler
* @cngzhnp
* @codeblanch
* @codeboten
* @cpanato
* @cparkins
* @cpheps
* @crobert-1
* @cromefire
* @cyrille-leclerc
* @damemi
* @danelson
* @danielbdias
* @danielodievich
* @danielsn
* @daniel-white
* @dashpole
* @datsabk
* @davidfowl
* @davidji99
* @dazuma
* @dbolduc
* @debajitdas
* @decko
* @dehaansa
* @deosu
* @derekkraan
* @devrimdemiroz
* @dewalddejager
* @dgoscn
* @dineshg13
* @djaglowski
* @djc
* @dloucasfx
* @dmarkwat
* @dmathieu
* @dmitryax
* @dmytr
* @dnelson-relativity
* @donnerbart
* @dotboris

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @dpauls
* @dpk83
* @driedas
* @dsgrieve
* @dszmigielski
* @dubonzi
* @dyladan
* @edenfed
* @edwintye
* @eedorenko
* @eerhardt
* @elias19r
* @elikatsis
* @emreyalvac
* @ericashi
* @erichsueh3
* @ericmustin
* @esigo
* @estolfo
* @ethanresnick
* @evan-bradley
* @evantorrie
* @evgenyfedorov2
* @fatsheep9146
* @fbogsany
* @fchikwekwe
* @ferd
* @fernferret
* @ff-sdesai
* @flarna
* @fmhwong
* @fracasula
* @frankcy
* @frank-dspeed
* @frapschen
* @fredthomsen
* @frzifus
* @fsmaxb
* @fstab
* @fuaiyi
* @fyuan1316
* @gabrielgiussi
* @gao-artur
* @garypwhite
* @gbbr
* @gebn
* @gillg
* @gouthamve
* @greatestusername
* @grunet

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @gsanchezgavier
* @h0cheung
* @haddasbronfman
* @haim6678
* @hanjm
* @hanyuancheung
* @haoqixu
* @harshit-splunk
* @havret
* @hdost
* @hectorhdzg
* @henrinormak
* @hexdigest
* @heyams
* @hgaol
* @hickeyma
* @hkfgo
* @hofmeisteran
* @huange7
* @humivo
* @hypnoce
* @iblancasa
* @icebergxty
* @idigdoug
* @imanshafiei540
* @indrekj
* @ishwarkanse
* @iskiselev
* @itslastday
* @jack-berg
* @jack-burridge-cfh
* @jacksonweber
* @jacobmarble
* @jamesmoessis
* @jamesnk
* @jamiedanielson
* @jaredtan95
* @jaronoff97
* @jarosal
* @jaydeluca
* @jcountsnr
* @jdoherty
* @jeanbisutti
* @jefchien
* @jeremydvoss
* @jiekun
* @jimwsplk
* @jinja2
* @jj22ee
* @jkwatson

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @jlawrienyt
* @jlegoff
* @jmacd
* @jmichalek132
* @jmsnll
* @joaopgrassi
* @johanpel
* @jonaskunz
* @jonatan-ivanov
* @jonathanwamsley
* @jorturfer
* @joshleecreates
* @jpkrohling
* @jrgns
* @jskiba
* @jsuereth
* @jtescher
* @julealgon
* @julianocosta89
* @junhuangli
* @jvmlet
* @jvoravong
* @jwilh
* @kaiwalyakoparkar
* @kalyanaj
* @kamalmarhubi
* @kangsheng89
* @karmingc
* @kaushal28
* @kausik-a
* @kaylareopelle
* @kedare
* @kenfinnigan
* @kennytrytek-wf
* @kentquirk
* @kes2464
* @kevinearls
* @kevinnio
* @kevinslin
* @khanhntd
* @khyatigandhi6
* @kielek
* @kirrg001
* @kitsutliff
* @kittylyst
* @kkujawa-sumo
* @klippx
* @kovrus
* @kpratyus
* @kristinapathak

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @kronos11
* @kuiperda
* @kyongsik-yoon
* @lachmatt
* @lalitb
* @laserphaser
* @laurit
* @ledor473
* @leewoobin789
* @legendecas
* @lewis262626
* @likethesalad
* @liubey
* @liurui-1
* @liustanley
* @lizthegrey
* @llc1123
* @lmolkova
* @lmonkiewicz
* @loomis-relativity
* @lootek
* @lquerel
* @lstrojny
* @luke6lh43
* @lukestoward
* @lunij
* @lzchen
* @macieyng
* @mackjmr
* @madvikinggod
* @maheshgpai
* @maokitty
* @mapno
* @mar4uk
* @marcalff
* @marcsanmi
* @marctc
* @mariojonke
* @martincostello
* @martinjt
* @martinkuba
* @martin-majlis-s1
* @matej-g
* @mateuszrzeszutek
* @mat-rumian
* @matt-hensley
* @matthewgrossman
* @mattmccleary
* @mattsains
* @maxksyunz

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @mcardy
* @mcinbell
* @mconnew
* @mdelapenya
* @melbgirl
* @mfogliatto
* @mhassan1
* @mhausenblas
* @michalvavrik
* @mic-max
* @mikegoldsmith
* @mitchellgale
* @mizhexiaoxiao
* @mjingle
* @mmanciop
* @mmorel-35
* @mohitk05
* @moh-osman3
* @moonbox3
* @moonheart
* @moviestoreguy
* @mrajashree
* @mralias
* @mrblonde91
* @mrod1598
* @mrsillydog
* @msnev
* @mtwo
* @muhaook
* @muripic
* @mviitane
* @mwear
* @mxiamxia
* @mx-psi
* @nachobonafonte
* @naseemkullah
* @neelayu
* @nemoshlag
* @nevay
* @newly12
* @ngnix
* @nicolastakashi
* @nirga
* @niteshs7
* @noahfalk
* @nozik
* @npellet
* @nrcventura
* @nslaughter
* @nstawski

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @rahuldimri
* @rahulhacker
* @rajim17
* @rajkumar-rangaraj
* @rangelreale
* @raphael-theriault-swi
* @rapphil
* @rassk
* @rauno56
* @rbagd
* @reese-lee
* @repl-chris
* @reyang
* @richardmcmillen
* @rmfitzpatrick
* @rnishtala-sumo
* @robbkidd
* @robertlaurin
* @roberttoyonaga
* @robo210
* @rogersd
* @ronfed
* @ronyis
* @rrschulze
* @rrva
* @runtu666
* @rypdal
* @sairamsadanala
* @sakshi1215
* @samimusallam
* @samiura
* @samsp-msft
* @sanketmehta28
* @saurabhdes
* @scbjans
* @scheler
* @schmikei
* @seankhliao
* @sebastien-rosset
* @secustor
* @seemk
* @seh
* @sergeykanzhelev
* @serkan-ozal
* @sernst
* @shalevr
* @shalper2
* @sharp-pixel
* @shaun-cox
* @sherifkayad

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @sherlouk
* @shivanshu1333
* @shuwpan
* @sigilioso
* @simenb
* @simi
* @simonegiusso
* @sirianni
* @sirzooro
* @siyuniu-ms
* @sk-
* @sky333999
* @smithclay
* @songy23
* @sourabh1007
* @splunkericl
* @sreejesh-radhakrishnan-db
* @srikanthccv
* @srprash
* @starbeast
* @starptech
* @stefankurek
* @styblope
* @sumo-drosiek
* @sungam3r
* @surbhiia
* @svetlanabrennan
* @svrnm
* @swalkinshaw
* @swar8080
* @sweetxiaodai
* @swiatekm-sumo
* @sylvainjuge
* @t2t2
* @tammy-baylis-swi
* @tarekgh
* @tavh
* @tedsuo
* @temppus
* @terev
* @theanshul756
* @theletterf
* @theoxfromoutofthebox
* @thomsontan
* @thpierce
* @tigrannajaryan
* @timannguyen
* @timothymothra
* @tj---
* @tjiuming

**Comment by dyladan** [comment]
We invite the people mentioned in this comment to vote in the OpenTelemetry Governance Committee, as they have provided more than 20 contributions to the project over the last year via GitHub. Your contributions were comments, code reviews, pull requests, among others. Thank you!

* @tomaz-s1
* @tombruijn
* @tommycpp
* @tomtaylor
* @trask
* @trejjam
* @trentm
* @tsloughter
* @tuhao1020
* @twenzel
* @ty-elastic
* @tylerbenson
* @tylerhelmuth
* @ugzuzg
* @unflxw
* @unicod3
* @utezduyar
* @utpilla
* @varunraiko
* @vasireddy99
* @vastin
* @vibhavarimandal-sumo
* @vihasmakwana
* @vihas-splunk
* @viktorhofer
* @vineethreddy02
* @vishweshbankwar
* @vitek-karas
* @viveksubr
* @vmarchaud
* @vvydier
* @wangzlei
* @weyert
* @willarmiros
* @willianpc
* @windsonsea
* @wperron
* @wu-sheng
* @wzy531a
* @xiang17
* @xiangtianyu
* @xoscar
* @xsam
* @xsoheilalizadeh
* @xuan-cao-swi
* @xvilo
* @xwgao
* @ydfu
* @yehaotian
* @yonch
