### ISSUE TITLE
REQUEST: New repository opentelemetry-php-instrumentation

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/community#1177]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-php-instrumentation

### Requested changes

Creation of a new repository.

Same ownership etc as `opentelemetry-php`
 
### Purpose

Setting up a new php extension to enable auto-instrumentation.
 
### Expected Duration

Permanent

### Repository Maintainers

- @open-telemetry/php-maintainers

**Comment by tigrannajaryan** [comment]
Repo created: https://github.com/open-telemetry/opentelemetry-php-instrumentation

Do you also need @open-telemetry/php-approvers to be approvers and @open-telemetry/php-triagers to be triagers on this repo?

**Comment by tigrannajaryan** [comment]
@open-telemetry/php-maintainers I think EasyCLA is already enabled, but please double check make the first PR is created.

**Comment by brettmc** [comment]
Yes please for approvers and triagers! Confirming that EasyCLA is enabled and working.

**Comment by tigrannajaryan** [comment]
> Yes please for approvers and triagers! Confirming that EasyCLA is enabled and working.

Done.

**Comment by tigrannajaryan** [comment]
Closing the issue, looks like all done.
