### ISSUE TITLE
REQUEST: New membership for hdost

### ISSUE THREAD

**Issue by hdost** [open-telemetry/community#1179]
### GitHub Username

@hdost 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application:
 -  https://github.com/open-telemetry/opentelemetry-rust/pull/839#issuecomment-1244863783

### Sponsors

- @jtescher 
- @TommyCpp

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-rust/pulls?q=is%3Apr+author%3Ahdost+
- https://github.com/open-telemetry/opentelemetry-java/pull/3739
- Issues responded to
- SIG projects I am involved with:
  - Rust
  - Java

**Comment by jtescher** [comment]
👍

**Comment by bogdandrutu** [comment]
invite sent.
