### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-go

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/community#1180]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go
https://github.com/open-telemetry/opentelemetry-go-contrib

### Requested changes

Give 'Admin' permissions to @MadVikingGod 
 
### Purpose

Go 1.19 has been released and Go 1.17 has be deprecated, and we follow the supported versions of go.  We need to remove the branch protection required actions to not include the g1.17, and include 1.19.
 
### Expected Duration

1 hour

### Repository Maintainers

- @open-telemetry/go-maintainers

**Comment by tigrannajaryan** [comment]
@MadVikingGod you are an admin now. Ping me when you are done.

**Comment by MadVikingGod** [comment]
@tigrannajaryan I finished the changes.  Thank you.

**Comment by tigrannajaryan** [comment]
'Admin' permissions removed.
