### ISSUE TITLE
REQUEST: New membership for @musingvirtual

### ISSUE THREAD

**Issue by musingvirtual** [open-telemetry/community#1189]
### GitHub Username

@musingvirtual

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lizthegrey 
- @austinlparker 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

I am involved with the End User Working Group. I am the lead producer on the monthly OpenTelemetry in Practice meetup, part of the team producing the OTel Unplugged event, and assist with all the other end user activities including the lean coffees and building community in the End User channel.

Links to my contributions:

OTel Unplugged planning docs [1](https://docs.google.com/document/d/1BJ9FHdJMBaeG3izkkm755eUMk6oMevvrgeDMRl6T5J4/edit) [2](https://docs.google.com/document/d/1e46iPB522QBzjXn4a7LzVpaxbsRGVUNNhW9Akn6WTGg/edit)

OpenTelemetry in Practice Meetup [1](https://www.meetup.com/opentelemetry-in-practice-meetup-group/) [2](https://github.com/open-telemetry/opentelemetry.io/pull/1618)

End User Working Group notes tracking my involvement [1](https://github.com/open-telemetry/opentelemetry.io/pull/1618)

**Comment by lizthegrey** [comment]
+1

**Comment by austinlparker** [comment]
I support.

**Comment by sharrmander** [comment]
I support too, thanks @musingvirtual for all your help in the End User WG!

**Comment by bogdandrutu** [comment]
Invite sent

**Comment by arminru** [comment]
The invitation expired. I just re-sent it. @musingvirtual PTAL in your inbox 🙂
