### ISSUE TITLE
Create a SIG for C++

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/community#120]
Though I'm not sure if we want to commit to a timeline as of yet, there is more than enough interest in C++ to start the SIG at this point. 

* Please name the GitHub repo `opentelemetry-cpp`.
* Please add @jmacd and @rnburn to the repo as approver and maintainer.
* Question: is there a CNCF zoom account available, which could be assigned to this SIG?
* I went ahead and created a gitter chat room: https://gitter.im/open-telemetry/opentelemetry-cpp

**Comment by tigrannajaryan** [comment]
@tedsuo I'd like to join the SIG. It will not be a primary SIG for me but I will probably be able to help with reviews, etc.

**Comment by tedsuo** [comment]
@tigrannajaryan of course! Great to have you. :)

**Comment by g-easy** [comment]
Please sign me up also. I'm coming from opencensus-cpp. :)

**Comment by SergeyKanzhelev** [comment]
@tedsuo - let me know if I need to change roles of existing nominees. Specifically, @jmacd if you up for maintainers commitment. 

Otherwise - see PR with nomination. Once approved and merged I will update corresponding teams for permissions for cpp repo

**Comment by tedsuo** [comment]
This all LGTM. @jmacd is probably interested in being a maintainer, but we can close this issue and open a separate one for that, if all of the infrastructure is now in place.
