### ISSUE TITLE
REQUEST: New repository opamp-java

### ISSUE THREAD

**Issue by jlegoff** [open-telemetry/community#1201]
### Affected Repository

https://github.com/open-telemetry/opamp-java

### Requested changes

Creation of a new repository.
 
### Purpose

A Java implementation of OpAmp would be useful for creating OpAmp servers (use case for Sumo Logic and New Relic). Java agents could also benefit from a client implementation in the future.
 
### Expected Duration

Permanent

### Repository Maintainers

I (@jlegoff) can be a maintainer, and @portertech suggested someone from Sumo Logic could also work on this project. Perhaps we can create a new team for this (@open-telemetry/opamp-java-maintainers)
o

**Comment by tigrannajaryan** [comment]
Discussed this in Slack. I will be the initial maintainer for the new repo. Additional approvers and maintainers will be added as per OpenTelemetry rules later.

**Comment by tigrannajaryan** [comment]
Repo created: https://github.com/open-telemetry/opamp-java
