### ISSUE TITLE
Requesting TC review for JS metrics API/SDK spec compliance

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#1204]
Requesting a compliance review from @open-telemetry/technical-committee prior to GA release. Documentation work is still underway. If there are questions you can ask myself or any of the other JS maintainers, especially @legendecas as he as done most of our metrics maintenance work or @pichlermarc since he has also done a lot of work on the metrics SDK.

**Comment by tigrannajaryan** [comment]
I added this to the next TC meeting agenda.

**Comment by reyang** [comment]
I can do it, @dyladan @legendecas would you provide a permanent link to the doc/code? Is this about the API and SDK only, or it covers some exporters (e.g. OTLP)?

**Comment by reyang** [comment]
The opentelemetry-js repo has issue templates which makes it harder to file issues found during the review, to make it easier, I'll post my findings in individual comments here.

**Comment by reyang** [comment]
API not mentioned in the spec but provided by the implementation:
* https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Meter.ts#L142
* https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Meter.ts#L156

**Comment by reyang** [comment]
[API spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#synchronous-and-asynchronous-instruments) requires a state object to be passed to the callback, I couldn't find how it is supported in opentelemetry-js, e.g. https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Meter.ts#L110.

The API SHOULD provide some way to pass state to the callback.

**Comment by reyang** [comment]
Not part of the spec compliance review but I noticed this comment:

https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Metric.ts#L67

Do we want `Inputs may not be negative.` or `Inputs must not be negative.`?

**Comment by reyang** [comment]
Since 1.13.0, the API spec allows optional attributes in the [GetMeter API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter):

https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/MeterProvider.ts#L32

**Comment by reyang** [comment]
Exemplar in the SDK spec is not yet Stable, need to be removed or hidden if the intention is to ship the initial stable JS package https://github.com/open-telemetry/opentelemetry-js/tree/d154066354863e8c682b4aa488d79c7e914bf91c/experimental/packages/opentelemetry-sdk-metrics/src/exemplar.

**Comment by reyang** [comment]
MetricReader doesn't have `ForceFlush` according to the [SDK spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader-operations).

https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/experimental/packages/opentelemetry-sdk-metrics/src/export/MetricReader.ts#L171

**Comment by reyang** [comment]
I haven't looked deeper so I could be wrong, it seems the ConsoleExporter is only supporting CUMULATIVE? https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/experimental/packages/opentelemetry-sdk-metrics/src/export/ConsoleMetricExporter.ts#L41

The specification requires both CUMULATIVE and DELTA to be supported https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/stdout.md#opentelemetry-metrics-exporter---standard-output.

**Comment by reyang** [comment]
So far I've finished reviewing the following parts:

* @opentelemetry/api-metrics
* @opentelemetry/sdk-metrics
* @opentelemetry/sdk-node

I'll cover these parts next week:

* @opentelemetry/exporter-metrics-otlp-grpc
* @opentelemetry/exporter-metrics-otlp-http
* @opentelemetry/exporter-metrics-otlp-proto

I don't plan to cover these parts since the spec is not yet marked as Stable (if a dry run would be helpful, please let me know and I can do it):

* @opentelemetry/exporter-prometheus
* Exemplar in @opentelemetry/sdk-metrics
* Exponential Bucket Histogram in @opentelemetry/sdk-metrics

**Comment by legendecas** [comment]
> API not mentioned in the spec but provided by the implementation:
> 
> * https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Meter.ts#L142
> * https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Meter.ts#L156

This is defined in the spec with a different name: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#multiple-instrument-callbacks. Also, the spec requires the registered callbacks to be able to be unregistered: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-counter-operations.

**Comment by legendecas** [comment]
> [API spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#synchronous-and-asynchronous-instruments) requires a state object to be passed to the callback, I couldn't find how it is supported in opentelemetry-js, e.g. https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/api/src/metrics/Meter.ts#L110.

> The API SHOULD provide some way to pass state to the callback.

It is quite easy for JavaScript to capture variable in lambdas, so by the statement in the spec:

> The API SHOULD provide some way to pass state to the callback. [OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#api) authors MAY decide what is the idiomatic approach (e.g. it could be an additional parameter to the callback function, or captured by the lambda closure, or something else).

I believe the JavaScript API is sufficient to cover the requirements.

**Comment by legendecas** [comment]
> Exemplar in the SDK spec is not yet Stable, need to be removed or hidden if the intention is to ship the initial stable JS package https://github.com/open-telemetry/opentelemetry-js/tree/d154066354863e8c682b4aa488d79c7e914bf91c/experimental/packages/opentelemetry-sdk-metrics/src/exemplar.

Exemplar is not exposed in the SDK as a public interface yet: https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-sdk-metrics/src/index.ts.

**Comment by pichlermarc** [comment]
> MetricReader doesn't have `ForceFlush` according to the [SDK spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md?rgh-link-date=2022-11-04T22%3A15%3A03Z#metricreader-operations).
> 
> [open-telemetry/opentelemetry-js@`d154066`/experimental/packages/opentelemetry-sdk-metrics/src/export/MetricReader.ts#L171](https://github.com/open-telemetry/opentelemetry-js/blob/d154066354863e8c682b4aa488d79c7e914bf91c/experimental/packages/opentelemetry-sdk-metrics/src/export/MetricReader.ts#L171)

Hmm, correct. :thinking: 
However, it is referenced in the [spec for the `MeterProvider`.](https://github.com/open-telemetry/opentelemetry-specification/blob/740524363835162bb9ff6b017e66f3a0b150a73c/specification/metrics/sdk.md?plain=1#L132-L134)

> ForceFlush MUST invoke ForceFlush on all registered [MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader) and [Push Metric Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#push-metric-exporter) instances.

Both the [Python](https://github.com/open-telemetry/opentelemetry-python/blob/778c4b1cffdd448c531c868a9470618eb8a6517c/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/export/__init__.py#L351) and [Java](https://github.com/open-telemetry/opentelemetry-java/blob/51ff803eb3d47d9b1fbe5e7de1aae004e9f52b40/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java#L50) SDK implementations seem to have solved it in the same way. May be worth opening a spec issue over if one does not yet exist. :thinking:

**Comment by dyladan** [comment]
I can create issues without the template so i'll move these into the JS repo

**Comment by dyladan** [comment]
Created issues so discussions can be moved to those. Thanks @reyang
