### ISSUE TITLE
Nomination: @cartermp for Governance Committee

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#1209]
As per https://github.com/open-telemetry/community/blob/main/governance-charter.md#eligibility-for-candidacy, anyone may nominate themself or another person for GC. I nominate @cartermp and am a Member of Standing, so count as one of the three Members of Standing required. Carter will also need to accept if he so wishes once he is back from PTO.

**Comment by sharrmander** [comment]
I support this nomination.

**Comment by cartermp** [comment]
I accept! Will formally run once back from PTO.

**Comment by lizthegrey** [comment]
Three members of standing have ratified including self-ratification.

**Comment by svrnm** [comment]
I support this nomination :-)

Just a formality:
> Anyone may nominate either themselves or someone else to be a candidate in the election. To be ratified as a candidate, the nominee must accept the nomination and three Members of Standing (including the nominator, if she/he has standing) **from three different employers**, must endorse the nomination.

@lizthegrey & @cartermp you're both with honeycomb, right? So I fixed that.

**Comment by lizthegrey** [comment]
oh, oops, yes, good call. Thank you for fixing!
