### ISSUE TITLE
REQUEST: New membership as Ruby SIG approver for luvtechno

### ISSUE THREAD

**Issue by luvtechno** [open-telemetry/community#121]
### GitHub Username

@luvtechno

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x]  I ~am~ will be actively contributing to 1 or more OpenTelemetry subprojects
    - I will actively contribute to the OpenTelemetry Ruby subproject
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @fbogsany
- @bogdandrutu

**Comment by bogdandrutu** [comment]
@fbogsany can you please approve/+1 this?

**Comment by SergeyKanzhelev** [comment]
@fbogsany confirmed over the e-mail.

@luvtechno welcome!

**Comment by luvtechno** [comment]
Thank you!
