### ISSUE TITLE
REQUEST: New membership for kristinapathak

### ISSUE THREAD

**Issue by kristinapathak** [open-telemetry/community#1213]
### GitHub Username

@kristinapathak

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Aneurysm9 
- @codeboten

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored
https://github.com/open-telemetry/opentelemetry-operator/pull/1040
https://github.com/open-telemetry/opentelemetry-operator/pull/1070
https://github.com/open-telemetry/opentelemetry-operator/pull/1090
- PRs reviewed
https://github.com/open-telemetry/opentelemetry-operator/pull/1030
https://github.com/open-telemetry/opentelemetry-operator/pull/1041
https://github.com/open-telemetry/opentelemetry-operator/pull/1068
https://github.com/open-telemetry/opentelemetry-operator/pull/1069
https://github.com/open-telemetry/opentelemetry-operator/pull/1079
https://github.com/open-telemetry/opentelemetry-operator/pull/1087
https://github.com/open-telemetry/opentelemetry-operator/pull/1124
https://github.com/open-telemetry/opentelemetry-operator/pull/1127
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14464
- Issues responded to
https://github.com/open-telemetry/opentelemetry-operator/issues/1011
https://github.com/open-telemetry/opentelemetry-operator/issues/1122
https://github.com/open-telemetry/opentelemetry-operator/issues/1034
https://github.com/open-telemetry/opentelemetry-operator/issues/1095
- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-operator

**Comment by Aneurysm9** [comment]
I support

**Comment by codeboten** [comment]
+1

**Comment by bogdandrutu** [comment]
Invite sent
