### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-operator - create group for target allocator

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/community#1218]
### Affected Repository
https://github.com/open-telemetry/opentelemetry-operator

### Requested changes

Create a group (e.g. `operator-ta-maintainers`) for maintaining the target allocator component of the operator - https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator

This group will be given write access to the `cmd/otel-allocator`.

### Purpose

The target allocator (TA) is a component that the operator deploys to manage Prometheus metrics collection. TA is maintained by a different set of people that do not necessarily have expertise in building k8s operator. This group will helps us better manage roles in the operator and ping appropriate people on changes to the TA.
 
### Repository Maintainers

- @open-telemetry/operator-maintainers

**Comment by pavolloffay** [comment]
Following users should be added to the group: @kristinapathak @jaronoff97 @Aneurysm9

**Comment by secustor** [comment]
Can you add me to the list too?

**Comment by pavolloffay** [comment]
> Can you add me to the list too?

absolutely. @secustor is a long time contributor to the target allocator

**Comment by tigrannajaryan** [comment]
> This group will be given write access to the `cmd/otel-allocator`.

Can you clarify how will you do this? Does github allow giving write access only to individual sub-directories?

**Comment by jaronoff97** [comment]
@tigrannajaryan this is how the website's docs are [currently setup](https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/CODEOWNERS#L18-L32) The plan here would be to add a stanza to the CODEOWNERS doc in the operator repo that would allow `@open-telemetry/operator-ta-maintainers` to maintain the `cmd/otel-allocator` directory. You can see that done [here](https://github.com/open-telemetry/opentelemetry-operator/compare/main...jaronoff97:opentelemetry-operator:codeowners)

**Comment by tigrannajaryan** [comment]
operator-ta-maintainers team is now created and requested github handles added to the team.
