### ISSUE TITLE
REQUEST: New membership for @reese-lee

### ISSUE THREAD

**Issue by reese-lee** [open-telemetry/community#1221]
### GitHub Username

@reese-lee

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @cartermp
- @TylerHelmuth 
- @austinlparker

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

* Co-organizer for the [OpenTelemetry End User Discussion Group](https://opentelemetry.io/blog/2022/new-end-user-resources/#monthly-discussion-group)
* One of the primary contacts for the private #otel-endusers CNCF Slack channel 
* Co-organizer for OTel Unplugged Day, an event for the OpenTelemetry community taking place during KubeCon NA
* Talks and blog posts advocating for OpenTelemetry:
  * [Where the Heck are my Spans](https://vi.to/hubs/o11yfest/videos/5088) - o11yFest talk
  * [Tail-Based Sampling in the OpenTelemetry Collector](https://www.youtube.com/watch?v=l4PeclHKl7I) - KubeCon EU talk
  * [Tail Sampling with OpenTelemetry: Why it's useful, how to do it, and what to consider](https://opentelemetry.io/blog/2022/tail-sampling/) - OpenTelemetry.io blog post
  * [CNCF Live Webinar: OTel Me All About OpenTelemetry](https://community.cncf.io/events/details/cncf-cncf-online-programs-presents-cncf-live-webinar-otel-me-all-about-opentelemetry/) 
  * [Lightning Talk: OTel Me How to Build a Data Pipeline for Observability](https://sched.co/1Avqa) Upcoming lightning talk at Open Observability Day, a co-located event for KubeCon NA 2022

**Comment by TylerHelmuth** [comment]
I support!

**Comment by jpkrohling** [comment]
I support!
