### ISSUE TITLE
REQUEST: New membership for @TheAnshul756

### ISSUE THREAD

**Issue by TheAnshul756** [open-telemetry/community#1226]
### GitHub Username

@TheAnshul756

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @srikanthccv 
- @lzchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored
    - [Metrics instrumentation flask (#1186)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1186)
    - [Metric instrumentation asgi (#1197)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1197)
    - [Metric instrumentation pyramid (#1242)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1242)
    - [Metric instrumentation fastapi (#1199)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1199)
    - [Metric instrumentation falcon (#1230)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1230)
    - [uninstruemnt existing instances before uninstrumenting fastapi class (#1258)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1258)
    - [Uninstruemnt existing instances before uninstrumenting falcon class (#1341)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1341)
    - [fix check of is_otel_instrumented (#1313)](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1313)
- Issues responded to
    - [Warning triggered by asgi.OpenTelemetryMiddleware (#1335)](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1335)
- SIG projects I am involved with
    - opentelemetry-python-contrib

**Comment by srikanthccv** [comment]
I support. Thanks for your contributions @TheAnshul756

**Comment by SergeyKanzhelev** [comment]
Welcome @TheAnshul756! Invite sent
