### ISSUE TITLE
REQUEST: Make the Opentelemetry-go Beta project public.

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/community#1243]
### Affected Github Project

[Go Metrics Beta Project](https://github.com/orgs/open-telemetry/projects/32)

### Requested changes

Make the project public, like the [Alpha Project](https://github.com/orgs/open-telemetry/projects/22)
 
### Purpose

This project is intended to track the progress of the beta and should be available for anyone to view.
 
### Expected Duration

This should be public in perpetuity. 

### Repository Maintainers

- @open-telemetry/go-maintainers

**Comment by MrAlias** [comment]
@open-telemetry/technical-committee can we get some help with this one? I would like to share our progress out to the broader community, but cannot without these becoming public.

Can we also make the other related projects public:

- https://github.com/orgs/open-telemetry/projects/33
- https://github.com/orgs/open-telemetry/projects/34
- https://github.com/orgs/open-telemetry/projects/35

Regarding permissions for these projects we have set a base role to read for all these project with appropriate SIG groups given write and admin roles for the project.

![20221108_104940](https://user-images.githubusercontent.com/5543599/200650190-5f0039df-ec2d-4566-a988-bdea6eb93337.png)

This should ensure these projects, once public, are not modifiable by anyone outside the project, but will be readable.

**Comment by tigrannajaryan** [comment]
Sorry for the delay, I missed this one. All 4 projects are public now.
