### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry.io -- end user WG gh team

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#1249]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io

### Requested changes

Create a github team for the end-user-working group, initial members: @reese-lee , @musingvirtual, @sharrmander 
 
### Purpose

Similar to the language SIGs for /instrumentation/<language> we want to have the end-user WG have ownership for /community/end-user (get asked & give approval for changes within that directory)
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/docs-maintainers

**Comment by arminru** [comment]
I created @open-telemetry/end-user-wg and added @reese-lee and @sharrmander.

@musingvirtual please open a request to join the organization as a member so we can add you to the team as well (see https://github.com/open-telemetry/community/blob/main/community-membership.md#member).

Thank you!

**Comment by arminru** [comment]
@open-telemetry/end-user-wg does this mean the content in https://github.com/open-telemetry/community/tree/main/working-groups/end-user will be moved to https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/community/end-user?

**Comment by musingvirtual** [comment]
Hi Armin, please find my membership request here.

https://github.com/open-telemetry/community/issues/1189

**Comment by sharrmander** [comment]
> @open-telemetry/end-user-wg does this mean the content in https://github.com/open-telemetry/community/tree/main/working-groups/end-user will be moved to https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/community/end-user?

I have this same question. I think it is important to make the end-user assets easily discoverable for new folks, which is why I originally put them under the /community repo. In my mind, putting them under the website repo doesn't seem an intuitive location.

**Comment by cartermp** [comment]
Yeah, I think what we've learned in general that the website gets a ton of traffic and it's where people go first to find things. I'm not opposed to also having things in the community repo, but in its current form it's for a lot more than hosting end-user WG stuff.

**Comment by svrnm** [comment]
Here would be my suggestion for a _rule of thumb_ (exceptions will apply): official documents (like the Mission,Vision,Values or charters), that are owned by the GC,TC should live in this repo and we pull them in via a submodule eventually, but everything that's end-user or contributor-facing should ideally live with the website (as @cartermp said, for reach & findability). But yeah, we should have that discussion somewhere else

**Comment by svrnm** [comment]
the initialreas of this issue was
