### ISSUE TITLE
REQUEST: New membership for melbgirl

### ISSUE THREAD

**Issue by melbgirl** [open-telemetry/community#1251]
### GitHub Username

@melbgirl

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @svrnm 
- @austinlparker 
- @cartermp 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: [1691](https://github.com/open-telemetry/opentelemetry.io/pull/1691), [1609](https://github.com/open-telemetry/opentelemetry.io/pull/1609), [1559](https://github.com/open-telemetry/opentelemetry.io/pull/1559), [1691](https://github.com/open-telemetry/opentelemetry.io/pull/1691) 
- Co-organizer for [OTel Unplugged Day](https://opentelemetry.io/blog/2022/otel-unplugged-kubecon-na/), an event for the OpenTelemetry community taking place during KubeCon NA
- Support-organizer for the [OpenTelemetry End User Discussion Group](https://opentelemetry.io/blog/2022/new-end-user-resources/#monthly-discussion-group)

**Comment by austinlparker** [comment]
I support

**Comment by cartermp** [comment]
I support!

**Comment by svrnm** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @melbgirl!
