### ISSUE TITLE
REQUEST: New repository opentelemetry-profiling

### ISSUE THREAD

**Issue by petethepig** [open-telemetry/community#1262]
Hello,

I am part of the profiling working group and we recently had our [profiling vision](https://github.com/open-telemetry/oteps/blob/main/text/profiles/0212-profiling-vision.md) approved. Now we are making steps towards a more formal OTEP and as part of that we would like to set up a benchmarking suite in order to evaluate and compare the various formats.

For more context see this [google doc](https://docs.google.com/document/d/1Ba1F1PjRtW4AZ6qurUrBjw6bz5NiKqIs2WQQ2N2FR6A/edit#heading=h.nhcufnxt0tol) and [this example repository](https://github.com/petethepig/otel-profiling-benchmark) which have been discussed within the working group.

### Affected Repository

https://github.com/open-telemetry/opentelemetry-profiling

### Requested changes

Creation of a new repository.
 
### Purpose

Setting up a repo for [profiling benchmark code](https://github.com/petethepig/otel-profiling-benchmark). 
 
### Expected Duration

Potentially permanent or at least until the profiling OTEP is approved

### Repository Maintainers

We'll follow up with our sponsoring TC members (cc @tigrannajaryan and @jsuereth) regarding creating a dedicated group for this.

**Comment by tigrannajaryan** [comment]
Does it need to be a separate repository just for the benchmark? Do you anticipate any other aspects of profiling requiring their own repositories? Perhaps combine them all into one repository for profiling related code? I assume in the future the language-specific implementations of profiling will go into the already existing repos for languages that we have, so you only need a repo to store things that are not language specific, are probably experimental and not needed in the final implementations of profiling.

**Comment by petethepig** [comment]
@tigrannajaryan Fair enough — let's do one repo. Do you think `https://github.com/open-telemetry/opentelemetry-profiling` would be a good name?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan Fair enough — let's do one repo. Do you think `https://github.com/open-telemetry/opentelemetry-profiling` would be a good name?

@petethepig Sounds good. I will create the repo.

I will need to know the github usernames of initial maintainers and approvers. Anyone who has been regularly participating the profiling SIG meeting qualifies, but they need to register as OpenTelemetry members if they haven't already.

**Comment by tigrannajaryan** [comment]
Repo created https://github.com/open-telemetry/opentelemetry-profiling

**Comment by tigrannajaryan** [comment]
@petethepig The repo is created. I need github user names of Maintainers, Approvers and Triagers to give them the permissions.
