### ISSUE TITLE
REQUEST: User group maintenance: add @dineshg13 as a Go auto-instrumentation approver

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1264]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go-instrumentation

### Requested changes

Please add @dineshg13 to the @open-telemetry/go-instrumentation-approvers group.

### Purpose

Dinesh is a founding member of the SIG and looking to help get it off the ground by assuming approver duties.

**Comment by dineshg13** [comment]
@arminru Thanks. I have created the issue https://github.com/open-telemetry/community/issues/1267

**Comment by arminru** [comment]
Invited to the org and added to the team. Welcome, @dineshg13!

**Comment by dineshg13** [comment]
Thanks @arminru @MrAlias
