### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-php-instrumentation-extension

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#1266]
Affected Repository
https://github.com/open-telemetry/opentelemetry-php-instrumentation-extension

Requested changes
Creation of a new repository.

Same ownership etc as opentelemetry-php

Purpose
Setting up a new php extension to enable auto-instrumentation-extension

Expected Duration
Permanent

Repository Maintainers
https://github.com/orgs/open-telemetry/teams/php-maintainers

**Comment by trask** [comment]
ping @open-telemetry/technical-committee

**Comment by bobstrecansky** [comment]
@yurishkuro - we don't want a new repo, we are just looking to get admin privileges on this repo.

**Comment by yurishkuro** [comment]
That's not what the ticket says. Please update it to accurately reflect the request.
