### ISSUE TITLE
REQUEST: User group maintenance: add @pellared  as a Go auto-instrumentation approver

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1274]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go-instrumentation

### Requested changes

Please add @pellared  to the @open-telemetry/go-instrumentation-approvers group.

### Purpose

Robert is a founding member of the SIG and looking to help get it off the ground by assuming approver duties.

**Comment by tigrannajaryan** [comment]
Done.
