### ISSUE TITLE
REQUEST: New membership for vvydier

### ISSUE THREAD

**Issue by vvydier** [open-telemetry/community#1278]
### GitHub Username

@vvydier

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @nachoBonafonte 
- @bryce-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored https://github.com/open-telemetry/opentelemetry-swift/pulls?q=is%3Apr+is%3Amerged+author%3Avvydier+
- Issues responded to https://github.com/open-telemetry/opentelemetry-swift/issues?q=vvydier 
- Issues responded on slack https://cloud-native.slack.com/archives/C01NCHR19SB/p1664985185776599
- SIG projects I am involved with
  Proposed and participate in Swift SIG

**Comment by bryce-b** [comment]
I support

**Comment by nachoBonafonte** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @vvydier!

**Comment by vvydier** [comment]
Thank you!
