### ISSUE TITLE
Traces & sensitive data: Should trace contain a request or response body?

### ISSUE THREAD

**Issue by sanasz91mdev** [open-telemetry/community#1279]
Hello

Should a trace contain an entire request or response body of API ? 

An API request and response may contain sensitive data like CVV, PIN etc.
Is there a way to mask sensitive data in traces or is it the responsibility of the developers using open telemetry libraries to secure data being added as span attributes?

Also, Is there a standard guide that would contain that what a traces must/must not contain?

Regards,

**Comment by dmathieu** [comment]
No, your trace shouldn't/doesn't need to contain the entire request and response.
You can see the data auto-instrumentations will provide: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md

Of course, you can and should augment those spans with additional data related to your own application.

If you need to remove sensitive/PII data from spans, you the best place to do so would be in a collector processor, for example, with the redactionprocessor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor

**Comment by sanasz91mdev** [comment]
> No, your trace shouldn't/doesn't need to contain the entire request and response. You can see the data auto-instrumentations will provide: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md

When you say that they should not. Do you mean it from security perspective? Yes i use autoinstrumentation in js and it does not log request, response. So that's the best guide , right?

**Comment by dmathieu** [comment]
Yes. But especially regarding the amount of data that would generate.

**Comment by sanasz91mdev** [comment]
> Yes. But especially regarding the amount of data that would generate.

So what i understand is that as a best practice we link trace id with log id of application requests and then person should see logs for any such details like request & response body ..

**Comment by dmathieu** [comment]
No, I'm saying you don't need to log/trace the request and response body at all.

**Comment by sanasz91mdev** [comment]
> No, I'm saying you don't need to log/trace the request and response body at all.

But if you want to debug issues , how will one investigate if there are no application logs that contains request and response?

**Comment by trask** [comment]
@sanasz91mdev also check out https://github.com/open-telemetry/oteps/pull/219

**Comment by sanasz91mdev** [comment]
@trask  so its ok to have request, response payload attached to a trace?
