### ISSUE TITLE
Legal: Copywrite notice

### ISSUE THREAD

**Issue by pellared** [open-telemetry/community#1280]
Most of OTel repositories are using dependencies with licenses (e.g. MIT, Apache-2.0) that AFAIK require a copywrite notice. I am not sure if any OTel repository has any copywrite notice file.

Should the repositories contain a `NOTICE` file (which is even mentioned in the Apache-2.0 license text)?

Reference: https://infra.apache.org/licensing-howto.html

Side question: Do we have any requirements regarding OTel repositories?

PS. I am not a lawyer 😉

**Comment by dyladan** [comment]
We may be able to autogenerate these in many cases. For example we should be able to generate a NOTICE file from the lockfiles in node.

**Comment by yurishkuro** [comment]
I'd expect the orgs that care about supply chain to use automated tools that scan dependencies, which would be way more comprehensive than any manually-written NOTICE file. Curiously, Apache policy [1] says "_ if _ the Work includes a "NOTICE" text file as part of its distribution...", i.e. doesn't say that it must include it.

[1]: https://www.apache.org/licenses/LICENSE-2.0.html#redistribution

**Comment by pellared** [comment]
> I'd expect the orgs that care about supply chain to use automated tools that scan dependencies, which would be way more comprehensive than any manually-written NOTICE file. Curiously, Apache policy [1](https://www.apache.org/licenses/LICENSE-2.0.html#redistribution) says "_ if _ the Work includes a "NOTICE" text file as part of its distribution...", i.e. doesn't say that it must include it.

But the dependency (aka "Work") may have it

**Comment by pellared** [comment]
Also thanks to https://en.m.wikipedia.org/wiki/Berne_Conventioiit does not seems to be required almost anywhere

**Comment by pellared** [comment]
@trask Thanks. Yes, you are right and the examples are correct 👍 

I had a conversation with Splunk's legal team. Below is the summary.

### 1. Regarding @yurishkuro [comment](https://github.com/open-telemetry/community/issues/1280#issuecomment-1297212701)
 
The fact that a downstream user should scan the code DOES NOT remove the obligation to provide copyright/license notifications required by many OSS licenses. Apache 2.0, in the clause right before the clause that I cited [here](https://github.com/open-telemetry/community/issues/1280#issuecomment-1297140654) states:

> You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Work". 

Providing the copyright attribution and license notice is NOT optional if you want to distribute/contribute the code.

### 2. What requires notices

Any 3rd party code that is included in a submission to OTel should be given attribution per the terms of the corresponding license. This includes 3rdy party code that is:

**A)** copied into the repository;

**B)** distributed (embedded) in object/compiled form.

Many of the OTel components are distributed as packages or binaries (which are object/compiled forms of distribution).

### 3. NOTICE file

The use of the NOTICE file to provide notice is just one option.

CC @governance-committee

**Comment by yurishkuro** [comment]
Sometimes stupid reasons produce stupid solutions. Here's one stupid solution:
```
NOTICE file

(1) The dependencies for this project are listed in pom.xml 
(2) All copyright, patent, trademark, and attribution notices from these dependencies are hereby incorporated.
```
(1) - attribution
(2) - notices included

**Comment by trask** [comment]
> I had a conversation with Splunk's legal team

just as an fyi, the CNCF service desk also provides [legal services](https://github.com/cncf/servicedesk#legal-services). the @open-telemetry/governance-committee members are able to open CNCF service desk tickets on behalf of the OpenTelemetry community.

**Comment by dyladan** [comment]
> ### 2. What requires notices
> Any 3rd party code that is included in a submission to OTel should be given attribution per the terms of the corresponding license. This includes 3rdy party code that is:
> 
> **A)** copied into the repository;
> 
> **B)** distributed (embedded) in object/compiled form.
> 
> Many of the OTel components are distributed as packages or binaries (which are object/compiled forms of distribution).

Does this include distributions like JS, ruby, python, and others which don't actually include their dependencies in the distributed package, but instead a manifest (package.json in case of node.js) which instructs the package manager where to go to get the dependency? In this case we're not actually distributing the dependency right?

**Comment by pellared** [comment]
> Does this include distributions like JS, ruby, python, and others which don't actually include their dependencies in the distributed package, but instead a manifest (package.json in case of node.js) which instructs the package manager where to go to get the dependency? In this case we're not actually distributing the dependency right?

AFAIK, no as the dependencies are not embedded. These distributions do not contain "compiled" code of those dependencies.
 
> edit: am I also correct in assuming this would not apply to any development-only dependencies like the test suite, linters, and related tooling which is not needed to run OTel on end-user production systems?

Correct.

**Comment by pellared** [comment]
I do not think so. Personally, I think that the releases from [these](https://github.com/open-telemetry/community/issues/1280#issuecomment-1335817395) repositories should include copywrite and license notices. I let the @open-telemetry/governance-committee to figure it out how to address the issue.

**Comment by trask** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation releases already include license and notice files from 3rd party dependencies that are redistributed.

@open-telemetry/collector-maintainers @open-telemetry/collector-contrib-maintainer @open-telemetry/dotnet-instrumentation-maintainers @open-telemetry/go-instrumentaiton-maintainers can you review this issue and comment how you are managing license and notice files for 3rd party dependencies which you are redistributing (if any)? thx!

**Comment by pellared** [comment]
Regarding https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation I have created https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1706 which was planned for [1.0.0-rc](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/milestone/2) milestone during SIG meeting.

**Comment by pellared** [comment]
Addressed for .NET Automatic Instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2134

**Comment by jpkrohling** [comment]
I have opened a ticket with the CNCF to clarify our legal requirements (CNCFSD-1647).

**Comment by TylerHelmuth** [comment]
It is _possible_ that the [operator and its images](https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-operator) need to be considered in this issue.

**Comment by jpkrohling** [comment]
There hasn't been an update to the ticket yet, probably because folks are focused on KubeCon, but I pinged them and will post an update here as soon as I have it.

**Comment by TylerHelmuth** [comment]
It is also possible that the opentelemetry-demo images need to be considered.

**Comment by jpkrohling** [comment]
I pinged the CNCF helpdesk again, still waiting.

**Comment by jpkrohling** [comment]
I still didn't get an official answer from Legal (the ticket is still open), but I did hear back from @caniszczyk. Excerpt:

> in short, the answer is generally yes, you need to include the NOTICE file in distributed binaries per Apache license

I would work with the assumption that we should provide attribution and that including the NOTICE file is the preferred way to go.

**Comment by trask** [comment]
> I would work with the assumption that we should provide attribution and that including the NOTICE file is the preferred way to go.

@pellared does this answer your question/concern?

**Comment by pellared** [comment]
@trask This is confirming that we can follow https://infra.apache.org/licensing-howto.html. I think it would be describe it e.g. under [CONTRIBUTING.md](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md) as part of this issue. Do you agree?

I also created https://github.com/open-telemetry/opentelemetry-collector-releases/issues/364. In my opinion all other repositories are already compliant with the licensing and copywrite requirements.

**Comment by trask** [comment]
I'm not sure if we should specifically recommend https://infra.apache.org/licensing-howto.html, since that page is about requirements for Apache Software Foundation projects, which are stricter in some cases than the requirements of the Apache License itself.

Though I do really like that page's sections on bundling.

I can try sending a PR to https://github.com/cncf/foundation introducing a new page `bundling-third-party-dependencies.md`, based on the ASF bundling sections, if that sounds like a good resolution?

**Comment by jpkrohling** [comment]
It would be great to have that information available publicly, @trask. I think it's a good idea.

**Comment by pellared** [comment]
@trask @jpkrohling I agree. I am closing this issue.
