### ISSUE TITLE
Request larger runner support for GitHub Actions.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1281]
The Demo SIG has encountered significant challenges in regards to build time for releases with standard GitHub Actions runners. A full x86 build takes [an hour](https://github.com/open-telemetry/opentelemetry-demo/actions/runs/3315575864) currently; This is obviously challenging on its own, but we would like to perform multi-arch builds to resolve issues with the demo running on Apple Silicon. These multi-platform builds take over [4 hours](https://github.com/open-telemetry/opentelemetry-demo/actions/runs/3313405848). I'll provide more details below.

Per [this page](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners), Teams/Enterprise plans have access to larger runners if requested. Would we be able to request these runners in order to see if throwing more resources at the problem helps? 

--

Our build times are significantly impacted by the overhead required for gRPC builds in several languages (C++, PHP, etc.). We aren't able to use local caching, because runners are ephemeral. We also are required to build each stage completely in the target architecture (can't build/share a x86 gRPC layer with an arm64 binary layer for example), so we can't do platform targeting in the Dockerfile itself to 'quickly' build underlying layers then only emulate arm for the final compilation step.

The only other thing we can really think to do would be to refactor the Dockerfiles to build + publish base images for our 'slow' builds, but since the base image would need OpenTelemetry libraries itself in the case of C++, I feel like we'd just be regenerating it every month anyway?

**Comment by austinlparker** [comment]
@open-telemetry/technical-committee Are y'all the GitHub admins? Would you be able to enable larger runners?

**Comment by mtwo** [comment]
@bogdandrutu @carlosalberto the TC owns GitHub permissions, correct? Who should Austin work with on the TC?

**Comment by dyladan** [comment]
I think @SergeyKanzhelev was in discussions with CNCF about the enterprise account. He may have some details

**Comment by trask** [comment]
The initial discussions (~2 years ago) were directly with GitHub, though I'm not sure if things have changed since then. I have the original GitHub contacts if needed.

I'd be interested to look over the admin settings for the GitHub org first, to see if there's any mention already of cost limits in place on the org. Other than the cost question, it looks doesn't look difficult to configure large runners based on link @austinlparker provided above, and I generally support the idea of throwing hardware at the problem at least for the time being.

If anyone from the TC wants to ping me on slack I can help with this.

**Comment by yurishkuro** [comment]
We also have an outstanding invitation to join CNCF Enterprise account, which is likely to have higher limits on the runners.

**Comment by bogdandrutu** [comment]
Access Log:

* Created a new runner with ubuntu 16 cores, price for this is 0.064 per minute of usage, limited to max 15 at a time.
* Created a runner group with only demo repo.

Looks like it works, but we need to pay attention to cost.

**Comment by bogdandrutu** [comment]
I disabled this experiment, we consumed only for the first build 634minutes * 0.064 => 40.576$ 

This is too much to justify the pros (build was still failing after 5h). Happy to re-enable if we get some info from CNCF about the budget we have and how much we can use.

**Comment by SergeyKanzhelev** [comment]
CC: @jeefy to comment on "allowance" for the project

**Comment by trask** [comment]
I've opened a CNCF Service Desk ticket to inquire about allowance / costs.

**Comment by dyladan** [comment]
@trask assigning you since you made the ticket

**Comment by RobertKielty** [comment]
@trask  I Just updated the Service Desk req update please check the new Github Action runners available to the projects and let me know when you first start making use of the larger runners.

**Comment by trask** [comment]
FYI we now have access to Arm GitHub runners, see #1821, and you can open a repo maintenance request to get access

**Comment by trask** [comment]
@austinlparker will that resolve this issue?

**Comment by trask** [comment]
GitHub just recently announced official GitHub Arm runners, it would be great if someone wants to try these out (it may require @open-telemetry/technical-committee to 

https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

> GitHub is ecstatic to unveil ArmⓇ-based Linux and Windows runners for GitHub Actions are now in Public Beta.

OpenTelemetry is under the CNCF's GitHub Enterprise account, so we should have access to this feature

> These runners are available to our customers on our GitHub Team and Enterprise Cloud plans.

**Comment by austinlparker** [comment]
If someone could check and turn these on for the demo repo, that’d be swell

**Comment by trask** [comment]
> If someone could check and turn these on for the demo repo, that’d be swell

done! see #2156 for more details
