### ISSUE TITLE
Need calendar event for configuration WG

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1286]
The configuration working group needs a new calendar event, the group currently meets every 2 weeks, on Fridays at 10:30AM PT.

Related issue:

https://github.com/open-telemetry/opentelemetry-specification/issues/2920

**Comment by codeboten** [comment]
Pinging @carlosalberto as the sponsoring TC member

**Comment by arminru** [comment]
@open-telemetry/governance-committee can someone please create a meeting notes doc owned by the GC Google Account?

**Comment by dyladan** [comment]
@codeboten do you have an existing document? If not I can create one owned by the GC.

**Comment by dyladan** [comment]
Also I need a more specific start date for the event. Do you meet this Friday the 11th or did you meet last Friday the 4th? What zoom link have you been using?

**Comment by dyladan** [comment]
Looks like armin already created a calendar invite. I added a doc link to it but here is the link https://docs.google.com/document/d/1uNgWQLQZcSVfBLRXfW9XCVJmKa5NH9R15fSOXhmpGWw/edit
