### ISSUE TITLE
REQUEST: New membership for @JaredTan95

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/community#1289]
hi, I request org member with https://github.com/open-telemetry/community/issues/1059 and I accept it, and I am a member already. 

But, I found today, I am not in the org and not a member.

if possible, I request to be a `triager` of [opentelemetry-col-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib). :-P
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS#L45
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS#L205

### GitHub Username
https://github.com/JaredTan95/

### List of contributions to the OpenTelemetry project
- PRs reviewed / authored
  - [otel col contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls/JaredTan95)
  - [opentelemetry helm charts](https://github.com/open-telemetry/opentelemetry-helm-charts/pulls?q=is%3Apr+author%3AJaredTan95+is%3Aclosed)
  - [opentelemetry demo](https://github.com/open-telemetry/opentelemetry-demo/pulls?q=is%3Apr+author%3AJaredTan95+is%3Aclosed)

- Issues responded to
- SIG projects I am involved with

**Comment by SergeyKanzhelev** [comment]
I resent the invite to join the org. Not sure why the original invite wasn't sent. As for the triager group - please work with maintainers of the specific SIG - they can approve roles and add you to corresponding GitHub teams

**Comment by JaredTan95** [comment]
> I resent the invite to join the org. Not sure why the original invite wasn't sent. As for the triager group - please work with maintainers of the specific SIG - they can approve roles and add you to corresponding GitHub teams

👌
