### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-js-api

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#1290]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-js-api

### Requested changes

Archive repository
 
### Purpose

API package has been merged back into the main opentelemetry js repo.
 
### Expected Duration

n/a

### Repository Maintainers

- @open-telemetry/javascript-maintainers

**Comment by arminru** [comment]
@dyladan Do you want to add a banner to the README indicating why it was archived and where people should look for it instead?

**Comment by dyladan** [comment]
https://github.com/open-telemetry/opentelemetry-js-api/pull/176
