### ISSUE TITLE
Fix misspelling team name @open-telemetry/swift-mainteiners

### ISSUE THREAD

**Issue by chalin** [open-telemetry/community#1291]
The team name:

- @open-telemetry/swift-mainteiners 

should be written as

- **@open-telemetry/swift-maintainers**

Maybe just rename the team, or clone the team and give folks a heads up that the old name will be deprecated as some point in the near future?

Context: https://github.com/open-telemetry/opentelemetry.io/commit/404909586002a60134dcb9aebc9ba6a1918fce92#r88816494

/cc @svrnm @cartermp

**Comment by arminru** [comment]
Thanks for bringing this up!
I renamed the team, as their CODEOWNERS file does not make use of them but instead lists individuals here:
https://github.com/open-telemetry/opentelemetry-swift/blob/main/CODEOWNERS
Maybe you could consider updating this, @open-telemetry/swift-maintainers @nachoBonafonte.
