### ISSUE TITLE
REQUEST: New membership for windsonsea

### ISSUE THREAD

**Issue by windsonsea** [open-telemetry/community#1292]
### GitHub Username

@windsonsea

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @svrnm 
- @dmitryax 
- @cartermp 
- @chalin 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored: [1960](https://github.com/open-telemetry/opentelemetry.io/pull/1960), [1967](https://github.com/open-telemetry/opentelemetry.io/pull/1967), [1968](https://github.com/open-telemetry/opentelemetry.io/pull/1968), [1969](https://github.com/open-telemetry/opentelemetry.io/pull/1969), [1975](https://github.com/open-telemetry/opentelemetry.io/pull/1975), [1984](https://github.com/open-telemetry/opentelemetry.io/pull/1984), [1988](https://github.com/open-telemetry/opentelemetry.io/pull/1988), [1996](https://github.com/open-telemetry/opentelemetry.io/pull/1996)
- SIG projects I am involved with [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io)

**Comment by svrnm** [comment]
I support.

**Comment by dmitryax** [comment]
I support

**Comment by cartermp** [comment]
I support!

**Comment by SergeyKanzhelev** [comment]
Welcome, @windsonsea! Invite sent
