### ISSUE TITLE
Transfer ownership of opentelemetry-calendar-contributors google group to GC google account?

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1302]
Does it make sense to transfer ownership of [opentelemetry-calendar-contributors](https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-calendar-contributors-google-group) to cncf-opentelemetry-governance@lists.cncf.io?

This would allow anyone in @open-telemetry/governance-committee to help manage it.

Related: https://github.com/open-telemetry/community/issues/1300#issuecomment-1325595577

**Comment by mtwo** [comment]
I've added the GC account as an owner to the list! It appears that groups can have many owners, so I haven't removed any of the existing ones
