### ISSUE TITLE
REQUEST: Maintainer of opentelemetry-php for pdelewski

### ISSUE THREAD

**Issue by pdelewski** [open-telemetry/community#1303]
### GitHub Username

pdelewski

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @brettmc 
- @bobstrecansky 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/18
https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/15
https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/16
https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/14
https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/7
https://github.com/open-telemetry/opentelemetry-php-contrib/pull/84
https://github.com/open-telemetry/opentelemetry-php-contrib/pull/81
https://github.com/open-telemetry/opentelemetry-php/pull/864
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/6
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/3

- Issues responded to
- SIG projects I am involved with
Go auto instrumentation
PHP

**Comment by bobstrecansky** [comment]
I approve

**Comment by brettmc** [comment]
I support

**Comment by arminru** [comment]
@pdelewski @bobstrecansky @brettmc so the request is to add @pdelewski to @open-telemetry/php-maintainers, right?

**Comment by pdelewski** [comment]
Yes

**Comment by brettmc** [comment]
@arminru yes, that's right

**Comment by arminru** [comment]
Thanks for the clarification!

Added @pdelewski to the team as requested.

**Comment by arminru** [comment]
@open-telemetry/php-maintainers please make sure to update these lists accordingly:

- https://github.com/open-telemetry/opentelemetry-php/blob/main/CONTRIBUTING.md
- https://github.com/open-telemetry/opentelemetry-php-contrib/blob/main/CONTRIBUTING.md

Thanks!
