### ISSUE TITLE
Process for repo creation and transfer

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/community#131]
Currently, only admins can create or transfer repositories. The latter part is especially problematic, since it prevents someone from temporarily creating a repo under their own account and then subsequently transferring it. (Forking or re-cloning under the main org are also insufficient.)

Thoughts on something like an `opentelemetry-temp` org that has looser permissions? The idea being that non-admin contributors can create and/or transfer repos there, then admins can (if approved) transfer them over.

Definitely sounds convoluted, but I can't think of something better right now 😅

**Comment by yurishkuro** [comment]
Private repos can still be transferred, the owner just needs to add some of OTel admins as admins in that repp

**Comment by bogdandrutu** [comment]
Also more high level comment. I don't think transferring an entire repo is good idea for any new work (I think it is fine to do it for an already existing work). My main argument is that the new work will lack reviews and agreement from the community.

**Comment by iredelmeier** [comment]
@yurishkuro the issue isn't with public vs private repos but instead **individual vs org ownership**.

**Comment by SergeyKanzhelev** [comment]
transferring also lacks CLA checks. Do you expect it to be a common issue? If not - we can solve it individually in all cases

**Comment by iredelmeier** [comment]
@SergeyKanzhelev the CLA checks are a good point.

I would expect repo transfer to be common for new language repos. Depending on how we choose to organize repos for integrations with third-party libraries, frameworks, etc., it may become a **big** issue there. Similarly - and more complicatedly - we'll likely eventually want "official" OpenTelemetry forks of projects we want to integrate OpenTelemetry directly into.

I'm not sure how OpenTracing handles the CLA issue for transfers, nor how other multi-repo OSS projects do it. OpenTelemetry definitely isn't the first CNCF project to ever need new repos!

**Comment by SergeyKanzhelev** [comment]
We had this done a few times by now. Examples are OTEPS and PHP. All the time it was a large PR into repo. It ensures CLA was signed off.

Let's re-open this issue if we will have a large migration issue.
