### ISSUE TITLE
Is there an OpenTelemetry AWS account?

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1310]
This is a question that came up a while ago when looking to publish Lambda layers from the opentelemetry-lambda repository. See https://github.com/open-telemetry/opentelemetry-lambda/issues/2.

**Comment by trask** [comment]
hey @codeboten, check out #685 and #392

**Comment by codeboten** [comment]
Thanks @trask! I missed that issue in my searches. Closing as dupe of #685
