### ISSUE TITLE
Update time/day for configuration WG

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1314]
The current time (Friday 10:30am PT) doesn't work for many folks. Following a vote in the #otel-config-file slack channel and discussion at last Friday's meeting, it was decided that every other Monday at 8:00am PT would work better.

Please update the meeting time in the google calendar to every second Monday at 8:00am PT starting on Dec 12th. I'll submit a PR for the README.md update.

**Comment by trask** [comment]
> Please update the meeting time in the google calendar to every second Monday at 8:00am PT starting on Dec 12th

@codeboten you can get permissions to update the calendar: https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#gaining-calendar-permissions

**Comment by pellared** [comment]
@codeboten Any update? When does the meeting currently take place? I cannot find the info in a timely manner).

**Comment by jack-berg** [comment]
The meeting has been updated to take place every other Monday at 8am PST. The next meeting is January 23rd at 8am PST.
