### ISSUE TITLE
REQUEST: Approver role for pdelewski (opentelemetry-go-contrib, instrgen subdirectory in particular)

### ISSUE THREAD

**Issue by pdelewski** [open-telemetry/community#1324]
### GitHub Username

pdelewski

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MadVikingGod 
- @MrAlias 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/6
- https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/3
Bunch of PHP commits
- Issues responded to
- SIG projects I am involved with
PHP SIG
GO AutoInstrumentation

**Comment by MadVikingGod** [comment]
I approve.

**Comment by SergeyKanzhelev** [comment]
Maintainers of individual sigs/repositories are promoting to approvers role.

In this case, the team [go-approvers](https://github.com/orgs/open-telemetry/teams/go-approvers/members?query=role%3Amaintainer) has the following maintainers:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/9950081/207928426-3766f50e-c60c-4bbb-86db-a7c54f56b554.png">

It doesn't match the codeowners file: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/CODEOWNERS#L17, I'm not sure why. But sponsors listed in this request definitely can approve.

Also I see that your alias is already in CODEOWNERS. So not sure if there is anything needed here. I'd let maintainers of go-contrib decide.

**Comment by SergeyKanzhelev** [comment]
I see. Maintainers for the repo can make you an approver. Thank you!

**Comment by trask** [comment]
> @SergeyKanzhelev Without being an approver I don't have merge permissions which was the goal

@open-telemetry/go-maintainers if you have a need to grant approvers the right to merge can you open a community issue to discuss? currently see https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-main

> * Restrict who can push to matching branches: ✔️
>   * Organization administrators, repository administrators, and users with the Maintain role

**Comment by pdelewski** [comment]
Seems that, it was my misunderstanding, I was thinking that approver have merge permissions
