### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java, opentelemetry-java-instrumentation, opentelemetry-java-contrib

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1327]
### Affected Repository

[opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java)
[opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation)
[opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib)

### Requested changes

Grant access for these repositories to the new org-wide secret `OPENTELEMETRYBOT_TOKEN` (see https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot)
 
### Purpose

We have been using @opentelemetrybot already for release automation and would like to switch over to use the org managed secret.
 
### Expected Duration

Permanently

### Repository Maintainers

@open-telemetry/java-maintainers
@open-telemetry/java-instrumentation-maintainers
@open-telemetry/java-contrib-maintainers

**Comment by trask** [comment]
@open-telemetry/technical-committee I believe this is done, can you confirm?

**Comment by carlosalberto** [comment]
@trask Is this still a thing? (I guess it is?)

**Comment by trask** [comment]
oh, I can see the org secret is available under our repo secrets, so all looks good:

![image](https://user-images.githubusercontent.com/218610/217374842-8b418e3c-3101-4052-913f-b1315c64ca73.png)
