### ISSUE TITLE
REQUEST: New membership for @vmarchaud

### ISSUE THREAD

**Issue by vmarchaud** [open-telemetry/community#133]
### GitHub Username

@vmarchaud

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mayurkale22 
- @danielkhan

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-js/issues/15
- https://github.com/open-telemetry/opentelemetry-js/issues/7
- Made some PRs on the census node implementation: https://github.com/census-instrumentation/opencensus-node/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+author%3Avmarchaud
- Involved on the SIG Javascript group

**Comment by SergeyKanzhelev** [comment]
@danielkhan please like/comment

**Comment by danielkhan** [comment]
Confirmed

**Comment by SergeyKanzhelev** [comment]
Welcome, @vmarchaud!

**Comment by vmarchaud** [comment]
Thanks @SergeyKanzhelev ! It seems that i can't assign myself to issues on the js repository, do you know why ?

**Comment by SergeyKanzhelev** [comment]
It is a GitHub limitation: https://help.github.com/en/articles/assigning-issues-and-pull-requests-to-other-github-users

> Anyone with write permissions to a repository can assign issues and pull requests.

Approvers and maintainers have write permissions. Just mention yourself in the issue and @open-telemetry/node-approvers will help assigning issue to you
