### ISSUE TITLE
REQUEST: New membership for harshit-splunk

### ISSUE THREAD

**Issue by harshit-splunk** [open-telemetry/community#1341]
### GitHub Username

@harshit-splunk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dmitryax 
- @MovieStoreGuy
- @djaglowski

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+is%3Amerged+author%3Aharshit-splunk+
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+involves%3Aharshit-splunk
- SIG projects I am involved with
  - OpenTelemetry Collector
    - [CODEOWNER](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/06d5dc53634a7859f84ed059f91af1ae62fce2d9/.github/CODEOWNERS#L187) of [k8sobjectsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14699) plugin

**Comment by atoulme** [comment]
I support!

**Comment by dmitryax** [comment]
I support 👍

**Comment by SergeyKanzhelev** [comment]
From requirements: https://github.com/open-telemetry/community/blob/main/community-membership.md

> sponsored by 2 approvers or maintainers. multiple contributions to the project.

@harshit-splunk can you pls comment on @atoulme approver/maintainer status.

**Comment by atoulme** [comment]
Oh that's true, I'm not an approver. I will look for someone else to help here.

**Comment by atoulme** [comment]
@harshit-splunk I talked with @djaglowski and he would be open to be your second sponsor. Sorry for the mess!

**Comment by MovieStoreGuy** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
> @harshit-splunk I talked with @djaglowski and he would be open to be your second sponsor. Sorry for the mess!

no worries, thank you for helping!

**Comment by SergeyKanzhelev** [comment]
Welcome, @harshit-splunk! Invite sent
