### ISSUE TITLE
FAAS sig needs a different zoom instance

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/community#1345]
The FAAS zoom link overlaps partially with the dotnet sdk sig. We'd like to change ours to something different.

**Comment by carlosalberto** [comment]
I have changed the Zoom room (calendar updated as well).

However, remember we re-use Zoom links _and_ there's always chance that one call starts right after a previous one finishes (which seems to be the case you saw, as the DotNet call started right after the FaaS one).

**Comment by cartersocha** [comment]
Thanks Carlos! We understand.
