### ISSUE TITLE
[build] access to open-telemetry docker hub account for eBPF collector

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#1348]
The [eBPF collector project](https://github.com/open-telemetry/opentelemetry-ebpf) is looking to push Docker images in a Docker registry that is not tied to a corporate sponsor, such as the Docker hub account associated with open-telemetry.

Please help me understand how to best go about going access and how to manage this on an ongoing basis.

**Comment by tigrannajaryan** [comment]
See for example how it is implemented for the [Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib). You will need to add 2 secrets to your repo: DOCKER_USERNAME and DOCKER_PASSWORD and use them from your action that pushes to Docker hub. 

You will need to let me or any other TC member know and we will add the values for DOCKER_USERNAME and DOCKER_PASSWORD in your repo's secrets.

**Comment by atoulme** [comment]
We are good with this and working with Tigran now.
