### ISSUE TITLE
REQUEST: New membership for <your-GH-handle>

### ISSUE THREAD

**Issue by bg451** [open-telemetry/community#135]
### GitHub Username

@bg451

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tedsuo 
- @mayurkale22 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-js/pull/30
https://github.com/open-telemetry/opentelemetry-js/pull/10
https://github.com/open-telemetry/opentelemetry-js/pull/57
https://github.com/open-telemetry/opentelemetry-js/pull/39
https://github.com/open-telemetry/opentelemetry-js/pull/55
- Issues responded to
https://github.com/open-telemetry/opentelemetry-js/issues/50
https://github.com/open-telemetry/opentelemetry-js/issues/7
https://github.com/open-telemetry/opentelemetry-js/issues/13
https://github.com/open-telemetry/opentelemetry-js/issues/4
- SIG projects I am involved with
  - opentelemetry-js

**Comment by SergeyKanzhelev** [comment]
welcome, @bg451 !
