### ISSUE TITLE
REQUEST: New membership for @iblancasa

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/community#1352]
### GitHub Username

@iblancasa

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pavolloffay 
- @frzifus 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-operator/pull/505
- https://github.com/open-telemetry/opentelemetry-operator/pull/1365
- https://github.com/open-telemetry/opentelemetry-operator/pull/1354
- https://github.com/open-telemetry/opentelemetry-operator/pull/1345
- https://github.com/open-telemetry/opentelemetry-operator/pull/133
- https://github.com/open-telemetry/opentelemetry-operator/pull/1254
- https://github.com/open-telemetry/opentelemetry-cpp/pull/747
- Issues responded to

**Comment by pavolloffay** [comment]
I support this

**Comment by frzifus** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
@frzifus thank you for raising this. Indeed, @iblancasa you will need to find a sponsor affiliated with the different company.

Please re-open the issue once you found the new sponsor. Very glad to see interest to join OpenTelemetry
