### ISSUE TITLE
TC Review Request: Go Metric API

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1355]
The Go SIG is looking to make a stable release of the OpenTelemetry metric API in Go. We are looking for a TC member familiar with the metric API specification to review our offering and help ensure our compliance with the specification.

We are still working to ensure the compliance of the metric SDK. Therefore, this request is only scoped to the API.

### Prior work

We have conducted our own internal review of the specification [here](https://github.com/orgs/open-telemetry/projects/33). That review identified one outstanding compliance issue remains:

- https://github.com/open-telemetry/opentelemetry-go/issues/3565

However, we believe this to be an specification issue. https://github.com/open-telemetry/opentelemetry-specification/pull/3171 is opened to address this at the specification level.

### Inventory

We would like to evaluate the [v1.12.0/v0.35.0 Release](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.12.0), links should be related to this tag.

- Metric API package: https://github.com/open-telemetry/opentelemetry-go/tree/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric
  - [`MeterProvider`](https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/meter.go#L24-L35)
  - [`Meter`](https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/meter.go#L37-L107)
  - Asynchronous instruments:
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/asyncfloat64.go#L35-L56
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/asyncint64.go#L35-L56
  - Single-instrument callbacks:
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/asyncfloat64.go#L58-L79, https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/asyncfloat64.go#L125-L131
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/asyncint64.go#L58-L79, https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/asyncint64.go#L125-L131
  - Multi-instrument callbacks:
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/meter.go#L104-L129
  - Synchronous instruments:
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/syncfloat64.go#L24-L54
    - https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/instrument/syncint64.go#L24-L54
- No-op implementation: https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/noop.go
- Metric portion of global API: https://github.com/open-telemetry/opentelemetry-go/tree/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/global

**Comment by reyang** [comment]
I can probably take it if it's okay to wait till mid Feb (13th-17th), please let me know if it is okay.

**Comment by MrAlias** [comment]
> I can probably take it if it's okay to wait till mid Feb (13th-17th), please let me know if it is okay.

Yeah, that timeline works. Thanks :+1:

**Comment by reyang** [comment]
I've scanned through all the links provided in the PR description and confirmed that they are compliant to the API specification.
I've also confirmed that the API spec has been well covered by the OTel Go API package, except for the following section (which is okay):

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter

> [since 1.13.0] attributes: Specifies the instrumentation scope attributes to associate with emitted telemetry.
> 
> Users can provide attributes to associate with the instrumentation scope, but it is up to their discretion. Therefore, this API MUST be structured to accept a variable number of attributes, including none.

One minor thing I've noticed:

https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/trace/trace.go#L550 we seem to use `name` as the parameter for a provider to get a Tracer, https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/meter.go#L34 we use `instrumentationName` which is not very consist with trace as well as the spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter.

**Comment by reyang** [comment]
@MrAlias I'm closing this issue as _completed_.

**Comment by jmacd** [comment]
I completely support the Go metrics API.
For the record, I maintain an alternate Go metrics SDK and have completed upgrading my code to use the new APIs. I found no difficulties and am pleased with the new APIs. https://github.com/lightstep/otel-launcher-go/pull/381

**Comment by MrAlias** [comment]
> One minor thing I've noticed:
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/trace/trace.go#L550 we seem to use `name` as the parameter for a provider to get a Tracer, https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/metric/meter.go#L34 we use `instrumentationName` which is not very consistent with trace as well as the spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter.

Addressed by https://github.com/open-telemetry/opentelemetry-go/pull/3734

**Comment by MrAlias** [comment]
> I've scanned through all the links provided in the PR description and confirmed that they are compliant to the API specification. I've also confirmed that the API spec has been well covered by the OTel Go API package, except for the following section (which is okay since we're targeting 1.12):
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter
> 
> > [since 1.13.0] attributes: Specifies the instrumentation scope attributes to associate with emitted telemetry.
> > Users can provide attributes to associate with the instrumentation scope, but it is up to their discretion. Therefore, this API MUST be structured to accept a variable number of attributes, including none.


Addressing this with https://github.com/open-telemetry/opentelemetry-go/pull/3738
