### ISSUE TITLE
REQUEST: New membership for avillela

### ISSUE THREAD

**Issue by avillela** [open-telemetry/community#1360]
### GitHub Username

@avillela

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reese-lee 
- @musingvirtual

### List of contributions to the OpenTelemetry project

PRs Reviewed/Authored
- https://github.com/open-telemetry/opentelemetry-demo/pull/432
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/531
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9764
- https://github.com/open-telemetry/opentelemetry.io/pull/2096
- https://github.com/open-telemetry/opentelemetry.io/pull/1387
- https://github.com/open-telemetry/opentelemetry.io/pull/2130
- https://github.com/open-telemetry/opentelemetry.io/pull/2205
- https://github.com/open-telemetry/opentelemetry.io/pull/2234
- https://github.com/open-telemetry/opentelemetry.io/pull/2300

SIG projects I am involved with
- OTel Comms
- OTel End User Working Group

**Comment by reese-lee** [comment]
I support!

**Comment by musingvirtual** [comment]
Strongly support Adriana's nomination!

**Comment by svrnm** [comment]
I support :-)

**Comment by arminru** [comment]
Invite sent. Welcome, @avillela!

**Comment by arminru** [comment]
I also added @avillela to @open-telemetry/end-user-wg as discussed on Slack.
