### ISSUE TITLE
Suggestion: Pinned repositories

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/community#137]
We should [pin](https://github.blog/2016-06-16-pin-repositories-to-your-github-profile/) key cross-cutting repositories to the org profile so that they're more obvious to newcomers, e.g., [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification), [community](https://github.com/open-telemetry/community), and [rfcs](https://github.com/open-telemetry/rfcs).

**Comment by mtwo** [comment]
+1

________________________________

**Comment by bhs** [comment]
I absolutely agree...

Any objections? If there's no disagreement by Friday, IMO we should just do this. I can't really see a downside.

cc @open-telemetry/admins

**Comment by SergeyKanzhelev** [comment]
OK?

![image](https://user-images.githubusercontent.com/9950081/60153531-5dbd7a80-9799-11e9-9259-47a9e62db6f4.png)
