### ISSUE TITLE
REQUEST: New membership for hughesjj

### ISSUE THREAD

**Issue by hughesjj** [open-telemetry/community#1375]
### GitHub Username

@hughesjj 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dmitryax 
- @jsuereth

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [Make table generation conflicts easier to debug (with colors!)](https://github.com/open-telemetry/build-tools/pull/121)
  - [Add Enabled flag for attributes to metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16736)
  - [[cmd/mdatagen] Expose resource_attributes option in user settings](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17967)
  - [Add a detailed CONTRIBUTING guide for semantic-conventions build-tools](https://github.com/open-telemetry/build-tools/pull/118)
  - [Added Semantic Conventions working group references](https://github.com/open-telemetry/community/pull/1304)
  - [[bug]? fix host metrics config test error comparison](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17026)
- Issues responded to
  - do [docs count](https://docs.google.com/document/d/1ghvajKaipiNZso3fDtyNxU7x1zx0_Eyd02OGpMGEpLE/edit#)? (check resolved comments) 
- SIG projects I am involved with
  - Semantic Conventions WG
  - Opentelemetry Communications

**Comment by dmitryax** [comment]
I support!

**Comment by jsuereth** [comment]
I support!

**Comment by arminru** [comment]
> * do [docs count](https://docs.google.com/document/d/1ghvajKaipiNZso3fDtyNxU7x1zx0_Eyd02OGpMGEpLE/edit#)? (check resolved comments)

I'd say so, yes 👍🙂

**Comment by arminru** [comment]
Invite sent. Welcome, @hughesjj!
