### ISSUE TITLE
REQUEST: New membership for dao-jun

### ISSUE THREAD

**Issue by tjiuming** [open-telemetry/community#1379]
### GitHub Username

@dao-jun
(This is my personal GitHub account, please send the invitation to it.)

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@trask 
@dmitryax 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5926
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9791
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9792
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12108
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13392
    - https://github.com/open-telemetry/opentelemetry-collector-releases/pull/184
- Issues responded to
- SIG projects I am involved with

**Comment by trask** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @dao-jun!
