### ISSUE TITLE
REQUEST: New membership for jmacd

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/community#138]
### GitHub Username

@jmacd 

### Organization you are requesting membership in

@open-telemetry/go-approvers 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@tedsuo 
@rghetia  

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-go/pull/9

- Issues responded to
lots

- SIG projects I am involved with
specification, golang, proto

**Comment by SergeyKanzhelev** [comment]
@jmacd sorry for misunderstanding. This template was misused before for nominating for approvers role while bootstrapping.

Typically @tedsuo would nominate for languages. While Ted is on vacation, @bhs  can you please confirm nomination. We only have till July 1st to finish bootstrapping

**Comment by bhs** [comment]
Happy to confirm @jmacd for this nomination, yep!

**Comment by bhs** [comment]
(All done)

**Comment by jmacd** [comment]
What I actually need is to be a "reviewer", apparently. Can I get that via this ticket?

**Comment by SergeyKanzhelev** [comment]
@jmacd I added you to the proper group. Now please send PR to include you into the [codeowners file in the go repo](https://github.com/open-telemetry/opentelemetry-go/blob/master/CODEOWNERS)
