### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-ebpf

### ISSUE THREAD

**Issue by yonch** [open-telemetry/community#1383]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-ebpf

### Requested changes

Add docker credentials and config as GitHub Secrets:

- [ ] Secret: DOCKER_USERNAME
- [ ] Secret: DOCKER_PASSWORD

And the following Variables -- these are used across the CI/CD config for readability and in the more remote cases we'd want to switch repository for testing ahead of changes to publishing (nothing currently envisioned):

- [ ] Variable: DOCKER_REGISTRY where to `docker login` into, `https://registry-1.docker.io/` ([StackOverflow](https://stackoverflow.com/a/57108557))
- [ ] Variable: DOCKER_NAMESPACE the image prefix under which to publish container images, probably `otel` since [Docker Hub doesn't appear to support multiple repository levels](https://github.com/docker/hub-feedback/issues/1404).
 
### Purpose

This will enable publishing of docker images of the eBPF collectors and the eBPF reducer from CI/CD pipelines, which also excitingly include an eBPF compatibility test that runs on multiple Linux kernels via GitHub Actions VMs!

If interested in more details: [PR#109](https://github.com/open-telemetry/opentelemetry-ebpf/pull/109), credit to @samiura for this work!

### Expected Duration

Permanent

### Repository Maintainers

- @open-telemetry/ebpf-maintainers

**Comment by tigrannajaryan** [comment]
@yonch I added the secrets and variables. Note that DOCKER_REGISTRY and DOCKER_NAMESPACE as variable and are visible in plain text.
