### ISSUE TITLE
REQUEST: New membership for mar4uk

### ISSUE THREAD

**Issue by mar4uk** [open-telemetry/community#1390]
### GitHub Username

e.g. @mar4uk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @codeboten 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed/authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19399
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19373
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18532
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18499
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17071
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16855
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9369
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9085
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18083

- Issues responded to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9130
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18403
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17445
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16722

**Comment by codeboten** [comment]
👍🏻

**Comment by jpkrohling** [comment]
👍🏽
