### ISSUE TITLE
Send metrics data in JSON format to Collector

### ISSUE THREAD

**Issue by w00ski** [open-telemetry/community#1397]
Hello,

I have been struggling sending data as a JSON to the Collector. Assume that I already have the metrics values and timestamps and I want to add them manually in the collector. I have reached this format until now:
`{
  "resourceMetrics": [
    {
      "resource": {
        "attributes": [{ "key": "attr_key", "stringValue": "attr_value" }]
      },
      "scopeMetrics": [
        {
          "scope": {
            "name": "metrics_scope",
            "version": "4.2.0",
            "attributes": []
          },
          "metrics": [
            {
              "name": "metric_1",
              "description": "metric_1 description string",
              "unit": "1",
              "gauge": {
                "dataPoints": [
                  {
                    "attributes": [],
                    "timeUnixNano": 1679912468340000000,
                    "asDouble": 5.66
                  },
                  {
                    "attributes": [],
                    "timeUnixNano": 1679912463340000000,
                    "asDouble": 10.66
                  }
                ]
              }
            },
            {
              "name": "metric_2",
              "description": "metric_2 description string",
              "unit": "1",
              "gauge": {
                "dataPoints": [
                  {
                    "attributes": [],
                    "timeUnixNano": 1679912468340000000,
                    "asDouble": 3.33
                  },
                  {
                    "attributes": [],
                    "timeUnixNano": 1679912463340000000,
                    "asDouble": 6.33
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
`
But when sending this through a POST request with curl (content type set to application/json), it returns "partialSuccess" and only the last value is visible in the prometheus graph, at the time of the request was sent, not at the time specified in "timeUnixNano".

Can you figure out what is wrong here? I am out of ideas.

Thank you!!!

**Comment by djaglowski** [comment]
Please open an issue on the [collector](https://github.com/open-telemetry/opentelemetry-collector/issues) or [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues). It would be very helpful to include your configuration as well.

**Comment by w00ski** [comment]
I am using this example, running it in docker:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo

With 2 small modifications:

1. Added `- "4318:4318"   # OTLP http receiver` in [docker-compose.yaml(line 32)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/docker-compose.yaml#L32)

2.Added `http:` in [otel-collector-config.yaml(line 4)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/otel-collector-config.yaml#L4)

Sending the requests on port 4318.

**Comment by atoulme** [comment]
You can also use the splunk HEC receiver and hit the raw endpoint.

**Comment by mtwo** [comment]
Closing this issue as it's stale. If you're still having the problem, please open an issue on the Collector repository.
