### ISSUE TITLE
REQUEST: New membership for sumo-drosiek

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/community#1399]
### GitHub Username

@sumo-drosiek

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski
- @atoulme

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [pkg/stanza: use ObservedTimestamp to decide if flush log for recombine operator](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11433)
  - [feat(coreinternal/attraction): supports pattern for delete and hash attractions](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10822)
  - [\[mysqlreceiver\]: rename mysql.commands metric to mysql.prepared_statements](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14722)
  - [\[resourcedetectionprocessor\]: add host.id to system detector](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18618)
  - [all of opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Asumo-drosiek+is%3Aclosed)
- Issues responded to
  - [\[processor/k8sattributes\] agent passthrough, gateway k8s.pod.ip configuration broken post v0.55.0 release](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13765)
  - [filelog receiver: the last event of every data file was lost](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4849)
- SIG projects I am involved with (not sure how involved is defined)
  - I was contributing mostly to the opentelemetry-collector-contrib repository

**Comment by atoulme** [comment]
I support
