### ISSUE TITLE
REQUEST: New membership for <gnm444>

### ISSUE THREAD

**Issue by gnm444** [open-telemetry/community#1402]
GitHub Username
@gnm444

Requirements
 I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
 I have enabled 2FA on my GitHub account. See https://github.com/settings/security
 I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
 I am actively contributing to 1 or more OpenTelemetry subprojects
 I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
 I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
Sponsors
@lalitb
@esigo

Each sponsor should reply to this issue with the comment "I support".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

List of contributions to the OpenTelemetry project
PRs authored
https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/179
https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/164
SIG projects I am involved with
[opentelemetry-cpp-contrib](https://github.com/open-telemetry/opentelemetry-cpp-contrib)

**Comment by esigo** [comment]
I do NOT support.

> I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

@gnm444 I can't recall if we've ever talked. Also please don't spam emails that are not listed anywhere.

**Comment by gnm444** [comment]
I am extremely sorry for that...Let me approach in the right channel.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
