### ISSUE TITLE
Public calendaring issue/improvement

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1414]
We are having some problems with the Google calendar syncing (for those who have joined [opentelemetry-calendar@googlegroups.com](mailto:opentelemetry-calendar@googlegroups.com)). Likely because I updated too many meetings while giving all of the Zoom meetings separate ids/names, and hit some Google calendar spamming limits (by the way, sorry for the spam 😅).

I'd like to propose a change (originally raised by @tylerbenson), and create separate "invitee" google groups per meeting so that we aren't spamming so many updates for every meeting (there are currently >150 people in opentelemetry-calendar@googlegroups.com).

If we do this, I'd like to remove opentelemetry-calendar@googlegroups.com from the meetings, and email that list letting them know about the new per-meeting google groups they can join instead.

If we still need a list for all meetings, we can create that separately (e.g. opentelemetry-calendar-all@googlegroups.com) and hopefully it should be much smaller number of people who want to be in that group.

(and yes, I'm volunteering to make these changes and document them in this repo, I've lost too much time on the calendar in the last days to not hopefully see this through to a better place 😅)

**Comment by alolita** [comment]
For those of us who are interested in all SIG meetings - can we get a list for all meetings, we can create that separately (e.g. opentelemetry-calendar-all@googlegroups.com :-)

**Comment by dyladan** [comment]
@trask did this ever go anywhere?

**Comment by trask** [comment]
we are unblocked now, working on implementing this in #1788
