### ISSUE TITLE
REQUEST: New membership for @nslaughter

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/community#1417]
### GitHub Username

@nslaughter

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @codeboten 
- @fatsheep9146

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: [collector-contrib PRs](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Anslaughter+)
- Issues responded to: [collector-contrib Issues involved](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=involves%3Anslaughter+sort%3Aupdated-desc+) 
- SIG projects I am involved with: attending various to learn where it makes sense to focus

**Comment by fatsheep9146** [comment]
I support

**Comment by carlosalberto** [comment]
Invite sent, welcome aboard!
