### ISSUE TITLE
REQUEST: New membership for AbhiPrasad

### ISSUE THREAD

**Issue by AbhiPrasad** [open-telemetry/community#1419]
### GitHub Username

@AbhiPrasad

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

ref https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

- @atoulme
- @jpkrohling

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1320
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/565
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19367
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13415
- Issues responded to
- SIG projects I am involved with: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/sentryexporter

**Comment by trask** [comment]
@atoulme is there a second sponsor that everyone listed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 can use?

**Comment by atoulme** [comment]
@trask no, but we have discussions about the best way to go about it. I'll reach out.

**Comment by atoulme** [comment]
I support.

**Comment by jpkrohling** [comment]
I support.

**Comment by carlosalberto** [comment]
Invitation sent. Welcome!
