### ISSUE TITLE
REQUEST: New membership for chrroberts-pure

### ISSUE THREAD

**Issue by chrroberts-pure** [open-telemetry/community#1423]
### GitHub Username

@chrroberts-pure

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@jpkrohling 
@TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

Comments and code reviews on PRs in collector-contrib
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18466
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17906
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17356
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17266
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14969

**Comment by chrroberts-pure** [comment]
re: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

**Comment by jpkrohling** [comment]
@TylerHelmuth,  @atoulme, would one of you be open to @chrroberts-pure's sponsor?

**Comment by TylerHelmuth** [comment]
I support.

**Comment by carlosalberto** [comment]
Invitation sent, welcome!
