### ISSUE TITLE
REQUEST: New membership for bertysentry

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/community#1424]
### GitHub Username

@bertysentry 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jack-berg 
- @trask 

Each sponsor should reply to this issue with the comment "*I support*".

### List of contributions to the OpenTelemetry project

- 30 issues: https://github.com/issues?q=is%3Aissue+author%3Abertysentry+archived%3Afalse+org%3Aopen-telemetry+
- 10 PRs: https://github.com/issues?q=is%3Apr+author%3Abertysentry+archived%3Afalse+org%3Aopen-telemetry+

Request as per https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

**Comment by jack-berg** [comment]
I support

**Comment by trask** [comment]
I support!

**Comment by carlosalberto** [comment]
Invitation sent, welcome!

**Comment by jmacd** [comment]
:+1:
