### ISSUE TITLE
REQUEST: New membership for varunraiko

### ISSUE THREAD

**Issue by varunraiko** [open-telemetry/community#1427]
### GitHub Username

varunraiko

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

@atoulme
@punya 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18689
- Issues responded to
- SIG projects I am involved with https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/googlecloudspannerreceiver

**Comment by atoulme** [comment]
I support.

**Comment by atoulme** [comment]
Please get in touch with @evan-bradley and ask him if he would be willing to support your membership application as well, given that he reviewed your last PR. Thanks!

**Comment by punya** [comment]
I support.

**Comment by varunraiko** [comment]
@atoulme do we need anything else for this PR?

**Comment by atoulme** [comment]
No, that is enough, thanks! A member of the community will now process the request.

**Comment by arminru** [comment]
Invite sent. Welcome, @varunraiko!
