### ISSUE TITLE
REQUEST: New membership for xiang17

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/community#1432]
### GitHub Username

@xiang17

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @utpilla
- @pjanotti

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2411
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2178
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2157
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2140
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2004

- Issues responded to
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1997

- SIG projects I am involved with
  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation
  https://github.com/open-telemetry/opentelemetry-dotnet-contrib

**Comment by pjanotti** [comment]
I support

**Comment by utpilla** [comment]
I support
