### ISSUE TITLE
REQUEST: New membership for jkowall

### ISSUE THREAD

**Issue by jkowall** [open-telemetry/community#1434]
### GitHub Username

@jkowall 

### Requirements

- [x ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x ] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@jmacd
@yurishkuro

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored - Many of them, also contributor to spanmetricprcoessor design due to the Jaeger work
- Issues responded to - There are many
- SIG projects I am involved with - Java, Logs, Community

Also related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

**Comment by carlosalberto** [comment]
Ping @alolita @pavolloffay

**Comment by jmacd** [comment]
+1

**Comment by arminru** [comment]
I updated the sponsors with those who responded.

**Comment by arminru** [comment]
Invite sent. Welcome, @jkowall!
