### ISSUE TITLE
REQUEST: New membership for albertteoh

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/community#1435]
### GitHub Username

@albertteoh

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @kovrus 
- @djaglowski 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs
  - 55 reviewed: https://github.com/pulls?q=is%3Apr+reviewed-by%3Aalbertteoh+archived%3Afalse+org%3Aopen-telemetry+
  - 30 authored: https://github.com/pulls?q=is%3Apr+author%3Aalbertteoh+archived%3Afalse+org%3Aopen-telemetry+
- Issues:
  - 17 authored: https://github.com/issues?q=is%3Aissue+author%3Aalbertteoh+archived%3Afalse+org%3Aopen-telemetry+
  - 36 responded to: https://github.com/issues?q=is%3Aissue+commenter%3Aalbertteoh+archived%3Afalse+org%3Aopen-telemetry+
- SIG projects I am involved with:
  - Attended collector SIGs for APAC region while AEST friendly, but was later removed.
  - Started attending: https://opentelemetry.io/blog/2022/end-user-discussion-group-apac/

**Comment by kovrus** [comment]
I Support!

**Comment by djaglowski** [comment]
I support

**Comment by dmitryax** [comment]
I support!

**Comment by carlosalberto** [comment]
Invitation sent, welcome!
