### ISSUE TITLE
Requesting TC review for PHP Tracing API/SDK spec compliance

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#1436]
Requesting a compliance review from https://github.com/orgs/open-telemetry/teams/technical-committee prior to GA release. If there are questions you can ask myself or any of the other PHP maintainers (@brettmc or @pdelewski)

**Comment by carlosalberto** [comment]
Hey @bobstrecansky - the TC is looking for a PHP expert, and hopefully we will find one soon so the review takes place in the following weeks. Otherwise, I have volunteered to do a _general_ pass myself.

**Comment by carlosalberto** [comment]
Hey @bobstrecansky - I will be doing a review of the PHP API/SDK next week. I will be mostly providing a general review but that should be helpful with the API/SDK surface at the very least ;)

**Comment by bobstrecansky** [comment]
Perfect; thank you for the update @carlosalberto !

**Comment by carlosalberto** [comment]
@bobstrecansky I started filling issues in the PHP repo after my review - observe most of them are recommendations and can be discarded if the maintainers decide so.

**Comment by bobstrecansky** [comment]
Thank you @carlosalberto!  Appreciate the review!

**Comment by brettmc** [comment]
@carlosalberto I think this can be closed as done now, as all of the issues have been actioned and closed: https://github.com/open-telemetry/opentelemetry-php/issues?q=is%3Aissue+author%3Acarlosalberto+label%3Atc-review
