### ISSUE TITLE
Authorize renovatebot to pass CLA

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1439]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib

### Requested changes

Authorize the `renovatebot` account.
 
### Purpose

The collector core & contrib repos are planning on using Renovate moving forward to reduce the toil generated by the many dependabot PRs. The OpenTelemetry JS repo already uses renovate for dependency management. However, the account used by the official renovate app fails the CLA check. See an example: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20910

This is expected to work as it does in the JS repo https://github.com/open-telemetry/opentelemetry-js/pull/3733

The root issue may be that "forking renovate" and "renovate" are using a different bot account. 
 
### Expected Duration

permanently

**Comment by trask** [comment]
I'll open a CNCF Service Desk ticket for this

**Comment by trask** [comment]
https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1709

**Comment by codeboten** [comment]
@trask any update on the service desk request?

**Comment by trask** [comment]
No response yet. I just cross-posted it to the #easycla Slack Channel in case there's a more direct way to make this request to the EasyCLA team: https://cloud-native.slack.com/archives/CK8QVEXQB/p1682396314482599

**Comment by trask** [comment]
based on guidance from the EasyCLA team, I've opened the request directly with them at https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-17966 (and canceled the CNCF Service Desk ticket)

**Comment by codeboten** [comment]
Thanks!

**Comment by trask** [comment]
this is done 👍
