### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-go-instrumentation

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/community#1442]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go-instrumentation

### Requested changes

Create `otel/autoinstrumentation-go` docker hub repository
 
### Purpose

Push images during releases of opentelemetry-go-instrumentation.  It appears that an image can only be pushed to an existing repository.  More details here: https://github.com/open-telemetry/community/issues/1377#issuecomment-1511933211

### Repository Maintainers

- @open-telemetry/go-instrumentaiton-maintainers

**Comment by MrAlias** [comment]
https://hub.docker.com/r/otel/autoinstrumentation-go has been created.
