### ISSUE TITLE
EasyCLA not happy with coauthored commits

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#1445]
Two weeks ago when I originally applied the commits in question it was fine:
https://github.com/open-telemetry/opentelemetry-specification/pull/3212/commits/e78230358563c7f6b68e24295b3875bff6c862ab

Now after adding additional commits that pass, without modifying the original commits, it is now complaining:
https://github.com/open-telemetry/opentelemetry-specification/pull/3212

The problem seems to be isolated to the coauthored commits that were applied via the UI from a suggestion.

**Comment by tylerbenson** [comment]
I'm not the only one having issues:
https://github.com/open-telemetry/opentelemetry-specification/pull/2960#issuecomment-1515246279

**Comment by trask** [comment]
I reported this to the #easycla channel: https://cloud-native.slack.com/archives/CK8QVEXQB/p1681939413474509

**Comment by trask** [comment]
this is resolved now, adding `/easycla` comment on PRs should fix
