### ISSUE TITLE
REQUEST: New membership for jacobmarble

### ISSUE THREAD

**Issue by jacobmarble** [open-telemetry/community#1446]
### GitHub Username

jacobmarble

(this is in response to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868)

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @atoulme
- @dmitryax
- @MovieStoreGuy
- @codeboten

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: 26 (https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=author%3Ajacobmarble+is%3Apr and https://github.com/open-telemetry/opentelemetry-operator/pull/1666)
- Issues responded to: ~20 (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=jacobmarble+is%3Aissue)
- SIG projects I am involved with: opentelemetry-collector-contrib

**Comment by dmitryax** [comment]
I support!

**Comment by atoulme** [comment]
I support!

**Comment by MovieStoreGuy** [comment]
I support!

**Comment by codeboten** [comment]
+1

**Comment by jacobmarble** [comment]
Is there anything left for me to do here?
