### ISSUE TITLE
REQUEST: New membership for mapno

### ISSUE THREAD

**Issue by mapno** [open-telemetry/community#1447]
### GitHub Username

@mapno

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @kovrus 
- @atoulme
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

I'm the original author and maintainer of the [servicegraph processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/servicegraphprocessor), now [connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector) as well.
- List of PR: https://github.com/pulls?q=is%3Apr+author%3Amapno+archived%3Afalse+org%3Aopen-telemetry+
- List of Issues: https://github.com/issues?q=is%3Aissue+author%3Amapno+archived%3Afalse+org%3Aopen-telemetry+

**Comment by kovrus** [comment]
I support

**Comment by mapno** [comment]
cc/ @atoulme

**Comment by atoulme** [comment]
I support!
