### ISSUE TITLE
REQUEST: New membership for dgoscn

### ISSUE THREAD

**Issue by dgoscn** [open-telemetry/community#1449]
### GitHub Username

@dgoscn

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @atoulme 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13928
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16529
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16560
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16590
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16591
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16725
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16738
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16764
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17266
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17356
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17449
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17909
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18466
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17906
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21100
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16770#event-7982061798

- Issues responded to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14886
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17528
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10205#issuecomment-1372682192
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10368#issuecomment-1242103448

**Comment by dgoscn** [comment]
re: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

**Comment by atoulme** [comment]
@dgoscn I can be your second sponsor if you sre looking for one.

**Comment by dgoscn** [comment]
@atoulme thank you

**Comment by atoulme** [comment]
I support!

**Comment by jpkrohling** [comment]
I support.

**Comment by dgoscn** [comment]
thak you @jpkrohling
