### ISSUE TITLE
REQUEST: New repository opentelemetry-ebpf-build-tools

### ISSUE THREAD

**Issue by bjandras** [open-telemetry/community#1452]
The [OpenTelemetry eBPF](https://github.com/open-telemetry/opentelemetry-ebpf) project uses a concept of a "build environment" container image that packs all third-party tools and libraries which are used to build the main project. This approach also allows for repeatable builds.

Sources for third-party tools and libraries are referenced through the mechanism of [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

Because the main repository ([opentelemetry-ebpf](https://github.com/open-telemetry/opentelemetry-ebpf)) has its own submodules, it is advisable not to mix them (the `git-submodule` tool does not have a concept of grouping submodules). Thus a separate repository is preferred.

### Affected Repository

https://github.com/open-telemetry/opentelemetry-ebpf-build-tools

### Requested changes

Creation of a new repository.

### Purpose

Repository for build tools and libraries for the OpelTelemetry eBPF project.
 
### Expected Duration

Permanently.

### Repository Maintainers

- @open-telemetry/ebpf-maintainers

**Comment by tigrannajaryan** [comment]
Repo created https://github.com/open-telemetry/opentelemetry-ebpf-build-tools and all teams from https://github.com/open-telemetry/opentelemetry-ebpf have the same permissions.

@open-telemetry/governance-committee can you please enable EasyCLA check on the main branch? For some reason it does not show up as an available check.

**Comment by trask** [comment]
I'm not familiar with EasyCLA admin, but I've opened a request to get admin rights (cc @lizthegrey @bogdandrutu who I believe may have admin rights already)

**Comment by tigrannajaryan** [comment]
The repo creation was not completed (EasyCLA not yet enabled), but folks went ahead and merged a PR. I am going to reset the repo.

**Comment by tigrannajaryan** [comment]
I will delete the repo and will create a new to avoid having PRs that link to nothing. FYI,

**Comment by tigrannajaryan** [comment]
We will need to add teams after the EasyCLA is enabled.

**Comment by trask** [comment]
Got this response from EasyCLA team:

> We can not provide admin access based on how CNCF is structured.
> I have confirmed EasyCLA is enabled on the repo and should be working. Please try a test pr to confirm. Thank you. 

Seems like it's working now: https://github.com/open-telemetry/opentelemetry-ebpf-build-tools/pull/1

I'm not clear if they did anything or if it just started working after re-creating the repository, I've asked for some clarification so we can update our [repo setup documentation](https://github.com/open-telemetry/community/blob/ed96a8dc92b9a9034576fd565edde90ffd3168d0/docs/how-to-configure-new-repository.md#branch-protection-rule-main)

**Comment by trask** [comment]
Got feedback that they didn't do anything. I think it's supposed to be added automatically, and probably re-creating the repo fixed it magically. I'll update the [repo setup documentation](https://github.com/open-telemetry/community/blob/ed96a8dc92b9a9034576fd565edde90ffd3168d0/docs/how-to-configure-new-repository.md#branch-protection-rule-main) to clarify our current working knowledge 😂

**Comment by tigrannajaryan** [comment]
Confirmed, it now appears as a check on main branch too.

**Comment by tigrannajaryan** [comment]
I added the teams. I believe all is ready now. Closing the issue.
