### ISSUE TITLE
OTel's presence at KubeCon+CloudNativeCon

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1455]
It's quite evident from the past couple KubeCon's that OpenTelemetry is getting people's attention. My impression though is that they deserve better planning from our side, so that we can make the best out of this event. This ticket tracks the ideas that I exchanged with a few folks on how we can improve for the next KubeCon. 

- [x] Prepare a spreadsheet with all the maintainers that are participating in the event, inviting them to be volunteers at the booth with fixed shifts
- [x] Have some "Ask me anything" sessions at the booth around hot topics
- [ ] Use our maintainer's track slot to talk about something cool and deeply technical. We can give a short "project updates" presentation during the keynote, I believe.
- [x] Be part of the contrib fest, so that people can hack on something together
- [x] Have an "#otel-kubecon-questions" channel, so that we can direct people on-site to a single channel to ask their questions. It makes it easier to tell them "go here for any questions you may have" instead of trying to figure out which channel would be best suitable for their questions.

I'll keep this issue here open so that other ideas can be provided. I volunteer to make those points happen if we have agreement on them.

**Comment by jiekun** [comment]
I have a small thought (on the Q&A section) inspired by the all-hands meeting of our company.

Could we have a QR code or a short URL on the slides so that audience could visit it (which redirect them to a Google form) and write down their question during the presentation?

We could also use a Slack channel or something similar. The point is:
1. to have a place for the audience to note it down quickly.
2. it might be easier for non-English speakers to understand the question by reading instead of listening, in case of miscommunication, etc...

**Comment by arminru** [comment]
For the project meeting on Tuesday, the maintainer's talk on Thursday, and quite a few other sessions, we ran into the problem that the capacity of the rooms assigned to us was not sufficient for the influx of people who would've wanted to attend them.

Given we're the second largest project in the CNCF, we should pass this on to the CNCF events team so they can consider this in their planning for upcoming events.

**Comment by austinlparker** [comment]
> For the project meeting on Tuesday, the maintainer's talk on Thursday, and quite a few other sessions, we ran into the problem that the capacity of the rooms assigned to us was not sufficient for the influx of people who would've wanted to attend them.
> 
> Given we're the second largest project in the CNCF, we should pass this on to the CNCF events team so they can consider this in their planning for upcoming events.

Please trust me in that we have given fairly constant feedback to the events team about this and continue to work closely with them on solutions. Bear in mind that while we are a very large project, we are not the _only_ project. That said, I'm confident that we will continue to iterate and improve together.

**Comment by mtwo** [comment]
+1 to Austin's comments: we've given feedback to the CNCF every Kubecon about (a) the project meeting conflicting with other events and (b) the rooms for our various presentations being too small. Also, we are **not** given time during the keynote to discuss project updates. I think that this is only available for graduated projects, though there's now enough of those that keynote slots may be even more restrictive.

Regarding technical talks, my understanding from talking to observability track reviewers is that more will get approved if they're submitted. Given that the maintainers track talk fills the room and gets 10/10 speaker scores, I think that it's providing a lot of value to attendees in its current format.

**Comment by codeboten** [comment]
> I think that this is only available for graduated projects, though there's now enough of those that keynote slots may be even more restrictive.

There's a part of keynotes dedicated to incubating projects which OpenTelemetry was not mentioned in this time around. See https://kccnceu2023.sched.com/event/1HyQL/keynote-cncf-incubating-project-updates

**Comment by jpkrohling** [comment]
Status: we have submitted a proposal for Contrib Fest 🤞🏽

**Comment by dyladan** [comment]
Submitted abstract:

> Join the OpenTelemetry maintainers in making OpenTelemetry better for everyone. OpenTelemetry will have several opportunities to contribute.
> 
> The OpenTelemetry Collector is vendor-agnostic implementation for receiving, processing and exporting telemetry data. The Collector is a large ecosystem, including individual components, a telemetry transformation language, helm charts, and a Kubernetes operator. Join the Collector maintainers and help fix bugs, add new features, and add new transformation functions.
> 
> OpenTelemetry JavaScript is an OTel client written in typescript which supports traces, metrics, and logs, but an observability client is only as good as the telemetry it collects. Help the OTel JS maintainers update the instrumentation libraries and ensure they are outputting semantic convention-compliant telemetry data.

Don't think it can be updated anymore but I'm putting it here so people know what to expect. Even if we don't update the abstract, we are still open to different ideas for the contribfest if they make sense.

**Comment by jiekun** [comment]
I have my proposal accepted at KubeCon + CloudNativeCon + OpenSourceSummit China 2023: https://sched.co/1PTFF

> Distributed tracing is crucial for troubleshooting in today's microservice architecture.In a sizable organization, over 100 million Trace Spans could be generated every second, requiring 200TB of disk space per day to store them. Collecting the entire volume of Trace data can be expensive, and many Traces that appear identical may not be helpful. OpenTelemetry offers various sampling policies. These policies help to reduce resource usage, but different policies require different amounts of network I/O, memory, and storage space to achieve varying sampling quality. Finding the best combo of different policies for a specific scenario is essential. We will share our experience in evaluating different combo of sampling policies by analyzing their cost and sampling quality quantitatively. We'll also introduce some sampling policies that aim to cover more edge cases. You will learn about the specific costs and benefits of different sampling policies and discover how to customize them for your own business.

I would like to have some review and input later on my dry-run presentation :)

**Comment by jpkrohling** [comment]
@jiekun, ping me on CNCF's Slack, we can try to find a slot. I'd love to watch your dry-run!

**Comment by jpkrohling** [comment]
Contrib fest accepted: https://sched.co/1R2rQ and [#otel-kubecon-questions](https://cloud-native.slack.com/archives/C05Q56W13SB) Slack channel created.

**Comment by jpkrohling** [comment]
I prepared a draft spreadsheet and invited maintainers to edit it. If you are a maintainer of OTel, ping me and I'll share the spreadsheet with you.

**Comment by jpkrohling** [comment]
As a summary: some things worked (AMA at the booth), some things worked REALLY well (contribfest), some didn't (booth duty). I'm closing this, and will create a new one to track our activities for KubeCon EU 2024.
