### ISSUE TITLE
REQUEST: New membership for rapphil

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/community#1456]
### GitHub Username

rapphil

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Aneurysm9 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
**Authored:**
https://github.com/open-telemetry/opentelemetry-collector/pull/5956
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13766
https://github.com/open-telemetry/opentelemetry-collector/pull/6683
https://github.com/open-telemetry/opentelemetry-lambda/pull/280
https://github.com/open-telemetry/opentelemetry-lambda/pull/545
https://github.com/open-telemetry/opentelemetry-collector/pull/6984
https://github.com/open-telemetry/opentelemetry-collector/pull/6876
**Reviewed:**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6963
https://github.com/open-telemetry/opentelemetry-java/pull/4700

- Issues responded to
https://github.com/open-telemetry/opentelemetry-specification/issues/2759
https://github.com/open-telemetry/oteps/pull/182
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21106
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20304

- SIG projects I am involved with
NA

**Comment by Aneurysm9** [comment]
I support

**Comment by vsakaram** [comment]
I support

**Comment by TylerHelmuth** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @rapphil!

**Comment by rapphil** [comment]
Thank you @arminru
