### ISSUE TITLE
Create a regular SIG meeting for the opentelemetry-ebpf SIG every Tuesday at 9am PST

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#1457]
Create a regular SIG meeting for the opentelemetry-ebpf SIG every Tuesday at 9am PST.

Create a google doc for notes and an entry in the calendar, associated with the Zoom call for this meeting.

Please help clarify if the process to set up the SIG meeting is different.

See https://docs.google.com/document/d/13GK915hdDQ9sUYzUIWi4pOfJK68EE935ugutUgL3yOw/edit# for the previous SIG meeting docs.

**Comment by trask** [comment]
hi @atoulme! can you send a PR to update the meeting time here? https://github.com/open-telemetry/community#implementation-sigs

you can continue using the same google doc (and it's already owned by the OTel Governance Committee google acct 👍)

I created a new Zoom meeting id and created the entry on the [public calendar](https://github.com/open-telemetry/community#calendar).

**Comment by atoulme** [comment]
Very cool! On it.
