### ISSUE TITLE
REQUEST: New membership for owais

### ISSUE THREAD

**Issue by owais** [open-telemetry/community#146]
### GitHub Username

@owais

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan
- @pjanotti

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
 https://github.com/open-telemetry/opentelemetry-service/pull/45
 https://github.com/open-telemetry/opentelemetry-service/pull/70
 https://github.com/open-telemetry/opentelemetry-service/pull/62
 https://github.com/open-telemetry/opentelemetry-service/pull/85
 https://github.com/open-telemetry/opentelemetry-service/pull/80
 https://github.com/open-telemetry/opentelemetry-service/pull/69
 https://github.com/open-telemetry/opentelemetry-service/pull/73
 https://github.com/open-telemetry/opentelemetry-service/pull/108
 https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/72 (open)
 https://github.com/census-instrumentation/opencensus-proto/pull/202 (open)

- Reviews
  https://github.com/open-telemetry/opentelemetry-service/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Aowais+ 

- Issues responded to
 https://github.com/open-telemetry/community/issues/53
 https://github.com/census-instrumentation/opencensus-service/issues/586
 https://github.com/open-telemetry/opentelemetry-service/issues/102

**Comment by tigrannajaryan** [comment]
I support the nomination as an Approver for OpenTelemetry Service.

**Comment by pjanotti** [comment]
Same here: I support @owais as approver for OpenTelemetry Service.

**Comment by bogdandrutu** [comment]
Invited him to the org based on the request to be a member of the organization.

**Comment by bogdandrutu** [comment]
@tigrannajaryan & @pjanotti we need a bit more proof I think based on the rules here:
https://github.com/open-telemetry/community/blob/master/community-membership.md#requirements-1. Probably in couple of weeks all the requirements will be met.

**Comment by tigrannajaryan** [comment]
@bogdandrutu OK, I was misremembering the PR count requirement. I thought we need 10 PRs, looks like the requirement is 30. No problem, he is actively contributing, should be there soon.

**Comment by owais** [comment]
I'd like to re-raise the request for membership.

-----------

Contributions since last consideration:

https://github.com/open-telemetry/opentelemetry-service/pull/326
https://github.com/open-telemetry/opentelemetry-service/pull/325
https://github.com/open-telemetry/opentelemetry-service/pull/212
https://github.com/open-telemetry/opentelemetry-service/pull/196
https://github.com/open-telemetry/opentelemetry-service/pull/191
https://github.com/open-telemetry/opentelemetry-service/pull/159
https://github.com/open-telemetry/opentelemetry-service/issues/138

Helped release a bug-fix OpenCensus service release
https://github.com/census-instrumentation/opencensus-service/releases/tag/0.1.11

Design doc on k8s automatic tagging. I'm working on the prototype right now.
https://docs.google.com/document/d/1HIhoKPJ_18GUwUkKW9o_j9iqgYUo2d9DeEV4T4X-I6U/edit#heading=h.v9evt864g5s9

**Comment by owais** [comment]
I've been able to contribute a little more to Otel (and OC) since the last time we considered my membership. I'd like to apply to become a member once more :)

Thanks.

**Comment by tigrannajaryan** [comment]
I support the nomination for Approver.

**Comment by bogdandrutu** [comment]
Sorry. This issue is for membership. Please consider to open a PR to add to the list here:
https://github.com/open-telemetry/community/blob/master/community-members.md#agent-and-collector

**Comment by owais** [comment]
https://github.com/open-telemetry/community/pull/172
