### ISSUE TITLE
REQUEST: New membership for @zeitlinger

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/community#1462]
### GitHub Username

@zeitlinger 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@jack-berg 
@jkwatson 

#### PRs reviewed / authored

opentelemetry-java
- https://github.com/open-telemetry/opentelemetry-java/pull/4271
- https://github.com/open-telemetry/opentelemetry-java/pull/1159
- https://github.com/open-telemetry/opentelemetry-java/pull/4535
- https://github.com/open-telemetry/opentelemetry-java/pull/4539
- https://github.com/open-telemetry/opentelemetry-java/pull/5026

#### SIG projects I am involved with

- Java

**Comment by zeitlinger** [comment]
@jkwatson @trask @carlosalberto @breedx-splk do you want to sponsor my membership?

**Comment by jkwatson** [comment]
I support.

**Comment by jack-berg** [comment]
I support

**Comment by zeitlinger** [comment]
Thanks so much :smile:

**Comment by arminru** [comment]
Invite sent. Welcome, @zeitlinger!
