### ISSUE TITLE
Please rename @open-telemetry/go-instrumentaiton-maintainers to @open-telemetry/go-instrumentation-maintainers

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1464]
There is a spelling error in the team name: https://github.com/orgs/open-telemetry/teams/go-instrumentaiton-maintainers. Can we please update the name to use the correct spelling of "instrumentation"?

[GitHub documentation on team renaming](https://docs.github.com/en/organizations/organizing-members-into-teams/renaming-a-team).

**Comment by arminru** [comment]
Team name updated. Hello @open-telemetry/go-instrumentation-maintainers 👋
