### ISSUE TITLE
 Is it necessary to trace before the front end initiates the request?

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/community#1470]
We have done the trace before and after the request, and I would like to ask how everyone in the industry does it
 Is it necessary to trace before the front end initiates the request?

**Comment by trask** [comment]
hi @runtu666! try asking in https://github.com/open-telemetry/opentelemetry-js (assuming you are talking about browser front ends) and/or in the [`#otel-client-side-telemetry`](https://cloud-native.slack.com/archives/C0239SYARD2) slack channel
