### ISSUE TITLE
REQUEST: New membership for yotamloe

### ISSUE THREAD

**Issue by yotamloe** [open-telemetry/community#1471]
### GitHub Username

@yotamloe

In response to: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi
- @atoulme

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PR's:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3800
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4386
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4395
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4431
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5512
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6159
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10821
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17011
#### Issues:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3736
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6226
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10836

**Comment by TylerHelmuth** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @yotamloe!
