### ISSUE TITLE
REQUEST: New opentelemetry-docs-examples repository

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#1474]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-docs-examples

### Requested changes

Request to add new repository with proposed name `opentelemetry-docs-examples`
 
### Purpose

During the last Comms SIG call we talked about our current effort to standardize the "Getting Started" across languages using the "same application" (see https://github.com/open-telemetry/opentelemetry.io/issues/2623). Eventually this sample should be used across all the docs. We want to make the source code of these applications (uninstrumented & instrumented) available outside of the docs markdown files for a few reasons:

* Makes it easier for end-users to get a copy of the (uninstrumented) code to follow along the documentation
* Possibility to verify the correctness of the code
* There were some requests to provide a "simple version" of the [Demo](https://github.com/open-telemetry/opentelemetry-demo), this might take away some of that need (cc @open-telemetry/demo-maintainers)
* Publishing them as containers: to provide a walkthrough getting started for the [operator](https://opentelemetry.io/docs/k8s-operator/) we need those images (see [this tutorial from KubeCon](https://github.com/pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial/blob/main/03-app-instrumentation.md) as reference where we want to land, cc @open-telemetry/operator-maintainers 

We have discussed a few alternatives to the above but agreed that a separate repository provides the best option:

* Alternative 1 "Host the application in https://github.com/open-telemetry/opentelemetry.io": this would highly increase the complexity of the docs repo (makes downloads bigger, layers of complexity for CI, ...)
* Alternative 2 "Host the applications in the language SIGs": all/most language SIGs already have an `examples/` folder, so hosting the app there would be possible. Doing that creates a need of the SIG maintainers to go through all the changes, creates a need to distinguish that sample app from others, we spread out common logic across multiple repositories (building the containers, CI checks, ...)
 
### Expected Duration

Potentially permanent

### Repository Maintainers

- @open-telemetry/docs-maintainers 

cc @cartermp @austinlparker @chalin

**Comment by trask** [comment]
cc @open-telemetry/technical-committee

**Comment by reyang** [comment]
> We want to make the source code of these applications (uninstrumented & instrumented) available outside of the docs markdown files

Would it work if we start by having these examples in a dedicated branch under the same (github.com/open-telemetry/opentelemetry.io) repo?

**Comment by svrnm** [comment]
> > We want to make the source code of these applications (uninstrumented & instrumented) available outside of the docs markdown files
> 
> Would it work if we start by having these examples in a dedicated branch under the same (github.com/open-telemetry/opentelemetry.io) repo?

We wanted to have a clean separation of docs & the example codes to not mix workflows, etc. I don't think that a dedicated branch is helping with that.

**Comment by tigrannajaryan** [comment]
@svrnm  this fell through the cracks. Is it is still actual?
