### ISSUE TITLE
Hold the 2023 Governance Committee election

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#1477]
Tracking issue for election-related tasks. Election announcements will be in a separate issue.

 - [x] #1478 23-25 October
 - [x] #1479 (helios)
 - [x] #1480
 - [x] #1560
 - [x] #1481
 - [x] #1482
 - [x] #1483
 - [x] #1484
 - [x] #1485
 - [x] #1486
 - [x] #1487
 - [x] #1488
 - [x] #1489
 - [x] #1490
 - [x] #1491
 - [x] #1492
 - [x] #1493
 - [x] #1494

**Comment by jpkrohling** [comment]
I'm closing this, as it's almost time to start planning for the next :-)
