### ISSUE TITLE
Create a new election in the voting system of choice

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#1480]
Depends on #1479 

~~Add @mtwo and @trask as trustees (election committee)~~ #1560

**Comment by jpkrohling** [comment]
For the future: the times should be 00:00 and not 12:00, and the final date should be 1 minute past midnight on the day after the announced date. For this year, it would have been Oct 26.

![image](https://github.com/open-telemetry/community/assets/13387/2925cd71-41b8-40a4-a249-8fc88cf178c2)

**Comment by jpkrohling** [comment]
To record the reasoning here: officially, it's 23:59 but we allowed two minutes buffer to account for people having trouble voting "last minute" and for clock drifts.
