### ISSUE TITLE
REQUEST: New membership for jeremydvoss

### ISSUE THREAD

**Issue by jeremydvoss** [open-telemetry/community#1496]
### GitHub Username

@jeremydvoss

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lzchen 
- @srikanthccv
- @ocelotl

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
Fix Windows auto-instrumentation: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1100
Fix django auto-instrumentation: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1369
BLRP variables: https://github.com/open-telemetry/opentelemetry-python/pull/3237
Custom sampler fix: https://github.com/open-telemetry/opentelemetry-python/pull/3026
Custom sampler injection: https://github.com/open-telemetry/opentelemetry-python/pull/2972
Use [Resource.to](http://resource.to/)_json: https://github.com/open-telemetry/opentelemetry-python/pull/2784
- Issues responded to (or initiated)
https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1102
https://github.com/open-telemetry/opentelemetry-python/issues/3244
https://github.com/open-telemetry/opentelemetry-python/issues/2746
https://github.com/open-telemetry/opentelemetry-python/issues/2747
https://github.com/open-telemetry/opentelemetry-python/issues/2772
https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1802
- SIG projects I am involved with
[OpenTelemetry Python](https://github.com/open-telemetry/opentelemetry-python)
[OpenTelemetry Python Contrib](https://github.com/open-telemetry/opentelemetry-python-contrib)

**Comment by ocelotl** [comment]
I support

**Comment by srikanthccv** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @jeremydvoss!
