### ISSUE TITLE
REQUEST: New membership for adrielp

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/community#1497]
### GitHub Username

@adrielp 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by dyladan** [comment]
It looks like you may not have fulfilled the requirements for a membership request.

> * [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
> * [ ]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
> * [ ]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

I also don't see sponsors listed. Please contact your sponsors and get their agreement before creating a membership request issue. If you have already contacted them, please add them to the issue description.

Please do not open a membership request issue until you have fulfilled the requirements. If you have already fulfilled the requirements, please open a new request with the relevant details filled out.

**Comment by adrielp** [comment]
Ok thanks. I will make sure to open again only once everything is completed. My apologies there.
