### ISSUE TITLE
Change meeting handling

### ISSUE THREAD

**Issue by AloisReitbauer** [open-telemetry/community#150]
Currently, we are using a Google calendar for all meetings which works but has some drawbacks. The main issue is that once linked to your calendar you see all meetings and not just the ones you are interested in crowding your calendar.

I would rather only see the meetings that I am interested in. However, I cannot delete meetings from a shared calendar. 

My proposal would be to also send meeting invites via the mailing list as well or have another way of adding individual meetings to the calendar.

Maybe there is also a pro trick with Google calendar I am not aware of.

**Comment by mtwo** [comment]
I'm in favour of adding the mailing lists to the meeting invites. Any objections?

**Comment by bhs** [comment]
@mtwo SGTM!

**Comment by bhs** [comment]
@AloisReitbauer your concern here was presaged by @sarahnovotny in a call a while back... paraphrasing, that "a single calendar is great until it isn't." Maybe we've already hit that point.

In gcal, btw, I think (?) you can take an existing meeting on some other calendar and copy the meeting to your own calendar. Though of course you would miss updates to times / zoom links / etc.

**Comment by mtwo** [comment]
I’ve added the community, contributors, and TC lists to the community meeting invite. Should we do the same for each SIG meeting?

________________________________
