### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1503]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib

### Requested changes

Please give write access to `opentelemetrybot` to those two repositories.
 
### Purpose

PRs opened by forking renovate need to be updated after they've been opened to make them useful. Running `go mod tidy` is required for the PR to pass all the CI checks. For the bot account to be able to update the PR, write permissions to the repositories are needed.
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/collector-contrib-maintainer  
- @open-telemetry/collector-maintainers

**Comment by trask** [comment]
> PRs opened by forking renovate need to be updated after they've been opened to make them useful. Running go mod tidy is required for the PR to pass all the CI checks. For the bot account to be able to update the PR, write permissions to the repositories are needed.

I agree this is an important automation use case (the Java Instrumentation repo could benefit from this as well).

Currently, https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot says:

> Important: You do not need to (and should not) give this account any permissions to any OpenTelemetry repository.

I think the main security issue is that currently the `OPENTELEMETRYBOT_GITHUB_TOKEN` is a "classic" personal access token, which means it's permissions really can't be scoped in a very meaningful way, and so if you give @opentelemetrybot write permission to a repository, anyone with that token could write to that repository.

The problem with using the new (beta) "fine-grained" personal access tokens was that GraphQL (and so most of `gh` CLI) didn't support them, but [it looks like support for GraphQL was added about a month ago](https://github.blog/changelog/2023-04-27-graphql-improvements-for-fine-grained-pats-and-github-apps/) 🎉

I'll set up a "fine-grained" personal access token for us to try out. I think we would still need to get everyone off of the "classic" personal access token and delete that (or at least rotate the token and lock it down to specific repos that still need it).

Ideally I think we would have
* shared across the OTel org: one "fine-grained" personal access token that doesn't give write access to anything, and that could be used for most automation
* per repository that needs it: one "fine-grained" personal access token that includes write access for (only) that repo

**Comment by pellared** [comment]
Can you please make sure that the PAT does not allow editing the GitHub Releases? 

As far as I know, the Write permission (even fine-grained for Contents scope) also gives the power to modify (create/delete) the  releases. Then the PAT (and bot) could be used to e.g. modify artifacts added to a release. Also if tag protection is not set - it would also allow creation/deletion of Git tags. If so then, adding such PAT increases the attack surface that could be used for supply chain attacks.

**Comment by pellared** [comment]
One more feference:  [Supply Chain Attacks via GitHub.com Releases](https://wwws.nightwatchcybersecurity.com/2021/04/25/supply-chain-attacks-via-github-com-releases/)

**Comment by codeboten** [comment]
Would one way we could potentially work around this issue not to produce releases with any artifacts from repositories that have these tokens enabled?

**Comment by pellared** [comment]
@codeboten  This is a good idea 👍 

Then we would just need (in Collector and Collector Contrib repos) something that would detect if something publishes an unwanted release.

For instance, we can create a GitHub workflow which triggers when a release is published and creates an issue.  I think it could be done like this (not tested):

```yaml
name: Unwanted release detector
permissions:
  contents: read
  issues: write 
on:
  release:
    types: [published]
jobs:
  report-unwanted-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        run: gh issue create --title "Unwanted release $GITHUB_REF" --body "${{ github.event.release.html_url }} SHOULD NOT be published." --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Instead of creating issues we could try [privately report a security vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability). 

Still the PAT could be used to create tags, which is like a "release of Go module". However, I am sure that the Collector maintainers would detect it almost immediately and they can [retract the module(s)](https://go.dev/ref/mod#go-mod-file-retract) and [create a repository security advisory](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/creating-a-repository-security-advisory).

**Comment by pellared** [comment]
> Still the PAT could be used to create tags

It would be enough to add a `*` [tag protection rule](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules).

**Comment by Aneurysm9** [comment]
> > Still the PAT could be used to create tags
> 
> It would be enough to add a `*` [tag protection rule](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules).

I think this is critical.  We should probably be doing this regardless whether we give a bot account write access given the importance of git tags being immutable to the Go package management system.  We would need a custom role to allow approvers to continue to manage collector releases.

**Comment by pellared** [comment]
> at that point we can start issuing fine-grained PATs with write access to a single repo for those who want to grant write permission to @opentelemetrybot.

The fine-grained PAT may leak e.g. via something like the ["Codecov breach"](https://about.codecov.io/security-update/) and then it could be used to modify existing releases to contain malicious code (e.g. a ransomware). Unfortunately supply chain attacks [are getting "popular"](https://www.csoonline.com/article/3677228/supply-chain-attacks-increased-over-600-this-year-and-companies-are-falling-behind.html).

PS. Even if we accept such risk, we should update https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot 😉

**Comment by trask** [comment]
> The fine-grained PAT may leak e.g. via something like the ["Codecov breach"](https://about.codecov.io/security-update/) and then it could be used to modify existing releases to contain malicious code (e.g. a ransomware). Unfortunately supply chain attacks [are getting "popular"](https://www.csoonline.com/article/3677228/supply-chain-attacks-increased-over-600-this-year-and-companies-are-falling-behind.html).

@pellared I liked your proposal above about creating a GitHub workflow to detect unwanted releases / release artifacts

> PS. Even if we accept such risk, we should update https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot 😉

👍

**Comment by tigrannajaryan** [comment]
@pellared this fell through the cracks. Is it is still actual?

**Comment by codeboten** [comment]
This is no longer needed, we have a workflow that works ok for renovabot
