### ISSUE TITLE
GitHub org request: Allow access via fine-grained personal access tokens

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1505]
@open-telemetry/technical-committee can you enable "Allow access via fine-grained personal access tokens" for the @open-telemetry GitHub org? I think the setting can be found at https://github.com/organizations/open-telemetry/settings/personal-access-tokens.

And can you add @opentelemetrybot as an @open-telemetry org member so that I can set up fine-grained personal access tokens for it targeting OpenTelemetry repositories?

For this setting: `Require approval of fine-grained personal access tokens`, it seems ok to me to choose `Do not require administrator approval`, but i'm also ok if you prefer `Require administrator approval`.

For context on this request, see https://github.com/open-telemetry/community/issues/1503#issuecomment-1562214077

**Comment by jmacd** [comment]
Done.
