### ISSUE TITLE
REQUEST: New membership for @swiatekm-sumo

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/community#1512]
### GitHub Username
@swiatekm-sumo

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@djaglowski 
@jaronoff97

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs reviewed / authored
Picked some of the more interesting ones:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11889
- https://github.com/open-telemetry/opentelemetry-collector/pull/5784
- https://github.com/open-telemetry/opentelemetry-collector/pull/5828
- https://github.com/open-telemetry/opentelemetry-collector/pull/7396
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13730
- https://github.com/open-telemetry/opentelemetry-operator/pull/1620
- https://github.com/open-telemetry/opentelemetry-operator/pull/1688
- https://github.com/open-telemetry/opentelemetry-operator/pull/1729
####  Issues responded to
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21912
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22036
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22067
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22620
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9003
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12084
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13449
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21743
- https://github.com/open-telemetry/opentelemetry-operator/issues/1707
- https://github.com/open-telemetry/opentelemetry-operator/issues/1477
#### SIG projects I am involved with
- https://github.com/open-telemetry/opentelemetry-collector
- https://github.com/open-telemetry/opentelemetry-operator

**Comment by jaronoff97** [comment]
I support!

**Comment by djaglowski** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @swiatekm-sumo!
