### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-go

### ISSUE THREAD

**Issue by pellared** [open-telemetry/community#1514]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go

### Requested changes

Give 'Admin' permissions to @pellared.
 
### Purpose

I want to fix branch protection rules so that we can take advantage of Dependabot for bumping GitHub Actions and Pip packages. Example: https://github.com/open-telemetry/opentelemetry-go/pull/4108#issuecomment-1556217087
 
### Expected Duration

2 work days

### Repository Maintainers

@open-telemetry/go-maintainers

**Comment by trask** [comment]
(@pellared just in case you haven't already seen: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-dependabot)

**Comment by pellared** [comment]
Alternatively someone from the TC could setup the branch protection rule per @trask's [reference](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-dependabot)).

@trask Thank you.

**Comment by pellared** [comment]
@arminru I just want to thank you and confirm that everything works. Thank you 👍
