### ISSUE TITLE
REQUEST: New membership for llc1123

### ISSUE THREAD

**Issue by llc1123** [open-telemetry/community#1525]
### GitHub Username

@llc1123

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan 
- @martinkuba 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-js/pull/3712
  - https://github.com/open-telemetry/opentelemetry-js/pull/3770
  - https://github.com/open-telemetry/opentelemetry-js/pull/3787
  - https://github.com/open-telemetry/opentelemetry-js/pull/3807
  - https://github.com/open-telemetry/opentelemetry-js/pull/3811
  - https://github.com/open-telemetry/opentelemetry-js/pull/3853
  - https://github.com/open-telemetry/opentelemetry-js/pull/3817#issuecomment-1552650338
  - https://github.com/open-telemetry/opentelemetry-js/pull/3798#issuecomment-1545300361
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-specification/issues/3514#issuecomment-1555010218
- SIG projects I am involved with
  - Opentelemetry JS

**Comment by martinkuba** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @llc1123!
