### ISSUE TITLE
REQUEST: New membership for xakep139

### ISSUE THREAD

**Issue by xakep139** [open-telemetry/community#1527]
### GitHub Username

@xakep139

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Kielek
- @cijothomas

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/949
- Issues responded to: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4499
- SIG projects I am involved with

**Comment by xakep139** [comment]
cc @dpk83 @evgenyfedorov2

**Comment by Kielek** [comment]
I support.

@xakep139 is a package owner in dotnet Contrib repository

**Comment by cijothomas** [comment]
I support.

**Comment by arminru** [comment]
For reference: This is part of https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1201.

**Comment by xakep139** [comment]
Thanks!
