### ISSUE TITLE
REQUEST: Enable Renovate on opentelemetry-demo

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1528]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-demo

### Requested changes

Install Renovate app (request made 5/6)

### Purpose

Setting up Renovate to automate dependency updates

### Repository Maintainers

- @open-telemetry/demo-maintainers

**Comment by arminru** [comment]
Installed and enabled for the demo repo:
![image](https://github.com/open-telemetry/community/assets/7052238/44797460-330d-4830-ba33-faad49723d12)

**Comment by arminru** [comment]
Note that the other repos use "Forking Renovate" instead. This one might be preferred for CLA reasons but we can consider adding an exemption rule like we have for dependatbot.
cc @trask

**Comment by austinlparker** [comment]
Could we get exemptions for renovate and dependabot on demo as well then?

**Comment by trask** [comment]
> Could we get exemptions for renovate and dependabot on demo as well then?

@dependabot is already exempted by EasyCLA team

and I think renovate (non-forking) is too: https://github.com/open-telemetry/community/issues/1439

if you run into EasyCLA failure related to renovate, just open a new issue (similar to #1439) and I'll open a ticket with EasyCLA team (they usually turn those around in just a couple of days)

**Comment by austinlparker** [comment]
Great, thanks.

**Comment by trask** [comment]
@austinlparker is everything resolved on this issue? thx

**Comment by julianocosta89** [comment]
I believe this one is good to be closed
