### ISSUE TITLE
REQUEST: New membership for markwolff

### ISSUE THREAD

**Issue by markwolff** [open-telemetry/community#153]
### GitHub Username

@markwolff

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mayurkale22 
- @SergeyKanzhelev 

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-js/pull/89
https://github.com/open-telemetry/opentelemetry-js/pull/93
https://github.com/open-telemetry/opentelemetry-js/pull/118

**Comment by bhs** [comment]
Sounds good to me! @markwolff are you up for making a PR against the membership .md file?

**Comment by bogdandrutu** [comment]
Invitation to the org members sent.
