### ISSUE TITLE
Authorize renovate to bypass CLA for Demo Repo

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1533]
Same problem as in #1439 

Repo: https://github.com/open-telemetry/opentelemetry-demo

**Comment by trask** [comment]
it looks like EasyCLA check is passing on that PR:

![image](https://github.com/open-telemetry/community/assets/218610/28bbe2f4-d2fc-44e1-a68a-524a4c97d104)

**Comment by austinlparker** [comment]
<img width="1017" alt="Screenshot 2023-06-07 at 2 12 37 PM" src="https://github.com/open-telemetry/community/assets/4140740/3729af9a-d6a4-4fcf-95d8-1e6a349ae65c">

This is what happens when I try to update the branch.

**Comment by austinlparker** [comment]
I guess this is actually due to branch protection rules?

**Comment by trask** [comment]
> I guess this is actually due to branch protection rules?

ya, I sent #1535 which should clarify

@open-telemetry/technical-committee I think if you can add renovate branch protection rule for https://github.com/open-telemetry/opentelemetry-demo (according to #1535) that should resolve this issue.
