### ISSUE TITLE
 Requesting TC review for PHP Logs API/SDK spec compliance

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#1537]
Requesting a compliance review from https://github.com/orgs/open-telemetry/teams/technical-committee prior to GA release. If there are questions you can ask myself or any of the other PHP maintainers (@brettmc or @pdelewski)

[UPDATE from @tigrannajaryan] I am doing the review. Here is my checklist so far, borrowed mostly from compatibility matrix (checkmark means reviewed/verified against spec definition):

- [x] Getting Started example works
- [x] LoggerProvider.Get Logger
- [x] LoggerProvider.Get Logger accepts attributes	
- [x] LoggerProvider.Shutdown
- [x] LoggerProvider.ForceFlush
- [x] Can get global LoggerProvider
- [x] Can set global LoggerProvider 
- [x] Logger.Emit(LogRecord)	
- [x] SimpleLogRecordProcessor ([needs a rename](https://github.com/open-telemetry/opentelemetry-php/issues/1063))
- [x] BatchLogRecordProcessor ([doesn't support async emitting](https://github.com/open-telemetry/opentelemetry-php/issues/1064#issuecomment-1611272769)), ([needs a rename](https://github.com/open-telemetry/opentelemetry-php/issues/1063))
- [x] Can plug custom LogRecordProcessor
- [x] OTLP/gRPC exporter		
- [x] OTLP/HTTP exporter		
- [ ] OTLP File exporter - Not yet implemented according to compatibility matrix.
- [x] Can plug custom LogRecordExporter
- [x] Trace Context Injection
- [x] LogRecord fields output

**Comment by carlosalberto** [comment]
@tigrannajaryan

**Comment by tigrannajaryan** [comment]
@open-telemetry/php-maintainers I finished working through my checklist. Other than a few bugs/clarification questions I filed as issues everything looks good to me.

Are there any other areas that you would like me to take a look?

**Comment by brettmc** [comment]
Thanks, @tigrannajaryan 
I'm not confident about our handling of complex LogRecord attributes, I think it needs a closer look. In particular, we apply the "must be primitive or homogeneous array of primitives" check on them, but I suspect should not.

**Comment by tigrannajaryan** [comment]
> Thanks, @tigrannajaryan I'm not confident about our handling of complex LogRecord attributes, I think it needs a closer look. In particular, we apply the "must be primitive or homogeneous array of primitives" check on them, but I suspect should not.

@brettmc done and filed a couple bugs. If you can think of another review area please let me know.

**Comment by tigrannajaryan** [comment]
@brettmc is there anything else that you would like me to take a look? If not I will close this issue as done.

**Comment by brettmc** [comment]
@tigrannajaryan no, nothing else. Thank you very much for the detailed review, it was very useful!
I have updated and closed the related issues, as I believe them to all be resolved now.

**Comment by tigrannajaryan** [comment]
Closing as "done".
