### ISSUE TITLE
EasyCLA is picking up the wrong "Austin Parker" when Co-authored-by

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1538]
See https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1686149746830439

and test cases:
* https://github.com/open-telemetry/opentelemetry-demo/pull/933
* https://github.com/open-telemetry/opentelemetry-demo/pull/934

I will open ticket with the EasyCLA team, just wanted to open this issue for tracking and transparency.

**Comment by trask** [comment]
https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-18913

**Comment by wojtekLs** [comment]
@trask Spack Jira. Dickheads

**Comment by trask** [comment]
EasyCLA team has fixed this bug
