### ISSUE TITLE
Chinese translation for opentelemetry specs,docs etc

### ISSUE THREAD

**Issue by sunface** [open-telemetry/community#154]
Hi all:
Great work on OpenTelemetry!

We are a translation team from china, and we sincerely want to translate OpenTelemetry's specs,docs to chinese to make more people knowing and using opentelemetry in the future.

Our work has already begun: @opentelemetry-cn(cn is short for china), so if you have any questions or suggestions, please notify us, and we will do better late

**Comment by bhs** [comment]
@sunface first of all, *thank you*, this is much appreciated.

I'm wondering if it would make more sense to create the various repos within the main OpenTelemetry GitHub organization... that is, to create `open-telemetry/specification-cn`, `open-telemetry/community-cn`, etc. This would be more discoverable, and also play nicer with the GitHub permissions model.

Also, which repos are we talking about replicating? Just the document-heavy repos, or the others as well? (I would be nervous about keeping the code-focused language repos in sync across languages so would prefer not to fork those for this purpose, but rather to find ways to keep docs translated within those repos... though I'm open to other opinions and lessons from other projects)

What do you think?

**Comment by mtwo** [comment]
+1 to Ben's suggestion
________________________________

**Comment by sunface** [comment]
Hi @bhs @mtwo, thanks for your suggestions.
1. Great, we want to  move our repo to main OpenTelemetry  organization too,so which steps should we take to achieve that goal?
2. We will not do any code sync things, as the codes will be quickly changed in a long time, so it makes no sense. What we want do is to
- Translate the docs, specs,official blogs... to chinese
- Write chinese articles about OpenTelemetry(Technical principle, Core code analysis etc), by the way, we are also a experienced team good at APM)
- Maintain the chinese community such as online chatting with QQ, community Meetings in  first-tier cities in china
- Help chinese developers to use OpenTelemetry in their projects

**Comment by mtwo** [comment]
@SergeyKanzhelev @yurishkuro @sarahnovotny @bogdandrutu FYI

@sunface I agree we shouldn't try to translate the code comments or perform any kind of code synchronization.

I suggest that we provide translations of the specs, community, and docs repos (and whichever others make sense). We can do this either in -cn versions of the existing repositories (as Ben suggested), or via -cn files and folders within each repository.

**Comment by yurishkuro** [comment]
My only concern is with whether this is going to be a one time translation effort or ongoing support, at least through the next 6 months when the specs will still be undergoing frequent changes.

I also prefer a separate -cn repo, unless we have two or more committers fluent in Chinese.

**Comment by sunface** [comment]
@yurishkuro 
First of all, thanks for your suggestion.

We are a team work on commercial APM for years. At first we are going to make our apm and pinpoint agent compatible with OpenTracing, now our plan surely turns to OpenTelemetry.

We have three core members, and also maintained a golang commnunity(about 2000 acitve chinese members now) for 4 years,  so a onetime translation will never happen.

BTW, our apm and opentracing  experiences will help us to do translation and community maintaing better

**Comment by bhs** [comment]
@sunface thanks! So, can I create the following and make you an admin?

* github.com/open-telemetry/community-cn
* github.com/open-telemetry/specification-cn

I think translating the RFCs is too likely to fall out of date, but that would be the other obvious candidate for translation.

How do we track the status of the translation? Is there some way to mark the most-recent (English)  commit that's been translated?

**Comment by sunface** [comment]
Hi, @bhs 

Yes, please,  you can create this one now: github.com/open-telemetry/docs-cn,  and we will put specification, rfcs, sdk docs altogether in that repo.Otherwise, it's easy to manage.

There is a version tag in github.com/open-telemetry/specification, so we can use it in cn-repo to  to keep both versions consistent.

**Comment by yurishkuro** [comment]
@sunface done https://github.com/open-telemetry/docs-cn

**Comment by sunface** [comment]
@yurishkuro thanks, can you invite @congim  and @addname to this project? they are also in my team

**Comment by SergeyKanzhelev** [comment]
I have invited  @congim and @addname bypassing the official request issue creation. Welcome!

Do you all need maintainer role on the repository?

**Comment by SergeyKanzhelev** [comment]
It looks like all permissions were set. Please accept invites. Re-open the issue or file a new one if you need more assistance, please

**Comment by sunface** [comment]
Hi @SergeyKanzhelev, thanks for helping, can you re-invite  @addname ? last invitation seems out-of-date
