### ISSUE TITLE
REQUEST: New membership for @estolfo

### ISSUE THREAD

**Issue by estolfo** [open-telemetry/community#1544]
### GitHub Username

@estolfo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask
- @joaopgrassi 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - https://github.com/open-telemetry/semantic-conventions/pull/23
    - https://github.com/open-telemetry/opentelemetry-specification/pull/3358 (duplicate of above)
    - https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/357
    - https://github.com/open-telemetry/opentelemetry-proto/pull/484
- Issues responded to
    - https://github.com/open-telemetry/oteps/pull/182 (in SIG)
    - https://github.com/open-telemetry/opentelemetry-specification/issues/3535
    - https://github.com/open-telemetry/opentelemetry-specification/issues/3239
- SIG projects I am involved with
    - Specification SIG
    - Ruby SIG

**Comment by joaopgrassi** [comment]
I support!

**Comment by trask** [comment]
I support!

**Comment by carlosalberto** [comment]
Invitation sent, thanks!
