### ISSUE TITLE
Add README to otel github org

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#1545]
Not sure whom to ping regarding this to get a review/merge, so I put this issue here for visibility :-)

> I thought it would be nice to have a organization README that is presented on github.com/open-telemetry (as outlined here: https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)

https://github.com/open-telemetry/.github/pull/5

**Comment by breedx-splk** [comment]
It's merged and we can close this now right? Also, nice work, looks good!
