### ISSUE TITLE
REQUEST: New membership for rnishtala-sumo

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/community#1546]
### GitHub Username

rnishtala-sumo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @astencel-sumo 
- @atoulme 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22968
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23210
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22715
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22787
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22787
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22123
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
  - https://github.com/open-telemetry/opentelemetry-collector

**Comment by astencel-sumo** [comment]
I'd be happy to sponsor your membership @rnishtala-sumo.

You still need to find one more sponsor though, and the instructions explicitly say:

> I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

So not sure what to do here 😉 

Btw. here's another contribution of yours that you might want to includ in the application:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22123
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22715

**Comment by astencel-sumo** [comment]
@rnishtala-sumo is also a code owner for the Syslog exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.79.0/.github/CODEOWNERS#L79.

**Comment by astencel-sumo** [comment]
I support!

**Comment by rnishtala-sumo** [comment]
thank you @atoulme !

**Comment by TylerHelmuth** [comment]
I support

**Comment by codeboten** [comment]
👍🏻

**Comment by arminru** [comment]
Invite sent. Welcome, @rnishtala-sumo!

**Comment by rnishtala-sumo** [comment]
Thank you! :tada:
