### ISSUE TITLE
REQUEST: New membership for jonatan-ivanov

### ISSUE THREAD

**Issue by jonatan-ivanov** [open-telemetry/community#1548]
### GitHub Username

@jonatan-ivanov

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask
- @jack-berg

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored and Issues responded to
  - opentelemetry-specification 
    - https://github.com/open-telemetry/opentelemetry-specification/pull/3274
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2930
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2292
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2584
    - https://github.com/open-telemetry/opentelemetry-specification/pull/3355
    - https://github.com/open-telemetry/opentelemetry-specification/issues/3311
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2550
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2388
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2272
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2257
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2111
    - https://github.com/open-telemetry/opentelemetry-specification/issues/2118
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2035
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2101
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2105
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2106
    - https://github.com/open-telemetry/opentelemetry-specification/pull/2104
    - https://github.com/open-telemetry/opentelemetry-specification/pull/1753
    - https://github.com/open-telemetry/opentelemetry-specification/issues/464
    - https://github.com/open-telemetry/opentelemetry-specification/issues/1732
    - https://github.com/open-telemetry/opentelemetry-specification/pull/1665
    - https://github.com/open-telemetry/opentelemetry-specification/pull/1645
    - https://github.com/open-telemetry/opentelemetry-specification/pull/1617
    - https://github.com/open-telemetry/opentelemetry-specification/issues/1593
    - https://github.com/open-telemetry/opentelemetry-specification/pull/1590
    - https://github.com/open-telemetry/opentelemetry-specification/discussions/1371
    - https://github.com/open-telemetry/opentelemetry-specification/discussions/1370
    - https://github.com/open-telemetry/opentelemetry-specification/discussions/1369
    - https://github.com/open-telemetry/opentelemetry-specification/discussions/1368
    - https://github.com/open-telemetry/opentelemetry-specification/issues/1361
  - opentelemetry-java
    - https://github.com/open-telemetry/opentelemetry-java/pull/4933
    - https://github.com/open-telemetry/opentelemetry-java/issues/4932
    - https://github.com/open-telemetry/opentelemetry-java/issues/4381
    - https://github.com/open-telemetry/opentelemetry-java/pull/3353
    - https://github.com/open-telemetry/opentelemetry-java/issues/3123
    - https://github.com/open-telemetry/opentelemetry-java/discussions/2328
  - opentelemetry-java-instrumentation
    - https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7006
    - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6635
    - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6561
    - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4919
  - opentelemetry-java-contrib
    - https://github.com/open-telemetry/opentelemetry-java-contrib/pull/140
    - https://github.com/open-telemetry/opentelemetry-java-contrib/pull/71
  - opentelemetry-collector-contrib
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18913
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18903
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16530
- SIG projects I am involved with
  - OpenTelemetry Java + Instrumentation SIG
  - OpenTelemetry JVM Monitoring Working Group
  - Used to be involved with the Specifications SIG (Metrics API/SDK specs from late-2020 till mid-2022)

**Comment by jack-berg** [comment]
I support

**Comment by trask** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @jonatan-ivanov!
