### ISSUE TITLE
REQUEST: New membership for aboguszewski-sumo

### ISSUE THREAD

**Issue by aboguszewski-sumo** [open-telemetry/community#1551]
### GitHub Username

@aboguszewski-sumo

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @astencel-sumo 
- @djaglowski 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22976
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19423
PRs related to  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14635, for example https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16346
PRs related to  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14095, for example https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16053
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12767
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14340

#### Issues
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22145
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23212
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14791
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14635
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14095
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12766

**Comment by djaglowski** [comment]
I support!

**Comment by astencel-sumo** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @aboguszewski-sumo!
