### ISSUE TITLE
REQUEST: New membership for chrlic

### ISSUE THREAD

**Issue by chrlic** [open-telemetry/community#1565]
### GitHub Username

@chrlic

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pavolloffay 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-operator - authored:
PR 1236
PR 1305
PR 1444
PR 1826
PR 1827
PR 1847
PR 1853
- Issues responded to
https://github.com/open-telemetry/opentelemetry-operator :
1572
1821
1820
- SIG projects I am involved with

**Comment by pavolloffay** [comment]
+1

**Comment by TylerHelmuth** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @chrlic!
