### ISSUE TITLE
Missing meeting recordings from 2023-06-28

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/community#1571]
Looking at the recording list for Wednesday, June 28th 2023 in the [Google Doc](https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s/edit), the only link is the PHP SIG, but on that day a couple other SIG meeings happened, including the Collector SIG at 9am PT ([Zoom link](https://zoom.us/j/97380657643?pwd=RzJhQUp2ZHc0aHlma1dPRDNsVWlNQT09)). I'm not seeing links to those in the doc.

![image](https://github.com/open-telemetry/community/assets/70892616/34367aeb-d330-4e84-af81-739b5de48fcf)
![image](https://github.com/open-telemetry/community/assets/70892616/e53316ac-8aa1-405a-bd71-4fb8f768bf2d)

**Comment by arminru** [comment]
@trask can you take a look please? As per #1431 I _think_ the recordings should be working again.

**Comment by trask** [comment]
yeah, it looks like we hit the limit on June 28 at 9:04am Pacific Time, and we upgraded to paid account on June 28 at 4:40pm Pacific Time, which explains the missing recordings on June 28.

I'm going to truncate the spreadsheet to June 29 and later to avoid the confusion going forward that any recordings may be missing

**Comment by astencel-sumo** [comment]
Sounds good to me, thanks a lot @trask

**Comment by arminru** [comment]
Thank you, @trask!
