### ISSUE TITLE
Should the "Governance Committee private meeting" recording be publicly available?

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/community#1572]
I honestly don't know, but figured it's better to ask.

![image](https://github.com/open-telemetry/community/assets/70892616/9bf1e0e9-2e74-47a6-a651-ff3c74a6d3c4)

**Comment by trask** [comment]
thx for asking! the meeting is not open for others to join, but the recordings are publicly available

I've updated the name of the meeting to just "Governance Committee" to avoid the confusion (it's already not on the public calendar)

**Comment by astencel-sumo** [comment]
All right, thanks for the explanation, closing this issue then.
