### ISSUE TITLE
REQUEST: New repository request - "opentelemetry-security"

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1575]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-security

### Requested changes

New repository

### Purpose

The newly established SIG Security needs a home for its documents and issue tracker. The initial maintainers are: @jpkrohling, @reyang and @cartersocha, as per https://github.com/open-telemetry/community/issues/1454

### Expected Duration

Permanent.

### Repository Maintainers

Please create the following group with the three aforementioned people:

- @open-telemetry/security-maintainers

**Comment by codeboten** [comment]
Not a blocker, but could the repo name be https://github.com/open-telemetry/security?

**Comment by trask** [comment]
or security-governance, to avoid the confusion that this is a related to something for end users?

**Comment by trask** [comment]
or https://github.com/open-telemetry/sig-security, based on https://github.com/open-telemetry/community/pull/1576#discussion_r1253756483, to match k8s naming which uses the `sig-` prefix to help differentiate from something for end users

**Comment by cpanato** [comment]
+1 for the sig-security

**Comment by carlosalberto** [comment]
@jpkrohling It's created now. @cartersocha and @reyang are now also members of the sig-security-maintainers group (for that repo).

**Comment by carlosalberto** [comment]
Please confirm (and close this issue).

**Comment by jpkrohling** [comment]
Thanks!
