### ISSUE TITLE
REQUEST: New membership for hauleth

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/community#158]
### GitHub Username

hauleth

### Organization you are requesting membership in

open-telemetry

### Requirements

I'm opening this for hauleth and can attest that he is active, on gitter, etc

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@tsloughter 
@bogdandrutu 

### List of contributions to the OpenTelemetry project

He is a member of and has actively been working on OpenCensus Erlang client https://github.com/census-instrumentation/opencensus-erlang/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Ahauleth+

**Comment by bogdandrutu** [comment]
@hauleth please say +1 if you agree. Also please make sure that you check all items in the list of requirements.

**Comment by hauleth** [comment]
+1 and I have fulfilled all requirements
