### ISSUE TITLE
REQUEST: New membership for felixge

### ISSUE THREAD

**Issue by felixge** [open-telemetry/community#1582]
### GitHub Username

felixge

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jsuereth
- @tigrannajaryan 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Various Architecture Proposals ([Doc](https://docs.google.com/document/d/1aS6OaPQzbPyKxxkMSKMZFZiGqIfOYWeFPbhfxPmLceE/edit#heading=h.pyp5l8amax90), [Slides](https://docs.google.com/presentation/d/1tfS9vv-8hrNlGRUHRTvMxtnfHlYHaEQVCwmJDDbel3A/edit#slide=id.p))
- [protobuf draft PR](https://github.com/felixge/opentelemetry-proto/pull/1)
- [pprof timestamp proposal](https://github.com/google/pprof/pull/728)
- Member of Profiling SIG

**Comment by tigrannajaryan** [comment]
I support.

**Comment by tylerbenson** [comment]
I also support.

**Comment by arminru** [comment]
Hi @felixge!
The PR you linked above (https://github.com/felixge/opentelemetry-proto/pull/1) targets your own fork rather than the upstream repo https://github.com/open-telemetry/opentelemetry-proto-profile, not sure if that's intentional or not 🙂

**Comment by arminru** [comment]
Invite sent. Welcome, @felixge!
