### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-proto-profile

### ISSUE THREAD

**Issue by petethepig** [open-telemetry/community#1583]
### Affected Repository

e.g. https://github.com/open-telemetry/opentelemetry-proto-profile

### Requested changes

I'm not sure exactly what needs to be done, but currently when I try to push to a branch, I get this error:
```shell
$ git push profile profiling
remote: error: GH006: Protected branch update failed for refs/heads/profiling.
remote: error: Required status check "EasyCLA" is expected.
```

I think we either need to:
* relax branch protection rules, or
* enable EasyCLA on the repo
 
### Purpose

This unblocks development in opentelemetry-proto-profile repo
 
### Expected Duration

permanently

### Repository Maintainers

@Rperry2174

**Comment by tigrannajaryan** [comment]
We don't push to Otel repo branches. The workflow normally is: make a fork, push to a branch in your fork, then create a PR against the repo in Otel org.

Is there a reason that you need a branch in this repo?

**Comment by petethepig** [comment]
@tigrannajaryan Ah, I see. Yeah, that will work too. 

Thank you!
