### ISSUE TITLE
REQUEST: New membership for ccaraman

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/community#159]
### GitHub Username

@ccaraman

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pjanotti 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- [PRs authored](
https://github.com/open-telemetry/opentelemetry-service/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Accaraman+)
- [PRs reviewed](https://github.com/open-telemetry/opentelemetry-service/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Accaraman+)
- [Issues responded to](https://github.com/open-telemetry/opentelemetry-service/issues?utf8=%E2%9C%93&q=is%3Aissue+ccaraman)
- SIG projects I am involved with - none yet :)

**Comment by SergeyKanzhelev** [comment]
Welcome, @ccaraman!
