### ISSUE TITLE
REQUEST: New membership for tammy-baylis-swi

### ISSUE THREAD

**Issue by tammy-baylis-swi** [open-telemetry/community#1590]
### GitHub Username

@tammy-baylis-swi

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cartersocha 
- @ocelotl

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1762
   https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1784
   https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1810
   https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1873
- Issues responded to
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/936
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1752
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1779
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1809
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1872
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1591
   https://github.com/open-telemetry/opentelemetry-python-contrib/issues/367#issuecomment-1479917275
   https://github.com/open-telemetry/opentelemetry-specification/issues/3560
- SIG projects I am involved with

**Comment by cartersocha** [comment]
I support

**Comment by srikanthccv** [comment]
I support

**Comment by shalevr** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @tammy-baylis-swi!
