### ISSUE TITLE
REQUEST: New membership for lizthegrey

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#160]
### GitHub Username

@lizthegrey

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @iredelmeier 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
-- https://github.com/open-telemetry/rfcs/pull/24 (with @bogdandrutu)
-- https://github.com/open-telemetry/opentelemetry-specification/pull/180
- Issues responded to
-- https://github.com/open-telemetry/opentelemetry-go/issues/90
- SIG projects I am involved with
-- OpenTelemetry Tuesdays -- a weekly community podcast/livestream with @iredelmeier -- examples at twitch.tv/lizthegrey
-- OpenTelemetry Go workshop being developed with @ymotongpoo at https://glitch.com/edit/#!/equable-burn

**Comment by bhs** [comment]
LGTM! Thank you for all of your contributions, @lizthegrey. I see that Bogdan and Isobel have already 👍 so I've changed your GitHub permissions and am closing this issue.

(PS: I also found some typos in the membership doc in the process... https://github.com/open-telemetry/community/pull/161)
