### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java-examples

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1601]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-java-examples

### Requested changes

Install Renovate app
 
### Purpose

We want to explore advantages of using Renovate over Dependabot, see https://github.com/open-telemetry/opentelemetry-java-examples/issues/151
 
### Expected Duration

Probably permanently

### Repository Maintainers

- @open-telemetry/java-maintainers
- @open-telemetry/java-instrumentation-maintainers

**Comment by jack-berg** [comment]
All set on this.
