### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry.io

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/community#1604]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io 

### Requested changes

Please add the opentelemetry.io repo to the @open-telemetry/helm-approvers and @open-telemetry/helm-maintainers teams
 
### Purpose

I am writing new helm documentation for the site and would like to add @open-telemetry/helm-approvers to the CODEOWNERS file.
 
### Expected Duration

permanently

### Repository Maintainers
- @open-telemetry/docs-maintainers

**Comment by cartermp** [comment]
Done!
