### ISSUE TITLE
REQUEST: New membership for adrielp

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/community#1605]
### GitHub Username

@adrielp

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @atoulme 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23225
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24241
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22028
- SIG projects I am involved with
  - attends the otel collector sig
- Other things
  - focused on an o11y initiative at the company i work for getting others to be contributors to OTEL 
  - kicked off the liatrio-otel-collector distribution to help enable contributions from Liatrio -> OTEL
  - Got Liatrio to be CCLA'd for CNCF starting with OTEL

**Comment by jpkrohling** [comment]
The membership rules mention "several contributions", and I think being the code owner for one component for the contrib would be a good equivalent. Therefore, I support this.

**Comment by atoulme** [comment]
I support!

**Comment by jpkrohling** [comment]
@open-telemetry/technical-committee, is anything preventing this request from moving forward?

**Comment by jsuereth** [comment]
Invite is sent

**Comment by adrielp** [comment]
Invitation accepted @jsuereth . Thanks!
