### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java-contrib

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1607]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-java-contrib

### Requested changes

Install Renovate app
 
### Purpose

[Onboarding Renovate to the opentelemetry-java-examples repo went well](https://github.com/open-telemetry/opentelemetry-java-examples/pull/180), and we want to move on to opentelemetry-java-contrib next.
 
### Expected Duration

Probably permanently

### Repository Maintainers

- @open-telemetry/java-contrib-maintainers

**Comment by jack-berg** [comment]
All set!
