### ISSUE TITLE
REQUEST: New membership for pxaws

### ISSUE THREAD

**Issue by pxaws** [open-telemetry/community#1612]
### GitHub Username

@pxaws

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @TylerHelmuth
- @atoulme

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3211
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3218
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3367
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3372
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3426
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3683
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3698
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3756
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3790
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3793
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3802
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3846
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3853
 * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3880
- Issues responded to
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2307
- SIG projects I am involved with
  * https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by atoulme** [comment]
I support!

**Comment by jpkrohling** [comment]
I support

**Comment by pxaws** [comment]
Thanks @TylerHelmuth

**Comment by pxaws** [comment]
Thanks @jpkrohling

**Comment by pxaws** [comment]
Thanks @atoulme

**Comment by carlosalberto** [comment]
Invitation sent, welcome!
