### ISSUE TITLE
[proposal] Remove markdown-link-check

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/community#1613]
I cannot merge a one-line plain text PR for 2 weeks because this linter keeps failing on random links that take too long and the linter time out (and has no timeout settings). This seems like a ridiculous barrier to contributions.

Options:
  * remove it altogether (does it really provide value for this repo, compared to friction it creates?)
  * run it only on main, if someone wants to check the links occasionally
  * fix it so that if it does run on PRs, it only checks _the changes_, and doesn't block PRs because some completely unrelated link somewhere is failing

**Comment by trask** [comment]
markdown-link-check isn't a required status check, so it shouldn't be blocking merging?

**Comment by trask** [comment]
Closing, markdown-link-check isn't a required status check (anymore?) so I think this is resolved

![image](https://github.com/user-attachments/assets/8cafa7f9-5c6e-4fe7-9523-d020bc910cdb)
