### ISSUE TITLE
REQUEST: Add @swiatekm-sumo to @open-telemetry/operator-approvers

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/community#1618]
# Affected Repository
https://github.com/open-telemetry/opentelemetry-operator

# Requested changes
Please add @swiatekm-sumo to the @open-telemetry/operator-approvers group

# Purpose
We have promoted @swiatekm-sumo to an approver within our repo and now we need the github team updated to reflect. I merged [this PR](https://github.com/open-telemetry/opentelemetry-operator/pull/1966) with two thirds of the maintainers approving.

**Comment by jack-berg** [comment]
You should be able to do this yourself. If the teams were setup properly, the operator-maintainers should all be “maintainers” of the operator-approvers team, as documented here: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams

I’ve fixed the team setup by assigning you the “maintainer” role on the operator-maintainer team, and by adding the missing maintainers as explicit members of operator-approvers with the “maintainer” role.

You should now be able to add new approvers.
