### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java-instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1620]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-java-instrumentation

### Requested changes

Install Renovate app
 
### Purpose

Onboarding Renovate to the opentelemetry-java-examples and opentelemetry-java-contrib repos went well, and we want to move on to opentelemetry-java-instrumentation next.
 
### Expected Duration

Probably permanently

### Repository Maintainers

- @open-telemetry/java-instrumentation-maintainers

**Comment by jack-berg** [comment]
I believe this has already been added.

**Comment by trask** [comment]
this has been done
