### ISSUE TITLE
REQUEST: New membership for @johnnyshields

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/community#1625]
### GitHub Username

@johnnyshields

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite) --> I have tried to join but failed. Please let me know how I can sign up.
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @arielvalentin
- @mwear 

### List of contributions to the OpenTelemetry project

PRs reviewed / authored:
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/109
- https://github.com/open-telemetry/opentelemetry-ruby/pull/1331 
- https://github.com/open-telemetry/opentelemetry-ruby/pull/934 
- https://github.com/open-telemetry/opentelemetry-ruby/pull/690 
- https://github.com/open-telemetry/opentelemetry-ruby/pull/590 
- https://github.com/open-telemetry/opentelemetry-ruby/pull/563
- https://github.com/open-telemetry/opentelemetry-ruby/pull/562
- https://github.com/open-telemetry/opentelemetry-ruby/pull/546
- https://github.com/open-telemetry/opentelemetry-ruby/pull/536
- https://github.com/open-telemetry/opentelemetry-ruby/pull/478
- https://github.com/open-telemetry/opentelemetry-ruby/pull/477
- https://github.com/open-telemetry/opentelemetry-ruby/pull/472
- https://github.com/open-telemetry/opentelemetry-ruby/pull/448
- https://github.com/open-telemetry/opentelemetry-ruby/pull/447

Issues responded to:
- Quite a few on https://github.com/open-telemetry/opentelemetry-ruby and https://github.com/open-telemetry/opentelemetry-ruby-contrib

SIG projects I am involved with:
- Not currently participating but I have been involved in discussions with the Ruby SIG and Semantic Convention SIG in the past.

**Comment by arielvalentin** [comment]
I support!

**Comment by johnnyshields** [comment]
@fbogsany please kindly give support if you are ok to do so. I've added your name b/c you've merged many of my PRs.

**Comment by carlosalberto** [comment]
Ping @fbogsany

**Comment by mwear** [comment]
Feel free to add me as a sponsor @johnnyshields.

**Comment by johnnyshields** [comment]
@mwear thank you! Done.

**Comment by mwear** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @johnnyshields!
