### ISSUE TITLE
REQUEST: New membership for @simi

### ISSUE THREAD

**Issue by simi** [open-telemetry/community#1626]
### GitHub Username

@simi

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @arielvalentin
- @robbkidd

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Slack discussions (trying to helping other users to resolve problems, trying to help other Ruby maintainers)
- https://github.com/open-telemetry/opentelemetry-ruby/pull/1443
- https://github.com/open-telemetry/opentelemetry-demo/pull/989 (problems resolved over Slack)
- I'm actively triaging issues in opentelemetry-ruby and opentelemetry-ruby-contrib repos

**Comment by robbkidd** [comment]
I support.

(Support Credentials: I am currently an [Approver for otel-ruby](https://github.com/orgs/open-telemetry/teams/ruby-approvers) and [Maintainer for otel-ruby-contrib](https://github.com/orgs/open-telemetry/teams/ruby-contrib-maintainers).)

**Comment by arminru** [comment]
Invite sent. Welcome, @simi!
