### ISSUE TITLE
REQUEST: Project maintenance for Go Auto Instrumentation: Beta

### ISSUE THREAD

**Issue by pellared** [open-telemetry/community#1627]
### Affected Project

https://github.com/orgs/open-telemetry/projects/50/ public 

### Requested changes

Make the project public 
 
### Purpose

We want to transparently share our plan
 
### Expected Duration

Infinite 😉 

### Repository Maintainers

- @open-telemetry/go-instrumentation-maintainers

**Comment by MrAlias** [comment]
Note: the default permissions of the project have been set to "read" so public users will not be able to modify the project (which is intentional).

**Comment by arminru** [comment]
Done!
