### ISSUE TITLE
REQUEST: New membership for atsahw43

### ISSUE THREAD

**Issue by atshaw43** [open-telemetry/community#1629]
### GitHub Username

@atshaw43

### Requirements

- [✓] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [✓] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✓] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [✓] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✓] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [✓] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Kielek
- @trivedu

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-java-contrib/pull/813
- https://github.com/open-telemetry/opentelemetry-java-contrib/pull/903
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20313
- Involved in messaging system SIG

**Comment by srprash** [comment]
I support

**Comment by Kielek** [comment]
I support

**Comment by arminru** [comment]
Hi @atshaw43!
Please note that both of your sponsors will need to be approvers or maintainers of at least one repository in the organization.
See https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements for details.

**Comment by trask** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @atshaw43!

**Comment by Kielek** [comment]
@atshaw43, please remember to accept invitation.

**Comment by arminru** [comment]
@Kielek @atshaw43 It expired in the meantime so I just re-sent it. Should be good for another 7 days now.
