### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/community#1636]
### Affected Repository

- http://github.com/open-telemetry/opentelemetry-collector

### Requested changes

Give 'Admin' permissions to `@dmitryax`

Or, if possible, grant @open-telemetry/collector-maintainers permissions to change Branch protection rules permanently

### Purpose

We are migrating the Go version support from 1.19-1.20 to 1.20-1.21. Therefore, we need to update the required CI tests for the protected `main` branch to use the new versions. Otherwise, we cannot merge https://github.com/open-telemetry/opentelemetry-collector/pull/8208
 
### Expected Duration

1 week. We'll comment again on this issue once we are done so the permissions can be reverted.

### Repository Maintainers

- @open-telemetry/collector-maintainers

**Comment by arminru** [comment]
@dmitryax I added you as an Admin.

Please make sure to keep the settings as described in https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#repository-settings, particularly the branch protection rules with the EasyCLA check and required reviews (the order of rules is significant) and let us know when we can revert the permissions.

Thanks!

cc @open-telemetry/collector-maintainers

**Comment by arminru** [comment]
@dmitryax I only saw your other comment in https://github.com/open-telemetry/community/issues/1637#issuecomment-1673861788 now.
I reverted the permissions for core as discussed and will resolve this issue here while keeping the other one open.
