### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/community#1637]
### Affected Repository

- http://github.com/open-telemetry/opentelemetry-collector-contrib

### Requested changes

Give 'Admin' permissions to `@dmitryax`

Or, if possible, grant @open-telemetry/collector-contrib-maintainer permissions to change Branch protection rules permanently

### Purpose

Similar to https://github.com/open-telemetry/community/issues/1636.

We are migrating the Go version support from 1.19-1.20 to 1.20-1.21. Therefore, we need to update the required CI tests for the protected `main` branch to use the new versions.
 
### Expected Duration

1 week. We'll comment again on this issue once we are done so the permissions can be reverted.

### Repository Maintainers

- @open-telemetry/collector-contrib-maintainer

**Comment by trask** [comment]
> if possible, grant https://github.com/orgs/open-telemetry/teams/collector-contrib-maintainer permissions to change Branch protection rules permanently

you can request permanent Admin permission if you want, check out https://github.com/open-telemetry/community/blob/1fe51b7ecd71263e1d6abf7758fd2822ca6c36fa/docs/how-to-configure-new-repository.md?plain=1#L43-L47

**Comment by dmitryax** [comment]
> you can request permanent Admin permission if you want, check out

I'm good with any approach. We can submit requests here every time or maintain `.github/repository-settings.md`. @open-telemetry/collector-contrib-maintainer what would you prefer?

**Comment by trask** [comment]
another option that works well if you are only needing this for updating the required status checks is to have a single "required status check" job, and make it a dependency of your other jobs, e.g. https://github.com/open-telemetry/opentelemetry-java-examples/blob/9a42295cd56ed1706673822d63288fbc5e35064a/.github/workflows/build.yml#L53

**Comment by dmitryax** [comment]
> another option that works well if you are only needing this for updating the required status checks is to have a single "required status check" job, and make it a dependency of your other jobs, e.g. https://github.com/open-telemetry/opentelemetry-java-examples/blob/9a42295cd56ed1706673822d63288fbc5e35064a/.github/workflows/build.yml#L53

I would like to avoid going this route. It's nice to see which required jobs failed explicitly instead of jumping through an additional job.

**Comment by dmitryax** [comment]
@trask, I think we can apply your suggestion just for `unittest` matrix and have one required check for all the go versions to avoid going through this exercise every 6 months. cc @open-telemetry/collector-contrib-maintainer

I submitted https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25151 for this issue and https://github.com/open-telemetry/opentelemetry-collector/pull/8208 for https://github.com/open-telemetry/community/issues/1636

**Comment by dmitryax** [comment]
@trask, the PRs ^ are approved. Can you please help us with switching the required jobs from `unittest (1.19)` and `unittest (1.20)` to `unittest` in:
- http://github.com/open-telemetry/opentelemetry-collector-contrib to close this issue
- http://github.com/open-telemetry/opentelemetry-collector-contrib to close https://github.com/open-telemetry/community/issues/1636

Thank you!

**Comment by trask** [comment]
> @trask, the PRs ^ are approved. Can you please help us with switching the required jobs from `unittest (1.19)` and `unittest (1.20)` to `unittest`

paging someone from @open-telemetry/technical-committee who have the permissions to do this ☎️

**Comment by arminru** [comment]
@dmitryax I changed the settings in https://github.com/open-telemetry/opentelemetry-collector as requested. For -contrib there is no such job name but rather some dozens of jobs based on a matrix. Do you intend to keep it there like that or will https://github.com/open-telemetry/opentelemetry-collector/pull/8218 also be ported to -contrib?

**Comment by arminru** [comment]
Found your PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25151 in the meantime.

Unfortunately the 30-ish recommendations the Github UI gives when filtering for `unittest` did not include the plain `unittest` but all of the individual matrix branch results instead...
I was able to get it to set it to just `unittest` by replacing the branch protection rule via the Github API now and it looks like it worked:

![image](https://github.com/open-telemetry/community/assets/7052238/ac338511-e425-4f36-9aff-09f4e3c3a18e)
