### ISSUE TITLE
Create new semantic-conventions-java repository

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/community#1638]
The `opentelemetry-java` repo currently publishes an artifact containing generated classes with attributes from the semantic conventions. With the split of semantic conventions from `opentelemetry-specification` to `semantic-conventions`, and with the approaching stability of http semantic conventions, we want to split out this code generation to a dedicated repository called `semantic-conventions-java`. Tracking this issue from `opentelemetry-java`'s side [here](https://github.com/open-telemetry/opentelemetry-java/issues/5463).

The current process causes confusion because `opentelemetry-java` publishes new versions monthly, with all artifacts versioned in lockstep. This produces confusing artifact versions, as `io.opentelemetry:opentelemetry-semconv` has versions which are different from the version of semantic conventions used to generate them.

This new repo would publish new versions in lockstep with `semantic-conventions`.

cc @open-telemetry/java-maintainers @open-telemetry/specs-semconv-approvers 

I know I already have the ✅ from the java maintainers. If the semantic convention conventions maintainers agree, I'll go ahead and get started on the new repo.

**Comment by Oberon00** [comment]
This only works in an ideal world where your Java artifacts make breaking changes and bug-fixes in lockstep with the specification. I am not sure if this is a good idea.

**Comment by jack-berg** [comment]
> This only works in an ideal world where your Java artifacts make breaking changes and bug-fixes in lockstep with the specification. I am not sure if this is a good idea.

I think what you're saying is that we may want to change the code generation logic independently of a bump in the semantic conventions repo. We could accomplish this by having a versioning strategy which is essentially two versions:
```
io.opentelemetry:opentelemetry-semconv:{CODE_GEN_VERSION}_{SEMCONV_VERSION}
// e.g.
io.opentelemetry:opentelemetry-semconv:1.0.0_1.21.0
```
Or something to that effect. But we can't do any of this if the artifact has to be published in lockstep with `opentelemetry-java` as it is today.

**Comment by jack-berg** [comment]
I see 👍 from both java maintainers and semantic convention maintainers so I'm going to proceed with setting up the repo and close this issue.

**Comment by jack-berg** [comment]
See new repository at [semantic-conventions-java](https://github.com/open-telemetry/semantic-conventions-java).
