### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-android

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/community#1639]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-android

### Requested changes

Install Renovate app
 
### Purpose

Similar to #1620 we would like to be consistent with the java repos and use renovatebot to help detect and PR dependency updates. 
 
### Expected Duration

permanently 

### Repository Maintainers

- @open-telemetry/android-maintainers 

Thanks! 😎

**Comment by arminru** [comment]
Enabled Renovate for open-telemetry/opentelemetry-android

**Comment by trask** [comment]
@open-telemetry/technical-committee can you also set up branch protection for `renovate/**/**`?

https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-renovate

**Comment by jack-berg** [comment]
Added the branch protection rules 👍

**Comment by breedx-splk** [comment]
Thanks thanks, wasn't aware of that bit.
