### ISSUE TITLE
Need a public repository to store Docker images

### ISSUE THREAD

**Issue by flands** [open-telemetry/community#164]
Per https://github.com/open-telemetry/opentelemetry-service/issues/281 some repos will need to ability to publish images. Do we have a dockerhub or some other location that can be used? It appears https://hub.docker.com/u/opentelemetry exists, but not sure who owns it.

**Comment by bhs** [comment]
(looking through some open issues – sorry for the delay)

@flands I did some light digging and have no idea who owns that docker hub account :sob:

Seems like the first step here...

**Comment by pavolloffay** [comment]
@jpkrohling reserved opentelemetry organization on quai.io. https://quay.io/organization/opentelemetry.

Many OSS projects publish images there. It's a free service namaged by Red Hat/CoreOS. In Jaeger we had problems with dockerhub availability recently so we publish also to quay.io.

**Comment by Jamim** [comment]
Hello @flands,
Please consider changing the issue title to
> Need a public repository to store **Docker** images

Currently, when you overview [the issue list](https://github.com/open-telemetry/community/issues) and see the title of this issue, it's not obvious that this issue is about **Docker** images, not some jpegs or pngs.

Thanks!

**Comment by tigrannajaryan** [comment]
@open-telemetry/admins since we are unable to locate the owner of `opentelemetry` organization in Dockerhub I am going to create `open-telemetry` (with a dash) Dockerhub organization and make that the canonical place for OpenTelemetry related images (we need this particularly for Collector images). `open-telemetry` org name with a dash also matches well the Github org name.

Let me know if there are any objections, otherwise I will go ahead and create it and will add all OpenTelemetry admins as admins in Dockerhb as well.

**Comment by yurishkuro** [comment]
I'd say go ahead, we can always switch to the one without dash if we find an owner.

**Comment by tigrannajaryan** [comment]
Looks like dashes are not valid characters for org names in Dockerhub :-(

It appears we can claim `opentelemetry`. There is a procedure for trademarked names: https://success.docker.com/article/how-can-i-claim-ownership-of-an-existing-docker-id

I submitted a support ticket, let's see what Docker says.

**Comment by jpkrohling** [comment]
I know this is about DockerHub, but we do have a repository at Quay, where we are pushing the operator images:

https://quay.io/organization/opentelemetry

For current open-telemetry GitHub admins: let me know your Quay account name and I'll add you as an owner there.

**Comment by SergeyKanzhelev** [comment]
sergeykanzhelev

**Comment by jpkrohling** [comment]
Invited

**Comment by austinlparker** [comment]
@tigrannajaryan any update on getting the opentelemetry docker org?

**Comment by tigrannajaryan** [comment]
Morgan and I initiated the process but it got stuck at Docker. Let me try to contact them one more time.

**Comment by andrewhsu** [comment]
@tigrannajaryan looks like https://hub.docker.com/u/otel is available

**Comment by tigrannajaryan** [comment]
@open-telemetry/admins can one of you grab https://hub.docker.com/u/otel while it is available?

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan please take it. We have two patterns of ownership. Where possible we are asking to create a private mail list controlled by CNCF and including maintainers of a SIG. And create a log in using this DL as an e-mail. In other cases we have individuals owning things and sharing ownership with other maintainers.

If you want a DL registered - happy to assist.

**Comment by jpkrohling** [comment]
Isn't "open-telemetry" already registered to this group? Or are you taking `otel` only so that others can't?

**Comment by tigrannajaryan** [comment]
`open-telemetry` is not a valid organization name on Dockerhub. Dashes are not allowed.

**Comment by tigrannajaryan** [comment]
I registered https://hub.docker.com/orgs/otel

I also added @bogdandrutu as an owner. I can add other OpenTelemetry admins as owners as needed (let me know if you want to be added).

If we don't get `opentelemetry` in the near future then we will go with `otel`.

**Comment by mtwo** [comment]
Thanks Tigran!

**Comment by tigrannajaryan** [comment]
We are now publishing to `otel`. Please close this issue.

**Comment by yurishkuro** [comment]
https://hub.docker.com/u/otel

**Comment by bobstrecansky** [comment]
@tigrannajaryan - I'd love to be added as an admin for this so that we have the ability to push a PHP docker image.

**Comment by yurishkuro** [comment]
NB: publishing should be done via bot accounts, not personal accounts.

**Comment by tigrannajaryan** [comment]
We use https://hub.docker.com/u/opentelemetrybot bot account to publish images. If you have a CI where I can enter bot credentials such that it remains secret I can do it for you.

**Comment by SergeyKanzhelev** [comment]
> We use https://hub.docker.com/u/opentelemetrybot bot account to publish images. If you have a CI where I can enter bot credentials such that it remains secret I can do it for you.

Would you please add information about the bot and it's ownership to the assets file: https://github.com/open-telemetry/community/blob/main/assets.md It is for the future reference

**Comment by trask** [comment]
I wanted to share here, just in case publishing docker images to GitHub packages is enough for some use cases, we've been doing this in the opentelemetry-java-instrumentation repo, and found recently that we no longer need org-wide packages (which are harder to manage #556, #579).

Here's an old "org-wide" package: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pkgs/container/java-test-containers

Here's a new "repo-scoped" package: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pkgs/container/opentelemetry-java-instrumentation%2Fpetclinic-rest-base

And here's how we push that repo-scoped package:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/59439cb46488c9fe30800373a2ebb615bfbfa734/.github/workflows/build-petclinic-overhead-base.yml#L19-L30
