### ISSUE TITLE
REQUEST: New membership for shivanshu1333

### ISSUE THREAD

**Issue by shivanshu1333** [open-telemetry/community#1641]
### GitHub Username

@shivanshu1333

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dmitryax 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23668
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25164
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25162
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25183
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25171
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25136
https://github.com/open-telemetry/opentelemetry-collector/pull/8223
https://github.com/open-telemetry/opentelemetry-collector/pull/8225
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25184
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/385
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25185

- SIG projects I am involved with
  - [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector)
  - [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib)
  - [opentelemetry-collector-releases](https://github.com/open-telemetry/opentelemetry-collector-releases/)
  (at the moment these three, hoping to get involved at other components as well)

**Comment by TylerHelmuth** [comment]
I support

**Comment by dmitryax** [comment]
I support

**Comment by shivanshu1333** [comment]
Thanks Armin!
Thanks to all :)
