### ISSUE TITLE
Add Zapier to the CNCF slack

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/community#1644]
The OTel security sig is looking to improve the automation around community security incident response. 

1 piece of that is automatically notifying the technical committee when a new incident has been opened and needs to be triaged. 

We've developed a webhook based automation using Zapier to solve this problem. But Zapier needs org owner permission to be installed to Slack.

**Comment by trask** [comment]
I've opened CNCF ticket to request installing Zapier App on CNCF Slack: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1907

**Comment by trask** [comment]
Zapier app has been added to CNCF Slack
