### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-android

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/community#1645]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-android

### Requested changes

Give 'Admin' permissions to maintainers `@breedx-splk` and `@likethesalad` (or simply `@opentelemetry/android-maintainers`). We agree to maintain `.github/repository-settings.md` as per `how-to-configure-new-repository.md`.
 
### Purpose

Our main need is to be able to configure secrets into GHA for the purposes of signing and publishing release artifacts. Some of these secrets, such as sonatype credentials, are user-specific and not sharable with TC members. Furthermore, we will be striving toward repo configuration consistency with the other java repos and can help reduce some of this burden from TC members.
 
### Expected Duration

perpetuity 

### Repository Maintainers

- @open-telemetry/android-maintainers

**Comment by breedx-splk** [comment]
Litte help? @jack-berg ?

**Comment by jack-berg** [comment]
I've updated the `@open-telemetry/android-maintainers` team to have "Admin" role on the `opentelemetry-android` repo. Please add the `.github/repository-settings.md` document and trace changes from the defaults!
