### ISSUE TITLE
REQUEST: New membership for moh-osman3

### ISSUE THREAD

**Issue by moh-osman3** [open-telemetry/community#1647]
### GitHub Username

@moh-osman3

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @lquerel

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
-- otel-arrow-adapter (new repository being donated - PRs are from original repo)
https://github.com/f5/otel-arrow-adapter/pull/207
https://github.com/f5/otel-arrow-adapter/pull/200
https://github.com/f5/otel-arrow-adapter/pull/191
https://github.com/f5/otel-arrow-adapter/pull/186
https://github.com/f5/otel-arrow-adapter/pull/185
https://github.com/f5/otel-arrow-adapter/pull/174
-- opentelemetry-operator
https://github.com/open-telemetry/opentelemetry-operator/pull/1651
https://github.com/open-telemetry/opentelemetry-operator/pull/1553
https://github.com/open-telemetry/opentelemetry-operator/pull/1462
https://github.com/open-telemetry/opentelemetry-operator/pull/1302
https://github.com/open-telemetry/opentelemetry-operator/pull/1237
https://github.com/open-telemetry/opentelemetry-operator/pull/1232
https://github.com/open-telemetry/opentelemetry-operator/pull/1214
https://github.com/open-telemetry/opentelemetry-operator/pull/1127
https://github.com/open-telemetry/opentelemetry-operator/pull/1066
-- opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector/pull/6886
https://github.com/open-telemetry/opentelemetry-collector/pull/6607
https://github.com/open-telemetry/opentelemetry-collector/pull/6460

- Issues responded to
https://github.com/open-telemetry/opentelemetry-operator/issues/985
https://github.com/open-telemetry/opentelemetry-operator/issues/998
https://github.com/open-telemetry/opentelemetry-operator/issues/1008
https://github.com/open-telemetry/opentelemetry-helm-charts/issues/296
https://github.com/open-telemetry/opentelemetry-operator/issues/1028
https://github.com/open-telemetry/opentelemetry-operator/issues/1065
https://github.com/open-telemetry/opentelemetry-operator/issues/1115
https://github.com/open-telemetry/opentelemetry-operator/issues/1213
https://github.com/open-telemetry/opentelemetry-operator/issues/1231
https://github.com/open-telemetry/opentelemetry-operator/issues/1516
https://github.com/open-telemetry/opentelemetry-operator/issues/1560
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20840
https://github.com/open-telemetry/opentelemetry-operator/issues/1558
https://github.com/open-telemetry/opentelemetry-operator/issues/1203
https://github.com/open-telemetry/opentelemetry-operator/issues/1439
https://github.com/open-telemetry/opentelemetry-operator/issues/1574

- SIG projects I am involved with

**Comment by lquerel** [comment]
I support

**Comment by codeboten** [comment]
I support

**Comment by jmacd** [comment]
Thanks @moh-osman3 -- by the way your list of PRs above is impressive for someone not yet added to the community here!
