### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1649]
(submitting on @jack-berg's behalf for transparency)

### Affected Repository

https://github.com/open-telemetry/opentelemetry-java

### Requested changes

Install Renovate app
 
### Purpose

Similar to #1620 we would like to be consistent with the java repos and use renovatebot to help detect and PR dependency updates. 
 
### Expected Duration

Permanently 

### Repository Maintainers

- @open-telemetry/java-maintainers

**Comment by arminru** [comment]
Enabled Renovate on open-telemetry/opentelemetry-java.
