### ISSUE TITLE
REQUEST: New membership for @a-feld

### ISSUE THREAD

**Issue by a-feld** [open-telemetry/community#165]
### GitHub Username

@a-feld

### Organization you are requesting membership in

@open-telemetry/python-approvers

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang
- @mwear 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-python/pull/84
https://github.com/open-telemetry/opentelemetry-python/pull/92
https://github.com/open-telemetry/opentelemetry-python/pull/94
https://github.com/open-telemetry/opentelemetry-python/pull/112

- Issues responded to
https://github.com/open-telemetry/opentelemetry-python/issues/71

- SIG projects I am involved with
Python SIG

**Comment by reyang** [comment]
@a-feld has been actively contributing to OpenTelemetry Python and the overall OpenTelemetry community. It is my pleasure to sponsor him to become `@open-telemetry/python-approvers`.

**Comment by bogdandrutu** [comment]
@mwear are you supporting this? Please +1

**Comment by mwear** [comment]
Indeed @a-feld's work on OpenTelemetry Python has been well received!

**Comment by bogdandrutu** [comment]
Thanks for all your contributions @a-feld. Sent you an invite to become a member https://github.com/open-telemetry/community/blob/master/community-membership.md#community-membership. To become an approver you need to match the requirements from https://github.com/open-telemetry/community/blob/master/community-membership.md#requirements-1

If the requirements are met please open a PR that updates https://github.com/open-telemetry/community/blob/master/community-members.md#python.
