### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-sandbox-web-js

### ISSUE THREAD

**Issue by MSNev** [open-telemetry/community#1650]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-sandbox-web-js

### Requested changes

Give 'Admin' permissions to `@MSNev"

### Purpose

Need of override blocked EasyCLA check due to the number of commits in the merge PR as per this Slack thread https://cloud-native.slack.com/archives/CK8QVEXQB/p1692636005379499?thread_ts=1692635121.030049&cid=CK8QVEXQB

### Expected Duration

One off (hours)

### Repository Maintainers

@open-telemetry/sandbox-web-js-maintainers

**Comment by dyladan** [comment]
I don't have permission to do this myself but can confirm admin permission was the cncf's workaround suggestion for PRs with too many commits causing easycla to fail

**Comment by trask** [comment]
just for reference: https://cloud-native.slack.com/archives/CK8QVEXQB/p1692640228009879?thread_ts=1692635121.030049&cid=CK8QVEXQB

**Comment by trask** [comment]
ping @open-telemetry/technical-committee

**Comment by yurishkuro** [comment]
done
<img width="1207" alt="image" src="https://github.com/open-telemetry/community/assets/3523016/68e6341f-e8d8-464e-9764-ebec3c77faa3">
