### ISSUE TITLE
Add filter to recordings google sheet

### ISSUE THREAD

**Issue by Rperry2174** [open-telemetry/community#1653]
In https://github.com/open-telemetry/community/pull/1431/ we created a google sheet that has he recordings from sig meetings. Currently it is view only so it's easy enough to create a temporary filter, but just for usability and discoverability of the meetings that people are most interested in would be nice if this spreadsheet had filters enabled

cc @trask

**Comment by trask** [comment]
hey @Rperry2174, I tried, but not succeeding 😅

I created a Filter View called "By Name", but it seems like that just stores one specific set of values that I choose, as opposed to letting other users change the value they want to filter on.

It seems like with that limitation I'd need to create a separate filter view for each SIG(?)

do you know if I'm missing something? thx!
