### ISSUE TITLE
OTel components observability WG question

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/community#1657]
Opening this issue in order to get attention from people interested in auto-observability semantic conventions, e.g. [processed and dropped Span metrics](https://github.com/open-telemetry/semantic-conventions/pull/184). This would include observability in APIs, SDKs and the Collector (and related components).

Observe that currently a few components (Java SDK, Collector) already report a few metrics/traces around its own components, but they are not defined in our semconv docs nor they have been reviewed, documented, etc.

**Comment by tigrannajaryan** [comment]
@carlosalberto by "auto observability" do you mean the observability of Otel components? This is unrelated to auto-instrumentation, right?

**Comment by dyladan** [comment]
I think the longer form would be "semantic conventions to describe automatic observability systems" which may apply to otel components but may also apply to other o11y systems that want to describe themselves.

**Comment by carlosalberto** [comment]
Correct, unrelated to auto-instrumentation. Will update the title.

**Comment by trask** [comment]
discussion going on in otep land: https://github.com/open-telemetry/oteps/pull/259
