### ISSUE TITLE
REQUEST: New membership for <your-GH-handle>

### ISSUE THREAD

**Issue by charles0830** [open-telemetry/community#1658]
### GitHub Username

e.g. (at)example_user

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by trask** [comment]
hi @charles0830! can you `@` your sponsors above, so they will get notified? thx

**Comment by charles0830** [comment]
Sorry, but I am not sure what do you mean.
Could you describe step-by-step with example?
Thx

**Comment by trask** [comment]
check out https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements

**Comment by charles0830** [comment]
Ah, I understand
I can
