### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#1659]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector-contrib

### Requested changes

Add a new PAT from the opentelemetry-bot with specific permissions to query the Github API for organization members.
 
### Purpose

We are rolling out a tool that needs to get access to organization members list to check for codeowners.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24638
 
### Expected Duration

Permanently.

### Repository Maintainers

- @open-telemetry/collector-contrib-maintainer

**Comment by atoulme** [comment]
Can I get any help on this? We are missing CI checks because of this, and it created regressions in our repository, specifically https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27267

**Comment by tigrannajaryan** [comment]
>Add a new PAT from the opentelemetry-bot with specific permissions

@atoulme what are the permissions you need?

**Comment by atoulme** [comment]
It needs "read:org, read:user"

**Comment by jpkrohling** [comment]
I was able to generate the token, but I can't seem to be able to create the secret in that repo 🤦🏽 I guess someone from the TC will have to do both steps. @tigrannajaryan, would you do the honors?

**Comment by trask** [comment]
> I was able to generate the token, but I can't seem to be able to create the secret in that repo 🤦🏽 I guess someone from the TC will have to do both steps. @tigrannajaryan, would you do the honors?

ya, this is the motivation behind #1652

**Comment by tigrannajaryan** [comment]
> I was able to generate the token, but I can't seem to be able to create the secret in that repo 🤦🏽 I guess someone from the TC will have to do both steps. @tigrannajaryan, would you do the honors?

@jpkrohling can you put the secret in our 1password, give me access to it and tell me what setting do you want in the repo to be updated?

**Comment by jpkrohling** [comment]
Sorry for taking so long, I lost track of this one. I just created an entry in our 1password, within the OpenTelemetry Collector vault. I also added you to that vault, as I wasn't sure you'd have access to it. Given you are part of the TC, I believe you should.

@atoulme, other than the secret, do you need anything else updated in this repo?

**Comment by tigrannajaryan** [comment]
@atoulme please tell what exactly you need to be done on the repo, I am not sure I understand.

**Comment by atoulme** [comment]
I need a secret containing a PAT with the permissions "read:org, read:user" that we can reference as a secret in a github action runners workflow so we can query members of the organization to check codeowners.

**Comment by tigrannajaryan** [comment]
@atoulme I added OTEL_BOT_PASSWORD and OTEL_BOT_USERNAME to https://github.com/open-telemetry/opentelemetry-collector-contrib/settings/secrets/actions

**Comment by atoulme** [comment]
Thanks working with that.

**Comment by bogdandrutu** [comment]
Closing since @atoulme confirm it works.

**Comment by atoulme** [comment]
Sorry, it didn't work. I just never had time to get back into this.

**Comment by trask** [comment]
> Sorry, it didn't work. I just never had time to get back into this.

reopening

@atoulme can you provide any more details / logs / errors that might help?

**Comment by atoulme** [comment]
The gh client doesn't work with username and password of the user. It would be best to remove those secrets from the repository, in case someone finds a way to abuse our checks and use those to login as opentelemetry-bot.

Here is what I would need. Logged in as the opentelemetry-bot user, you can generate a token using the following steps:

* Go to https://github.com/settings/apps (Developer Settings)
* Click on Personal Access Tokens and select Tokens (classic). It should get you to https://github.com/settings/tokens
* Click on "Generate new token" up to the right, and select "Generate new token (classic)"
* In the dialog, select the permission "read:org":
<img width="607" alt="Screenshot 2024-01-02 at 15 58 49" src="https://github.com/open-telemetry/community/assets/16758/609084f7-e9b9-4bc9-b4d1-f0329cf717a2">
** Give a name to the token of your choosing
** Set up a rotation time for the token
* Click "Generate token"
* Copy the token value (should start with `ghp_`) into a github secret on the repository opentelemetry-collector-contrib.

**Comment by atoulme** [comment]
hello folks, any upate on this issue?

**Comment by arminru** [comment]
Hi @atoulme! Are you saying that the new PAT should replace the existing secrets `OTEL_BOT_USERNAME` and `OTEL_BOT_PASSWORD` in https://github.com/open-telemetry/opentelemetry-collector-contrib/settings/secrets/actions, or should it be added in addition to it?

**Comment by arminru** [comment]
@tigrannajaryan I see a PAT called `opentelemetry-collector-contrib-1659` in the @opentelemetrybot but it was never used. Is that the PAT you added for `OTEL_BOT_PASSWORD` already?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan I see a PAT called `opentelemetry-collector-contrib-1659` in the @opentelemetrybot account but it was never used. Is that the PAT you added for `OTEL_BOT_PASSWORD` already?

@arminru I think yes, that's it, but I can't remember for certain.

**Comment by atoulme** [comment]
OK, I will try this out. I appreciate the help!

**Comment by atoulme** [comment]
It worked! We're good now. Thanks for all your help, closing.
