### ISSUE TITLE
TC Review Request: Go Metric SDK

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1663]
The Go SIG is looking to make a stable release of the OpenTelemetry metric SDK in Go. We are looking for a TC member familiar with the metric SDK specification to review our offering and help ensure our compliance with the specification.

### Prior work

We have conducted our own internal review of the specification [here](https://github.com/orgs/open-telemetry/projects/34). That review has identified no outstanding compliance issues, but does include minor documentation work still to be done and the following specification issues that remain:

- [Stabilize the `MetricProducer`](https://github.com/open-telemetry/opentelemetry-specification/issues/3599) given this will be included in the stable SDK.
- [Clarify the view `attribute_keys` stream configuration](https://github.com/open-telemetry/opentelemetry-specification/pull/3680).

Other than this documented work in the linked project, the SDK should be ready for stable release and is currently ready for TC review.

### Inventory

We would like to evaluate the [v1.17.0/v0.40.0/v0.5.0 Release](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.17.0), links should be related to this tag.

- Metric SDK package: https://github.com/open-telemetry/opentelemetry-go/tree/v1.17.0/sdk/metric
  - [`MeterProvider`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/provider.go#L32-L40)
    - [`View`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/view.go)
    - [`Aggregation`
](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/aggregation.go)
  - [`Meter`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/meter.go)
  - [`MetricReader`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/reader.go#L40-L92)
    - [`ManualReader`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/manual_reader.go)
    - [`PeriodicReader`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/periodic_reader.go)
    - [`MetricExporter`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/exporter.go)
  - [`MetricProducer`](https://github.com/open-telemetry/opentelemetry-go/blob/3c476ce1816ae6f38758e90cc36d8b77ebcc223b/sdk/metric/reader.go#L102-L108)

**Comment by MrAlias** [comment]
cc @open-telemetry/technical-committee

**Comment by tigrannajaryan** [comment]
@MrAlias I added this to the next TC meeting agenda. We will post back here once the TC member is selected.

**Comment by jmacd** [comment]
I volunteered to do this. I am familiar with the Go metrics SDK and have followed the recent releases. I don't expect any blockers, but will do the review as requested.

**Comment by jmacd** [comment]
@MrAlias I feel we can close this, let me know if you're satisfied. Thanks!
