### ISSUE TITLE
REQUEST: New membership for shaun-cox

### ISSUE THREAD

**Issue by shaun-cox** [open-telemetry/community#1674]
### GitHub Username

@shaun-cox

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security.
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jtescher 
- @cijothomas 
- @TommyCpp 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [PRs reviewed / authored](https://github.com/open-telemetry/opentelemetry-rust/pulls?q=is%3Apr+author%3Ashaun-cox)
- [Issues responded to](https://github.com/open-telemetry/opentelemetry-rust/issues?q=is%3Aissue+commenter%3Ashaun-cox)
- SIG projects I am involved with
  - [OpenTelemetry Rust SIG](https://docs.google.com/document/d/1tGKuCsSnyT2McDncVJrMgg74_z8V06riWZa0Sr79I_4/edit#heading=h.fssat5bvwd5m)

**Comment by cijothomas** [comment]
I support

**Comment by TommyCpp** [comment]
I support 👍

**Comment by jtescher** [comment]
welcome @shaun-cox!

**Comment by arminru** [comment]
Invite sent. Welcome, @shaun-cox!
