### ISSUE TITLE
REQUEST: New membership for fchikwekwe

### ISSUE THREAD

**Issue by fchikwekwe** [open-telemetry/community#1676]
### GitHub Username

@fchikwekwe

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @TylerHelmuth 
- @evan-bradley

### List of contributions to the OpenTelemetry project
PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25069
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25147
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24453
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24243
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23659
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26371

Issues responded to
SIG projects I am involved with

**Comment by TylerHelmuth** [comment]
I support

**Comment by evan-bradley** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @fchikwekwe!
