### ISSUE TITLE
REQUEST:  jmacd for Go Maintainer

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/community#168]
### GitHub Username

jmacd

### Organization you are requesting membership in

https://github.com/open-telemetry/opentelemetry-go

### Requirements

- [ ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ ] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tedsuo 
- @rghetia 

### List of contributions to the OpenTelemetry project

- Many Golang proposals and reviews
- Many Spec proposals and reviews

**Comment by rghetia** [comment]
@tedsuo do you have admin access to this repo? I don't.

**Comment by bogdandrutu** [comment]
Sponsors are maintainers of the repo.

@tedsuo please include the list of contributions, also this should be a PR not an issue.

**Comment by tedsuo** [comment]
@bogdandrutu sure, can do. The protocol says fill in the issue template, so that's what I did. :)

**Comment by bogdandrutu** [comment]
This issue template is to become a member of the community. See the rules for maintainer here:
https://github.com/open-telemetry/community/blob/master/community-membership.md#requirements-2

**Comment by bogdandrutu** [comment]
I am going to close this issue because @jmacd is already a member of the community.

**Comment by bogdandrutu** [comment]
If you want to make him maintainer of the go repo please open a PR that changes the status here:
https://github.com/open-telemetry/community/blob/master/community-members.md#golang

And add justification.
