### ISSUE TITLE
REQUEST: Credential Store Access for austinlparker

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1680]
We need a vault for https://github.com/open-telemetry/opentelemetry-demo.

This store needs the OpenTelemetry Docker Hub username and password in it.

cc @open-telemetry/demo-maintainers

**Comment by codeboten** [comment]
Happy to add a vault and invite you to it

**Comment by codeboten** [comment]
@austinlparker did you mean the collector repo or the demo repo?

**Comment by codeboten** [comment]
Invite to vault sent. I don't have access to the docker credentials, maybe @tigrannajaryan can comment here
