### ISSUE TITLE
Proposal for establishing the SIG OpenTelemetry on Mainframe 

### ISSUE THREAD

**Issue by rrschulze** [open-telemetry/community#1686]
# Description

As we see a growing interest from customers to use OpenTelemetry on the mainframe, we'd like to propose a working group to define and stabilize semantic conventions supporting the observability of the mainframe and to introduce instrumentation for programming languages present on the mainframe.

This proposal has been created as result of a [series of meetings](https://docs.google.com/document/d/14p-bpofozTL4n3jy6HZH_TKjoOXvog18G1HBRqq6liE/edit?pli=1#heading=h.pss2tdsd549w) for the topic “OpenTelemetry on Mainframe” with contributions from participants of multiple vendors and is based on [this document](https://docs.google.com/document/d/1SM5BmM4st8n4giWuqe1shqN98d37VG9C_-di1hG6sbg/edit#heading=h.q3h9nwmyzjva).

# Goals

-   Mainframe users can capture infrastructure metrics and logs with OpenTelemetry and can export these to the tools of their choice.
-   Mainframe users can capture application spans (traces), metrics, logs, and (eventually) profiles from their applications with OpenTelemetry and can export these to the tools of their choice.
    -   Context propagation works across different parts (subsystems) of each mainframe application, akin to how requests are traced across distributed services running on hosts and containers.
-   All captured telemetry has appropriate resource and interaction metadata attached to it, and this metadata conforms to the OpenTelemetry semantic conventions.
-   Capturing infrastructure and application telemetry from a mainframe incurs a minimal performance impact and allows for different deployment scenarios of the OpenTelemetry Collector to minimize both mainframe CPU costs and mainframe network egress costs.

# Staffing / Help wanted

This group will welcome contributors from various areas:
-   We look for participation from mainframe experts of all kinds: observability and monitoring experts, performance experts, virtualization experts, architects, and users of observability solutions for the mainframe and those who want to extend, simplify, and improve their current observability solution to the mainframe.
-   We welcome developers working with Assembler, COBOL, PL/1, and REXX, and engineers willing to contribute with the instrumentation for mainframe-specific programming languages.
-   We invite everybody to join who is passionate about the mainframe.
-   Two project leads who are willing to drive the project and address any issues which are not handled by other project members.
-   At least two sponsoring TC (Technical Committee) members. TC sponsors are dedicated to attending meetings, reviewing proposals, and in general being aware of the state of the project and its technical details. TC sponsors guide the project through the spec process, keep the tracking issue up to date, and help to ensure that relevant community members provide input at the appropriate times.
-   Contributors from Semantic Conventions WG: \<to be added\>
-   Maintainers or approvers: \<to be added\>

# Deliverables

-   Definition of semantic conventions that capture the concepts of the mainframe including hardware, virtualization, z/OS and subsystems, Linux on IBM Z by aligning to and extending the existing semantic conventions across resources, metrics, logs, and traces. The enhancements of the semantic conventions are assumed to be generically applicable to the mainframe and apply to any OS on the mainframe incl. TPF and z/VSE.
-   Alignment of semantic conventions for virtualization between mainframe and other virtualizations solutions, as far as feasible and reasonable
-   Description of mapping between names and mainframe terms (for conventions not specifically defined as mainframe extensions)
-   Definition of a curated, most meaningful set of metrics (out of the thousands of available metrics) to be fully supported by the semantic conventions.
-   Description and definition of semantic conventions for metrics determined as result from aggregation across system topology to simplify handling in observability backends
-   Definition of approach for supporting instrumentation of mainframe-specific programming languages
-   Definition of approach for supporting instrumentation of mainframe-specific logs
-   Definition of approach for supporting trace context propagation
-   Code instrumentation (SDKs) for mainframe-specific programming languages and runtimes

# Logistics

Start of workgroup at the beginning of October 2023.

## Track: Semantic Conventions
-   Stage 1: Semantic conventions for basic mainframe concepts - 4Q2023/1Q2024
-   Stage 2: Semantic conventions for curated list of metrics - 2Q2024

## Track: Code Instrumentation
-   Stage 1: Definition of approach for supporting instrumentation of mainframe-specific programming languages - 4Q2023.
-   Stage 2: SDK for COBOL - 1H2024
-   Stage 3: others

## Track: Collector Enhancements
-   Stage 1: Make the Collector compatible (runnable) within mainframe environments. Should be able to run from Linux on IBM Z, the Container Extension of z/OS (zCX) and the z/OS Unix System Services (USS). (Note: s390x support for Linux on IBM Z and zCX is already addressed by this [PR](https://github.com/open-telemetry/opentelemetry-collector-releases/pull/384)).
-   Stage 2: Make the Collector capture resource metrics from mainframes for z/OS and Linux on IBM Z, considering both agent and gateway deployments of the Collector.
-   Stage 3: Make the Collector capture logs from mainframes for z/OS and Linux on IBM Z, considering both agent and gateway deployments of the Collector.

## Project Leads
[\@rrschulze](https://github.com/rrschulze) agrees to volunteer, at least one more volunteer is required.
[Aaron Young](mailto:aaron.young@broadcom.com) from Broadcom is willing based on specific tasks and time requirements.

## Proposed Time 
-   For now, proposing: Tuesdays or Wednesdays at 10 a.m. PDT.
-   Please vote or please propose alternative times!
    -   Aaron Young - Either will work for me. Tuesday is slightly preferable.

## Slack Channel
[https://cloud-native.slack.com/archives/C05PXDFTCPJ](https://cloud-native.slack.com/archives/C05PXDFTCPJ)

# Examples: Enhancements of Semantic Conventions

## Metrics examples

[Metrics Semantic Conventions](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/)

| **Metrics**   | **Enhancements**  | **OS**           |
|------------- |-----------------|--------------|
| [system.cpu. - Processor metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/system-metrics/)    | Multiple types of processor (e.g., CP, IFL,..) <br /> Support of partitioning and virtualization (LPAR, VM)                                                                                                                               | z/OS, Linux |
| [system.memory. - Memory metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/system-metrics/)  | Several types of storage = memory, support of detailed metrics                                                                                                             | z/OS  |
| [process. - Process metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/process-metrics/)                                                              | Similar to z/OS address space but different <br /> Support of Controll Block metrics  | z/OS and z/OS USS |
| [hw. - Common hardware metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/hardware-metrics/) | Detailed level mapping required (e.g., add type=crypto) | z/OS, Linux       |
| [hw.cpu. - Physical processor metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/hardware-metrics/)  | Multiple types of processors (e.g., CP, IFL, ...) <br /> Support of physical processor utilization| z/OS, Linux  |
| [hw.host. - Physical host metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/hardware-metrics/) | For instance, LPAR power metrics  | z/OS and Linux    |
|      | Support of I/O Channels, FC, DASD, Crypto | z/OS, Linux       |
|      | Sysplex & CF, Workload Management    | z/OS              |
|      | Subsystem support | z/OS              |
| [Hostmetrics receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/documentation.md) <br /> process.command <br /> process.command_line  <br /> process.executable.name  <br /> process.executable.path | Because of concept differences, sometimes cannot be fully conformed. If we match process as z/OS address space, it's hard to follow exactly since the terms are different. | z/OS  |

## Resource examples

[Resource Semantic Conventions](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/)

| **Metrics**   | **Enhancements**  | **OS**           |
|------------- |-----------------|--------------|
|  [service. - Service metrics](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/)  | How to describe where the data is originally created?         |      z/OS, Linux |
| | How to describe resource relationships and relationships between infrastructure components (host to LPARs to VMs)?   | z/OS, Linux |

## Log Attribute examples

[Log Attribute Semantic Conventions](https://opentelemetry.io/docs/specs/otel/logs/semantic_conventions/)

| **Metrics**   | **Enhancements**  | **OS**           |
|------------- |-----------------|--------------|
| [event. - Event attributes](https://opentelemetry.io/docs/specs/otel/logs/semantic_conventions/events/)  |  Many other attributes other than the suggested one, e.g., for correlation to other signal types  | z/OS |

### z/OS syslog Write-to-Operator (WTO) example
![zos_logs3](https://github.com/open-telemetry/community/assets/140042958/02e74fc0-b8fe-4e23-9aaf-67aab28d4a18)

**Comment by tigrannajaryan** [comment]
Please take a look at the new project/SIG proposal process here: https://github.com/open-telemetry/community/blob/main/project-management.md

You will need to submit a PR against this repo.

**Comment by rrschulze** [comment]
Created #1687 .
