### ISSUE TITLE
REQUEST: New membership for trentm

### ISSUE THREAD

**Issue by trentm** [open-telemetry/community#1689]
### GitHub Username

@trentm

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pichlermarc 
- @martinkuba 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - https://github.com/open-telemetry/opentelemetry-js/pull/3727
    - https://github.com/open-telemetry/opentelemetry-js/pull/3743 
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1694
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1695
    - https://github.com/open-telemetry/opentelemetry-js/pull/2917
- Issues responded to
    - https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1692
    - https://github.com/open-telemetry/opentelemetry-js/issues/3976
    - https://github.com/open-telemetry/opentelemetry-js/issues/3701
    - https://github.com/open-telemetry/opentelemetry-js/issues/3655
    - https://github.com/open-telemetry/opentelemetry-js/issues/3954
- SIG projects I am involved with
    - https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1559 and adding Logs Bridge support for other Node.js logging libraries. I'm not sure if this counts as a SIG "project".

**Comment by martinkuba** [comment]
I support!

**Comment by pichlermarc** [comment]
I support! :slightly_smiling_face:

**Comment by blumamir** [comment]
I support as well 🥇

**Comment by arminru** [comment]
Invite sent. Welcome, @trentm!
