### ISSUE TITLE
Enable automatic assignment of repo maintainers to a security incident in their repo using Zapier

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/community#1691]
At the moment only organization admins have the ability to see a security incident when it is opened in any repo in that organization. This means TC members have to add the relevant repo maintainers to every issue as it comes in and manually check to see if no new incidents have been created. SIG-security would like to automate this process using Zapier, the GitHub API, and Webhooks. 

### Ask:

I'd like to request an organization Webhook subscribed to repository advisories, access to the community Zapier account, and a personal access token with the ability to read/write on repository security advisories. See below for details and screenshots. 

**Note the personal access token will need to be renewed after a set period of time. Ideally its expiration is set as long as possible unless deemed a risk** 

### Overall Zapier Workflow:
<img width="905" alt="Screenshot 2023-09-22 at 10 40 33 AM" src="https://github.com/open-telemetry/community/assets/43380952/ecab0a02-e1b8-4ce4-bf64-11385bf5c203">

### Step by Step
1. Zapier gets a event from the Webhook that only subscribes to repo security advisories 
<img width="914" alt="Screenshot 2023-09-22 at 10 41 45 AM" src="https://github.com/open-telemetry/community/assets/43380952/5b7fb8c4-6ee2-49bc-a6ad-e8590c27cd99">

2. It ensures the event is untriaged and needs to be examined. 

3. Zapier makes an API call to GitHub based on the repo in the event to pull teams assigned to the repo. A organization personal access token is needed for this and the subsequent API call
<img width="1274" alt="Screenshot 2023-09-22 at 10 48 39 AM" src="https://github.com/open-telemetry/community/assets/43380952/4cadf2d8-ad0f-4d3b-b729-1fc7a59d870a">

<img width="920" alt="Screenshot 2023-09-22 at 10 44 15 AM" src="https://github.com/open-telemetry/community/assets/43380952/07886f82-5380-4fc0-a938-cee8ba6651f0">

<img width="1021" alt="Screenshot 2023-09-22 at 10 42 57 AM" src="https://github.com/open-telemetry/community/assets/43380952/9ef5e96d-d2b7-43cb-9c27-a08f624a8c0a">

5. Zapier filters to just maintainer teams / teams with maintainer rights

6. Zapier makes another API call to GitHub to assign the maintainers to the issue

**Comment by tylerbenson** [comment]
CC @trask given your past involvement with the Zapier account.

**Comment by trask** [comment]
> access to the community Zapier account

a potential issue is that our Zapier workflows are authenticated against other resources (Zoom and Google Docs), so i'm not sure if we can give out access to it

(and after this workflow is added it will have even more authenticated access)

a few options:
* if you are able to create the workflows in another account, we could try [exporting and importing](https://help.zapier.com/hc/en-us/articles/8496308481933-Import-and-export-Zaps-in-your-Team-or-Company-account) them into the community account
* we could implement and test the workflows together over Zoom
* we could open a ticket with CNCF about upgrading our Zapier account to the Team plan which would allow us to have multiple users with varied access rights, so you could create the workflow and test the workflow under your user (in the community account), and then we could move it to a GC/TC user (also in the community account).

**Comment by cartersocha** [comment]
@trask lets try a combination of 1 and 2 if you have some time next week. I exported the zap. We can import into the community account and then put in the GitHub access token and webhook. Worst case we manually copy over. 

Thanks for the help and taking the time to assist!

**Comment by trask** [comment]
@cartersocha are we good to close this issue now? thx
