### ISSUE TITLE
How can OpenTelemetry be integrated into a C project? I saw that there is no C among the supported languages, only C++. Is there any case of integrating it into a C project?

### ISSUE THREAD

**Issue by niuzhi** [open-telemetry/community#1696]
How can OpenTelemetry be integrated into a C project? I saw that there is no C among the supported languages, only C++. Is there any case of integrating it into a C project?
https://opentelemetry.io/docs/instrumentation/

**Comment by arminru** [comment]
Hi @niuzhi!
I suggest opening an issue in https://github.com/open-telemetry/opentelemetry-cpp.
The folks there should be able to guide you further.
