### ISSUE TITLE
Consider adding more TC members

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#1697]
As we know, the TC is very busy.  I think they would benefit from bolstering their membership.
If there are solid candidates from under represented companies or SIGs, the TC should consider inviting them.

Alternatively, perhaps the per company limit should be raised from  2 to 3.  This currently only impacts Lighstep and Splunk, but I'm sure there are qualified candidates at either company that could be considered if the limit were increased.

**Comment by jmacd** [comment]
I think we should consider growing the TC by a small number to include candidates who bring new areas of expertise that are necessary for the growth of OpenTelemetry. The areas that we appear to need new technical committee members to cover that I've seen mentioned recently:

1. Mobile telemetry
2. Profiling

**Comment by jpkrohling** [comment]
Do we have people with a background in client instrumentation? That would be another area to cover if we don't have yet.

**Comment by bogdandrutu** [comment]
> Alternatively, perhaps the per company limit should be raised from 2 to 3. This currently only impacts Lighstep and Splunk, but I'm sure there are qualified candidates at either company that could be considered if the limit were increased.

@tylerbenson I think you are kind of asking 2 things in one issue, hence none will be resolved. Would suggest to move this to a different issue and keep this only about growing.

**Comment by tylerbenson** [comment]
I'm just going to close this and let the TC figure it out internally.
