### ISSUE TITLE
REQUEST: Repository maintenance on `opentelemetry-java`

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#1699]
### Affected Repository
https://github.com/organizations/open-telemetry/settings/actions/runner-groups/8
https://github.com/open-telemetry/opentelemetry-java

### Requested changes
- Add `opentelemetry-java` to `Repository Access > selected repositories config`
- Add `open-telemetry/opentelemetry-java/.github/workflows/benchmark.yml@refs/heads/main,open-telemetry/opentelemetry-java/.github/workflows/benchmark-tags.yml@refs/heads/main,` to `Workflow access > selected workflows config`
 
### Purpose
Enable bare metal benchmark execution.
 
### Expected Duration
permanently

### Repository Maintainers
- @open-telemetry/java-maintainers

**Comment by arminru** [comment]
@tylerbenson I enrolled the repo and both workflows, please let me know if it works as expected.

**Comment by arminru** [comment]
For the `main` workflow it looks like it picked up the first commit containing adding the workflow definition:
https://github.com/open-telemetry/opentelemetry-java/actions/runs/6330283817

**Comment by arminru** [comment]
@tylerbenson @jack-berg The run failed with
```
Run benchmark-action/github-action-benchmark@v1
/usr/bin/git -c user.name=github-action-benchmark -c user.email=github@users.noreply.github.com -c http.https://github.com/.extraheader= fetch ***github.com/open-telemetry/opentelemetry-java.git benchmarks:benchmarks
fatal: couldn't find remote ref benchmarks
```

I can add a branch protection rule that excludes a branch named `benchmark` from the EasyCLA check (see #1577) so you can create an empty branch as described in #1695. I think this will also be necessary for the workflow to push its results there.

cc @ocelotl as you'll likely face the same in #1700.

**Comment by tylerbenson** [comment]
Thanks @arminru.  I think the branch just needs to be created. I'll work with @jack-berg on that.

**Comment by tylerbenson** [comment]
It's working!
https://open-telemetry.github.io/opentelemetry-java/

**Comment by jack-berg** [comment]
Nice! Closing this issue.
