### ISSUE TITLE
Migrating OpenTracing/OpenCensus members to new organization?

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#17]
Will we be adding existing OT and OC members to this new organization, or will everyone need to go through the sponsorship process in https://github.com/open-telemetry/community/blob/master/community-membership.md?

**Comment by SergeyKanzhelev** [comment]
+ @tedsuo who is on point to nominate people to bootstrap languages in terms of approvers and maintainers. Mostly taking commitments from people as we hope for fast bootstrapping. 

For the membership - I'd let it sit and see how migration happens natively and if it will be a lot of pain - we can organize some mass migration

**Comment by SergeyKanzhelev** [comment]
Closing for now, please re-open if you have suggestions on the best course of actions here.
