### ISSUE TITLE
REQUEST: New membership for bryannaegele

### ISSUE THREAD

**Issue by bryannaegele** [open-telemetry/community#170]
### GitHub Username

@bryannaegele

### Organization you are requesting membership in

@open-telemetry/opentelemetry-erlang

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tsloughter 
- @hauleth 

### List of contributions to the OpenTelemetry project

- Erlang Ecosystem Foundation Observability Group member
- Active contributor to several @beam-telemetry projects
- Author and maintainer of @bryannaegele/telemetry_metrics_prometheus

**Comment by tsloughter** [comment]
+1

**Comment by bogdandrutu** [comment]
Added as a member.
