### ISSUE TITLE
REQUEST: Repository maintenance on `opentelemetry-python`

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/community#1700]
### Affected Repository

https://github.com/organizations/open-telemetry/settings/actions/runner-groups/8
https://github.com/open-telemetry/opentelemetry-python

### Requested changes

- Add opentelemetry-python to Repository Access > selected repositories config
- Add open-telemetry/opentelemetry-python/.github/workflows/benchmarks.yml@refs/heads/main to Workflow access > selected workflows config
 
### Purpose

Enable bare metal benchmark execution.
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/python-maintainers

[This PR](https://github.com/open-telemetry/opentelemetry-python/pull/3450) is pending still, please disregard this issue until that PR is merged.

**Comment by arminru** [comment]
@open-telemetry/python-maintainers I noticed that https://github.com/open-telemetry/opentelemetry-python/pull/3450 was merged in the meantime so I enrolled the workflow to run on the benchmark nodes.
