### ISSUE TITLE
REQUEST: Repository maintenance on `opentelemetry-js`

### ISSUE THREAD

**Issue by martinkuba** [open-telemetry/community#1701]
### Affected Repository

[github.com/organizations/open-telemetry/settings/actions/runner-groups/8](https://github.com/organizations/open-telemetry/settings/actions/runner-groups/8)
[open-telemetry/opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js)

### Requested changes

* Add `opentelemetry-js` to `Repository Access > selected repositories config`
* Add `open-telemetry/opentelemetry-js/.github/workflows/benchmark.yml@refs/heads/main` to `Workflow access > selected workflows config`

This is related to these requests for Java and Python
https://github.com/open-telemetry/community/issues/1699
https://github.com/open-telemetry/community/issues/1700

### Purpose

Enable bare metal benchmark execution.

### Expected Duration

permanently

### Repository Maintainers

* https://github.com/orgs/open-telemetry/teams/js-maintainers

**Comment by arminru** [comment]
@martinkuba @pichlermarc I enrolled the repo and the workflow. Please let me know if it works as expected.

**Comment by martinkuba** [comment]
@arminru Looks like the workflow is running correctly with the self-hosted runner. Thank you!
