### ISSUE TITLE
REQUEST: New membership for noahfalk

### ISSUE THREAD

**Issue by noahfalk** [open-telemetry/community#1706]
### GitHub Username

@noahfalk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lmolkova 
- @joaopgrassi

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

I am the diagnostics architect for .NET. I've done a lot of the design work integrating OTel into .NET runtime API and collaborate @reyang on OpenTelemetry.NET.

Most of my work occurs in the .NET repo and behind the scenes on design and coordination. These are a few examples from the OTel side of GH though:

https://github.com/open-telemetry/opentelemetry-dotnet/pull/4874
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4797
https://github.com/open-telemetry/oteps/pull/123
https://github.com/open-telemetry/opentelemetry-specification/issues/3061#issuecomment-1601818538
https://github.com/open-telemetry/opentelemetry-specification/pull/1753#pullrequestreview-681585540

**Comment by lmolkova** [comment]
I support

**Comment by noahfalk** [comment]
@joaopgrassi (@lmolkova requested I ping you on this)

**Comment by trask** [comment]
I support (but replaced myself above with @joaopgrassi since we need supporters from two different companies)

**Comment by joaopgrassi** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @noahfalk!
