### ISSUE TITLE
REQUEST: New membership for jamesnk

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/community#1707]
### GitHub Username

@jamesnk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lmolkova
- @joaopgrassi

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

I'm heavily involved with gRPC and ASP.NET Core (web framework for .NET), and I'm a lead engineer on the observability story in these areas.

- https://github.com/open-telemetry/opentelemetry-dotnet/pull/275
- https://github.com/open-telemetry/opentelemetry-dotnet/pull/4753
- https://github.com/open-telemetry/opentelemetry-dotnet/pull/4823
- [Many issues](https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+sort%3Aupdated-desc+author%3AJamesNK+)

**Comment by joaopgrassi** [comment]
I support!

**Comment by lmolkova** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @JamesNK!
