### ISSUE TITLE
REQUEST: New membership for ferd

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/community#171]
I'm creating this for Fred Hebert (@ferd). He will comment in response to confirm this is all accurate.

### GitHub Username

@ferd

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tsloughter 
- @hauleth 

### List of contributions to the OpenTelemetry project

- Active contributor to @beam-telemetry projects
- Actively reviewing opentelemetry-erlang pull requests

**Comment by ferd** [comment]
+1 and I have fulfilled all requirements

**Comment by bogdandrutu** [comment]
@tsloughter this request is to add @ferd as a member of the community (I want to clarify this). If you need to have @ferd as approver see https://github.com/open-telemetry/community/blob/master/community-membership.md#community-membership
