### ISSUE TITLE
REQUEST: New membership for @marandaneto

### ISSUE THREAD

**Issue by marandaneto** [open-telemetry/community#1710]
### GitHub Username

@marandaneto

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @LikeTheSalad
- @joaopgrassi

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed and/or Issues responded to
	- https://github.com/open-telemetry/opentelemetry-android/issues/149
	- https://github.com/open-telemetry/opentelemetry-android/pull/173
	- https://github.com/open-telemetry/opentelemetry-android/pull/145
	- https://github.com/open-telemetry/opentelemetry-android/pull/180
	- https://github.com/open-telemetry/opentelemetry-android/pull/156

**Comment by marandaneto** [comment]
Closing it for now until I actively contribute to OTel and meet the other requirements.

**Comment by marandaneto** [comment]
I've reopened this issue with the required sponsors and a list of issues/PRs I contributed to, there are probably more.

**Comment by LikeTheSalad** [comment]
I support.

**Comment by joaopgrassi** [comment]
I support

**Comment by breedx-splk** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @marandaneto!

**Comment by marandaneto** [comment]
> Invite sent. Welcome, @marandaneto!

Thanks, the next step is to get into https://github.com/orgs/open-telemetry/teams/semconv-mobile-approvers 
Do I need to do something about that or just keep contributing?

**Comment by arminru** [comment]
Hey there! You can already get involved in the respective group and their calls and implementation work. Then the maintainers would be able to nominate you to become an approver and either add you themselves or request that via an issue here.
The formal requirements are specified here: https://github.com/open-telemetry/community/blob/main/community-membership.md#approver
