### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-ruby-contrib

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/community#1716]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-ruby-contrib

### Requested changes

Give 'Admin' permissions to `@open-telemetry/ruby-contrib-maintainers`

 
### Purpose

I accidentally reset the permissions while trying to verify permission levels.
 
### Expected Duration

Permanently

### Repository Maintainers

- @open-telemetry/ruby-contrib-maintainers

**Comment by mwear** [comment]
This should be done @arielvalentin. Double check and feel free to close this issue if it has been addressed.

**Comment by arielvalentin** [comment]
@mwear The permissions were not set as I expected. The `ruby-contrib-approvers` team was set to `Admin` but they should not have had those rights. 

I would also like to be granted admin rights again to the Repo. 

Please set the following permissions:

| Person or Team | Role |
| --- | --- |
| @open-telemetry/ruby-contrib-maintainers | `OpenTelemetry Maintainers` |
| @open-telemetry/ruby-maintainers  | `OpenTelemetry Maintainers` |
| @open-telemetry/ruby-contrib-approvers | `Maintain` |
| @arielvalentin | `Admin` |

**Comment by mwear** [comment]
I've updated the permissions. Please double check they are correct.

**Comment by arielvalentin** [comment]
Thanks again @mwear !
