### ISSUE TITLE
REQUEST: Repository maintenance on https://github.com/open-telemetry/opentelemetry-php-instrumentation/

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#1718]
### Affected Repository
https://github.com/open-telemetry/opentelemetry-php-instrumentation/

### Requested changes

Give `Admin` permissions to @bobstrecansky , @brettmc , and @pdelewski , to mirror the other PHP repositories - [base](https://github.com/open-telemetry/opentelemetry-php) and  [contrib](https://github.com/open-telemetry/opentelemetry-php-contrib/settings)

 
### Purpose
Maintaining this repo will be difficult without this access

 
### Expected Duration
Permanent

### Repository Maintainers

@bobstrecansky 
@brettmc
@pdelewski

**Comment by dyladan** [comment]
Only the TC can handle this.

/cc @arminru

**Comment by arminru** [comment]
On https://github.com/open-telemetry/opentelemetry-php and https://github.com/open-telemetry/opentelemetry-php-contrib only @bobstrecansky is set as an Admin.
Should all three users mentioned above be added as Admins on all three repos?

**Comment by bobstrecansky** [comment]
@arminru - yes please - all three Maintainers should be admins for all three repos.

**Comment by arminru** [comment]
@bobstrecansky admins added as requested.

If any user departs from their maintainer role, please make sure to either remove their permissions yourself or open another community issue here.

cc @open-telemetry/php-maintainers 

Thanks!

**Comment by bobstrecansky** [comment]
Thank you @arminru !
