### ISSUE TITLE
REQUEST: New membership for @antonfirsov

### ISSUE THREAD

**Issue by antonfirsov** [open-telemetry/community#1721]
### GitHub Username

@antonfirsov

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lmolkova
- @joaopgrassi

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

As the primary author of the `System.Net.*` metrics implemented in .NET 8.0 (see https://github.com/dotnet/runtime/pull/87319 & follow ups), I'm interested in discussions & reviews shaping HTTP semantic conventions.

- https://github.com/open-telemetry/opentelemetry-specification/discussions/3519
- https://github.com/open-telemetry/opentelemetry-specification/issues/3520
- https://github.com/open-telemetry/semantic-conventions/pull/205#discussion_r1272763452
- https://github.com/open-telemetry/semantic-conventions/pull/70#discussion_r1213337374
- Review on https://github.com/open-telemetry/semantic-conventions/pull/283, and related discussions.

**Comment by lmolkova** [comment]
I support!

**Comment by joaopgrassi** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @antonfirsov!
