### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-cpp

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/community#1727]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-cpp

### Requested changes

Per: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md

"
If requested, foo-maintainers will be granted Admin permissions, and in return they must document any changes they make to the repository settings in a file named .github/repository-settings.md in their repository (other than temporarily disabling "Do not allow bypassing the above settings", see branch protection rules below).
"

Give 'Admin' permissions to @open-telemetry/cpp-maintainers 

* @ThomsonTan 
* @lalitb 
* @marcalff 
* @esigo
 
### Purpose

We (cpp-maintainers) would like to have control on which CI build is `required` / `not required`, as part of the CI workflows.

This is needed as a lot of new builds have been added (but are not tagged as required),
and some existing builds may disappear (obsolete platform/configuration) or be changed in name/scope,
due to worflow cleanup.

I could not find anywhere in the github UI a way to set this up, so I assume the admin privilege is required for this.

Also, we need a way to temporarily bypass branch protections settings to forcefully merge a PR, when a failure is caused by issues external to opentelemetry-cpp (changes in github images for a given platform, network failures during the build).

Upon acceptance, file `.github/repository-settings.md` will be created and maintained to reflect local admin changes.

### Expected Duration

Permanently

### Repository Maintainers

cc @open-telemetry/cpp-maintainers

**Comment by arminru** [comment]
I updated the access settings for @open-telemetry/cpp-maintainers to `Admin` and removed the explicit `Mainain` access for @marcalff since you're already covered via the maintainer's group anyway.

Also, @SergeyKanzhelev was still listed explicitly, I dropped your access setting as well.

**Comment by marcalff** [comment]
Thanks @arminru 

FYI, see pr:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2392

I suggest to keep this issue opened until the PR is merged, to make sure we don't forget to create the repository settings documentation.

**Comment by arminru** [comment]
Thanks, @marcalff!

I'll close the issue now that your PR was merged.
