### ISSUE TITLE
REQUEST: New membership for cedricziel

### ISSUE THREAD

**Issue by cedricziel** [open-telemetry/community#1738]
### GitHub Username

@cedricziel

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @julianocosta89
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-demo/pull/1181
  - https://github.com/open-telemetry/opentelemetry-demo/pull/1180
  - https://github.com/open-telemetry/opentelemetry-demo/pull/1083
  - https://github.com/open-telemetry/opentelemetry-demo/pull/1074
  - https://github.com/open-telemetry/opentelemetry-demo/pull/899
  - https://github.com/open-telemetry/opentelemetry-demo/pull/671
  - https://github.com/open-telemetry/opentelemetry-demo/pull/661
  - https://github.com/open-telemetry/opentelemetry-demo/pull/657
  - https://github.com/open-telemetry/opentelemetry-demo/pull/319
  - https://github.com/open-telemetry/opentelemetry-demo/pull/318
  - https://github.com/open-telemetry/opentelemetry-demo/pull/291
  - https://github.com/open-telemetry/opentelemetry-demo/pull/239
  - https://github.com/open-telemetry/opentelemetry-demo/pull/238
  - https://github.com/open-telemetry/opentelemetry-demo/pull/234
  - https://github.com/open-telemetry/opentelemetry-php/pull/961
  - https://github.com/open-telemetry/opentelemetry-php/pull/960
  - https://github.com/open-telemetry/opentelemetry-php/pull/943
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/43
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/58
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/142
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/143
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/144
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/146
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/147
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/145
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/181
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/182
  - https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/172
  - https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/175
- Issues responded to
- SIG projects I am involved with
  - opentelemetry-demo
  - opentelemetry-php

**Comment by jpkrohling** [comment]
I support!

**Comment by julianocosta89** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @cedricziel!
