### ISSUE TITLE
UTC Times for SIG meetings

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/community#1744]
As a non US hopeful contributor, it would be nice to list SIG meeting times in UTC rather than or as well as PT so that we don't have to worry about potential daylight savings etc changes

**Comment by tigrannajaryan** [comment]
The meetings _are_ actually scheduled in PT timezone. Listing them in UTC will either require to update the listing every time the DST changes or the meeting time will change every time the DST changes. Why use PT and not some other timezone? It seem the largest cohort of contributors are in PT.

**Comment by hdost** [comment]
FWIW Rust SIG was specifically on UTC but it actually doesn't help you escape DST it just changes when it affects you.
