### ISSUE TITLE
Add Cedric Ziel to OTel-demo approver GitHub team

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/community#1745]
@cedricziel was recently added as an approver to the OTel demo repo. Please add him to the formal @open-telemetry/demo-approvers github team so he is added on PRs.

**Comment by trask** [comment]
hey @cartersocha, it looks like you have role "Maintainer" in that github team, so should be able to add new members, see

https://github.com/open-telemetry/community/blob/0cb6dcadb53f1f7ffe5ef819ceef02ac9e6886c8/docs/how-to-configure-new-repository.md?plain=1#L32-L34

**Comment by cartersocha** [comment]
Ahh gotcha. Many thanks. Mobile didn't show the option and I was away from my computer
