### ISSUE TITLE
Digitalized Election Proposal - Candidate Testsuite Matching

### ISSUE THREAD

**Issue by abitrolly** [open-telemetry/community#1754]
(@dyladan, @mtwo, or @trask)

I've received the proposal to cast a vote, but my role is so minor (https://github.com/open-telemetry/opentelemetry-specification/issues/2773) that I don't feel like I know anyone sufficiently well to vote just by reading bios. Or speaking in a more harsh way - I don't care. However, that exaggeration is a lie - I am still interested to vote for every person who will deliver the feature that I find missing in specification that replaced Zipkin.

* [ ] **record incomplete spans** - _The problem with OpenTracing now is that incomplete spans are lost. If the process dies, its spans will never be finished and will never arrive, so tracing of crashes becomes incomplete/impossible_

I want to propose a process that everybody clicks that checkbox, gets my vote. I feel such "personal election testsuite" is a better way to cast a vote in technological community, than a classical paper and emotional based process of pre-internet era.

**Comment by abitrolly** [comment]
@austinlparker a bit offtopic, but draw spans from start/stop span events as soon as they happen, and require tools such as Jaeger to support such real-time span tracking.

**Comment by trask** [comment]
there doesn't appear to be successful prior art for this kind of open source governance body election
