### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1755]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-java

### Requested changes

Delete and recreate the @open-telemetry/java-maintainers team
 
### Purpose

We have isolated a weird problem in the Zapier security advisory workflow where

```
curl -H "Accept: application/vnd.github+json" \
     -H "X-GitHub-Api-Version: 2022-11-28" \
     -H "Authorization: Bearer <TOKEN>" \
     --request PATCH \
     --data '{"collaborating_teams":["java-maintainers"]}' \
     https://api.github.com/repos/open-telemetry/opentelemetry-java/security-advisories/<ADVISORY>
```
 
fails with

```
   Team 'java-maintainers' not found, collaborating_teams cannot be modified
```

But when @jack-berg created an identical team named `java-maintainers2` that team worked, so we suspect something is weird with the `java-maintainers` team and are hoping that recreating it will fix the issue.

### Repository Maintainers

- @open-telemetry/java-maintainers

**Comment by jack-berg** [comment]
I've deleted the original `java-maintainers` and renamed `java-maintainers2` to `java-maintainers`. Closing as completed. We can re-open if this doesn't fix the issue.

**Comment by jack-berg** [comment]
Re-opening. Apparently this didn't work and @trask is still seeing the no found error.

**Comment by trask** [comment]
will probably end up opening a github support ticket, not sure why this particular team name(?) seems to be a problem

**Comment by trask** [comment]
github ticket created (#2399896)

**Comment by trask** [comment]
github deployed a fix for this and looks to be working now
