### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-ebpf

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#1758]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-ebpf

### Requested changes

Rename opentelemetry-ebpf to <picking a name>
 
### Purpose

See https://github.com/open-telemetry/opentelemetry-ebpf/issues/233
 
### Expected Duration

Permanent.

### Repository Maintainers

- @open-telemetry/ebpf-maintainers

**Comment by mtwo** [comment]
I discussed this at the GC today at @atoulme's request. The GC is supportive of the name change, as long as it doesn't use 'npm' as the new name as this is already overloaded with the popular JS package manager and Nginx Proxy Manager. 'otel-network-performance' or something like that is recommended.

**Comment by atoulme** [comment]
I'll try and see if we can agree on a name here.
Please vote with emoji:

- 🎉 opentelemetry-network-monitoring
- ❤️ opentelemetry-network-performance
- 🚀 opentelemetry-network-performance-monitoring

Or comment with a name of your choosing.

**Comment by yonch** [comment]
in the spirit of "keep it simple/minimal"
* :+1: opentelemetry-network

(since opentelemetry already implies monitoring / performance / detecting faults)

**Comment by rogercoll** [comment]
Another option that aligns with auto instrumentation [repositories](https://github.com/open-telemetry?q=instrumentat&type=all&language=&sort=):

- 👍 opentelemetry-network-instrumentation

**Comment by atoulme** [comment]
Thank you all for your time and consideration weighing in on this issue.

With 3 votes, `opentelemetry-network` is considered the best option.

Can a GC member perform the rename please?

**Comment by trask** [comment]
cc @open-telemetry/technical-committee  who has these powers

**Comment by tigrannajaryan** [comment]
@open-telemetry/technical-committee @open-telemetry/governance-committee any objections to renaming `opentelemetry-ebpf` to `opentelemetry-network`?

**Comment by tigrannajaryan** [comment]
@open-telemetry/docs-maintainers is `opentelemetry-ebpf` referenced/consumed by opentelemetry.io in a way that can be impacted by renaming the repo?

**Comment by mtwo** [comment]
> @open-telemetry/technical-committee @open-telemetry/governance-committee any objections to renaming `opentelemetry-ebpf` to `opentelemetry-network`?

The GC signed off in [late October](https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8/edit#heading=h.dost9u3qz1hj)

**Comment by atoulme** [comment]
There should be no impact on docs as this search shows no reference to the repository there:
https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry.io+%22opentelemetry-ebpf%22&type=pullrequests

The github repository rename will not break links as github will redirect to the new repository name.

**Comment by cartermp** [comment]
Yep, docs are clear of this name. No issues with a rename. We do mention eBPF but it's in an entirely different context.

**Comment by yurishkuro** [comment]
> is opentelemetry-ebpf referenced/consumed by opentelemetry.io in a way that can be impacted by renaming the repo?

fwiw after renaming the old name still redirects to the new repo name. However, if the plan is to reuse the ebpf name for something else later than it may cause confusion.

**Comment by atoulme** [comment]
@open-telemetry/technical-committee gentle ping that this is pending action.

**Comment by tigrannajaryan** [comment]
I don't see any objections, going ahead with renaming to `opentelemetry-network`.

**Comment by tigrannajaryan** [comment]
Renamed to: https://github.com/open-telemetry/opentelemetry-network

@atoulme I can also rename all `ebpf-` teams to `network-` to be consistent. Are you OK?

**Comment by atoulme** [comment]
Yes, and thank you!

**Comment by tigrannajaryan** [comment]
Teams renamed too. I think we can close this.
