### ISSUE TITLE
REQUEST: New membership for cparkins

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/community#1759]
cparkins

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @atoulme 
- @MovieStoreGuy

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19436
- PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25096
- PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28626
- PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28634
- PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28650

**Comment by atoulme** [comment]
I support

**Comment by MovieStoreGuy** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @cparkins!
