### ISSUE TITLE
Java SIG calendar entry has no meeting notes Link

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/community#176]
Most other SIGs have a Link to their meeting notes (Google Doc) directly in the event description on the Google Calendar event, but Java doesn't, e.g. https://www.google.com/calendar/event?eid=NmRpNmFvcGpjNHBtY2I5ajZzczM2YjlrYzVpMzhiOW82dGdqOGJiNjYwbzZhY2hoY29xbWFwOWk2NF8yMDE5MDkxM1QxNTAwMDBaIGdvb2dsZS5jb21fYjc5ZTNlOTBqN2Jic2EybjJwNWFuNWxmNjBAZw

**Comment by SergeyKanzhelev** [comment]
Fixed, thanks for noting

![image](https://user-images.githubusercontent.com/9950081/65191462-e65e5680-da28-11e9-9ea0-63f4e65ecb85.png)
