### ISSUE TITLE
REQUEST: New membership for marctc

### ISSUE THREAD

**Issue by marctc** [open-telemetry/community#1761]
### GitHub Username

@marctc

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @crobert-1
- @djaglowski

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21090
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28670
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24410
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24409
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24407
  - https://github.com/open-telemetry/opentelemetry-python/issues/3275  
- SIG projects I am involved with
  - opentelemetry-collector-contrib

**Comment by crobert-1** [comment]
I support

However, from [documentation](https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements) I'm not sure I'm qualified since I'm only a triager and not an approver/maintainer. I'll defer to others as to qualifications here in case I misunderstood something.

**Comment by jpkrohling** [comment]
I support as well!

**Comment by djaglowski** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @marctc!

**Comment by marctc** [comment]
> Invite sent. Welcome, @marctc!

Thanks :pray:
