### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-rust-contrib

### ISSUE THREAD

**Issue by hdost** [open-telemetry/community#1765]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-rust-contrib

### Requested changes

Create Repo and provide access to @open-telemetry/rust-maintainers and @open-telemetry/rust-approvers 

### Purpose

Plan to split contrib into separate repo
https://github.com/open-telemetry/opentelemetry-rust/issues/841

 
### Expected Duration

permanently

### Repository Maintainers

Already mentioned above.

**Comment by arminru** [comment]
@open-telemetry/rust-maintainers @open-telemetry/rust-approvers

You can find the new repo here: https://github.com/open-telemetry/opentelemetry-rust-contrib

Please add a list of maintainers and approvers (I suggest linking to https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md#approvers-and-maintainers for a single place to maintain) to the README and add a CODEOWNERS file.

If you need a rule set up to allow Dependabot or Renovate as described [here](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-dependabot) and [here](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-renovate), let me know.

**Comment by hdost** [comment]
Thank you, I'll work on getting it setup.

**Comment by hdost** [comment]
All seems to be working. This can be closed.
