### ISSUE TITLE
Outreachy - 2024 May - Prepare for our participation

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1766]
From https://www.outreachy.org/ :
✍🏿 [Intern applications](https://www.outreachy.org/apply/) are accepted from mid-January to early February
📑 Internship project list is finalized in early March 2023
🙋🏽 Mentors can [sign up](https://www.outreachy.org/communities/cfp/) starting in January
🙌🏿 Internships run late May 2024 to late August 2024

Meta Tasks:
- [x] #1767
- [x] #1946
- [x] #1947
- [x] #1768
- [x] #1769
- [x] #1770
- [x] #1771
- [x] #1772

Internship tasks:

- [x] #1988
- [x] #1989
- [x] #1990
- [x] #1991
- [x] #1992

**Comment by jpkrohling** [comment]
Slack channel for this internship: [#otel-mentorship-outreachy-may-2024](https://cloud-native.slack.com/archives/C06MF3939NX)

**Comment by aditi5926** [comment]
Do we have to work on Meta tasks or Internship tasks?

**Comment by Dev-JoyA** [comment]
@aditi5926 internship tasks

**Comment by jpkrohling** [comment]
This has been completed now.
