### ISSUE TITLE
Outreachy - 2024 May - Collect feedback from the previous cohort

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1767]
We were part of the Outreachy internship, Dec 2023 cohort. I could have done a better job preparing the ground for the participants, and I would like to collect feedback on what can be improved.

Here's a list of ideas for the next cohort:
- [ ] #1773
- [ ] Recruit more folks from the community to join the #otel-outreachy channel to help people on their first steps
- [ ] Have a weekly office-hours session to answer questions and unblock participants

**Comment by EjiroLaurelD** [comment]
As an Outreachy contributor for the Dec 2023 cohort, I believe it will be great if the above suggestions are implemented as it will go a long way in helping future contributors/applicants.
Understanding what to do for the project was a bit confusing for me as a first timer, I had a lot of questions and wasn't really sure how to go about the project. 
I was able to get a hang of it after making some observations on the community slack group, asking mentors and fellow contributors questions. 
Asking questions and requesting feedback definitely worked for me. 
The weekly office-hours would be a great way to help participants through their confusion in the contribution phase . It would be a great way to help participants get up to speed quickly and efficiently.

**Comment by oly-baby** [comment]
Participating in this Outreachy Dec 2023 Cohort is a challenging experience for me, but with the help of the mentors, communication channel and my follow participants I was able to make a little contribution. The list of ideas  for improving the preparation process for the next cohort of Outreachy interns is very great and I know it will be very helpful especially the weekly office-hour session.
Creating a dedicated Outreachy Guide is an excellent idea as I was lost at some point. It will provide a structured resource for interns to understand the project, its goals, and the steps they should follow to get started effectively. Engaging more community members can help create a welcoming environment and offer diverse perspectives on the project,  Your proactive approach in preparing the ground for participants is commendable, and I believe these improvements will be well-received.

**Comment by OluomaEsther** [comment]
As an Outreachy applicant Dec 2023 Cohort the whole thing was overwhelming at first, but but with the help of the mentors in the communication channel, I was able to understand what I am supposed to do and make a little contribution. To improve in the preparation process for the next cohort of Outreachy interns it will be very helpful to have onboarding sessions with the interns before the contribution to enable them understand what they are expected to do. The process looks overwhelming for first time contributors and creating a guide will help the applicants understand the project, its goals, and the steps they should follow to get started effectively.

**Comment by jpkrohling** [comment]
Thank you for all your feedback! This is valuable, and will help us in the next cohorts.
