### ISSUE TITLE
Outreachy - 2024 May - Call for ideas in the community

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1768]
Project ideas:

* One or more languages from this: https://github.com/open-telemetry/community/issues/1970

**Comment by yuriolisa** [comment]
@jpkrohling, I can contribute somehow to teaching the mentees about the Operator Framework.

**Comment by jpkrohling** [comment]
Another idea: one of the steps of this refactoring (migrate policies) could be the target of this, or a future, Outreachy internship: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31580
