### ISSUE TITLE
Archive Slack channel #otel-collector-contrib-maintainers

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/community#1775]
According to [this Slack post](https://cloud-native.slack.com/archives/C02LFCQBG2V/p1691599227020279) from @atoulme, a decision was made during a Collector SIG meeting to archive the channel [#otel-collector-contrib-maintainers](https://cloud-native.slack.com/archives/C02LFCQBG2V) in favor of the general purpose channel [#otel-collector](https://cloud-native.slack.com/archives/C01N6P7KR6W).

I saw a similar issue on this repo https://github.com/open-telemetry/community/issues/1694 that describes creating a CNCF Service Desk ticket, but I don't have access to CNCF Service Desk. Can somebody help with this?

**Comment by arminru** [comment]
I created a service desk ticket with the CNCF at https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2034.

**Comment by krook** [comment]
Hi folks. I archived the channel and updated the service desk ticket. This is done.

**Comment by arminru** [comment]
Thank you, @krook!
