### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-erlang and opentelemetry-erlang-contrib

### ISSUE THREAD

**Issue by bryannaegele** [open-telemetry/community#1778]
Putting this into one request. I can split if necessary.

### Affected Repository

https://github.com/open-telemetry/opentelemetry-erlang
https://github.com/open-telemetry/opentelemetry-erlang-contrib

### Requested changes

Install Renovate app
 
### Purpose

We would like to enable renovatebot to help detect and PR dependency updates.
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/erlang-maintainers
@open-telemetry/erlang-contrib-maintainers

**Comment by arminru** [comment]
Hi @bryannaegele!

I wasn't sure if you were asking for Renovate (https://github.com/apps/renovate) or Forking Renovate (https://github.com/apps/forking-renovate) as both are used in OTel but I assumed it's the former and enabled it for both repos you requested.

Please let me know if it works as expected.

**Comment by bryannaegele** [comment]
Yeah, the former. It seems to be working well. Thank you!
