### ISSUE TITLE
Donation for OpenTelemetry

### ISSUE THREAD

**Issue by JennyScripts3** [open-telemetry/community#1780]
Hello

On the 26th october we hosted our annual customer event Puzzle up! at Wankdorf Stadium, and we conducted a buzzer action to raise donations for each of our vision elements:

we care: Hörschatz
we invent: NetAP
we contribute: Open Telemetry

During this buzzer action, we collected donations totaling 1,050 Swiss Francs for Open Telemetry. We will transfer the money as soon as you provide us with the payment/account details. Can someone help us?

Thank you very much & best regards
Jenny from Puzzle ITC

**Comment by trask** [comment]
Hi @JennyScripts3, thanks for reaching out, and thanks for your interest in and support of the OpenTelemetry project!

I will reach out to the CNCF (our parent OSS organization) to find out how you can make a donation and get back to you.

**Comment by trask** [comment]
I've created a CNCF ServiceDesk ticket to find out (btw, the CNCF is running KubeCon this week, so response from them may be delayed)

**Comment by trask** [comment]
hi @JennyScripts3, please try this: https://docs.linuxfoundation.org/lfx/crowdfunding/donate-sponsor/donate-as-a-sponsor
