### ISSUE TITLE
REQUEST: New membership for @nstawski

### ISSUE THREAD

**Issue by nstawski** [open-telemetry/community#1784]
### GitHub Username

@nstawski

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @ocelotl
- @lzchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-python/pull/3310
- https://github.com/open-telemetry/opentelemetry-python/pull/3351
- https://github.com/open-telemetry/opentelemetry-python/pull/3486
- https://github.com/open-telemetry/opentelemetry-python/pull/3519
- https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1072
- https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1136
- https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1137
- https://github.com/open-telemetry/opentelemetry-js/pull/673
- https://github.com/open-telemetry/opentelemetry-js/pull/562
- https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1741
- https://github.com/open-telemetry/opentelemetry-python/pull/3279
- https://github.com/open-telemetry/opentelemetry-python/pull/3472

Issues responded to
- https://github.com/open-telemetry/opentelemetry-python/issues/3114
- https://github.com/open-telemetry/opentelemetry-python/issues/3201
- https://github.com/open-telemetry/opentelemetry-python/issues/3129
- https://github.com/open-telemetry/opentelemetry-python-contrib/issues/939
- https://github.com/open-telemetry/opentelemetry-python-contrib/issues/946
- https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1037
- https://github.com/open-telemetry/opentelemetry-python-contrib/issues/943

SIG projects I am involved with
- OpenTelemetry Python

**Comment by ocelotl** [comment]
I support

**Comment by lzchen** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @nstawski!
