### ISSUE TITLE
Restore the  Wednesdays 9am PT Collector SIG meeting on the OpenTelemetry Calendar

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/community#1790]
@sirianni noticed today that the reoccurring Wednesdays 9am PT Collector SIG meeting is missing from the OpenTelemetry calendar:

(This screenshot is in MT)
<img width="1308" alt="image" src="https://github.com/open-telemetry/community/assets/12352919/c5289f86-df2d-4621-94ee-01aa4ecc9187">

**Comment by trask** [comment]
@TylerHelmuth what month is this (Nov 10 is not a Wed)?

this is what I see (which is also odd):

![image](https://github.com/open-telemetry/community/assets/218610/fd3b0f0d-23ac-47fa-8fd9-5f4dab2b4315)

**Comment by trask** [comment]
I think I've fixed them up through the end of the year, let me know if you still see anything weird. We should be on the new calendar by then (#1788).

**Comment by TylerHelmuth** [comment]
Apparently I was looking at Jan 2024 without realizing it, although I don't believe @sirianni was.  @sirianni can you confirm you see the correct meetings for Nov and Dec 2023?  I do.

**Comment by sirianni** [comment]
For Nov 15th I see `Collector SIG` meetings at both 12PM and 7PM ET.
