### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector/opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1792]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib

### Requested changes

The following changes are needed:
1. ensure the renovate app (and *not* forking renovate) is setup
2. ensure branch protection rules for renovatebot/ branches are setup to allow them to be updated https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-renovate
 
### Purpose

The collector repository would like to switch from dependabot for dependency management to renovatebot. 
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/collector-contrib-maintainer 
- @open-telemetry/collector-maintainers

**Comment by bogdandrutu** [comment]
To unblock your work @codeboten I will give admin right away, but if I remember correctly we don't do this permanently. I may be wrong.

**Comment by bogdandrutu** [comment]
I don't know how to read, this is about `renovate` not admin role :))

**Comment by codeboten** [comment]
@bogdandrutu even with admin permissions i dont think i can configure github apps for the repo (i think this requires org level permissions)

happy to setup branch protection permissions though if you give me admin permissions temporarily
