### ISSUE TITLE
KubeCon+CloudNativeCon EU 2024 - OTel's activities

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1795]
Reference: https://github.com/open-telemetry/community/issues/1455

This issue tracks the planned activities around OTel for KubeCon+CloudNativeCon EU 2024. Feel free to create sub-tasks to this one to discuss new ideas.

- [x] #1796
- [x] #1799
- [x] #1798
- [x] #1800
- [x] #1801
- [x] #1804
- [x] #1818

**Comment by cartersocha** [comment]
I feel like the second might be a good panel @svrnm. Not sure how kubecon talks work for that but if we got 3-4 services to chat about it and then I or someone else could moderate

**Comment by svrnm** [comment]
> I feel like the second might be a good panel @svrnm. Not sure how kubecon talks work for that but if we got 3-4 services to chat about it and then I or someone else could moderate

That's actually a great idea, @cartersocha! Something like "o11y included: what we learned from natively integration OpenTelemetry" or similar

Via the [CfP](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/cfp/#submission-types): _"Panel Discussion: 35 minutes of discussion amongst 3 to 5 speakers"_, but this could also be a format profiting more from being done during Observability Day (cc @austinlparker)

**Comment by cartersocha** [comment]
I can go ahead and ping some people if necessary. I’m guessing we’d need speakers lined up for the proposal? Initial thought is to start with nginx, tyk, and VMware

**Comment by svrnm** [comment]
@cartersocha moving this to a separate issue: https://github.com/open-telemetry/community/issues/1810

**Comment by svrnm** [comment]
@jpkrohling with the CfP ending soon, how are we handing in ContribFest, Maintainers Track, etc, do they go through the normal CfP Process or is there a "special" route?

**Comment by jpkrohling** [comment]
They are due at a later date and are part of a special CFP.

**Comment by svrnm** [comment]
> They are due at a later date and are part of a special CFP.

Thanks for clarifying, let me know if you need some help anyways, e.g. for writing some of the abstracts, etc.

**Comment by danielgblanco** [comment]
For Observability Day, I would love to see a panel discussion on OTel adoption within end-user organisations. Challenges, success stories, status, etc. Perhaps something the end-user group can help with, but I'd be happy hosting as well. However, I also think the panel that @svrnm proposed above would be awesome. Can we submit both?

**Comment by svrnm** [comment]
@danielgblanco having a (second) panel with end-users is definitely something we should have. If we have both (integrations & end-users) it also helps to see the differences and commonalities in challenges 👍

**Comment by danielgblanco** [comment]
Cool. I'll create an issue for it and get the ball rolling. I have some ideas of other end-users at different stages of their OTel journey that may be interested in joining.

**Comment by jpkrohling** [comment]
I'll try to get a couple of people I know in touch with you as well. @reese-lee might also be able to help her.

**Comment by jiekun** [comment]
With the conclusion of KubeCon Europe, this issue can now be closed. Thank you very much to everyone who participated, it was great to see you all in person.

// Do we plan to host similar activities at KubeCon NA in a new issue (also some events related to observability and OpenTelemetry)?
