### ISSUE TITLE
KubeCon+CloudNativeCon EU 2024 - Contribfest

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1796]
Contribfest during KubeCon+CloudNativeCon NA 2023 was a success and we want to repeat that for EU 2024: https://opentelemetry.io/blog/2023/contribfest-na/

This issue is to track the activities related to this event. So far, the following people volunteered to be the official speakers at the event. The first five people to volunteer are selected and are expected to receive free tickets if the session is selected.

Official speakers (will get free tickets if the session is selected):
* @Kielek (.NET)
* @yuriolisa (Operator)
* @trask (Java and Semantic Conventions)
* @pichlermarc (JS)
* @JamieDanielson (JS)

Other volunteers:
* @jpkrohling (Collector)
* @svrnm (Docs)
* @pellared (Go)
* @dyladan (JS)
* @MikeGoldsmith (Go SDK & Go auto instrumentation)
* @djaglowski (Collector)

Tasks

- [x] #1797
- [ ] KubeCon+CloudNativeCon EU 2024 - Contribfest - Confirm speakers
- [ ] KubeCon+CloudNativeCon EU 2024 - Contribfest - Triage issues
- [ ] KubeCon+CloudNativeCon EU 2024 - Contribfest - Prepare presentation

**Comment by svrnm** [comment]
Count me in for Docs :-)

**Comment by jpkrohling** [comment]
We are five now, but people should continue to volunteer. I might step out of this one, allowing someone else to join and get a free ticket, as I might get a free ticket through a different avenue already.

**Comment by trask** [comment]
please add me as a backup, for Java and Semantic Conventions, thx

**Comment by svrnm** [comment]
Regarding https://opentelemetry.io/blog/2023/contribfest-na/ (cc @codeboten)

> The session began with 53 open issues, and by the end of the session, 2 pull requests had already been merged with another 11 pull requests having been opened.

By any chance did we tag those PRs / issues worked on during contribfest? (a) we could update the blog post with them and (b) it could help us to compare the numbers year-by-year if we continue doing contribfests

**Comment by TylerHelmuth** [comment]
@svrnm yes the issues/prs are tagged with the `Contribfest` label

**Comment by pellared** [comment]
You can add me as backup for Go. I could even help without getting a ticket. I hope I will get it somehow 😉

**Comment by dyladan** [comment]
I'm also happy to volunteer again. I really enjoyed participating in Chicago. I'm a JS maintainer but can also help in other areas if needed.

**Comment by svrnm** [comment]
Per my comment on the maintainers track (https://github.com/open-telemetry/community/issues/1799#issuecomment-1815949342), I am open to to do that as a main speaker instead of contribfest, although I am still keen to participate to make sure Docs are represented :-)

**Comment by dyladan** [comment]
I think we should probably try to minimize speaker overlap between contribfest and the maintainer track in order to maximize the number of people who get speaker tickets.

>The first five people to volunteer are selected and are expected to receive free tickets

I'm curious where the people listed in the issue volunteered? It seems like 4 of the 5 slots were already filled when this issue was created. I'm also not sure that taking the first 5 is necessarily the best way to maximize the speaker tickets. Anyone should of course feel welcome to help out, but we may want to prioritize people who might not be able to attend otherwise.

**Comment by djaglowski** [comment]
I reached out to @jpkrohling to express interest, since he organized the previous one. Coincidentally it was just after he posted this issue.

**Comment by pichlermarc** [comment]
I'd also be happy to volunteer (JavaScript SIG) 🙂

**Comment by jpkrohling** [comment]
> I'm curious where the people listed in the issue volunteered? 

I discussed the idea of doing a ContribFest again with a few folks before opening this issue, and they expressed interest in being part of it. That's why there were a few people listed here already by the time I created this issue.

> I'm also not sure that taking the first 5 is necessarily the best way to maximize the speaker tickets.

Good point, I didn't spend much time thinking about the options we had. Perhaps we could have had a community vote, where people would select the SIGs that should be represented?

> we may want to prioritize people who might not be able to attend otherwise

Absolutely: I mentioned in private already, but like @svrnm, I might get a ticket some other way, so I'll step down from this session here, while still informally helping out.

To set the expectations right: there's no guarantee that our ContribFest proposal will be accepted.

**Comment by svrnm** [comment]
> Good point, I didn't spend much time thinking about the options we had. Perhaps we could have had a community vote, where people would select the SIGs that should be represented?

Since I have not been at KubeCon NA and the first contribfest and only know it from pictures via @codeboten's blog post (https://opentelemetry.io/blog/2023/contribfest-na/), an idea that might not work: the 5 people being named as official speaker are (a) organizing this event and (b) serve as moderators, but there will be other SIG maintainers as well representing their SIG and helping people with their specific issues. For example, all SIGs that want to be included tag issues with "contribfest" and at least one maintainer/approver is available to help during that 90 minutes. From the pictures it looks like there have been 7 tables and plenty of space(?), so even if there are 5 "named main speakers" and 5 other maintainers, that should work?

**Comment by MikeGoldsmith** [comment]
Throwing my hat in to say I'm interested in helping with this session too. I can help with Go SDK & Go auto instrumentation issue management / preparation.

**Comment by codeboten** [comment]
> which follows a template we make that describes not only how to set up the repo

@dyladan i would expect this to be documented in CONTRIBUTING.md :D

**Comment by pellared** [comment]
I guess that for most repos using GitHub Codespaces and following `CONTRIBUTING.md` should be the fastest way to setup a development environment.

**Comment by dyladan** [comment]
Yes but I think we can add contribfest-specific things targeted specifically to new contributors. We can link out to CONTRIBUTING.md for setup and stuff, but there are also some contribfest-specific FAQs that I think we can cover.

**Comment by codeboten** [comment]
> Yes but I think we can add contribfest-specific things targeted specifically to new contributors. We can link out to CONTRIBUTING.md for setup and stuff, but there are also some contribfest-specific FAQs that I think we can cover.

That's fair, I guess ideally, the steps for new contributors would be well documented enough in CONTRIBUTING.md that the only additional step for newcomers is "look for contribfest label". Maybe this is a good reason to revamp the contributing doc for consistency across the project

**Comment by jpkrohling** [comment]
I updated the ticket description with the list of official speakers that I'll use for the proposal. That list is fixed, but can be changed after the session is selected if needed.

The list of volunteers is mainly for our own organization and can be changed at any time.

People who are marked as official speakers: I'll need your email addresses. Please message me in private via Slack with them.

**Comment by djaglowski** [comment]
I've secured a ticket another way so would be happy to give up my seat on this to the next person. cc: @trask

**Comment by evan-bradley** [comment]
@trask If the submission can still be modified and the spot hasn't been reserved for someone else, I am still looking for a way to get a ticket and would be happy to represent the Collector SIG at the contribfest.

**Comment by jpkrohling** [comment]
It was brought to my attention that we have a male-only proposal for this contrib fest, and I can't accept that I didn't notice this before 🤦🏽 

This means that I'll remove @djaglowski and give preference to a non-male moderator. I have a candidate in mind, and pinged her already, but if you are interested in joining, please let me know in a comment here.

**Comment by JamieDanielson** [comment]
I am interested in helping out with Contribfest! I am an approver on JS but can help in other areas as well.

**Comment by Kielek** [comment]
I have bad news about contribfest:

> We are writing to notify you that your submission for [KubeCon + CloudNativeCon Europe 2024](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe), OpenTelemetry Contribfest, has regrettably not been accepted due to the overwhelming number of submissions we received for the event. The decisions made by the program committee and co-chairs have been difficult and at this time, they can only accept a limited number of proposals.

> 
> There were several factors the program committee and co-chairs took into consideration that contributed to the final decisions on talks; including those that we were unable to accept even though they might have been highly rated. Some of these include:

> 
> Multiple talks on the same topic for the same track
> Limited session slots within a specific track
> Receiving 11x the number of talks for which we had space

**Comment by jpkrohling** [comment]
That's a bummer, but we'll try again next time. Thank you for the updates, @Kielek.
