### ISSUE TITLE
KubeCon+CloudNativeCon EU 2024 - Contribfest - Submit proposal

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1797]
This is KubeCon NA 2023 proposal text:

> Join the OpenTelemetry maintainers in making OpenTelemetry better for everyone. OpenTelemetry will have several opportunities to contribute. The OpenTelemetry Collector is vendor-agnostic implementation for receiving, processing and exporting telemetry data. The Collector is a large ecosystem, including individual components, a telemetry transformation language, helm charts, and a Kubernetes operator. Join the Collector maintainers and help fix bugs, add new features, and add new transformation functions. OpenTelemetry JavaScript is an OTel client written in typescript which supports traces, metrics, and logs, but an observability client is only as good as the telemetry it collects. Help the OTel JS maintainers update the instrumentation libraries and ensure they are outputting semantic convention-compliant telemetry data.

Once we have a complete list of volunteers to run the session, we can adapt the above.

**Comment by jpkrohling** [comment]
Suggested description:

> Join the OpenTelemetry maintainers in making OpenTelemetry better for everyone. OpenTelemetry will have several opportunities to contribute, as we'll have maintainers and approvers from different SIGs, including Collector, JavaScript, Go, .NET, OTel Operator, Docs, and likely more!

Additional notes:
> We had a very successful ContribFest in Chicago, with more than 10 pull requests being created during the event. Everyone got so excited about the results from Chicago that we have more maintainers now committing to joining a ContribFest in Paris.
Tracking issue: https://github.com/open-telemetry/community/issues/1796

Speakers:

- @Kielek (.NET)
- @yuriolisa (Operator)
- @djaglowski (Collector)
- @trask (Java and Semantic Conventions)
- @dyladan (JS)

When trying to create the session, I can only add four other co-speakers. Therefore, it would be best if another GC member (@trask? @dyladan?) also participating in the session could create the proposal.

**Comment by trask** [comment]
Proposal submitted
