### ISSUE TITLE
KubeCon+CloudNativeCon EU 2024 - OTel Observatory

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1798]
This ticket is to evaluate whether the Observatory was successful in 2023 and whether we'd want to encourage vendors to collaborate on having it again.

**Comment by jpkrohling** [comment]
@austinlparker, @mtwo, you were closely involved on this, would you please provide some comments on this? I think it would be REALLY cool to have it again, but perhaps you have different opinions?

**Comment by svrnm** [comment]
https://opentelemetry.io/blog/2023/contribfest-na/ via @codeboten 

> The session began with 53 open issues, and by the end of the session, 2 pull requests had already been merged with another 11 pull requests having been opened.

By any chance did we tag those PRs / issues worked on during contribfest? (a) we could update the blog post with them and (b) it could help us to compare the numbers year-by-year if we continue doing contribfests

**Comment by djaglowski** [comment]
I think we should definitely try to do something like this at future conferences. Personally, I found it to be a comfortable place to hang around during downtime, which lead to many productive conversations with both users and other community members.

**Comment by TylerHelmuth** [comment]
The Observatory was a huge success in my mind.  It was an excellent default place to meet with other community members and have conversations.

Some feedback for next time:
- Include a TV so we can do "proper" booth duty with the OTel demo.  While the Observatory was incredible for existing community members, I think we saw less user engagement once we shut down the proper booth. The booth provided a clear "go here and ask the people standing around a question" space, but the Observatory did not. The Observatory needs a proper, standing, attendee-facing section where we can staff a "booth" for users to ask questions.
- A more official "schedule" that is easier for attendees to find.

**Comment by mtwo** [comment]
+1 to the comments here, I thought that it was great! I had the same takeaways as @TylerHelmuth: having a more visible schedule (perhaps on a screen or e-ink panel or something up front) and a dedicated mini space for people walking past would make it even better.

Regarding costs, I already have the money to do it again in NA next year, still need to find out about EU. My events team is telling me that the costs will be substantially lower if we want to use the same design with minor tweaks; apparently much of the build cost this year was for design.

**Comment by mtwo** [comment]
Also, someone at the conference had made a (not entirely serious) suggestion about using one of the flippy letter signs popular in train stations to show what sessions are on now, and which are up next. It turns out that these are much cheaper than I'd thought and are possibly an option.

**Comment by jpkrohling** [comment]
@mtwo is Splunk open to share the costs with other vendors? NA and EU.

**Comment by mtwo** [comment]
@jpkrohling I'll find out, might take a few weeks given that we just got back, budget planning, and with the upcoming Thanksgiving holiday in the USA

**Comment by MikeGoldsmith** [comment]
I'm willing to help organise and contribute running the observatory again.

**Comment by mtwo** [comment]
Marike just let me know that we've secured the budget for this, both for Paris and Salt Lake City! We didn't have certainty about getting the money again (particularly for Paris), which spurred the conversation about co-sponsoring, but we're good to go now.

Now that the budget is secured, we (the community / people commenting on this issue) need to decide the layout, appearance, and programming of the Observatory. From comments on this issue and at Kubecon, my impression is that we want to pursue a similar layout to Chicago (helps with the budget and I think that we were generally happy with it) with some improvements:

- Adding a more visible schedule and posting the schedule online.
- Adding a board or screen that highlights what event is happening now / next (perhaps a split-flap display).
- Some affordance for people who want to come up to learn more about OpenTelemetry, similar to the purpose that the project booth serves. This could be a designated area within the Observatory, or people wearing t-shirts that indicate that they're able to talk, or something else.
- In Chicago we'd originally planned to put the GitHub handles of the top ~100 contributors onto the back of the booth, but we ran out of time to implement this. Might be a nice idea in the future.

Who wants to be involved in organizing this? @austinlparker did all of the programming in Chicago and it was great, and I see @MikeGoldsmith. Anyone else?

**Comment by bshetti** [comment]
@mtwo sounds awesome. The Observatory was a nice event. Just clarifying - based on the statement above - The observatory is a Splunk sponsored only event? Asking because it seems that its also a community driven event at Kubecon but only sponsored by Splunk vs multiple sponsors making it more community driven.

**Comment by mtwo** [comment]
Same as Chicago: it's a community-run space, Splunk is just paying the bill. I'd had some concerns about whether I could secure the money for it, which is why we had a few chats about co-sponsorship while we were in Chicago.

**Comment by bshetti** [comment]
Thanks.

**Comment by danielgblanco** [comment]
I'm closing this, considering KubeCon EU 2024 is now complete and we've had great participation with Q&As, interviews, and end-user feedback sessions. We even had some nice OTel lab coats!! (thanks @austinlparker!) Thanks to all for contributing and participating!
