### ISSUE TITLE
REQUEST: New membership for Erlang SIG

### ISSUE THREAD

**Issue by deadtrickster** [open-telemetry/community#18]
This follows up gitter discussion and echoes https://github.com/open-telemetry/community/issues/17.

I and @tsloughter maintain https://github.com/census-instrumentation/opencensus-erlang and https://github.com/opencensus-beam. 

What's the best way to participate? Looks like SIG?

**Comment by SergeyKanzhelev** [comment]
If you plan to create some regular sync-ups and you believe there will be enough interest to justify SIG - one definitely can be created. If not - perhaps repo maintenance can be a good starting point. Let us know if you want to bootstrap SIG.

Are you up for the challenge to maintain OpenTelemetry Erlang repo?

**Comment by SergeyKanzhelev** [comment]
https://github.com/open-telemetry/community/pull/19

**Comment by tsloughter** [comment]
We are creating a related working group (observability/telemetry) as part of the new Erlang Ecosystem Foundation, https://erlef.org/, and will be having regular sync ups as part of that. I'm not sure if that would mean we should have a SIG or not -- if it was an option to sort of combine them then it would make sense, but in my opinion if we already have to have sync ups, write ups, minutes in the foundation WG it would be better to not have to essentially duplicate that work.

What do you think @deadtrickster ?

And, hoping I can get a nomination as well? :)

**Comment by deadtrickster** [comment]
If creating SIG later is an option, we can start with repo maintenance and see how it goes in erlef.org side.

Please invite Tristan too :-)

**Comment by SergeyKanzhelev** [comment]
@tsloughter I'm in reactive mode =) added to the nomination.

If you want to refer to that working group from this repo readme file - it's totally cool. Just send a PR. Perhaps not under SIGs header - create a separate section of "related groups"

**Comment by SergeyKanzhelev** [comment]
closing this issue, I think membership, nomination and SIG creation are tracked in separate issues or resolved
