### ISSUE TITLE
KubeCon+CloudNativeCon EU 2024 - Noise monitoring

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1800]
During KubeCon NA 2023, I was talking to @codeboten about how noisy the booth crawl was, and we had an idea: spread Sound Level Meters around the sponsor showcase, collecting metrics and sending them in OTLP format to the backends of vendors. They can then showcase how that data looks on their solutions.

- [ ] Buy or build a Sound Level Meters
- [ ] Make it spit out OTLP
- [ ] Have a Collector that receives this data
- [ ] Recruit vendors
- [ ] Have a page somewhere listing all the vendors

**Comment by codeboten** [comment]
im 100% interested in hacking on this :D

**Comment by djaglowski** [comment]
Wouldn't it be reasonably easy to also capture traces and logs from any application we write to collect the metrics?

**Comment by jpkrohling** [comment]
> A raspberry pi/arduino solution isn't gonna be that much less expensive I'd think, and would require assembly, but the bespoke option would at least give us some more flexibility

That's what I had in mind. The advantage of Raspberry Pi is that we can use a language we already support to instrument the application. The components aren't going to be that expensive if we focus on the sound level for now: it's the Pi's price (~70 with a case?) plus ~20 EUR for the sensor.

I can certainly get the value for one of those expensed by my employer, and if each one of the involved vendors can pay for their hardware, we can collaboratively work on the software.

**Comment by MikeGoldsmith** [comment]
Ditto, happy to help contribute to this. I think it would be super cool for the data to be available for anyone to use, including for demos on the exhibition floor.

**Comment by jpkrohling** [comment]
This was a good idea and I think we should be doing this, but I wasn't able to allocate time to build it :-(
