### ISSUE TITLE
KubeCon+CloudNativeCon EU 2024 - OTel Sucks

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1801]
During one of the sessions at KubeCon, @codeboten had this idea of having a "OTel Sucks" talk, in the same format as "Linux Sucks" that's been highly popular.

https://youtu.be/puZVqV1xstU?si=7gb9hkTPDBj279Qn

- [ ] Recruit volunteers to deliver this talk
- [ ] Collect ideas from users on what's bad about OTel, and what's good
- [ ] Prepare the presentation, with a dry-run closed to maintainers

**Comment by jpkrohling** [comment]
@codeboten, would you like to follow-up on this one? If so, I'll assign this to you[

**Comment by atoulme** [comment]
I'd be happy to help.

**Comment by codeboten** [comment]
@jpkrohling my recollection of the conversation is that you had the idea :D i won't be at kubecon EU, but will be happy to take this on if no one has by salt lake :)

**Comment by atoulme** [comment]
Same, I thought @jpkrohling was enchanted with this idea. I assume there'll be plenty of things to comment on for both EU and US conferences.

**Comment by jpkrohling** [comment]
I might have said out loud first, but you all tricked me into doing it! 

It's likely too late for Paris now, given that the CFP has closed and I have two proposals lined up for Observability Day already. Perhaps another maintainer would like to propose this for Observability Day?

**Comment by cartermp** [comment]
@jpkrohling happy to funnel you various feedback items I've seen over time. There's quite a lot :D

**Comment by jpkrohling** [comment]
@yurishkuro has mentioned he'd be interested in having something similar as well. Perhaps you both could collaborate on a presentation, @cartermp?

**Comment by cartermp** [comment]
I would also say that we should have any such talk also have a short section about "and this is what we're looking to make better" or something like that.

**Comment by jpkrohling** [comment]
The original Linux Sucks has half of it being about ways Linux has deceived its users, and about half of it on how it's still awesome. We should definitely follow this format.

**Comment by svrnm** [comment]
just curious, was an otel sucks talk proposed for kubecon/o11yday now?

**Comment by jpkrohling** [comment]
Not to my knowledge. But we should keep track of this for NA 2024.

**Comment by jpkrohling** [comment]
I'm closing this, as this wasn't proposed for EU 2024. I'll open a new one for NA 2024.
