### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java*

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1807]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-java
https://github.com/open-telemetry/opentelemetry-java-instrumentation
https://github.com/open-telemetry/opentelemetry-java-contrib
https://github.com/open-telemetry/opentelemetry-java-examples

### Requested changes

Re-enable Renovate on the above repositories.

### Repository Maintainers

- @open-telemetry/java-maintainers
- @open-telemetry/java-instrumentation-maintainers
- @open-telemetry/java-contrib-maintainers

**Comment by bogdandrutu** [comment]
The app is enabled. What do you see that makes it not enabled? Also do you use "forking" version?

**Comment by bogdandrutu** [comment]
Per slack conversation, this is fixed.
