### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-js-contrib

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/community#1814]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-js-contrib

### Requested changes

- Give write permissions to @opentelemetrybot
- Create a fine-grained PAT for @opentelemetrybot to create PRs and Releases on the https://github.com/open-telemetry/opentelemetry-js-contrib repository
  - I'm not sure if stating the required scopes should be public, feel free to reach out to me on the CNCF slack to discuss details.
 
### Purpose

We currently have a [workflow that's creating release PRs and releases](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/release-please.yml) via the [release-please-action](https://github.com/google-github-actions/release-please-action) and predates the creation of the @opentelemetrybot account. We'd prefer switching to using the bot account so that PRs and releases authored by the automation be properly identified as such.
 
### Expected Duration

permantenly

### Repository Maintainers

- @open-telemetry/javascript-maintainers

**Comment by trask** [comment]
cc @open-telemetry/technical-committee

**Comment by jack-berg** [comment]
Thanks for the ping @trask. Based on this [doc](https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot), it seems like all that is needed for the @open-telemetry/javascript-maintainers to use @opentelemetrybot to create PRs and releases is to grant the `opentelemetry-js-contrib` repo access to the `OPENTELEMETRYBOT_GITHUB_TOKEN`.

However, @pichlermarc requests granting additional permissions to @opentelemetrybot and creating a fine-grained PAT. Why the need for the additional permissions and the separate fine-graned PAT?

**Comment by pichlermarc** [comment]
> Why the need for the additional permissions and the separate fine-graned PAT?

Sorry for the (very) late reply. :fearful: 

We were planning to continue using the https://github.com/google-github-actions/release-please-action, which automatically creates a release PR and the releases in GitHub.

In order for @opentelemetrybot to create these releases, I was under the impression that bot user would need write access for releases in the repository. Due to that additional access, I saw using a fine-grained PAT (scoped to the js-core repo only) as the more secure option.

However, reading https://github.com/open-telemetry/community/issues/1549#issuecomment-1653877770 and the [python SIGs release workflow](https://github.com/open-telemetry/opentelemetry-python/blob/main/.github/workflows/release.yml), it looks like we might actually be able to do this without giving the bot additional access. We'll likely be able to use the `OPENTELEMETRYBOT_GITHUB_TOKEN` to create the release PR, and then the usual `GITHUB_TOKEN` to create the release. 

Let's try with just access to `OPENTELEMETRYBOT_GITHUB_TOKEN` first. I think you're right @jack-berg, just using that should work fine :slightly_smiling_face:

**Comment by jack-berg** [comment]
Ok @pichlermarc - I'm sorry for my late reply as well. I'm going to go ahead and close this because it looks like we can get away with using `OPENTELEMETRYBOT_GITHUB_TOKEN`. Happy to re-open if I'm misunderstanding.
