### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-rust(-contrib)

### ISSUE THREAD

**Issue by hdost** [open-telemetry/community#1815]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-rust
https://github.com/open-telemetry/opentelemetry-rust-contrib

### Requested changes

Give 'Admin' permissions @open-telemetry/rust-maintainers 

We will abide by:
> If requested, foo-maintainers will be granted Admin permissions, and in return they must document any changes they make to the repository settings in a file named .github/repository-settings.md in their repository (other than temporarily disabling "Do not allow bypassing the above settings", see branch protection rules below)
Source: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams
 
### Purpose

We are looking to make a few modifications to our repo settings to match with our working style.  Review process and open up the ability to 
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/rust-maintainers

**Comment by bogdandrutu** [comment]
We would prefer to not give permanent Admin power unless there is a strong argument. I can give temporal permission if you still need it.

**Comment by trask** [comment]
> We would prefer to not give permanent Admin power unless there is a strong argument

@open-telemetry/technical-committee we can definitely revisit the policy (especially as part of #1596), but I don't believe we have been requiring justification for admin rights since #1311

**Comment by jack-berg** [comment]
> @open-telemetry/technical-committee we can definitely revisit the policy (especially as part of https://github.com/open-telemetry/community/issues/1596), but I don't believe we have been requiring justification for admin rights since https://github.com/open-telemetry/community/pull/1311

Agreed - there's precedent for this request and a documented process. 

> Review process and open up the ability to

@hdost can you elaborate on the settings you intend to change? Perhaps open a draft PR of the `.github/repository-settings.md` the repo will ultimately need to maintain.

**Comment by jack-berg** [comment]
@hdost just following up on this, and reiterating that repos with admin access need to document their settings in `.github/repository-settings.md`.

**Comment by hdost** [comment]
I think we can closed this as the thread was duplicated over here https://github.com/open-telemetry/community/issues/2021
