### ISSUE TITLE
Rust SIG Meeting

### ISSUE THREAD

**Issue by hdost** [open-telemetry/community#1816]
After a recent discussion in #otel-rust we've decided to change our meeting time to (9am US Pacific) which translates typically to 6PM CET

cc: @open-telemetry/rust-maintainers

**Comment by trask** [comment]
hi @hdost! can you follow https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#gaining-calendar-permissions to get access to update the calendar entry, and send a PR to update the time at https://github.com/open-telemetry/community#special-interest-groups?

**Comment by hdost** [comment]
> hi @hdost! can you follow https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#gaining-calendar-permissions to get access to update the calendar entry, and send a PR to update the time at https://github.com/open-telemetry/community#special-interest-groups?

I've now requested access to the calendar.

**Comment by hdost** [comment]
Also, I did notice the comment about creating a zoom so I would like to request that as well, I don't think I can do that.

**Comment by trask** [comment]
> @trask Is there a regular review of requests to access?

sorry, looks like we missed the notification for your request, I've approved the request now

> Also do I need a new ticket for this.
> 
> > Adding a Zoom link to a meeting
> 
> > Open an issue in the community repository, requesting a new Zoom link. By requesting a new Zoom link that is only associated with a single meeting series, the meeting recordings can be associated with a meeting name. The Zoom link will be created in one of the 5 OpenTelemetry Zoom account. A single Zoom account should not be used for back-to-back meetings or for more than two meetings at the same time. You can see which Zoom account any potentially conflicting meetings are using in the meeting descriptions. (Note: posting the URLs publicly on GitHub leads to Zoom bombing by random bots).

It looks like you already have a (unique) Zoom link for Rust. The Zoom links aren't tied to any specific time (only to a specific SIG).

**Comment by hdost** [comment]
I've updated the calendar but the the zoom link on the even I confirmed is on Meet Room #1

Maybe the zoom room exists but I don't have a reference to it.

**Comment by trask** [comment]
The zoom link on the event looks correct, maybe I'm not understanding what you're looking for?

**Comment by hdost** [comment]
Ah i guess I thought there were dedicated zoom meetings that were being setup per SIG now.
