### ISSUE TITLE
 KubeCon+CloudNativeCon EU 2024 - OTel End-User Panel Discussion

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#1818]
I'd like to propose a panel for Observability Day (although I left the title as KubeCon+CloudNativeCon so it's easier to find it among other activities part of #1795), getting end-users from different companies to tell us about their experiences adopting OTel: challenges, success stories, deployment patterns, etc

I volunteer to put together the CFP submission and to be either host or participant of the panel.

**Comment by danielgblanco** [comment]
Confirmed @IrisDyr (Farfetch) would be up for participating in the panel, thank you! 🎉 Still trying to confirm a couple more people.

**Comment by danielgblanco** [comment]
Confirmed @SodaDev (Ryanair) would also like to participate, thanks! Looking forward to it.

**Comment by danielgblanco** [comment]
I'm thinking, considering my experience as an OTel practitioner and my lack of experience as a host/moderator, that it'd be a better idea to try to find a moderator (ideally non-vendor) to help us with this. If anybody has any recommendations please reach out to me.

**Comment by svrnm** [comment]
Would be great if someone from the @open-telemetry/end-user-wg can help with moderating?

**Comment by reese-lee** [comment]
Ok I've shared this issue and asked them to respond to this issue directly if they're able to do it. I have a couple others in mind if they aren't able to.

**Comment by IAMebonyhope** [comment]
I am happy to help with moderating the panel.

**Comment by danielgblanco** [comment]
Thanks for supporting it @mhausenblas and @IAMebonyhope! Hard to choice to make as you'd both be awesome moderators, but considering @mhausenblas may also be organising another panel at KubeCon (fingers crossed that's accepted) makes @IAMebonyhope the most logical choice!

I think that closes it for now with @IAMebonyhope (Microsoft) as moderator and @IrisDyr (Miro), @SodaDev (Ryanair) and @danielgblanco (Skyscanner) as participants. I will coordinate with you over Slack to get the CFP submitted (I'll submit it).

**Comment by jpkrohling** [comment]
I don't see this on the schedule, I think this wasn't selected, right? I'm closing this issue, but we should definitely coordinate a new one for NA 2024. Or perhaps even part of Observatory?
