### ISSUE TITLE
REQUEST: New membership for greatestusername

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/community#1819]
### GitHub Username

@greatestusername

### Requirements

- [X ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X ] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

[@atoulme](https://www.github.com/atoulme)
[@shalper2](https://www.github.com/shalper2)
[@MovieStoreGuy](https://github.com/MovieStoreGuy)

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+is%3Aclosed+author%3Agreatestusername
- Issues responded to: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+author%3Agreatestusername+is%3Aclosed
- SIG projects I am involved with: 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/webhookeventreceiver
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/splunkenterprisereceiver

**Comment by shalper2** [comment]
I support

**Comment by greatestusername** [comment]
Just realized I need one other sponsor from outside of my company. Contacting them with this issue so leaving it open and will add them once they've agreed to sponsor.

**Comment by MovieStoreGuy** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @greatestusername!

**Comment by greatestusername** [comment]
Thank you @arminru !
