### ISSUE TITLE
REQUEST: Repository maintenance on Collector repositories

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/community#1826]
### Affected Repository

At a minimum, I have verified these two repositories need modifications:
https://github.com/open-telemetry/opentelemetry-collector-contrib
https://github.com/open-telemetry/opentelemetry-collector-releases

I have confirmed that non-Collector repositories may be impacted by this as well.

### Requested changes

Please add the OpenTelemetry organization member group as collaborators to these repositories with "read" permissions.

I believe the group was previously included as a collaborator but that this access was removed somehow, as the behavior I expect has changed recently.
 
### Purpose

I am currently unable to assign issues to non-participants or request reviews from OpenTelemetry organization members. We also depend on automations that leverage GitHub's APIs to perform these actions.
 
### Expected Duration

Permanently.

### Repository Maintainers

@open-telemetry/collector-contrib-maintainer

**Comment by trask** [comment]
hi @evan-bradley! I don't believe there's a team that includes all OpenTelemetry org members. I think other repos are using a `@open-telemetry/*-triagers` group for this purpose, e.g. [@open-telemetry/java-contrib-triagers ](https://github.com/orgs/open-telemetry/teams/java-contrib-triagers). Would something like that work for your needs? thx

**Comment by TylerHelmuth** [comment]
Chiming in to say this is really annoying.  I want to assign some open-telemetry org members to a PR but cant.

Do other CNCF organizations have this problem/restriction?

**Comment by trask** [comment]
> Chiming in to say this is really annoying. I want to assign some open-telemetry org members to a PR but cant.

looks like @open-telemetry/technical-committee is going to discuss options this week (https://github.com/open-telemetry/community/issues/1715#issuecomment-1852242513)

**Comment by TylerHelmuth** [comment]
Did this end up getting discussed? Not being able to assign OpenTelemetry Org members to Collector Contrib PRs breaks our automation and if we don't have a resolution in sight we'll need to update our automation to go back to pinging code owners.

**Comment by trask** [comment]
@open-telemetry/technical-committee @cartersocha can we revert #1715 for now until we figure out path forward?

**Comment by bogdandrutu** [comment]
Is this caused by:

![Screenshot 2023-12-21 at 10 08 47 AM (2)](https://github.com/open-telemetry/community/assets/1373887/e39ada9a-0e0f-4427-9980-777004f8576f)
<img width="1728" alt="Screenshot 2023-12-21 at 10 08 47 AM" src="https://github.com/open-telemetry/community/assets/1373887/f2464a47-59eb-42bd-816d-d9ce9d469666">

**Comment by cartersocha** [comment]
We're good to revert the default / base permissions to "read" but I think someone from the TC will need to create the separate org and repo for storing the incident data then give me access to port over the Grafana tracking

**Comment by jack-berg** [comment]
> Did this end up getting discussed?

Yes, but there wasn't a resolution. See this related blurb in the [maintainers meeting notes](https://docs.google.com/document/d/14lBtLAdzsV7M8xQNdhTJ0d2PxM1R7FByw-GttKJzVVw/edit):

> Default Github privileges problem: the way Security reporting is handled, created technical difficulties (e.g., for assigning CODEOWNERs), We discussed a couple of high-level solutions, and concluded that a little more research should be done.  Likely our best solution is to create a separate Github owned by CNCF to receive and organize security reports.

**Comment by arminru** [comment]
We're currently trying out an alternative to the setting introduced in #1715, and if it all works out well, we should be able to revert the setting in https://github.com/open-telemetry this week to resolve the issue reported here.

**Comment by arminru** [comment]
Our alternative approach worked out.
I enabled "Read" as the base permission on https://github.com/open-telemetry, so your workflows (both automated and manual) for assigning issues/PRs and requesting reviews should work again.

@evan-bradley please let me know if it works as expected.

**Comment by arminru** [comment]
It's in a separate org (also owned by the CNCF and under the enterprise account) now and all repos in https://github.com/open-telemetry/ are public anyway so having "Read" as base permissions there is fine.

**Comment by TylerHelmuth** [comment]
I saw the automations in contrib working today as expected

**Comment by evan-bradley** [comment]
I've tested it as well and this resolved the issue. Thank you!
