### ISSUE TITLE
Enable AllStars across OpenTelemetry organisation

### ISSUE THREAD

**Issue by sakshi-1505** [open-telemetry/community#1831]
# What?

We need to install/enable Allstar application across our organisation https://github.com/ossf/allstar.

# Why?

Sig-Security is implementing auditing & security best-practices for the Otel organisation; to ensure certain checks & consistency across all the repository in our organisation, we need to install Allstar & enforce certain policies. See https://github.com/open-telemetry/sig-security/issues/12, https://github.com/open-telemetry/sig-security/issues/21

# When?

We would prefer to get it install as soon as possible since we will have opt-in configuration for now which means it won't be enabled across the org's repositories but at the places over which we would have defined the configuration.

**Comment by sakshi-1505** [comment]
cc: @jpkrohling @codeboten

**Comment by svrnm** [comment]
Thank you for driving this @sakshi-1505!

**Comment by bogdandrutu** [comment]
No idea about this product, happy to enable this if we have couple of the security-maintainers approving (+1) this.

**Comment by trask** [comment]
cc @open-telemetry/sig-security-maintainers

**Comment by cartersocha** [comment]
This is a known project to sig-security as part of the outreachy internship. Ping @jpkrohling

**Comment by codeboten** [comment]
Thanks for opening the issue @sakshi-1505! @cartersocha @jpkrohling can you reply here with "I approve" 😬

**Comment by cartersocha** [comment]
I approve

**Comment by svrnm** [comment]
@sakshi-1505 can you provide some details what is required to roll out allstar? Do you have a suggestion, if using a dedicated repository is best, or can this be housed in the [.github repository](https://github.com/open-telemetry/.github)?

**Comment by jpkrohling** [comment]
I approve as well

**Comment by bogdandrutu** [comment]
> We need to install/enable Allstar application across our organisation https://github.com/ossf/allstar.

Enabled it for the sig-security repo, do you need for all?

**Comment by sakshi-1505** [comment]
> can you provide some details what is required to roll out allstar? Do you have a suggestion, if using a dedicated repository is best, or can this be housed in the [.github repository](https://github.com/open-telemetry/.github)?

@svrnm we can actually use either but using a dedicated `.allstar` repository would be preferred by me given that it aligns with the convention established by Allstar and can help segregate security policy management from other GitHub configurations. This would also make the setup more transparent and easier to manage, especially if the number of policies increases in future.

**Comment by sakshi-1505** [comment]
> > We need to install/enable Allstar application across our organisation https://github.com/ossf/allstar.
> 
> Enabled it for the sig-security repo, do you need for all?

@bogdandrutu We will need to enable it for all repo's ideally but for now we can limit the installation to few repos; @jpkrohling I suggest that we add otel-go & contrib-go in the first phase and if things work out fine we can enable it across the org.

**Comment by bogdandrutu** [comment]
Done. Closing this issue, please open a different one if more permissions are required (or extend the list).

<img width="816" alt="Screenshot 2024-01-16 at 1 48 21 PM" src="https://github.com/open-telemetry/community/assets/1373887/2166edf4-37a0-454a-bc10-33503661eedb">
