### ISSUE TITLE
REQUEST: New membership for @mlunadia

### ISSUE THREAD

**Issue by mlunadia** [open-telemetry/community#1834]
### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cartersocha 
- @AlexanderWert

### List of contributions to the OpenTelemetry project
- https://github.com/open-telemetry/semantic-conventions/pull/544
- https://github.com/open-telemetry/semantic-conventions/pull/543
- https://github.com/open-telemetry/semantic-conventions/issues/58
- Working with semantic-conventions wg on ECS merger.

**Comment by cartersocha** [comment]
I support

**Comment by AlexanderWert** [comment]
I support

**Comment by bogdandrutu** [comment]
Invite sent

**Comment by mlunadia** [comment]
thanks @bogdandrutu was on leave and missed the invite before it expired. Do you mind reissuing it? TIA
