### ISSUE TITLE
Proposal: GC/TC On-Call Rotation

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#1843]
To better support community issues and connect with the community, we'd like to explore the idea of having a defined on-call rotation for a single GC and TC member each week.

Responsibilities:
- Same-day (local working hours) responses to new community issues (repo maintenance, donation proposal, et. al.)
- Escalation of issues to greater GC/TC as appropriate
- Handling questions/concerns/comments to inbox

I would also suggest a weekly drop-in 'office hours' on zoom that the on-call GC/TC members would run.

To clarify, the commitment here would not necessarily be same-day _resolution_, but a same day response (i.e., "we've received your request" and dispatched the appropriate followup action, like adding it to the next TC/GC meeting agenda, etc.).

**Comment by bogdandrutu** [comment]
` donation proposal` I don't think we should do a same day response. Someone needs to do a technical due diligence.

**Comment by austinlparker** [comment]
> ` donation proposal` I don't think we should do a same day response. Someone needs to do a technical due diligence.

Ah, let me clarify - my intent is that there would be a same-day response to the issue (acknowledgement/getting it on a future agenda/whatever), not same-day resolution.

**Comment by svrnm** [comment]
> I would also suggest a weekly drop-in 'office hours' on zoom that the on-call GC/TC members would run.

If this is also within working hours of the GC/TC member, +1 for all the proposal. It makes it easier for each one of us to feel responsible to pick up an issue.

One question: Is the GC/TC member then also the "default" responsible person for the issue until it is handed over or closed? So even beyond there rotation? What I not mean by that, is that they are suddenly the goto person for a major thing like a donation or the foundation of a new SIG/WG, but it's their job to hand it off to the right person (or group), and for minor things (questions to the community, etc..) they take it to close?

**Comment by danielgblanco** [comment]
With the triaging processes we currently have (both EU and US), do we think this is still something we'd like to do?

**Comment by mtwo** [comment]
Triage notes: we're closing this as the GC triage process now covers this
