### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-java-instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1849]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-java-instrumentation

### Requested changes

Remove ciMate GitHub App.

### Purpose

We haven't been using it since https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1921.

### Expected Duration

Permanently

### Repository Maintainers

- @open-telemetry/java-instrumentation-maintainers

**Comment by jsuereth** [comment]
ciMate is uninstalled. Looks like it was only used by java-instrumentation.
