### ISSUE TITLE
Event Specification

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1863]
@tigrannajaryan and @jack-berg have volunteered to be the sponsors for this.

**Comment by jpkrohling** [comment]
@tigrannajaryan, you weren't there, so, you didn't actually volunteer for that. But people on the call told me you are involved in this already. I would appreciate it if you could confirm you are ready to be the sponsor for this with @jack-berg.

**Comment by tigrannajaryan** [comment]
Confirmed, I am already a sponsor.

**Comment by jack-berg** [comment]
Confirmed, I am already a sponsor.

**Comment by jpkrohling** [comment]
This is the project tracking the roadmap item: https://github.com/open-telemetry/community/blob/main/projects/event-api.md
