### ISSUE TITLE
File-based configuration

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1864]
@jack-berg has volunteered to be the sponsor for this.

**Comment by jack-berg** [comment]
Confirmed, @carlosalberto is listed as the TC sponsor on [community/README.md](https://github.com/open-telemetry/community/blob/main/README.md) but I've been engaging with this for a while.

**Comment by jpkrohling** [comment]
Is there a project specific to file-based config? Or is it the target of the existing project? https://github.com/open-telemetry/community/blob/main/projects/config.md

**Comment by jack-berg** [comment]
The latter is the case.
