### ISSUE TITLE
REQUEST: New membership for akats7

### ISSUE THREAD

**Issue by akats7** [open-telemetry/community#1872]
### GitHub Username

@akats7

### Requirements

- [X ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [ X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @breedx-splk 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

PRs

Collector Contrib
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28818
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29557
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30019
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21726
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22726

Java Contrib/ Instrumentation
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1102
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7557
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/960
https://github.com/open-telemetry/opentelemetry-java-contrib/issues/926
https://github.com/open-telemetry/opentelemetry-java/pull/5662

**Comment by djaglowski** [comment]
I support!

**Comment by breedx-splk** [comment]
I support!

**Comment by bogdandrutu** [comment]
Invite sent
