### ISSUE TITLE
REQUEST: New membership for @xuan-cao-swi

### ISSUE THREAD

**Issue by xuan-cao-swi** [open-telemetry/community#1873]
### GitHub Username

@xuan-cao-swi

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mwear 
- @arielvalentin

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [PRs reviewed / authored at contrib](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pulls?q=author%3Axuan-cao-swi++is%3Apr+)
- [PRs reviewed / authored at core](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=author%3Axuan-cao-swi++is%3Apr+)
- [Issues responded](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues?q=is%3Aissue+commenter%3Axuan-cao-swi+)
- SIG projects I am involved with: Ruby

**Comment by arielvalentin** [comment]
I approve!

**Comment by mwear** [comment]
I support!

**Comment by bogdandrutu** [comment]
Invite sent
