### ISSUE TITLE
Create `.allstar` repository to house Allstar policies

### ISSUE THREAD

**Issue by sakshi-1505** [open-telemetry/community#1874]
## What?

We need to enable and house our Allstar policies centrally for our projects

## Why?

Sig-Security is implementing auditing & security best-practices for the Otel organisation; to ensure certain checks & consistency across all the repository in our organisation, we need to add Allstar policies & enforce certain policies. See https://github.com/open-telemetry/sig-security/issues/12, https://github.com/open-telemetry/sig-security/issues/21

## When?

We would prefer to get it created as soon as possible

**Comment by sakshi-1505** [comment]
cc: @jpkrohling @svrnm @codeboten

**Comment by svrnm** [comment]
I assume this repo should be owned by @open-telemetry/sig-security-maintainers then?

**Comment by svrnm** [comment]
https://github.com/open-telemetry/community/issues/1831

**Comment by sakshi-1505** [comment]
> I assume this repo should be owned by @open-telemetry/sig-security-maintainers then?

Yes, it should be.

**Comment by jpkrohling** [comment]
I confirm we need this to unblock our work on the SIG Security.

**Comment by bogdandrutu** [comment]
Is this private?

**Comment by bogdandrutu** [comment]
I could not find this settings (I expect because the repo is private, so no external collaborator case). If we want to make this public we need to make sure this settings is set correctly.

<img width="743" alt="Screenshot 2024-01-16 at 1 58 46 PM" src="https://github.com/open-telemetry/community/assets/1373887/c45b9a89-9ac4-4b75-a6c3-581fccd73b16">

**Comment by sakshi-1505** [comment]
@bogdandrutu Can we make it public?

> I could not find this settings

Why do we require this setting; sorry I don't have enough idea around the above requirement?

**Comment by arminru** [comment]
@sakshi-1505 I set the repo to public and added the settings as described by Bogdan above.
