### ISSUE TITLE
REQUEST: New membership for zdaratom

### ISSUE THREAD

**Issue by zdaratom** [open-telemetry/community#1876]
### GitHub Username

@zdaratom

### Requirements

- [ x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@zdaratom-s1
@atoulme

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23640
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23250
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23149

**Comment by zdaratom-s1** [comment]
*I support*

**Comment by TylerHelmuth** [comment]
I support

**Comment by bogdandrutu** [comment]
I would prefer to remove the old account, since having multiple accounts may imply multiple votes during elections for example.

@open-telemetry/governance-committee what is your take here?

**Comment by tedsuo** [comment]
I agree, this is more like an account transfer than a new membership. @zdaratom does that work for you?

**Comment by zdaratom-s1** [comment]
Yes make sense, replacing with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30639

**Comment by zdaratom-s1** [comment]
Feel free to close this issue as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30639 was merged
