### ISSUE TITLE
REQUEST: New membership for @braydonk

### ISSUE THREAD

**Issue by braydonk** [open-telemetry/community#1877]
### GitHub Username

@braydonk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi 
- @jsuereth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector/pulls/braydonk)
[OpenTelemetry Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls/braydonk)
[OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/pulls/braydonk)
[Semantic Conventions](https://github.com/open-telemetry/semantic-conventions/pulls/braydonk)
- Issues responded to
[OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector/issues?q=is%3Aissue+is%3Aopen+commenter%3Abraydonk)
[OpenTelemetry Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+is%3Aopen+commenter%3Abraydonk)
[Semantic Conventions](https://github.com/open-telemetry/semantic-conventions/issues?q=is%3Aissue+is%3Aopen+commenter%3Abraydonk)
- SIG projects I am involved with
System Metrics Semantic Conventions Working Group
Collector SIG (Hostmetrics codeowner)

**Comment by jsuereth** [comment]
I support

**Comment by jsuereth** [comment]
Invitation sent.
