### ISSUE TITLE
REQUEST: New membership for seth-priya

### ISSUE THREAD

**Issue by seth-priya** [open-telemetry/community#1893]
### GitHub Username

seth-priya

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi 
- TBD

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   https://github.com/open-telemetry/opentelemetry-collector/pull/5645 (internal review)
   https://github.com/search?q=repo%3Appc64le%2Fbuild-scripts%20opentelemetry&type=code (other components that we have built / validated on ppc64le)
- Issues responded to
   https://github.com/open-telemetry/opentelemetry-collector/issues/8528
- SIG projects I am involved with

**Comment by mx-psi** [comment]
I support

**Comment by austinlparker** [comment]
Is this still a relevant request?
