### ISSUE TITLE
One Logging Bridge per language - C++

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1900]

**Comment by jpkrohling** [comment]
@lalitb says on https://github.com/open-telemetry/opentelemetry-specification/issues/3824:

> OTel C++ doesn't have any bridge implementation in the main repo. There are a few contributions for spdlog, glog, log4cxx, and boost.log in progress in the contrib repo.

**Comment by cijothomas** [comment]
Additional thing to note : 
https://github.com/open-telemetry/opentelemetry-cpp/tree/main/examples/logs_simple OTel C++ created own logging API and is part of stable release. (Still does not exclude the need for bridge)

**Comment by jpkrohling** [comment]
Related PRs:

- https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/357
- https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/356
