### ISSUE TITLE
One Logging Bridge per language - Erlang

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1902]

**Comment by tsloughter** [comment]
To be clear, this is about the API not used by a user, right?

**Comment by tsloughter** [comment]
We are open to this through Outreachy. We do have an experimental log handler -- a handler is the interface between Erlang/Elixir's structured logger and the output of those logs, https://www.erlang.org/doc/apps/kernel/logger_chapter#handlers -- but it is not production ready https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_experimental/src/otel_log_handler.erl

**Comment by jpkrohling** [comment]
Given that there's experimental support already, I'm closing this as I believe this satisfies the main goal. We might be able to help you if needed in other areas, @tsloughter.

**Comment by tsloughter** [comment]
@jpkrohling ok. There are plenty of areas in need of help so if there is someone who expresses interest in Erlang/Elixir we can certainly figure something out.
