### ISSUE TITLE
One Logging Bridge per language - Go

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1903]

**Comment by jpkrohling** [comment]
@pellared mentioned that they'll move forward with the slog implementation on their own for now. Once we have 100% coverage, we'll try to have a second implementation, likely for logrus.

**Comment by pellared** [comment]
I created issues for bridges for other logging libraries that are very popular:
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5191
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5192
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5193

**Comment by jpkrohling** [comment]
Closing, as we are achieving the goal based on the last comment.
