### ISSUE TITLE
One Logging Bridge per language - JavaScript

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1905]

**Comment by dyladan** [comment]
There is a logs bridge for Bunyan https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-bunyan and one in progress for Winston https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1837

**Comment by jpkrohling** [comment]
Thanks, @dyladan!

**Comment by jpkrohling** [comment]
@dyladan, I see on the notes from the maintainer's meeting that JS wants more bridges. I can reopen this issue to reflect that if you agree.
