### ISSUE TITLE
REQUEST: New membership for adilhusain-s

### ISSUE THREAD

**Issue by adilhusain-s** [open-telemetry/community#1911]
### GitHub Username

@adilhusain-s

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi
- tbd 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[Adding support for linux/ppc64le platform](https://github.com/open-telemetry/opentelemetry-collector-releases/pull/173)
- Issues responded to
[responded to issue 170](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/170)
- SIG projects I am involved with

**Comment by mx-psi** [comment]
I support

**Comment by tigrannajaryan** [comment]
We need one more sponsor to support.

**Comment by austinlparker** [comment]
Is this still relevant?
