### ISSUE TITLE
REQUEST: New membership for @pegasas

### ISSUE THREAD

**Issue by pegasas** [open-telemetry/community#1915]
### GitHub Username

@pegasas 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @svrnm 
- @srikanthccv 
- @ocelotl 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

https://github.com/open-telemetry/opentelemetry.io/pull/3244
https://github.com/open-telemetry/opentelemetry.io/pull/3260
https://github.com/open-telemetry/opentelemetry.io/pull/3716
https://github.com/open-telemetry/opentelemetry-python/pull/3567
https://github.com/open-telemetry/opentelemetry-python/pull/3566
https://github.com/open-telemetry/opentelemetry-python/pull/3565
https://github.com/open-telemetry/opentelemetry-python/pull/3564
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4843

- Issues responded to

https://github.com/open-telemetry/opentelemetry-python/issues/3561
https://github.com/open-telemetry/opentelemetry.io/issues/3157
https://github.com/open-telemetry/opentelemetry.io/issues/2623
https://github.com/open-telemetry/opentelemetry-python/issues/3547
https://github.com/open-telemetry/opentelemetry-python/issues/3548
https://github.com/open-telemetry/opentelemetry-python/issues/3549
https://github.com/open-telemetry/opentelemetry-python/issues/3550
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4810

- SIG projects I am involved with

https://github.com/open-telemetry/opentelemetry.io
https://github.com/open-telemetry/opentelemetry-python
https://github.com/open-telemetry/opentelemetry-dotnet

**Comment by svrnm** [comment]
> I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Hey @pegasas, ping me and @srikanthccv on CNCF slack ([link for registration](https://communityinviter.com/apps/cloud-native/cncf)) and we can quickly review what is required to support your membership.

**Comment by pegasas** [comment]
> > I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
> 
> Hey @pegasas, ping me and @srikanthccv on CNCF slack ([link for registration](https://communityinviter.com/apps/cloud-native/cncf)) and we can quickly review what is required to support your membership.

Thanks @svrnm for this key information. 
I've join this slack. feel free to ping me if any concerns.

**Comment by srikanthccv** [comment]
I support. Thanks @pegasas for your contributions to Python SIG and it's related docs.

**Comment by svrnm** [comment]
I support. Thanks for your help @pegasas !

**Comment by ocelotl** [comment]
I support too :v:

**Comment by jmacd** [comment]
Welcome @pegasas. Invite should have arrived.
