### ISSUE TITLE
Community Feedback Survey - OTel Collector

### ISSUE THREAD

**Issue by avillela** [open-telemetry/community#1925]
The OpenTelemetry End User Working Group (EUWG) has been working closely with @jpkrohling of the OpenTelemetry Collector SIG to gather community feedback on the OpenTelemetry Collector. This information will be used to help steer the direction for the Collector in terms of priorities, etc.

One of the EUWG's deliverables has been an [OpenTelemetry Collector Survey](https://forms.gle/81v8HSnjcazxYKnT9). This survey was vetted with members of the Collector SIG before being made public.

Now that the survey has been out in the community, we have received additional feedback on the type of information that we might want to also capture next time we run another such survey:
* Job title
* Company size

We would appreciate any other suggestions for "core information" to be included in subsequent surveys.

**Comment by trask** [comment]
this is done, check out https://opentelemetry.io/blog/2024/otel-collector-survey/
