### ISSUE TITLE
Create new `weaver` repository

### ISSUE THREAD

**Issue by lquerel** [open-telemetry/community#1929]
OTEP [#0243](https://github.com/open-telemetry/oteps/blob/main/text/0243-app-telemetry-schema-vision-roadmap.md) is now merged, and the next step is to **create a new repository** `open-telemetry/weaver` for prototyping tooling and the schema itself prior to the next set of specification PRs for phase 1. 

Related issue: #1866 

Initial maintainers of this new project: 
- Laurent Querel (@lquerel )
- Josh Suereth (@jsuereth )

**Comment by tigrannajaryan** [comment]
@jsuereth we briefly chatted today that some of what weaver does is related to the semconv build tool. What's the plan, do you want to start in a separate repo and then figure out what gets merged into semconv build tool?

**Comment by jsuereth** [comment]
@tigrannajaryan Yes.  I'd like to move this work into CNCF so we have active prototypes that any OTEL engineer can work on.

These prototypes would then drive changes to the specification *and* tooling used for Semantic Conventions. 

For now I expect the two repositories to exist as complementary components.  I would like to merge down to one tool, assuming we as a community decide it makes sense.   This is a topic I plan to raise in Semconv WG.   For now, though, the source of truth on tooling will remain the `build-tools` repository.

**Comment by jsuereth** [comment]
https://github.com/open-telemetry/weaver is created.  We should start working on the prototype of resolved telemetry and look for additional contributors, approvers + maintainers.
