### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector*

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1931]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib

### Requested changes

Update required checks to include go 1.22 checks and remove go 1.20 checks
 
### Purpose

We're updating the supported versions of go in the collector repos
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/collector-maintainers 
- @open-telemetry/collector-contrib-maintainers

**Comment by jack-berg** [comment]
I assume you mean updating the branch protection rules for main to include new required status checks?

If so, I don't see a required status check named "go 1.22" or "go 1.20" available.

Also, assuming we can sort out what you mean, I'll wait for a thumbs up from @open-telemetry/collector-maintainers / @open-telemetry/collector-contrib-maintainer before I go ahead and make the update.

**Comment by codeboten** [comment]
my bad @jack-berg, the check is now on the job that uses a matrix for each version, no changes needed, closing.
