### ISSUE TITLE
Extending project management to reference existing issues

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#1933]
This issue discusses a potential an extension to the current [project management](https://github.com/open-telemetry/community/blob/main/project-management.md) to facilitate the process of prioritising challenges faced by end-users, maintainers, and vendors within the OpenTelemetry community, communicating roadmap items and the value delivered to all. However, it is not the proposal itself, which would be done via a PR to this repo with changes to project management page, project proposal template, and issue template.

This approach is inspired by strategy frameworks (e.g. Good Strategy/Bad Strategy by Richard P. Rumelt), adapted to the practices of the OpenTelemetry community.

Within the existing project management workflow, the way to propose and manage changes that expand the scope of OpenTelemetry, or impact many SIGs within OpenTelemetry, starts with a Project Proposal. This assumes two key aspects:

* The problem we’re solving is well understood by the community, and it's worth solving.
* The author of the proposal, although supported by TC and GC, has a good idea of what needs to be done to solve that
  problem (i.e. deliverables, timelines, staff, etc).

It requires a jump straight to the approach (i.e the project proposal), and the actions (i.e. individual project  issues, PRs, OTEPs), without a diagnosis of the problem itself. This results in:

* End-users may miss a direct connection between the challenges they’re facing and the actions being delivered by individual projects.
* The End-User Working Group don't have a structured way to communicate OpenTelemetry-wide challenges and problems to solve, without proposing a solution.
* The scope of projects that are needed to tackle multiple issues (e.g. Event API project also needed for client-side) may grow without a direct connection to the challenges they solve.
* The prioritisation of projects may be driven by the staffing/project proposal readiness, affecting the bandwidth of TC members and other sponsors, without a prioritisation of challenges faced by the community.

The workflow can be characterised in three main areas.

### 1. Diagnosis: what problems need solving?
The main proposed change to the current workflow is the requirement for an issue to be created before the project proposal is created. The issue template should prompt issue authors to cover:

* What is the OpenTelemetry-wide challenge/problem we’re facing? Focus on one challenge, short summary, etc. It should NOT suggest a solution.
* What impact is this issue having for end-users, maintainers, vendors, etc?
* What is the value-add from solving this issue, in addition to tackling the challenge documented above?

~~Issues can be created by anyone, but they mat also be condensed/consolidated by different groups (e.g. GC, EUWG, SIGs, TC), if they see appropriate, with the aim to facilitate prioritisation.~~
GC and End-User Working Group should work together to consolidate end-user feedback into actionable issues that represent the most pressing challenges to be solved, ensuring alignment with the overall strategy and projects currently in progress.

GC and TC should work together to prioritise open issues. This will allow the TC to balance work in progress, and the wider community to understand the backlog of priorities (regardless of having a project proposal open or not), which can help communicate roadmap, or signal anyone to make a project proposal for any issue without one. After a project is created and approved, corresponding issues can be moved through different states on the project board and closed when all projects needed to solve an issue have been completed.

### 2. Approach: what do we need to do to solve them?
This follows the current approach to project management. The change proposed here is that projects should link to the issues they solve, or partially solve, as there may be more than one project needed to solve the same challenge. A project can also solve (or partially solve) more than one challenge.

### 3. Actions: how are we going to execute the approach?
No change proposed here, as individual issues are already linked to their project.

**Comment by tedsuo** [comment]
I agree that understanding the scope of the challenges across the project is not something that end users are well equipped for. The work of understanding how projects fit into the wider scope feels like it is our responsibility. As project managers and sponsors, we should be communicating this to end users and subject matter experts as part of helping them craft their project proposals. I don't think that forcing end users to fill out a template with information that we do not expect them to have would be useful.

Instead of demanding that individual end users do the work of compartmentalizing and organizing their feedback, should this work be a collaboration between the GC and the End User working group? I agree that it would be useful to have issues on our project board that we feel are important, but do not yet have a project proposal.

**Comment by danielgblanco** [comment]
> Instead of demanding that individual end users do the work of compartmentalizing and organizing their feedback, should this work be a collaboration between the GC and the End User working group?

Yeah, I think that's probably a better way of approaching it. Issues would be able to cover the priorities and opinions of the larger community this way, incorporating feedback from end-users but also taking into consideration the current status of items in progress within the project.

**Comment by danielgblanco** [comment]
I have just updated the issue to reflect this

**Comment by danielgblanco** [comment]
Closing this issue, as https://github.com/open-telemetry/community/pull/2049 covers the aspect related to project creation. The end-user SIG is also working on ways to ensure that the feedback loop between maintainers and end-users is faster, by organising focused feedback sessions and other ways to gather actionable feedback.
