### ISSUE TITLE
REQUEST: github org read access for opentelemetry-rust

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/community#1938]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-rust
https://github.com/open-telemetry/opentelemetry-rust-contrib

### Requested changes

- Grant `read:org` access to me for `cargo.io` OAuth applicaion
 
### Purpose

Cargo is the Rust's package manager and we are trying to setup ownership via Github Teams `open-telemetry/rust-maintainers`. While doing so I get error message says I cannot query the membershp([this error](https://doc.rust-lang.org/cargo/reference/publishing.html#troubleshooting-github-team-access-errors)). 

Per [this help doc](https://doc.rust-lang.org/cargo/reference/publishing.html#github-permissions) I need to give `read:org` access to `cargo.io`. I have requested it but need someone with access to grant it
 
### Expected Duration
permanently

### Repository Maintainers

- @open-telemetry/rust-maintainers

**Comment by reyang** [comment]
I'm looking into this.

**Comment by reyang** [comment]
I didn't see the request from @TommyCpp. However, there was a request from another OTel Rust maintainer @jtescher, and based on my discussion with @TommyCpp we think approving it should also work.

![image](https://github.com/open-telemetry/community/assets/17327289/87709b52-7bdb-4988-90dd-a38d5aba3d8d)

**Comment by reyang** [comment]
@TommyCpp we should be all set now, please try and let me know if it is not working.

**Comment by hdost** [comment]
Thank you!
