### ISSUE TITLE
Create a PHP SIG

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#194]
There currently isn't a PHP SIG group created for open-telemetry.  

- Please name the GitHub repo opentelemetry-php.
- We have a meeting next week to discuss a couple of the implementation details, we can determine ownership during that meeting.  You can add me as the approver / maintainer for the time being so we have someone in place.

Question: is there a CNCF zoom account available, which could be assigned to this SIG?
We'd like to create a gitter chat room: https://gitter.im/open-telemetry/opentelemetry-php

**Comment by SergeyKanzhelev** [comment]
@nekufa do you want to work with @bobstrecansky on this?

@bobstrecansky happy to assist creating everything for you. I can bootrap the repo later today for you

**Comment by nekufa** [comment]
sure, we can use my opentelemetry-php repository as a start point, tracing part is implemented and fully covered with tests. or also start from scratch, why not :)

**Comment by bobstrecansky** [comment]
I'm assuming this is the repository you're referring to @nekufa - https://github.com/nekufa/opentelemetry-php

Seems like just as good of a starting point as any to me.  Thank you for the contribution!  I'm sure we will chat more next week about this during our first unofficial meeting.

**Comment by SergeyKanzhelev** [comment]
https://github.com/open-telemetry/opentelemetry-php is created and @bobstrecansky has maintainer's permission on it.

**Comment by SergeyKanzhelev** [comment]
What time is your first meeting? I can put it into the schedule. We have rotating zoom accounts:

https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md

**Comment by bobstrecansky** [comment]
It's Wednesday at 1:30PM EST / 10:30AM PST.  Thank you for putting this on the calendar!
