### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry.io -- fix broken netlify build process

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#1941]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io

### Requested changes

Help with fixing the broken netlify build process. This seems to be a setup/permission issue:

```
Error enqueueing build. POST https://api.github.com/app/installations/.../access_tokens: 422 - There is at least one repository that does not exist or is not accessible to the parent installation. // See: https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app
```

The [API docs for that endpoint](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app) stated that a 422 means "Validation failed, or the endpoint has been spammed." -- We are probably not spamming this endpoint, so it looks like some validation issue.

We (@open-telemetry/docs-maintainers) do not have the right permissions to triage and fix this issue ourselves, so we need help.

### Repository Maintainers

- @open-telemetry/docs-maintainers

**Comment by trask** [comment]
@svrnm this got magically fixed somehow IIUC?
