### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-dotnet-instrumentation

### ISSUE THREAD

**Issue by RassK** [open-telemetry/community#1944]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

### Requested changes

Add [self-actuated](https://github.com/apps/self-actuated) support for [opentelemetry-dotnet-instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation).

### Purpose

Getting ARM64 runners and release software with ARM64 support.

### Repository Maintainers

- @open-telemetry/dotnet-instrumentation-maintainers

### Related

https://github.com/open-telemetry/community/issues/1821

CC: @atoulme

**Comment by tigrannajaryan** [comment]
Done.
