### ISSUE TITLE
REQUEST: New membership for RichieSams

### ISSUE THREAD

**Issue by RichieSams** [open-telemetry/community#1945]
### GitHub Username

@RichieSams

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@jpkrohling
@djaglowski

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

* I am the creator / maintainer of the new interval processor in the contrib repo
    * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29461
    * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30756
    * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30827
* I will be co-owner of the new internal/exp/metrics module, which will allow for common methods for metric identification and manipulation
    * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31017
    * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31016
    * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31089

**Comment by djaglowski** [comment]
I support.

**Comment by jpkrohling** [comment]
I support

**Comment by arminru** [comment]
@RichieSams I just noticed you were already invited. I'll close this issue - if you need to be added to any team, please open a new one. Thanks!
