### ISSUE TITLE
REQUEST: New membership for @bobstrecansky

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#195]
### GitHub Username
@bobstrecansky

### Organization you are requesting membership in
@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects

I'm opening a separate PHP SIG group in a separate ticket - https://github.com/open-telemetry/community/issues/194, where I hope to make contributions.  If this is a blocker, i'll make a contribution to another language for the time being.

- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines

- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

I do not currently have sponsors as this is a new project.

**Comment by SergeyKanzhelev** [comment]
@bobstrecansky glad to see you here and at w3c meeting. We ask for some participation before adding people to the org. Like filing and c ommenting on issues, participate in SIG meetings or code contributions. I believe it can be easily done in a week and I will be happy to add you to the org after this.

Again, happy to see you here!

**Comment by bobstrecansky** [comment]
@SergeyKanzhelev - no problem, i'll get on it this weekend.  Thanks for the quick comment back!

**Comment by SergeyKanzhelev** [comment]
I didn't realize you want to start a PHP SIG. In this case I'd be happy to add you to the org. Please confirm that you will be running this SIG.

**Comment by bobstrecansky** [comment]
That's the plan, at least for the time being.  We have a meeting next week to discuss ownership and accountability, i'll be sure to update you after that meeting.
