### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-go

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/community#1954]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go

### Requested changes

Please grant access to the `actuated` app to this repository.
Related: #1821 and #1162
 
### Purpose

We are looking into doing two things:

* Run our benchmarks on dedicated machines so noisy neighbors do not impact their results.
* Possibly, run our CI suite on ARM, so we can update our compatibility matrix with that architecture.
 
### Expected Duration

Permanently.

### Repository Maintainers

- @open-telemetry/go-maintainers

**Comment by tigrannajaryan** [comment]
Done.
