### ISSUE TITLE
Create regular meeting invites for llm-semconv working group / project.

### ISSUE THREAD

**Issue by drewby** [open-telemetry/community#1958]
I want to establish our regular meeting cadence described in our [project](https://github.com/open-telemetry/community/blob/main/projects/llm-semconv.md).

I attempted to follow the instructions [here](https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md) and email calendar-edit-permission@opentelemetry.io but this address was rejected by google.

Can you grant calendar permission to drew@drewby.com or let me know what I need to do?

**Comment by trask** [comment]
hi @drewby! sorry for the confusion, I just sent #1959 to clarify that this is a google group you need to join.
