### ISSUE TITLE
REQUEST: New membership for breedx-nr

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/community#196]
### GitHub Username

@breedx-nr

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @jkwatson
- @carlosalberto 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-java/pull/563
  - https://github.com/open-telemetry/opentelemetry-java/pull/566
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-java/issues/562
- SIG projects I am involved with
  - Java SIG

**Comment by SergeyKanzhelev** [comment]
@breedx-nr, welcome!

![image](https://user-images.githubusercontent.com/9950081/65791564-e8a26e00-e116-11e9-8bd5-1e272421bfa8.png)
