### ISSUE TITLE
Calendar View for End User Events

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#1962]
To make it easier for people to find all the events planned by @open-telemetry/end-user-wg there should be a Calendar View like [this one](https://calendar.google.com/calendar/embed?src=c_2bf73e3b6b530da4babd444e72b76a6ad893a5c3f43cf40467abc7a9a897f977%40group.calendar.google.com). We could make them accessible through the website then.

cc @trask

**Comment by rafey1104** [comment]
@svrnm Please assign me this issue, i have already started working on it

**Comment by svrnm** [comment]
hey @rafey1104 , thanks for your interest in helping here, see https://github.com/open-telemetry/opentelemetry.io/issues/4098#issuecomment-1979297632, we are not assigning issues but happy to see your contribution. I'll followup on that issue over at opentelemetry.io as well.

**Comment by danielgblanco** [comment]
Thanks for the proposal. I'm going to close this one, as we have requested access to CNCF Community Groups and that's where the public (non-Google) calendar of End User Events will live.

Please follow https://github.com/open-telemetry/sig-end-user/issues/8 updates.
