### ISSUE TITLE
REQUEST: Create new team open-telemetry/semconv-db-approvers

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#1964]
### Requested changes

Create new team `@open-telemetry/semconv-db-approvers` with the following members:

- @alanwest 
- @jack-berg 
- @jcocchi 
- @lmolkova 
- @sourabh1007 
- @trask 

### Purpose

To be able to tag the members of the database semconv stability team on semconv issues and PRs.
 
### Expected Duration

Permanent

### Repository Maintainers

- @open-telemetry/specs-semconv-maintainers

**Comment by jsuereth** [comment]
Done
