### ISSUE TITLE
Zoom Links and Meeting Notes for LLM semconv WG

### ISSUE THREAD

**Issue by drewby** [open-telemetry/community#1965]
I am scheduling the recurring meetings for the LLM Semantic Conventions WG.

We will alternate the times each week to cover TZ. 

I need a Zoom Link for the following meeting times:

* Wednesday, 4:00pm PST beginning March 6, Bi-weekly
* Wednesday, 8:00am PST beginning March 13, Bi-weekly

I will also need a Google Docs link for the Meeting Notes.

**Comment by trask** [comment]
I've created the two meeting series to the calendar and added the Zoom link and Google Docs link to them. Let me know if everything looks good. (FYI the meeting links are the same for both series as they are not time-specific, only WG-specific)

**Comment by drewby** [comment]
@trask Thank you! And thanks for adding to the calendar as well. I assume with my edit access I can cancel instances of the meeting for holidays, etc.

**Comment by trask** [comment]
> I assume with my edit access I can cancel instances of the meeting for holidays, etc.

Yup 👍
