### ISSUE TITLE
REQUEST: New membership for @jkwatson

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/community#198]
### GitHub Username

@jkwatson

### Organization you are requesting membership in

@opentelemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @carlosalberto 
- @tylerbenson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-java/pull/566
  - https://github.com/open-telemetry/opentelemetry-java/pull/555
  - https://github.com/open-telemetry/opentelemetry-java/pull/554
  - https://github.com/open-telemetry/opentelemetry-specification/pull/255
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-java/issues/557
  - https://github.com/open-telemetry/opentelemetry-java/issues/534
- SIG projects I am involved with
  - Java SIG

**Comment by bhs** [comment]
Thank you, @jkwatson!

![image](https://user-images.githubusercontent.com/2251553/65792032-c5c48980-e117-11e9-94e9-9a3f1083ee4a.png)
