### ISSUE TITLE
Outreachy Mentorship May-Aug 2024 - Get familiar with Log Bridge API

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1988]

**Comment by Dev-JoyA** [comment]
@jpkrohling @yuriolisa  I would love to work on this task, can you please assign it to me , so i can get started

**Comment by aditi5926** [comment]
Hello mentor how to get started with the contribution phase of this project of this organisation? Please help me get started with this.

**Comment by yuriolisa** [comment]
Hello @Dev-JoyA and @aditi5926,
Thank you for demonstrating your interest in that issue, but this one is more related to a task for all the Outreachy candidates. One great idea after you get familiar with the Log Bridge definition(https://opentelemetry.io/docs/specs/otel/logs/bridge-api/)  would be choosing a repo from the Otel project (https://github.com/open-telemetry) and find #goo-first-issues to work on.

**Comment by aditi5926** [comment]
Yes @jpkrohling @yuriolisa , I am participating in Outreachy as well so after searching I found this repo and started communication regarding Outreachy. I am really a beginner but I passionately want to continue here. Can you please guide me step by step on what to learn before starting the contribution phase in Outreachy for this organisation? I guarantee my complete involvement.

**Comment by danielgblanco** [comment]
Close as complete
