### ISSUE TITLE
REQUEST: New membership for @sokoide

### ISSUE THREAD

**Issue by sokoide** [open-telemetry/community#1996]
### GitHub Username

@sokoide

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling
- @songy23

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: [Reviewed](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+reviewed-by%3Asokoide), [Authored](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Asokoide+)
- Issues responded to: [Issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+author%3Asokoide), [Issues](https://github.com/open-telemetry/opentelemetry-collector/pull/9130)
- SIG projects I am involved with: Collector (#otel-collector)

**Comment by songy23** [comment]
I support

**Comment by jpkrohling** [comment]
I support

**Comment by arminru** [comment]
Hi @sokoide! Please fill out the last section in the issue template as well:

> SIG projects I am involved with

Also your list of PRs seems to query a different user, could you fix that one too?
Thanks!

**Comment by sokoide** [comment]
@arminru, I updated "Collector (#otel-collector)" as the SIG. I'm discussing and reviewing the PRs with @mcube8. Other than that, although it wasn't merged, I made [PRs](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Asokoide+) in opentelemetry-collector (not contrib) or responded issues for [this](https://github.com/open-telemetry/opentelemetry-collector/issues/8000) as [this](https://github.com/open-telemetry/opentelemetry-collector/issues/9129).
Thank you for your review!

**Comment by sokoide** [comment]
@arminru , I reorganized `Reviewed` and `Authored` PRs the issue description. Thank you!

**Comment by arminru** [comment]
Invite sent. Welcome, @sokoide!
