### ISSUE TITLE
looking for a github action

### ISSUE THREAD

**Issue by Samyu09** [open-telemetry/community#1999]
### Discussed in https://github.com/open-telemetry/community/discussions/1997

<div type='discussions-op-text'>

<sup>Originally posted by **Samyu09** March  7, 2024</sup>
i have a github action. **kittychiu/workflow-metrics@v0.4.7**  that generates the metrics of the workflows running in repository 
now i want to send these metrics to Open telemetry any idea on how can i t be done? or do we have any github action already present to do so</div>
or if there's already some github action that can directly create metrics of worklfow and send it to opentelemetry that will also help me.

**Comment by svrnm** [comment]
I provided an answer in your discussion, I think this is the right place to discuss this, let's not have duplicates here.

thanks
