### ISSUE TITLE
REQUEST: New membership for drewby

### ISSUE THREAD

**Issue by drewby** [open-telemetry/community#2003]
### GitHub Username

@drewby

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lmolkova 
- @alolita 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/semantic-conventions/pull/639 
- Issues responded to
- SIG projects I am involved with
https://github.com/open-telemetry/community/pull/1928

**Comment by lmolkova** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @drewby!

**Comment by drewby** [comment]
@arminru or @alolita, can you add me to the semconv-llm-approvers group? I finally realized that's why I can't approve PRs for our area. Thanks!

**Comment by arminru** [comment]
Hi @drewby! I added you to @open-telemetry/semconv-llm-approvers as per https://github.com/open-telemetry/community/blob/main/projects/llm-semconv.md#staffing--help-wanted.
