### ISSUE TITLE
REQUEST: New repository and team for end-user SIG

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2004]
### Affected Repository

https://github.com/open-telemetry/sig-end-user

### Requested changes

- Create a new repository for the end-user SIG named https://github.com/open-telemetry/sig-end-user
- Rename @open-telemetry/end-user-wg to `@open-telemetry/sig-end-user-maintainers`
- Ensure that membership of `@open-telemetry/sig-end-user-maintainers` contains only:
  - @danielgblanco
  - @avillela
  - @reese-lee 

 
### Purpose

The end-user SIG would like a way to manage end-user content (e.g. raw survey results, processes to aggregate feedback, etc) and issues in a permanent fashion. As an initial step, the content present in https://github.com/open-telemetry/community/tree/main/working-groups/end-user will be moved into this repo, along with any issues in the `community` repo.
 
### Expected Duration

Permanent

### Repository Maintainers

`@open-telemetry/sig-end-user-maintainers`

**Comment by svrnm** [comment]
> @open-telemetry/end-user-wg (possibly renamed to @open-telemetry/end-user-approvers)

Since there is some similarity to `[sig-security-maintainers](https://github.com/orgs/open-telemetry/teams/sig-security-maintainers)`, I would suggest `sig-end-user-maintainers`?

**Comment by trask** [comment]
same for the repo name, similar to https://github.com/open-telemetry/sig-security?

**Comment by danielgblanco** [comment]
That's interesting. Was there a discussion when the `sig-security` repo was created to not follow guidance in https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md ?

**Comment by danielgblanco** [comment]
Ah, I see https://github.com/open-telemetry/community/issues/1575

**Comment by reese-lee** [comment]
We also need to update the repo maintainers to remove [sharrmander](https://github.com/sharrmander), as she is no longer involved in the OTel community (😞).

**Comment by danielgblanco** [comment]
So, in summary, this request implies:

- New repo called `sig-end-user`
- `end-user-wg` team renamed to `sig-end-user-maintainers`
- `sig-end-user-maintainers` given `Maintain` role in the new repo

I see `sharrmander` is no longer in the `end-user-wg` team, but team membership may need to be reviewed.

**Comment by danielgblanco** [comment]
I think we got agreement on this, the only final thing is deciding who needs to be part of `sig-end-user-maintainers`. @open-telemetry/end-user-wg could you review membership?

**Comment by reese-lee** [comment]
Thoughts on this SIG having different roles as outlined [here](https://github.com/open-telemetry/community/blob/main/community-membership.md)? Or does `sig-end-user-maintainers` encompass all those roles?

**Comment by avillela** [comment]
> Thoughts on this SIG having different roles as outlined [here](https://github.com/open-telemetry/community/blob/main/community-membership.md)? Or does `sig-end-user-maintainers` encompass all those roles?

Yes, I agree with @reese-lee that we should have different roles. This way, folks can contribute as per their capacity.

**Comment by danielgblanco** [comment]
I believe if we take `sig-security-maintainers` as an example, they take on all responsibilities of the group equally. However, if you think you may need `sig-end-user-triagers` or `sig-end-user-approvers` that can be discussed later?

**Comment by reese-lee** [comment]
@danielgblanco

Per the definition of `Maintainer` in the [role table](https://github.com/open-telemetry/community/blob/main/community-membership.md), I think it makes sense to start `sig-end-user-maintainers` with the following members: 
- @danielgblanco 
- @avillela 
- @reese-lee (myself)

And we can revisit other roles as needed down the road.

**Comment by svrnm** [comment]
After creating the repo for the End User SIG, I'd like to wish for one thing: let's make sure that "end user facing content" continues to live on the website. What do I mean by that: we ask all SIGs to have their end-user facing docs on the website, and only their SIG-specific material (charters, tooling, pre-release/draft docs, ...) in their repo. A good example is SIG security: https://opentelemetry.io/docs/security/ vs https://github.com/open-telemetry/sig-security. So, when I read that "survey results, aggregated feedback" should be housed in the End User SIG repository, I hope this means the raw data and that end-user facing summaries end up on the website.

**Comment by danielgblanco** [comment]
Yes, absolutely @svrnm! I think in terms of survey results, I would expect the raw/CSV results form surveys to be in that repo, but anything digested and well presented to live in the website.

**Comment by danielgblanco** [comment]
I've just updated the issue definition to match all the comments in this thread

**Comment by tigrannajaryan** [comment]
@open-telemetry/governance-committee can you please clarify if the SIG was approved? I do not see it in the list of projects, nor in the list of SIGs.

**Comment by svrnm** [comment]
> @open-telemetry/governance-committee can you please clarify if the SIG was approved? I do not see it in the list of projects, nor in the list of SIGs.

It's an approved and already long runnign SIG, it's listed in the README.md:

https://github.com/open-telemetry/community/blob/main/README.md?plain=1#L169

**Comment by danielgblanco** [comment]
Agreed. Not a project, but rather a permanent SIG.

**Comment by tigrannajaryan** [comment]
> > @open-telemetry/governance-committee can you please clarify if the SIG was approved? I do not see it in the list of projects, nor in the list of SIGs.
> 
> It's an approved and already long runnign SIG, it's listed in the README.md:
> 
> https://github.com/open-telemetry/community/blob/main/README.md?plain=1#L169

That line says `Communications (Website, Documentation)` SIG, so perhaps update the description to mention "End User".

**Comment by tigrannajaryan** [comment]
- https://github.com/open-telemetry/sig-end-user created
- @open-telemetry/sig-end-user-triagers @open-telemetry/sig-end-user-approvers @open-telemetry/sig-end-user-maintainers created.
- @danielgblanco @avillela @reese-lee invited to @open-telemetry/sig-end-user-maintainers

@open-telemetry/sig-end-user-maintainers please make sure the repo is configured as specified here https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md

**Comment by tigrannajaryan** [comment]
I am closing the issue. Please reopen if anything else is needed.
