### ISSUE TITLE
REQUEST: New membership for federicobond

### ISSUE THREAD

**Issue by federicobond** [open-telemetry/community#2007]
### GitHub Username

@federicobond

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @aabmass 
- @ocelotl

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2123
    https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1717
    https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1562
    https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2064 (reviewed)
    https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2260 (reviewed)
    
- Issues responded to
    https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2165
    https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1729

- SIG projects I am involved with
   - OTel Python

**Comment by aabmass** [comment]
I support

**Comment by ocelotl** [comment]
I support
