### ISSUE TITLE
Standardize GitHub Milestones for Website

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#201]
The OpenTelemetry website will be updating shortly (see https://github.com/open-telemetry/opentelemetry.io/pull/30 for more details) with a new feature, an automatically generated SIG progress chart. This chart is generated automatically when the site is published, using data from the GitHub API. 

**For existing SIGs**
In order for each SIG's progress to be accurately reported, each SIG needs to create milestones that match the progress labels in the chart config. Each SIG should create milestones with the following names (note that the label can be a substring of the milestone name):

* v0.1
* v0.2
* v0.3
* v0.4
* beta
* rc
* v1.0

Once a milestone is completed (by that version releasing), the milestone should be closed. 

**For new SIGs**
If a SIG is being created that wants to add its progress to the chart, the following steps should be taken:

* In the website repository, make a PR that modifies `data/progress_source.yaml` and adds a new entry to the `data` collection in that file.
* Be sure to follow the format of the other entries exactly - the `sourceUrl` and `label` fields are of special note. The `sourceUrl` should be in the same format (`https://github.com/open-telemetry/<repo_name>`) as the others. The `label` field will be used exactly as written as the row label in the chart.

If you find any issues with the chart, please open an issue in the website repository. Maintainers, please use this issue to ask any questions about creating the milestones. Thanks in advance everyone!

**Comment by austinlparker** [comment]
The OpenTelemetry website recently updated with a new feature to pull release notes from GitHub for the latest release from each SIG. If you would like to use this feature, please ensure that you are publishing releases + release notes through GitHub Releases.

**Comment by SergeyKanzhelev** [comment]
I believe this needs to be worked out with individual repositories and maintainers. Happy to provide support in terms of pointing that this is very important.

Closing it here

**Comment by austinlparker** [comment]
@SergeyKanzhelev could you move this issue to the opentelemetry.io repo?
