### ISSUE TITLE
Create Calendar Group and Meeting Notes doc for Entities SIG

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#2010]
We need to create calendar-entities@opentelemetry.io and a meeting notes doc owned by Otel.

@open-telemetry/governance-committee can you help create these?

**Comment by svrnm** [comment]
Group created at https://groups.google.com/a/opentelemetry.io/g/calendar-entities
Doc created at https://docs.google.com/document/d/15Yt9ss2_EhuFPqItPbk4vjfpeRDAQ5WCUVuY_kCeOAo/edit?usp=sharing

**Comment by tigrannajaryan** [comment]
Thank you!
