### ISSUE TITLE
REQUEST: New membership for agoallikmaa

### ISSUE THREAD

**Issue by agoallikmaa** [open-telemetry/community#2011]
### GitHub Username

@agoallikmaa

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bobstrecansky 
- @brettmc

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored:
  - in [opentelemetry-php-contrib](https://github.com/open-telemetry/opentelemetry-php-contrib/pulls?q=is%3Apr+author%3Aagoallikmaa)
  - in [opentelemetry-php-instrumentation](https://github.com/open-telemetry/opentelemetry-php-instrumentation/pulls?q=is%3Apr+author%3Aagoallikmaa)
  - in [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Apr+author%3Aagoallikmaa)
  - in [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Aagoallikmaa)
  - in [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Aagoallikmaa)
- Issues responded to:
  - in [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php/issues?q=is%3Aissue+commenter%3Aagoallikmaa)
  - in [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues?q=is%3Aissue+commenter%3Aagoallikmaa)

**Comment by brettmc** [comment]
I support.

**Comment by breedx-splk** [comment]
I wasn't tagged, but I support. 🚀

**Comment by bobstrecansky** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @agoallikmaa!
