### ISSUE TITLE
REQUEST: New membership for ChrisLightfootWild

### ISSUE THREAD

**Issue by ChrisLightfootWild** [open-telemetry/community#2012]
### GitHub Username

@ChrisLightfootWild

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
  - PHP contrib 
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
  - There was a suggestion in the PHP-SIG around adding myself as a member

### Sponsors

- @bobstrecansky
- @brettmc

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-php-contrib/commits?author=ChrisLightfootWild
  - Typically, Laravel related auto-instrumentation
    - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/188
    - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/184
    - https://github.com/open-telemetry/opentelemetry-php-contrib/pull/221
- Issues responded to
  - (usually a mere a participant!)
  - https://github.com/open-telemetry/opentelemetry-php/issues/1045
  - https://github.com/open-telemetry/opentelemetry-php/issues/1232
  - https://github.com/open-telemetry/opentelemetry-php/issues/1241
- SIG projects I am involved with
  - PHP (contrib)

**Comment by bobstrecansky** [comment]
Approved!

**Comment by brettmc** [comment]
I support.

**Comment by arminru** [comment]
Invite sent. Welcome, @ChrisLightfootWild!
