### ISSUE TITLE
REQUEST: New membership for @bidetofevil

### ISSUE THREAD

**Issue by bidetofevil** [open-telemetry/community#2014]
### GitHub Username

@bidetofevil

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @breedx-splk
- @LikeTheSalad 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Regular attendance in the Client SIG since July 2023
- Regular contributor to the Client and Android slack channels in CNCF Slack since joining
- Issue: https://github.com/open-telemetry/opentelemetry-android/issues/283
- Commenting: https://github.com/open-telemetry/opentelemetry-android/issues/214#issuecomment-1953576131
- Commenting: https://github.com/open-telemetry/opentelemetry-android/pull/133#issuecomment-1821473157

**Comment by LikeTheSalad** [comment]
I support 👍

**Comment by arminru** [comment]
@bidetofevil please make sure to confirm all of the self-certifications above (☑️)

**Comment by breedx-splk** [comment]
I support! 👍🏻

**Comment by bidetofevil** [comment]
Done! I thought I had clicked lol

**Comment by arminru** [comment]
Invite sent. Welcome, @bidetofevil!
