### ISSUE TITLE
[WIP] Working Group: Add sustainability Metrics to Semantic Conventions

### ISSUE THREAD

**Issue by Spazzy757** [open-telemetry/community#2020]
### Description

With the introduction of various [European Laws regarding sustainability](https://www.consilium.europa.eu/en/policies/green-deal/fit-for-55-the-eu-plan-for-a-green-transition/), it is becoming increasingly more important for companies to track the emissions of their systems.

We have various efforts of implementations in the form of [Kepler](https://github.com/sustainable-computing-io/kepler) and others but creation conventions on tracking these metrics will be vital in order to align with other sectors and remove "creative accounting" practices in the IT sector

We want to have a unified metrics convention in order to better facilitate measuring sustainability metrics accross different ecosystems

### Project Board

Once approved by TC, a project should be managed using a GitHub project board. This project board should be pre-populated with issues that cover all known deliverables, organized by timeline milestones.

A [Technical Committee](https://github.com/open-telemetry/community/blob/main/community-members.md#technical-committee) (TC) member associated with the project can create the board, along with a new project-specific GitHub label to automatically associate issues and PRs with the project. The project lead and all other relevant project members should have edit access to the board.

Once created, please link to the project board here.

### Deliverables

We are looking to add to some new sustainability semantic conventions, these potentially include:

- `hw.abiotic_depletion_potential`
- `hw.product_carbon_footprint`
- `hw.site.pue` ([more](https://knowledge.sdialliance.org/data-center-metrics#903dbdc8aae84211aa42aa33c625ab7e))
- `hw.site.itue`, hw.site.tue ([more](https://knowledge.sdialliance.org/data-center-metrics#e6bcce2b25fb4671a51086dc1eee1695))
- `hw.site.cue` ([more](https://knowledge.sdialliance.org/data-center-metrics#1ae20a03c3f24f6c8558504fdcc6a4af))
- `hw.site.wue`
- `hw.site.ere`, `hw.site.erf` ([more](https://knowledge.sdialliance.org/data-center-metrics#f3b2ee7b318a41a39d16a3cabe2b3ebf))
- `hw.site.ref`, `hw.site.oef` ([more](https://knowledge.sdialliance.org/data-center-metrics#284afeeab1cd474bb0a84dbad125d687))
- `hw.site.cer` ([more](https://knowledge.sdialliance.org/data-center-metrics#fe1467211e0b4f5484f8eae368b4a0a1))
- `hw.site.electricity_cost`
- `hw.site.carbon_intensity`

We will also be creating a prototype based off these

### Staffing / Help Wanted

GC:
- @jpkrohling 

TC:
- none yet

Domain Experts
- @spazzy757
- @gabibeyer
- @bertysentry
- @nikimanoledaki
- @mkorbi
- @rossf7

#### Required staffing

Projects cannot be started until they the following participants have been identified:
* Every project needs a project lead, who is willing to bottom line the project and address any issues which are not handled by other project members.
* At least two sponsoring TC members. TC sponsors are dedicated to attending meetings, reviewing proposals, and in general being aware of the state of the project and it's technical details. TC sponsors guide the project through the spec process, keep the tracking issue up to date, and help to ensure that relevant community members provide input at the appropriate times.
* Engineers willing to write prototypes in at least two languages (if relevant to project). Languages should be fairly different from each other (for example: Java and Python).
* Maintainers or approvers from those languages committed to reviewing the prototypes.

### Meeting Times

- Meeting Times: TBD
- [cncf slack channel](https://cloud-native.slack.com/archives/C06RTM63YD6) for collaboration

### Timeline

We are hopefully looking at finishing this by end of Q3 2024

### Labels

- `sustainability`

### Linked Issues and PRs
- https://github.com/open-telemetry/semantic-conventions/issues/835

**Comment by svrnm** [comment]
@cprecup you might be interested in this

**Comment by cprecup** [comment]
> @cprecup you might be interested in this

Hi, great initiative in terms of the much-needed standardization!

We've got some work on sustainability-related KPIs collection and monitoring for the Network and DC infrastructure: https://github.com/cisco-open/green-monitoring. I would like to be part of this Working Group, if possible. Thank you!

**Comment by greenhsu123** [comment]
A great proposal! I would love to get involved, as well! Thanks!

**Comment by svrnm** [comment]
@greenhsu123, take a look at https://github.com/open-telemetry/community/pull/2018, review the PR and ask to be added to the list of contributors

**Comment by rossf7** [comment]
Hey, I discussed this working group with @mrchrisadams from Green Web Foundation and he would be interested in collaborating on this too.

**Comment by mrchrisadams** [comment]
thanks @rossf7 - I've been joining the Green Software Foundation Real Time Cloud (GSF RTC) working group calls for a while, and I think this Open Telemetry proposal came up recently in a convo there.

I'm happy to be involved, and share domain expertise where it's helpful.

There's a few things learned about how different orgs represent carbon intensity that I think would be worth bearing in mind. there's a miro board and open set of issues below that might be of interest:

https://github.com/Green-Software-Foundation/real-time-cloud/

**Comment by pyohannes** [comment]
@cprecup @greenhsu123

Thanks for your interest in participating in this workgroup. Organizational discussions for this group happen in the CNCF Slack channel [#otel-sustainability-semconv-sig](https://cloud-native.slack.com/archives/C06RTM63YD6). I couldn't find a Slack handle for you, so please subscribe to this group.

We're meeting each Monday at 4pm CET, please find calendar invites and Zoom links [here](https://github.com/open-telemetry/community?tab=readme-ov-file#specification-sigs).

**Comment by greenhsu123** [comment]
Unfortunately, I am not allowed to use Slack or Google-related products. Is it possible to subscribe to the group for me?

**Comment by pyohannes** [comment]
@greenhsu123 Got it, can you manage to join our weekly meetings (which already started)? All technical discussions should happen there and on GitHub.

> We're meeting each Monday at 4pm CET, please find calendar invites and Zoom links [here](https://github.com/open-telemetry/community?tab=readme-ov-file#specification-sigs).

**Comment by greenhsu123** [comment]
@pyohannes the zoom link seems to be behind a Google group, so, I am unable to access it. Is it possible to send the zoom invite directly to me @ sarah.hsu@gs.com? 

Thanks so much for understanding!
