### ISSUE TITLE
REQUEST: New membership for @devrimdemiroz

### ISSUE THREAD

**Issue by devrimdemiroz** [open-telemetry/community#2027]
### GitHub Username

 @devrimdemiroz

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @austinlparker 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-demo/pull/797
https://github.com/open-telemetry/opentelemetry.io/pull/2538
https://github.com/open-telemetry/opentelemetry-demo/pull/787
https://github.com/open-telemetry/opentelemetry-demo/pull/655

- Issues responded to
https://github.com/open-telemetry/opentelemetry-demo/issues/894
https://github.com/open-telemetry/opentelemetry-demo/issues/749
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20306
https://github.com/open-telemetry/opentelemetry-demo/issues/606

- SIG projects I am involved with

**Comment by jpkrohling** [comment]
I ssponsor

**Comment by austinlparker** [comment]
I support

**Comment by arminru** [comment]
update sponsor section to include @austinlparker

**Comment by arminru** [comment]
Invite sent. Welcome, @devrimdemiroz!

**Comment by devrimdemiroz** [comment]
🥳 Thank you!
