### ISSUE TITLE
Onboard mviitane as SIG OTel Demo maintainer

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/community#2028]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-demo

### Requested changes

Add `@mviitane` to `@open-telemetry/demo-maintainers` group.
We also moved `@cartersocha` to emeritus, so we need to remove him from the group.

When checking this, I've noticed that only Carter was tagged as maintainer in this list: https://github.com/orgs/open-telemetry/teams/demo-maintainers

Would it be possible to apply the maintainer tag to all members of `@open-telemetry/demo-maintainers`?

### Repository Maintainers

- @open-telemetry/demo-maintainers

**Comment by arminru** [comment]
Members updated and maintainer roles applied.

**Comment by julianocosta89** [comment]
Thank you @arminru!

Would you mind applying the same here as well?
https://github.com/orgs/open-telemetry/teams/demo-approvers

Carter is still there, and the maintainers tags are also not set.
