### ISSUE TITLE
REQUEST: New membership for asafm

### ISSUE THREAD

**Issue by asafm** [open-telemetry/community#2029]
### GitHub Username

asafm

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jack-berg 
- @trask 
- @reyang 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - Spec
      - https://github.com/open-telemetry/opentelemetry-specification/pull/3566
      - https://github.com/open-telemetry/opentelemetry-specification/pull/3761
      - https://github.com/open-telemetry/opentelemetry-specification/pull/3184
  - Java SDK
     - https://github.com/open-telemetry/opentelemetry-java/pull/5709
     - Bug fix: https://github.com/open-telemetry/opentelemetry-java/pull/5984
     -  https://github.com/open-telemetry/opentelemetry-java/pull/5998
     - https://github.com/open-telemetry/opentelemetry-java/pull/6058
     - https://github.com/open-telemetry/opentelemetry-java/pull/6136
     - https://github.com/open-telemetry/opentelemetry-java/pull/6153
     - https://github.com/open-telemetry/opentelemetry-java/pull/6179
     - https://github.com/open-telemetry/opentelemetry-java/pull/6182
     - https://github.com/open-telemetry/opentelemetry-java/pull/6196
     - Bug fix: https://github.com/open-telemetry/opentelemetry-java/pull/6221
     - https://github.com/open-telemetry/opentelemetry-java/pull/6231
  - Site
     - https://github.com/open-telemetry/opentelemetry.io/pull/3962  
- Issues responded to
   - https://github.com/open-telemetry/opentelemetry-specification/issues/2229
   - https://github.com/open-telemetry/opentelemetry-specification/issues/3062
   - https://github.com/open-telemetry/opentelemetry-specification/issues/2704
   - https://github.com/open-telemetry/opentelemetry-specification/issues/3062  
   - https://github.com/open-telemetry/opentelemetry-specification/issues/3101
   - https://github.com/open-telemetry/opentelemetry-go/issues/3943
   - ...
- SIG projects I am involved with

**Comment by trask** [comment]
@asafm you can use me as your second sponsor

**Comment by jack-berg** [comment]
I support!

**Comment by reyang** [comment]
I support!

**Comment by asafm** [comment]
Thank you all! Appreciate it!

**Comment by jmacd** [comment]
I support --

**Comment by jmacd** [comment]
Invite sent.

**Comment by dao-jun** [comment]
Welcome!
