### ISSUE TITLE
Create @open-telemetry/specs-profiling-approvers team

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#2033]
I'm looking for some way to tag profiling folks on community issues, e.g. https://github.com/open-telemetry/oteps/issues/251 and https://github.com/open-telemetry/opentelemetry-specification/issues/3979.

I realize we're thinking (and I support) to do away with the other specs-*-approvers teams in https://github.com/open-telemetry/opentelemetry-specification/issues/3821, but I think that profiling deserves its own team for a while since most people in the profiling SIG are pretty new to the specification repo to be thrown into the general spec approvers pool, and people not in the profiling SIG probably need time to get up to speed on the profiling work before being able to help out on those issues.

**Comment by tigrannajaryan** [comment]
We have `[profiling-approvers](https://github.com/orgs/open-telemetry/teams/profiling-approvers)` that we forgot to populate. Shall we use that?

**Comment by tigrannajaryan** [comment]
We have @open-telemetry/profiling-approvers and will use that. Please reopen if you want to rename it to specs-profiling-approvers.
