### ISSUE TITLE
REQUEST: New membership for @maryliag

### ISSUE THREAD

**Issue by maryliag** [open-telemetry/community#2036]
### GitHub Username

@maryliag

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pichlermarc 
- @pyohannes 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed 
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2029
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2033
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2075
- PRs authored
    - https://github.com/open-telemetry/opentelemetry-js/pull/4566
    - https://github.com/open-telemetry/opentelemetry.io/pull/4191
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2046
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2047
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2048
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2049
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2050
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2051
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2053
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2056 
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2057
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2060
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2061
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2062
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2063
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2064
    - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2077
- Issues created/replied to
    - https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2055
    - https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2065
    - https://github.com/open-telemetry/opentelemetry-js/issues/4556 
    - https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2054
- SIG projects I am involved with
    - SDK JS: participating in SIG meeting and being the [CODEOWNER](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2052) of the `opentelemetry-instrumentation-pg` package

**Comment by trentm** [comment]
I support, as well. :)

**Comment by pichlermarc** [comment]
I support :slightly_smiling_face:

**Comment by pyohannes** [comment]
I support! :slightly_smiling_face:
