### ISSUE TITLE
Create End-User SIG recurring meeting in public calendar

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2037]
As outlined in the `community` repo README, the End-User SIG meets every other week on Thursday at 10:00 PT. Next meeting is on April 11th. However, the meeting is not currently on the public calendar.

This issue requests the following:

- End-user SIG meeting invite created in the public calendar.
- `calendar-all@opentelemetry.io` and `calendar-end-users@opentelemetry.io` are invited to the meeting to receive invite updates.
- The current Zoom meeting is added to the calendar invite (i.e. no need to create new recurring Zoom meeting)

**Comment by danielgblanco** [comment]
I'm happy to take this (tomorrow) :) No need for @trask to get involved.

**Comment by trask** [comment]
I approve ❤️

**Comment by danielgblanco** [comment]
This is now done, keeping the same Zoom meeting, I've created the event in the public calendar and invites have been sent!
