### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector-releases

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/community#2039]
### Affected Repository

[opentelemetry-collector-releases](https://github.com/open-telemetry/opentelemetry-collector-releases)

### Requested changes

Give approver access to @open-telemetry/operator-approvers and @open-telemetry/helm-approvers  
 
### Purpose

We are adding @open-telemetry/operator-approvers and @open-telemetry/helm-approvers as codeowners for the new Kubernetes Distribution of the Collector
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/collector-maintainers
- @open-telemetry/collector-contrib-maintainer

**Comment by arminru** [comment]
I added both groups with Write access as requested.
