### ISSUE TITLE
Consistent expression for the stability of library implementations

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/community#2041]
**What are you trying to achieve?**

I would like to have consistent expressions of the status of implementations for each telemetries; trace, metric and log across all language repositories, like:

| Signal  | Status     | Project |
| ------- | ---------- | ------- |
| Traces  | Stable     | N/A     |
| Metrics | Alpha      | N/A     |
| Logs    | Frozen [1] | N/A     |

as `opentelemetry-go` and `opentelemetry-cpp` do.

**Additional context.**

The specifications of versioning is [well defined](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) in the spec document. However, when we try to check the maturity of libraries for each languages, we can't have the consistent understanding.

For example, [`opentelemety-java`](https://github.com/open-telemetry/opentelemetry-java) shows a table of versions of each components. This gives an insight that trace & metric are stable whereas log is alpha.

Next, when we look at [`opentelemetry-go`](https://github.com/open-telemetry/opentelemetry-go), there is a small simple table that shows the stability for each telemetries; trace, metrics and logs. Still I get the impression like "ok, trace is stable, metric is alpha, and log is frozen", as it literally says.

Then, when we go though the README of [`opentelemetry-python`](https://github.com/open-telemetry/opentelemetry-python), I get confused because there's no clue about the status of each components. Also, the version says `v1.9.1 & v0.28b1`. I tried to understand 1) the reason why it has two different versions in a single release  and 2) the status for each telemetries, but I could  not find them in `README` and `CHANGELOG.md`.

I had similar experience when I looked into [`opentelemetry-js`](https://github.com/open-telemetry/opentelemetry-js).

Preparing the detailed table something like what `opentelemetry-java` has should be burden, but at least something like the ones in `opentelemetry-go` and `opentelemetry-cpp` really help users to grasp the status of libraries at a glance.

**Comment by ymotongpoo** [comment]
@tedsuo Thank you for the comment. It looks what I wanted. If [`$.Site.Data.instrumentation`](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/shortcodes/telemetry-support-table.md?plain=1) is automatically updated, that is absolutely perfect.

**Comment by svrnm** [comment]
> If [`$.Site.Data.instrumentation`](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/shortcodes/telemetry-support-table.md?plain=1) is automatically updated, that is absolutely perfect.

This data is represented here for all language SDKs: https://opentelemetry.io/status/, note that the underlying data you references (Site.Data.Instrumentation) is not automatically updated in the sense that SIGs need to get back to the docs team to have their status updated accordingly, although this works _fairly_ good.
