### ISSUE TITLE
Remove myself from demo-approvers group for the website

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/community#2043]
I moved to emeritus maintainer on the demo but I'm still in the demo-approver group for the website repo. Thanks!

**Comment by svrnm** [comment]
Website repo makes use of [CODEOWNERS](https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/CODEOWNERS), if you are in any of the group listed you will be tagged accordingly

**Comment by trask** [comment]
@cartersocha I don't see you listed in @open-telemetry/demo-approvers, can you check if you've been removed now?

**Comment by cartersocha** [comment]
yep looks like it. I must be getting some emails from older threads. Thanks
