### ISSUE TITLE
Rename "Working group" (WG) to SIG everywhere

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#2044]
The distinction between working group and SIG has been confusing to everyone, and so the GC has decided to do away with the term "working group" (WG) and use only the term SIG.

**Comment by svrnm** [comment]
We also have some slack channels that are named "-wg":

[#otel-semantic-conventions-wg](https://cloud-native.slack.com/archives/C041APFBYQP)
[#otel-prometheus-wg](https://cloud-native.slack.com/archives/C01LSCJBXDZ)
[#otel-agentmanwg](https://cloud-native.slack.com/archives/C02J58HR58R)
[#otel-system-metrics-wg](https://cloud-native.slack.com/archives/C05CTFE9U4A)
[#otel-llm-semconv-wg](https://cloud-native.slack.com/archives/C06KR7ARS3X)
[#otel-jvm-metrics-stability-wg](https://cloud-native.slack.com/archives/C053TMS6BSN)
[#otel-wg](https://cloud-native.slack.com/archives/C04TN935PMH)
[#otel-db-client-semconv-stability-wg](https://cloud-native.slack.com/archives/C06HH05KNMC)

**Comment by trask** [comment]
> * @open-telemetry/instr-wg

just went ahead and deleted this (see #2218)

**Comment by dashpole** [comment]
I would prefer that we archive the repository.  We haven't used it in years, and it is probably misleading

**Comment by dashpole** [comment]
prometheus-interoperability works for me

**Comment by trask** [comment]
thanks!

I've renamed and archived the repository

and updated the team name to @open-telemetry/prometheus-interoperability 

I didn't find any [uses of the old team name](https://github.com/search?q=org%3Aopen-telemetry%20wg-prometheus&type=code) in code, but it did break past @mentions of the old team name, I don't think I realized that would happen (unlike repo renames where github handles the redirects), will be more clear beforehand on future team renames

**Comment by austinlparker** [comment]
> * [ ]  [#otel-wg](https://cloud-native.slack.com/archives/C04TN935PMH)

I'll open a Service Desk ticket to archive this channel.

**Comment by austinlparker** [comment]
Done.

**Comment by trask** [comment]
Remaining
- [ ] #2448
- [ ] Google Doc Meeting Notes, I can check this as I go through #1809

**Comment by svrnm** [comment]
> > * [ ]   [#otel-wg](https://cloud-native.slack.com/archives/C04TN935PMH)
> 
> I'll open a Service Desk ticket to archive this channel.

Thanks! Note, that if [OpenTelemetry Admin](https://cloud-native.slack.com/team/U07DR07KAEQ) is a channel manager we can also do it without a service ticket.

So all that is missing is removing the references in the document
