### ISSUE TITLE
REQUEST: Create new Docker Hub repository: otel/opentelemetry-collector-k8s

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/community#2046]
Recently, we added a new distribution of the OTel Collector https://github.com/open-telemetry/opentelemetry-collector-releases/pull/507.

We need to be able to push docker images to a new Docker Hub repository: https://hub.docker.com/r/otel/opentelemetry-collector-k8s. The repository cannot be created by doing `docker push` with existing `otelbot` credentials. See the [CI job failure](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/8641171572/job/23690246608).

Please help with creating the repository manually: **https://hub.docker.com/r/otel/opentelemetry-collector-k8s**

**Comment by tigrannajaryan** [comment]
Repository created: https://hub.docker.com/r/otel/opentelemetry-collector-k8s

**Comment by TylerHelmuth** [comment]
@tigrannajaryan the release job failed again: https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/8641171572/job/23713005927.

Can you confirm the credentials in `opentelemetry-collector-releases` has permissions to push to the new repository?

**Comment by TylerHelmuth** [comment]
Maybe a similar issue as the one we had here: https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/66?

**Comment by tigrannajaryan** [comment]
Try again, I added permissions to the otelbot user.

**Comment by TylerHelmuth** [comment]
Success!

**Comment by dmitryax** [comment]
Thank you, @tigrannajaryan !

**Comment by tigrannajaryan** [comment]
@jsuereth note this thread. You may need to do the same for weaver.
