### ISSUE TITLE
REQUEST: New membership for @bruno-garcia

### ISSUE THREAD

**Issue by bruno-garcia** [open-telemetry/community#205]
### GitHub Username

@bruno-garcia

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lmolkova
- @austinlparker 

### List of contributions to the OpenTelemetry project

- PRs authored
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/220
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/219
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/208
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/194
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/195
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/188
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/155
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/151
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/150
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/116
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/114
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/112
- PRs reviewed
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/247
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/246
  * https://github.com/open-telemetry/opentelemetry-dotnet/pull/246
- Issues responded to
  * https://github.com/open-telemetry/opentelemetry-specification/issues/276
- SIG projects I am involved with
  * .NET SIG

**Comment by SergeyKanzhelev** [comment]
@bruno-garcia, welcome!
