### ISSUE TITLE
REQUEST: New membership for tiffany76

### ISSUE THREAD

**Issue by tiffany76** [open-telemetry/community#2050]
### GitHub Username

@tiffany76

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @svrnm 
- @mx-psi 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io/issues?q=author%3Atiffany76+)
   - [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=reviewed-by%3Atiffany76)
- Issues responded to
   - [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io/issues?q=reviewed-by%3Atiffany76+)
   - [opentelemtry-collector](https://github.com/open-telemetry/opentelemetry-collector/issues?q=mentions%3A%40me+)
- SIG projects I am involved with: Communications SIG, Collector SIG

**Comment by svrnm** [comment]
I support 🙌

**Comment by mx-psi** [comment]
I support! :rocket:

**Comment by arminru** [comment]
Invite sent. Welcome, @tiffany76!
