### ISSUE TITLE
REQUEST: new repository and team for mainframe SIG

### ISSUE THREAD

**Issue by rrschulze** [open-telemetry/community#2053]
### Affected Repository

https://github.com/open-telemetry/sig-mainframe

### Requested changes

- Create a new repository for the [mainframe SIG](https://github.com/open-telemetry/community/blob/main/projects/mainframe.md) named `https://github.com/open-telemetry/sig-mainframe`
- Create a team `@open-telemetry/sig-mainframe-maintainers`
- Ensure that membership of `@open-telemetry/sig-mainframe-maintainers` contains:
   - @rrschulze 
   - @youngaaronm
   
### Purpose

The [mainframe SIG](https://github.com/open-telemetry/community/blob/main/projects/mainframe.md) would like a way to manage issues (incl. backlog of SIG activities) and pre-release content (draft documents and code) before actually opening issues and PRs for contributing it to the respective OpenTelemetry project repositories. In case of the mainframe SIG, pre-release content can be mainframe-specific input to the Otel semantic conventions, early documentation and code how to port Otel components to linux/s390x or zos/s390x and early versions of user documentation. 
 
### Expected Duration

Permanent

### Repository Maintainers

`@open-telemetry/sig-mainframe-maintainers`

**Comment by tigrannajaryan** [comment]
@mtwo @alolita @dyladan Since we don't have a TC sponsor for this SIG can you as a GC confirm repository creation and all the details above?

**Comment by mtwo** [comment]
I don't have permissions to create the repo or the team, but I can confirm that we need exactly what @rrschulze requested!

**Comment by tigrannajaryan** [comment]
- Repository https://github.com/open-telemetry/sig-mainframe created.
- Teams @open-telemetry/sig-mainframe-triagers @open-telemetry/sig-mainframe-approvers @open-telemetry/sig-mainframe-maintainers created
- @rrschulze @youngaaronm are invited to @open-telemetry/sig-mainframe-maintainers 

@rrschulze @youngaaronm you now have the permissions to write/maintain the repo. Please make sure you follow the instructions here for setting up the repo: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md
