### ISSUE TITLE
REQUEST: New membership for grcevski

### ISSUE THREAD

**Issue by grcevski** [open-telemetry/community#2067]
### GitHub Username

@grcevski

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias 
- @jpkrohling 
- @zeitlinger 
- @pyohannes 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/529
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/620
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/682
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/705
https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/780

- Issues responded to
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/471
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/472
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/290
https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/367

- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-go-instrumentation

**Comment by MrAlias** [comment]
I support 🎉

**Comment by pyohannes** [comment]
I support!

**Comment by zeitlinger** [comment]
I support :100:

**Comment by jpkrohling** [comment]
Even though it won't count (other Grafanistas are supporting already), I wanted to show my support here 🙂

**Comment by arminru** [comment]
Invite sent. Welcome, @grcevski!

**Comment by grcevski** [comment]
> Invite sent. Welcome, @grcevski!

Thank you!
