### ISSUE TITLE
REQUEST: New membership for christos68k

### ISSUE THREAD

**Issue by christos68k** [open-telemetry/community#2068]
### GitHub Username

[christos68k](https://github.com/christos68k)

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan
- @petethepig 
- @AlexanderWert 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [otel-profiling-agent](https://github.com/elastic/otel-profiling-agent/) (in-progress donation to OTel) 
- [Profiling SIG](https://github.com/open-telemetry/opentelemetry-proto)
- https://github.com/open-telemetry/semantic-conventions/issues/581
- https://github.com/open-telemetry/semantic-conventions/pull/576

**Comment by AlexanderWert** [comment]
I support!

**Comment by tigrannajaryan** [comment]
I support.
