### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-lambda

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#2079]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-lambda

### Requested changes

Please enable Renovate
 
### Purpose

We would like to evaluate using renovate  instead of dependabot.

### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/lambda-extension-maintainers

**Comment by arminru** [comment]
Configured https://github.com/apps/renovate to have access to https://github.com/open-telemetry/opentelemetry-lambda.

**Comment by tylerbenson** [comment]
Thanks!
