### ISSUE TITLE
REQUEST: Give organization access to the self-actuated Github application

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#2083]
The self-actuated folks report that we use a fair chunk of the CNCF workers associated, and we want to debug and understand the pattern of usage of the resources.

To do so, they have instructed to report in to https://dashboard.actuated.dev/ which shows a screen asking that we look at granting access to the application for members of the open-telemetry github organization.

https://docs.actuated.dev/troubleshooting/#the-actuated-dashboard

```
For security reasons, an administrator for your GitHub Organisation will need to approve the Actuated Dashboard for access to your organisation before team members will be able to see any data. Send them the link for the dashboard, and have them specifically tick the checkbox for your organisation when logging in for the first time.

If you missed this step, have them head over to their [Applications Settings page](https://github.com/settings/apps/authorizations), click "Authorized OAuth Apps" and then "Actuated Dashboard". On this page, under "Organization access" they can click "Grant" for each of your organisations registered for actuated.
```

Please follow the instructions above and grant this request so we may troubleshoot issues further.

**Comment by tigrannajaryan** [comment]
The instructions appear inacurate and impossible to follow. When I go to https://github.com/settings/apps/authorizations it shows me my personal github settings. Switching to OpenTelemetry org moves to a different page that does not show apps.

I tried finding "Authorized OAuth Apps" they are referring to in the Settings, but I am not able.

**Comment by atoulme** [comment]
Sorry to hear ; I have passed on your message to the Self Actuated slack, and folks there say this is a direct link to the page you seek: https://github.com/settings/connections/applications/8c5dc5d9750ff2a8396a

Please let me know if that works. Thank you!

**Comment by atoulme** [comment]
We have found how to get to this page, unfortunately, it appears this application asks for access to private data.
It's unclear which data is requested or made available if this is granted. For now, I will close this issue as we don't have a good way to know what data this will access ; we certainly would need a bit of review from the GC to allow this, at the very least, as well.

![image (8)](https://github.com/open-telemetry/community/assets/16758/5f45b0f3-3b6a-4746-a529-5cfbe7e5a82a)

**Comment by trask** [comment]
btw, it looks like GitHub Actions Arm support will be in public preview pretty soon now: https://github.com/github/roadmap/issues/955

**Comment by atoulme** [comment]
It's helpful some. I don't know the granularity the dashboard would have afforded us because I didn't get to it, I was hoping to identify long running jobs. We will limit our usage of resources for now.

**Comment by trask** [comment]
maybe run arm jobs only on `main` and not on PRs? (if you aren't doing that already)

**Comment by atoulme** [comment]
We are doing that.
