### ISSUE TITLE
REQUEST: New membership for AnaMMedina21

### ISSUE THREAD

**Issue by AnaMMedina21** [open-telemetry/community#2085]
### GitHub Username

AnaMMedina21 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @danielgblanco 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
-- https://github.com/open-telemetry/opentelemetry.io/pull/3346 
-- helped edit transcript for Humans of OTel 2023 https://opentelemetry.io/blog/2023/humans-of-otel/
--  Helped co-organize activities being held at OTel Observatory for KubeCon EU 2024 
-- SIG: End-User - Getting Started Survey
- Issues responded to
- SIG projects I am involved with
-- End-User SIG

**Comment by avillela** [comment]
My name's not on the sponsorship list, but happy to support @AnaMMedina21 as well! 😄

**Comment by musingvirtual** [comment]
I wish to add a comment in support of Ana's membership - she's done good work for the End User SIG so far and as a project member we hope she'll do even more!  She's an established contributor to other CNCF projects, kubernetes & keptn, as well.

**Comment by danielgblanco** [comment]
I support! @AnaMMedina21 has been an active member of the OTel community in the End-User SIG

**Comment by jpkrohling** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @AnaMMedina21!
