### ISSUE TITLE
REQUEST: New membership for IAMebonyhope

### ISSUE THREAD

**Issue by IAMebonyhope** [open-telemetry/community#2086]
### GitHub Username

@iamebonyhope

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @avillela
- @musingvirtual

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  -  https://github.com/open-telemetry/opentelemetry.io/pull/4136
  - https://github.com/open-telemetry/opentelemetry.io/pull/4409
  - Helped co-organize activities being held at OTel Observatory for KubeCon EU 2024
  - Helped create blogpost for End user SIG OpenTelemetry Collector Survey
- Issues responded to
- SIG projects I am involved with
  - End-User SIG

**Comment by musingvirtual** [comment]
I support.

**Comment by danielgblanco** [comment]
I support! @IAMebonyhope has been an active member of the End-User SIG and would like to see this effort continue as part of the community.

**Comment by jpkrohling** [comment]
I also support!

**Comment by avillela** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @IAMebonyhope!
