### ISSUE TITLE
REQUEST: Enable Renovate on opentelemetry-go and opentelemetry-go-contrib

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/community#2090]
### Affected Repository

- https://github.com/open-telemetry/opentelemetry-go
- https://github.com/open-telemetry/opentelemetry-go-contrib

### Requested changes

Install Renovate app (request made 05/02)
 
### Purpose

Setting up Renovate to automate dependency updates

### Repository Maintainers

- @open-telemetry/go-maintainers 

### Additional info

Related to https://github.com/open-telemetry/opentelemetry-go/issues/5271

**Comment by arminru** [comment]
@XSAM I set up Renovate for the two repos you requested, let me know if it works.

**Comment by arminru** [comment]
@pellared added!

**Comment by pellared** [comment]
@arminru, something is still wrong. https://developer.mend.io/github/open-telemetry/opentelemetry-go/-/job/15741f11-847c-40db-96df-d42215fde497, can you please try to fix it?

**Comment by arminru** [comment]
@pellared I put the branch protection rules in a different order so `**/**` comes last, now it's working.
I forced a Renovate run here which succeeded: https://developer.mend.io/github/open-telemetry/opentelemetry-go/-/job/99718a2f-1d8b-4e07-b53a-58158e0d3fcf

**Comment by arminru** [comment]
The Renovate app was also able to create https://github.com/open-telemetry/opentelemetry-go/tree/renovate/configure now to prepare https://github.com/open-telemetry/opentelemetry-go/pull/5309.

**Comment by MrAlias** [comment]
@pellared @XSAM can this be closed as completed?

**Comment by XSAM** [comment]
> @pellared @XSAM can this be closed as completed?

We might need to merge https://github.com/open-telemetry/opentelemetry-go/pull/5309 first to ensure the renovate bot can create update PRs correctly.

**Comment by XSAM** [comment]
The renovate bot works fine. Thank you! @arminru
