### ISSUE TITLE
Recreate the Go SIG meeting on alternate weeks

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#2091]
The Go SIG has adjusted our SIG meeting times to alternate a hour earlier every other week. To achieve this the existing meeting was updated to take place every other week and in the alternate weeks a new event was created at the earlier time. The new meeting elements were copy pasted from the existing one, but it does not show up on the calendar of those in the calendar-all@opentelemetry.io or calendar-go@opentelemetry.io groups.

It was pointed out in [slack](https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1714704544701489?thread_ts=1714672828.312909&cid=C01NJ7V1KRC) that this is likely due to https://github.com/open-telemetry/community/pull/2022/files.

Can the admin with appropriate permissions recreate our earlier meeting so they show up on the appropriate calendars?

**Comment by mtwo** [comment]
@trask will pick this up

**Comment by trask** [comment]
should be fixed now, it seems like it can take some time (maybe up to a day?) for calendar synchronization to occur, let me know if you don't see it on your calendar by tomorrow morning

**Comment by MrAlias** [comment]
Looks fixed. The meetings sync-ed to my calendar.

Thanks @trask :pray:
