### ISSUE TITLE
Verify opentelemetry.io with github.com

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2092]
I think we should roll out [Verification/Approval for our domain on GitHub](https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization). It appears to be an easy thing to do and add the same time adds an additional layer of trustworthiness.

What we need:
* A github admin that can do steps 1-5 as outlined above (Go to org settings and add a domain)
* A netlify admin that can add that TXT entry (I can do that)

**Comment by jpkrohling** [comment]
I've just done it for one of my orgs and it's straightforward.

**Comment by yurishkuro** [comment]
@svrnm can you do these?
1. Create a TXT record in your DNS configuration for the following hostname: _gh-open-telemetry-o.opentelemetry.io
2. Use this code for the value of the TXT record: c45c315455. Please note that the code will expire in 7 days.
3. Wait until your DNS configuration changes. This could take up to 72 hours to propagate.

**Comment by yurishkuro** [comment]
added

**Comment by yurishkuro** [comment]
<img width="510" alt="image" src="https://github.com/open-telemetry/community/assets/3523016/312f0457-d592-424a-b59d-be399ff6ff7e">
