### ISSUE TITLE
REQUEST: golang approver for @pjanotti

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/community#21]
### GitHub Username

@pjanotti

### Organization you are requesting membership in

open-telemetry golang (TBD)

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- [Bogdan Drutu](https://github.com/BogdanDrutu), Google
- [Rahul Patel](https://github.com/rghetia), Google

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [OpenCensus Service](https://github.com/census-instrumentation/opencensus-service/pulls?q=is%3Apr+is%3Aclosed+author%3Apjanotti)
  - [OpenCensus OC Agent Exporter](https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pulls?q=is%3Apr+is%3Aclosed+author%3Apjanotti)
- Issues responded to
  - Gitter issues for OC Service on gitter census-instrumentation/lobby
  - github issues for OC Service
- SIG projects I am involved with
  - OpenTelemetry Agent and Collector

**Comment by SergeyKanzhelev** [comment]
1. Added you as a member.
2. Created PR for initial contributors list

**Comment by pjanotti** [comment]
Thanks @SergeyKanzhelev
