### ISSUE TITLE
REQUEST: Create new team open-telemetry/semconv-security-approvers

### ISSUE THREAD

**Issue by trisch-me** [open-telemetry/community#2100]
I would like to create a group @open-telemetry/semconv-security-approvers for all PRs related to security fields in following namespaces (some of them are not present now(*) but will be added soon):

process
tls
dll*
dns*
file
registry*
user
vulnerability*
x509 Certificate*
threat*
and more namespaces to come into security field

Members of the group:
* @trisch-me (Elastic) - added
* @mjwolf (Elastic)
* @raesene (Datadog)
* @lambdanis (Isovalent)
* @mdelfabro (Dynatrace)
* @kelnage (Grafana Labs)
* @alexvanboxel (Collibra) - added

Project: https://github.com/open-telemetry/community/blob/main/projects/security-semconv.md

**Comment by trask** [comment]
(cc @open-telemetry/specs-semconv-maintainers)

**Comment by lmolkova** [comment]
nit: could you please change the suggested name to plural `semconv-security-approvers`

**Comment by arminru** [comment]
@trisch-me I created the group @open-telemetry/semconv-security-approvers and added it to our semconv repo. You can go ahead and adjust the CODEOWNERS file already.

I was able to add you @trisch-me and @alexvanboxel to the team right away. For the new faces, they'll need to become a member of the Github organization first by following the process defined at https://github.com/open-telemetry/community/blob/main/community-membership.md#member once they fulfill the requirements listed there and then we can add them as well.

**Comment by trisch-me** [comment]
Thank you @arminru 
I have wrote a comment in the original issue for everyone to become a member of otel community

**Comment by jsuereth** [comment]
Thanks @arminru !

**Comment by mjwolf** [comment]
@arminru Can you add me to this group; I'm now in the OpenTelemetry org
