### ISSUE TITLE
REQUEST: New membership for michalpristas

### ISSUE THREAD

**Issue by michalpristas** [open-telemetry/community#2102]
### GitHub Username

@michalpristas

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @TylerHelmuth 
- @ycombinator

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28824
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28864
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28877
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32185
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32479
- Ongoing work:
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32906
- PRs reviewed:
  - https://github.com/open-telemetry/opentelemetry-collector/pull/9241
  - https://github.com/open-telemetry/opentelemetry-collector/pull/8685
- Issues responded to
- SIG projects I am involved with
  - Collector

**Comment by ycombinator** [comment]
I support  🙌

**Comment by TylerHelmuth** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @michalpristas!
