### ISSUE TITLE
Generate Calendar entry and shared notes for Semantic Conventions: Tooling WG

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/community#2106]
We're splitting the semantic conventions meeting into "general" and "tooling", so we have more time to discuss schema evolution, weaver, etc.

Can you create a weekly calendar entry for Wednesdays at 7am PDT and a shared notes document?

Context: [We voted on times in our notes document](https://docs.google.com/document/d/10xG7DNKWRhxNmFGt3yYd3980a9uwS8lMl2LvQL3VNK8/edit#heading=h.yvrp5o73ixp3)

Calendar invite group: https://groups.google.com/a/opentelemetry.io/g/calendar-semconv

Thanks!

**Comment by trask** [comment]
done, I also created a new Zoom link with title "Semantic Convention Tooling" to make the different meeting recordings easier to find
