### ISSUE TITLE
New teams `docs-zh-approvers` and `docs-zh-maintainers`

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2107]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io

### Requested changes

Phase 1:
- [ ] Create a new group `docs-zh-approvers` with @windsonsea as member, and @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
- [ ] Create a new sub-group to `docs-zh-approvers` named `docs-zh-maintainers` with @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
 
### Purpose

We just launched the capability to host multiple languages on opentelemetry.io and kicked it off with a landing page at https://opentelemetry.io/zh/ from where we will grow the page (and hopefully others!) incrementally. 

@windsonsea is our first approver in this group, with more hopefully coming soon, that's why I also explicitly ask to have Doc maintainers as "group maintainers" such that we can add more individuals swiftly. We will start with having them as approvers and grow into maintainers eventually.

Note that this is different from the existing @open-telemetry/docs-cn-approvers  and @open-telemetry/docs-cn-maintainers , as we choose "zh" as language code based on [this discussion](https://github.com/open-telemetry/opentelemetry.io/issues/4465). We (docs maintainers) are already working with contributors to https://github.com/open-telemetry/docs-ja for a Japanese translation, and we will also reach out to the maintainers for https://github.com/open-telemetry/docs-cn to provide migration (see https://github.com/open-telemetry/opentelemetry.io/discussions/4302)
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/docs-maintainers

**Comment by windsonsea** [comment]
Thank you for the nomination. I feel happy to join the team.

This team will grow after migration from @open-telemetry/docs-cn-approvers.

**Comment by reyang** [comment]
Both teams have been created.

BTW, I wonder if I could join the docs-zh-approvers, I'm a native Chinese speaker and I'm familiar with the specs. Can certainly help there.

**Comment by reyang** [comment]
> @reyang of course, I just added you to the group :-)

Thanks @svrnm! ❤️
