### ISSUE TITLE
REQUEST: New membership for @akvanhar

### ISSUE THREAD

**Issue by akvanhar** [open-telemetry/community#211]
### GitHub Username

@akvanhar

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @rghetia
- @jmacd

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/search?utf8=%E2%9C%93&q=org%3Aopen-telemetry+involves%3Aakvanhar+is%3Apr&type=Issues&ref=advsearch&l=&l=
- Issues responded to
https://github.com/search?utf8=%E2%9C%93&q=org%3Aopen-telemetry+involves%3Aakvanhar+is%3Aissue&type=Issues&ref=advsearch&l=&l=
- SIG projects I am involved with
OpenTelmetry-Go

**Comment by rghetia** [comment]
approved.

**Comment by jmacd** [comment]
I sponsor Alyson. +1

**Comment by SergeyKanzhelev** [comment]
welcome!
