### ISSUE TITLE
REQUEST: Add users to group open-telemetry/sig-end-user-approvers

### ISSUE THREAD

**Issue by avillela** [open-telemetry/community#2110]
Please add the following users to @open-telemetry/sig-end-user-approvers:
* @musingvirtual 
* @AnaMMedina21 
* @IAMebonyhope

**Comment by arminru** [comment]
Done!

**Comment by arminru** [comment]
I also added all @open-telemetry/sig-end-user-maintainers to @open-telemetry/sig-end-user-approvers so you get notified too when someone tags the latter or adds the group to a PR.

**Comment by avillela** [comment]
> I also added all @open-telemetry/sig-end-user-maintainers to @open-telemetry/sig-end-user-approvers so you get notified too when someone tags the latter or adds the group to a PR.

Thank you!!
