### ISSUE TITLE
Sustainability SemConv SIG Calendar Invites and Meeting

### ISSUE THREAD

**Issue by Spazzy757** [open-telemetry/community#2111]
We have recently merged the following PR: https://github.com/open-telemetry/community/pull/2018

My understanding is that we require a meeting link as well as to be setup on the calendar

The Proposed meeting time is for: [Mondays 2:00PM - 3:00PM UCT](https://github.com/open-telemetry/community/blob/main/projects/env-semconv.md#meeting-times)

**Comment by trask** [comment]
done! let me know if there are any issues, thanks
