### ISSUE TITLE
REQUEST: Repository maintenance on open-telemetry/opentelemetry-operator

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#2112]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-operator

### Requested changes

Revoke 'mainainer' permissions from `@VineethReddy02`
 
### Purpose

Context: https://github.com/open-telemetry/opentelemetry-operator/pull/2957
 
### Repository Maintainers

- @open-telemetry/operator-maintainers

**Comment by pavolloffay** [comment]
+1

**Comment by swiatekm-sumo** [comment]
+1

**Comment by trask** [comment]
@jpkrohling @pavolloffay @swiatekm-sumo it looks like you are all listed as maintainers of @open-telemetry/operator-maintainers, which means you should be able to add/remove members from that team on your own, can you check?

**Comment by pavolloffay** [comment]
yes it worked, this ticket can be closed
