### ISSUE TITLE
Gitter is no longer accessible

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#212]
The link to Gitter chat on the readme (https://gitter.im/open-telemetry/community) goes to a page that says the Gitter room is either missing or private

![image](https://user-images.githubusercontent.com/1612643/66484419-f3dd8e00-ea74-11e9-9238-d293102713bb.png)

**Comment by jkwatson** [comment]
Same here. For all the channels that are associated with the project.

**Comment by mtwo** [comment]
I’m en route to my office but will take a look as soon as I arrive, should be about 20 mins

________________________________

**Comment by SergeyKanzhelev** [comment]
I see a few rooms, but not the community:

![image](https://user-images.githubusercontent.com/9950081/66500137-e2e14c80-ea75-11e9-9262-ba756937824d.png)

**Comment by jkwatson** [comment]
confirmed. only the community is currently gone.

**Comment by mtwo** [comment]
Same here. I'm debating whether we should try to create a new community room or if that will guarantee that we lose history. Thoughts

**Comment by SergeyKanzhelev** [comment]
the only alternative is to contact gitter support I guess...

I personally think that gitter history is not important very important. It is a channel for just-at-the-moment discussion for me and I often ignore the past even unread messages. So my vote will be to re-create

**Comment by mtwo** [comment]
Ok, I'll recreate now

**Comment by mtwo** [comment]
Done: https://gitter.im/open-telemetry/community

**Comment by bhs** [comment]
@mtwo would you be willing to file a ticket with Gitter? My main asks:

- What happened??? And can we fix permissions to make this harder in the future?
- Can the two channels (old and new) be joined somehow? I'm actually more concerned about the membership than the message history (for future `/@all`s, etc)

**Comment by mtwo** [comment]
+1, yep I'm on it. Membership is also my main concern, as previous members won't be getting notifications anymore.

**Comment by mtwo** [comment]
Filed a ticket: https://gitlab.com/gitlab-org/gitter/webapp/issues/2306

I _think_ that this is the right location for these - if they push back then I'll start a conversation over email instead

**Comment by tedsuo** [comment]
Thanks for looking into this. All the more reason to ensure that Github remains the primary place for serious discussion. :)

**Comment by SergeyKanzhelev** [comment]
@mtwo please keep us posted on the investigation. Closing this issue.
