### ISSUE TITLE
Create calendar event for OTel Q&A on June 27th (OTel End User SIG)

### ISSUE THREAD

**Issue by avillela** [open-telemetry/community#2120]
Details:

* Calendar: [calendar-end-users](https://groups.google.com/a/opentelemetry.io/g/calendar-end-users)
* Date: June 27th
* Time: 13:00 EDT/10:00 PDT

Speakers
* Austin Emmons
* Eliab Sisay

Description:
TBD

**Comment by trask** [comment]
hi @avillela! I created a placeholder for this event on the calendar, I think now that it has been created by the calendar admin, you should be able to update it as needed and calendar synchronization should work. can you give it a try, and let me know if anything doesn't work out? thanks

**Comment by avillela** [comment]
> hi @avillela! I created a placeholder for this event on the calendar, I think now that it has been created by the calendar admin, you should be able to update it as needed and calendar synchronization should work. can you give it a try, and let me know if anything doesn't work out? thanks

Thanks @trask! I've filled in the details and added in a Zoom link (Meeting 1).
