### ISSUE TITLE
REQUEST: New membership for krnowak

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/community#213]
### GitHub Username

@krnowak

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @rghetia

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [PRs where I was involved](https://github.com/search?utf8=%E2%9C%93&q=org%3Aopen-telemetry+involves%3Akrnowak+is%3Aissue&type=Issues&ref=advsearch&l=&l=)
  - opentracing bridge (https://github.com/open-telemetry/opentelemetry-go/pull/98)
  - part of metrics work (https://github.com/open-telemetry/opentelemetry-go/pull/100)
  - some bug fixes (https://github.com/open-telemetry/opentelemetry-go/pull/97, https://github.com/open-telemetry/opentelemetry-go/pull/103)
  - reviews (https://github.com/open-telemetry/opentelemetry-go/pull/150, https://github.com/open-telemetry/opentelemetry-go/pull/143, https://github.com/open-telemetry/opentelemetry-go/pull/135, https://github.com/open-telemetry/opentelemetry-go/pull/85, https://github.com/open-telemetry/opentelemetry-go/pull/117, …)
- Issues responded to
  - [Issues where I was involved](https://github.com/search?utf8=%E2%9C%93&q=org%3Aopen-telemetry+involves%3Akrnowak+is%3Aissue&type=Issues&ref=advsearch&l=&l=)

- SIG projects I am involved with
  - opentelemetry-go

**Comment by tedsuo** [comment]
+1 sponsorship from me :)

**Comment by rghetia** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
welcome, @krnowak
