### ISSUE TITLE
New teams `docs-ja-approvers` and `docs-ja-maintainers`

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2138]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io
https://github.com/open-telemetry/docs-ja

### Requested changes

- [x] Create a new group `docs-ja-approvers` with @ymotongpoo, @katzchang as member, and @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
- [x] Create a new sub-group to `docs-ja-approvers` named `docs-ja-maintainers` with @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
 
This request is similar to #2107

### Purpose

We now have our second translation at https://opentelemetry.io/ja :tada: 

@ymotongpoo, @katzchang are our first approver in this group. Eventually we also want to add @shirou but they need to become member of the Org first. We will work on that separately. 

We will also work on checking what to do with https://github.com/open-telemetry/docs-ja, so please also make the newly formed group maintainers/admins for that repository.
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/docs-maintainers

**Comment by ymotongpoo** [comment]
Thank you @svrnm for the update and logistics!

**Comment by chalin** [comment]
Thanks @svrnm.

> * [ ]  Create a new group `docs-ja-approvers` with @ymotongpoo as member, and @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
> * [ ]  Create a new sub-group to `docs-ja-approvers` named `docs-ja-maintainers` with @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)

Hmm, I'd suggest we keep things DRY: that is, keeping the membership exclusive. Concretely:

- `docs-ja-maintainers`: empty for now
- `docs-ja-approvers`: with @ymotongpoo, and `docs-ja-maintainers` as subgroup

The `zh` groups should be similarly adjusted.

We then use CODEOWNERS to achieve the effect of what was originally requested, as was done via https://github.com/open-telemetry/opentelemetry.io/pull/4584.

@svrnm et @open-telemetry/docs-maintainers WDYT?

**Comment by svrnm** [comment]
@chalin having the docs-maintainers in those groups allows us to add people without raising a community issue everytime, we can remove ourselves eventually when things have evolved.

**Comment by chalin** [comment]
Thanks for providing a rational. Ok, then instead we should add @open-telemetry/docs-maintainers as a subgroup of `docs-ja-maintainers`.

**Comment by arminru** [comment]
@chalin Unfortunately that's not possible because each team can only one parent and @open-telemetry/docs-maintainers is already a child of @open-telemetry/docs-approvers as per https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams.

**Comment by arminru** [comment]
Created @open-telemetry/docs-ja-maintainers (with Maintain permissions on https://github.com/open-telemetry/docs-ja) and @open-telemetry/docs-ja-approvers (with Write permissions on https://github.com/open-telemetry/docs-ja) as per https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams.

**Comment by arminru** [comment]
@shirou once you're a member of the https://github.com/open-telemetry org, any @open-telemetry/docs-ja-maintainers can invite you to @open-telemetry/docs-ja-approvers.

**Comment by svrnm** [comment]
Thanks @arminru
