### ISSUE TITLE
REQUEST: New membership for @g7ed6e

### ISSUE THREAD

**Issue by g7ed6e** [open-telemetry/community#2139]
### GitHub Username

@g7ed6e

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Kielek
- @vishweshbankwar

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

1. https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1493

- Issues responded to
- Community activities I organized/ran
- SIG projects I am involved with

**Comment by Kielek** [comment]
I support.

ConfluentKafka instrumentationm is about to merge. @g7ed6e is owner of this package.

**Comment by vishweshbankwar** [comment]
I support

**Comment by g7ed6e** [comment]
> @g7ed6e Please make sure to go through the outstanding ☑️ self-certifications in the issue description above.

Done! Thanks for the reminder @arminru

**Comment by arminru** [comment]
Invite sent. Welcome, @g7ed6e!
