### ISSUE TITLE
CI/CD Build Tooling Information

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#214]
Hey y'all, Bob from the opentelemetry-php community here.   Wanted to make sure our SIG understood properly:

(a) Are there common CI/CD tooling bits that we are using for opentelemetry as a whole?
(b) If so, how do we gain access to those?

**Comment by SergeyKanzhelev** [comment]
@bobstrecansky nope, there is no prescriptive or paid for tools that we are all using. For now it is just the best tool for the job.

**Comment by SergeyKanzhelev** [comment]
please re-open if you have more questions
