### ISSUE TITLE
REQUEST: New membership for emdneto

### ISSUE THREAD

**Issue by emdneto** [open-telemetry/community#2143]
### GitHub Username

emdneto

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@xrmx
@lzchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - authored in opentelemetry-python: https://github.com/open-telemetry/opentelemetry-python/pulls?q=is%3Apr+author%3Aemdneto
  - authored in opentelemetry-python-contrib: https://github.com/open-telemetry/opentelemetry-python-contrib/pulls?q=is%3Apr+author%3Aemdneto
  - reviewed in opentelemetry-python: https://github.com/open-telemetry/opentelemetry-python/pulls?q=is%3Apr+reviewed-by%3Aemdneto
  - reviewed in opentelemetry-python-contrib: https://github.com/open-telemetry/opentelemetry-python-contrib/pulls?q=is%3Apr+reviewed-by%3Aemdneto
  - other PR reviews:
    - https://github.com/open-telemetry/opentelemetry-python/pull/3875
    - https://github.com/open-telemetry/opentelemetry-python/pull/3746
    - https://github.com/open-telemetry/opentelemetry-python/pull/3859
- Issues responded to
  - opentelemetry-python: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python+is%3Aissue+commenter%3Aemdneto+&type=issues
  - opentelemetry-python-contrib: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib+is%3Aissue+commenter%3Aemdneto+&type=issues
- Community activities I organized/ran
  - [First Meetup Cloud Native RN](https://community.cncf.io/events/details/cncf-cloud-native-rio-grande-do-norte-presents-1o-meetup-cloud-native-rn/) from CNCF Community Groups
- SIG projects I am involved with
  - SIG Python

**Comment by xrmx** [comment]
I support

**Comment by lzchen** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @emdneto!
