### ISSUE TITLE
REQUEST: New membership for @katzchang

### ISSUE THREAD

**Issue by katzchang** [open-telemetry/community#2146]
### GitHub Username

@katzchang

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @ymotongpoo 
- @svrnm 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry.io/pull/4616
- https://github.com/open-telemetry/opentelemetry.io/pull/4580
- https://github.com/open-telemetry/docs-ja
- Holding local user community (3 times including scheduled): https://opentelemetry.connpass.com/

**Comment by ymotongpoo** [comment]
I support @katzchang 's membership of JA docs approvers

**Comment by svrnm** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @katzchang!

**Comment by katzchang** [comment]
Joined! Thanks Team!!
