### ISSUE TITLE
REQUEST: Move the donated profiling agent `elastic/otel-profiling-agent` to `open-telemetry/opentelemetry-profiling-agent`

### ISSUE THREAD

**Issue by rockdaboot** [open-telemetry/community#2149]
The OpenTelemetry GC has accepted the [donation proposal of the Elastic profiling agent](https://github.com/open-telemetry/community/issues/1918).

[Blog post](https://opentelemetry.io/blog/2024/elastic-contributes-continuous-profiling-agent/)

In order to get the agent code into the open-telemetry Github namespace, we can either
1. Create a new repository and move the code into it.
2. Rename the existing repository `elastic/otel-profling-agent` into `open-telemetry/opentelemetry-profiling-agent`.

(The name `opentelemetry-profiling-agent` is just a suggestion and open to change.)

Option 2 is preferred, because it has the benefit of keeping existing issues, pull requests stars, watchers and forks. It had already significant exposure to the public (2k stars, 200+ forks).

### Affected Repositories

https://github.com/elastic/otel-profiling-agent

https://github.com/open-telemetry/opentelemetry-profiling-agent

### Requested changes

Move the elastic repository to open-telemetry.

### Purpose

Further work on the profiling agent should be done under the umbrella of OpenTelemetry.
 
### Expected Duration

ASAP

### Repository Maintainers

tbd

**Comment by AlexanderWert** [comment]
@open-telemetry/technical-committee
@open-telemetry/governance-committee

Can you help us with that, please? We'd like to kick-off the repo asap, so we can start the work on integrating the agent into OTel.

**Comment by tigrannajaryan** [comment]
I personally like option 2. As far as I remember we have never done this in the past, so we will need to double check the implications. I will add this to tomorrow's TC meeting agenda and will post back here.

**Comment by svrnm** [comment]
> I personally like option 2. As far as I remember we have never done this in the past, so we will need to double check the implications. I will add this to tomorrow's TC meeting agenda and will post back here.

Although preferred, the challenge is that you need someone who has the permission to move a repository in **both organisations**, so either someone from Elastic gets (temporary) permissions in the otel org to move, or someone from OpenTelemetry gets (temporary) permissions in the elastic org to move.

**Comment by rockdaboot** [comment]
> > I personally like option 2. As far as I remember we have never done this in the past, so we will need to double check the implications. I will add this to tomorrow's TC meeting agenda and will post back here.
> 
> Although preferred, the challenge is that you need someone who has the permission to move a repository in **both organisations**, so either someone from Elastic gets (temporary) permissions in the otel org to move, or someone from OpenTelemetry gets (temporary) permissions in the elastic org to move.

I think you refer to a move/rename from one org to another when staying the owner. In this case you need permissions on both orgs.

But here it may be different (from https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository):
```
When you transfer a repository that you own to another personal account, the new owner will receive a confirmation email. The confirmation email includes instructions for accepting the transfer. If the new owner doesn't accept the transfer within one day, the invitation will expire.
```

**Comment by dmathieu** [comment]
> another personal account

This transfer is not to a personal account.

In this case, I think this rule from the doc you linked applies:

> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization. If organization owners have disabled repository creation by organization members, only organization owners can transfer repositories out of or into the organization.

**Comment by dmathieu** [comment]
One (rather intricate) way to do this could be to move the repository from the elastic organization into the personal account of an open-telemetry owner, who would then be able to move it to the open-telemetry organization.

**Comment by AlexanderWert** [comment]
> > I personally like option 2. As far as I remember we have never done this in the past, so we will need to double check the implications. I will add this to tomorrow's TC meeting agenda and will post back here.
> 
> Although preferred, the challenge is that you need someone who has the permission to move a repository in **both organisations**, so either someone from Elastic gets (temporary) permissions in the otel org to move, or someone from OpenTelemetry gets (temporary) permissions in the elastic org to move.

Since it's something that should take too long, we could do that "transaction" maybe even in a sync call between someone with corresponding rights from Otel and Elastic. So in that call we could:

- grant permission to the other org
- transfer the repo
- remove the permission again

**Comment by tigrannajaryan** [comment]
Update from the TC:
- We will need the GC's help to figure the legal aspects of the transfer and how the CLA should be applied if the repo is moved and not created from scratch.
- We would like to seed the repo with 1 or 2 maintainers from Elastic and also add 1 or 2 maintainers from other companies. We will ask the current maintainers of Profiling SIG to see if they are interested.

**Comment by trask** [comment]
> We will need the GC's help to figure the legal aspects of the transfer and how the CLA should be applied if the repo is moved and not created from scratch.

I've opened a legal ticket with the CNCF service desk to ask if we need Elastic to sign an IP transfer (https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2343)

**Comment by brancz** [comment]
I would propose @umanwizard and @gnurizen to participate in maintaining it. They are maintainers of the Parca Agent (a very similar project that we expect to merge with or make a consumer of the otel agent as a library, it doesn’t make sense to reinvent the same things).

**Comment by tigrannajaryan** [comment]
As posted earlier we will be seeding the profiling agent maintainers from 2 sources: current Profiling SIG maintainers and current agent maintainers suggested by Elastic (1 or 2 maintainers).

@felixge @petethepig will be the Profiling SIG maintainers that will become profiling agent maintainers.

More maintainers can be added in the future via the process [describe here](https://github.com/open-telemetry/community/blob/main/community-membership.md#becoming-a-maintainer).

**Comment by felixge** [comment]
Option 2 (rename repo) sounds good to me.

> (The name opentelemetry-profiling-agent is just a suggestion and open to change.)

I think the name is okay, but maybe it's worth considering some other options as well. A few ideas in my personal order of preference:

1. opentelemetry-host-profiler
2. opentelemetry-ebpf-profiler
3. opentelemetry-system-profiler

What I like about these names is that they make it clear that there will also be other OTel SDK profilers. The term agent is also often used in Java for byte code instrumentation. I'm curious what other people here think.

**Comment by mtwo** [comment]
+1 to Felix’s name suggestions, I was meaning to to reply with the same feedback
________________________________

**Comment by svrnm** [comment]
+1 for not using the term agent, we had way to many discussions where to use it and where to not use it and since the much better term "profiler" exists, I also prefer that.

In the part between opentelemetry and profiler: is there any possibility that there is a host (or system?) profiler that is not ebpf based? Even if it is not created or maintained within the otel project. Being specific about the technology (so picking 'ebpf') might help to avoid future confusion.

**Comment by felixge** [comment]
> In the part between opentelemetry and profiler: is there any possibility that there is a host (or system?) profiler that is not ebpf based?

Yes. There are many host profilers that don't use eBPF, e.g. [perf](https://en.wikipedia.org/wiki/Perf_(Linux)), [samply](https://github.com/mstange/samply/tree/main), [bytehound](https://github.com/koute/bytehound) or [ddprof](https://github.com/DataDog/ddprof).

> Even if it is not created or maintained within the otel project. Being specific about the technology (so picking 'ebpf') might help to avoid future confusion.

That would make sense to me. The elastic profiler seems to be pretty tied to eBPF right now, and even if it gains non-eBPF based capabilities, I don't see the eBPF parts going away anytime soon. But the elastic folks should obviously chime in on this.

**Comment by rockdaboot** [comment]
> As posted earlier we will be seeding the profiling agent maintainers from 2 sources: current Profiling SIG maintainers and current agent maintainers suggested by Elastic (1 or 2 maintainers).

For Elastic, @christos68k will be the Profiling SIG maintainer that will become profiling agent maintainer.
As current agent maintainers, we'd like @athre0z and @fabled to become profiling agent maintainers.

The membership for @fabled is [in progress](https://github.com/open-telemetry/community/issues/2155).

**Comment by rockdaboot** [comment]
> I think the name is okay, but maybe it's worth considering some other options as well. A few ideas in my personal order of preference:
> 
>     1. opentelemetry-host-profiler
>     2. opentelemetry-ebpf-profiler
>     3. opentelemetry-system-profiler

Thanks for your suggestions, @felixge

The profiling agent team at Elastic prefers 2 or 3, without a particular tendency to either one of them.

**Comment by AlexanderWert** [comment]
@trask is there an update already on the legal ticket?

**Comment by trask** [comment]
nothing yet, I just followed up

**Comment by felixge** [comment]
> The profiling agent team at Elastic prefers 2 or 3, without a particular tendency to either one of them.

@rockdaboot I think I'd prefer `opentelemetry-ebpf-profiler` over `opentelemetry-system-profiler` would be me preference for the reasons [outlined above](https://github.com/open-telemetry/community/issues/2149#issuecomment-2176314708).

**Comment by rockdaboot** [comment]
> > The profiling agent team at Elastic prefers 2 or 3, without a particular tendency to either one of them.
> 
> @rockdaboot I think I'd prefer `opentelemetry-ebpf-profiler` over `opentelemetry-system-profiler` for the reasons [outlined above](https://github.com/open-telemetry/community/issues/2149#issuecomment-2176314708).

Then we are at 3:0 for `opentelemetry-ebpf-profiler`. Is there anyone else pro or con this name?

**Comment by yanglong1010** [comment]
Is there an expected time for the migration of otel-profiling-agent to open-telemetry?

**Comment by AlexanderWert** [comment]
> Is there an expected time for the migration of otel-profiling-agent to open-telemetry?

We are blocked by / waiting for the reply on the above-mentioned legal ticket.

**Comment by trask** [comment]
sorry all, I've followed up multiple times with CNCF legal and no response yet 😞

**Comment by trask** [comment]
it has been officially escalated now 🤞

**Comment by trask** [comment]
Got a response back from CNCF legal, they're drafting a contribution agreement to document the movement of the repo and the project name. They say that's all we need. They'll ping me when that's ready.

**Comment by trask** [comment]
CNCF Legal sent us a draft agreement. We just need to review the doc and make sure everything looks good. And get it signed.

@mtwo @AlexanderWert I'll share the agreement with you over Slack, let me know if I should include anyone else, thanks!

**Comment by mtwo** [comment]
Thanks @trask! Replied on Slack, but @AlexanderWert I think that the next step is to get Elastic legal to sign this?

**Comment by rockdaboot** [comment]
Update: The legal topics have been cleared, now the transfer is mostly a matter of coordination, which is in progress.

**Comment by austinlparker** [comment]
The repository has been moved. For future reference, this is the least privileged way we discovered to move it:

- Invite an admin (or other member with appropriate permissions) from the transferring side to the open-telemetry GH org.
- Temporarily change the organization permissions to allow for org members to create public repositories.
- Initiate the transfer, then once completed, reset the repo creation permissions and remove the transferrer from the org.

**Comment by austinlparker** [comment]
ok, should be good to go

**Comment by rockdaboot** [comment]
The new repository for the agent code is https://github.com/open-telemetry/opentelemetry-ebpf-profiler.

The repository maintainers are
https://github.com/athre0z (Elastic)
https://github.com/fabled (Elastic)
https://github.com/felixge (Datadog)
https://github.com/petethepig (Grafana/Pyroscope)

I'd like to thank everybody who was involved in the transfer, discussions and background work!

Happy contributing 🎉
