### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-rust

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/community#2150]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-rust

### Requested changes

Please grant access to the `actuated` app to this repository.
Related: https://github.com/open-telemetry/community/issues/1821 and https://github.com/open-telemetry/community/issues/1162
 
### Purpose

Run our CI pipeline natively on the ARM, to validate the compatibility with ARM architecture.

### Expected Duration

Permanently

### Repository Maintainers

- @open-telemetry/rust-maintainers

**Comment by cijothomas** [comment]
Agree with this. (I am one of the otel rust maintainers)

**Comment by arminru** [comment]
Done!

Do you need the same change for https://github.com/open-telemetry/opentelemetry-rust-contrib too?

**Comment by trask** [comment]
> Run our CI pipeline natively on the ARM, to validate the compatibility with ARM architecture.

do you think we can use the just recently released official GitHub ARM runners instead?

https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

> "We leveraged Arm runners to very quickly set up a workflow to build a Linux Arm64 binary for our open source Rust project, Spice.ai OSS, and it’s been rock-solid–we haven’t had any issues with it since we set it up."

**Comment by trask** [comment]
I created a GitHub Linux ARM64 runner (#2156) in case you are able to try that out

**Comment by lalitb** [comment]
> I created a GitHub Linux ARM64 runner (https://github.com/open-telemetry/community/issues/2156) in case you are able to try that out

Thanks, let me try it out.

> Do you need the same change for https://github.com/open-telemetry/opentelemetry-rust-contrib too?

Yes @arminru we would need this to be setup for the `opentelemetry-rust-contrib` too. Just in case the official Github ARM runner created by @trask doesn't work for us:)

**Comment by arminru** [comment]
Thanks @trask!

@lalitb I enrolled rust-contrib for self-actuated as well.
