### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-cpp

### ISSUE THREAD

**Issue by esigo** [open-telemetry/community#2151]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-cpp 
### Requested changes

Please grant access to the `actuated` app to this repository.

 
### Purpose

run our CI suite on ARM, so we can update our compatibility matrix with that architecture.
https://github.com/open-telemetry/opentelemetry-cpp/issues/1417
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/cpp-maintainers

**Comment by marcalff** [comment]
+1 as otel-cpp maintainer

**Comment by esigo** [comment]
@arminru thanks main repo is enough.
The runner is also tested in the CI.

**Comment by trask** [comment]
I've given permission for opentelemetry-cpp to use the new official ARM64 GitHub Action runner, check out #2156 and see if you can use that instead of actuated if possible
