### ISSUE TITLE
REQUEST: New membership for @athre0z

### ISSUE THREAD

**Issue by athre0z** [open-telemetry/community#2152]
### GitHub Username

@athre0z

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@christos68k
@mtwo

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Been a maintainer of and an active contributor to the recently [donated OTel profiling agent](https://github.com/open-telemetry/community/issues/1918) for 3-4 years now
- Active member of the Profiling SIG for ~6 months now
  - Recently did a [presentation on the profiler internals](https://www.youtube.com/watch?v=4zEpvNJ8r4I)
  - Worked out a detailed [comparison between two symbolization protocol options](https://docs.google.com/document/d/1jStTplInNIb9x7v_1DFqXkjKPDnXRSLu3ps5pdblU6k/edit#heading=h.qeazsbsfbtsw)

**Comment by christos68k** [comment]
I support!

**Comment by mtwo** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @athre0z!
