### ISSUE TITLE
Create an ARM64 GitHub Actions Runner that repositories can use to build / test on ARM64

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#2156]
Opening as a public tracking issue, it looks like I have access to create it.

(see https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/)

**Comment by trask** [comment]
![image](https://github.com/open-telemetry/community/assets/218610/7d43e4a8-4086-4271-aca5-59a7e10209b7)

**Comment by lalitb** [comment]
Is this the correct runner - `otel-linux-arm64`, as it doesn't seem to work - https://github.com/open-telemetry/opentelemetry-rust/actions/runs/9522286107/job/26251528030?pr=1884

**Comment by trask** [comment]
it looks like we have to give permission to the runner for each repository, I've given permission to opentelemetry-rust and opentelemetry-rust-contrib now

**Comment by trask** [comment]
I've also given permission to opentelemetry-cpp (#2151)

**Comment by trask** [comment]
I've updated the runner to 4-cores to match the default linux runners (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)

**Comment by trask** [comment]
I also created `otel-linux-arm64-8-cores` for comparison testing

**Comment by trask** [comment]
I also gave permission to the ARM64 runners to the opentelemetry-demo repository (cc @austinlparker)

**Comment by dmathieu** [comment]
Note that some SIGs are using actuated to do this (not on windows).
https://github.com/open-telemetry/community/blob/main/docs/using-actuated.md

**Comment by pellared** [comment]
@trask, can you please give permissions for:

- https://github.com/open-telemetry/opentelemetry-dotnet
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation
- https://github.com/open-telemetry/opentelemetry-go
- https://github.com/open-telemetry/opentelemetry-go-contrib
- https://github.com/open-telemetry/opentelemetry-go-instrumentation

CC @open-telemetry/dotnet-maintainers @open-telemetry/dotnet-instrumentation-maintainers @open-telemetry/go-maintainers @open-telemetry/go-instrumentation-maintainers

**Comment by pellared** [comment]
Shouldn't we create docs similar to https://github.com/open-telemetry/community/blob/main/docs/using-actuated.md?

**Comment by trask** [comment]
> Shouldn't we create docs similar to https://github.com/open-telemetry/community/blob/main/docs/using-actuated.md?

👍 sent #2201

**Comment by trask** [comment]
> @trask, can you please give permissions for:
> 
> * https://github.com/open-telemetry/opentelemetry-dotnet
> * https://github.com/open-telemetry/opentelemetry-dotnet-contrib
> * https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation
> * https://github.com/open-telemetry/opentelemetry-go
> * https://github.com/open-telemetry/opentelemetry-go-contrib
> * https://github.com/open-telemetry/opentelemetry-go-instrumentation

done

**Comment by pellared** [comment]
> we can also create a Windows ARM64 runner if needed

@trask, can you please create it? It will be helpful for .NET repositories.

**Comment by trask** [comment]
done, runner name is `otel-windows-arm` (and added it to #2201)

**Comment by codeboten** [comment]
Would love to test this out for the collector as well:
* https://github.com/open-telemetry/opentelemetry-collector
* https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by trask** [comment]
> Would love to test this out for the collector as well:
> 
> * https://github.com/open-telemetry/opentelemetry-collector
> * https://github.com/open-telemetry/opentelemetry-collector-contrib

✅

**Comment by trask** [comment]
this seems to be working, closing
