### ISSUE TITLE
project onboarding: Feature Flag Semantic Conventions

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2157]
The Feature Flag Semantic Conventions SIG project proposal has been approved, here are the todos to get them started:

- [ ] Project Board
- [ ] Add Meeting Times, GC Liaison, Slack Channel, Google Doc to sigs.yml
- [ ] SIG Channel
- [ ] GitHub Teams

cc @dyladan @AlexanderWert @beeme1mr

**Comment by trask** [comment]
@open-telemetry/semconv-feature-flag-approvers created with following maintainers:

* @dyladan 
* @AlexanderWert
