### ISSUE TITLE
HTTP instrumentation push

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2159]
We want language SIGs to adopt the stable HTTP semantic conventions, for that we need a project proposal and individuals who care to push this forward, cc @trask

**Comment by danielgblanco** [comment]
I agree with @trask above. For this particular case, is this something that SIG liaisons can sync with their SIGs and see where this currently sits in their priorities (for those that have not adopted them).

**Comment by svrnm** [comment]
> can we add semconv version to the registry somehow, so we can see which instrumentations have implemented it and which haven't?

Yes, we can add this! However we have to make sure that people populate that field and keep it up to date, see https://github.com/open-telemetry/community/pull/2246
