### ISSUE TITLE
REQUEST: Repository maintenance on teams/lambda-extension-approvers

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#2164]
### Affected Repository

https://github.com/orgs/open-telemetry/teams/lambda-extension-approvers

### Requested changes

Please remove @tsloughter and add @nslaughter 

See also: https://github.com/open-telemetry/opentelemetry-lambda/pull/1399
 
### Purpose

Nathan is replacing Tristan as approver.
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/lambda-extension-approvers
- @open-telemetry/lambda-extension-maintainers

**Comment by nslaughter** [comment]
Thank you to Tristan and the maintainers continuing the effort.

**Comment by trask** [comment]
@open-telemetry/technical-committee can you give @tylerbenson and @rapphil maintainer rights to the lambda-extension-* teams so they can manage the membership themselves?

**Comment by arminru** [comment]
> @open-telemetry/technical-committee can you give @tylerbenson and @rapphil maintainer rights to the lambda-extension-* teams so they can manage the membership themselves?

Done!
