### ISSUE TITLE
KubeCon+CloudNativeCon NA 2024 - Observatory / Project Pavilion

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2170]
One of the [project opportunities](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/project-opportunities/#about-project-participation) during KubeCon+CloudNativeCon NA 2024 is the In-Person Kiosk (also known as Project Pavilion). For the last 2 KubeCons we had the Observatory. This issue here is to track what we do (the kiosk, the observatory, how we staff it, etc.)

cc @open-telemetry/governance-committee

**Comment by mtwo** [comment]
Update: we're checking if we can place the Observatory within the Project Pavilion
