### ISSUE TITLE
KubeCon+CloudNativeCon NA 2024 - Maintainer track

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2171]
One of the [project opportunities](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/project-opportunities/#about-project-participation) during KubeCon+CloudNativeCon NA 2024 is the "Maintainer Track", in our case this presentation is done by members of the @open-telemetry/governance-committee. 

This issue can serve to collect ideas on what we'll be talking about, as well as to collect information on who from the GC is going to run this.

**Comment by jpkrohling** [comment]
Who's submitting this proposal?

**Comment by jpkrohling** [comment]
@austinlparker is handling that as part of this board item: https://github.com/orgs/open-telemetry/projects/96?pane=issue&itemId=68233968

**Comment by austinlparker** [comment]
I've submitted the proposal today.

**Comment by trask** [comment]
this talk was accepted
