### ISSUE TITLE
KubeCon+CloudNativeCon NA 2024 - Contribfest

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2172]
One of the [project opportunities](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/project-opportunities/#about-project-participation) during KubeCon+CloudNativeCon NA 2024 is the "Contribfest"

The CFP closes on Monday, July 22.

Here's the issue from EU this year: https://github.com/open-telemetry/community/issues/1797, we didn't get accepted since there was already a contribfest during NA'23, so our chances might be higher.

Here's the draft proposal:

> Join the OpenTelemetry maintainers to make the project better for everyone. You can choose between several opportunities to contribute, and you can count on maintainers from different project areas to help you on your first steps: documentation, Collector, Java, JS, Ruby, Python, .NET, and more. 

If you are interested in joining, please leave a comment stating which SIG(s) you'd be representing and your role in them.

Here's the list of people who would be the official speakers, getting a free ticket if our contrib fest proposal is accepted:
* @trask (GC, Java maintainer, Semconv approver)
* @Kielek (.NET, maintainer)
* @JamieDanielson (JS, maintainer)
* @mx-psi (SemConv approver, Collector maintainer)

And here are the people who volunteered to be there, should they be able to go to KubeCon:
* @cijothomas (Rust maintainer)
* @codeboten (Collector, Security, Config, maintainer)
* @djaglowski (Collector, maintainer)
* @dmitryax (Collector, maintainer)
* @dyladan (GC, JS, maintainer)
* @jpkrohling  (GC, Collector, Security, maintainer)
* @pichlermarc (JS, maintainer)
* @maryliag (JS, triager)
* @TylerHelmuth (Collector, SemConv, Operator, Helm, maintainer)
* @yuriolisa (Operator, approver) (edited)

**Comment by jpkrohling** [comment]
The following people expressed interest in the past and are more than welcome to volunteer this time again :-) 

@Kielek (.NET)
@yuriolisa (Operator)
@djaglowski (Collector)
@trask (Java and Semantic Conventions)
@pichlermarc (JS)

**Comment by mx-psi** [comment]
I am interested in participating on this as a speaker :)

**Comment by TylerHelmuth** [comment]
Id like to help as well

**Comment by yuriolisa** [comment]
I'd like to help on this also.

**Comment by codeboten** [comment]
happy to help as well

**Comment by dmitryax** [comment]
I'm in!

**Comment by jpkrohling** [comment]
I was pointed out to a decision the GC made last time, that speaker slots are a decision of the full GC. While I don't remember that specific part being discussed, I wanted to record this decision here and apply it for this time as well.

From the CNCF perspective, only the GC and TC members are maintainers. Therefore, I'm moving everyone to a single "volunteers" list and will try to get the GC/TC to agree on a list of speakers by Friday, July 22.

I apologize for this confusion.

**Comment by jpkrohling** [comment]
Status update: we talked about this yesterday during the GC call, and we agreed that we'll have the following priority order for the contrib fest:

1. GC/TC members who are *also* maintainers
2. Other Maintainers
3. Other GC/TC members

In addition, we prefer to have at most one representative per SIG.

**Comment by cijothomas** [comment]
I'll help from OTel Rust side. I am one of the maintainers.

**Comment by jpkrohling** [comment]
I just submitted the proposal, including @trask, @Kielek, @JamieDanielson, and @mx-psi as speakers. All others are invited to help on-site, should our proposal get accepted.

**Comment by jpkrohling** [comment]
The proposal was selected! We have the very last session at KubeCon, but hey, better than nothing :-)

**Comment by codeboten** [comment]
Should this issue be closed or is the plan to use it to coordinate? Here's a link to the session: https://sched.co/1hoyF

**Comment by jpkrohling** [comment]
I think this can be closed. I created the private channel #otel-contribfest-2024-na for coordination and added the official speakers, as it's clear they will be there. Anyone else who knows already they'll be there can ping me and I'll include them there.
