### ISSUE TITLE
KubeCon+CloudNativeCon NA 2024 - 5-Minute Lightning Talk

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2173]
One of the [project opportunities](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/project-opportunities/#about-project-participation) during KubeCon+CloudNativeCon NA 2024 is the "5-Minute Lightning Talk", last year this was delivered by @tedsuo and @trask

**Comment by trask** [comment]
@austinlparker and @danielgblanco will be doing this lightning talk
