### ISSUE TITLE
REQUEST: New membership for jaydeluca

### ISSUE THREAD

**Issue by jaydeluca** [open-telemetry/community#2177]
### GitHub Username

@jaydeluca

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @svrnm 
- @trask 

#### opentelemetry-java-instrumentation
* [Update docs for bundled exporters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11662)
* [Add support for informix connection string parsing in jdbc instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11542)
* [Convert struts tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11468)
* [Remove unneeded groovy dependencies](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11467)
* [Convert tomcat 10 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11420)
* [Convert tomcat 7 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11402)
* [Add tests for sap db missed in migration](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11367)
* [Update camel tests to use RpcIncubatingAttributes](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11253)
* [Convert aws sdk 2.2 sqs tracing tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11240)
* [Convert jdbc library tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11178)
* [Convert couchbase client 3.1 from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10880)
* [Convert aws 1.11 SQS receive span suppression tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10660)
* [Convert aws 1.11 SQS tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10657)
* [Update Spring autoconfigure and zipkin starter readmes to link to doc site](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10531)
* [update sqs and sns attributes for camel tests](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10168)
* [Convert lettuce 5.1 SyncClientAuthTest from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10045)
* [Convert lettuce 5.1 Async client tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9994)
* [Convert lettuce 5.1 reactive client tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9876)
* [Convert log4j context-data tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9804)
* [Convert lettuce 5.1 SyncClientTest from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9697)
* [Convert tapestry tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9684)
* [Convert internal-url-class-loader javaagent integration tests](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9614)
* [Convert internal-reflection tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9612)
* [Convert internal-lambda test from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9611)
* [Convert external-annotations javagent unit tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9582)
* [Convert internal-class-loader tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9560)
* [Convert external-annotations javaagent tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9557)
* [Convert lettuce-5.0 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9547)
* [Convert logback-mdc-1.0 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9490)
* [Convert lettuce-common test from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9430)
* [Convert couchbase-2-common javaagent unit tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9426)
* [Remove unneeded spock test dependency for camel tests](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9420)
* [Convert Lettuce 4.0 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9419)
* [Convert hibernate-procedure-call-4.3 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9290)
* [Convert Hibernate-4.0 groovy tests - part 3](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9282)
* [Convert hibernate-4.0 groovy tests - part 2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9249)
* [Convert hystrix 1.4 test from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9217)
* [Convert hibernate-4.0 groovy tests - part 1](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9211)
* [Convert hibernate-4.0 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9191)
* [Convert hibernate-3.3 tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9025)
* [Convert async-http-client tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8954)
* [Convert camel-2-20 aws tests from groovy to java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8906)
* [Convert camel-2.20 Groovy tests to Java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8813)

#### opentelemetry.io
* [Add clarity to java sdk config descriptions around endpoints](https://github.com/open-telemetry/opentelemetry.io/pull/4748)
* [Update Java SDK Configuration page](https://github.com/open-telemetry/opentelemetry.io/pull/4579)
* [Move java sdk configuration documentation into docs site](https://github.com/open-telemetry/opentelemetry.io/pull/4377)
* [Update java metric instrumentation docs](https://github.com/open-telemetry/opentelemetry.io/pull/4165)
* [Document configuration options for java agent enduser attribute collection](https://github.com/open-telemetry/opentelemetry.io/pull/3982)
* [Move the Spring Auto-Configuration doc](https://github.com/open-telemetry/opentelemetry.io/pull/3900)

#### opentelemetry-java-contrib
* [Update JMX metrics to support both a script and target systems](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1339)

#### opentelemetry-java-examples
* [Exponential histogram example](https://github.com/open-telemetry/opentelemetry-java-examples/pull/396)
* [add view examples](https://github.com/open-telemetry/opentelemetry-java-examples/pull/381)
* [Remove empty objects from file-configuration](https://github.com/open-telemetry/opentelemetry-java-examples/pull/264)

#### opentelemetry-java
* [Reference configuration documentation on opentelemetry.io](https://github.com/open-telemetry/opentelemetry-java/pull/6491)

#### opentelemetry-configuration
* [Document time value units in kitchen-sink example](https://github.com/open-telemetry/opentelemetry-configuration/pull/51)

#### opentelemetry-specification
* [Rework metric signal overview](https://github.com/open-telemetry/opentelemetry-specification/pull/3916)

#### opentelemetry-proto
* [Add markdown linting to makefile and github actions](https://github.com/open-telemetry/opentelemetry-proto/pull/494)

#### opentelemetry-collector-contrib
* [[chore] fix exhaustive lint for processor spanprocessor (#23266)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23952)

**Comment by svrnm** [comment]
I support

**Comment by trask** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @jaydeluca!
