### ISSUE TITLE
Contributor Guide points LFX deprecated EasyCLA V1 Link

### ISSUE THREAD

**Issue by thatsdone** [open-telemetry/community#2180]
I noticed that "[Sign CLA](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#sign-the-cla)" section of "OpenTelemetry Contributor Guide" is redirected to the LFX EasyCLA V1(deprecated) page as of July 2, 2024.

This could be an LFX side issue, but which EasyCLA do we require?
V1 or V2?

If we prefer V2, I think it's better explicitly note so and use:

https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors

instead of:

https://docs.linuxfoundation.org/lfx/easycla/contributors (currently used link).

**Comment by svrnm** [comment]
I would assume that we use V2, but I am not 100% sure, @open-telemetry/technical-committee @open-telemetry/governance-committee does anyone know which version we use and if this can be fixed easily?

**Comment by danielgblanco** [comment]
FYI I think that link in the guide will disappear when https://github.com/open-telemetry/community/pull/2051 is merged. Following the GitHub check "more details" link on any PR takes us to https://easycla.lfx.linuxfoundation.org/#/?version=2 so I can assume we're using V2 but the docs were outdated.

**Comment by austinlparker** [comment]
Is this still an issue?

**Comment by thatsdone** [comment]
@austinlparker 
I think this commit https://github.com/open-telemetry/community/commit/34f771c34a80c057a3b7e167009111fa1ae097bc fixed the issue, and You can close it now.
