### ISSUE TITLE
Request to use Dosu on selected repositories

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#2183]
@svrnm mentioned on a thread on the GC/TC Slack channel about a page with the tools we have available for being part of the CNCF, and among those, there's [Dosu](https://dosu.dev). We discussed this tool today during the Collector SIG and we would like to try it out on two repositories: 

- open-telemetry/opentelemetry-helm-charts
- open-telemetry/opentelemetry-collector-releases

Those are relatively small repositories that would allow us to try it out, while still limiting the possible damage in terms of noise. 

I created an OpenTelemetry organization on that tool, and requested its installation via GitHub, and would like to ask someone at the TC to approve this request.

Permissions requested by the app:
* Read access to actions, administration, checks, code, commit statuses, and metadata
* Read and write access to discussions, issues, and pull requests

Examples of it in action (from @yurishkuro):
* Example of the bot answering question in Jaeger https://github.com/orgs/jaegertracing/discussions/5728

Reference: https://github.com/open-telemetry/community/blob/main/docs/using-github-extensions.md

**Comment by jpkrohling** [comment]
cc @open-telemetry/technical-committee

**Comment by svrnm** [comment]
I support!

**Comment by yurishkuro** [comment]
example of Dosa bot answering question in Jaeger https://github.com/orgs/jaegertracing/discussions/5728

**Comment by trask** [comment]
I support

**Comment by trask** [comment]
I think we need a majority of GC members to support based on https://github.com/open-telemetry/community/blob/main/docs/using-github-extensions.md#requesting-installing-of-apps-extensions-or-bots

> GC member needs to approve with no other GC members raising concerns. It is recommended to discuss each extension, app, or bot that is about to be installed at GC meeting for awareness.

**Comment by jpkrohling** [comment]
@open-telemetry/governance-committee, can you take a look and approve or share your concerns? OTel Collector folks, among other SIGs, are interested in trying this out.

**Comment by austinlparker** [comment]
sgtm

**Comment by danielgblanco** [comment]
I support, trialling it in those two repos seems like a good way forward to evaluate its usefulness.

**Comment by jpkrohling** [comment]
Thanks! We have GC majority now:

- @jpkrohling 
- @svrnm 
- @austinlparker 
- @trask 
- @danielgblanco 

@open-telemetry/technical-committee, would you please install Dosu?

**Comment by dyladan** [comment]
I support

**Comment by trask** [comment]
looks like this has been installed now

**Comment by jpkrohling** [comment]
For reference, here's one example of the bot in action: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/603
