### ISSUE TITLE
REQUEST: Repository maintenance on open-telemetry/opentelemetry-js

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/community#2188]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-js
https://github.com/opentelemetrybot/opentelemetry-js

### Requested changes

Please fork https://github.com/open-telemetry/opentelemetry-js to @opentelemetrybot :slightly_smiling_face: 
 
### Purpose

We'd like to use a workflow (see https://github.com/open-telemetry/opentelemetry-js/pull/4849) that uses the @opentelemetrybot to create release PRs. These PRs will be opened by @opentelemetrybot, targeting https://github.com/open-telemetry/opentelemetry-js. As we don't want to give the bot user write permissions on the repo, we opt to use the bot user's fork to create the PR. However, the bot user does not have a fork yet (AFAIK that needs to be done manually).
 
### Expected Duration

permanent

### Repository Maintainers

- @open-telemetry/javascript-maintainers 

### Additional Notes

Not sure if this is the correct request type as I'm not really requesting changes to the https://github.com/open-telemetry/opentelemetry-js repo, but it was the closest match I could find  :slightly_smiling_face:

**Comment by svrnm** [comment]
tbh, I was not aware that renovate is working in a similar way that the bot forks all the repos and then creates PRs from there. Although some extra effort that would remove the necessity to create branch exceptions as we have outlined them right now

**Comment by pichlermarc** [comment]
Ah, I actually just realized we could likely just use the token we already have access to to fork the repo in first step of the workflow, so no manual intervention is needed :facepalm:  

Closing this issue - will re-open in case we find that that's not possible, but I figure if we can write then we can also fork. :slightly_smiling_face:
