### ISSUE TITLE
REQUEST: Repository maintenance on open-telemetry/sig-contributor-experience

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2191]
### Affected Repository

https://github.com/open-telemetry/sig-contributor-experience

### Requested changes

Create repository and create teams:

@open-telemetry/sig-contributor-experience-approvers
`- @open-telemetry/sig-contributor-experience-maintainers

Add @JamieDanielson @jpkrohling @mx-psi @theletterf @musingvirtual @svrnm as maintainers

### Purpose

We formed the SIG Contributor Experience and the repo should serve as a place to store common documents, drafts, create issues to work on, etc.
 
### Expected Duration

permanently

### Repository Maintainers

@jpkrohling @mx-psi @theletterf @musingvirtual

**Comment by svrnm** [comment]
@open-telemetry/technical-committee @austinlparker @trask can someone help us here to move forward? Thanks!

**Comment by yurishkuro** [comment]
doing it

**Comment by yurishkuro** [comment]
I created the repo and two teams. The maintainers team is given Maintain role. I wasn't sure what we want for approvers team, for now I set it to Triage.

**Comment by svrnm** [comment]
thank you @yurishkuro
