### ISSUE TITLE
Request for semconv-cicd-approvers team

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/community#2192]
I'd like to request the creation of a team for the [CICD Semantic Conventions SIG](https://github.com/open-telemetry/community/blob/main/projects/ci-cd.md). The team should be named semconv-cicd-approvers and contain project lead and sponsors:

* @carlosalberto 
* @jsuereth 
* @adrielp 

> Note: This was largely copied from #2136

**Comment by arminru** [comment]
Created @open-telemetry/semconv-cicd-approvers and added the team as a collaborator on https://github.com/open-telemetry/semantic-conventions.

**Comment by arminru** [comment]
@adrielp You can proceed with adding the team for the respective paths in https://github.com/open-telemetry/semantic-conventions/blob/main/.github/CODEOWNERS now.

**Comment by adrielp** [comment]
thanks @arminru for the quick turn around!
