### ISSUE TITLE
REQUEST: Java SIG approver for tigrannajaryan

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#22]
### GitHub Username

@tigrannajaryan

### Organization you are requesting membership in

@open-telemetry Java SIG

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects (
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu
- @songy23
- @pjanotti

### List of contributions to the OpenTelemetry project

- https://github.com/census-instrumentation/opencensus-service/pulls/tigrannajaryan

SIG projects I am involved with

- OpenTelemetry Agent and Collector

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan I invited you to become a member. 

For Java approvers - I'd suggest to start with approvers and follow the standard process of becoming an approver. Unless there were some work in OpenCensus that justifies inclusion in initial (bootstrap) members list.
