### ISSUE TITLE
REQUEST: New membership for @123liuziming

### ISSUE THREAD

**Issue by 123liuziming** [open-telemetry/community#2207]
### GitHub Username

@123liuziming

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @laurit

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11698
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11519
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11260
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10982
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9678
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9677
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9597
- Issues responded to
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10652
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11302
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11233
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10981
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9711
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9596
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9495
- SIG projects I am involved with
 https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Comment by trask** [comment]
I support!

**Comment by laurit** [comment]
I support

**Comment by trask** [comment]
invite sent, welcome!
