### ISSUE TITLE
REQUEST: New membership for zhihali

### ISSUE THREAD

**Issue by zhihali** [open-telemetry/community#2214]
### GitHub Username

@zhihali

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @xrmx
- @emdneto

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2668
  https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2694
  https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2702
  https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2648
  https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2620
  https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2612
  https://github.com/open-telemetry/opentelemetry-python/pull/3968
  https://github.com/open-telemetry/opentelemetry-python/pull/3949
  https://github.com/open-telemetry/opentelemetry-go/pull/5514

- Issues responded to
  https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2639
  https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2684
  https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2683
  https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2453
  https://github.com/open-telemetry/opentelemetry-python/issues/3969
  https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2511
  https://github.com/open-telemetry/opentelemetry-python/issues/3969
  https://github.com/open-telemetry/opentelemetry-python/issues/3921
  https://github.com/open-telemetry/opentelemetry-go/issues/5462

- SIG projects I am involved with
  https://github.com/open-telemetry/opentelemetry-python-contrib
  https://github.com/open-telemetry/opentelemetry-python

**Comment by xrmx** [comment]
I support

**Comment by trask** [comment]
invite sent, wecome!
