### ISSUE TITLE
Remove unused(?) team: @open-telemetry/instr-wg

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#2218]
I believe this is no longer used and can be deleted.

I don't see any recent references: https://github.com/search?q=org%3Aopen-telemetry+open-telemetry%2Finstr-wg&type=code

Let me know if anyone knows of this still being in use, otherwise we'll plan to delete it.

cc @open-telemetry/instr-wg

**Comment by lmolkova** [comment]
I support removing it

**Comment by trask** [comment]
deleted
