### ISSUE TITLE
Create a large Windows runner to test the collector MSI

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/community#2221]
I'm starting to work on https://github.com/open-telemetry/opentelemetry-collector-releases/issues/576 and per tests on a separate repo a large Windows runner solved the issues mentioned at https://github.com/open-telemetry/opentelemetry-collector-releases/issues/576#issuecomment-2229108989.

Is it possible to get a large Windows runner for the releaser repo?

**Comment by trask** [comment]
hi @pjanotti, sorry for the late reply, is this still an issue? I believe we can do this.

**Comment by pjanotti** [comment]
Yes, @trask - without the larger runner the tests will be very flaky (based on the experience with our distro and a larger Windows runner that we use to run MSI tests).

**Comment by trask** [comment]
I've created a runner named `otel-windows-latest-8-cores` and given access to it to the opentelemetry-collector-releases repo, you should be able to use it in your workflow via:

`runs-on: otel-windows-latest-8-cores`
