### ISSUE TITLE
REQUEST: New membership for atreat

### ISSUE THREAD

**Issue by atreat** [open-telemetry/community#2222]
### GitHub Username

e.g. @atreat

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bryce-b 
- @nachoBonafonte 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - Authored list in [opentelemetry-swift](https://github.com/open-telemetry/opentelemetry-swift/pulls?q=is%3Apr+is%3Aclosed+author%3Aatreat)
  
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-swift/issues/530
  - https://github.com/open-telemetry/semantic-conventions/issues/1104
  
- Community activities I organized/ran
  - Q&A with the End User SIG

- SIG projects I am involved with
   - Active member of Client Side SIG
   - Active member of Swift SIG

**Comment by nachoBonafonte** [comment]
I support

**Comment by bryce-b** [comment]
I support

**Comment by arminru** [comment]
Invite sent. Welcome, @atreat!
