### ISSUE TITLE
Enabled Snyk on collector, collector contrib, and collector releases

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#2228]
Documenting that the Snyk integration (thru CNCF) has been enabled on collector repositories per @jpkrohling.

**Comment by codeboten** [comment]
Just a follow up on this, what's the requirements around the license check for snyk? We have the license check failing on MPL license in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34199

**Comment by evan-bradley** [comment]
@austinlparker @jpkrohling Could the maintainers of each Collector repo the integration runs on be given access to the corresponding dashboard? Right now it runs on PRs, and it would be nice to know why a particular PR causes a failure.

**Comment by trask** [comment]
> Just a follow up on this, what's the requirements around the license check for snyk? We have the license check failing on MPL license in [open-telemetry/opentelemetry-collector-contrib#34199](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34199)

check out https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#cncf-allowlist-license-policy

(we have a somewhat similar issue in Java instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10705#issuecomment-1979548829)

**Comment by codeboten** [comment]
thanks @trask, have you applied for an exception?

**Comment by trask** [comment]
hey @codeboten, no I haven't, it looks like we need to open an issue similar to these: https://github.com/cncf/foundation/issues?q=is%3Aissue+is%3Aopen+label%3Alicensing

**Comment by jpkrohling** [comment]
@evan-bradley , absolutely! To maintainers reading this: just ping me and tell me your email addressed and I'll add you to Snyk.
