### ISSUE TITLE
New Calendar Item: OpenTelemetry Q&A in calendar-end-users Calendar

### ISSUE THREAD

**Issue by avillela** [open-telemetry/community#2229]
Please create a new calendar item in calendar-end-users calendar

**Date:** August 29th
**Time:** 13:00 EDT
**Title:** OpenTelemetry Q&A

**Zoom link:** Zoom: [https://zoom.us/j/96494767116?pwd=aVhwQW9xNTd2WUJ3Z3g1bkptZ0V2UT09](https://www.google.com/url?q=https://zoom.us/j/96494767116?pwd%3DaVhwQW9xNTd2WUJ3Z3g1bkptZ0V2UT09&sa=D&source=calendar&usd=2&usg=AOvVaw1xbIIf0ENYhwbZCSz8dC2n) (OpenTelemetry Zoom Account #1)

**Meeting notes:** N/A

**Comment by arminru** [comment]
@avillela  Please add links to the respective meeting notes doc (if applicable) and the Zoom link (unless an existing available Zoom room should be assigned).

**Comment by danielgblanco** [comment]
I can create the invite and Zoom meeting (i.e. non-recurring). @avillela anything you'd like to put in the description? Also, should I put something in the title like "OpenTelemetry Q&A with {name}"?

**Comment by avillela** [comment]
@danielgblanco yes, please make the title "OTel Q&A with Steven Swartz of Ripple"

Also, I put the wrong date originally (updated above now). Should be Thursday, August 29th.

**Comment by avillela** [comment]
Yes, correct!

**Comment by danielgblanco** [comment]
Zoom call created for the event and invites sent!
