### ISSUE TITLE
New teams `docs-pt-approvers` and `docs-pt-maintainers`

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2232]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io

### Requested changes

- [x] Create a new group `docs-pt-approvers` with and @emdneto, @joaopgrassi, @jpkrohling, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
- [x] Create a new sub-group to `docs-pt-approvers` named `docs-pt-maintainers` with @jpkrohling, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
 
Note: We have individual contributors (like @edsoncelio, @EzzioMoreira), who helped making this happen. We are looking forward to have them go through the process of becoming established members and approvers eventually, following [the membership guidelines](https://github.com/open-telemetry/community/blob/main/community-membership.md)

### Purpose

Team to manage Portuguese translations for opentelemetry.io
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/docs-maintainers

**Comment by joaopgrassi** [comment]
Feel free to also add me as an approver as a native pt-BR speaker :)

**Comment by emdneto** [comment]
I'm more than glad to also help with as a native pt-BR speaker as well 🚀

**Comment by svrnm** [comment]
Any updates? @open-telemetry/technical-committee @austinlparker @trask can someone take a look and create these teams for us? Thanks

**Comment by lmolkova** [comment]
done
/cc @open-telemetry/docs-pt-approvers and @open-telemetry/docs-pt-maintainers

**Comment by trask** [comment]
> * Create a new group `docs-pt-approvers` with and @emdneto, @joaopgrassi, @jpkrohling, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)

typically only members of `docs-pt-maintainers` would be team maintainers for `docs-pt-approvers`

**Comment by lmolkova** [comment]
> > * Create a new group `docs-pt-approvers` with and @emdneto, @joaopgrassi, @jpkrohling, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
> 
> typically only members of `docs-pt-maintainers` would be team maintainers for `docs-pt-approvers`

👍 
@svrnm was there a specific reason to have everyone in approvers be a maintainer?

**Comment by svrnm** [comment]
> > > * Create a new group `docs-pt-approvers` with and @emdneto, @joaopgrassi, @jpkrohling, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
> > 
> > 
> > typically only members of `docs-pt-maintainers` would be team maintainers for `docs-pt-approvers`
> 
> 👍 @svrnm was there a specific reason to have everyone in approvers be a maintainer?

No, probably a copy and paste error on my end.

**Comment by chalin** [comment]
@lmolkova et al., any idea why we have this issue:

- https://github.com/open-telemetry/opentelemetry.io/issues/5090

**Comment by trask** [comment]
hey @chalin I think you need to give @open-telemetry/docs-pt-approvers write access to the repo first

**Comment by lmolkova** [comment]
> hey @chalin I think you need to give @open-telemetry/docs-pt-approvers write access to the repo first

Thanks! Can confirm - just did it. I assume you also want to do it for @open-telemetry/docs-es-approvers

**Comment by chalin** [comment]
Thanks all!

> Thanks! Can confirm - I just did it and it works.

Thanks all!

Btw, I thought that we were trying to avoid granting members or groups write access to repos, but if this is the way to go, so be it. /cc @svrnm 

> I assume you also want to do it for @open-telemetry/docs-es-approvers

Yes, for all localisation approvers, thanks.

**Comment by svrnm** [comment]
> Btw, I thought that we were trying to avoid granting members or groups write access to repos, but if this is the way to go, so be it. /cc @svrnm

That's why we have component-owners today, we do not need repo write permissions anymore. Maybe teams still need triage or read permissions for that?

**Comment by chalin** [comment]
Ok, so is there anything to be adjusted here -- e.g., write permission revoked for `@open-telemetry/docs-XX-approvers` etc.

**Comment by svrnm** [comment]
> Ok, so is there anything to be adjusted here -- e.g., write permission revoked for `@open-telemetry/docs-XX-approvers` etc.

Eventually, yes, it looks like we can lower permissions to "triage" for most teams that way
