### ISSUE TITLE
REQUEST: Repository maintenance on `sig-contributor-experience`

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2233]
### Affected Repository

e.g. https://github.com/open-telemetry/sig-contributor-experience

### Requested changes

Make sure that @open-telemetry/sig-contributor-experience-approvers have the right privilelges to be codeowners (`write`), such that the following PR can be merged: https://github.com/open-telemetry/sig-contributor-experience/pull/2/files

Also, make sure that PR review requirements ask for codeowners to review.
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/sig-contributor-experience-maintainers

**Comment by arminru** [comment]
Permissions and branch protection rules fixed.
