### ISSUE TITLE
REQUEST: New membership for codefromthecrypt

### ISSUE THREAD

**Issue by codefromthecrypt** [open-telemetry/community#2241]
### GitHub Username

codefromthecrypt

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@svrnm
@tylerbenson

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

reviewed maybe too many to list, but ask me if you want me to add them

authored/merged recently:
* https://github.com/open-telemetry/community/pull/2238
* https://github.com/open-telemetry/community/pull/2231
* https://github.com/open-telemetry/opentelemetry-collector/pull/10398
* https://github.com/open-telemetry/opentelemetry-java/pull/6152
* https://github.com/open-telemetry/opentelemetry-java/pull/6151
* https://github.com/open-telemetry/opentelemetry-java/pull/6131
* https://github.com/open-telemetry/opentelemetry-java/pull/6129

- Issues responded to

responded maybe too many to list, but ask me if you want me to add them

authored recently:
* https://github.com/open-telemetry/community/issues/2194
* https://github.com/open-telemetry/opentelemetry.io/issues/4795
* https://github.com/open-telemetry/community/issues/2176
* https://github.com/open-telemetry/community/issues/2175
* https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33747

- Community activities I organized/ran
 * worked with various SIGs towards asiapac friendliness. e.g. collector SIG which has had two sequential meetings with at least three participants
 * have a history of leading community centric groups, such as zipkin, and intent to do more here

- SIG projects I am involved with
 * semantics LLM SIG
 * contributor-experience SIG
 * collector SIG (occasionally)
 * java SIG (occasionally)

**Comment by svrnm** [comment]
I support ❤️

**Comment by tylerbenson** [comment]
I also support.  Welcome @codefromthecrypt!

**Comment by arminru** [comment]
Invite sent. Welcome, @codefromthecrypt!
