### ISSUE TITLE
REQUEST: Repository maintenance on sig-developer-experience

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/community#2242]
### Affected Repository

https://github.com/open-telemetry/sig-developer-experience

### Requested changes

Create repository and create teams:

- @open-telemetry/sig-developer-experience-approvers
- @open-telemetry/sig-developer-experience-maintainers

Add @tsloughter @austinlparker @tedsuo @lmolkova as maintainers

 
### Purpose

Tracking Developer Experience SIG discussions and active work.
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/sig-developer-experience-maintainers

**Comment by lmolkova** [comment]
I created repo and teams with permissions over the repo.
