### ISSUE TITLE
REQUEST: New membership for serkan-ozal

### ISSUE THREAD

**Issue by serkan-ozal** [open-telemetry/community#2254]
### GitHub Username

@serkan-ozal

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tylerbenson
- @rapphil

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-java/pull/6329
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10942
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10736
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11868
  - https://github.com/open-telemetry/opentelemetry-lambda/pull/1180
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10921
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10931
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7808
  - https://github.com/open-telemetry/opentelemetry-lambda/issues/640
- Community activities I organized/ran
- SIG projects I am involved with: 
  - `OTEL FAAS SIG`

**Comment by tylerbenson** [comment]
I support and look forward to your involvement in the FAAS SIG.

**Comment by rapphil** [comment]
I support this.

**Comment by arminru** [comment]
Invite sent. Welcome, @serkan-ozal!
