### ISSUE TITLE
Replacement for community-membership.md file

### ISSUE THREAD

**Issue by kaylareopelle** [open-telemetry/community#2255]
The opentelemetry-ruby-contrib repo used to link to the community-membership.md file in this repository. I looked through the recent git history and couldn't find when it was removed or what its replacement would be.

It looks like it is also still linked to in this repo in some places, as there's [a link to the community-membership.md file in the Contributor guide](https://github.com/open-telemetry/community/blob/main/guides/contributor/README.md?plain=1#L57) that goes to a file not found. 

Here's the last commit I tracked down related to this file: https://github.com/open-telemetry/community/commit/66a95fe321f6c3770f93ea1201d121ecff9b69ef

Is there a new page that holds this content?

**Comment by kaylareopelle** [comment]
Relates to https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1096

**Comment by trask** [comment]
hi @kaylareopelle! ya, it was moved in #2051, this is affecting lots of repos 😅, you can point now to [guides/contributor/membership.md](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)

**Comment by kaylareopelle** [comment]
Aha! Thank you!! 😄
