### ISSUE TITLE
REQUEST: New membership for karthikscale3

### ISSUE THREAD

**Issue by karthikscale3** [open-telemetry/community#2256]
### GitHub Username

karthikscale3

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (@lmolkova)sponsor-1
- (@drewby)sponsor-2
- (@codefromthecrypt)sponsor-3

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

Authored/Reviewed the following PRs
- https://github.com/open-telemetry/semantic-conventions/pull/1059
- https://github.com/open-telemetry/semantic-conventions/pull/980
- https://github.com/open-telemetry/semantic-conventions/pull/1231

Issues responded to
- https://github.com/open-telemetry/semantic-conventions/issues/936
- https://github.com/open-telemetry/semantic-conventions/issues/1294

- Community activities I organized/ran
- SIG projects I am involved with

- Actively participating in the LLM Semantics working group
- Core maintainer of the open source project Langtrace (https://github.com/Scale3-Labs/langtrace) which implements a python and typescript SDK for the GenAI stack that follows the OpenTelemetry GenAI semantic conventions.

**Comment by codefromthecrypt** [comment]
I'm not an approver+, yet, so can't sponsor you officially. That said, I wholeheartedly support this.

@drewby is an approver, and is similarly a fan of yours, so maybe swap me out with Drew?

**Comment by drewby** [comment]
I support!

**Comment by lmolkova** [comment]
I support!

**Comment by arminru** [comment]
Invite sent. Welcome, @karthikscale3!
