### ISSUE TITLE
New teams `docs-es-approvers` and `docs-es-maintainers`

### ISSUE THREAD

**Issue by theletterf** [open-telemetry/community#2262]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io

### Requested changes
 
- [x] Create a new group `docs-es-approvers` with and @mx-psi, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)
- [x] Create a new sub-group to `docs-es-approvers` named `docs-es-maintainers` with @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)

Note: We have individual contributors who want to participate who aren't OTel members yet. We are looking forward to have them go through the process of becoming established members and approvers eventually.

### Purpose

Team to manage Spanish translations for opentelemetry.io.

### Expected Duration

Permanent.

### Repository Maintainers

@open-telemetry/docs-maintainers

**Comment by theletterf** [comment]
Based on #2232 .

**Comment by krol3** [comment]
Hi @theletterf , following the spanish issue https://github.com/open-telemetry/opentelemetry.io/issues/4887, I would like to collaborate together with the k8s spanish team such as @ramrodo, @electrocucaracha

**Comment by didiViking** [comment]
Hi @theletterf @krol3 Ivwould like to contribute to this thread. Thanks

**Comment by electrocucaracha** [comment]
> Hi @theletterf @krol3 Ivwould like to contribute to this thread. Thanks

@didiViking the Spanish translation team has weekly meetings on Tuesdays, where we discuss this and other initiatives https://go.rael.dev/k8s-sig-docs-es-meetings

**Comment by ramrodo** [comment]
I would like to contribute to this documentation in Spanish too :)

**Comment by theletterf** [comment]
@krol3 @ramrodo @didiViking Wonderful! My understanding, much as it happened with pt-BR, is that you'll be considered maintainers, though the addition to the group can only happen after OTel membership has been attained. Is that correct, @svrnm ?

**Comment by lmolkova** [comment]
Done!
/cc @open-telemetry/docs-es-approvers @open-telemetry/docs-es-maintainers

**Comment by trask** [comment]
> Create a new group docs-es-approvers with and @mx-psi, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members (all as "maintainers" for the group)

typically only members of docs-es-maintainers would be team maintainers for docs-es-approvers

**Comment by lmolkova** [comment]
fixed
