### ISSUE TITLE
New eBPF Profiler Approvers

### ISSUE THREAD

**Issue by athre0z** [open-telemetry/community#2270]
#2265 added the initial maintainer team for the OTel eBPF profiler, but no approvers. 

Since this is a new project with a lot of existing long term contributors that have worked on the Elastic profiling agent before it was donated for years, I asked to skip the [normal approver promotion process](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md) in yesterday's [profiling SIG meeting](https://zoom.us/rec/play/n_X0OVmkfsbBZKlraO4FlPbdCnOiEHXbwWE0MSe1ZYSzgrPtv2PkOGDCA6nvYqybgSu-eO3Y7PBAxyDS.2l5I3v9HRrQ-8j6h?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FbH5GM01EeNo3rO2bpPeeOxuWmFtUeZM98u1HXyBqvwI_9_r77NfYPTF2ORiDbYsO.EDvrYFmRvVbOUWrJ) (timestamp 33:56) to get them on board quickly, just like we did for the initial selection of maintainers. We had consensus of everyone present that this was reasonable to do.

**Comment by athre0z** [comment]
I added the following people as approvers to @open-telemetry/ebpf-profiler-approvers:

- @christos68k
- @florianl 
- @rockdaboot

**Comment by mtwo** [comment]
Confirming that we discussed this in yesterday's SIG call and that the SIG approved it
