### ISSUE TITLE
REQUEST: New membership for @EzzioMoreira

### ISSUE THREAD

**Issue by EzzioMoreira** [open-telemetry/community#2272]
### GitHub Username

@EzzioMoreira

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @emdneto 
- @svrnm

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry.io/pull/4868
  - https://github.com/open-telemetry/opentelemetry.io/pull/4896
  - https://github.com/open-telemetry/opentelemetry.io/pull/4901
  - https://github.com/open-telemetry/opentelemetry.io/pull/4984
  - https://github.com/open-telemetry/opentelemetry.io/pull/4997
  - https://github.com/open-telemetry/opentelemetry.io/pull/5019
  - https://github.com/open-telemetry/opentelemetry.io/pull/4794
  - https://github.com/open-telemetry/opentelemetry.io/pull/4993
  - https://github.com/open-telemetry/opentelemetry.io/pull/4980

- Issues responded to
  - https://github.com/open-telemetry/opentelemetry.io/issues/4871
 
- Community activities I organized/ran
- SIG projects I am involved with
  - I am involved in the localization of the website into Portuguese BR: SIG: Communications (Website, [Documentation](https://opentelemetry.io/docs/), etc.)

**Comment by svrnm** [comment]
I support 💟

**Comment by emdneto** [comment]
I support

**Comment by jpkrohling** [comment]
I support, highly!

**Comment by arminru** [comment]
Invite sent. Welcome, @EzzioMoreira!
