### ISSUE TITLE
REQUEST: Repository maintenance on opentelementry-swift

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/community#2279]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-swift

### Requested changes

Add `swift-triagers` team to repo per the repository guidelines. 

 
### Purpose

We don't have a way to manage triagers in this repository.
 
### Expected Duration
permanently

### Repository Maintainers

- @open-telemetry/swift-maintainers

**Comment by arminru** [comment]
Created @open-telemetry/swift-triagers, added all @open-telemetry/swift-approvers as members and all @open-telemetry/swift-maintainers with Maintain permissions so you can add users to the team yourself.

**Comment by arminru** [comment]
Also added @alolita as per https://github.com/open-telemetry/opentelemetry-swift/issues/574.
