### ISSUE TITLE
REQUEST: create new Docker Hub repo `otel/opentelemetry-ebpf-profiler-dev`

### ISSUE THREAD

**Issue by athre0z** [open-telemetry/community#2283]
We'd like to provide a builder image for the [opentelemetry-ebpf-profiler](https://github.com/open-telemetry/opentelemetry-ebpf-profiler) project to allow users to build it without installing a bunch of stuff on their system first, or building the Docker image by themselves. See https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/43 and https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/44 for more motivation.

I've asked @austinlparker how this is done and he suggested creating an issue here to have the repo created and the credentials added to the CI secrets, so here we go :)

**Comment by trask** [comment]
cc @open-telemetry/technical-committee @tigrannajaryan

**Comment by christos68k** [comment]
Another friendly ping @open-telemetry/technical-committee @tigrannajaryan

**Comment by tigrannajaryan** [comment]
@trask Sorry, I missed this the first time.

Docker repo is created: https://hub.docker.com/repository/docker/otel/opentelemetry-ebpf-profiler-dev/general

DOCKER_USERNAME, DOCKER_PASSWORD added as secrets to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/settings/secrets/actions

You can use the secrets in your github action.
