### ISSUE TITLE
REQUEST: New membership for aryanishan1001

### ISSUE THREAD

**Issue by aryanishan1001** [open-telemetry/community#2284]
### GitHub Username

@aryanishan1001

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lalitb 
- @marcalff 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
1. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/346
2. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/428
3. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/394
4. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/398
5. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/403
6. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/436
7. https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/416

- SIG projects I am involved with
1. [opentelemetry-cpp-contrib](https://github.com/open-telemetry/opentelemetry-cpp-contrib)

**Comment by lalitb** [comment]
I support.

**Comment by austinlparker** [comment]
Invite sent. Welcome!
