### ISSUE TITLE
REQUEST: Repository maintenance on github.com/open-telemetry/govanityurls

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#2288]
### Affected Repository

https://github.com/open-telemetry/govanityurls

### Requested changes

Enable GitHub actions for the repository
 
### Purpose

We want to run actions to validate and manage the code.

### Repository Maintainers

- @damemi

**Comment by MrAlias** [comment]
It looks like branch protections are not setup for this repository either.

**Comment by jsuereth** [comment]
@MrAlias That's on me.  I forked - but didn't have time to finish setting things up.  Can tackle that shortly.

1. Who is your maintainer group? Can I re-use existing groups or should I set up a new one?
2. Are you using dependabot or rennovate or both?

**Comment by jsuereth** [comment]
Oh, also you do have branch protection, but just mandatory CLA so far.  Will add more based on your answers above.

**Comment by damemi** [comment]
@jsuereth I proposed these groups for the repo owners in https://github.com/open-telemetry/community/issues/2260

* @open-telemetry/go-instrumentation-approvers
* @open-telemetry/collector-approvers
* @open-telemetry/collector-contrib-approvers

@MrAlias I'd like to get dependabot set up in this repo, and then actually publish releases when we do an update. Then we should be able to pin https://github.com/open-telemetry/opentelemetry-go-vanityurls/ to a release of the new repo with a blank import and also get dependabot updates there to actually deploy the new release. It's a weird chain but it should keep the app up to date

**Comment by jsuereth** [comment]
@damemi There's a different bar for maintainer vs. approver status (see: https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#membership-roles-and-responsibilities).  Should I set up a new group to elevate individuals to maintainer status just for this repository or did you intend to use the same group?

**Comment by MrAlias** [comment]
> Oh, also you do have branch protection, but just mandatory CLA so far. Will add more based on your answers above.

Sorry, that looks like just my misunderstanding. I'm not sure if we need additional branch protections at the moment.

**Comment by damemi** [comment]
I meant the higher of maintainer vs approver, sorry. These should be the "*-maintainer" groups (I'll update the proposal issue).

I did not intend to change any individual status, the existing groups should be sufficient.

**Comment by MrAlias** [comment]
> @MrAlias I'd like to get dependabot set up in this repo, and then actually publish releases when we do an update. Then we should be able to pin https://github.com/open-telemetry/opentelemetry-go-vanityurls/ to a release of the new repo with a blank import and also get dependabot updates there to actually deploy the new release. It's a weird chain but it should keep the app up to date

+1

**Comment by jsuereth** [comment]
Ok, I'll set up the fine-grained branch protection rules for dependabot shortly.

Additionally, I'll add existing maintainer groups as maintainers. Can one of @damemi or @MrAlias update CONTRIBUTING with that list (if you haven't already)

**Comment by damemi** [comment]
I also missed @open-telemetry/go-maintainers. @MrAlias please double check that I'm not missing anyone who uses the go imports

**Comment by MrAlias** [comment]
> I also missed @open-telemetry/go-maintainers. @MrAlias please double check that I'm not missing anyone who uses the go imports

Approvers:

* @open-telemetry/go-approvers
* @open-telemetry/go-instrumentation-approvers
* @open-telemetry/collector-approvers
* @open-telemetry/collector-contrib-approvers

Maintainers:

* @open-telemetry/go-maintainers 
* @open-telemetry/go-instrumentation-maintainers 
* @open-telemetry/collector-maintainers 
* @open-telemetry/collector-contrib-maintainers

**Comment by MrAlias** [comment]
> Can you please confirm and I'll remove @damemi and @MrAlias as individuals for the repository and close this request

Can confirm for myself.

**Comment by damemi** [comment]
> > Can you please confirm and I'll remove @damemi and @MrAlias as individuals for the repository and close this request
> 
> Can confirm for myself.

+1 lgtm

**Comment by jsuereth** [comment]
Great - Everything should be good to go, please open a new issue (and ping me on slack with it) if you find anything not working.
