### ISSUE TITLE
Change membership of open-telemetry/otel-elections team to reflect election working group

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2300]
Election committee (@austinlparker @danielgblanco) should be made members of @open-telemetry/otel-elections 

I believe this is it, unless someone else from the GC wants to join (considering we had 3 members before)

**Comment by austinlparker** [comment]
Yeah

**Comment by arminru** [comment]
@open-telemetry/otel-elections

➖ @mtwo 
➖ @dyladan 
➖ @trask 
➕ @danielgblanco 
➕ @austinlparker 

✅

**Comment by arminru** [comment]
Are any more of @open-telemetry/governance-committee joining or should we close this?

**Comment by jpkrohling** [comment]
As someone who's done this before, I'm available to assist @danielgblanco and @austinlparker.

**Comment by danielgblanco** [comment]
Thanks @jpkrohling. As you're not up for re-election I'd appreciate that, to make sure we follow previous processes. @arminru can you add him?

**Comment by arminru** [comment]
@danielgblanco Added Juraci! Thanks.
