### ISSUE TITLE
REQUEST: New membership for @tpaschalis

### ISSUE THREAD

**Issue by tpaschalis** [open-telemetry/community#2322]
### GitHub Username

@tpaschalis

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - Some specific highlights:
    - https://github.com/open-telemetry/opamp-spec/pull/197
    - https://github.com/open-telemetry/opamp-spec/pull/195
    - https://github.com/open-telemetry/opamp-go/pull/286
    - https://github.com/open-telemetry/opamp-go/pull/289
    - All PRs with `involves:@tpaschalis` on OpAMP repos
    -  https://github.com/open-telemetry/opamp-go/pulls?q=is%3Aissue++involves%3Atpaschalis+
    - https://github.com/open-telemetry/opamp-spec/pulls?q=is%3Aissue++involves%3Atpaschalis+

- Issues responded to
    - https://github.com/open-telemetry/opamp-spec/pull/190
- Community activities I organized/ran
    - None
- SIG projects I am involved with
    - OpAMP/Agent Management WG

**Comment by tigrannajaryan** [comment]
I support.

**Comment by jpkrohling** [comment]
I support

**Comment by tigrannajaryan** [comment]
@tpaschalis invitation sent. Welcome!
