### ISSUE TITLE
REQUEST: New membership for lahsivjar

### ISSUE THREAD

**Issue by lahsivjar** [open-telemetry/community#2325]
### GitHub Username

@lahsivjar

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @AlexanderWert 
- @crobert-1 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34061
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34059
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33554
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33391
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33087
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33035
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32512
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32351
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31848
- Issues responded to
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34042
    - https://github.com/open-telemetry/opentelemetry-collector/issues/10166
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33949

**Comment by crobert-1** [comment]
I support

**Comment by AlexanderWert** [comment]
I support

**Comment by AlexanderWert** [comment]
@open-telemetry/technical-committee Can we add @lahsivjar as a member please, or anything else blocking it?

**Comment by trask** [comment]
@lahsivjar sorry for the delay, invite just sent!
