### ISSUE TITLE
Decentralize membership lists

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/community#233]
At the moment we list approvers/maintainers of all SIGs in the central file `community-members.md` in this repo. That means adding/editing those lists requires the attention of the admins/TC, while the decisions to promote member are actually made locally in the SIGs.

I suggest replacing the explicit lists with links to the respective repo and maintaining the lists there, to better scale up the process.

Similarly, the SIG information (schedule of meetings, etc.) can be also moved from the README in this repo to the READMEs in the respective repos. This repo will only have the links to information.

To avoid creating a bunch of refactoring work right now (unless someone wants to take it on), I suggest we do it incrementally as new requests (like #230) to change membership arrive.

**Comment by SergeyKanzhelev** [comment]
We actually discussed it while back and @bogdandrutu @sarahnovotny and @bhs we onboard. It is a good idea to make it in stages. 

Removing the "proposal" from title.

**Comment by mayurkale22** [comment]
I like the idea, but who is responsible for adding a new member to respective team (ex: `@open-telemetry/xxx-approvers` or `@open-telemetry/xxx-maintainers`)?

**Comment by yurishkuro** [comment]
I see that the teams allow Member vs. Maintainer roles, which exist outside of a specific repository. Do Maintainers have rights to add people to the team?

**Comment by SergeyKanzhelev** [comment]
Yes: https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md#permissions:

> Even though the members of foo-maintainers are included in foo-approvers transitively, every member of foo-maintainers should be included in foo-approvers explicitly, and with the "Maintainer" GitHub privileges. So repository maintainers can invite new approvers to the team.

**Comment by SergeyKanzhelev** [comment]
node teams seems to be broken. I can fix permissions right away. Also do you want them to be renamed to JavaScript?

**Comment by mayurkale22** [comment]
> node teams seems to be broken. I can fix permissions right away. Also do you want them to be renamed to JavaScript?

Sure, thanks 👍

**Comment by SergeyKanzhelev** [comment]
approvers are fixed:

![image](https://user-images.githubusercontent.com/9950081/67510150-44deac00-f649-11e9-965c-87959deaf52a.png)

**Comment by SergeyKanzhelev** [comment]
Maintainers are fixed:

![image](https://user-images.githubusercontent.com/9950081/67510235-65a70180-f649-11e9-8a11-48d75563d173.png)

**Comment by tedsuo** [comment]
Great to see this!

**Comment by lizthegrey** [comment]
This is now done.

**Comment by SergeyKanzhelev** [comment]
@lizthegrey we still have docs, erlang, cpp, and a few others not migrated out: https://github.com/open-telemetry/community/blob/master/community-members.md#docs-and-website

Let's keep it open. Would you mind following up with these SIGs?

**Comment by lizthegrey** [comment]
Sure, I can sort that out.

**Comment by bogdandrutu** [comment]
There are some special sigs that are cross repos (like TC) I would suggest for this we keep track here.

**Comment by SergeyKanzhelev** [comment]
I believe this is done for all, except website. Let's track decentralization of website sig membership file in this issue https://github.com/open-telemetry/community/issues/427
