### ISSUE TITLE
REQUEST: New membership for edsoncelio

### ISSUE THREAD

**Issue by edsoncelio** [open-telemetry/community#2336]
### GitHub Username

@edsoncelio

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @emdneto 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

-  https://github.com/open-telemetry/opentelemetry.io/issues/4922 (author)
- https://github.com/open-telemetry/community/issues/2280 (author)
- https://github.com/open-telemetry/opentelemetry.io/pull/4794 (author)
- https://github.com/open-telemetry/opentelemetry.io/pull/4868 (reviewer)
- https://github.com/open-telemetry/opentelemetry.io/pull/4901 (reviewer)
- https://github.com/open-telemetry/opentelemetry.io/pull/4980 (reviewer)
- https://github.com/open-telemetry/opentelemetry.io/pull/4984 (reviewer)
- https://github.com/open-telemetry/opentelemetry.io/pull/5019 (reviewer)
- https://github.com/open-telemetry/opentelemetry.io/pull/5120 (reviewer)

And some other non-code related:
- guide to the Portuguese documentation localization: https://edsoncelio.dev/otel-localization-ptbr-guide/
- Help to maintain the documentation localization team (Portuguese)

**Comment by emdneto** [comment]
I support

**Comment by svrnm** [comment]
I support :-)

**Comment by trask** [comment]
Invite sent!
