### ISSUE TITLE
update access for 1password account

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#2337]
I need to update my 1password account from my old email to my new email. Can an admin of the account help?

**Comment by jpkrohling** [comment]
Apparently, there's no way to change an email address for a 1password user, so I suspended your existing account and sent a new invitation to your new email address. Once you join it, I'll add you to the Collector vault.

**Comment by codeboten** [comment]
Thanks @jpkrohling, joined just waiting on verification

**Comment by jpkrohling** [comment]
Done.
