### ISSUE TITLE
REQUEST: New membership for @heitorganzeli

### ISSUE THREAD

**Issue by heitorganzeli** [open-telemetry/community#2339]
### GitHub Username

@heitorganzeli

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Obs**: I don't have any sponsors at the moment. I'm engineer from Huawei Cloud and we are trying to release a couple of new vendor specific components for the OpenTelemetry collector. It would also be great for me and @narcis96 to become members and start contributing more with the community

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34953
- Issues responded to
- Community activities I organized/ran
- SIG projects I am involved with

**Comment by trask** [comment]
hi @heitorganzeli, can you fill out the rest of the membership request form?

**Comment by heitorganzeli** [comment]
reopening this issue now that I got the work in and the sponsors

**Comment by TylerHelmuth** [comment]
I support

**Comment by mx-psi** [comment]
I support

**Comment by heitorganzeli** [comment]
hello @trask ,

would you be able to follow up with the membership procedure now?

**Comment by arminru** [comment]
Invite sent. Welcome, @heitorganzeli!
