### ISSUE TITLE
REQUEST: New membership for narcis96

### ISSUE THREAD

**Issue by narcis96** [open-telemetry/community#2340]
### GitHub Username

@narcis96

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- [mx-psi](https://github.com/mx-psi)
- @TylerHelmuth 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs  authored :  

1. goldendataset: Fix histogram metric BucketCounts length: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35610
2. Migrate to latest semconv version and ensure regular updates: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095
3. Improve coverage of mdatagen: https://github.com/open-telemetry/opentelemetry-collector/pull/11352
4. Define featuregates in metadata.yaml: https://github.com/open-telemetry/opentelemetry-collector/pull/11466
5. https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34953
6. Add debug wrapper for all traces components, fix nil error: https://github.com/open-telemetry/opentelemetry-collector/pull/11380
7. Remove exportertest.NewNopFactory: https://github.com/open-telemetry/opentelemetry-collector/pull/11381

**Comment by trask** [comment]
hi @narcis96, can you fill out the rest of the membership request form?

**Comment by narcis96** [comment]
@trask can you please re-open it ? I have done some updates on it. Thanks

**Comment by TylerHelmuth** [comment]
I support

**Comment by trask** [comment]
Invite sent!
