### ISSUE TITLE
REQUEST: New membership for @chan-tim-sumo

### ISSUE THREAD

**Issue by chan-tim-sumo** [open-telemetry/community#2341]
### GitHub Username
- @chan-tim-sumo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @songy23
- @andrzej-stencel 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33522 
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33604
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33643
- Issues responded to
- Community activities I organized/ran
- SIG projects I am involved with

**Comment by andrzej-stencel** [comment]
I support.

**Comment by rnishtala-sumo** [comment]
I support this too!

**Comment by chan-tim-sumo** [comment]
hey @trask ! can you take a look at this when you're free? thanks!

**Comment by trask** [comment]
> sponsors must be approvers or maintainers of at least one repository in the organization

I think @rnishtala-sumo may not meet the requirement of a sponsor, can you reach out to another member of @open-telemetry/collector-contrib-approvers? thanks!

**Comment by songy23** [comment]
I support

**Comment by trask** [comment]
Invite sent!
