### ISSUE TITLE
Please update docs/how-to-handle-public-calendar.md with zoom links for mainframe sig meetings

### ISSUE THREAD

**Issue by vvydier** [open-telemetry/community#2346]
The mainframe SIG zoom recording links does not exist in  https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s/edit?gid=0#gid=0
Please update the spreadsheet with the recording links
@open-telemetry/docs-maintainers

**Comment by mtwo** [comment]
@vvydier the recordings are in that sheet, you may just need to scroll all the way to the bottom. Today's meeting recording is linked in row 2076, and the prior weeks are above it: https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s/edit?gid=0#gid=0

Can you re-open this if you're not able to find or access the recordings?

**Comment by vvydier** [comment]
I see it now, thank you @mtwo !
