### ISSUE TITLE
REQUEST: New membership for jmichalek132

### ISSUE THREAD

**Issue by jmichalek132** [open-telemetry/community#2347]
### GitHub Username

e.g. @jmichalek132

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @gouthamve 
- @dashpole

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31924
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30808
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29503
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27565
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19164
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18292
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30309
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13849
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33661
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30435
- Community activities I organized/ran
n/a
- SIG projects I am involved with
  - OTEL Prometheus WG

**Comment by gouthamve** [comment]
I support!

Juraj has been showing up and contributing for a long time now and this is well deserved!

**Comment by dashpole** [comment]
I support!

**Comment by jpkrohling** [comment]
I support as well!

**Comment by trask** [comment]
Invite sent!
