### ISSUE TITLE
REQUEST: New membership for ysolomchenko

### ISSUE THREAD

**Issue by ysolomchenko** [open-telemetry/community#2351]
### GitHub Username

e.g. @ysolomchenko

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Kielek 
- @rajkumar-rangaraj 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5824
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1943
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1983
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1985
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3615
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3523
- Issues responded to
- Community activities I organized/ran
- SIG projects I am involved with

**Comment by Kielek** [comment]
I support

**Comment by rajkumar-rangaraj** [comment]
I support

**Comment by trask** [comment]
Invite sent!
