### ISSUE TITLE
REQUEST: New membership for @gyliu513

### ISSUE THREAD

**Issue by gyliu513** [open-telemetry/community#2355]
### GitHub Username
@gyliu513 

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@lmolkova
@alolita

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11874 
  - https://github.com/open-telemetry/opentelemetry.io/pull/4387
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29690
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12217
  - https://github.com/open-telemetry/opentelemetry-go/pull/2993
  - https://github.com/open-telemetry/semantic-conventions/pull/825
  - https://github.com/open-telemetry/community/pull/2326
  - https://github.com/open-telemetry/semantic-conventions/pull/639
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector/issues/11038
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32909
  - https://github.com/open-telemetry/opentelemetry-python/issues/3868
  - https://github.com/open-telemetry/semantic-conventions/issues/936
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29568
  - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2050
  - https://github.com/open-telemetry/opentelemetry-python/issues/3482
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28553
  - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2016
  - https://github.com/open-telemetry/opentelemetry-collector/issues/5671
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11873
- Community activities I organized/ran
  - Instrumentation Code for GenAI Contribution
    - https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-watsonx
  - Deeply involved in LLM Semantic Convention
    - I'm an initial engineer for LLM Semantic Convention https://github.com/open-telemetry/community/blob/main/projects/llm-semconv.md
    - Attend Weekly meeting for LLM Semantic Convention https://docs.google.com/document/d/1EKIeDgBGXQPGehUigIRLwAUpRGa7-1kXB736EaYuJ2M/edit#heading=h.uwkz4hbep35f
  - AI_DEV Euro 2024 Topic
    - https://aideveu24.sched.com/event/1c1mL?iframe=no Examining the principal of observability and Its relevance in LLM Applications
  - OSA CON 2024
    - https://www.linkedin.com/feed/update/urn:li:activity:7240736070290526209/ Observability for Large Language Models with OpenTelemetry
  - My Blogs for OTEL
    - https://gyliu513.github.io/jekyll/update/2024/05/07/opentelemetry-profiling-with-elastic-otel-profiling-agent.html
    - https://gyliu513.github.io/jekyll/update/2024/03/03/otel-collector-deep-dive.html
    - https://gyliu513.github.io/jekyll/update/2024/02/28/deep-dive-into-instana-ai-observability.html
    - https://gyliu513.github.io/jekyll/update/2023/11/15/enhancing-ai-with-observability.html
- SIG projects I am involved with
  - https://github.com/open-telemetry/community/blob/main/projects/llm-semconv.md

**Comment by alolita** [comment]
Thanks for contributing to OpenTelemetry @gyliu513

I support your membership.

**Comment by trask** [comment]
Invite sent!
