### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-configuration

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#2357]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-configuration

### Requested changes

Enable dependabot alerts in the security settings

 
### Purpose

Going through the https://github.com/open-telemetry/opentelemetry-configuration/issues/52 checklist, the repo should have dependabot alert enabled
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/configuration-maintainers

**Comment by trask** [comment]
hey @codeboten! can you try adding a `.github/dependabot.yml` file to the repo, e.g. https://github.com/open-telemetry/community/blob/main/.github/dependabot.yml? I _think_ that should enable it

**Comment by trask** [comment]
oh, nm, I think I see the setting you are talking about...

**Comment by trask** [comment]
I enabled these two settings on https://github.com/open-telemetry/opentelemetry-configuration:

![image](https://github.com/user-attachments/assets/473109d5-21f5-4b31-a4ba-d991ed7e3847)

and

![image](https://github.com/user-attachments/assets/07c073cf-cdaf-423d-adf0-66cbccfd9545)

**Comment by trask** [comment]
probably we should update https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md, I'll send a PR

**Comment by codeboten** [comment]
Thanks @trask

**Comment by codeboten** [comment]
This can be closed as done 👍🏻
