### ISSUE TITLE
Authorize CNCF Slack to enable Github Scheduled Reminders

### ISSUE THREAD

**Issue by ankitpatel96** [open-telemetry/community#2362]
Hi,
It'd be very helpful to enable Github's "[scheduled reminders](https://github.com/settings/reminders)" feature.  This enables Github to send notifications to individual users via Slack and Microsoft Teams.  It's opt-in by each user and personally configurable - for example you might decide that you like to get live slack pings for reviews, but you can also get a daily digest if you'd like.

Here's an example of what the reminder interface is - these are my personal settings for notifications for my employer's Slack (DataDog) 
![image](https://github.com/user-attachments/assets/53d39111-bc5c-4e73-b3bd-53889c70050b)

In order for individual users to make use of this integration, the owner of the open-telemetry Github org needs to install it first - I believe you can navigate to the [reminders page](https://github.com/settings/reminders) and simply authorize a Slack Workspace for the Otel org without setting up reminders for everyone.  We should link it to the CNCF slack.

Adding another option for users to get synchronous Github notifications can help speed PR review, issue troubleshooting, and overall engagement.  Once again - this would just be an option for people - if someone is happy with Github's other notification systems (email etc), they don't have to opt-in!
Thanks!

**Comment by yurishkuro** [comment]
I don't mind if people want to receive notifications as 1-1 messages, but how can we guarantee this will not spam the public channels?

**Comment by trask** [comment]
> I don't mind if people want to receive notifications as 1-1 messages, but how can we guarantee this will not spam the public channels?

here's what I found:

* [You can set scheduled reminders for personal or team-level review requests for pull requests in organizations you are a member of.](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/managing-your-scheduled-reminders#about-scheduled-reminders-for-users)
  * It doesn't look like you have the option to set a slack channel for these, I assume they are only 1-1 messages.
* [Team maintainers and organization owners can set scheduled reminders for any pull requests that a team has been requested to review.](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-scheduled-reminders-for-your-team#about-scheduled-reminders-for-teams)
  * You _can_ set a slack channel for these, but given the limited set of people that would have access to set these up I think it's manageable.
* [Organization owners can schedule a reminder for one or more teams in their organization, for all pull requests the team or teams have been requested to review.](https://docs.github.com/en/organizations/managing-organization-settings/managing-scheduled-reminders-for-your-organization#about-scheduled-reminders-for-pull-requests)
  * You _can_ set a slack channel for these, but given the (even more) limited set of people that would have access to set these up I think it's manageable.

**Comment by trask** [comment]
I enabled the Slack integration and it is live, seems CNCF slack administrators had already authorized it from their side.

**Comment by ankitpatel96** [comment]
Thanks!!
