### ISSUE TITLE
REQUEST: New membership for ArthurSens

### ISSUE THREAD

**Issue by ArthurSens** [open-telemetry/community#2370]
### GitHub Username

@ArthurSens

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dashpole
- @jpkrohling  

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Support transforming OTLP StartTimeUnixNano into Prometheus created timestamps: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34596
- Bootstrapping the new `prometheusremotewrite` receiver component (and intention to be the codeowner): https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35295
- Allowing UTF-8 characters in `prometheus` and `prometheusremotewrite` exporters: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35469
- Active contributor to the otel-prometheus working group
- [Maintainer of the /otlp endpoint in Prometheus](https://github.com/prometheus/prometheus/blob/main/MAINTAINERS.md#:~:text=otlptranslator%3A%20Arthur%20Silva%20Sens%20(arthursens2005%40gmail.com%20/%20%40ArthurSens)%2C%20Arve%20Knudsen%20(arve.knudsen%40gmail.com%20/%20%40aknuds1)%2C%20Jes%C3%BAs%20V%C3%A1zquez%20(jesus.vazquez%40grafana.com%20/%20%40jesusvazquez))
- Currently mentoring the support of Prometheus Remote Write v2 in prometheusremotewriteexporter: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/03-Sep-Nov#prometheus-remote-write-v2-support-in-otel-collectors-prometheusremotewriteexporter
- [Helping when possible with processor/interval and processor/deltatocumulative](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+commenter%3AArthurSens+is%3Aclosed+label%3Aprocessor%2Fdeltatocumulative%2Cprocessor%2Finterval) :)

**Comment by dashpole** [comment]
I support!

**Comment by jpkrohling** [comment]
I support

**Comment by trask** [comment]
Invite sent!
