### ISSUE TITLE
REQUEST: Create new Docker Hub repository: otel/opentelemetry-collector-otlp

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/community#2378]
On open-telemetry/opentelemetry-collector-releases/pull/663 we added a new OpenTelemetry Collector distribution that we intend to release as part of the [GA roadmap ](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/ga-roadmap.md).

We need to create the `otel/opentelemetry-collector-otlp` Dockerhub repository to be able to have Docker releases of this new distribution.

I am asking this as an OpenTelemetry Collector maintainer, and you can see the PR has approvals from 4 other contrib maintainers (which are the actual owners of opentelemetry-collector-releases).

**Comment by mx-psi** [comment]
To further clarify: this is blocking the v0.111.0 release because we forgot to ask for it beforehand (see [logs](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/11180623917/job/31082766369))

**Comment by TylerHelmuth** [comment]
Whoops

**Comment by codeboten** [comment]
I support this

**Comment by bogdandrutu** [comment]
+1, I support this

**Comment by tigrannajaryan** [comment]
https://hub.docker.com/r/otel/opentelemetry-collector-otlp created.
