### ISSUE TITLE
Create calendar event for OTel Q&A on October 17th (OTel End User SIG) 

### ISSUE THREAD

**Issue by avillela** [open-telemetry/community#2379]
Details:
* Calendar: [calendar-end-users](https://groups.google.com/a/opentelemetry.io/g/calendar-end-users)
* Date: October 17th
* Time: 13:00 EDT/10:00 PDT

Speaker
* Dan Ravenstone

Description:
Join Dan Ravenstone as he talks about his experiences and challenges around OTel adoption

Please send an invite directly to Dan (daniel.ravenstone@tophatmonocle.com)

**Comment by danielgblanco** [comment]
I'll take this

**Comment by danielgblanco** [comment]
Meeting created using `cncf-opentelemetry-meeting-4` account and invite sent out to `calendar-all` and `calendar-end-users`.
