### ISSUE TITLE
Guidelines for Medium posts? 

### ISSUE THREAD

**Issue by mangotron** [open-telemetry/community#238]
Asking this set of questions here as I'm not sure where else it would belong, and it'd be great if we had an agreed-upon process for publishing to medium.com/opentelemetry.

* What guidelines would everyone be comfortable with around review/approval? (e.g. Can a submitted draft be approved by _anyone_ who has editor rights in Medium?)
* In general, is there a preference to submit completed work for review, or would it potentially be better to have authors propose a topic first before submitting a draft?
* For a prospective author who is _not_ already able to submit a draft directly through Medium, what is the preferred process for submitting content? 

Historically most contributions to the OpenTelemetry blog have been from a handful of people, but I'd love to encourage more people to contribute, and putting together a clearer set of instructions will help facilitate this.

**Comment by SergeyKanzhelev** [comment]
interesting you brought it up. I put it in agenda for the next governance meeting. 

Right now the only process is to contact comms e-mail list: https://github.com/open-telemetry/community#public-communication-requests

We need to come back with clearer guidance on the formal requirements and suggestions.

**Comment by mangotron** [comment]
Sounds good! I'm great at following guidelines as long as they're clearly stated somewhere :-)

**Comment by SergeyKanzhelev** [comment]
@ccaraman I will be writing some instructions as I need to help make a blog post. So assigned to myself. Let me know if you want to take it back.

**Comment by alolita** [comment]
Hi @SergeyKanzhelev @mtwo - it would be great to have these guidelines for publishing on the project blog :-) The interns on my team will be publishing about their project contributions and Morgan had mentioned this would be discussed in the governance meeting. I'd be happy to help draft review guidelines if that helps the process.

**Comment by mtwo** [comment]
My suggestions:

- Posts should be reviewable for at least 48 hours before they go live
- The approval of a single blog approver is sufficient for posts that are minor updates (status reports, community / SIG updates, though they still need to be reviewable for 48 hours
- Substantive project announcements must be posted to cncf-opentelemetry-comms@lists.cncf.io (which is an open mailing list) and should be reviewable for at least 72 hours

**Comment by SergeyKanzhelev** [comment]
One point from https://lists.cncf.io/g/cncf-opentelemetry-comms/messages?expanded=1&msgnum=266 needs to be covered is whether we allow reposts

**Comment by trask** [comment]
@open-telemetry/docs-maintainers do you think this issue can be closed given https://github.com/open-telemetry/opentelemetry.io#submitting-a-blog-post?

**Comment by cartermp** [comment]
I think yes, this can be closed. Ideally we wouldn't be posting to medium anymore and instead boosting the official blog.
