### ISSUE TITLE
REQUEST: Repository maintenance on Dockerhub 

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/community#2389]
### Affected Repository

https://hub.docker.com/r/otel/opentelemetry-collector-otlp/tags

### Requested changes

Remove all existing tags for v0.111.0 release and latest.

 
### Purpose

The OTLP-only distro release failed and we want to remove the tags to re-do the release. These images have a total of 7 pulls so we believe nobody is actively using them. This is also the first release we have done this.
 
### Expected Duration

e.g. "1-2 weeks. We'll comment again on this issue once we are done so the permissions can be reverted." or "permanently"

We will re-add them by re-running the release process

### Repository Maintainers

- @open-telemetry/collector-maintainers 

cc @tigrannajaryan @bogdandrutu

**Comment by mx-psi** [comment]
All of these should be deleted, both the `0.111.0-` and `latest-` tags (the `latest-` tags point to the `0.111.0` ones)

**Comment by tigrannajaryan** [comment]
Deleted.
