### ISSUE TITLE
REQUEST: New membership for shalk

### ISSUE THREAD

**Issue by shalk** [open-telemetry/community#2393]
### GitHub Username

@shalk 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @laurit
- @jaydeluca 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12207
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12132
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12108
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12008
- https://github.com/open-telemetry/opentelemetry-java/issues/6749

**Comment by jaydeluca** [comment]
I support

**Comment by laurit** [comment]
I support

**Comment by trask** [comment]
Invite sent!
