### ISSUE TITLE
 New teams `docs-fr-approvers` and `docs-fr-maintainers`

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2396]
### Affected Repository

https://github.com/open-telemetry/opentelemetry.io

### Requested changes

- [ ] Create a new group `docs-fr-approvers` with @dmathieu, @codeboten, @jeanbisutti, @bertysentry, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members
- [ ] Create a new sub-group to `docs-fr-approvers` named `docs-fr-maintainers` with @dmathieu, @codeboten, @marcalff, @theletterf, @cartermp, @austinlparker, @chalin and @svrnm as members.
 
Note 1: We bootstrap the maintainer team with individuals who are maintainers in any capacity already, and with approvers who are either approvers already, or have contributed significantly to the OpenTelemetry project to meet the criteria. As of today the "maintainer" in this context is no different to the approver, we have an [ongoing discussion around localization maintainership](https://github.com/open-telemetry/opentelemetry.io/discussions/5350) and the setup may change.

Note 2: We have individual contributors (like @iguitton, @pierrehilbert), who helped making this happen. We are looking forward to have them go through the process of becoming established members and approvers eventually, following [the membership guidelines](https://github.com/open-telemetry/community/blob/main/community-membership.md)

### Purpose

Team to manage French translations for opentelemetry.io
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/docs-maintainers

**Comment by RichardChukwu** [comment]
Can I work on this issue @svrnm ?

**Comment by trask** [comment]
hi @RichardChukwu! this requires special permissions to create new teams

**Comment by RichardChukwu** [comment]
ooh, noted @trask thanks for the feedback

**Comment by trask** [comment]
done, please double check the team membership (also I assumed that @marcalff was intended to be in docs-fr-approvers team as well as docs-fr-maintainers)

**Comment by pierrehilbert** [comment]
It looks like the membership guidelines link changed and should be https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md

**Comment by svrnm** [comment]
> It looks like the membership guidelines link changed and should be [`main`/guides/contributor/membership.md](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md?rgh-link-date=2024-10-15T07%3A44%3A20Z)

good call out, I copy and pasted from a previous issue, will update this issue, so I will have it right for the next language ;)
