### ISSUE TITLE
REQUEST: Opentelemetry Service approver for sjkaris

### ISSUE THREAD

**Issue by sjkaris** [open-telemetry/community#24]
### GitHub Username

@sjkaris

### Organization you are requesting membership in

e.g. (at)open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @rghetia

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [Opencensus Service](https://github.com/census-instrumentation/opencensus-service/pulls?q=is%3Apr+is%3Aclosed+author%3Asjkaris)
  - [Opencensus go exporter](https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pulls?q=is%3Apr+is%3Aclosed+author%3Asjkaris)
- Issues responded to
- SIG projects I am involved with
  - Opentelemetry collector and agent
  - golang opencensus exporter

**Comment by SergeyKanzhelev** [comment]
what's your company affiliation?

**Comment by sjkaris** [comment]
Omnition

**Comment by SergeyKanzhelev** [comment]
welcome!
