### ISSUE TITLE
REQUEST: New membership for robsunday

### ISSUE THREAD

**Issue by robsunday** [open-telemetry/community#2401]
### GitHub Username
@robsunday
e.g. (at)example_user

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @breedx-splk 
- @SylvainJuge

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[authored] https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1480
[authored] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12084
[authored] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11914 
[authored] https://github.com/SylvainJuge/opentelemetry-java-contrib/pull/1
[reviewed] https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1485
[reviewed] https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1445
[reviewed] https://github.com/SylvainJuge/opentelemetry-java-contrib/pull/4
- Issues responded to
- Community activities I organized/ran
- SIG projects I am involved with
Java SIG, Client Instrumentation SIG

**Comment by SylvainJuge** [comment]
I support @robsunday membership.

**Comment by breedx-splk** [comment]
I support @robsunday membership! Welcome aboard! 🚀

**Comment by trask** [comment]
I support

**Comment by trask** [comment]
Invite sent!
