### ISSUE TITLE
REQUEST: New membership for dazuma

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/community#241]
### GitHub Username

@dazuma

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [ ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ ] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@mwear 
@fbogsany 

### List of contributions to the OpenTelemetry project

https://github.com/census-instrumentation/opencensus-ruby/graphs/contributors
https://github.com/census-instrumentation/opencensus-ruby/commits?author=dazuma
open-telemetry/opentelemetry-ruby#124
open-telemetry/opentelemetry-ruby#138

**Comment by SergeyKanzhelev** [comment]
welcome, @dazuma!
