### ISSUE TITLE
GC ONBOARDING: mx-psi

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2410]
This issue should be assigned to both an existing member and a newly elected
member, and the actions should be performed by both in collaboration. This
ensures fluid communication and a successful onboarding into the
OpenTelemetry Governance Committee.

The issue should be `Closed as completed` by the new member after all steps
have been completed.

## Assumptions
These assumptions ensure that the rest of the guide can be followed
successfully.

The existing member must:

1. Have the necessary privileges to perform the actions listed below.

The new member must:

1. Be familiar with basic OpenTelemetry concepts
   1. [Mission, Vision and Values](https://opentelemetry.io/community/mission/)
   2. [Concepts](https://opentelemetry.io/docs/concepts/)
   3. [Specification](https://opentelemetry.io/docs/specs/otel/)
2. Have read and agreed to comply with the
   [OpenTelemetry Governance Committee Charter](https://github.com/open-telemetry/community/blob/main/governance-charter.md)
   as per requirements to stand for election.
3. Have an email address, Google account, and GitHub account and is willing
   to share those details with other GC members.
   1. **Note**: Google account is mainly needed for Google Docs, but one may
      prefer to use work email or personal email for calendar invites.

## Access Grants
This section ensures that the new member has access to all systems and has the
necessary privileges to perform their role as a member of the GC.

### 1Password
1Password contains credentials for accounts managed by the GC as a group (i.e.
not personal items).

The existing member must:

- [x] Invite new member to [OpenTelemetry 1Password](https://opentelemetry.1password.com)
      via email.
- [x] After invite is accepted, add them to the `Owners` group as a `Manager`.

The  current member must:

- [x] Accept invitation and create new account on [OpenTelemetry 1Password](https://opentelemetry.1password.com).
- [x] Validate they have `Manager` access to `Owners` group, and that the group
      contains only current GC members.
- [x] Validate they have `Full Access` to the `OpenTelemetry Governance` vault.
      This should be given automatically via the `Owners` group.

### CNCF Slack
The main async medium for GC and TC members to communicate is a set of private
channels on Slack.

The existing member must:

- [x] Add new member to the following private channels:
  - [opentelemetry-gc](https://cloud-native.slack.com/archives/C01S673T1NE)
  - [opentelemetry-gc-tc](https://cloud-native.slack.com/archives/C02KF2PPUV9)
  - [opentelemetry-gc-alum](https://cloud-native.slack.com/archives/C02KBUGC685)

The new member must:

- [x] Create a [CNCF Slack](https://slack.cncf.io/) account if they do not
  already have one.

### CNCF Service Desk
Interactions between the OpenTelemetry GC and CNCF are mostly driven via Service
Desk tickets. Members can create tickets to discuss access to systems, licensing,
funds, marketing, press, etc.

The existing member must:

- [x] Create a Service Desk ticket to invite new member via email and add it to
  OpenTelemetry group.

The new member must:

- [x] Accept invitation to CNCF Service Desk and create an account.
- [x] Validate they have access to the [CNCF Service Desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portals)
  (see more information about Service Desk in the [docs](https://github.com/cncf/servicedesk#readme)).
- [x] Validate they have access to [OpenTelemetry Requests](https://cncfservicedesk.atlassian.net/servicedesk/customer/user/requests?page=1&reporter=org-31).

### GitHub
Most of the management, enablement, support and documentation work done by GC
members happens on GitHub.

The existing member must:

- [x] Ask TC to add new member as `Member` to the [open-telemetry](https://github.com/open-telemetry/)
  organization.
- [x] Ask TC to add new member as `Member` to the [open-telemetry/governance-committee](https://github.com/orgs/open-telemetry/teams/governance-committee)
  team.
- [x] Add new member as code owner in [open-telemetry/community](https://github.com/open-telemetry/community/blob/main/CODEOWNERS)
- [x] Add new member to the list of GC members in [open-telemetry/community/community-members.md](https://github.com/open-telemetry/community/blob/main/community-members.md).
- [x] Add new member in the `OpenTelemetry (Governance Committee)` section of [cncf/foundation/project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)

### Mailing Lists
The following mailing lists ensure that communications reach all necessary
members of this group.

The existing member must:

- [x] Invite new member as `Moderator`, ensuring that they have the same
  privileges as existing members, to the following mailing lists:
  - https://lists.cncf.io/g/cncf-opentelemetry-governance
  - https://lists.cncf.io/g/cncf-otel-zoomadmins
- [x] Open CNCF Service Desk ticket to invite new member as `Member` to 
  https://lists.cncf.io/g/cncf-opentelemetry-maintainers

The new member must:
- [x] Accept invitations to mailing lists above, creating an account on https://lists.cncf.io
  if necessary, using their preferred email address.

### Google Drive
OpenTelemetry handles minutes and other ad-hoc documents in Google Drive.

The existing member must:

- [x] Give new member write access to:
  - [OpenTelemetry Governance Committee meeting notes](https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8)

The new member must:

- [x] Validate they have write access to the documents listed above.

### Zapier
Zapier is used to sync meeting recordings from Zoom to a publicly viewable
Google spreadsheet (see https://github.com/open-telemetry/community/blob/main/docs/how-meeting-recordings-upload-works.md
for more details).

The new member must:
- [x] Validate they can log in to https://zapier.com with the credentials in 1Password.

## Meetings and Ceremonies
As per GC charter, all members are expected to attend the following meetings:

- Governance Committee Meeting (every Thursday 11:00 Pacific Time).
- Governance/Technical Committee Joint Meeting (every second Thursday of the month,
  coinciding with the Governance Committee Meeting).

The dates and times of these meetings may be discussed and updated after every
election cycle to accommodate time zones and scheduling requirements of attendees.

The existing member must:
- [x] Invite the new member to the meetings using the new members' preferred
  email address.

## Further Reading
The following is a list of documents and other media that new members must
familiarize themselves with. The new member must go through these media and ask
any relevant questions that will aid them in understanding their role as a GC
member. The existing member must assist the new member, to the best of their
capacity, in finding answers to these questions.

- [x] [OpenTelemetry Code of Conduct](https://github.com/open-telemetry/community/blob/main/code-of-conduct.md):
  all GC members define, evolve, and defend the Code of Conduct.
- [x] [OpenTelemetry Governance Committee meeting notes](https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8):
  to identify items currently in progress. [Meeting Recordings](https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s)
  can help get more details if needed.
- [x] [Project Management](https://github.com/open-telemetry/community/blob/main/project-management.md):
  to understand the fundamentals of how projects are managed by the GC and TC.
- [x] [Active Projects](https://github.com/open-telemetry/community/tree/main/projects):
  to understand current project deliverables and the challenges they aim to
  solve.
- [x] [Project Board](https://github.com/orgs/open-telemetry/projects/29):
  including the individual project boards for each of these, they help
  understand the current state of the projects listed in the previous item.
- [x] [Community repo docs](https://github.com/open-telemetry/community/tree/main/docs):
  for instructions on how to work with calendars, configuring repositories,
  uploading recordings, etc. As a GC member, it is useful to know that these 
  docs are there when needed.
- [x] [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/):
  this free orientation course is designed to provide you with essential
  background knowledge and practical skills to create an inclusive culture
  in the open source community. Members of the GC may take this course in
  support of our community values.

**Comment by danielgblanco** [comment]
Congratulations again @mx-psi! 🎉  

Issue for team membership:

https://github.com/open-telemetry/community/issues/2413

PR with changes required to GC members:

https://github.com/open-telemetry/community/pull/2412

**Comment by danielgblanco** [comment]
We still have to decide how we assign GC liaison for the different SIGs current assigned to @dyladan. It might make sense to do a full review as timezones may be challenging.

**Comment by mx-psi** [comment]
> Congratulations again @mx-psi! 🎉

Thank you! 

Will update the issue checklist once I have write access :) 

And yes, I think it also makes sense for me to be the liaison for the SIGs I participate in

**Comment by mx-psi** [comment]
@trask We are unsure if this should be done or if this part is outdated:

> The existing member must:
> 
>  Add user as Owner of [groups.google.com/g/opentelemetry-calendar-contributors](https://groups.google.com/g/opentelemetry-calendar-contributors).
> The new member must:
> 
>  Validate they have Owner permissions on the group above.

 Could you help us double check?

**Comment by danielgblanco** [comment]
The only place where the group is used is in https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#zoom-bombing-prevention

I don't know if we still require host keys for Zoom bombing to be shared this way, or if we can remove that doc entirely. If we do require it, we can share it with another group like https://groups.google.com/a/opentelemetry.io/g/calendar-edit-permission.

In any case, I'll raise a PR to remove this requirement, because it's not needed anymore for member onboarding.

**Comment by danielgblanco** [comment]
All tasks are done except for the [cncf-opentelemetry-maintainers](https://lists.cncf.io/g/cncf-opentelemetry-maintainers) mailing list. This is being discussed in a Service Desk ticket, along with @dyladan's offboarding.

**Comment by trask** [comment]
> I don't know if we still require host keys for Zoom bombing to be shared this way, or if we can remove that doc entirely. If we do require it, we can share it with another group like https://groups.google.com/a/opentelemetry.io/g/calendar-edit-permission.

I just sent #2424 for this part

**Comment by danielgblanco** [comment]
Raised https://github.com/open-telemetry/opentelemetry.io/pull/5540 to update website. I don't think that needs to be added to the onboarding issue template. Should probably happen on a regular cadence as a desired end-state.

**Comment by mx-psi** [comment]
I got invited to [lists.cncf.io/g/cncf-opentelemetry-maintainers](https://lists.cncf.io/g/cncf-opentelemetry-maintainers) today, so I think we are all set here :rocket:
