### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-dotnet-instrumentation

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/community#2418]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

### Requested changes

The SIG maintainers lost the rights to update their project board.

### Purpose

We use project boards to track items to be completed by each milestone and release.
 
### Expected Duration

Permanently

### Repository Maintainers

@open-telemetry/dotnet-instrumentation-maintainers

**Comment by trask** [comment]
sorry about that, it was a side effect of #2356, I've given @open-telemetry/dotnet-instrumentation-approvers access now, let me know if you wanted a different access setup

**Comment by pjanotti** [comment]
Thanks @trask - I will double check with the other maintainers, meeting is today, and will you let you know.

**Comment by nrcventura** [comment]
I have access again. Thank you!

**Comment by Kielek** [comment]
Works for me also. Feel free to close this issue :)
