### ISSUE TITLE
Request for guidance: Collector SIG meeting timezones

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/community#2419]
In the repo readme, the following is stated about meeting timezones:

>The meeting times in the tables below are given in 24-hour notation. All meeting hours between 2pm and 1am UTC are in Pacific Time (PT), with Daylight Saving Time. All meeting hours between 2am and 1pm UTC in UTC+8, without Daylight Saving Time.

All Collector meeting times have been set to PT since most meeting attendees are in places where Daylight Savings Time is used. Since the notice conflicts with the meeting times, can we:

1. Add to the notice that meeting hours between 2am and 1pm UTC are in UTC+8 *unless otherwise noted*.
2. Remove the notice since all meeting times are already listed with the timezone next to them.
3. Leave the Collector meeting as an unstated exception since the meeting time is explicitly listed in PT both in the readme and on the calendar.

I think option 1 is sufficient, but want to get consensus. We could also change the one corresponding meeting time to fit this pattern, but I would prefer that the meeting time remains the same throughout the year for as many attendees as possible, which requires pinning to a timezone that uses DST.

**Comment by svrnm** [comment]
I would prefer (1) over (2) -- we introduced that statement because we had non-PST meetings all over the place across different timezones and wanted to get some consistency.

Here is another propsal:

> The meeting times in the tables below are given in 24-hour notation. Meeting are either in Pacific Time (PT), with Daylight Saving Time or UTC+8, without Daylight Saving Time.

This way we remove that admittedly arbitrary and very strict time blocks and SIGs can pick the timezone they prefer while remaining consistent

**Comment by trask** [comment]
there's similar language at https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#create-the-meeting:

> * Timeslot, with the right timezone set:
>   * All meeting hours between 2pm and 1am UTC are in Pacific Time (PT), with Daylight Saving Time.
>   * All meeting hours between 2am and 1pm UTC in UTC+8, without Daylight Saving Time.
