### ISSUE TITLE
REQUEST: New membership for dazuma

### ISSUE THREAD

**Issue by dazuma** [open-telemetry/community#242]
### GitHub Username

@dazuma

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @fbogsany 
- @mwear

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-ruby/pull/138 https://github.com/open-telemetry/opentelemetry-ruby/pull/124
- Issues responded to: https://github.com/open-telemetry/opentelemetry-ruby/issues/94 https://github.com/open-telemetry/opentelemetry-ruby/issues/95 https://github.com/open-telemetry/opentelemetry-ruby/issues/77
- SIG projects I am involved with: ruby
- I am also one of the core engineers on OpenCensus Ruby and Stackdriver for Ruby, and expect to be heavily involved in the integration efforts there.

**Comment by dazuma** [comment]
Whoops, looks like this was already done.

**Comment by SergeyKanzhelev** [comment]
welcome again =)
