### ISSUE TITLE
REQUEST: New membership for christophe-kamphaus-jemmic

### ISSUE THREAD

**Issue by christophe-kamphaus-jemmic** [open-telemetry/community#2433]
### GitHub Username

christophe-kamphaus-jemmic

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lmolkova 
- @adrielp 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/semantic-conventions/pull/1383
  - https://github.com/open-telemetry/oteps/pull/258
  - https://github.com/open-telemetry/semantic-conventions/pull/1075
- Issues responded to
  - https://github.com/open-telemetry/semantic-conventions/issues/915
  - https://github.com/open-telemetry/semantic-conventions/issues/1111
  - https://github.com/open-telemetry/semantic-conventions/issues/1452
  - https://github.com/open-telemetry/semantic-conventions/issues/1453
- Community activities I organized/ran
- SIG projects I am involved with
  - Semantic Conventions
  - CICD SemConv SIG

**Comment by lmolkova** [comment]
I support!

**Comment by adrielp** [comment]
I support as well!

**Comment by trask** [comment]
Invite sent!
