### ISSUE TITLE
REQUEST: New membership for phanidevavarapu

### ISSUE THREAD

**Issue by phanidevavarapu** [open-telemetry/community#2436]
### GitHub Username

e.g. @phanidevavarapu

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @pavankrish123

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [PRs reviewed / authored](https://github.com/open-telemetry/opamp-go/pulls?q=is%3Apr+author%3Aphanidevavarapu+is%3Aclosed)
- [Issues responded to](https://github.com/open-telemetry/opamp-go/issues?q=author%3Aphanidevavarapu)
- [Community activities I organized/ran](N/A)
- [SIG projects I am involved with](https://github.com/open-telemetry/opamp-go)

**Comment by pavankrish123** [comment]
I support

**Comment by trask** [comment]
hi @phanidevavarapu! I'm not sure if @pavankrish123 meets the sponsor requirement

> Sponsors must be approvers or maintainers in at least 1 CODEOWNERS file in any repo in the OpenTelemetry org.

can you maybe check with another opamp-go approver or maintainer?

**Comment by pavankrish123** [comment]
Hi @trask, I am the code owner for otel collector oauth2extension https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS#L105  

Kindly let me know if anything else is needed from my end

**Comment by trask** [comment]
thanks @pavankrish123! yes, I think that meets the requirement, thanks!

**Comment by trask** [comment]
Invite sent!
