### ISSUE TITLE
2024 OpenTelemetry Community Awards Announcement 🎉 

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2439]
The OpenTelemetry Governance Committee is excited to announce the winners of our 2024 OpenTelemetry Community Awards! The first of their kind. This is our opportunity to recognise those individuals in our community that contribute to the project in many wonderful ways. Read more about OpenTelemetry Community Awards in this [blog post](https://opentelemetry.io/blog/2024/community-awards/).

Without further ado, the winners are....

@serkan-ozal
@anunarapureddy
@avillela
@codeboten
@emdneto

If you're listed above, and you're currently at KubeCon NA Salt Lake City, please drop by the OpenTelemetry Observatory in the Solutions Showcase hall to collect you award! 🏅 If you're not, please reach out to any member of the GC.

Thanks to everyone that nominated others, and thanks to those for their contributions!

**Comment by anunarapureddy** [comment]
@danielgblanco Unfortunately, I couldn’t make it to KubeCon NA in Salt Lake City this year. Could I delegate a peer to collect the award at the booth? :)

**Comment by danielgblanco** [comment]
@anunarapureddy and @serkan-ozal can you reach out to me on CNCF Slack or LinkedIn?

**Comment by emdneto** [comment]
Thank you @danielgblanco ! Unfortunately, I couldn't attend Kubecon, but I'm contacting @jpkrohling to see what we can do.

**Comment by jpkrohling** [comment]
@emdneto, your award should be on its way to Brazil already :-)

**Comment by danielgblanco** [comment]
Closing this issue as owners have been announced and blog post is out.
