### ISSUE TITLE
REQUEST: Organization maintenance in codecov

### ISSUE THREAD

**Issue by pellared** [open-telemetry/community#2440]
### Affected Repository

All repositories in the organization.

### Requested changes

Please set the authentication option to "Not required".
It is designed for public open-source repositories.
Hyperlink: https://app.codecov.io/account/gh/open-telemetry/org-upload-token

### Purpose

Codecov changed its token policy
From https://app.codecov.io/account/gh/open-telemetry:
> You must now upload using a token. Upload with either or the repo upload token. Contact your admins to manage the upload token settings.

This change is now needed if we want to use the new v5 of codecov-action. See: https://github.com/codecov/codecov-action/issues/1645

Blocks OTel Go PR: https://github.com/open-telemetry/opentelemetry-go/pull/5979

PS. It still may not work because of "the upload is for a commit that is on an unprotected branch" condition from https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token (but the docs may be outdated or not accurate). I suggest not closing the issue until I confirm that everything is working fine.
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/go-maintainers

**Comment by trask** [comment]
> Please set the authentication option to "Not required".
> It is designed for public open-source repositories.
> Hyperlink: https://app.codecov.io/account/gh/open-telemetry/org-upload-token

I made this change.

It looks like we have a `CODECOV_TOKEN` org secret, but wondering what it was used for (I don't think PRs can access any secrets, so doesn't seem like it would have been useful for codecov reports, at least on PRs).

Leaving this issue open for a bit to give others a chance to comment or raise any concerns.

**Comment by pellared** [comment]
> I don't think PRs can access any secrets, so doesn't seem like it would have been useful for codecov reports, at least on PRs.

It is not working for forks, but it works when the branch is in upstream. For v4 the action was working fine so far on forks in a "tokenless" mode. I suggest keeping the `CODECOV_TOKEN` org secret  at least until everyone migrates to v5.

**Comment by pellared** [comment]
> I made this change.

Thanks! https://github.com/open-telemetry/opentelemetry-go/pull/5979 passed.
I will close the issue when we merge the PR and also see that there is no issue when the action runs on `main`.

**Comment by pellared** [comment]
CI passed on `main`: https://github.com/open-telemetry/opentelemetry-go/actions/runs/11853793435/job/33034653950#step:3:172
