### ISSUE TITLE
REQUEST: New membership for echlebek

### ISSUE THREAD

**Issue by echlebek** [open-telemetry/community#2441]
### GitHub Username

@echlebek

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@andrzej-stencel 

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opamp-go/pull/254
- https://github.com/open-telemetry/opamp-go/pull/251
- https://github.com/open-telemetry/opamp-go/issues/256

**Comment by echlebek** [comment]
Hello @andrzej-stencel,

I would be grateful for your sponsorship on becoming an organization member, and maybe you could put in a good word for me with another approver. 🙏

**Comment by andrzej-stencel** [comment]
I support! Eric works at Sumo Logic in the team that builds the Sumo OTel Collector distro and the Sumo Helm chart that uses the collector. Definitely worth having Eric in the OpenTelemetry community! 👍

**Comment by srikanthccv** [comment]
I support—@echlebek thanks for your contributions.

**Comment by echlebek** [comment]
Thank you for your support @andrzej-stencel and @srikanthccv!
