### ISSUE TITLE
REQUEST: New membership for lopes-felipe

### ISSUE THREAD

**Issue by lopes-felipe** [open-telemetry/community#2442]
### GitHub Username
lopes-felipe

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling 
- @andrzej-stencel 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project
https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is:pr+is:closed+author:lopes-felipe
https://github.com/open-telemetry/opentelemetry.io/pulls?q=is:pr+is:closed+author:lopes-felipe

**Comment by andrzej-stencel** [comment]
I support!

**Comment by jpkrohling** [comment]
I support as well

**Comment by arminru** [comment]
Invite sent. Welcome, @lopes-felipe!
