### ISSUE TITLE
REQUEST: New membership for pitoniak32

### ISSUE THREAD

**Issue by pitoniak32** [open-telemetry/community#2452]
### GitHub Username

@pitoniak32

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cijothomas
- @TommyCpp

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored:
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2204
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2217
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2221
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2241
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2255
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2258
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2303
  - https://github.com/open-telemetry/opentelemetry-rust/pull/2322
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-rust/issues/1810
  - https://github.com/open-telemetry/opentelemetry-rust/issues/2270
  - https://github.com/open-telemetry/opentelemetry-rust/issues/2294
  - https://github.com/open-telemetry/opentelemetry-rust/issues/1961
- Community activities I organized/ran
- SIG projects I am involved with
  - opentelemetry-rust (SDK)

**Comment by TommyCpp** [comment]
I will sponsor too

**Comment by cijothomas** [comment]
I support.

**Comment by trask** [comment]
Invite sent!

**Comment by pitoniak32** [comment]
Thank you all!
