### ISSUE TITLE
REQUEST: Repository maintenance on docs-cn and docs-ja

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2453]
### Affected Repository

* https://github.com/open-telemetry/docs-cn
* https://github.com/open-telemetry/docs-ja

### Requested changes

Archive these repositories.

Suggested process:
* Give existing repo maintainers some time to approve/reject this request of archival. These are @open-telemetry/docs-ja-maintainers and @open-telemetry/docs-cn-maintainers 
* If approved, we will add a note to the README.md of both repos in English and the respective language that this repo is archived
* Archive the repo via github repo settings.
* Also delete @open-telemetry/docs-cn-approvers & @open-telemetry/docs-cn-maintainers, since this group is superseded by @open-telemetry/docs-zh-approvers and @open-telemetry/docs-zh-maintainers. Keep `ja` groups. 

### Purpose

Both repos haven't been updated in a long time, and also we have started to implement localizations within the opentelemetry.io repo, so they are no longer needed
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/docs-cn-maintainers @open-telemetry/docs-cn-approvers 
@open-telemetry/docs-zh-approvers @open-telemetry/docs-zh-maintainers 
@open-telemetry/docs-ja-approvers @open-telemetry/docs-ja-maintainers

**Comment by ymotongpoo** [comment]
as a part of @open-telemetry/docs-ja-approvers, I agree upon archiving the old JA repo.

**Comment by trask** [comment]
@svrnm just post back when it's ok to go ahead with the archival, thanks!

**Comment by svrnm** [comment]
@trask docs-ja can be archived

**Comment by trask** [comment]
both docs-ja and docs-cn are archived now

**Comment by svrnm** [comment]
> both docs-ja and docs-cn are archived now

can we close the open issues on docs-cn as well? 

The teams @open-telemetry/docs-cn-approvers & @open-telemetry/docs-cn-maintainers are also no longer needed, since the `zh` teams are used in docs, can you delete them as well?

**Comment by trask** [comment]
> can we close the open issues on docs-cn as well?

I wasn't sure if you want to leave a note when you close them or not, so I've unarchived the repo, just let me know when you're done and I'll re-archive and delete the teams

**Comment by svrnm** [comment]
> > can we close the open issues on docs-cn as well?
> 
> I wasn't sure if you want to leave a note when you close them or not, so I've unarchived the repo, just let me know when you're done and I'll re-archive and delete the teams

all issues closed, so the repo can be archived again, thanks. 

Can you also remove the groups?

**Comment by trask** [comment]
done!
