### ISSUE TITLE
REQUEST: create a triager role for JS Contrib

### ISSUE THREAD

**Issue by JamieDanielson** [open-telemetry/community#2455]
JS would like a `javascript-contrib-triagers` role to help facilitate code reviews on packages in the contrib repo. The role should have permission only on the JS contrib repo. 

CC: @open-telemetry/javascript-maintainers

**Comment by trask** [comment]
create https://github.com/orgs/open-telemetry/teams/javascript-contrib-triagers

and gave that group triage permission on https://github.com/open-telemetry/opentelemetry-js-contrib

I added the existing https://github.com/orgs/open-telemetry/teams/javascript-maintainers as team maintainers, so you should be able to add/remove members as needed
