### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector-releases

### ISSUE THREAD

**Issue by ArthurSens** [open-telemetry/community#2457]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector-releases

### Requested changes

Enable the [Require merge queue setting](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) on the branch protection rules for the main branch with "squash" merge method
 
### Purpose

The Github documentation linked above puts it succinctly:

> The merge queue provides the same benefits as the Require branches to be up to date before merging branch protection, but does not require a pull request author to update their pull request branch and wait for status checks to finish before trying to merge.

To be 100% transparent here our final goal is to enable the same configuration in https://github.com/open-telemetry/opentelemetry-collector-contrib, but we'd like to test the possible side effects of the new configuration in a smaller repository before doing so.

In the contrib repository, our goal is to improve contributor experience by accelerating merges. It's too much manual work to keep all PRs based on latest main, so the merge queue will help us here.
 
### Expected Duration

Permanently

### Repository Maintainers

- @open-telemetry/collector-contrib-maintainers 
- @open-telemetry/collector-maintainers

**Comment by mx-psi** [comment]
I support this

**Comment by mx-psi** [comment]
Both https://github.com/open-telemetry/opentelemetry.io and https://github.com/open-telemetry/opentelemetry-js use a merge queue. I think having the same configuration as those would be reasonable here.

**Comment by mx-psi** [comment]
Thanks @trask! I tried merging open-telemetry/opentelemetry-collector-releases/pull/751 but it seems like there is something related to the branch protection rules that needs to be set up in a different way:
![image](https://github.com/user-attachments/assets/34603b02-a1b2-499b-ad2a-ad11798e64d7)

I don't think I am able to fix this on my own, maybe you can compare the branch protection rules that exist in the opentelemetry(.)io/opentelemetry-js repositories?

**Comment by mx-psi** [comment]
My guess is that `github-merge-queue[bot]` needs to be authorized to push to the main branch/to the temporary merge queue branch.

**Comment by mx-psi** [comment]
Looks like it worked now! I am closing this, but since we will be setting this up in other repositories, would you mind documenting what was done here to solve the branch protection error?

**Comment by mx-psi** [comment]
Okay, you can try with https://github.com/open-telemetry/opentelemetry-collector-releases/pull/736, just removed from the queue. I'll reopen until we get this right :)

Another interesting bit (this may be on us): we have the merge queue now, but it seems like only the "Build" job is running :thinking: 
![image](https://github.com/user-attachments/assets/1a996da7-aae9-424b-87cd-1b7446cd1a84)

https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/12034936523/job/33552687997

Despite having multiple `merge_group` items after open-telemetry/opentelemetry-collector-releases/pull/755.

**Comment by trask** [comment]
ok, the configuration in #2459 looks like it's working

> Another interesting bit (this may be on us): we have the merge queue now, but it seems like only the "Build" workflow is running 🤔

you may need to add `merge_group` to the workflows, e.g.

```
on:
  pull_request:
  merge_group:
```

**Comment by mx-psi** [comment]
> ok, the configuration in #2459 looks like it's working
> 
> > Another interesting bit (this may be on us): we have the merge queue now, but it seems like only the "Build" workflow is running 🤔
> 
> you may need to add `merge_group` to the workflows, e.g.
> 
> ```
> on:
>   pull_request:
>   merge_group:
> ```

This was done in open-telemetry/opentelemetry-collector-releases/pull/755, I think what matters here is that the merge queue only waits/shows the jobs marked as required. I feel like that is an independent problem, we can make a separate request for adding further required checks in the future if needed.

**Comment by ArthurSens** [comment]
All good to close this one? :)
