### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-proto-go

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/community#2458]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-proto-go

### Requested changes

Enable renovate app.
 
### Purpose

We are switching from dependabot to renovate for this repository.
See https://github.com/open-telemetry/opentelemetry-proto-go/issues/195
 
### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/proto-go-maintainers

**Comment by trask** [comment]
hi @dmathieu! I enabled Renovate for the repo.

It looks like you set up the branch protections already, but I think you'll need to switch the order so that `renovate/**/**` is before `**/**`.
