### ISSUE TITLE
Create maintainer team for auto-instr-java

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/community#246]
Hello! I am looking to set up maintainers and approvers for https://github.com/open-telemetry/opentelemetry-auto-instr-java.

Initial maintainers are @trask, @tylerbenson, and @SevaSafris. I believe @jkwatson and others would like to be approvers, but since we decentralizing now, this is just a request for the maintainers to be set up with access.

We also may want to change the naming convention for our agent repos at some point. :)

**Comment by jkwatson** [comment]
yes, I would like to be an approver, at least.

**Comment by SergeyKanzhelev** [comment]
https://github.com/orgs/open-telemetry/teams/auto-instr-java-approvers
https://github.com/orgs/open-telemetry/teams/auto-instr-java-maintainers/members

Also configured repository. Please re-open if something else is needed.
