### ISSUE TITLE
REQUEST: New membership for @flc1125

### ISSUE THREAD

**Issue by flc1125** [open-telemetry/community#2461]
### GitHub Username

@flc1125

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@pellared
@dmathieu

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
	- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6373
	- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6365
	- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6373
	- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6360
	- https://github.com/open-telemetry/opentelemetry-go/pull/5994
- Issues responded to
	- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4588
	- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5088
	- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5741
	- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5090
- Some projects or discussions participated in
	- https://github.com/open-telemetry/opentelemetry-php/issues/1411	
	- https://github.com/open-telemetry/opentelemetry.io/issues/5417
	- https://github.com/uptrace/uptrace/issues/414
	- https://github.com/hyperf-contrib/open-telemetry
	- https://github.com/flc1125/go-cron/issues/7  - Based on robfig/cron not supporting OTEL, secondary improvements have been made (current progress: still in testing).
	- https://github.com/redis/go-redis/pull/3168

**Comment by pellared** [comment]
I support

**Comment by dmathieu** [comment]
I support

**Comment by trask** [comment]
Invite sent!

**Comment by flc1125** [comment]
Thank you all。
