### ISSUE TITLE
[Proposal] Move Semantic Convention: Tooling to Implementation or Cross-Cutting SIG

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/community#2463]
`Semantic Convention: Tooling` SIG mostly discuss needs of semconv and release planning for the [Opentelemery Weaver](https://github.com/open-telemetry/weaver) project.

I think this is better categorized as an implementation SIG focused on building OpenTelemetry weaver to support semconv, *or* a cross-cutting SIG as we have donated and contributed to other SIGs for the purpose of semconv codegen.

We currently defer specification related changes from tooling to the Semantic Convention SIG and/or the Specification SIG.

**Comment by mx-psi** [comment]
I feel like this fits best in the Implementation SIG category
