### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-go-instrumentatoin

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#2464]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go-instrumentation

### Requested changes

Enable renovate app.
 
### Purpose

We are switching from dependabot to renovate for this repository. See https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/1317
 
### Expected Duration

permanently

### Repository Maintainers

- @open-telemetry/go-instrumentation-maintainers

**Comment by trask** [comment]
done!
