### ISSUE TITLE
REQUEST: New membership for @jj22ee

### ISSUE THREAD

**Issue by jj22ee** [open-telemetry/community#2468]
### GitHub Username

@jj22ee

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pichlermarc 
- @trentm

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-js/pull/5006
  - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2344
  - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2361
  - https://github.com/open-telemetry/opentelemetry-java/pull/4574
  - https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1488
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19173
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19204
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26041
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3620
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3652
- Issues responded to
- Community activities I organized/ran
- SIG projects I am involved with
  - opentelemetry-js-contrib
  - opentelemetry-js
  - opentelemetry-collector-contrib

**Comment by pichlermarc** [comment]
I support 🙂

**Comment by trentm** [comment]
I support

**Comment by trask** [comment]
Invite sent!

**Comment by jj22ee** [comment]
Accepted the invite, thanks all!
