### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-collector

### ISSUE THREAD

**Issue by jade-guiton-dd** [open-telemetry/community#2472]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-collector

### Requested changes

Add the `Merge freeze / Check` CI check introduced in [this PR](https://github.com/open-telemetry/opentelemetry-collector/pull/11744) to the required checks for the `main` branch.
 
### Purpose

With the merge queue enabled (#2469), this should allow automatically cancelling merges while a release PR is open. See the PR for more details. Note that the check does not actually run on `main`, only in PRs and queues merging into `main`.
 
### Expected Duration

Permanently, unless it causes issues during the next release period.

### Repository Maintainers

- @open-telemetry/collector-maintainers

**Comment by mx-psi** [comment]
I support this

**Comment by trask** [comment]
done

just a heads up, it has a pretty generic name `Check`:

![image](https://github.com/user-attachments/assets/0131127e-86cb-4c67-827d-3bf5fb057566)
