### ISSUE TITLE
OpenTelemetry End of Year 2-Week Break?

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#2473]
Based on GC discussion, we'd like to propose canceling all OpenTelemetry meetings from Monday, Dec 23 through Fri, Jan 3.

This would give everyone a well-deserved break from meetings and avoid the overhead of every SIG having to decide individually whether to keep or cancel their meetings during this time period.

**Comment by svrnm** [comment]
looks like we all agree that this should happen:-)

**Comment by trask** [comment]
All OpenTelemetry meetings from Monday, Dec 23 through Fri, Jan 3 have been canceled, and a (dismissible) github org banner has been posted:

> OpenTelemetry will observe an end-of-year break between Monday, Dec 23 and Fri, Jan 3. All SIG meetings are cancelled during this time. Responses may be delayed to non-security-related issues or pull requests.
