### ISSUE TITLE
ARM64 runner access for opentelemetry-rust and opentelemetry-cpp repos

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/community#2474]
`opentelemetry-rust` and `opentelemetry-cpp` were earlier successfully using `actuated-arm64-4cpu-16gb` as arm64 runners in the CI environment. But they [stopped working](https://github.com/open-telemetry/opentelemetry-rust/actions/runs/12150848605/job/33884386969?pr=2380) sometime back. Can we get the access to `actuated-arm64-4cpu-16gb`, or else the [GitHub-hosted ARM64 runners](https://github.com/open-telemetry/community/blob/main/assets.md#github-hosted-arm64-runners) for both main and contrib repo.

cc @open-telemetry/cpp-maintainers @open-telemetry/rust-maintainers

**Comment by mx-psi** [comment]
Actuated is no longer available see https://github.com/open-telemetry/community/issues/2135#issuecomment-2438011230 and https://github.com/open-telemetry/community/pull/2423#issuecomment-2461719932, so I think we need to use Github hosted runners

**Comment by trask** [comment]
hi @lalitb!

I've given opentelemetry-cpp repository access to the OpenTelemetry GitHub ARM runners, it looks like opentelemetry-rust already has access.

the runner names are:

* `otel-linux-arm64`
* `otel-windows-arm64`

they are both 4-core, 16 gb ram

**Comment by lalitb** [comment]
Thanks @trask. Closing the issue.
