### ISSUE TITLE
REQUEST: New membership for manu2

### ISSUE THREAD

**Issue by manu2** [open-telemetry/community#2475]
### GitHub Username
 @manu2

### Requirements

- [Yes] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [Yes] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [Yes] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [Yes] I am actively contributing to 1 or more OpenTelemetry subprojects
- [Yes] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [YEs] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@dashpole
@mx-psi 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Issues responded to : 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36112
-  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32397
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32397

#### Updates:
- PRs submitted:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36685
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36683

**Comment by KiranmayiB** [comment]
LGTM

**Comment by dsimil** [comment]
I support

**Comment by KiranmayiB** [comment]
I support

**Comment by dashpole** [comment]
> sponsored by 2 approvers or maintainers. multiple contributions to the project.

@manu2 I think the general expectation is that contributions are PRs, rather than comments.

@dsimil and @KiranmayiB are not approvers or maintainers for the OpenTelemetry collector.  They were granted a temporary exception to become a component codeowner with the expectation that they will become members within a few months. You can see the list of approvers here: https://github.com/open-telemetry/opentelemetry-collector-contrib?tab=readme-ov-file#contributing

I can be one sponsor, and we need to find one more sponsor.  @mx-psi mentioned at kubecon he would be willing to sponsor members of the spanner team after they make contributions.

**Comment by mx-psi** [comment]
> I can be one sponsor, and we need to find one more sponsor. @mx-psi mentioned at kubecon he would be willing to sponsor members of the spanner team after they make contributions.

Indeed, I would be happy to sponsor @manu2 after they make a PR contribution :)

**Comment by manu2** [comment]
@mx-psi Added the recently submitted PRs

**Comment by dashpole** [comment]
Feel free to add list me as a sponsor in the issue description.

**Comment by dashpole** [comment]
I support

**Comment by mx-psi** [comment]
I support

**Comment by trask** [comment]
Invite sent!
