### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-operator

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/community#2478]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-operator

### Requested changes

- Enable the renovate app for the repo
- Ensure branch protection rules for renovatebot/ branches are setup to allow them to be updated [main/docs/how-to-configure-new-repository.md#branch-protection-rule-renovate](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md?rgh-link-date=2023-11-14T19%3A46%3A02Z#branch-protection-rule-renovate)

### Purpose

The operator repo would like to start using renovate for managing tooling upgrades: https://github.com/open-telemetry/opentelemetry-operator/issues/3450.

### Expected Duration

permanently

### Repository Maintainers

@open-telemetry/operator-maintainers

**Comment by trask** [comment]
done, onboarding PR: https://github.com/open-telemetry/opentelemetry-operator/pull/3520
