### ISSUE TITLE
REQUEST: New membership for aalexand

### ISSUE THREAD

**Issue by aalexand** [open-telemetry/community#2482]
### GitHub Username

@aalexand

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @christos68k
- @jhalliday

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-proto

**Comment by christos68k** [comment]
I support

**Comment by petethepig** [comment]
I support

**Comment by mtwo** [comment]
I support!

**Comment by jhalliday** [comment]
Long-standing and valuable participant in the profiling spec work. I support.

**Comment by trask** [comment]
Invite sent!

**Comment by felixge** [comment]
I support!
