### ISSUE TITLE
REQUEST: New membership for alizenhom

### ISSUE THREAD

**Issue by alizenhom** [open-telemetry/community#2484]
### GitHub Username

@alizenhom

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @karthikscale3
- @codefromthecrypt

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

- https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2984
- https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2759

- SIG projects I am involved with
- LLM Semantic Conventions
- Core maintainer of the open source project Langtrace (https://github.com/Scale3-Labs/langtrace) which implements a python and typescript SDK for the GenAI stack that follows the OpenTelemetry GenAI semantic conventions.

**Comment by karthikscale3** [comment]
I support

**Comment by codefromthecrypt** [comment]
I support!

**Comment by trask** [comment]
Invite sent!
