### ISSUE TITLE
REQUEST: New membership for @jerbly

### ISSUE THREAD

**Issue by jerbly** [open-telemetry/community#2486]
### GitHub Username

@jerbly

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jsuereth 
- @lquerel

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/weaver/pull/177
  - https://github.com/open-telemetry/weaver/pull/467
  - https://github.com/open-telemetry/weaver/pull/494
  - https://github.com/open-telemetry/weaver/pull/504
  - https://github.com/open-telemetry/weaver/pull/515
- Issues responded to
  - https://github.com/open-telemetry/weaver/issues/481
  - https://github.com/open-telemetry/weaver/issues/502
  - https://github.com/open-telemetry/weaver/issues/405
- Community activities I organized/ran
- SIG projects I am involved with
  - opentelemetry/weaver

**Comment by lmolkova** [comment]
I'm not listed, but I support anyway!

**Comment by jsuereth** [comment]
I support!

**Comment by lquerel** [comment]
I support!
