### ISSUE TITLE
Create maintainer team for auto-instr-python

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/community#249]
Hey hey! I am looking to set up maintainers and approvers for https://github.com/open-telemetry/opentelemetry-auto-instr-python. There's an initial prototype based on the DDog Python client, which I'd love to have pushed here for contributors to review/help ;)

Initial maintainers will be me (temporary) and members from the OTel Python team who might be interested (please comment on this Issue).

**Comment by codeboten** [comment]
Would love to be involved

**Comment by yurishkuro** [comment]
Any reason why that team cannot be created in the repository itself? This way you don't need to go to TC to update it.

**Comment by yurishkuro** [comment]
(or perhaps I am seeing Add Team because I am the org admin)

**Comment by c24t** [comment]
If you go with this structure, sign me up @carlosalberto. :D

> Any reason why that team cannot be created in the repository itself? This way you don't need to go to TC to update it.

AFAIK teams are scoped to the org, not the repo. [python-approvers](https://github.com/orgs/open-telemetry/teams/python-approvers/members) and -maintiners belong to [OpenTelemetry](https://github.com/orgs/open-telemetry/teamsa) org, and I don't see an option to add a new team as a non-admin.

**Comment by tigrannajaryan** [comment]
Is Python auto-instrumentation SIG already started or this is brand new?

**Comment by toumorokoshi** [comment]
I would love to be an approver at least. Potentially a maintainer but that's only to have the ability to merge outstanding PRs.

Regardless I'm very excited for this and would love to be involved!

**Comment by SergeyKanzhelev** [comment]
CC: @reyang @ramthi

**Comment by hectorhdzg** [comment]
I would like to be part of this as well

Thanks

**Comment by reyang** [comment]
I can be an approver and help to review the design/code. I might not have time to be maintainer.

**Comment by carlosalberto** [comment]
Hey @tigrannajaryan 

> Is Python auto-instrumentation SIG already started or this is brand new?

It's based out of the DataDog Python client (https://github.com/DataDog/dd-trace-py), which has been **initially** modified to export its traces to the OTel Python SDK (which was in turn done as a prototype).

**Comment by carlosalberto** [comment]
https://github.com/open-telemetry/opentelemetry-auto-instr-python
https://github.com/orgs/open-telemetry/teams/auto-instr-python-approvers/members

Closing this issue (will follow up with @codeboten to put the prototype code on the repo ;) )
