### ISSUE TITLE
REQUEST: New membership for @mterhar

### ISSUE THREAD

**Issue by mterhar** [open-telemetry/community#2498]
### GitHub Username

@mterhar 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use https://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @TylerHelmuth 
- @atoulme 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs
  - add libhoneyreceiver to contrib release https://github.com/open-telemetry/opentelemetry-collector-releases/pull/787
  - add ignorelist https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18681
  - add log() function to ottlfuncs https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21825

**Comment by atoulme** [comment]
`e.g. (at)example_user` I guess should be @mterhar

**Comment by atoulme** [comment]
I support!

**Comment by mterhar** [comment]
> `e.g. (at)example_user` I guess should be @mterhar

Thanks. I missed that one.

**Comment by TylerHelmuth** [comment]
I support

**Comment by trask** [comment]
Invite sent!
