### ISSUE TITLE
Separate API repo for Erlang/Elixir

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/community#251]
tldr: Erlang/Elixir would benefit from having a separate repo for the api package.

I've created it already under my own account in order to get started https://github.com/tsloughter/opentelemetry-erlang-api and would like to transfer it to the open-telemetry organization.

I will open a transfer request.

**Comment by tsloughter** [comment]
Never mind, I can't open a request to transfer... Not sure how to do this.

**Comment by SergeyKanzhelev** [comment]
Done
