### ISSUE TITLE
REQUEST: New membership for <obecny>

### ISSUE THREAD

**Issue by obecny** [open-telemetry/community#254]
### GitHub Username

@obecny

### Organization you are requesting membership in

open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mayurkale22
- @bg451

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-js/commits?author=obecny
- https://github.com/open-telemetry/opentelemetry-js/issues/created_by/obecny
- https://github.com/open-telemetry/opentelemetry-js/issues/assigned/obecny
- SIG JS

**Comment by SergeyKanzhelev** [comment]
welcome, @obecny
