### ISSUE TITLE
REQUEST: New membership for paivagustavo

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/community#257]
### GitHub Username

@paivagustavo

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lizthegrey 
- @rghetia

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [prs authored](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-go+author%3Apaivagustavo+is%3Apr&type=Issues)
  - [prs reviewed](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-go+reviewed-by%3Apaivagustavo+type%3Apr)
- Issues responded to
  - [issues authored/responded](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-go+involves%3Apaivagustavo+type%3Aissue)
- SIG projects I am involved with
  - SIG Go

**Comment by SergeyKanzhelev** [comment]
welcome, @paivagustavo
