### ISSUE TITLE
REQUEST: New membership for zachdaniel

### ISSUE THREAD

**Issue by zachdaniel** [open-telemetry/community#258]
### GitHub Username

@zachdaniel

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tsloughter 
- @hauleth 

### List of contributions to the OpenTelemetry project

- review of https://github.com/open-telemetry/opentelemetry-erlang-api/pull/2
- I've taken part in many of the discussions, primarily as the pertain to Elixir and the Elixir API, and hope to take an active part in developing and pushing the Elixir implementation of open-telemetry forward.

**Comment by SergeyKanzhelev** [comment]
welcome, @zachdaniel

**Comment by tsloughter** [comment]
@SergeyKanzhelev does @zachdaniel need to be added to a specific repo or group so his reviews "count" on the erlang repos? I added him to `CODEOWNERS`, https://github.com/open-telemetry/opentelemetry-erlang-api/blob/master/CODEOWNERS#L15 , but you can see on this PR that his +1 is still black and doesn't have the codeowner lock icon next to it https://github.com/open-telemetry/opentelemetry-erlang-api/pull/18

**Comment by SergeyKanzhelev** [comment]
Yes, please add to @open-telemetry/erlang-approvers 

please read this for more details: https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md

**Comment by tsloughter** [comment]
Oh right :man_facepalming: 

Thanks!
