### ISSUE TITLE
REQUEST: New membership for dyladan

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#259]
### GitHub Username

@dyladan

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mayurkale22 
- @danielkhan

#### Open PRs
- https://github.com/open-telemetry/opentelemetry-js/pull/525

#### Merged PRs
- https://github.com/open-telemetry/opentelemetry-js/pull/516
- https://github.com/open-telemetry/opentelemetry-js/pull/504
- https://github.com/open-telemetry/opentelemetry-js/pull/508
- https://github.com/open-telemetry/opentelemetry-js/pull/497
- https://github.com/open-telemetry/opentelemetry-js/pull/483
- https://github.com/open-telemetry/opentelemetry-js/pull/482
- https://github.com/open-telemetry/opentelemetry-js/pull/472
- https://github.com/open-telemetry/opentelemetry-js/pull/470
- https://github.com/open-telemetry/opentelemetry-js/pull/468

#### Authored Issues
- https://github.com/open-telemetry/opentelemetry-js/issues/549
- https://github.com/open-telemetry/opentelemetry-js/issues/513
- https://github.com/open-telemetry/opentelemetry-js/issues/504
- https://github.com/open-telemetry/opentelemetry-js/issues/471
- https://github.com/open-telemetry/opentelemetry-js/issues/416
- https://github.com/open-telemetry/opentelemetry-js/issues/406

**Comment by bogdandrutu** [comment]
Welcome to the community dyladan@, and thanks for all your contributions.
