### ISSUE TITLE
REQUEST: Opentelemetry Service member for flands

### ISSUE THREAD

**Issue by flands** [open-telemetry/community#26]
### GitHub Username

@flands

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu
- @pjanotti

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/census-instrumentation/opencensus-service/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Aflands
- Issues responded to: https://github.com/census-instrumentation/opencensus-service/issues?utf8=%E2%9C%93&q=mentions%3Aflands+
- SIG projects I am involved with: open-telemetry agent and collector

**Comment by SergeyKanzhelev** [comment]
I sent invite for membership in OpenTelemetry. If you need permissions like approver or maintainer - let's discuss.
