### ISSUE TITLE
Would like to contribute an OpenTelemetry client for Swift

### ISSUE THREAD

**Issue by nacho-undefinedlabs** [open-telemetry/community#261]
Hi all,
We have been developing a OpenTelemetry client for Swift, and we would like to contribute it to the community. We would like to know what are the steps we should follow.

The repository is located at https://github.com/undefinedlabs/opentelemetry-swift.

**Comment by SergeyKanzhelev** [comment]
@nacho-undefinedlabs it is great to hear! Do you want to become a maintainer for this repository? I'll ask around if there are more people interested to join this project. Typically we want maintainers from at least two companies.

In general - it is very simple process. Once we identified who will be maintaining this repository, we will create a repo and you will need to submit your repo as a PR so we will clear this code from CLA perspective.

**Comment by tedsuo** [comment]
Fabulous!

**Comment by nacho-undefinedlabs** [comment]
Yes, you can count on me as a maintainer for the repository. I hope more people will be interested in joining it.

Thanks a lot

**Comment by lakamsani** [comment]
Hey I 'm interested. I am with https://github.com/WeWork (survived the recent layoffs!). https://github.com/dnlh and I are trying to get tracing infrastructure built for our apps.

**Comment by austinlparker** [comment]
this is rad. to the future maintainers, once you're set up in the OTel org, please see https://github.com/open-telemetry/community/issues/201 for info on how to get your library listed on the website!

**Comment by lakamsani** [comment]
@nacho-undefinedlabs  I assume you already took a look at https://github.com/wayfair/jaeger-swift . Can we leverage anything from there or do you see that also evolving into another independent Open Telemetry Swift implementation (from the currently Open Tracing/Jaeger focussed implementation).

**Comment by nacho-undefinedlabs** [comment]
@lakamsani No, I didn’t look at that project, but all the specific implementations for vendors should evolve to span exporters. Swift project would ideally have exporters for any vendor, in fact, implementing a Jaeger exporter should be high in the project priority list.

**Comment by SergeyKanzhelev** [comment]
@nacho-undefinedlabs do you want to move it forward?

**Comment by nacho-undefinedlabs** [comment]
Yes, I would like to move it forward. Contribute it to the community and can also become a maintainer.

**Comment by SergeyKanzhelev** [comment]
New repository: https://github.com/open-telemetry/opentelemetry-swift

We don't really have a formal process for declaring maintainers for the new repository. It is based on who asks. 

@nacho-undefinedlabs I made you a maintainer. Anybody else interested?

@open-telemetry/admins please comment in you have a suggestion on how we can approach the maintainers defining for the new projects. Should we have some sort of call for maintainers in community e-mail list?

**Comment by SergeyKanzhelev** [comment]
Please comment if you want to join the swift team.
