### ISSUE TITLE
Create approver and maintainer teams for Rust + CODEOWNERS

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/community#262]
Would someone mind creating a "rust-approvers" team and "rust-maintainers" child team corresponding to [opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust)?

Related to this, could we also have CODEOWNERS configured for the opentelemetry-rust repo?

Thanks!

open-telemetry/opentelemetry-rust#3

**Comment by bogdandrutu** [comment]
Please let me know who is maintainer and who is approver to add to the teams.

**Comment by iredelmeier** [comment]
Hmm, the initial maintainer list (@hawkw, @heavypackets, and myself) from #252 seems to have carried through to repo permissions, but not be stored anywhere.

Maintainers have admin access for the approver and maintainer teams, right? If so, I think we can add people once the teams get created. If not, we should at least add @jtescher as a maintainer.

**Comment by SergeyKanzhelev** [comment]
@iredelmeier you are a maintainer of both teams. Also I enabled CLA for the repo. Surprised it wasn't enforced before.
