### ISSUE TITLE
REQUEST: New membership for MikeGoldsmith

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/community#263]
### GitHub Username

@mikegoldsmith

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @austinlparker 
- @SergeyKanzhelev 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[OpenTelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+author%3AMikeGoldsmith+is%3Aclosed)

- Issues responded to
https://github.com/open-telemetry/opentelemetry-dotnet/issues/343

- SIG projects I am involved with
.NET & Rust

**Comment by austinlparker** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @MikeGoldsmith
