### ISSUE TITLE
REQUEST: New membership for jtescher

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/community#264]
### GitHub Username

@jtescher

### Organization you are requesting membership in

open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @iredelmeier 
- @toumorokoshi 

### List of contributions to the OpenTelemetry project

- Rust SIG member
- Author of original https://github.com/open-telemetry/opentelemetry-rust

**Comment by toumorokoshi** [comment]
+1. Welcome to the project!

**Comment by SergeyKanzhelev** [comment]
Welcome, @jtescher!
