### ISSUE TITLE
Calendar write permissions for maintainers

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/community#267]
The [current calendar docs](https://github.com/open-telemetry/community/blob/5109bda85be7061caa32b5838f396dd339282208/docs/how-to-handle-public-calendar.md) specify that all SIG maintainers can edit the calendar, but this doesn't seem to be the case.

CC @mtwo since I think you own the calendar?

**Comment by SergeyKanzhelev** [comment]
I think it's by request. Perhaps we need to mention the process of asking permissions in the document. @mtwo can you please do it?

**Comment by mtwo** [comment]
Created https://github.com/open-telemetry/community/pull/273
