### ISSUE TITLE
REQUEST: New membership for morrisonlevi

### ISSUE THREAD

**Issue by morrisonlevi** [open-telemetry/community#269]
### GitHub Username

morrisonlevi

### Organization you are requesting membership in

opentelemetry-php

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bobstrecansky
- @AustinSchoen

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-php/pull/31
  - https://github.com/open-telemetry/opentelemetry-php/pull/23

**Comment by SergeyKanzhelev** [comment]
Welcome, @morrisonlevi
