### ISSUE TITLE
REQUEST: New membership for AustinSchoen

### ISSUE THREAD

**Issue by AustinSchoen** [open-telemetry/community#270]
### GitHub Username

AustinSchoen 

### Organization you are requesting membership in

opentelemetry/php

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bobstrecansky
- @morrisonlevi

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-php/pull/33
https://github.com/open-telemetry/opentelemetry-php/pull/31
- Issues responded to
https://github.com/open-telemetry/opentelemetry-php/issues/22
- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-php

**Comment by SergeyKanzhelev** [comment]
Welcome, @AustinSchoen
