### ISSUE TITLE
Nominate @toumorokoshi for python-maintainers

### ISSUE THREAD

**Issue by c24t** [open-telemetry/community#271]
### GitHub Username

@toumorokoshi 

### Organization you are requesting membership in

@open-telemetry/python-maintainers 

### Requirements

- [ ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ ] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @c24t 
- (cc @open-telemetry/python-maintainers)

### List of contributions to the OpenTelemetry project

- [opentelemetry-python PRs reviewed (79 as of 12/10/19)](https://github.com/open-telemetry/opentelemetry-python/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Atoumorokoshi)
- [opentelemetry-python PRs authored (14 as of 12/10/19)](https://github.com/open-telemetry/opentelemetry-python/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atoumorokoshi+)

@toumorokoshi has been heavily involved in the OpenTelemetry specification and python client since the start of the project in July 2019. He has been instrumental in context propagation and tracer API/SDK work, and has worked consistently to keep the project in good health and welcoming to new contributors. He is already doing the work expected of a maintainer, and more.

**Comment by SergeyKanzhelev** [comment]
Great to hear!

This kind of requests can be handled by @open-telemetry/python-maintainers , no need to create an issue here. Let us know if any help is needed with this.

**Comment by c24t** [comment]
Thanks @SergeyKanzhelev. Are there any teams that still use this nomination form or should we delete the issue template?
