### ISSUE TITLE
REQUEST: New membership for ocelotl

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/community#274]
### GitHub Username

@ocelotl

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [ ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ ] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @c24t
-  @carlosalberto 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python/pulls?q=is%3Apr+author%3Aocelotl)
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-python/issues/236

**Comment by SergeyKanzhelev** [comment]
@c24t please react as a sponsor

**Comment by SergeyKanzhelev** [comment]
welcome, @ocelotl

**Comment by ocelotl** [comment]
Thanks!
