### ISSUE TITLE
Create maintainer team for auto-instr-ruby

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/community#275]
I'd like to create an initial maintainer team for the Ruby auto-instrumentation effort (https://github.com/open-telemetry/opentelemetry-auto-instr-ruby) - I'm wondering if we should, for a start, delegate this directly to the Ruby approvers/maintainers team?

cc @mwear

**Comment by tedsuo** [comment]
If it is the same group (ruby SIG) is working on both repos, would it make sense to keep these two projects as separate gems, in the same repo?  Or are separate repos better?

**Comment by mwear** [comment]
I think this is for the Ruby SIG to decide. I'll create an issue on the OTel Ruby repo and we can discuss there.

**Comment by SergeyKanzhelev** [comment]
Please re-open once you will decide on how this SIG will be managed.
