### ISSUE TITLE
REQUEST: New membership for MrAlias

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#281]
### GitHub Username

@MrAlias

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @lizthegrey 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-specification/pull/308
  - https://github.com/open-telemetry/opentelemetry-go/pull/289
  - https://github.com/open-telemetry/opentelemetry-specification/pull/347
  - https://github.com/open-telemetry/oteps/pull/49
  - https://github.com/open-telemetry/opentelemetry-go/pull/289
  - https://github.com/open-telemetry/opentelemetry-go/pull/404
  - https://github.com/open-telemetry/opentelemetry-go/pull/394
  - https://github.com/open-telemetry/opentelemetry-go/pull/416
  - https://github.com/open-telemetry/oteps/pull/66
  - https://github.com/open-telemetry/opentelemetry-go/pull/418
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-go/issues/341
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-go

**Comment by SergeyKanzhelev** [comment]
@jmacd please react. I don't see any problems, just need your ack.

**Comment by jmacd** [comment]
@MrAlias has my strong support!

**Comment by SergeyKanzhelev** [comment]
Welcome, @MrAlias!
