### ISSUE TITLE
KubeCon EU 2020 maintainers track session suggestions

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#282]
If you are a maintainer of one of the SIGs and have ideas for the hot topics for KubeCon EU 2020 maintainers track or want to present - please comment here or reach out to [cncf-opentelemetry-governance@lists.cncf.io](https://github.com/open-telemetry/community#governance-committee).

The goal for maintainers track is to introduce new or casual end users or contributors to OpenTelemetry activities.

@yurishkuro also suggested that Jaeger maintainers track session can be used to promote tracing concepts and OpenTelemetry while also speak about Jaeger.

## Summary so far:

Past KubeCon NA talk and slides: https://kccncna19.sched.com/event/Uake

Who wants to speak (no particular order. Added affiliation as it may help to decide):
@carlosalberto (LightStep), @mwear (LightStep), @iredelmeier (LightStep), @austinlparker (LightStep), @bobstrecansky (MailChimp), @mtwo (Google), @bhs (LightStep), @flands (Splunk) 

Proposed topic ideas:

- OpenTracing and OpenCensus - how to migrate to start using and contributing to OpenTelemetry.
- Introductory talk - getting started with OpenTelemetry.
- Introductory talk - what is tracing and why you should care.
- Getting started with OpenTelemetry and K8s
- Auto-instrumentation
- collectors

Deadline for proposal submission is coming soon. So please comment today/tomorrow

CC:
@open-telemetry/collector-maintainers 
@open-telemetry/dotnet-maintainers 
@open-telemetry/cpp-maintainers 
@open-telemetry/go-maintainers 
@open-telemetry/java-maintainers 
@open-telemetry/auto-instr-java-maintainers 
@open-telemetry/javascript-maintainers 
@open-telemetry/python-maintainers 
@open-telemetry/ruby-maintainers 
@open-telemetry/erlang-maintainers 
@open-telemetry/php-maintainers 
@open-telemetry/rust-maintainers

**Comment by austinlparker** [comment]
Would there be interest in a talk on how people can get involved in the community writ large? Could talk about how to run workshops, contribute to the registry/website, stuff like that.

**Comment by SergeyKanzhelev** [comment]
@austinlparker we mention it briefly last time at KubeCon San-Diego. Do we have a successful examples of these initiatives that can be shared?

**Comment by austinlparker** [comment]
Yeah, we've done a couple of the workshops and will have another one done by KubeCon EU. The registry will be live then as well, and we've got stuff from running it for OpenTracing as well.

**Comment by iredelmeier** [comment]
@SergeyKanzhelev thoughts on a talk on migrating from OpenTracing/OpenCensus/etc?

**Comment by SergeyKanzhelev** [comment]
@iredelmeier I'd think the technical details of migration may be offtopic. Not sure. Perhaps with the focus on how to migrate from contributing to OpenTracing and OpenCensus and start contributing to OpenTelemetry? What are your thoughts?

**Comment by mwear** [comment]
I could give a talk on OpenTelemetry basics. It doesn't necessarily have to be from the Ruby perspective, but it could.

**Comment by iredelmeier** [comment]
@SergeyKanzhelev yeah, I wasn't thinking of the technical details but instead either contributing or (more likely) going from **using** either OT or OC to OpenTelemetry.

**Comment by carlosalberto** [comment]
I'm also up for giving an introductory talk as I will be attending the event in Amsterdam this year. It can either be basics (similar to @mwear ) or an actual OTel Java workshop.

**Comment by bobstrecansky** [comment]
I think an intro class about the benefits of tracing, especially with respect to OpenTelemetry, would be great.  We all sit in the tracing space all the time so we know the benefits, but many of the engineers I talk to don't know what tracing is. If they do, they don't know how it would benefit them. A talk on how to use tracing impactfully (especially with context around OpenTelemetry and K8s) would probably be a really well received talk.

**Comment by yurishkuro** [comment]
We usually give this intro as part of Jaeger Intro session. That session is currently up for grabs, if someone wants to participate, please ping me.

**Comment by SergeyKanzhelev** [comment]
Summary so far:

KubeCon NA talk and slides: https://kccncna19.sched.com/event/Uake

Who wants to speak:
@carlosalberto, @mwear, 

Proposed topic ideas:
1. OpenTracing and OpenCensus - how to migrate to start using and contributing to OpenTelemetry.
2. Introductory talk - getting started with OpenTelemetry.
3. Introductory talk - what is tracing and why you should care.
4. Getting started with OpenTelemetry and K8s

@iredelmeier, @austinlparker, @bobstrecansky you haven't explicitly expressed interest to speak. Please let me know if you assumed this with your comment.

Deadline for proposal submission is coming soon. So please comment today/tomorrow

**Comment by iredelmeier** [comment]
@sergeykanzhelev I'm happy to talk, at least about migrating existing instrumentation.

**Comment by SergeyKanzhelev** [comment]
got it

**Comment by mtwo** [comment]
I'm happy to talk as well, though I don't have any super creative ideas about what we should present beyond a project status update

**Comment by bhs** [comment]
I'd be happy to do a presentation about OTel and auto-instrumentation. IMO that's something we're under-representing in our project status stuff if we think about the perspective of an end-user considering OTel vs OC vs OT.

**Comment by austinlparker** [comment]
Yeah, I'd be happy to speak.

**Comment by bobstrecansky** [comment]
I'd like to come (and present), but new 👶 may restrict me from doing so, not quite sure yet.

**Comment by flands** [comment]
I'd be happy to do a presentation on the collector with others /cc @ccaraman @tigrannajaryan

**Comment by SergeyKanzhelev** [comment]
@flads - great idea to present the collector. I think collector runtime config + some auto-instrumentation proposed by @bhs would demonstrate the spirit of the project very well.

**Comment by SergeyKanzhelev** [comment]
@bobstrecansky I fully understand. I've added you into the list to consider anyway.

**Comment by SergeyKanzhelev** [comment]
This is closed now. After the discussion of governance committee we decided that the best topic representing community will be the combination of java auto-instrumentation and collector work. @trask and @flands, thank you for readiness to speak at maintainers track!

Thank you everybody for ideas and readiness to talk!
