### ISSUE TITLE
Restore community meetings back

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#283]
its on the calendar but no one is here and no updates to the agenda

Sergey Kanzhelev @SergeyKanzhelev 10:15
I don't see it on calendar

Tristan Sloughter @tsloughter 10:15
argh, I must have copied it to my calendar
but it is the second wednesday of every month, isn't it

Sergey Kanzhelev @SergeyKanzhelev 10:16
I'm not sure. In case of this meeting - I'm in calendar-driven mode =) @mtwo would know but he is still on vacation I think

Tristan Sloughter @tsloughter 10:18
looks like they've all been removed from the calendar shrug

**Comment by mtwo** [comment]
In the last community and governance meetings we agreed to move it to the fourth Wednesday of each month, which appears to be correctly reflected in the community calendar (?)

**Comment by SergeyKanzhelev** [comment]
I think the issue was that the calendar invite stuck on some people's calendars. Looking back at gitter it seems that the issue was that the previous invite cancellation wasn't propagated properly.
