### ISSUE TITLE
Rebrand Governance meeting to Community Office hours

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#284]
Rebrand this meeting as “Community Office Hours”
- Pick new meeting times that don’t overlap with SIG meetings
- Alternate Europe and Asia/Pacific friendly times.

@mtwo we decided to assign this to you =)

**Comment by mtwo** [comment]
On it!

**Comment by mtwo** [comment]
Renamed to "Monthly OpenTelemetry Community & Governance Office Hours"
The meetings now alternate between 10:00 AM PT and 4:00 PM PT
