### ISSUE TITLE
Please add me to the go-approvers team

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/community#291]
As per https://github.com/open-telemetry/opentelemetry-go/pull/445, I requested a membership in the @open-telemetry/go-approvers team, but it seems like no one there is a team maintainer, so not sure if they can add me to the team. Thanks.

CC: @open-telemetry/go-approvers @open-telemetry/go-maintainers

**Comment by SergeyKanzhelev** [comment]
everything is fixed now. @rghetia and @jmacd are now owners of the  @open-telemetry/go-approvers team and can self-service. Thank you!
