### ISSUE TITLE
REQUEST: New membership for @mauriciovasquezbernal

### ISSUE THREAD

**Issue by c24t** [open-telemetry/community#292]
### GitHub Username

@mauriciovasquezbernal

### Organization you are requesting membership in

@open-telemetry 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @c24t 
- @toumorokoshi 

### List of contributions to the OpenTelemetry project

- [opentelemetry-python PRs reviewed (27 as of 01/22/20)](https://github.com/open-telemetry/opentelemetry-python/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Amauriciovasquezbernal)
- [opentelemetry-python PRs authored (20 as of 01/22/20)](https://github.com/open-telemetry/opentelemetry-python/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amauriciovasquezbernal+)

See also https://github.com/open-telemetry/opentelemetry-python/issues/373, which adds @mauriciovasquezbernal to the [python-approvers team](https://github.com/orgs/open-telemetry/teams/python-approvers/members).

**Comment by toumorokoshi** [comment]
+1.

**Comment by SergeyKanzhelev** [comment]
Welcome, @mauriciovasquezbernal!
