### ISSUE TITLE
REQUEST: New membership for @prydin

### ISSUE THREAD

**Issue by prydin** [open-telemetry/community#293]
### GitHub Username

@prydin

### Organization you are requesting membership in

e.g. (at)open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @tylerbenson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/118
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/115
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/113
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/112
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/94
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/87
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/81
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/75
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/72
https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/62

- Issues responded to
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/117
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/105
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/96
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/95
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/93
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/92
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/85
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/84
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/83
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/80
https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/78

- SIG projects I am involved with
opentelemetry-auto-instr-java

**Comment by trask** [comment]
👍

**Comment by tylerbenson** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
Welcome, @prydin!
