### ISSUE TITLE
REQUEST: New membership for GregMefford

### ISSUE THREAD

**Issue by GregMefford** [open-telemetry/community#297]
### GitHub Username

@GregMefford 

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tsloughter 
- @zachdaniel
- @hauleth 

### List of contributions to the OpenTelemetry project

- #279 
- #280 
- OpenTelemetry talk at FOSDEM 2020 BEAM devroom (https://beam-fosdem.org/schedule/)
- Contributing to Erlang/Elixir SIG
- Erlang Ecosystem Foundation Observability Working Group member

**Comment by tsloughter** [comment]
:+1:

**Comment by hauleth** [comment]
👍

**Comment by zachdaniel** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
Welcome, @GregMefford
