### ISSUE TITLE
Enable DCO for all of OT

### ISSUE THREAD

**Issue by caniszczyk** [open-telemetry/community#300]
Per the CNCF IP Policy, we require all projects to enforce the DCO.
https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

Please install this and enable it against the whole organization:
https://github.com/apps/dco

**Comment by yurishkuro** [comment]
OTel uses CLA, doesn't CLA supersede DCO?

**Comment by Oberon00** [comment]
I'd be against enabling DCO, from a practical perspective, because it would make using the GitHub online editor, or applying PR suggestions impossible.

**Comment by mtwo** [comment]
+1 to Yuri’s comment, I thought that implementing a CLA made DCO unnecessary?

________________________________

**Comment by Oberon00** [comment]
Or rather: Is the CLA bot not an implemenation of DCO (Developer Certificate of Origin) that replaces the Signed-off mechanism?

**Comment by bhs** [comment]
@caniszczyk can you respond to the above re OTel's use of CLA as an alternative? If that's acceptable, we will close this issue.

**Comment by lizthegrey** [comment]
We aren't yet using CNCF's new CLA bot, and I'm taking that as an AI

**Comment by bogdandrutu** [comment]
@lizthegrey before enabling make sure we have an easy path in terms of signing the new CLA and we don't block the entire project by having to wait for each company to sign the CLA again.

**Comment by lizthegrey** [comment]
We use CNCF EasyCLA now. Marking this as moot.
