### ISSUE TITLE
guidance for multiple repos per SIG

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/community#301]
After attending a few SIGs, I've observed a common pattern that seems to cause pause in getting code changes into the project: committing auxiliary code to the SIG SDK repo, e.g. code for plugins and code for auto-instrumentation.

The debate usually revolves around keeping a mono-repo structure vs creating lots of separate repos for each plugin (could be 10s of plugins), and varying degrees of structure in-between.

I'd like to propose the open-telemetry adopt an option to create multiple repo structure to allow SIGs chose within their community if they need more than 1 repo and have it created quickly, but with some guide rails. A guidance along the lines of these points:

- SIGs may have 1 main repo for their codebase and it must be listed in the top-level list of SIGs https://github.com/open-telemetry/community#special-interest-groups as well as the registry https://opentelemetry.io/registry/
- SIGs may choose to have an auxiliary repo to keep other code, but it must have a repo name prefix the same as their main repo. The main repo should point to the auxiliary repo in their readme and also list the auxiliary repo in the registry. The SIG should be mindful of having PR checks in the auxiliary repo verify code is compatible with the main repo.
- SIGs may also chose to have a policy of externally-related repos (repos not in the open-telemetry github org) to associate with and if so state in the readme of the main repo to add a pointer to the externally-related repo in the registry. There should also be documentation on how to make sure the externally-related repo is kept up-to-date with the SIG's main repo codebase for PR checks.
- In general it would be good to keep the number of auxiliary repos to a minimum (say less than 5) so as to limit the administrative process of maintaining too many repos for open-telemetry.

My hope is this guidance will help SIGs come to resolution quickly about adopting code.

**Comment by tigrannajaryan** [comment]
This makes sense and is similar to what we do for the Collector SIG. We have a main "collector" repo and an auxiliary "collector-contrib" repo.

**Comment by SergeyKanzhelev** [comment]
@andrewhsu do you think there should be an explicit mention for this? As @tigrannajaryan mentioned there are precedence: collector has three repos: primary, contrib and operator, erlang has a separate repo just for api. Basically, SIG decides how to organize and build the code. Perhaps this can be mentioned in the doc: https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md Please send PR if you feel it's unclear that this is a possibility.

**Comment by andrewhsu** [comment]
@tigrannajaryan @SergeyKanzhelev yes, i can open a PR with proposed wording in the docs.

**Comment by tsloughter** [comment]
For Erlang/Elixir we have an org https://github.com/opentelemetry-beam 

Each SIG making an org like that would make it easy for each SIG to handle contributions and repos on their own. Just need to link out to them from the website and to include the libraries in them into the registry.

**Comment by SergeyKanzhelev** [comment]
@tsloughter unfortunately the approach with multiple orgs will not work for everybody if those orgs are not managed and controlled by CNCF. Controls include CLA enforcements, analytics, code verification, etc.

Using components produced by non-CLA-enforced codebase will not be allowed by many companies as it puts an org at legal risk.

**Comment by SergeyKanzhelev** [comment]
@tsloughter if you experience many problems managing repositories inside this org and feel the need for more control - please let us know.

**Comment by tsloughter** [comment]
Ah, I see.

While we may never hit that issue with users, I wouldn't want it to be  hindrance, and if creating new orgs that is under the CNCF and includes the CLA and such (I think we'd be fine including that on opentelemetry-beam org) isn't a good way to go maybe we will be better off moving to this org.

I partly felt we'd be a bit of a nuisance :). We already had 22 repos for opencensus, https://github.com/opencensus-beam/, and we'll quickly have that many for opentelemetry now that the API is stabilizing.

**Comment by SergeyKanzhelev** [comment]
@tsloughter if we need 22 - let's have 22. Once it will stop scaling we can address it

Please re-open if there are more questions or issues
