### ISSUE TITLE
REQUEST: New membership for thisthat

### ISSUE THREAD

**Issue by thisthat** [open-telemetry/community#302]
### GitHub Username

@thisthat 

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @jkwatson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-java/pull/694
https://github.com/open-telemetry/opentelemetry-java/pull/695
https://github.com/open-telemetry/opentelemetry-java/pull/696
https://github.com/open-telemetry/opentelemetry-java/pull/746
https://github.com/open-telemetry/opentelemetry-java/pull/764
https://github.com/open-telemetry/opentelemetry-java/pull/772
https://github.com/open-telemetry/opentelemetry-java/pull/776
https://github.com/open-telemetry/opentelemetry-java/pull/777
https://github.com/open-telemetry/opentelemetry-java/pull/779
https://github.com/open-telemetry/opentelemetry-java/pull/781
https://github.com/open-telemetry/opentelemetry-java/pull/807
https://github.com/open-telemetry/opentelemetry-java/pull/818
https://github.com/open-telemetry/opentelemetry-java/pull/825
https://github.com/open-telemetry/opentelemetry-java/pull/830
https://github.com/open-telemetry/opentelemetry-java/pull/831
https://github.com/open-telemetry/opentelemetry-java/pull/833
https://github.com/open-telemetry/opentelemetry-specification/pull/389

- Issues responded to
https://github.com/open-telemetry/opentelemetry-java/issues/690
https://github.com/open-telemetry/opentelemetry-java/issues/692
https://github.com/open-telemetry/opentelemetry-java/issues/773
https://github.com/open-telemetry/opentelemetry-java/issues/775
https://github.com/open-telemetry/opentelemetry-java/issues/794
https://github.com/open-telemetry/opentelemetry-java/issues/795
https://github.com/open-telemetry/opentelemetry-java/issues/798
https://github.com/open-telemetry/opentelemetry-java/issues/801
https://github.com/open-telemetry/opentelemetry-java/issues/824
https://github.com/open-telemetry/opentelemetry-specification/issues/435

- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-java

**Comment by SergeyKanzhelev** [comment]
Welcome, @thisthat
