### ISSUE TITLE
Need open-telemetry/opentelemetry-contrib-go repo

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/community#303]
Need a separate repo for plugins/exporters/etc opentelemetry-go (similar to https://github.com/open-telemetry/opentelemetry-collector-contrib repo).
For example, [gormtrace plugin](https://github.com/open-telemetry/opentelemetry-go/pull/490) is better in a contrib repo than in a core-library repo.
Some of the exporters can also go in contrib repo.

**Comment by tigrannajaryan** [comment]
@rghetia would `open-telemetry/opentelemetry-go-contrib` be a better name? (See https://github.com/open-telemetry/community/issues/301)

**Comment by MikeGoldsmith** [comment]
I agree - I think it's best to suffix the existing repo name with `-contrib` to maximise discovery and it'll be consistent with other languages that have done the same.

**Comment by SergeyKanzhelev** [comment]
Done https://github.com/open-telemetry/opentelemetry-go-contrib/

**Comment by rghetia** [comment]
> Done https://github.com/open-telemetry/opentelemetry-go-contrib/

Thanks @SergeyKanzhelev
