### ISSUE TITLE
REQUEST: New membership for @DotSpy

### ISSUE THREAD

**Issue by DotSpy** [open-telemetry/community#304]
### GitHub Username

@DotSpy

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
-  @jkwatson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-java/pull/815
https://github.com/open-telemetry/opentelemetry-java/pull/866
https://github.com/open-telemetry/opentelemetry-java/pull/920
https://github.com/open-telemetry/opentelemetry-java/pull/887
https://github.com/open-telemetry/opentelemetry-java/pull/905
https://github.com/open-telemetry/opentelemetry-java/pull/782
https://github.com/open-telemetry/opentelemetry-java/pull/821
https://github.com/open-telemetry/opentelemetry-java/pull/839
https://github.com/open-telemetry/opentelemetry-java/pull/840
https://github.com/open-telemetry/opentelemetry-java/pull/861
https://github.com/open-telemetry/opentelemetry-js/pull/735
https://github.com/open-telemetry/opentelemetry-js/pull/701

- Issues responded to
https://github.com/open-telemetry/opentelemetry-java/issues/767
https://github.com/open-telemetry/opentelemetry-java/issues/792
https://github.com/open-telemetry/opentelemetry-java/issues/787
https://github.com/open-telemetry/opentelemetry-java/issues/498
https://github.com/open-telemetry/opentelemetry-js/issues/734

- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-java

**Comment by SergeyKanzhelev** [comment]
welcome, @DotSpy
