### ISSUE TITLE
Configure PR Bots with CLA (Renovate)

### ISSUE THREAD

**Issue by markwolff** [open-telemetry/community#306]
- From https://github.com/open-telemetry/opentelemetry-js/pull/829

We have a PR which configures the [Renovate bot](https://github.com/marketplace/renovate) to automatically create PRs on the JS repo to update dependencies to the latest versions. Currently it is blocked since the bot has not signed the CNCF CLA. How can we configure the bot to "sign" the CLA?

/cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
@tedsuo will follow up on policied to enable bots and integrations and how CLA must work

**Comment by mayurkale22** [comment]
@tedsuo any update here?

**Comment by dyladan** [comment]
Seems like there is no way to get Renovate configured because of the CLA requirements. As a workaround, we can use the [Forking Renovate](https://github.com/apps/forking-renovate) plugin. Can an OpenTelemetry owner please enable this on the https://github.com/open-telemetry/opentelemetry-js and https://github.com/open-telemetry/opentelemetry-js-contrib repos?

@open-telemetry/admins

**Comment by lizthegrey** [comment]
Sorry for the delay, I failed to actually get https://lfcla.com/ running, but it was on my plate. Can we defer for a second so I can try to get it up and running?

**Comment by lizthegrey** [comment]
In particular, https://lists.cloudfoundry.org/g/cf-dev/topic/34227989?p=Created,,,20,2,0,0::recentpostdate%2Fsticky,,,20,2,0,34227989 says that it's a supported feature to exempt bots in the new CLA tool.

**Comment by dyladan** [comment]
sounds good to me thanks

**Comment by lizthegrey** [comment]
We have gotten approval from CNCF to migrate, we're just doing the details now.

**Comment by dyladan** [comment]
@lizthegrey any update?

**Comment by lizthegrey** [comment]
Thanks for the reminder, pinging CNCF

**Comment by dyladan** [comment]
@lizthegrey sorry to keep bothering you, but is there an update on this?

**Comment by lizthegrey** [comment]
I emailed CNCF to ask for an update, but given that it hasn't happened so far, I'm not going to block any longer.

**Comment by dyladan** [comment]
If that's the case can an owner install the Forking Renovate plugin on both nodejs repositories?

**Comment by lizthegrey** [comment]
@open-telemetry/technical-committee I believe has the bits to do this.

**Comment by dyladan** [comment]
Someone (I assume @open-telemetry/technical-committee) began the process of installing renovate on our contrib repo (the process was already started on our main repo), but the issue still remains that we cannot merge the PRs because the bot has not "signed" the CLA. Installing [Forking Renovate](https://github.com/apps/forking-renovate) instead of Renovate should solve this issue.

**Comment by lizthegrey** [comment]
@dyladan we have successfully gotten LF/CNCF approval to install the new CLA bot, and are working on implementation!

**Comment by dyladan** [comment]
Great! Any ETA?

**Comment by lizthegrey** [comment]
This week!

**Comment by lizthegrey** [comment]
Once the CLA bot is installed, we'll need you to retrigger CI on at least one pull with the traditional Renovate bot, and then I can get it added as an override.

**Comment by lizthegrey** [comment]
New bot is installed. Please trigger at least one PR with the Renovate bot so I can forward the approval link to the CNCF triage desk to be allowlisted.

**Comment by dyladan** [comment]
Not sure which link you need from the PR, but here is a direct link to the PR bot's response https://github.com/open-telemetry/opentelemetry-js/pull/829#issuecomment-639765944

**Comment by lizthegrey** [comment]
Thank you! Filed https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-1388 with CNCF, they'll get it allowlisted in short order.

**Comment by lizthegrey** [comment]
Should be allowlisted. Please use commands to ask bot to rebase or reopen pull.

**Comment by lizthegrey** [comment]
"EasyCLA check passed. You are authorized to contribute."
