### ISSUE TITLE
Propose creation of a new SIG for logs

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/community#307]
I would like to propose that we create a SIG that will have as a primary goal to define the OpenTelemetry story for logs:
* Define what should OpenTelemetry do in regard to logs - how to do log correlation? do we support collecting logs in the collector? etc.
* Collaborate with other logging related projects in CNCF.
* etc.

**Comment by tigrannajaryan** [comment]
Thanks @bogdandrutu for starting this. I'd like to get involved in the SIG.

**Comment by bogdandrutu** [comment]
/CC @mtwo @c24t I know that this is something that also is interesting for you

**Comment by tedsuo** [comment]
Sounds good to me! Feels like we are still desperate to get tracing and metrics out the door, but I'm happy to start the discussion.

**Comment by bogdandrutu** [comment]
@tedsuo I feel that we need just start discussion, and define some work that these people need to do. No ask for any commitment in terms of implementation work or specs yet.

**Comment by mtwo** [comment]
We're extremely interested. I think that @flands is as well, and possibly @SergeyKanzhelev .

**Comment by SergeyKanzhelev** [comment]
yep

**Comment by yurishkuro** [comment]
+1

**Comment by tigrannajaryan** [comment]
A couple more items for the new SIG charter:

- Come up with a common vocabulary and understanding of logs and their data model.
- Define how logs intersect and correlate with traces and metrics and whether this intersection requires any changes to traces or metrics charters.
- Propose semantic conventions for storing references between logs and other telemetry types that enable correlations. This includes guidelines for storing this data in existing log data formats.
- Decide if OpenTelemetry wants to define a logging API or would like to piggyback on existing logging industry and merely specify how existing industry solutions map to OpenTelemetry’s definitions and data models.
- Decide if OpenTelemetry Collector should be able to handle logs as a data type and how.
- Decide if OpenTelemetry wants to specify a log data format that matches its definition of logs as data model and if so extend OTLP protocol specification to include support for logs. Define mapping of OpenTelemetry’s log data format to existing logging protocols.

I have recently put some thought into a few of these and I volunteer to be SIG's bootstrapper. If there are no objections I can create issues in relevant repos where we can discuss these and other log-related topics and also look into scheduling the first SIG meeting sometime after trace/metric Beta release.

**Comment by c24t** [comment]
cc @otoolep, who works on cloud logging at Google and worked with me and @mtwo on OpenCensus logging.

**Comment by tigrannajaryan** [comment]
Google doc works too. I'll start one.

**Comment by bogdandrutu** [comment]
@tigrannajaryan since you took a step to create this doc, I would suggest also to create an entry in the readme and add this SIG, schedule a meeting, and one of the topic should be also to determine the participants in the SIG (maybe in the first meeting?).

**Comment by c24t** [comment]
If it helps, here's [@mtwo's doc from the OpenCensus logging work last year](https://docs.google.com/document/d/1IieUDioNi7sr7giLDbukjnP6vEhZMfxNcpktudWQwa0/edit?usp=sharing) (copied to remove some internal comments).

**Comment by tigrannajaryan** [comment]
Here is the Doodle to vote for the bootstap meeting slot: https://doodle.com/poll/sthbvs8niwwimpec

**Comment by tigrannajaryan** [comment]
Bootstrap meeting vote complete, confirmed meeting time: Mar 18, 10am Pacific Time / 1pm Eastern Time.

Meeting added to OpenTelemetry calendar.

Zoom: https://zoom.us/j/8203130519

Agenda: https://docs.google.com/document/d/1cX5fWXyWqVVzYHSFUymYUfWxUK5hT97gc23w595LmdM/edit#heading=h.lro8kgalys10a
