### ISSUE TITLE
REQUEST: New membership for ank3it

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#311]
### GitHub Username

e.g. @ank3it

### Organization you are requesting membership in

e.g. open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @SergeyKanzhelev 
- @mtwo 

### List of contributions to the OpenTelemetry project

@ank3it is working on issues triaging and planning for .NET SDK and more broader

**Comment by mtwo** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @ank3it
