### ISSUE TITLE
REQUEST: New membership for hananiel

### ISSUE THREAD

**Issue by hananiel** [open-telemetry/community#312]
### GitHub Username

e.g. @hananiel

### Organization you are requesting membership in

e.g. @open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas 
- @MikeGoldsmith 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
open-telemetry/opentelemetry-dotnet#65
- SIG projects I am involved with
.NET SIG

**Comment by cijothomas** [comment]
I approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @hananiel
