### ISSUE TITLE
Propose creation of a new SIG for releases

### ISSUE THREAD

**Issue by mtwo** [open-telemetry/community#313]
We discussed the creation of a releases SIG during today's beta sync meeting. This SIG would be an extension of the technical committee and would oversee the following:

- Planning and work tracking for upcoming releases (primarily beta, RC, GA)
- Guidelines for building, testing, and releasing (via package managers, etc.) OpenTelemetry artifacts
- Guidelines for documentation, getting started guides, sample applications, etc.

By default, all maintainers and technical committee members would be members of this SIG.

Alternatively we could make the technical committee responsible for the topics that I outlined above - thoughts?

**Comment by mtwo** [comment]
Regardless of whether we choose to create a releases SIG or manage this through the technical committee, beta maintainers should vote on their availability for the next beta meeting: https://doodle.com/poll/k39ppcvkx2mvdesq

**Comment by SergeyKanzhelev** [comment]
My view on this - it is a point in time problem and we can handle it as ad-hoc meetings.

**Comment by dyladan** [comment]
Releases may be a point in time problem, but I definitely think there's value in having the various SIG maintainers meet regularly to ensure implementation is well synchronized

**Comment by SergeyKanzhelev** [comment]
@dyladan beyond the specs meeting?

**Comment by dyladan** [comment]
Spec meetings may be attended by some maintainers but the focus is typically on things that are not even started implementing yet, and we rarely hear about the status of various language SIGs.

**Comment by SergeyKanzhelev** [comment]
I agree that the meeting yesterday was very useful and insightful. My biggest worry is the number of meetings we will subject maintainers to attend. Second - will this meeting be as insightful after a few weeks.

**Comment by dyladan** [comment]
Possibly it won't be that useful every week, but even if it just becomes a 10 minute check-in most weeks, it would be a useful place to ask other maintainers how they interpreted or implemented certain specs. I have found myself multiple times wishing there was some place dedicated for that.

**Comment by mtwo** [comment]
I suggest that we revisit post-beta. For now we can do ad-hoc meetings and coordinate this through the specs SIG?

After reviewing the Doodle, Wednesday from 2:00 to 3:00 appears to work for all respondents. I've sent a meeting invite to everyone who attended Monday's sync.
