### ISSUE TITLE
Introduce a process to assure spec changes are implemented by language SIGs

### ISSUE THREAD

**Issue by arminru** [open-telemetry/community#317]
from https://github.com/open-telemetry/oteps/pull/65#issuecomment-600873288:

We should introduce a process to assure all spec (and proto) changes are implemented by all affected language SIGs and don't go unnoticed.

**Comment by andrewhsu** [comment]
If the release notes for a versioned spec release is clear in describing the updates in the new version, the language SIGs should use that to make sure the new version of the spec is implemented.

Today we have 10 language SIGs plus the collector SIG and each one is on varying states of spec adherence. A maturity matrix was introduced in #290 but it is not automated.

Ideally, would be good to have some type of automated test that can validate the adherence to specific spec version that would work across all languages. This could then be used to drive the update of the maturity matrix.

From the [spec SIG mtg today](https://docs.google.com/document/d/1-bCYkN-DWJq4jw1ybaDZYYmx-WAe6HnwfWbkm8d57v8/edit#heading=h.evt7z82bt2gy) this was discussed and github actions was looked at for keeping the spec release notes changelog up to date.

**Comment by SergeyKanzhelev** [comment]
This issue should belong to specification repository and discussed by @open-telemetry/technical-committee

**Comment by arminru** [comment]
@SergeyKanzhelev I think this issue fits here just as well since it's about cross-SIG collaboration and not the spec itself.

If we agree that the changelog in the spec, the compatibility matrix there for easy verification and the maintainers sync meeting to make everyone aware of the most extensive changes are enough and that we don't need to define a formal process or automatism, I'm fine with closing this issue (which already happened anyway).

**Comment by SergeyKanzhelev** [comment]
Full disclosure I have added it to the next TC meeting agenda after closed in case we need to re-open it in better suited place =). Sorry for not writing it down here explicitly
