### ISSUE TITLE
REQUEST: New membership for nilebox

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/community#318]
### GitHub Username

@nilebox

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @tigrannajaryan 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector/pull/577
  - https://github.com/open-telemetry/opentelemetry-collector/pull/582
  - https://github.com/open-telemetry/opentelemetry-collector/pull/594
  - https://github.com/open-telemetry/opentelemetry-collector/pull/616
  - https://github.com/open-telemetry/opentelemetry-collector/pull/627
  - https://github.com/open-telemetry/opentelemetry-collector/pull/628
  - https://github.com/open-telemetry/opentelemetry-proto/pull/110
  - https://github.com/open-telemetry/opentelemetry-proto/pull/114

- Issues responded to
    - https://github.com/open-telemetry/opentelemetry-collector/issues/574
    - https://github.com/open-telemetry/opentelemetry-collector/issues/619

- SIG projects I am involved with
    - https://github.com/open-telemetry/opentelemetry-collector
    - https://github.com/open-telemetry/opentelemetry-go

**Comment by SergeyKanzhelev** [comment]
Welcome, @nilebox!
