### ISSUE TITLE
Please enable CircleCI GitHub Workflow Checks

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#319]
https://circleci.com/gh/organizations/open-telemetry/settings#vcs -- please follow instructions here, thanks.

**Comment by lizthegrey** [comment]
cc @open-telemetry/technical-committee who have admin access.

**Comment by bogdandrutu** [comment]
I don't know what happens but I see this message:
`This organization's projects will build under trask's plan.`

Looks like @trask did something there so we are no longer admins.

**Comment by lizthegrey** [comment]
Can you temporarily admin me on the github org so I can fix this?

**Comment by lizthegrey** [comment]
You're looking for this button:
![Screenshot from 2020-03-26 13-27-46](https://user-images.githubusercontent.com/614704/77677113-a2af5100-6f65-11ea-93c8-6534ebb465f5.png)

**Comment by trask** [comment]
I don't have access to https://circleci.com/gh/organizations/open-telemetry/settings#vcs, it tells me

![image](https://user-images.githubusercontent.com/218610/77677355-cade8600-6f4c-11ea-8af3-c25a79d7c8b2.png)

**Comment by trask** [comment]
I had to set up payment a while back (with @tedsuo's help) because the Java Auto-Instrumentation project's build requires larger build instances than the free plan allows. But I don't think I'm an org admin.

**Comment by lizthegrey** [comment]
I sorted it out. There's a way to enable it from the GitHub side instead.

**Comment by lizthegrey** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/715

this pull should show Github Actions and a workflow status. I suspect this setting needs changed:

https://circleci.com/gh/open-telemetry/opentelemetry-collector/edit#advanced-settings ->
```Build forked pull requests
Run builds for pull requests from forks. CircleCI will automatically update the commit status shown on GitHub's pull request page.```

**Comment by lizthegrey** [comment]
Found it. it was
```
GitHub Status updates
By default, we update the status of every pushed commit with GitHub's status API. If you'd like to turn this off (if, for example, this is conflicting with another service), you can do so below.
```
