### ISSUE TITLE
REQUEST: New membership for Aneurysm9

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/community#320]
### GitHub Username

@Aneurysm9

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [ x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias
- @jmacd 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-go/pull/565
  - https://github.com/open-telemetry/opentelemetry-go/pull/556
  - https://github.com/open-telemetry/opentelemetry-go/pull/531
  - https://github.com/open-telemetry/opentelemetry-go/pull/473
  - https://github.com/open-telemetry/opentelemetry-go/pull/472
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-go/issues/496
  - https://github.com/open-telemetry/opentelemetry-go/issues/248
  - https://github.com/open-telemetry/opentelemetry-go/issues/149
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-go

**Comment by jmacd** [comment]
I support this membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @Aneurysm9!
