### ISSUE TITLE
Rename opentelemetry-auto-instr-python to opentelemetry-python-contrib

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#322]
Please rename the opentelemetry-auto-instr-python to opentelemetry-python-contrib.

**Comment by SergeyKanzhelev** [comment]
Should I rename teams @open-telemetry/auto-instr-java-maintainers and @open-telemetry/auto-instr-java-approvers too?

**Comment by jkwatson** [comment]
I don't think we should be renaming anything in the java projects, @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
oh, auto-suggestion failed on me. Sorry =) I meant corresponding groups for the python

**Comment by SergeyKanzhelev** [comment]
this is done

**Comment by codeboten** [comment]
Thanks!!
