### ISSUE TITLE
Enable Travis for opentelemetry-python-contrib

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#324]
Please turn on CI for the opentelemetry-python-contrib repo

**Comment by SergeyKanzhelev** [comment]
what permissions do I need? 

![image](https://user-images.githubusercontent.com/9950081/78731329-4dbff300-78f4-11ea-8265-528f43650f0b.png)

**Comment by codeboten** [comment]
I would guess this needs someone who has admin access to the repo?

**Comment by carlosalberto** [comment]
It's activated now - no need for you @SergeyKanzhelev to look into that, thanks! Closing this issue.

**Comment by codeboten** [comment]
Thanks @carlosalberto!
