### ISSUE TITLE
Create open-telemetry/auto-instr-dotnet repository

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/community#325]
The OpenTelemetry .NET team are starting to look into auto instrumentation and require a place outside of the manual instrumentation repository to work.

Please can we have a new repository `open-telemetry/auto-instr-dotnet`, which follows the same name pattern as other languages.

@pjanotti @reyang

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev @bhs @sarahnovotny @ccaraman @yurishkuro @lizthegrey @tedsuo @carlosalberto @mtwo are you ok with this?

**Comment by SergeyKanzhelev** [comment]
Creating the repository is fine. I would, however, delay on importing DD codebase to understand pros and cons better.

**Comment by pjanotti** [comment]
The .NET SIG agreed to move ahead with auto-instrumentations, details at 07/14 .NET SIG meeting notes and the roadmap for .NET Auto-Instrumentation:

- [.NET Meeting Notes](https://docs.google.com/document/d/1yjjD6aBcLxlRazYrawukDgrhZMObwHARJbB9glWdHj8/edit#)
- [.NET Auto-Instrumentation Roadmap](https://docs.google.com/document/d/1F25EzxYa7iSs2r9u0kjetCNPGS7Ui-bneHJEEwzEFR4/edit?usp=sharing)

cc @bhs @bogdandrutu @sarahnovotny @SergeyKanzhelev @yurishkuro @lizthegrey @ccaraman @mtwo @tedsuo

**Comment by yurishkuro** [comment]
`auto-instr-dotnet` would not be a name that follows the patterns. I see that even for Java auto-instr is gone, it's all in `opentelemetry-java-instrumentation`

**Comment by pjanotti** [comment]
`opentelemetry-dotnet-instrumentation` is good

**Comment by yurishkuro** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

**Comment by yurishkuro** [comment]
same permissions as otel-dotnet repo. Need to ensure EasyCLA runs for it, didn't for https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1

**Comment by pjanotti** [comment]
Thanks @yurishkuro!

**Comment by SergeyKanzhelev** [comment]
this seems to be done now
