### ISSUE TITLE
Reduce length of Rust SIG call to 30 minutes

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/community#326]
Please could the length of the Rust SIG be reduced to 30 minutes. I do not have access to edit the OpenTelemetry calendar.

The SIG calls are currently set alternate between 7:30am and 3:00pm on Tuesdays and are 60 minutes each.

@jtescher

**Comment by bogdandrutu** [comment]
@mtwo can you help with this?

**Comment by SergeyKanzhelev** [comment]
Done.
