### ISSUE TITLE
REQUEST: New membership for @dmitryax

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/community#327]
### GitHub Username

@dmitryax

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored:
  - https://github.com/open-telemetry/opentelemetry-collector/pull/614
  - https://github.com/open-telemetry/opentelemetry-collector/pull/633
  - https://github.com/open-telemetry/opentelemetry-collector/pull/648
  - https://github.com/open-telemetry/opentelemetry-collector/pull/651
  - https://github.com/open-telemetry/opentelemetry-collector/pull/667
  - https://github.com/open-telemetry/opentelemetry-collector/pull/687
  - https://github.com/open-telemetry/opentelemetry-collector/pull/694
  - https://github.com/open-telemetry/opentelemetry-collector/pull/717
  - https://github.com/open-telemetry/opentelemetry-collector/pull/742
  - https://github.com/open-telemetry/opentelemetry-collector/pull/763
  - https://github.com/open-telemetry/opentelemetry-collector/pull/793
  - https://github.com/open-telemetry/opentelemetry-collector/pull/803
  - https://github.com/open-telemetry/opentelemetry-collector/pull/767
  - https://github.com/open-telemetry/opentelemetry-collector/pull/714
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/165

- SIG projects I am involved with:
  - https://github.com/open-telemetry/opentelemetry-collector

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @dmitryax
