### ISSUE TITLE
Create Metrics SIG CODEOWNERS in OTEPs and Spec repos

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/community#329]
The Metrics SIG has several members who I would like to make into approvers for metrics-related specifications. Since we now have a subdirectory in the Spec repo, specification/metrics, we can create CODEOWNERS there to list metrics approvers.

I would nominate these approvers for metrics: 
@bogdandrutu 
@jmacd
@c24t 
@MrAlias
@jkwatson 
@rghetia 
@lzchen 
@cijothomas 

The same is needed in the OTEPs repo, but we don't have subdirectories there. I think we could probably divide the OTEPs text directory into sub-directories for this purpose, but maybe we should just add approvers for the OTEPs directory. Most of the above people are obviously qualified to approve non-metrics issues.

**Comment by yurishkuro** [comment]
+1

**Comment by carlosalberto** [comment]
TC decided to go ahead with this and this specific list of approvers (usually the TC would nominate them, btw). One question is whether this sub-spec-sig will have both approvers _and_ maintainers.

**Comment by jmacd** [comment]
How do we move this forward? I think we do not need both maintainers and approvers at this point, mainly because there's already overlap with existing maintainers in the above approvers list (Bogdan is in both groups).

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/community/blob/master/community-membership.md#approver

_Reviewer for or author of at least 10 substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls)._

The official requirement calls of at least 10 PRs in the repo. I don't meet this criteria, so my name can be removed from the list. 

Will continue review metric specs as a regular member :)

**Comment by jmacd** [comment]
I understand @cijothomas, but if 10 substantial PRs in the OTel specification or OTEPs on metrics were a requirement, very few would quality. This list is a group of people that have shown ongoing interest, have written code, and have participated in the SIG discussion in an ongoing basis. I continue to recommend you. :-)

**Comment by jmacd** [comment]
This is unfinished, and it's causing problems. We now have metrics approvers in the Spec repo, but not OTEPs. There are 5 OTEPs that should merge about metrics and I believe we have all the right approvers.
