### ISSUE TITLE
Create a repo for JS instrumentations

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#331]
The JS SIG has decided we would like to keep instrumentations in a separate repository, so we are requesting that one should be created for us with the same ownership/maintainers as the `opentelemetry-js` repo. Thank you.

**Comment by carlosalberto** [comment]
@dyladan What name do you want for it? We have, for other SIGs, names such as `opentelemetry-auto-instr-java` (but that that is the auto-instrumentation engine + instrumentation).

**Comment by mayurkale22** [comment]
We would prefer something like this: `opentelemetry-js-contrib`

**Comment by yurishkuro** [comment]
https://github.com/open-telemetry/opentelemetry-js-contrib, @dyladan is an admin, please set up the rest of the permissions as needed.
