### ISSUE TITLE
REQUEST: New membership for johnbley

### ISSUE THREAD

**Issue by johnbley** [open-telemetry/community#334]
### GitHub Username

@johnbley

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- 8 PRs merged to open-telemetry/opentelemetry-auto-instr-java, ranging from code nits to flaky test fixes to minor features to improved tooling
- 1 PR merged to open-telemetry/opentelemetry-java, fixing an issue identified while performing tests with the auto agent.
- Semi-regular participation in the auto-instr-java SIG meetings (dependent on schedule)

I recently started work at Splunk and contributions to the open-telemetry ecosystem are part of my job.  Official membership will be helpful for me as my involvement grows.

Thank you!

**Comment by trask** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
Welcome, @johnbley!
