### ISSUE TITLE
REQUEST: New membership for andrewhsu

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/community#335]
### GitHub Username

@andrewhsu

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd https://github.com/open-telemetry/opentelemetry-go/blob/43db6ec76f363192eddd75bdca8fce75a3ad286f/CODEOWNERS#L15
- @trask https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/ef61b8047f6d45dc3f3ececffec7d4257fb3719d/CODEOWNERS#L15

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/330
- https://github.com/open-telemetry/opentelemetry-go/pull/635
- SIG projects I am involved with
  - Specification SIG, see [meeting notes](https://docs.google.com/document/d/1-bCYkN-DWJq4jw1ybaDZYYmx-WAe6HnwfWbkm8d57v8/edit)
  - Java Auto-Instrumentation SIG, see [meeting notes](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw/edit)
  - Java SIG, see [meeting notes](https://docs.google.com/document/d/1oHpisisco8J7Yk73ovx3eeXaokSMqgVuEuWNwPOajtY/edit)
  - Golang SIG, see [meeting notes](https://docs.google.com/document/d/1A63zSWX0x2CyCK_LoNhmQC4rqhLpYXJzXbEPDUQ2n6w/edit#)
  - Javascript SIG, see [meeting notes](https://docs.google.com/document/d/1S_pN7sBU7wO6cBP2hDSAt3bjSWdWdm6jWeUikC9KrcY/edit)

**Comment by trask** [comment]
👍

**Comment by mtwo** [comment]
I approve

**Comment by jmacd** [comment]
Approve!

**Comment by SergeyKanzhelev** [comment]
Welcome, @andrewhsu
