### ISSUE TITLE
REQUEST: New membership for @evantorrie

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/community#337]
### GitHub Username

@evantorrie

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @MrAlias 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

https://github.com/open-telemetry/opentelemetry-go/pull/352
https://github.com/open-telemetry/opentelemetry-go/pull/546
https://github.com/open-telemetry/opentelemetry-go/pull/557
https://github.com/open-telemetry/opentelemetry-go/pull/569
https://github.com/open-telemetry/opentelemetry-go/pull/610
https://github.com/open-telemetry/opentelemetry-go/pull/667

- Issues responded to

https://github.com/open-telemetry/opentelemetry-go/issues/625
https://github.com/open-telemetry/opentelemetry-go/issues/657

- SIG projects I am involved with
   - Golang

**Comment by SergeyKanzhelev** [comment]
Welcome, @evantorrie!

**Comment by jmacd** [comment]
:+1: :tada:
