### ISSUE TITLE
REQUEST: New membership for CodeBlanch

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/community#338]
### GitHub Username

@CodeBlanch

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas 
- @bruno-garcia 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+author%3ACodeBlanch+is%3Aclosed
- Issues responded to: https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+involves%3ACodeBlanch
- SIG projects I am involved with: dotnet

**Comment by cijothomas** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @CodeBlanch

**Comment by bruno-garcia** [comment]
Welcome!
