### ISSUE TITLE
REQUEST: Opentelemetry node maintainer for justindsmith

### ISSUE THREAD

**Issue by flands** [open-telemetry/community#34]
### GitHub Username

@justindsmith

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu
- @pjanotti

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored:https://github.com/census-instrumentation/opencensus-node/pulls?q=is%3Apr+is%3Aclosed+author%3Ajustindsmith
- Issues responded to: https://github.com/census-instrumentation/opencensus-node/pulls?utf8=%E2%9C%93&q=mentions%3Ajustindsmith+
- SIG projects I am involved with: open-telemetry node

**Comment by flands** [comment]
@SergeyKanzhelev -- @justindsmith is out currently, but he is one of the current maintainers of opencensus-node. Let me know if any questions.

**Comment by SergeyKanzhelev** [comment]
Happy to invite to Open Telemetry.

Please advice on Justin's company affiliation for initial maintainers list.

**Comment by flands** [comment]
@SergeyKanzhelev he is at Omnition

**Comment by SergeyKanzhelev** [comment]
Great! Perhaps you can proxy confirm his readiness in #35 to be a maintainer if he is oof now.

**Comment by flands** [comment]
Done!
