### ISSUE TITLE
New contrib repository for .NET

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/community#340]
The .NET repository currently includes exporter code that should not be owned by the OpenTelemetry team. We're trying to find alternative homes for the current set of exporters with owning organisations the preferred destination but not all code was contributed by the organisation so will need somewhere else.

Other languages have a `opentelemetry-{lang}-contrib` repository for non-core code.

**Comment by yurishkuro** [comment]
Created https://github.com/open-telemetry/opentelemetry-dotnet-contrib/ with you as admin, please finish the setup as needed.
