### ISSUE TITLE
REQUEST: New membership for james-bebbington

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/community#342]
### GitHub Username

@james-bebbington 

### Organization you are requesting membership in

@open-telemetry 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @rghetia 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: [PRs](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Ajames-bebbington)
- Issues responded to: [Issues](https://github.com/open-telemetry/opentelemetry-collector/issues?q=is%3Aissue+author%3Ajames-bebbington) + https://github.com/open-telemetry/opentelemetry-collector/issues/802
- SIG projects I am involved with: [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector)

**Comment by bogdandrutu** [comment]
Invite sent.
