### ISSUE TITLE
REQUEST: New membership for iNikem

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/community#344]
### GitHub Username

@iNikem

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @tylerbenson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: [opentelemetry-auto-instr-java](https://github.com/open-telemetry/opentelemetry-auto-instr-java/pulls?q=is%3Apr+author%3AiNikem)
- Issues responded to: [opentelemetry-auto-instr-java](https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues?q=is%3Aissue+author%3AiNikem)
- SIG projects I am involved with: Java Auto-Instrumentation, Java SDK

**Comment by trask** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
Welcome, @iNikem!

**Comment by tylerbenson** [comment]
Delayed 👍
