### ISSUE TITLE
REQUEST: New membership for tensorchen

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/community#346]
### GitHub Username

@tensorchen

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias 
- @jmacd 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - open-telemetry/opentelemetry-go#706
  - open-telemetry/opentelemetry-go#700
  - open-telemetry/opentelemetry-go#696
  - open-telemetry/opentelemetry-go#692
  - open-telemetry/opentelemetry-go#681
  - open-telemetry/opentelemetry-go#653
- Issues responded to
  - open-telemetry/opentelemetry-go#704
  - open-telemetry/opentelemetry-go#703
  - open-telemetry/opentelemetry-go#693
  - open-telemetry/opentelemetry-go#673
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-go

**Comment by jmacd** [comment]
I support this request! Thank you @tensorchen for your contributions.

**Comment by SergeyKanzhelev** [comment]
Welcome, @tensorchen!
