### ISSUE TITLE
OpenTelemetry Google Slides template

### ISSUE THREAD

**Issue by flands** [open-telemetry/community#347]
Hey everyone -- I put together an OpenTelemetry Google Slides template and thought it might be good to make it be available to others: https://docs.google.com/presentation/d/1Neab3OZ3c-m5kOE37iZXEVpK4Pjj6xGTJEUuUzLQJvk/edit?usp=sharing.

Questions:
* Does it make sense to offer something like this?
* If so, where should it live? Here or https://github.com/cncf/artwork/tree/master/projects/opentelemetry?
* Any feedback on the template?

**Comment by SergeyKanzhelev** [comment]
Great idea! Thank you for sharing. I'm not in position to give recommendations on design (but I will do anyway). Maybe @alexcontini and @caniszczyk can help?

Ideally we need it next to all other artwork at https://github.com/cncf/artwork/tree/master/projects/opentelemetry

Again, I'm not a design expert. I think slides even in current form are quite usable. Feedback:

>I think neither accent color work great as fillers for the entire slide. One is too bright, other is not dark enough. Or maybe they needs to be used in combination - yellow letters on blue background. Also white logo on yellow background is hard to see. 
>
>What I like is how the telescope placed in the corner without the border around it "observing" the content of the slide. Maybe even shift the big titles to highlight this effect.

**Comment by SergeyKanzhelev** [comment]
@caniszczyk can you advice on where to place this template?

**Comment by caniszczyk** [comment]
@SergeyKanzhelev I'd probably just put it in this repo via a link for the gslides and a ppt file
