### ISSUE TITLE
REQUEST: New membership for jrcamp

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/community#349]
### GitHub Username

@jrcamp

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @rghetia 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/145
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/173
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/185
https://github.com/open-telemetry/opentelemetry-collector/pull/858
https://github.com/open-telemetry/opentelemetry-collector/pull/889

- Issues responded to
https://github.com/open-telemetry/opentelemetry-collector/issues/933
https://github.com/open-telemetry/opentelemetry-collector/issues/934

- SIG projects I am involved with
Collector

**Comment by mtwo** [comment]
I support this as well

________________________________

**Comment by bogdandrutu** [comment]
Welcome to the community @jrcamp
