### ISSUE TITLE
Request for a repo-specific triage role

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#350]
Hi all!

It would be helpful if we could have a triage role for PM folks in the Java Auto-Instrumentation project so that they can contribute more effectively.

I think this is a different request from #206, which was a request for an org-wide triage role.

Thanks,
Trask

**Comment by SergeyKanzhelev** [comment]
it is already covered here: https://github.com/open-telemetry/community/blob/master/community-membership.md#approver

>Some approvers may only be doing issues triage and have no approval rights.

We just introduced triager in dotnet repo

**Comment by SergeyKanzhelev** [comment]
let me know if you need help setting it up

**Comment by trask** [comment]
Is this still a requirement for approvers who are only doing issue triage?

> Reviewer for or author of at least 10 substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls).

**Comment by SergeyKanzhelev** [comment]
it's a good idea to improve the language there. Not for triagers I think. It's mostly for maintainers to decide.

**Comment by tedsuo** [comment]
@SergeyKanzhelev is it currently possible for maintainers to give access using the Triager Github role, specifically? No need to have privilege escalation if it is not necessary.

**Comment by SergeyKanzhelev** [comment]
With the current repositories set up (https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md) the way to do it is to add a person as approver, but do not add to CODEOWNERS

**Comment by mtwo** [comment]
Update: @bogdandrutu will create a triage role for each repository after @tedsuo defines criteria for this role

**Comment by tedsuo** [comment]
PR is here: https://github.com/open-telemetry/community/pull/357
