### ISSUE TITLE
Populate assets file

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#353]
As we started documenting assets, creating issue to track some assets off the top of my head:

- [x] Calendar: @mtwo ?
- [ ] DockerHub @tigrannajaryan, @bogdandrutu ?
- [x] cncf-opentelemetry-ruby@lists.cncf.io @fbogsany @mwear 
- [x] JS - npm? @open-telemetry/javascript-maintainers ?
- [ ] Java? @open-telemetry/java-maintainers ?
- [ ] Python? @open-telemetry/python-maintainers ?
- [x] CircleCI? @trask @bogdandrutu ?
- [ ] twitter account
- [ ] medium organization
- [ ] netlify (used to deploy the website opentelemetry.io)

The main idea is to ensure we have knowledge who to ask for permissions or report issues to. Also make sure CNCF has ownership.

**Comment by bogdandrutu** [comment]
> CircleCI -> github org owners are owners in CircleCI so it is based on the permissions in github.

**Comment by SergeyKanzhelev** [comment]
>> CircleCI
>Github org owners are owners in CircleCI so it is based on the permissions in github.

When I was looking at helping @trask to establish a paid account, I didn't have permissions. Maybe I missed something. One thing we may need to mention in assets file is that MS is paying for the account and all related questions can be directed to @trask.

**Comment by dyladan** [comment]
> JS - NPM

All packages are published under the `@opentelemetry` org. There are currently 41 packages, however some small handful of them are deprecated. Would say 35+ active.

@mayurkale22 is the "owner", I am an "admin" and @bogdandrutu is a "member" of the org. Not sure what permission each membership level is granted.

Unfortunately, there is no good way to list all of the packages in an organization without membership. @bogdandrutu should be able to see it in organization settings, and the list of dependents on the [SDK core](https://www.npmjs.com/package/@opentelemetry/core) does a reasonable job of showing all of them.

**Comment by SergeyKanzhelev** [comment]
Can you simply mention opentelemetry org and it's admins in asset file then? So everybody knows who to ask if something needed there.

**Comment by svrnm** [comment]
assets.md is populated with most elements listed here and more. Anything missing should be in a dedicated issue.
