### ISSUE TITLE
REQUEST: New membership for asuresh4

### ISSUE THREAD

**Issue by asuresh4** [open-telemetry/community#358]
### GitHub Username

@asuresh4

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @tigrannajaryan 

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/175
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/184
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/201
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/214
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/221
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/231
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/232
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/247

https://github.com/open-telemetry/opentelemetry-collector/pull/1003
https://github.com/open-telemetry/opentelemetry-collector/pull/1004

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @asuresh4!
