### ISSUE TITLE
REQUEST: New membership for <beniamin>

### ISSUE THREAD

**Issue by beniamin** [open-telemetry/community#360]
### GitHub Username

@beniamin

### Organization you are requesting membership in

@opent-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bobstrecansky 
- @morrisonlevi

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-php/pull/72
https://github.com/open-telemetry/opentelemetry-php/pull/64
https://github.com/open-telemetry/opentelemetry-php/pull/71
https://github.com/open-telemetry/opentelemetry-php/pull/76
https://github.com/open-telemetry/opentelemetry-php/pull/77
https://github.com/open-telemetry/opentelemetry-php/pull/79
https://github.com/open-telemetry/opentelemetry-php/pull/84
https://github.com/open-telemetry/opentelemetry-php/pull/94
https://github.com/open-telemetry/opentelemetry-php/pull/95

- Issues responded to
https://github.com/open-telemetry/opentelemetry-php/issues/67
https://github.com/open-telemetry/opentelemetry-php/issues/69

- SIG projects I am involved with
PHP SIG

**Comment by morrisonlevi** [comment]
:thumbsup:

**Comment by bobstrecansky** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
welcome, @beniamin
