### ISSUE TITLE
Please reevaluate Gitter

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#362]
Can we please reconsider Slack for community discussion?  Gitter is so buggy and really frustrating to use.  I know there is a lot of previous debate on this subject, but Gitter has if anything gotten worse since we last evaluated it.

**Comment by bhs** [comment]
I hear you...

Snippet from https://github.com/open-telemetry/community/issues/53#issuecomment-512092906 👍 

>We can reevaluate this decision if either (a) Slack changes their pricing model to allow for unlimited (or at least "very cheap") read-only users, or (b) *it's 2020*. (I.e., we are going to commit to this decision for the rest of the year but can reevaluate next year)

(Emphasis added)

So... yeah, it can be reevaluated. The concerns last time were basically around transparency and accessibility of OTel conversations, so if we move to Slack, we should be prepared to explain to ourselves "what changed" on that front.

BTW, I am personally "+1 for Slack" but that's not really the point. :)

**Comment by SergeyKanzhelev** [comment]
another option is to minimize the need for gitter conversations and threads and move most of it to github discussions or similar forum. I'd much prefer low traffic chat and async discussions

**Comment by bhs** [comment]
@tylerbenson and anyone else watching this thread – we talked about this at the governance committee meeting yesterday and came up with the following:

We *will* be switching to the CNCF Slack instance, **BUT...**
* We do not want to disrupt comms as we move (hopefully quickly!) towards OTel GA. So, for that reason, we will move to (CNCF) Slack only **after** OTel has reached GA.
* The historical concern with Slack is that it's difficult to link to as "a system of record" for discussions. As we've had more time working on the project, we don't want to make *any* real-time comms platform the place where big decisions are made – so, concurrent with the move to Slack – we will document (and lightly enforce/encourage) that the OTel community only use real-time comms for real-time tactical collaboration, and *not* as a place to have substantive, strategic conversations. Those should all happen in places that are globally visible, linkable, and better-suited to async communications, and we will all have to hold each other accountable to this.
* PS: the rationale behind "CNCF Slack" is simply that they have an unlimited usage agreement with Slack (OTel will not be able to negotiate that ourselves). CNCF is comfortable creating an effectively unlimited number of `#otel-*` channels, so each SIG can have their own place for tactical, real-time comms.

**Comment by toumorokoshi** [comment]
Just another datapoint: https://discord.com/ has personally been great for the OSS communities I participate in there:

1. easy for the public to join
2. easy to manage multiple communities for an end-user
3. good thread / code support

But CNCF slack makes sense, although I'm curious how they solve the public aspect.

**Comment by bhs** [comment]
@toumorokoshi DIscord has come up from time to time. I have non-religious feelings about all of this, but I think the basic argument has simply been that "more of the OTel community already has a Slack client running on their desktop."

**Comment by tylerbenson** [comment]
@bhs Thanks for the update.  I think it's very reasonable to encourage meaningful discussions/decisions to be made outside of slack.  I'm a little sad that we'll have to wait until after "GA" since that seems to be a bit of a moving target.  I wish it was instead that individual SIGs could start moving over as they're ready. Can we start creating channels there?

**Comment by bhs** [comment]
@tylerbenson let's make "GA" less of a moving target, then???

**Comment by anuraaga** [comment]
I found this thread when realizing myself not being able to keep up with communication as a maintainer of a SIG on Gitter, because frankly the tooling isn't great. I'd like to ask, why is GA a target for this? If there are better tools for communication, they could probably be considered even pre-GA to get communication rolling ASAP. If not, there doesn't seem to be a reason to think about it post-GA, communication is something not tied to releases IMO. Since SIGS operate relatively independently already (meeting notes / zoom rooms are different URLs), does this need to be consistent? I have already noticed a divide in the Java "SIG" of old-timers insisting on Gitter and everyone else having a backchannel on Slack - this is a sign of unhealth that IMO invalidates theory of sticking to one tool.

If we can go ahead and unlock Slack now, if not as a consistent effort, but as a means for SIGs to enable their communication channels going forward, both pre and post GA, that would be great.

**Comment by nilebox** [comment]
Not sure if that affects the re-evaluation, but Gitter has been acquired by Element: https://techcrunch.com/2020/09/30/element-acquires-gitter-to-get-more-developers-on-board-with-the-open-matrix-messaging-protocol/

**Comment by bhs** [comment]
@anuraaga sorry for my delay on this thread.

Long story short, this topic has been debated at great length in multiple forums over the past year. I don't think that Slack or Gitter is needed to get the project to GA, and primarily in the interests of sticking to past commitments, I would prefer that we make a/the move after GA.

**Comment by bogdandrutu** [comment]
@bhs here it is https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.0.0

**Comment by dyladan** [comment]
> @bhs here it is [open-telemetry/opentelemetry-specification@`v1.0.0` (release)](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.0.0)

Does this have to do with gitter? Think you may have commented on the wrong issue :)

**Comment by jkwatson** [comment]
> > @bhs here it is [open-telemetry/opentelemetry-specification@`v1.0.0` (release)](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.0.0)
> 
> Does this have to do with gitter? Think you may have commented on the wrong issue :)

It does! Our reward for 1.0 is supposed to be getting off of gitter!

**Comment by bogdandrutu** [comment]
@dyladan see previous comment from @bhs, I was responding to that :)

**Comment by bhs** [comment]
@bogdandrutu we only did all of this work to get rid of Gitter??! :)

jkjk. Point taken.

Only question in my mind is whether we want to move to CNCF Slack *or* move to GitHub Discussions (since so much of OTel is on GH Discussions at this point). (Or both??)

Thoughts?

**Comment by jkwatson** [comment]
I like having the option of a "real time" chat as well as GH discussions, and CNCF slack would work great for that.

**Comment by bogdandrutu** [comment]
@bhs to finish Metrics what is our reward :) this is how we roll :)

**Comment by bhs** [comment]
@bogdandrutu if we finish Metrics, we'll give everyone a **CUSTOM OPENTELEMETRY TOTE BAG**. Just think of it:

![image](https://user-images.githubusercontent.com/2251553/107590345-c2bb2380-6bbc-11eb-8810-4a0c308fcd39.png)

Now let's get coding!

**Comment by bhs** [comment]
Just kidding. So, yes, I think we can formally move off of Gitter and onto a combination of GitHub Discussions for threaded, well, _discussions_ about specific topics, and the CNCF Slack instance for random DMs and as an entrypoint for mostly external people who want to get triaged/redirected.

I think we'll need a pretty clear "sign on the wall" in the CNCF Slack instance to send people towards GH Discussions and/or GH Issues for topics that deserve a little more specialization and/or thought.

Sound good to people? I will bring this up at the GC meeting tomorrow and then we can move forward (!!). 🚀

**Comment by bhs** [comment]
I've [posted a message](https://gitter.im/open-telemetry/community?at=602b0b067ba8124e5469c471) to the Gitter channel and created #651... I'm now going to join the CNCF otel slack channel myself and will add a "sign on the wall" about the intended purpose of that channel.

**Comment by jkwatson** [comment]
I think we can close this now, correct?
