### ISSUE TITLE
Japanese translation for OpenTelemetry docs

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/community#364]
Hi all,

First of all, I appreciate all works done here for OpenTelemetry! Now the attention to OpenTelemetry is getting larger and larger from all over the world, and it would be great we can start Japanese translation project like #154.

The background is we have conducted [2 OpenTelemetry (OpenCensus) meetups](https://opencensus.connpass.com/) while ago, which has been stalled for a year to wait for some stability in libraries, and now we'd like to resume the meetup with this translation project so that more Japanese developers can join the movement.

It would be great if we can have a space for the project under `open-telemetry` org, like `docs-ja`.

**Comment by SergeyKanzhelev** [comment]
https://github.com/open-telemetry/docs-ja/

Made you a maintainer for the repo, please let me know who else needs to be on a team.

**Comment by ymotongpoo** [comment]
Thank you @SergeyKanzhelev for quick reaction! @katzchang is another coorganizer for the repo, so could you add him to the team?

**Comment by SergeyKanzhelev** [comment]
you both are maintainers of a repository now.

**Comment by ymotongpoo** [comment]
Could you add @shirou as the coorganizer as well?

**Comment by SergeyKanzhelev** [comment]
done
