### ISSUE TITLE
REQUEST: New membership for @naseemkullah

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/community#365]
Hello 👋 😃 

### GitHub Username

@naseemkullah

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan 
- @mayurkale22 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

  - Please see [my open PRs](https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+naseemkullah+is%3Aopen)

  - And [my closed ones](https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+naseemkullah+is%3Aclosed)

- Issues responded to

  - various, here is a recent one: https://github.com/open-telemetry/opentelemetry-js/issues/1119

- SIG projects I am involved with

  - opentelemetry-js
  - opentelemetry-js-contrib

**Comment by dyladan** [comment]
👍

**Comment by dyladan** [comment]
We were in the process of making Naseem an approver on the JS repo when we realized he hadn't done this yet 😆. He has been contributing to JS for a while now.

**Comment by SergeyKanzhelev** [comment]
yes, sometimes it comes as a surprise =)

@naseemkullah, welcome!

**Comment by naseemkullah** [comment]
Thanks @SergeyKanzhelev and @dyladan!
