### ISSUE TITLE
Concerned with diversity in technical groups

### ISSUE THREAD

**Issue by jkowall** [open-telemetry/community#367]
This is a question for the governance team. I have noticed in attending the SIGs for tracing, logging, and metrics that not a single Woman has been in attendance on the calls. I believe we have an issue on the technical side with diversity. I believe we need to make a more concerted effort to be more inclusive. @tedsuo made some great comments on the call how this is uncomfortable and difficult to accomplish, but I believe we need to address it sooner than later. I would like to help, but I need to learn how we would accomplish this. Thank you.

**Comment by bhs** [comment]
Thanks for raising this, @jkowall – and I agree completely that (a) this is a big problem, and (b) that we should take real action as a project to improve the status quo.

I've added it to the OTel gov committee agenda for a scheduled meeting we have on Thursday. One of us will report back about AIs/etc after that call.

**Comment by jkowall** [comment]
@bhs if you'd like me to join let me know. I'm happy to assist in trying to correct it. I also would like more participation in the broader community from Women. Thanks, Ben.

**Comment by bhs** [comment]
The meeting on Thursday is a recurring GC-internal thing with an agenda that includes a variety of other unrelated items.

_Unfortunately_, though, there is a 0% chance we'll be able to actually resolve OTel diversity and inclusion at the GC meeting... so I'm confident there will be some follow-on activities that will be, well, _inclusive_ (and open to the whole community). Hope that works.

**Comment by bhs** [comment]
@jkowall are you ok with me closing this issue and moving the discussion to #370 and #371 (which are slightly more targeted)?
