### ISSUE TITLE
REQUEST: New membership for @aabmass

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/community#368]
### GitHub Username

@aabmass

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @c24t 
- @toumorokoshi 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  * https://github.com/open-telemetry/opentelemetry-python/pull/749
  * https://github.com/open-telemetry/opentelemetry-python/pull/751
  * https://github.com/open-telemetry/opentelemetry-python/pull/769
  * https://github.com/open-telemetry/opentelemetry-python/pull/739
  * https://github.com/open-telemetry/opentelemetry-python/pull/764
- Issues responded to
  * https://github.com/open-telemetry/opentelemetry-python/issues/313
  * https://github.com/open-telemetry/opentelemetry-python/issues/768
  * https://github.com/open-telemetry/opentelemetry-python/issues/773
  * https://github.com/open-telemetry/opentelemetry-python/pull/775
- SIG projects I am involved with
  * Python
  * Metrics

**Comment by toumorokoshi** [comment]
I sponsor. Thanks!

**Comment by SergeyKanzhelev** [comment]
Welcome, @aabmass!
