### ISSUE TITLE
REQUEST: New membership for @cnnradams

### ISSUE THREAD

**Issue by cnnradams** [open-telemetry/community#369]
### GitHub Username

@cnnradams

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @c24t 
- @toumorokoshi 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

[open-telemetry/opentelemetry-python#694](https://github.com/open-telemetry/opentelemetry-python/issues/694)
[open-telemetry/opentelemetry-python#719](https://github.com/open-telemetry/opentelemetry-python/issues/719)
[open-telemetry/opentelemetry-python#741](https://github.com/open-telemetry/opentelemetry-python/issues/741)
[open-telemetry/opentelemetry-python#776](https://github.com/open-telemetry/opentelemetry-python/issues/776)
[open-telemetry/oteps#113](https://github.com/open-telemetry/oteps/issues/113)

- Issues responded to

various, eg [open-telemetry/opentelemetry-python#633](https://github.com/open-telemetry/opentelemetry-python/issues/633)
created: [open-telemetry/opentelemetry-python#779](https://github.com/open-telemetry/opentelemetry-python/issues/779)

- SIG projects I am involved with

opentelemetry-python

**Comment by toumorokoshi** [comment]
I sponsor. Thanks Connor!

**Comment by SergeyKanzhelev** [comment]
welcome, @cnnradams!
