### ISSUE TITLE
REQUEST: New membership for @AndrewAXue

### ISSUE THREAD

**Issue by AndrewAXue** [open-telemetry/community#372]
### GitHub Username

@AndrewAXue

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lzchen
- @c24t

### List of contributions to the OpenTelemetry project

PRs Closed:
https://github.com/open-telemetry/opentelemetry-python/pull/714. Remove default mutable attributues
https://github.com/open-telemetry/opentelemetry-python/pull/698. Add Cloud Trace Exporter.
https://github.com/open-telemetry/opentelemetry-python/pull/678. Add verification for span attributes.

PRs Open:
https://github.com/open-telemetry/opentelemetry-python/pull/739 Cloud Monitoring Exporter

SIG projects I am involved with
opentelemetry-python

**Comment by lzchen** [comment]
I sponsor this hard-working man.

**Comment by SergeyKanzhelev** [comment]
welcome, @AndrewAXue!
