### ISSUE TITLE
REQUEST: New membership for @pyohannes

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/community#376]
### GitHub Username

@pyohannes

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@reyang 
@maxgolov

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[Use lowercase base 16 representation of ids](https://github.com/open-telemetry/opentelemetry-cpp/pull/88)
[Add function to fill a buffer with random bytes](https://github.com/open-telemetry/opentelemetry-cpp/pull/87)
[Fix memory leak](https://github.com/open-telemetry/opentelemetry-cpp/pull/71)
[Clarify ABI requirements for the SDK vendor hooks](https://github.com/open-telemetry/opentelemetry-cpp/pull/70)
[Plug the SpanProcessor into the Tracer implementation](https://github.com/open-telemetry/opentelemetry-cpp/pull/65)
[Use newest available Go version in CI container](https://github.com/open-telemetry/opentelemetry-cpp/pull/56)
[Add interfaces for exporter, processor and span data](https://github.com/open-telemetry/opentelemetry-cpp/pull/55)
[Add CMake tests from a test list](https://github.com/open-telemetry/opentelemetry-cpp/pull/48)
[Add a type-erased shared pointer](https://github.com/open-telemetry/opentelemetry-cpp/pull/47)

- SIG projects I am involved with
opentelemetry-cpp

**Comment by reyang** [comment]
Welcome @pyohannes!

**Comment by SergeyKanzhelev** [comment]
Welcome, @pyohannes!
