### ISSUE TITLE
REQUEST: New membership for majorgreys

### ISSUE THREAD

**Issue by majorgreys** [open-telemetry/community#378]
### GitHub Username

@majorgreys

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @codeboten
- @toumorokoshi 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-python/pull/572
  - https://github.com/open-telemetry/opentelemetry-python/pull/643
  - https://github.com/open-telemetry/opentelemetry-python/pull/705
  - https://github.com/open-telemetry/opentelemetry-python/pull/716
  - https://github.com/open-telemetry/opentelemetry-python/pull/723
  - https://github.com/open-telemetry/opentelemetry-python/pull/740
  - https://github.com/open-telemetry/opentelemetry-python/pull/780
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-python/issues/663
  - https://github.com/open-telemetry/opentelemetry-python/issues/691
  - https://github.com/open-telemetry/opentelemetry-python/issues/710
  - https://github.com/open-telemetry/opentelemetry-python/issues/720
- SIG projects I am involved with
  - open-telemetry/opentelemetry-python

**Comment by toumorokoshi** [comment]
Sponsored +1! @majorgreys has been a huge help during his short time with the project.

**Comment by codeboten** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @majorgreys!
