### ISSUE TITLE
Disable old linuxfoundation CLA

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#379]
Tracking issue for completion of the EasyCLA migration (to be completed on June 18)

- [x] [open-telemetry/community](https://github.com/open-telemetry/community/settings/branches)
- [x] [open-telemetry/docs-cn](https://github.com/open-telemetry/docs-cn/settings/branches)
- [x] [open-telemetry/docs-ja](https://github.com/open-telemetry/docs-ja/settings/branches)
- [x] [open-telemetry/opentelemetry-auto-instr-ruby](https://github.com/open-telemetry/opentelemetry-auto-instr-ruby/settings/branches) - was empty, deleted
- [x] [open-telemetry/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/settings/branches)
- [x] [open-telemetry/opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/settings/branches)
- [x] [open-telemetry/opentelemetry-cpp](https://github.com/open-telemetry/opentelemetry-cpp/settings/branches)
- [x] [open-telemetry/opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet/settings/branches)
- [x] [open-telemetry/opentelemetry-dotnet-contrib](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/settings/branches)
- [x] [open-telemetry/opentelemetry-erlang](https://github.com/open-telemetry/opentelemetry-erlang/settings/branches)
- [x] [open-telemetry/opentelemetry-erlang-api](https://github.com/open-telemetry/opentelemetry-erlang-api/settings/branches)
- [x] [open-telemetry/opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go/settings/branches)
- [x] [open-telemetry/opentelemetry-go-contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/settings/branches)
- [x] [open-telemetry/opentelemetry-go-vanityurls](https://github.com/open-telemetry/opentelemetry-go-vanityurls/settings/branches)
- [x] [open-telemetry/opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java/settings/branches)
- [x] [open-telemetry/opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/settings/branches)
- [x] [open-telemetry/opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/settings/branches)
- [x] [open-telemetry/opentelemetry-js-contrib](https://github.com/open-telemetry/opentelemetry-js-contrib/settings/branches)
- [x] [open-telemetry/opentelemetry-operator](https://github.com/open-telemetry/opentelemetry-operator/settings/branches)
- [x] [open-telemetry/opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php/settings/branches)
- [x] [open-telemetry/opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto/settings/branches)
- [x] [open-telemetry/opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python/settings/branches)
- [x] [open-telemetry/opentelemetry-python-contrib](https://github.com/open-telemetry/opentelemetry-python-contrib/settings/branches)
- [x] [open-telemetry/opentelemetry-ruby](https://github.com/open-telemetry/opentelemetry-ruby/settings/branches)
- [x] [open-telemetry/opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust/settings/branches)
- [x] [open-telemetry/opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/settings/branches)
- [x] [open-telemetry/opentelemetry-swift](https://github.com/open-telemetry/opentelemetry-swift/settings/branches)
- [x] [open-telemetry/opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io/settings/branches)
- [x] [open-telemetry/oteps](https://github.com/open-telemetry/oteps/settings/branches)

**Comment by flands** [comment]
Can we please hold off on this for at least another week? At least Splunk and Grafana Labs are impacted by the new CLA and will require time to get it formally approved.

**Comment by lizthegrey** [comment]
> Can we please hold off on this for at least another week? At least Splunk and Grafana Labs are impacted by the new CLA and will require time to get it formally approved.

Yup, just a tracking issue, will wait another 1.5 weeks.

**Comment by lizthegrey** [comment]
@flands would it help if instead of re-signing, I asked the Linux Foundation to migrate your existing CLA?

**Comment by ccaraman** [comment]
@open-telemetry/admins - We should undo the Community repository from enforcing the EasyCLA for now. 

 I think Community should be the last repository to enforce the new CLA as we have seen that there are large gaps in who got the communication around the new process. (https://github.com/open-telemetry/community/issues/309) By having it turned on here first, this blocks users in the limbo area from opening any issues in the meantime.

**Comment by lizthegrey** [comment]
> @open-telemetry/admins - We should undo the Community repository from enforcing the EasyCLA for now.
> 
> I think Community should be the last repository to enforce the new CLA as we have seen that there are large gaps in who got the communication around the new process. (#309)

I'll revert!

**Comment by yurishkuro** [comment]
> At least Splunk and Grafana Labs are impacted by the new CLA and will require time to get it formally approved.

@flands it is my understanding that the CLA itself is unchanged, it's only the mechanism for checking it. When I did a test PR, all I had to do was to confirm that I still work at Uber, I was not required to re-sign the CLA. Are you seeing something different?

**Comment by lizthegrey** [comment]
@bogdandrutu how did discussion at maintainer meeting go? Do we need another week or am I good to swap the CLAs as of Friday?

**Comment by lizthegrey** [comment]
It's now been 3 weeks, I'm going to go ahead and globally change, unless people object.

**Comment by lizthegrey** [comment]
@open-telemetry/admins I've updated all but the ones for which I have no access as a GC member.

**Comment by yurishkuro** [comment]
open-telemetry/opentelemetry-operator doesn't show EasyCLA as a check

**Comment by yurishkuro** [comment]
same with open-telemetry/opentelemetry-python-contrib - no checks

open-telemetry/opentelemetry-auto-instr-ruby has no files

**Comment by lizthegrey** [comment]
> open-telemetry/opentelemetry-operator doesn't show EasyCLA as a check

A dummy PR needs to be opened to force EasyCLA checks to run then. I'll do that.

**Comment by lizthegrey** [comment]
> open-telemetry/opentelemetry-auto-instr-ruby has no files

@open-telemetry/ruby-maintainers do you need the auto-instr repo? or can we delete it until we need it? p.s. the name is out of spec with the naming of other language auto-instr where the language comes first.

**Comment by lizthegrey** [comment]
> > open-telemetry/opentelemetry-operator doesn't show EasyCLA as a check
> 
> A dummy PR needs to be opened to force EasyCLA checks to run then. I'll do that.

@yurishkuro dummy PRs opened against otel-operator and otel-python-contrib, it should show now.

**Comment by yurishkuro** [comment]
thanks, Liz, I  enabled the checked in those two.

**Comment by lizthegrey** [comment]
Great. I think we can declare this migration done. I've submitted a ticket to Linux Foundation support to ask them to disable the old CLA bot.

**Comment by yurishkuro** [comment]
I deleted `open-telemetry/opentelemetry-auto-instr-ruby`. It was poorly set up anyway, without README or license.

**Comment by lizthegrey** [comment]
one last item, @yurishkuro: Heather from CNCF/LF says we need to:

```
Hi Liz, i got clarification from the team and all that needs to be done here is for someone with rights on the org to remove the webhook.

It will look something like this:

Payload URL:
https://identity.linuxfoundation.org/lfcla/github/postreceive?ARG1=value&ARG2=value

Content type: application/json

Secret: the Github HMAC secret to enter here is a base64-encoded hash of an LF secret, concatenated with the group ID argument value (so that each project has their own secret).
```

**Comment by yurishkuro** [comment]
Just to confirm, we want to remove this webhook:

![image](https://user-images.githubusercontent.com/3523016/86288273-a3383300-bbb7-11ea-951d-1014e3345567.png)

And I assume the EasyCLA will continue working because it's not integrated via webhook, but as a GitHub App:

![image](https://user-images.githubusercontent.com/3523016/86288341-bcd97a80-bbb7-11ea-8f97-7a951f3d9980.png)

**Comment by lizthegrey** [comment]
that is correct, the github app is how we've integrated EasyCLA so the legacy webhook can be removed.

**Comment by yurishkuro** [comment]
deleted webhook.

**Comment by lizthegrey** [comment]
Opening a test PR to verify, but we can consider this closed.
