### ISSUE TITLE
REQUEST: New membership for tylerbenson

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/community#38]
### GitHub Username

@tylerbenson

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tedsuo

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-java/pull/218#discussion_r280924660

- Issues responded to
https://github.com/open-telemetry/opentelemetry-java/issues/243

- SIG projects I am involved with
OpenTelemetry-Java
(Also heavily involved with OpenTracing)

**Comment by SergeyKanzhelev** [comment]
@tedsuo I understand you will nominate @tylerbenson. So I invited to the org proactively.

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev I would like in the future to have one maintainer of that repo at least sign for these issues. I think this is fine because if Ted proposed him probably @carlosalberto would be on the same page :+1:
