### ISSUE TITLE
REQUEST: New membership for anuraaga

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#381]
### GitHub Username

@anuraaga

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @jkwatson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to

https://github.com/pulls?q=involves%3Aanuraaga+archived%3Afalse+user%3Aopen-telemetry+

- SIG projects I am involved with

cross language specification
java sdk
agent + collector

**Comment by trask** [comment]
👍

**Comment by yurishkuro** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
welcome, @anuraaga
