### ISSUE TITLE
REQUEST: New membership for alolita

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#382]
### GitHub Username

@alolita 

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [✅ ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✅ ] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [✅ ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✅ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mtwo 
- @reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to

https://github.com/pulls?q=involves%3Aalolita+archived%3Afalse+user%3Aopen-telemetry+

- SIG projects I am involved with

Specification - https://github.com/open-telemetry/opentelemetry-specification
Collector - https://github.com/open-telemetry/opentelemetry-collector
C++ SDK - https://github.com/open-telemetry/opentelemetry-cpp

**Comment by mtwo** [comment]
I support this

________________________________

**Comment by reyang** [comment]
Welcome to the community @alolita!

**Comment by alolita** [comment]
Thanks! Excited to contribute to the project! @reyang @mtwo 🙏

**Comment by SergeyKanzhelev** [comment]
Welcome, @alolita!
