### ISSUE TITLE
REQUEST: New membership for legendecas

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/community#383]
### GitHub Username

@legendecas

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan
- @mayurkale22

### List of contributions to the OpenTelemetry project

- [PRs reviewed / authored](https://github.com/search?q=org%3Aopen-telemetry+author%3Alegendecas&type=Commits)
- [Issues responded to](https://github.com/search?q=org%3Aopen-telemetry+author%3Alegendecas&type=Issues)
- SIG projects I am involved with: https://github.com/open-telemetry/opentelemetry-js

**Comment by mayurkale22** [comment]
I support this.

**Comment by dyladan** [comment]
> I support this.

I also support this.

**Comment by SergeyKanzhelev** [comment]
Welcome, @legendecas
