### ISSUE TITLE
REQUEST: New membership for abharg

### ISSUE THREAD

**Issue by ankit-bhargava** [open-telemetry/community#384]
### GitHub Username

@ankit-bhargava

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✅] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@mtwo 
@reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

https://github.com/open-telemetry/opentelemetry-cpp/pull/94

- Issues responded to

Currently working on https://github.com/open-telemetry/opentelemetry-cpp/issues/82

- SIG projects I am involved with

C++ SDK - https://github.com/open-telemetry/opentelemetry-cpp

**Comment by mtwo** [comment]
I support this

________________________________

**Comment by reyang** [comment]
Welcome @ankit-bhargava!

**Comment by SergeyKanzhelev** [comment]
Welcome, @ankit-bhargava!
