### ISSUE TITLE
REQUEST: New membership for HudsonHumphries

### ISSUE THREAD

**Issue by HudsonHumphries** [open-telemetry/community#385]
### GitHub Username

@HudsonHumphries

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✅] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@mtwo
@reyang

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

[C++ PR 97](https://github.com/open-telemetry/opentelemetry-cpp/pull/97)

- Issues responded to

[Created C++ Issue 101](https://github.com/open-telemetry/opentelemetry-cpp/issues/101)

- SIG projects I am involved with

[C++](https://github.com/open-telemetry/opentelemetry-cpp)
[Metrics](https://docs.google.com/document/d/1LfDVyBJlIewwm3a0JtDtEjkusZjzQE3IAix8b0Fxy3Y/edit#)
[Golang](https://github.com/open-telemetry/opentelemetry-go)

**Comment by mtwo** [comment]
I support this

________________________________

**Comment by reyang** [comment]
Welcome @HudsonHumphries!

**Comment by SergeyKanzhelev** [comment]
Welcome, @HudsonHumphries!
