### ISSUE TITLE
REQUEST: New membership for Brandon-Kimberly

### ISSUE THREAD

**Issue by Brandon-Kimberly** [open-telemetry/community#386]
### GitHub Username

@Brandon-Kimberly

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mtwo 
- @reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-cpp/pull/103
https://github.com/open-telemetry/opentelemetry-cpp/pull/93
https://github.com/open-telemetry/opentelemetry-java/pull/1293

- Issues responded to

- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-cpp
https://github.com/open-telemetry/opentelemetry-java
https://github.com/open-telemetry/opentelemetry-specification

**Comment by mtwo** [comment]
I support this

________________________________

**Comment by reyang** [comment]
Welcome @Brandon-Kimberly!

**Comment by SergeyKanzhelev** [comment]
Welcome, @Brandon-Kimberly!
