### ISSUE TITLE
REQUEST: New membership for @shivkanya9146

### ISSUE THREAD

**Issue by shivkanya9146** [open-telemetry/community#387]
### GitHub Username

@shivkanya9146

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan
- @mayurkale22

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [20+ PRs so far on opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ashivkanya9146+is%3Aclosed).
  - [2 PRs so far on opentelemetry-js-contrib](https://github.com/open-telemetry/opentelemetry-js-contrib/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ashivkanya9146+is%3Aclosed) 
- [Issues responded to](https://github.com/open-telemetry/opentelemetry-js/issues?q=is%3Aissue+sort%3Aupdated-desc+shivkanya9146+is%3Aclosed)
- SIG projects I am involved with
  - opentelemetry-js
  - opentelemetry-js-contrib

**Comment by mayurkale22** [comment]
I support this.

**Comment by SergeyKanzhelev** [comment]
Welcome, @shivkanya9146!

**Comment by shivkanya9146** [comment]
I am still not the member of the community, could you please look into this.

**Comment by mtwo** [comment]
@SergeyKanzhelev FYI

**Comment by SergeyKanzhelev** [comment]
resent invite

![image](https://user-images.githubusercontent.com/9950081/86293378-5c424180-bba7-11ea-90f4-dc855560d450.png)
