### ISSUE TITLE
REQUEST: New membership for keitwb

### ISSUE THREAD

**Issue by keitwb** [open-telemetry/community#390]
### GitHub Username

@keitwb

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @flands  

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-collector/pull/1098
- https://github.com/open-telemetry/opentelemetry-collector/pull/1117
- https://github.com/open-telemetry/opentelemetry-collector/pull/1104
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/303
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/297
- I'll be primarily working on log support and experimenting with a FluentBit integration for the next few months.

**Comment by SergeyKanzhelev** [comment]
Welcome, @keitwb!
