### ISSUE TITLE
New a new role in between Member and Approver

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#397]
We currently have 3 membership levels defined: Member, Approver and Maintainer.

This worked fine while the project was small. However, now that we have a lot more people contributing I feel that there is not enough granularity available between Member and Approver.

Member works fine for occasional, infrequent contributors.

Approvers works fine for those that do the heavy lifting and we have a pretty high bar for making people Approvers.

However, recently we see a lot more contributors who contribute periodically on a daily basis but do not necessarily meet the bar or have the desire to become Approvers. These contributors actively participate in the work but are very constrained in what they can do in the repo. For example in the Collector we have about 4-5 people like this who really are doing very useful and frequent work but someone else who have more permissions (Maintainer or Approver) needs to help them to assign issues (Members can't even self-assign), add reviewers to PR or assign PRs, etc.

I think we need a role called Contributor who has more permissions that Members. I am particularly interested in allowing Contributors to assign issues and PR, change issue and PR labels and allow to change the state of issues and PR in project boards. The closest we have to this role in Github is the Triage role.

I know we had this discussion https://github.com/open-telemetry/community/issues/350 but my request is not for PMs, it is for engineers who contribute PRs but have very limited permissions today. This complicates the life of Maintainers and Approvers who have to perform this simple actions (like assigning issues) on behalf of contributors.

**Comment by arminru** [comment]
Aren't the permissions you're asking for exactly the ones defined in the [Triager role](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) which will be added to our membership levels in #357?
If only the term "Triager" is a concern because it sounds too PM-ish and not like if these people would usually contribute code, we could consider naming it differently in our own terminology. I think "Contributor", like you proposed, would be fine because it fits both for people who contribute code and also people who contribute their time to respond to and manage issues and PRs as triagers.
cc @tedsuo

**Comment by bhs** [comment]
FWIW, I agree with the spirit of @arminru's note above – we should either use the forthcoming `Triager` role to plug this gap XOR rename it to make that possible. Adding some sort of fifth role seems like evidence that one of the other four roles needs to be redefined in some way.

I am fine with calling the new role `Triager`, though it seems that an important distinction between `Member` and `Triager` (per @tigrannajaryan's framing above) is the idea of *sustained* contribution (vs the one-time or sporadic contribution of a `Member`). So I can imagine modifying #357 to use a term like `Staff` or `Staffer`. But this is a very weakly-held point of view, and I am confident that the community will adjust to any reasonable nomenclature as long as the actual privileges for each role are appropriate.

**Comment by tigrannajaryan** [comment]
I am fine if it is the same role and yes the permissions seem to be the same. I slightly prefer the name "Contributor" but I am OK with the other names.

**Comment by SergeyKanzhelev** [comment]
I think there is an important difference. If we are not writing any automation like kubernetes's prow that will allow to assign issues and add labels using comments, but instead give a full triage permission, we need to emphasize it in the role name. So it's clear that person in this role have rights to change and set milestones, assign issues to milestones, add or remove labels, etc. 

If we simply need /assign robot for any member - we need to think of building or adopting one. This is how it works in k8s:

![image](https://user-images.githubusercontent.com/9950081/85621405-1cfd7900-b61a-11ea-8280-ac470253b336.png)

**Comment by yurishkuro** [comment]
@SergeyKanzhelev do you know if we can onboard OTEL repos onto k8s robot?

**Comment by SergeyKanzhelev** [comment]
I don't know and after quick search it looks quite specific to kubernetes https://github.com/kubernetes/test-infra/tree/master/prow maybe we can borrow some code.

Also I looked github actions: https://github.com/marketplace?after=Y3Vyc29yOjIw&query=assign&type=actions there is none that do exactly what we want=(
