### ISSUE TITLE
Add Log approvers

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#399]
According to the suggestion in https://github.com/open-telemetry/opentelemetry-specification/pull/661 and based on the past active contributions to the Log SIG I am proposing @kumoroku and @zenmoto as initial Log approvers.

**Comment by tigrannajaryan** [comment]
@open-telemetry/technical-committee please have a look.

**Comment by yurishkuro** [comment]
+1

**Comment by carlosalberto** [comment]
Sounds good to me.

**Comment by SergeyKanzhelev** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan can you send PR?

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev PR created: https://github.com/open-telemetry/community/issues/399

I think one of the admins must also add  @kumoroku and @zenmoto to @specs-logs-approvers user group.
