### ISSUE TITLE
REQUEST: New membership for CunjunWang

### ISSUE THREAD

**Issue by CunjunWang** [open-telemetry/community#400]
### GitHub Username

@CunjunWang

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✅] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@mtwo 
@reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[C++ PR #144](https://github.com/open-telemetry/opentelemetry-cpp/pull/144)

- Issues responded to
[C++ Issue #109](https://github.com/open-telemetry/opentelemetry-cpp/issues/109)

- SIG projects I am involved with
[C++](https://github.com/open-telemetry/opentelemetry-cpp)
[Java](https://github.com/open-telemetry/opentelemetry-java)

**Comment by SergeyKanzhelev** [comment]
@mtwo, @reyang please approve

**Comment by mtwo** [comment]
I approve

**Comment by reyang** [comment]
Same here, approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @CunjunWang!
