### ISSUE TITLE
Set security policies

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#401]
We should have a private security@opentelemetry.io alias, GPG key, and set up SECURITY.md for all our repos.

**Comment by SergeyKanzhelev** [comment]
Do you have some links on best practices on how it will be used?

**Comment by yurishkuro** [comment]
Not claiming it's a best practice, but just as a reference to what we did in Jaeger. Website footer contains a link to report security issues

![image](https://user-images.githubusercontent.com/3523016/86297951-9e30af00-bbca-11ea-8422-b39ff9335688.png)

which takes you to https://www.jaegertracing.io/report-security-issue/

**Comment by lizthegrey** [comment]
That's correct, the goal is to enable people with critical security issues to responsibly disclose to us without going through public issue trackers, in order to allow us to remediate, push releases, and issue security advisories.

**Comment by lizthegrey** [comment]
I'll bring this up at Governance this week, but it's probably more properly a matter for the TC.

**Comment by SergeyKanzhelev** [comment]
Added to TC meeting agenda

**Comment by arminru** [comment]
Related PR by @jpkrohling: https://github.com/open-telemetry/opentelemetry-specification/pull/990

**Comment by yurishkuro** [comment]
I would also recommend each repo to add an issue template "Report a security vulnerability". 

Cf: https://github.com/jaegertracing/jaeger/issues/new/choose

**Comment by jpkrohling** [comment]
That one is actually a link to the policy, which is created automatically when you add a SECURITY.md to the repo.

**Comment by trask** [comment]
@open-telemetry/technical-committee just checking if this is still an open issue, or is resolved by https://github.com/open-telemetry/.github/pull/1? thx!

**Comment by arminru** [comment]
@trask I think this can be resolved. The one from the meta repo also shows up here at https://github.com/open-telemetry/community/security/policy.

**Comment by yurishkuro** [comment]
Related: https://github.com/open-telemetry/community/issues/1338
