### ISSUE TITLE
Replace `master` with `main` branch name systematically

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#402]

**Comment by SergeyKanzhelev** [comment]
the only question here whether we want to go ahead now or wait for github to unify the names: https://twitter.com/natfriedman/status/1271253144442253312

**Comment by lizthegrey** [comment]
Based on the number of repos we'd need to update, I think we should probably wait for GitHub if that support is coming.

**Comment by MikeGoldsmith** [comment]
I've recently been involved in doing this, and it only takes a few minutes per repo. It took my ~30 minutes to do it for 5 repos.

Steps:
1) create new `main` branch from `master`
2) update open PRs to point to `main` (can be done by editing the PR and selecting target branch)
3) update branch protection rule pattern to target `main`
4) remove `master` branch

The time consuming part is 2), depending on how many open PRs there are.

I'd happily volunteer to do the work, but it does require admin access to each repository.

**Comment by SergeyKanzhelev** [comment]
https://github.com/github/renaming

It looks we can simply wait for a little and the migration will be automated by GitHub.

**Comment by SergeyKanzhelev** [comment]
Renamed the issue to indicate the name that GitHub will be using as a default

**Comment by bobstrecansky** [comment]
We talked about this in the Maintainer's meeting today - the maintainers generally seemed like waiting until the automatic github renaming occurred later this year was sufficient.  If we decide it must happen earlier, I don't foresee a lot of resistance against that kind of initiative.

**Comment by SergeyKanzhelev** [comment]
Need to start making progress here. See: https://github.com/github/renaming#renaming-existing-branches - GitHub implemented the renaming

**Comment by bobstrecansky** [comment]
@SergeyKanzhelev - I went to do this for https://github.com/open-telemetry/opentelemetry-php/ and I didn't have permissions to see https://github.com/open-telemetry/opentelemetry-php/settings/branches - Would you either be able to grant me permissions or make this change for our repo?

**Comment by arminru** [comment]
@bobstrecansky It looks like the @open-telemetry/php-maintainers team is assigned the Maintain role for the PHP repo but one needs to be Admin to change the default branch. Most repos currently have the Admin role set but the guidelines would prescribe the Maintain role. I filed #616 to have this fixed in one or the other direction.

For now I can go ahead and rename master to main as described in Sergey's link above once you confirm you're ready for that. I think you'll still have to update at least https://github.com/open-telemetry/opentelemetry-php/blob/master/.github/workflows/php.yml manually.

**Comment by dyladan** [comment]
JS already started this process by adding `main` to our list of branch names for CI actions. I ran a quick query on the github API to get the current state:

| repo                                 | branch renamed |
|--------------------------------------|----------------|
| .github                              | yes            |
| build-tools                          |                |
| community                            |                |
| docs-cn                              |                |
| docs-ja                              |                |
| opentelemetry-collector              |                |
| opentelemetry-collector-contrib      |                |
| opentelemetry-cpp                    |                |
| opentelemetry-cpp-contrib            | yes            |
| opentelemetry-dotnet                 |                |
| opentelemetry-dotnet-contrib         |                |
| opentelemetry-dotnet-instrumentation |                |
| opentelemetry-erlang                 |                |
| opentelemetry-erlang-api             |                |
| opentelemetry-go                     |                |
| opentelemetry-go-contrib             |                |
| opentelemetry-go-vanityurls          |                |
| opentelemetry-helm-charts            |                |
| opentelemetry-java                   |                |
| opentelemetry-java-contrib           |                |
| opentelemetry-java-instrumentation   |                |
| opentelemetry-js                     |                |
| opentelemetry-js-api                 | yes            |
| opentelemetry-js-contrib             |                |
| opentelemetry-lambda-extension       | yes            |
| opentelemetry-operator               |                |
| opentelemetry-php                    |                |
| opentelemetry-proto                  |                |
| opentelemetry-proto-go               | yes            |
| opentelemetry-python                 |                |

**Comment by bobstrecansky** [comment]
> @bobstrecansky It looks like the @open-telemetry/php-maintainers team is assigned the Maintain role for the PHP repo but one needs to be Admin to change the default branch. Most repos currently have the Admin role set but the guidelines would prescribe the Maintain role. I filed #616 to have this fixed in one or the other direction.
> 
> For now I can go ahead and rename master to main as described in Sergey's link above once you confirm you're ready for that. I think you'll still have to update at least https://github.com/open-telemetry/opentelemetry-php/blob/master/.github/workflows/php.yml manually.

Yup; I'm happy to update that - feel free to rename `master` to `main` whenever you'd like, I'll make the updates accordingly after!

**Comment by SergeyKanzhelev** [comment]
@bobstrecansky renamed

**Comment by dyladan** [comment]
JS branch renamed

**Comment by dyladan** [comment]
@lizthegrey I don't want to edit your original issue without consent, but if it's ok with you I'd like to add the table in this comment https://github.com/open-telemetry/community/issues/402#issuecomment-764822398 to the issue description and keep it updated once per day. As well as the link to the renaming procedure here: https://docs.google.com/document/d/1lkA0Re3vWfqXmuYLhL93Y6ABR27Sg6DzPcwi4kPXj0Y/edit

**Comment by jkwatson** [comment]
`opentelemetry-java` default branch has been renamed

**Comment by bogdandrutu** [comment]
Updated:
* build-tools
* community
* docs-cn
* docs-ja

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/opentelemetry-log-collection repo changed to `main`.

**Comment by bogdandrutu** [comment]
Updated
* opentelemetry-java-contrib
* opentelemetry-helm-charts

**Comment by bogdandrutu** [comment]
Updated `opentelemetry-go-vanityurls`

**Comment by bogdandrutu** [comment]
Updated `oteps`

**Comment by bogdandrutu** [comment]
Updated `opentelemetry-swift`

**Comment by eddynaka** [comment]
updated `opentelemetry-dotnet` and `opentelemetry-dotnet-contrib`

cc: @cijothomas

**Comment by dyladan** [comment]
updated `opentelemetry-js` and `opentelemetry-js-contrib`. `opentelemetry-js-api` was created with `main`.

**Comment by bogdandrutu** [comment]
Updated:
* opentelemetry-collector
* opentelemetry-proto

**Comment by bogdandrutu** [comment]
Updated:

* opentelemetry-ruby (by @dazuma )
* opentelemetry-operator

**Comment by bogdandrutu** [comment]
Thanks to @codeboten 👍

* opentelemetry-python
* opentelemetry-python-contrib

**Comment by bogdandrutu** [comment]
Few more updates thanks to @pjanotti and @MrAlias 

* opentelemetry-go
* opentelemetry-dotnet-instrumentation

**Comment by bogdandrutu** [comment]
Updated:

* opentelemetry.io

**Comment by bogdandrutu** [comment]
All repos updated except `opentelemetry-erlang-api` which is archived (cannot make changes to it) and will be deleted very soon.
