### ISSUE TITLE
REQUEST: New membership for connorlindsey

### ISSUE THREAD

**Issue by connorlindsey** [open-telemetry/community#404]
### GitHub Username

@connorlindsey

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @mtwo 

### List of contributions to the OpenTelemetry project

- Active in Go and JS SIGs
- [Filed issue](https://github.com/open-telemetry/opentelemetry.io/issues/212) and working on improvements to the OTel website registry search. 
- [Filed issue](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/119) and working on Cortex exporter for the Go SDK
- [Filed issue and PR](https://github.com/open-telemetry/opentelemetry-js/pull/1270) to fix broken link in JS documentation

Thanks!

**Comment by mtwo** [comment]
I approve

**Comment by jmacd** [comment]
I approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @connorlindsey!
