### ISSUE TITLE
Update permissions for opentelemetry-dotnet-contrib

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/community#405]
We're trying to configure Github actions on the .NET contrib project but it seems both myself and @cijothomas do not have access to manage the repository as expected. Our permissions do not match those we have for opentelementry-dotnet.

Both myself (@MikeGoldsmith) and Cijo (@cijothomas) are members of the @open-telemetry/dotnet-maintainers 

Please could we review the allocated permissions to match those for the main .NET repository.

**Comment by yurishkuro** [comment]
I changed permissions from Maintain to Admin, to match opentelemetry-dotnet.

**Comment by cijothomas** [comment]
Thanks. Unblocked and running GH actions now.
