### ISSUE TITLE
REQUEST: New membership for huyan0

### ISSUE THREAD

**Issue by huyan0** [open-telemetry/community#408]
### GitHub Username

@huyan0

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)

- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang 
- @jmacd 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
open-telemetry/opentelemetry-cpp#157
open-telemetry/opentelemetry-proto#162

- Issues responded to
 open-telemetry/opentelemetry-collector#1255
 open-telemetry/opentelemetry-collector#1150

- SIG projects I am involved with
Agent/Collector
Metric

**Comment by reyang** [comment]
I support @huyan0. Thanks!

**Comment by jmacd** [comment]
I support @huyan0.

**Comment by SergeyKanzhelev** [comment]
Welcome, @huyan0!
