### ISSUE TITLE
REQUEST: New membership for rajkumar-rangaraj

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/community#409]
### GitHub Username

@rajkumar-rangaraj

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas
- @CodeBlanch

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+author%3Arajkumar-rangaraj+is%3Aclosed
- Issues responded to: https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+involves%3Arajkumar-rangaraj
- SIG projects I am involved with: dotnet

**Comment by SergeyKanzhelev** [comment]
Welcome, @rajkumar-rangaraj

**Comment by CodeBlanch** [comment]
Welcome @rajkumar-rangaraj!

**Comment by cijothomas** [comment]
Doesn't look like @rajkumar-rangaraj is added to OpenTelemetry. @SergeyKanzhelev Can you check this ?

**Comment by SergeyKanzhelev** [comment]
Invite is pending. @rajkumar-rangaraj make sure to accept invite
![image](https://user-images.githubusercontent.com/9950081/87712545-b0c7ee00-c75d-11ea-88fe-c89a892ee8d8.png)

**Comment by rajkumar-rangaraj** [comment]
@SergeyKanzhelev , I missed an earlier invitation. The link has expired, could you please resend the link? Thanks!

**Comment by SergeyKanzhelev** [comment]
try now

**Comment by rajkumar-rangaraj** [comment]
It worked. Thank you!
