### ISSUE TITLE
REQUEST: New membership for malafeev

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/community#410]
### GitHub Username

@malafeev

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @iNikem

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Apr+is%3Aclosed+author%3Amalafeev+
- Issues responded to: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Aissue+involves%3Amalafeev
- SIG projects I am involved with: opentelemetry-java-instrumentation

**Comment by SergeyKanzhelev** [comment]
Welcome, @malafeev!
