### ISSUE TITLE
REQUEST: New membership for justinfoote

### ISSUE THREAD

**Issue by justinfoote** [open-telemetry/community#412]
### GitHub Username

@justinfoote

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@jmacd 
@jkwatson

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-specification/pulls?q=is%3Aissue+involves%3Ajustinfoote
- Issues responded to: https://github.com/open-telemetry/opentelemetry-specification/issues?q=is%3Aissue+involves%3Ajustinfoote+
- SIG projects I am involved with: metrics, errors

**Comment by SergeyKanzhelev** [comment]
Welcome, @justinfoote!
