### ISSUE TITLE
REQUEST: New membership for ymotongpoo

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/community#413]
### GitHub Username

@ymotongpoo

### Organization you are requesting membership in

@open-telemetry/opentelemetry-collector-contrib

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @james-bebbington
- @SergeyKanzhelev 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-go/pull/548
  - https://github.com/open-telemetry/opentelemetry-go/pull/167
  - https://github.com/open-telemetry/opentelemetry-go/pull/160
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/393
  - https://github.com/open-telemetry/opentelemetry.io/pull/139
  - https://github.com/open-telemetry/opentelemetry.io/pull/197
  - https://github.com/open-telemetry/docs-ja/pull/45
  - https://github.com/open-telemetry/docs-ja/pull/58
  - https://github.com/open-telemetry/docs-ja/pull/57
  - https://github.com/open-telemetry/docs-ja/pull/56
  - https://github.com/open-telemetry/docs-ja/pull/55
  - https://github.com/open-telemetry/docs-ja/pull/54
  - https://github.com/open-telemetry/docs-ja/pull/52
  - https://github.com/open-telemetry/docs-ja/pull/51
  - https://github.com/open-telemetry/docs-ja/pull/50
  - https://github.com/open-telemetry/docs-ja/pull/49
  - https://github.com/open-telemetry/docs-ja/pull/44
  - https://github.com/open-telemetry/docs-ja/pull/40
  - https://github.com/open-telemetry/docs-ja/pull/39
  - https://github.com/open-telemetry/docs-ja/pull/38
  - https://github.com/open-telemetry/docs-ja/pull/37
  - https://github.com/open-telemetry/docs-ja/pull/36
  - https://github.com/open-telemetry/docs-ja/pull/34
  - https://github.com/open-telemetry/docs-ja/pull/32
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/392
  - https://github.com/open-telemetry/community/issues/364
- SIG projects I am involved with
  - not the SIG but I'm leading the docs translation project for Japanese speaking developers.
  - indirectly working with Go and Metrics SIG for [Google Cloud Operations exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go)

**Comment by SergeyKanzhelev** [comment]
Welcome, @ymotongpoo!

**Comment by ymotongpoo** [comment]
Thank you, Sergey!!!
