### ISSUE TITLE
REQUEST: New membership for erichsueh3

### ISSUE THREAD

**Issue by erichsueh3** [open-telemetry/community#414]
### GitHub Username

@erichsueh3

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mtwo 
- @reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-cpp/pull/172

- Issues responded to
https://github.com/open-telemetry/opentelemetry-cpp/issues/81
Filed https://github.com/open-telemetry/opentelemetry-cpp/issues/148
Filed https://github.com/open-telemetry/opentelemetry-cpp/issues/170

- SIG projects I am involved with
C++ - https://github.com/open-telemetry/opentelemetry-cpp

**Comment by reyang** [comment]
"I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application" I don't recall that I've spoken with @erichsueh3 about this.

**Comment by erichsueh3** [comment]
Hi @reyang, sorry for the confusion, I forgot to mention that I was working on the [prometheus exporter](https://github.com/open-telemetry/opentelemetry-cpp/issues/81) with @alolita and @CunjunWang; I've added that to the "Issues responded to" section.

**Comment by reyang** [comment]
I support @erichsueh3 to be a member of the OpenTelemetry project.

**Comment by mtwo** [comment]
I support this

**Comment by SergeyKanzhelev** [comment]
Welcome, @erichsueh3!
