### ISSUE TITLE
REQUEST: New membership for @kbrockhoff

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/community#415]
### GitHub Username 

- @kbrockhoff

### Organization you are requesting membership in 

- @open-telemetry

### Requirements

- [*] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [*] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [*] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [*] I am actively contributing to 1 or more OpenTelemetry subprojects
- [*] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [*] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @tedsuo 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- - Specification: 397 405 396 395 394 393 383
-- OTEP: 69
-- Collector: 1222 1151 1144 1143 1062 967 518 516 439 435
-- Collector Contrib: 350 234 212 205 203 108 87 84 75 41
-- Java: 736 786 784 758 752 743 738 730 679
-- Java Instrumentation: 148
- Issues responded to
 -- Specification: 605 362 
 -- Collector: 1138 1123 1121 1137 1136 1122
-- Java: 747 536 522 519 517 735 521 520 518
- SIG projects I am involved with
-- Cross-language specification
-- Agent/Collector
-- Java SDK
-- Java Instrumentation

**Comment by SergeyKanzhelev** [comment]
Welcome, @kbrockhoff!
