### ISSUE TITLE
New membership for eddynaka

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/community#416]
### GitHub Username

@eddynaka

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas 
- @CodeBlanch 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+eddynaka+is%3Aclosed
- Issues responded to: https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+involves%3Aeddynaka
- SIG projects I am involved with: dotnet

**Comment by SergeyKanzhelev** [comment]
Welcome. @eddynaka!

**Comment by eddynaka** [comment]
@SergeyKanzhelev @cijothomas  , can you re-add me? Github support cleaned all my teams/organizations...
thank you

**Comment by SergeyKanzhelev** [comment]
Invited and re-instated in the dotnet-related  team

**Comment by eddynaka** [comment]
@SergeyKanzhelev , thank you 👍
