### ISSUE TITLE
REQUEST: New membership for danielbang907

### ISSUE THREAD

**Issue by danielbang907** [open-telemetry/community#418]
### GitHub Username

@danielbang907

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mtwo 
- @reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored:
   Upcoming implementation (design document completed) for Collector Cortex Exporter: https://github.com/open-telemetry/opentelemetry-collector/issues/1150
   PRs assigned, to be finished by early next week:
   https://github.com/open-telemetry/opentelemetry-go/issues/880
   https://github.com/open-telemetry/opentelemetry-cpp/issues/148

- Issues responded to:
   https://github.com/open-telemetry/opentelemetry-collector/issues/1249
   https://github.com/open-telemetry/opentelemetry-cpp/issues/149
  
- SIG projects I am involved with:
   OpenTelemetry Collector: https://github.com/open-telemetry/opentelemetry-collector
   Go SDK: https://github.com/open-telemetry/opentelemetry-go

**Comment by mtwo** [comment]
Approved, thanks for reaching out to me @danielbang907

**Comment by reyang** [comment]
I'm supportive, too!

**Comment by SergeyKanzhelev** [comment]
Welcome, @danielbang907!
