### ISSUE TITLE
REQUEST: New membership for EdZou

### ISSUE THREAD

**Issue by EdZou** [open-telemetry/community#419]
## GitHub Username

@EdZou
## Organization you are requesting membership in

@open-telemetry
## Requirements

   [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
   [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
   [✅] I have subscribed to the Gitter channel
   [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
   [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
   [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors

@mtwo
@jmacd 

## List of contributions to the OpenTelemetry project

PRs reviewed / authored

- [Collector PR 1338](https://github.com/open-telemetry/opentelemetry-collector/pull/1338)

- [Collector-contrib PR 390](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/390) 

SIG projects I am involved with

- [Collector](https://github.com/open-telemetry/opentelemetry-collector)

- [Collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib)

**Comment by alolita** [comment]
@mtwo @jmacd - can you please approve @EdZou for membership? :-)

**Comment by mtwo** [comment]
I approve

**Comment by jmacd** [comment]
I approve!

**Comment by SergeyKanzhelev** [comment]
Welcome, @EdZou!
