### ISSUE TITLE
REQUEST: New membership for davidwitten

### ISSUE THREAD

**Issue by davidwitten** [open-telemetry/community#420]
### GitHub Username

@davidwitten

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan 
- @obecny 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
[opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+author%3Adavidwitten+): PRs 1197, 1256, 1258, 1271, 1280, 1288, 1308, 1309, 1320
[GoogleCloudPlatform/OpenTelemetry-Operations-JS](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pulls?q=is%3Apr+author%3Adavidwitten+): PRs 78, 85
- Issues responded to
[opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/issues?q=is%3Aissue+commenter%3Adavidwitten): Issues 1109, 1193, 1294
[GoogleCloudPlatform/OpenTelemetry-Operations-JS](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues?q=is%3Aissue+author%3Adavidwitten): Issues 77, 79, 84
- SIG projects I am involved with
opentelemetry-js

**Comment by obecny** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @davidwitten!
