### ISSUE TITLE
Create open-telemetry/java-instrumentation-triagers

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#421]
We want to [add our first triager](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/741), and so I think we need the `open-telemetry/java-instrumentation-triagers` group created.

Thanks! (and thanks for creating this new role!)

**Comment by SergeyKanzhelev** [comment]
All done. all java instrumentation maintainers has permissions to add/remove members for both teams - approvers and triagers
