### ISSUE TITLE
REQUEST: New membership for jchengsfx

### ISSUE THREAD

**Issue by jchengsfx** [open-telemetry/community#422]
### GitHub Username

@jchengsfx

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

PRs reviewed / authored:
- opentelemetry-collector:
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1120
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1153
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1156
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1229
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1243
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1278
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1335
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1350
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1356
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1360
  - https://github.com/open-telemetry/opentelemetry-collector/pull/1376

- opentelemetry-collector-contrib:
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/381
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/405
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/443
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/445
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/465
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/484

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @jchengsfx!
