### ISSUE TITLE
REQUEST: New membership for jpkrohling

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#424]
### GitHub Username

@jpkrohling

### Organization you are requesting membership in

e.g. @open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pjanotti
- @yurishkuro 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: [`org:open-telemetry is:pr author:jpkrohling`](https://github.com/search?q=org%3Aopen-telemetry+is%3Apr+author%3Ajpkrohling)
- Issues responded to: [`org:open-telemetry is:issue author:jpkrohling`](https://github.com/search?q=org%3Aopen-telemetry+is%3Aissue+author%3Ajpkrohling)
- SIG projects I am involved with: Collector (includes Operator)

**Comment by SergeyKanzhelev** [comment]
Welcome, @jpkrohling!
