### ISSUE TITLE
Proposal: Education SIG

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/community#427]
There's an increasing number of people working on not just docs, but also example code, workshop code, demos, etc. -- so I'd like to propose that we have a regular weekly meeting time, set of repos, etc. in the open-telemetry organization (and also therefore have the programmatic capability to enforce the CLA on any shared example code we produce)

**Comment by SergeyKanzhelev** [comment]
would it be the same set of people who is currently on website SIG? Also, I like the name education, so maybe rename it to increase scope?

**Comment by austinlparker** [comment]
Not to overload the term, but what about 'Community SIG'? Responsibilities would include website, docs, example code, demos, and other cross-cutting community resources.

**Comment by SergeyKanzhelev** [comment]
Perhaps Comms SIG? Also education is very good. I feel like the governance committee is somehow already a Community SIG =) But it's not a strong objection, I really like where it's going.

BTW, @austinlparker do you believe this would be the same people? Just confirming my initial reaction on this proposal

**Comment by austinlparker** [comment]
I think it'd mostly be the same people, yeah - well, Liz too, I hope?

**Comment by lizthegrey** [comment]
> I think it'd mostly be the same people, yeah - well, Liz too, I hope?

affirmative. I don't have a horse in the www race, but there are other community areas I'd love to participate in.

**Comment by austinlparker** [comment]
I think 'Communication SIG' is a good idea. Responsibilities would cover:
- Website
- Education/Workshop Resources
- OTel 'official' video content (like otel tuesdays, etc.)
- Unified Documentation
- More(?)

I also like `comms` as a repo name, just to conserve a few characters when typing.

**Comment by alolita** [comment]
@SergeyKanzhelev @lizthegrey While all these SIGs would be great to have, it may be tough to retain regular participation if we have multiple SIG meetings - e.g on docs, education, website, comms etc. I vote recommend considering one community SIG meeting which addresses all these areas until we have more owners to run individual SIGs with clear charters.

**Comment by SergeyKanzhelev** [comment]
yep, this is what I am advocating for as well. Definitely need to expand [this membership](https://github.com/open-telemetry/community/blob/master/community-members.md#docs-and-website) as well with the expansion of a scope.

**Comment by alolita** [comment]
@SergeyKanzhelev yes agree - both membership and scope should be expanded. We've a lot of newcomers contributing on the project but it is difficult to find a clear graduation path for contributors to stay involved in the project long term. Would love to see that stickiness for the project.

**Comment by austinlparker** [comment]
@SergeyKanzhelev is there an issue template for creating a new SIG, I looked and didn't find anything

**Comment by SergeyKanzhelev** [comment]
There is no issue template. Just comment here if you need anything like github team renames and somebody will take care of it. There were no concerns with this SIG creation.

**Comment by austinlparker** [comment]
Ah, cool. Could you adjust the OpenTelemetry Website Sync meeting on the public calendar to be an hour and rename it to 'OpenTelemetry Communications SIG Meeting'? I'll update the website/notes to reflect the new scope and publicize it.

**Comment by SergeyKanzhelev** [comment]
> Ah, cool. Could you adjust the OpenTelemetry Website Sync meeting on the public calendar to be an hour and rename it to 'OpenTelemetry Communications SIG Meeting'? I'll update the website/notes to reflect the new scope and publicize it.

You should be able to do this: https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md We strive for self-service on meetings handling

**Comment by austinlparker** [comment]
I didn't realize I had permissions. Ok, first meeting will be thursday, thanks

**Comment by SergeyKanzhelev** [comment]
@austinlparker please add this to the agenda of your meeting in case anybody from OpenTelemetry needs some help, especially before the 1.0.

> We're introducing new office hours with our technical writers!
> This is 10am Pacific on the last Wednesday of the month, see the [CNCF community calendar](https://www.cncf.io/calendar/) for the invite. 
> 
> Need docs help? Visit the new CNCF docs office hours! Our Technical writers can help with tooling questions, offer advice on docs triage and workflow, talk about how to attract docs contributors, and maybe review a PR or two.
> 
> Zach Corleissen is a lead technical writer who joined the CNCF in November 2017. He focuses primarily on Kubernetes (where he chairs SIG Docs) but his role is expanding to more CNCF projects.
> 
> Celeste Horgan is a senior technical writer who joined the CNCF earlier this year. She has worked on websites and docs for Vitess, Kubernetes, Longhorn, in-toto and other CNCF projects.
> 
> Patrice Chalin is a senior technical writer who joined the CNCF earlier this year. He works on gRPC docs.

**Comment by trask** [comment]
@open-telemetry/end-user-wg and @open-telemetry/docs-approvers does it make sense to close this as done?

**Comment by cartermp** [comment]
Woah, old issue. Yeah, I think this can be closed. Maybe a more specific SIG would emerge later but for now but the combination of Comms and WG SIG seems to adequately cover the need here (insofar as there's people who work on the stuff listed here).
