### ISSUE TITLE
Upgrade OpenTelemetry GitHub organization account to support more GitHub Actions

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#429]
Hi OT Project Maintainers, Governance group, 

Our team - including our AWS interns have been building out the CI/CD workflows for build, test and publish artifacts using GitHub Actions workflows across several repos in OpenTelemetry. We've implemented these CI/CD workflows in C++, Ruby and other language specific repos. This has made it easier for developers to easily build and test their PRs without a CircleCI dependency.

We notice there is a limit on the number GitHub Actions workflows in a free account. This is restricting some of the individual SDK maintainer teams (for e.g. the C++ SDK) from building out required build-test-release pipelines. 

The solution would be to upgrade the GitHub account from Free to a paid plan to increase the number of Actions available across all repos in the project.

What is the process for getting the GitHub account upgraded to a paid plan for the OpenTelemetry project? See https://github.com/pricing

I plan to bring this up as a discussion item for the maintainers meeting next week. It may be useful for the OT governance group to discuss too. 

@mtwo can you please file a trouble ticket on the CNCF ticketing system to request the LF/CNCF team to upgrade the account?

Related links: https://github.com/open-telemetry/community/issues/398, https://github.com/open-telemetry/opentelemetry-cpp/issues/102, https://github.com/open-telemetry/opentelemetry-cpp/pull/103

cc: @reyang @alolita

**Comment by reyang** [comment]
On the [7/27/2020 maintainers meeting](https://docs.google.com/document/d/1-tGqaT9fn9Bpuy4roLS1YDfLzIWHodUFfyrBlyJVz9g/edit#heading=h.2ajso5m3t2ad) I asked about this. Based on what I heard (please refer to the meeting notes), it seems that @SarahNovotny is helping us to increase the limit from 20 concurrent jobs to 60 and we should be able to get it this week.

**Comment by alolita** [comment]
Thanks! @reyang @sarahnovotny This is great news!

**Comment by bogdandrutu** [comment]
@sarahnovotny any update?

**Comment by trask** [comment]
> any update?

@idvoretskyi (CNCF) and @SergeyKanzhelev are coordinating a meeting with the GitHub team to find out our options, hoping for good news soon 🤞

**Comment by trask** [comment]
got confirmation from @SergeyKanzhelev that the OpenTelemetry org is on GitHub "Team" subscription with 60 concurrent jobs 👍

**Comment by bogdandrutu** [comment]
Will close this since it is resolved
