### ISSUE TITLE
REQUEST: New membership for XSAM

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/community#432]
### GitHub Username

@XSAM

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias
- @Aneurysm9 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - open-telemetry/opentelemetry-go#986
  - open-telemetry/opentelemetry-go#905
  - open-telemetry/opentelemetry-go#796
  - open-telemetry/opentelemetry-go-contrib#153
  - open-telemetry/opentelemetry-go-contrib#134
  - open-telemetry/opentelemetry.io#226
- Issues responded to
  - open-telemetry/opentelemetry-go#890
  - open-telemetry/opentelemetry-go#792
  - open-telemetry/opentelemetry-go-contrib#87.
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-go
  - https://github.com/open-telemetry/opentelemetry-go-contrib
  - https://github.com/open-telemetry/opentelemetry.io

**Comment by Aneurysm9** [comment]
I'm @aneurysm9 and I approve this membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @XSAM!
