### ISSUE TITLE
REQUEST: New membership for dengliming

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/community#433]
### GitHub Username

@dengliming

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✅] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@trask 
@jkwatson

### List of contributions to the OpenTelemetry project

PRs reviewed / authored
- [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Apr+author%3Adengliming)
- [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java/pulls?q=is%3Apr+author%3Adengliming)
- [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Adengliming)

Issues responded to

- [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues?q=is%3Aissue+involves%3Adengliming)

SIG projects I am involved with
- [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation)
- [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java)
- [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib)

**Comment by SergeyKanzhelev** [comment]
Welcome, @dengliming!
