### ISSUE TITLE
Create a repository for GPU metrics extractor

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/community#434]
Currently OpenTelemetry Collector does not support GPU related metrics and the issue and PR were made (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/392), https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/393) in opentelemetry-collector-contrib for it.

However, because of the mandatory dependency to CGO, contrib Collector can't afford the PR and the repository approvers suggested the independent binary that collects GPU metrics and emits those in Prometheus format. Because the binary would be the complement feature for the Collector, I request a new repository for the binary in OpenTelemetry org with the following reasons:

1. NVIDIA's GPU is defacto among famous public cloud platforms (i.e. GCP, AWS, Azure, Oracle, IBM, etc.)
2. Anyway someone needs to write a GPU metrics collection binary to integrate with OpenTelemetry Collector
3. The feature completes the gap between GPU users and existing OpenTelemetry projects

Though NVIDIA has the OSS to emit GPU metrics in Prometheus format, it requires the extra setup in addition to NVML and I think we do worth doing the effort apart from NVIDIA's.
https://github.com/NVIDIA/gpu-monitoring-tools

@anuraaga has also shown his interests to the idea as well.

**Comment by bogdandrutu** [comment]
I think the collector receiver can live in contrib, just avoid shipping it in the contrib binary because of the cgo problem. This is what I personally think

**Comment by tigrannajaryan** [comment]
> I think the collector receiver can live in contrib, just avoid shipping it in the contrib binary because of the cgo problem. This is what I personally think

This is a good middle-ground. Put the source code in the contrib repo but build a separate binary from it.

**Comment by ymotongpoo** [comment]
@bogdandrutu @tigrannajaryan Thank you for the suggestion. Then, I'll be back to the controller-contrib repo and create another PR to create isolated directory or something for it.

**Comment by tigrannajaryan** [comment]
Anyone who has a permission: please close this issue since a new repo is no longer needed.

**Comment by trask** [comment]
hi @elgalu! I'd recommend asking in https://github.com/open-telemetry/opentelemetry-collector or https://github.com/open-telemetry/opentelemetry-collector-contrib
