### ISSUE TITLE
REQUEST: New membership for rmfitzpatrick

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/community#435]
### GitHub Username

rmfitzpatrick

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan
- @bogdandrutu

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

authored:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/325
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/349
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/495

reviewed:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/587
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/582
https://github.com/open-telemetry/opentelemetry-collector/pull/1414

- Issues responded to
https://github.com/open-telemetry/opentelemetry-collector/issues/1385

- SIG projects I am involved with
Agent/Collector SIG meeting attendee

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @rmfitzpatrick!
