### ISSUE TITLE
REQUEST: New membership for ercl

### ISSUE THREAD

**Issue by ercl** [open-telemetry/community#436]
### GitHub Username
@ercl

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @reyang 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-ruby/pull/296
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-ruby/issues/287
  - Working on https://github.com/open-telemetry/opentelemetry-go-contrib/issues/119
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-go
  - https://github.com/open-telemetry/opentelemetry-go-contrib/
  - https://github.com/open-telemetry/opentelemetry-ruby

**Comment by reyang** [comment]
Welcome @ercl! 👍

**Comment by SergeyKanzhelev** [comment]
Welcome, @ercl!
