### ISSUE TITLE
REQUEST: New membership for macrogreg

### ISSUE THREAD

**Issue by macrogreg** [open-telemetry/community#437]
### GitHub Username

@macrogreg

### Organization you are requesting membership in

open-telemetry

### Requirements

- [YES ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [YES ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [YES] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [YES ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [YES ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [YES ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@pjanotti 
@cijothomas 

### List of contributions to the OpenTelemetry project

I will be doing the initial commit / fork and subsequently I will co-maintain the .NET auto-instrumentation project.
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

This is a new repo / project that is different fro the .NET SDK project.  

Until so far, I have been involved into discussions of the .NET SDK SIG, and into the start-up discussions of the new .NET auto-instrumentation SIG. 

Please let me know if you require any additional information.

Thank you!

**Comment by cijothomas** [comment]
Approve.

**Comment by bogdandrutu** [comment]
Invite sent

**Comment by macrogreg** [comment]
Thank you, all!
