### ISSUE TITLE
Request to participate in docs-cn maintenance

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/community#438]
@SergeyKanzhelev 
I am a developer from China. very happy to be a member of opentelemetry. I am very willing to participate in maintenance, and look forward to attracting more Chinese community partners. thanks.

**Comment by SergeyKanzhelev** [comment]
@dengliming sorry for the delay. Welcome to OpenTelemetry! I see you already participate in a few repositories. There is a [docs-cn](https://github.com/open-telemetry/docs-cn) repo specifically for Chinese docs if you want to participate there. 

CC: @open-telemetry/docs-cn-approvers  to welcome @dengliming and coordinate contributions.

If you are looking for being a member of CN docs  approvers, I made sure that current maintainers of the repository has enough permissions to promote you when appropriate. 

Let me know if something else is needed to get you started.
