### ISSUE TITLE
REQUEST: New membership for @lucaspimentel

### ISSUE THREAD

**Issue by lucaspimentel** [open-telemetry/community#439]
### GitHub Username

@lucaspimentel

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/open-telemetry/community/blob/master/community-membership.md).
- [x] I have enabled 2FA on my GitHub account.
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community).
- [x] I ~am~ will be (see note below) actively contributing to 1 or more OpenTelemetry subprojects.
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines.
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application.

### Sponsors

- @macrogreg
- @MikeGoldsmith
- @pjanotti

### List of contributions to the OpenTelemetry project

I work at Datadog on their .NET Tracer ([DataDog/dd-trace-dotnet](https://github.com/DataDog/dd-trace-dotnet/graphs/contributors)), which will be forked as the initial contribution to [opentelemetry-dotnet-instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation).

**Comment by macrogreg** [comment]
Approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @lucaspimentel!
