### ISSUE TITLE
REQUEST: New membership for nrcventura

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/community#440]
### GitHub Username

@nrcventura

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pjanotti 
- @macrogreg

### List of contributions to the OpenTelemetry project

- I plan on working with the brand new .NET auto-instrumentation project and have started to attend the .NET SDK SIG and .NET Auto-Instrumentation SIG meetings.
- I gave an overview of the newly open-sourced New Relic .NET auto-instrumenting agent during the .NET Auto-Instrumentation SIG meeting. The slides are available at [New Relic .NET Agent Auto-Instrumentation overview](https://docs.google.com/presentation/d/1AxiDlkgbXBcuBAkpoiF4IpIfwQFoo65SBrlX6u6RM8k/edit?usp=sharing). We don't know where the recording is for this SIG meeting yet.

**Comment by macrogreg** [comment]
Approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @nrcventura!
