### ISSUE TITLE
REQUEST: New membership for tommycpp

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/community#443]
### GitHub Username

@TommyCpp

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jtescher
- @MikeGoldsmith

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-rust/pull/164
https://github.com/open-telemetry/opentelemetry-rust/pull/152
https://github.com/open-telemetry/opentelemetry-rust/pull/148
https://github.com/open-telemetry/opentelemetry-rust/pull/141

- Issues responded to
https://github.com/open-telemetry/opentelemetry-rust/issues/165
- SIG projects I am involved with
[open-telemetry/opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust)

**Comment by jtescher** [comment]
👍 welcome @TommyCpp

**Comment by SergeyKanzhelev** [comment]
Welcome, @TommyCpp!

**Comment by jtescher** [comment]
@SergeyKanzhelev can we get @TommyCpp added to @open-telemetry/rust-approvers? I do not have the permission to add.

**Comment by SergeyKanzhelev** [comment]
Fixed permissions for you and added @TommyCpp.
