### ISSUE TITLE
REQUEST: New membership for @zacharycmontoya

### ISSUE THREAD

**Issue by zacharycmontoya** [open-telemetry/community#447]
### GitHub Username

@zacharycmontoya

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @macrogreg
- @lucaspimentel

### List of contributions to the OpenTelemetry project

I am a key contributor to the https://github.com/DataDog/dd-trace-dotnet repo which is being used as the seed for the new OTel project https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation. As such, I plan to be heavily involved into the .NET auto-instrumentation SIG and in work on the above-mentioned repo.

**Comment by lucaspimentel** [comment]
Approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @zacharycmontoya!
