### ISSUE TITLE
Location requested for standalone opentelemetry-java sdk using library

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/community#449]
Splunk would like to contribute JMX-based metric scrapers using a generic utility that reaches remote applications.  Given this is not in line with the current sdk scope or follow the local jvm auto-instrumentation practices of the otel java agent, the java-instrumentation SIG has suggested this tool should potentially go in a new opentelemetry-java-tools project or in an expanded/repurposed build-tools project.  Guidance would be appreciated, as this scenario could likely extend to other offerings that don't necessarily belong with their associated sdk or instrumentation projects.

https://github.com/open-telemetry/opentelemetry-java/pull/1523
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/954

Update from @SergeyKanzhelev:

- Repository: opentelemetry-java-contrib
- Maintainers: @rmfitzpatrick 
- Approvers: @anuraaga, @trask, @pmcollins

**Comment by keitwb** [comment]
What about just treating the collector-contrib repo as a monorepo for this kind of stuff?

**Comment by bogdandrutu** [comment]
The problem is the mix of languages, this would be better fit to be maintained by some Java experts I think.

**Comment by trask** [comment]
The problem is that this out-of-proc JMX metric scraping tool doesn't really fit into the scope of either of the current Java repos.

How about a new repo `opentelemetry-java-tools`, with @rmfitzpatrick as initial maintainer?

**Comment by trask** [comment]
> `opentelemetry-java-tools`

Or maybe `opentelemetry-java-contrib`?

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/java-maintainers @open-telemetry/java-instrumentation-maintainers either of these two groups want to be declared a maintainers for this new contrib repository? Or this will be a separate set of people?

**Comment by anuraaga** [comment]
Makes sense to me to share with @open-telemetry/java-instrumentation-maintainers, I think the scope is similar enough to the java instrumentation repo for people to be familiar working in both.

**Comment by iNikem** [comment]
We want to have @rmfitzpatrick as maintainer of that tool, I think. But not necessarily of neither main java nor instrumentation repo. Not yet at least :)

**Comment by trask** [comment]
> Or this will be a separate set of people?

Yes. There may be overlap of individuals, but we would prefer that it not reuse either of the existing groups.

**Comment by SergeyKanzhelev** [comment]
Presumably contrib will have more than JMX reader. @rmfitzpatrick are you OK to maintain the repository? @trask, @iNikem have you discussed it with Ryan?

**Comment by trask** [comment]
We discussed a couple of options with @rmfitzpatrick this morning in Java Instrumentation SIG meeting, and recommended that he open this issue. You can add me as an approver in the new repo. @anuraaga, @iNikem let us know if you would like to be approver/maintainer/abstain in the new repo.

**Comment by iNikem** [comment]
Would abstain for now. If I have free cycle I rather spend them in the main java repo.

**Comment by anuraaga** [comment]
Can join as approver too

**Comment by SergeyKanzhelev** [comment]
Once we have volunteers to maintain, happy to create a repository.

**Comment by trask** [comment]
How many maintainers are required?

**Comment by SergeyKanzhelev** [comment]
we don't have any at the moment

**Comment by trask** [comment]
i mean, if @rmfitzpatrick volunteers, do we still need to find additional maintainers? will help to know if i need to reach out to people to try to find a second maintainer

**Comment by SergeyKanzhelev** [comment]
I'd really love to get him commenting here =) Based on the text - it is a request for location, not the request to be a maintainer for bigger scope of contrib repo. Just want to make sure there actually will be somebody owning it.

**Comment by trask** [comment]
yup for sure, there's no rush 😄

**Comment by rmfitzpatrick** [comment]
I would be happy to be a maintainer for the contrib project and appreciate @trask and @anuraaga stepping in to help out.

@pmcollins has also agreed to be an approver.

**Comment by SergeyKanzhelev** [comment]
Repo and teams are created. @rmfitzpatrick, you should have enough permissions in the teams and repo to set up everything else. Some information: https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md
