### ISSUE TITLE
Document how to enable EasyCLA 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#452]
@lizthegrey can you please update docs on how to enable easyCLA for the new repos: https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md

**Comment by lizthegrey** [comment]
I'm not sure there's anything to add to the docs, it's a github check like any other github check, you turn on enforcement.

**Comment by lizthegrey** [comment]
> I'm not sure there's anything to add to the docs, it's a github check like any other github check, you turn on enforcement.

oh, on the easycla side, got it

**Comment by SergeyKanzhelev** [comment]
I believe this is done in https://github.com/open-telemetry/community/pull/454
