### ISSUE TITLE
Missing youtube video

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/community#453]
Hi all,

Some people are missing some videos, for example, last Thursday we had a Java Instrumentation SIG.

Searched using the following patterns:
- 2020-08-13 meeting
- 2020-08-13 Java Auto-Instrumentation SIG
- 2020-08-13 Java SIG

cc: @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
Can you please specify for each meeting:

- exact datetime with timezone
- meeting room
- duration (as you remember it)

This will simplify search thru zoom recordings.

**Comment by eddynaka** [comment]
Information:
- meeting: OpenTelemetry Java Instrumentation SIG
- datetime: Thu, August 13, 9am – 10am 
- meeting room: https://zoom.us/j/8203130519
- duration: don't know

**Comment by SergeyKanzhelev** [comment]
Found this. Is it the right meeting? 

Topic: Open Telemetry Meeting 1's Personal Meeting Room
Date: Aug 13, 2020 07:59 PM Central Time (US and Canada)

Meeting Recording:
https://zoom.us/rec/share/w_BeLIqs3VxIXLfE-E3ae_YDWYbjT6a80CYZ_PJZmonIo37S1v8u1D3xD4qqNVE

Access Password: K&S2e?Yf

@eddynaka did you check in YouTube if it's there?

**Comment by trask** [comment]
> Aug 13, 2020 07:59 PM Central Time

This is Java Instrumentation's weekly Office Hours, not the weekly SIG meeting, which is Thu 9am Pacific Time

**Comment by eddynaka** [comment]
@trask , if that's true, so we have at least 2 videos missing!

**Comment by SergeyKanzhelev** [comment]
what I found is matching the date, time (duration is over 1 hour) and room of what is requested. Could it be that room stayed open for two consequentive meetings?

**Comment by SergeyKanzhelev** [comment]
If so, please use different meeting rooms for the back to back meetings:

https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md

> Same color (meeting location) meetings must not be held at the same time or be back to back meetings.

**Comment by eddynaka** [comment]
@SergeyKanzhelev , it's strange. The Office hours (if we see in the calendar) occurs at 6pm. and the SIG occurs at 9am. So, it's not the case where we have the same room opened for many hours.

**Comment by trask** [comment]
Office Hours meeting often goes over 1 hour.

I'm more concerned about the missing weekly SIG meeting at 9am Pacific Time.

**Comment by SergeyKanzhelev** [comment]
@trask please give me =)

- exact datetime with timezone
- meeting room
- duration (as you remember it)

**Comment by trask** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=aDM0cDVuNHQ4a2RlM2NxaDRlN2NmcDRjbnNfMjAyMDA4MTNUMTYwMDAwWiB0cmFzay5zdGFsbmFrZXJAbQ&tmsrc=trask.stalnaker%40gmail.com&scp=ALL

~1 hour

**Comment by trask** [comment]
sorry wrong link:

https://calendar.google.com/event?action=TEMPLATE&tmeid=aDM0cDVuNHQ4a2RlM2NxaDRlN2NmcDRjbnNfMjAyMDA4MTNUMTYwMDAwWiBnb29nbGUuY29tX2I3OWUzZTkwajdiYnNhMm4ycDVhbjVsZjYwQGc&tmsrc=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com&scp=ALL

**Comment by SergeyKanzhelev** [comment]
@trask it shows me March 12. is it what you are looking for? 

![image](https://user-images.githubusercontent.com/9950081/90548909-885b5700-e142-11ea-902a-7e290a7ca9c5.png)


I'm not trying to be hard, I want to establish precedence that will make it easier to troubleshoot these kind of issues.

**Comment by trask** [comment]
try this: https://calendar.google.com/event?action=TEMPLATE&tmeid=aDM0cDVuNHQ4a2RlM2NxaDRlN2NmcDRjbnNfMjAyMDA4MTNUMTYwMDAwWiBnb29nbGUuY29tX2I3OWUzZTkwajdiYnNhMm4ycDVhbjVsZjYwQGc&tmsrc=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com

**Comment by eddynaka** [comment]
@SergeyKanzhelev , its showing that time, because of his timezone (probably). If we look at the official calendar its 9AM PST time.

**Comment by trask** [comment]
I had put in link to the "event" before, not link to the "event instance". The latest link above should be correct.

**Comment by SergeyKanzhelev** [comment]
this?

Topic: Open Telemetry Meeting 1's Personal Meeting Room
Date: Aug 13, 2020 10:59 AM Central Time (US and Canada)

Meeting Recording:
https://zoom.us/rec/share/2fN2f6HQ715LHtLiylrEf68ERojsT6a80ScX__sMmk6Pp3MV-5qSYwtYEMeR_M00

Access Password: s#XFUg0U

**Comment by trask** [comment]
YES! ❤️

**Comment by SergeyKanzhelev** [comment]
@eddynaka is it on YouTube? If not we need to ask @amye to file a support ticket with Splain. Can you please check?

**Comment by eddynaka** [comment]
Hi @SergeyKanzhelev , we don't have either videos that you posted.

**Comment by SergeyKanzhelev** [comment]
hm... Do we have any videos from this room?

**Comment by eddynaka** [comment]
yes, we have some. But, probably not all. For example, on 08/06, we should have 2 again. but we just have one. @trask , can you confirm that we had 2 meetings on 08/06 to 08/07?

**Comment by SergeyKanzhelev** [comment]
I think what will help @amye to file a ticket is information about meetings that was processed vs. not processed. @eddynaka can you help combining this information? @amye can you please follow up with Splain?

**Comment by trask** [comment]
> @trask , can you confirm that we had 2 meetings on 08/06 to 08/07?

yes, normal SIG meeting 8/6 @ 9am Pacific Time, and office hours 8/6 @ 6pm Pacific Time

**Comment by amye** [comment]
Ticket is in with Splain

**Comment by eddynaka** [comment]
Hi @amye , I think we have two problems in Splain:
- the missing videos (that you opened a ticket yesterday)
- duplicated upload video, it's the second time that it occurs in less than one week.
  - Room: cncf-opentelemetry
  - when happened: 08/18 4pm EST
  - length: 55:13 minutes

**Comment by trask** [comment]
Hi @SergeyKanzhelev, can maintainers have access to the Zoom account, and we can manually upload the videos for our SIG meetings?

**Comment by SergeyKanzhelev** [comment]
> Hi @SergeyKanzhelev, can maintainers have access to the Zoom account, and we can manually upload the videos for our SIG meetings?

Last it was discussed the suggestion was that sharing Zoom account with many people is not ideal. The working automation would be better. Mostly from the fragility of all the settings and lack of audit perspective. Also there weren't much interest in helping with videos upload among the maintainers. Generally maintainers are looking for help here, not for additional duty.

This issues is my attempt to establish a precedence on how missing videos can be reported and uploaded.

Are you looking for personally help with this or proposing to establish a process and tooling to make it maintainers responsibility?

**Comment by trask** [comment]
> Last it was discussed the suggestion was that sharing Zoom account with many people is not ideal

Ok, I guess scratch my proposal then.

> Also there weren't much interest in helping with videos upload among the maintainers.

If we could all access the Zoom account, then we would each only have to upload one video a week, but I understand if Zoom doesn't give the permissions needed to make this viable.

**Comment by SergeyKanzhelev** [comment]
@eddynaka @trask please re-open if this is still an issue. Should be resolved now

**Comment by trask** [comment]
Hi @eddynaka, @SergeyKanzhelev,

We're still missing the video from 8/20:

* Time: 9am-10am Pacific Time
* Meeting room: https://zoom.us/j/8203130519

Seems to be working great since then. I just really want to watch the recording from that particular meeting, because I was unable to attend it due to KubeCon, and the New Relic team gave a walkthrough in that meeting about their recently open sourced Java agent 👍.

**Comment by eddynaka** [comment]
I'll take a look tomorrow!
