### ISSUE TITLE
REQUEST: New membership for elucus

### ISSUE THREAD

**Issue by elucus** [open-telemetry/community#457]
### GitHub Username

@elucus

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas
- @pjanotti 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-dotnet
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

**Comment by SergeyKanzhelev** [comment]
Welcome, @elucus!
