### ISSUE TITLE
Android advice needed in the Java and Java Instrumentation projects

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#458]
Hi all!

We need Android advice in the Java and Java Instrumentation projects around how to best support Android developers.

Are there any knowledgeable folks in the community who can advise us, or anyone outside of the community that you could connect us with?

Our current questions are:

* What libraries are critical for Android developers from an observability perspective? (e.g. OkHttp, ...)
* What Android API levels should we target for these libraries' instrumentation?
* Best practices around supporting older Android API levels?

I'm sure we will have more questions, so really hoping to connect with one or more people who can be our informal Android advisory committee.

Thanks,
Trask

**Comment by SergeyKanzhelev** [comment]
CC: @mtwo explicitly
CC: @nikmd23, do you know anybody in AppCenter team who can help with this?

**Comment by nikmd23** [comment]
I do not know anyone over there. 😟

I do, however, see that the following folks have contributed to the AppCenter/Android docs and might know who can help here: @anywherepilot, @conceptdev, @matthiaswenz, @jwargo, @King-of-Spades, @nilofer

**Comment by anywherepilot** [comment]
Start in #appcenter and someone will point you in the right direction :)

**Comment by mtwo** [comment]
@bogdandrutu we connected with Eric Anderson at Google and he gave useful feedback on gRPC integrations. Do you know anyone on the Android team who would be able to answer these questions and advise?

**Comment by matthiaswenz** [comment]
@trask I'll be happy to answer questions about Android at App Center and what we learned or connect with folks who know more.

**Comment by King-of-Spades** [comment]
Hi, I'm the current primary maintainer of App Center Docs (previously done by @jwargo & @conceptdev in the past). But most of what I do is aid with the research, publishing and maintenance of the docs...it's less about what I "know" and more about information or knowledgable folks I can find.

With your questions, I'm a bit unclear about how it ties over to App Center specifically...? Are you just hoping the team has some general knowledge/insight that's relevant?

**Comment by SergeyKanzhelev** [comment]
> With your questions, I'm a bit unclear about how it ties over to App Center specifically...? Are you just hoping the team has some general knowledge/insight that's relevant?

This is the hope. My understanding is that @trask is looking for some insights in app population and directions how to make OpenTelemetry cover the most use cases with minimal initial investments.

**Comment by King-of-Spades** [comment]
1. What libraries are critical for Android developers from an observability perspective? (e.g. OkHttp, ...)
2. What Android API levels should we target for these libraries' instrumentation?
3. Best practices around supporting older Android API levels?

Well, my instinct is that questions #2 & #3 likely inherit directly from #1. Say for example, all of the libraries you identify as critical support a certain API range, that'd probably be the default, recommended range to use. 

Supporting older versions via compatibility could range from trivial, if it "just works" but isn't actively maintained by the library maintainers; to possible but challenging if it requires some sort of achievable compatibility modifications; to nigh impossible if there are non-trivial breaking changes. 

As for which libraries those would be...that's out of my area of expertise, I'm a lot more familiar with "is this valid?" types of questions, with fairly concrete boundaries...vs. offering more abstract recommendations. Best of luck though!

**Comment by SergeyKanzhelev** [comment]
@trask is this issue still actual? I believe I saw people from Android community in Java calls on recordings.

**Comment by trask** [comment]
Thanks everyone for the connections!

I will close.

What we seem to be lacking most now is users. If you know any, please send them our way!
