### ISSUE TITLE
REQUEST: New membership for robertlaurin

### ISSUE THREAD

**Issue by robertlaurin** [open-telemetry/community#459]
### GitHub Username

@robertlaurin

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @fbogsany 
- @mwear 

### List of contributions to the OpenTelemetry project
[Opentelemetry-ruby PRs authored by @robertlaurin](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=is%3Apr+is%3Aclosed+author%3Arobertlaurin)

[Opentelemetry-ruby PRs reviewed by @robertlaurin](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=is%3Apr+reviewed-by%3Arobertlaurin)

**Comment by SergeyKanzhelev** [comment]
Welcome, @robertlaurin!
