### ISSUE TITLE
REQUEST: New membership for @ericmustin

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/community#460]
### GitHub Username

@ericmustin

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mwear 
- @fbogsany 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [opentelemetry-ruby PRs](https://github.com/open-telemetry/opentelemetry-ruby/commits?author=ericmustin)
  - [vendor exporter ruby](https://github.com/DataDog/dd-opentelemetry-exporter-ruby)
  - [vendor exporter js](https://github.com/DataDog/dd-opentelemetry-exporter-js)
- Issues responded to
  - [oteps](https://github.com/open-telemetry/oteps/pull/107#issuecomment-660067529)
  - [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/issues/1322#issue-658647254)
- SIG projects I am involved with
  - [opentelemetry-ruby](https://github.com/open-telemetry/opentelemetry-ruby)
  - [opentelemetry-js (participating in mtgs, no contribs to core yet)](https://github.com/open-telemetry/opentelemetry-ruby)

**Comment by SergeyKanzhelev** [comment]
Welcome, @ericmustin!
