### ISSUE TITLE
REQUEST: New membership for lalitb

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/community#464]
### GitHub Username

 @lalitb

### Organization you are requesting membership in

 open-telemetry

### Requirements

- [YES ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ YES] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ YES] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ YES] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ YES] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ YES] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang 
- @maxgolov

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    https://github.com/open-telemetry/opentelemetry-cpp/pull/309
- Issues responded to
https://github.com/open-telemetry/opentelemetry-cpp/pull/211
https://github.com/open-telemetry/opentelemetry-cpp/pull/143
https://github.com/open-telemetry/opentelemetry-cpp/pull/290

Would be continuing contribution to opentelemetry-cpp repo.

**Comment by SergeyKanzhelev** [comment]
@reyang @maxgolov I want to remind you about two companies representatives rule of membership. When you suggest your sponsorship, please mention this rule.

>- Sponsored by 2 approvers. Note the following requirements for sponsors:
>    - Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating on issues, etc.
>    - Sponsors must be approvers or maintainers in at least 1 CODEOWNERS file in any repo in the OpenTelemetry org.
>    - Sponsors must be from multiple member companies to demonstrate integration across community.

I'm not going to block this request, it is not the first one violating this rule. But I will start doing it going forward.

**Comment by SergeyKanzhelev** [comment]
Welcome, @lalitb!

**Comment by lalitb** [comment]
Thanks @SergeyKanzhelev
