### ISSUE TITLE
REQUEST: New membership for hencrice@

### ISSUE THREAD

**Issue by hencrice** [open-telemetry/community#465]
### GitHub Username

hencrice

### Organization you are requesting membership in
@opentelemetry-collector-contrib or @open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pjanotti
- @bogdandrutu

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-collector-contrib/commits?author=hencrice
- Issues responded to: N/A
- SIG projects I am involved with: opentelemetry-collector-contrib

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu @pjanotti I want to remind you about two companies representatives rule of membership. When you suggest your sponsorship, please mention this rule.

>- Sponsored by 2 approvers. Note the following requirements for sponsors:
>    - Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating on issues, etc.
>    - Sponsors must be approvers or maintainers in at least 1 CODEOWNERS file in any repo in the OpenTelemetry org.
>    - Sponsors must be from multiple member companies to demonstrate integration across community.

I'm not going to block this request, it is not the first one violating this rule. But I will start doing it going forward.
