### ISSUE TITLE
Up For Grabs in CONTRIBUTING.md is not working

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#469]
In the OpenTelemetry Contributor Guide the link to https://up-for-grabs.net/#/filters?tags=opentelemetry is not working:

> You can also find issues crafted for contributions using the tag **opentelemetry** at [up-for-grabs.net](https://up-for-grabs.net/#/filters?tags=opentelemetry).

The open-telemetry projects are not listed and therefor one can not find those issues. Here is the guide to list the projects on up-for-grabs.net: https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/docs/list-a-project.md

**Comment by SergeyKanzhelev** [comment]
@svrnm would you like to help out with this?

**Comment by svrnm** [comment]
@SergeyKanzhelev Sure, I can give it a try. I can create the required files for up-for-grabs.net and hand it in as PR there.

**Comment by ritwik12** [comment]
@SergeyKanzhelev and @svrnm Ritwik here from up-for-grabs.net. I have merged your PR for now. but please spend some time doing the following:

`One issue is there that there are some projects which do not have any issues labeled with the tag `**help wanted**` on their repository. Would request you to please add those so that if someone visits the project site they would not be treated with 0 issues.`

**Comment by svrnm** [comment]
> One issue is there that there are some projects which do not have any issues labeled with the tag help wanted on their repository. Would request you to please add those so that if someone visits the project site they would not be treated with 0 issues.

@SergeyKanzhelev not sure how to handle this: I can do another PR and remove some of the projects that are less active? Or opening issues with those projects calling out that they now can have their issues listed on up-for-grabs?

**Comment by ritwik12** [comment]
@svrnm  You can provide some other label too instead of help wanted. Or you can also create new issues there.

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev not sure how to handle this: I can do another PR and remove some of the projects that are less active? Or opening issues with those projects calling out that they now can have their issues listed on up-for-grabs?

Creating issue for repo maintainers is the best. It will be another reminder of importance to have entry-level tasks for new contributors.

Thank you!

**Comment by svrnm** [comment]
As you can see above, I added an issue to all the repos that are not having "help wanted" or "good first issue" tickets (excluding build-tools as it has 0 issues right now overall)

**Comment by SergeyKanzhelev** [comment]
CC: @tedsuo

Ted promised to help promote the need for better beginners issues hygiene.

**Comment by alolita** [comment]
@SergeyKanzhelev @tedsuo I can team up with you to help triage and label "help wanted" issues and "good first issues".

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev @tedsuo I can team up with you to help triage and label "help wanted" issues and "good first issues".

thank you! This is a constant problem with many projects to keep code welcoming for new contributors.

**Comment by svrnm** [comment]
@alolita @SergeyKanzhelev & @tedsuo -- Since I am still new to this community and trying to figure out how and where I can help best, feel free to use me as your "test dummy"

**Comment by svrnm** [comment]
@SergeyKanzhelev since the up for grabs is now updated, I think we can close this ticket?
