### ISSUE TITLE
REQUEST: New membership for ThomsonTan

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/community#471]
### GitHub Username

@ThomsonTan

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang
- @pyohannes

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-cpp/pull/301
https://github.com/open-telemetry/opentelemetry-cpp/pull/309
- Issues responded to
- SIG projects I am involved with
OpenTelemetry C++

**Comment by SergeyKanzhelev** [comment]
Welcome, @ThomsonTan!
