### ISSUE TITLE
[Zoom meetings] Thursday problem

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/community#472]
Hi,

I have been following the meetings calendar vs zoom recordings vs youtube.

Today I saw one problem: on Thursday we have three sequential meetings with the same room. With that, we can overlap the meeting record and it won't stop. That happened this Thursday, our recording is 2:30h long and has many meetings.

Below a link of the recording: https://zoom.us/recording/detail?meeting_id=4ZWShkgbSPOr%2BYZGgtpmlA%3D%3D

**Comment by SergeyKanzhelev** [comment]
We only have three zoom rooms and recordings got merged if room is not fully empty before the next meeting starts.

@open-telemetry/java-instrumentation-maintainers , @open-telemetry/python-maintainers, @open-telemetry/ruby-maintainers is 9-10 slot works for you? If so we might need to create a new room. If you've been thinking of rescheduling or shortening meeting - it may definitely help streamline video uploads.

![image](https://user-images.githubusercontent.com/9950081/92285261-b5d13000-eeb8-11ea-82af-37064e7d3c5b.png)

**Comment by fbogsany** [comment]
✋ I’ve been thinking about rescheduling the Ruby SIG meeting. I’ll discuss options with folks on Gitter and see if there’s a time that works for everyone.

**Comment by SergeyKanzhelev** [comment]
@fbogsany this would be great. Let us know if you want to keep the timeslot so we will need to start working on getting an extra room.

**Comment by tylerbenson** [comment]
maybe we should encourage minimum 30 min gaps between similar zoom rooms.

**Comment by SergeyKanzhelev** [comment]
there is already mention about it here: https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md

**Comment by fbogsany** [comment]
I'm polling folks in the Ruby SIG Gitter channel to see if we can find a non-conflicting time. I hope to have the meeting moved by EOD today.

**Comment by fbogsany** [comment]
I've moved the Ruby SIG meeting to Tuesday noon Eastern / 9am Pacific. We'll reschedule again if we find a better time, but this should resolve the scheduling issue here for now.

**Comment by SergeyKanzhelev** [comment]
> I've moved the Ruby SIG meeting to Tuesday noon Eastern / 9am Pacific. We'll reschedule again if we find a better time, but this should resolve the scheduling issue here for now.

Thank you! This is very helpful. But please do feel free to book it back and let us know that you need a new room.

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/python-maintainers python sig meeting zoom link changed in calendar to avoid back to back meetings. Please make sure to communicate it to everybody involved.
