### ISSUE TITLE
Java SIG meeting was flagged on YouTube

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#473]
@trask (I saw you been most active on the meeting), any idea why the Java SIG meeting recording might have been flagged? Has anything unusual happened during the call? I briefly watched episodes and didn't find any issues, but didn't watch end-to-end. Please suggest

Hi OpenTelemetry,

As you may know, our [Community Guidelines](https://www.youtube.com/attribution_link?a=en2Ze5wqfVVCFU6o&u=/t/community_guidelines) describe which content we allow – and don’t allow – on YouTube. Your video [2020-09-03 Java SIG](https://www.youtube.com/attribution_link?a=en2Ze5wqfVVCFU6o&u=/watch%3Fv%3DHH76HMcL59g) was flagged to us for review. Upon review, we’ve determined that it violates our guidelines and we’ve removed it from YouTube.

We know that this might be disappointing, but it's important to us that YouTube is a safe place for all. If content breaks our rules, we remove it. If you think we've made a mistake, you can appeal and we'll take another look. Keep reading for more details.

**Impact on your account**

This removal has not resulted in a Community Guidelines strike or penalty on your account. However, we still encourage you to review all of your content to make sure it's in line with our Community Guidelines. Additional violations could result in strikes against your account, or even lead to account termination.

**How you can respond**

If you believe this was a mistake, we'd like to hear from you. To appeal this removal, please submit this [form](https://www.youtube.com/attribution_link?a=en2Ze5wqfVVCFU6o&u=/appeal_policy%3Fappeal_type%3Dreject%26v%3DHH76HMcL59g). Our team will thoroughly review your appeal and will contact you again soon.

Sincerely,
 The YouTube Team

**Comment by Oberon00** [comment]
2020-09-03 is a Thursday, so no Java SIG. Could be "OpenTelemetry Java Instrumentation SIG" or "Java Instrumentation Office Hours" though.

**Comment by SergeyKanzhelev** [comment]
renamed. Also somebody submitted the appeal and it was reinstated. Thank you!

**Comment by trask** [comment]
weird. no idea why it would have been flagged.
