### ISSUE TITLE
Add labels to entry level tasks for new contributors

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#474]
Hi,

based on #469 I have added **open-telemetry/community** to Up For Grabs:

https://up-for-grabs.net/#/filters?names=640

There are currently no issues with label [help wanted](https://github.com/open-telemetry/community/labels/help%20wanted). Please add this label to your entry level tasks, so people can find a way to contribute easily. 

If "help wanted" is not the right label, let me know and I can change it (e.g. to "good first issue" or "up-for-grabs"), or you can provide a pull request by editing https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/opentelemetry-community.yml

Thanks!

**Comment by SergeyKanzhelev** [comment]
CC: @tedsuo

**Comment by SergeyKanzhelev** [comment]
@svrnm @tedsuo would you like to take a look on how to onboard OpenTelemetry to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? Might be a good motivation to clean up these tags

**Comment by svrnm** [comment]
@SergeyKanzhelev @tedsuo happy to help with that!

**Comment by tedsuo** [comment]
Awesome @svrnm! Want to look through the organizers kit and see what steps we can take now? https://hacktoberfest.digitalocean.com/eventkit

**Comment by svrnm** [comment]
Sure, @tedsuo.

The first thing, that is doable right now is adding the label "hacktoberfest" on ticket that have a well-defined scope and are self-contained. Since I already have opened a ticket with most OTel projects regarding the help wanted/up-for-grabs I could update them and add some words on hacktoberfest.

Next, for the event organization it is already possible to create a virtual come together. There are no restrictions on the content of those meetings, only recommendations. So, one option would be to create event(s) right now.

Then we can go ahead and plan the structure (there is a [sample agenda](https://hacktoberfest.digitalocean.com/eventkit/#sample-agenda) provided). Those events can be for new-comers, existing contributors or maintainers. Since I am curious about one for "new comers" I can help to set one up 😎

**Comment by SergeyKanzhelev** [comment]
for the meeting part - this is how to create meetings: https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md Ask @mtwo for permissions if you don't have them.

**Comment by svrnm** [comment]
@tedsuo @SergeyKanzhelev what is a good place to find people that are interested in helping to run such an event? Gitter I suppose?

**Comment by SergeyKanzhelev** [comment]
Gitter or send e-mail to contributors mailing list

**Comment by svrnm** [comment]
Thanks, I send an email to the contributors mailing list and a message via gitter.

**Comment by svrnm** [comment]
Cross-Posting from gitter: A similar event like this one from the puppet community could be a great way to encourage contribution: https://organize.mlh.io/participants/events/4634-puppet-hackathon

**Comment by svrnm** [comment]
@SergeyKanzhelev @tedsuo:

The rules for hacktoberfest have changed sligthly: https://hacktoberfest.digitalocean.com/hacktoberfest-update -- it is opt-in now, so all projects that want to participate have to follow the process outlined there.

Rg. the virtual event: I got some feedback from people that are not yet officially contributors that want to get started, but no feedback so far from the contributors. I am still happy to support such an event

**Comment by SergeyKanzhelev** [comment]
sorry for delayed reply. All this spam is very unfortunate and it left a bad impression. I'd leave it as maintainers decision whether they want to do it. Thank you!

**Comment by svrnm** [comment]
Don't worry. This all was on short notice rg. the Hacktoberfest, worth a try, but since it's end of October now we should postpone this.

Rg. the initial purpose of this issue: there are now a few tickets from community listed on up for grabs, so this is done.
