### ISSUE TITLE
Add information about related groups

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#483]
Add information about related groups to this list: https://github.com/open-telemetry/community#related-groups

1. CNCF SIG Observability
2. K8s SIG Instrumentation
3. OpenMetrics

**Comment by VictoryWekwa** [comment]
Hello 
Good day.
I am an outreachy applicant and I will like to work on this issue if it is still open

**Comment by SergeyKanzhelev** [comment]
@VictoryWekwa please feel free to contribute. Promoting related groups on our community page would help cross-groups collaboration. For each group it would be great to add a small description and point to the corresponding group pages. Here are the links:

https://github.com/cncf/sig-observability

https://github.com/kubernetes/community/tree/master/sig-instrumentation

https://openmetrics.io/

**Comment by SergeyKanzhelev** [comment]
Fixed via #553
