### ISSUE TITLE
REQUEST: New membership for mateuszrzeszutek

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/community#485]
### GitHub Username

@mateuszrzeszutek

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @iNikem
- @trask 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  * https://github.com/open-telemetry/opentelemetry-specification/pull/789
  * https://github.com/open-telemetry/opentelemetry-java/pull/1554
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1058
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1082
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1093
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1167
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1177 
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1184
  * https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1208
- Issues responded to
- SIG projects I am involved with
  * Java instrumentation

**Comment by SergeyKanzhelev** [comment]
Welcome, @mateuszrzeszutek!
