### ISSUE TITLE
REQUEST: New membership for kubawach

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/community#486]
### GitHub Username

@kubawach 

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @iNikem 
- @trask 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1191
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1122
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1158
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1199

- Issues responded to
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1198
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1191
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/718
-- https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1111

- SIG projects I am involved with
OpenTelemetry Java Instrumentation SIG

**Comment by SergeyKanzhelev** [comment]
Welcome, @kubawach!
