### ISSUE TITLE
Need to hold the 2020 "OpenTelemetry Governance Committee" election

### ISSUE THREAD

**Issue by bhs** [open-telemetry/community#488]
(This is a tracking issue that we will close after the election has successfully happened)

Related work:
* [OpenTelemetry 2019 Governance Committee election materials](https://github.com/open-telemetry/community/tree/master/elections/2019)
* [The OpenTelemetry Charter](https://github.com/open-telemetry/community/blob/master/governance-charter.md#establishment-of-a-governance-committee) – though note that GC decided that the GC will elect enough new members to keep the steady-state GC population at 9 members rather than shrinking down in 2021 as the initial charter indicated. See #487 .
* We will try to get #461 checked off as part of the process.

We're due to complete the election before the end of October 2020 and are expecting to actually hold the vote in the back half of that month (details TBD as part of this process).

Also, I would love some help from non-GC members of the community here – admittedly there's not a lot of glory in operating the machinery here, but it's important from a process standpoint for it to be more than a one-person show (and for some of the folks to not-be on the GC already)! So all volunteers are welcome, just identify yourself in the issue comments below, please. :)  Thanks in advance and looking forward to working together!

**Comment by bhs** [comment]
@kateetak awesome, thanks! I'll let you know as things spin up.

**Comment by alolita** [comment]
Hi Ben @bhs - Count me in to help :-)

**Comment by bhs** [comment]
@kateetak and @alolita : can you reach out to me at `bhs@lightstep.com` so that we can use old-fashioned email tech to schedule an initial kickoff meeting? (FYI, I'll be recording that meeting and any others about election stuff – hope that's ok!)

**Comment by SergeyKanzhelev** [comment]
> @kateetak and @alolita : can you reach out to me at `bhs@lightstep.com` so that we can use old-fashioned email tech to schedule an initial kickoff meeting? (FYI, I'll be recording that meeting and any others about election stuff – hope that's ok!)

I'd be interested to join the kick off meeting. I likely will not have time to help with ongoing work, but would love to keep track of the process. One thing is happening is k8s working on voting app that will simplify the election and I want to make sure it will work for our needs.

**Comment by bhs** [comment]
@SergeyKanzhelev that would be great, thank you!

**Comment by alolita** [comment]
Hi @bhs Ack. Will reach out via email.

**Comment by bhs** [comment]
Hi @alolita @kateetak @SergeyKanzhelev: given timezones and just my general bias-to-action feelings, I wonder how much we can just coordinate here? That has the advantages of being (a) async, (b) lightweight, and (c) 100% visible to the community.

With that in mind, please review the following process doc: https://docs.google.com/document/d/1SyTo67KG3HuvwS1a7jDdbXD52Raru01M3QSBjpJ7OMI/edit?usp=sharing

Note in particular that **I'm proposed we announce this process on September 30**, which is not far away. :)  I just think we are a bit late and need to catch up in order to allow ample time for the nomination period.

@SergeyKanzhelev is the voting app something that's ready now? Or are you just gathering requirements?

**Comment by alolita** [comment]
@bhs On issue works for me. +100 for transparency.

**Comment by kateetak** [comment]
Works for me as well. I've added my first comments (and Ben already replied, 🙇‍♀️ ).

The only additional comment input I have is to add some "messages" from the current members to incentivize new applications. For example, we could ask them what was their favourite contribution to the committee, why they would recommend somebody to apply. 

There isn't much time tough, so this might be something to consider for next year.

**Comment by bhs** [comment]
@kateetak re

>The only additional comment input I have is to add some "messages" from the current members to incentivize new applications. For example, we could ask them what was their favourite contribution to the committee, why they would recommend somebody to apply.

I think that's a really nice idea though agree the timeline is very tight (probably too tight). If it's any consolation, last year we had way more applicants than vacancies, so I think (?) we should be ok in terms of fulfilling the requirements of the election. If nominations are sparse in the first few days, we can still do something like you suggest while the nomination period is open.

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev is the voting app something that's ready now? Or are you just gathering requirements?

they are in a spec writing stage now. So too early

**Comment by bhs** [comment]
@kateetak @alolita @SergeyKanzhelev 

Thank you all for your comments! I have made a number of updates to the doc... assuming there are major (remaining) concerns, let's turn that doc into a `.md` file tomorrow (a la [the process doc for the 2019 election](https://github.com/open-telemetry/community/blob/master/elections/2019/governance-committee-election.md)).

Of particular note is that I've taken @SergeyKanzhelev's suggestion to use GitHub PRs for the nomination and ratification process (unlike last year). It'll be a little hectic but should also solve a bunch of logistical scrambling last time around.

**Comment by SergeyKanzhelev** [comment]
lgtm. Thank you, @bhs!

I suggest to add a small task list in the end of the document so election committee can discuss who is doing what. It is already time to write an announcement blog post =)

**Comment by bhs** [comment]
Given how little time we have (and how crazy my 9-5 is), I just threw together #511 ... let's move comments on the process over there.

@SergeyKanzhelev maybe we can just throw the task list into this Issue??? I don't think there's all that much to be done aside from copy-pasta'ing some emails from last year and getting the voter list together.

PS: Sergey, do you remember how to run the "voter list" script?

**Comment by kateetak** [comment]
One more idea: as part of the "Results are announced" task (or even as a separate one), it would be good to also have the list of the new members published here: https://github.com/open-telemetry/community/blob/master/governance-charter.md

When I started browsing this repo, it took me some time to realize that the elections happened last year until I found the blog post on Medium: https://medium.com/opentelemetry/welcome-new-opentelemetry-governance-committee-members-6ac09fee3777

**Comment by SergeyKanzhelev** [comment]
> PS: Sergey, do you remember how to run the "voter list" script?

@lukaszgryglicki helped us with this. after quick search I cannot find lists and scripts from the last year - it may be left in my MS inbox. But should be in Lukasz outbox.

**Comment by bhs** [comment]
Okay... so here are some things that need to get done.

- [ ] ASAP: We need to write a blog post / messaging announcing the call for nominations. Here's [last year's post](https://medium.com/opentelemetry/opentelemetry-governance-call-for-nominations-cbdccdc9b999). We never did an announcement about the election more generally this year... here's [the one from 2019](https://medium.com/opentelemetry/kicking-off-opentelemetrys-governance-committee-election-3eb53aeeba43).
- [ ] We need to get help from @lukaszgryglicki on the script to pull email addresses out of OTel commit history
- [ ] We need to create a voter reg questionnaire that includes the questions from [this doc](https://docs.google.com/document/d/1dFFHNMv_hKrjWr9VBRRGBCfKtI-CBa3IWAS2zFGi9kc/edit#heading=h.fnq9bh66jdl) per [this issue](https://github.com/open-telemetry/community/issues/370)

Am I missing anything else that's needed in the very-near future?

**Comment by SergeyKanzhelev** [comment]
> * ASAP: We need to write a blog post / messaging announcing the call for nominations. Here's [last year's post](https://medium.com/opentelemetry/opentelemetry-governance-call-for-nominations-cbdccdc9b999). We never did an announcement about the election more generally this year... here's [the one from 2019](https://medium.com/opentelemetry/kicking-off-opentelemetrys-governance-committee-election-3eb53aeeba43).

For this item, feel free to reference the last year post explaining the GC: https://medium.com/opentelemetry/opentelemetry-governance-committee-explained-860353baba0. And ideally combine with the call for nominations (https://medium.com/opentelemetry/opentelemetry-governance-call-for-nominations-cbdccdc9b999). So there will be leas blog posts

I cannot think of any other asap tasks.

**Comment by alolita** [comment]
@bhs @SergeyKanzhelev I can draft a blog post announcing the call for nominations using the links you've provided as references. Would Monday Oct 5 work for a draft to review?

**Comment by SergeyKanzhelev** [comment]
> @bhs @SergeyKanzhelev I can draft a blog post announcing the call for nominations using the links you've provided as references. Would Monday Oct 5 work for a draft to review?

schedule is here: https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#schedule First announcement of this document can be done today via gitter. Make sure your blog post calls for nominations and pre-registration and targets Oct 7th publishing. @bhs please comment if you feel we need it today for Sept 30th "September 30: this document announced".

**Comment by alolita** [comment]
Thanks for the link @SergeyKanzhelev Agree first broadcast can be done today on Gittter. I can do the post tonight if that works @bhs - let me know.

**Comment by bhs** [comment]
@alolita that Gitter mention would be *much* appreciated as I am drowning in end-of-quarter stuff today.

Also, the Oct 5 review timeline works well... I don't think it will be too controversial, hopefully!

I will make a very quick PR to simply clean up the TODOs in the .md file here (pre-Gitter-post).

**Comment by alolita** [comment]
@bhs sounds good. Do we need a message to review before broadcasting on Gitter. I will prepare one today and share here before broadcasting. Will target blog post for Oct 5.

**Comment by bhs** [comment]
@alolita that would be great. I think a 👍 from any of Sergey, Kate, or me is sufficient to post to Gitter. :)  Just want a second pair of eyes on elections comms if possible.

**Comment by bhs** [comment]
Hm, I think we missed the Gitter message... any objections to the following? I can post it as soon as there's a 👍 here.

> Hi all: I just wanted to briefly and formally announce the *2020 OpenTelemetry Governance Committee Election.* The full process is described in [this document](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md). If you're a contributor to OTel, please vote! (Details in that doc) And if you'd like to run for the Governance Committee, please read the doc carefully as there are some deadlines coming up in the next few weeks. Thanks, and feel free to post process questions/concerns on [this GitHub issue](https://github.com/open-telemetry/community/issues/488).
>
> - The Election Committee

**Comment by alolita** [comment]
Hi @bhs Looks good to me :-) Was working on this as we speak but please go ahead and post.

**Comment by kateetak** [comment]
Same with me. You have my 👍

**Comment by bhs** [comment]
Well, I'm on my phone and accidentally sent the Gitter message when I tried to enter a line break before _signing_ the message as the election committee... Oh well!

https://gitter.im/open-telemetry/community?at=5f756ff21bb53378fea8ae4a

**Comment by alolita** [comment]
Hi @bhs Here is the blog post for the announcement. Let me know when its good to post. 
https://docs.google.com/document/d/1_AEFAea723zXc0whGJXubdRtBov-9wZ07gA1a8Kaaaw/edit?usp=sharing

**Comment by bhs** [comment]
@alolita thank you! The post LGTM at this point, though let's give people until EOD tomorrow to add comments since we don't need to post until Oct 7.

Thinking forward a bit, I think we ought to post this on the OpenTelemetry Medium blog and then tweet/retweet/etc. Make sense? If so, I think (?) I have admin privs on the Medium account and can figure out how to invite you as an author for that post. Let me know if you have any questions or concerns about that approach...

**Comment by alolita** [comment]
Works for me @bhs

**Comment by SergeyKanzhelev** [comment]
@alolita please send your medium account as a reply to this: https://lists.cncf.io/g/cncf-opentelemetry-comms/message/125

@bhs, people may ask whether they are members of standing. Have you or anybody started the mail thread with Lukasz to find out the list of active contributors? it would be nice to have it when post will be online

**Comment by bhs** [comment]
>Have you or anybody started the mail thread with Lukasz to find out the list of active contributors? it would be nice to have it when post will be online

We've `@mentioned` him a few times here but I'm sure it's getting drowned out by other GH notifications. I don't have his email address but will get it from you off-GH, @SergeyKanzhelev .

**Comment by alolita** [comment]
Done. @bhs @SergeyKanzhelev

**Comment by bhs** [comment]
@alolita: Thanks! I've added you as a "Writer" in the OTel Medium Publication. Can you copy-paste your doc contents as a "Draft" story, and then we can do one last spot-check before scheduling a time to post it tomorrow?

**Comment by mangotron** [comment]
@alolita Assuming this blog post goes live tomorrow, are you comfortable being mentioned on Twitter when we share this post? (If yes, please also confirm your Twitter handle). Thanks!

**Comment by alolita** [comment]
Hi @bhs here is the link to the draft post - https://medium.com/@alolita/draft-opentelemetry-governance-committee-election-oct-26-28-466ea51f2546

Please let me know if this link works :-)

**Comment by alolita** [comment]
@mangotron That works. My Twitter handle is the same as my GitHub handle :-)

**Comment by kateetak** [comment]
@alolita I can see the draft post just fine. I've checked the content and all the links in the blog and they lgtm. Thank you!

**Comment by bhs** [comment]
@alolita thank you – I think we should change the title to reflect that this is an announcement, and I found one other tiny copy nitpick when I re-read the post. I made suggested edits for both in [the google doc](https://docs.google.com/document/d/1_AEFAea723zXc0whGJXubdRtBov-9wZ07gA1a8Kaaaw/edit?ts=5f7b9ab1#heading=h.c4mahth8yuek) (since I can't edit the Medium post). After those changes are in, please submit for publication and we'll get this out there. Thanks again!

**Comment by alolita** [comment]
Hi @bhs I added a second draft with your updates. Please review and let me know if I need to do anything else for the post.

**Comment by bhs** [comment]
LGTM! Just hit "publish" in Medium...

**Comment by alolita** [comment]
Submitted for publishing on our project blog @bhs

**Comment by bhs** [comment]
Thanks! Published: https://link.medium.com/mXnoAkJMpab

@mangotron can you post to OTel twitter per your comment above? Thanks!

**Comment by mangotron** [comment]
Published! Here's the link for anyone who wants to help amplify: 

https://twitter.com/opentelemetry/status/1314230073742954496

**Comment by bhs** [comment]
Many thanks to @lukaszgryglicki who worked with me (via email) to pull a list of GH handles and email addresses associated with OTel commits... I think that can serve as the basis for the "members of standing" list we need to run the actual election. (The email addresses are pulled from the commit logs, to be clear)

**Comment by SergeyKanzhelev** [comment]
> Many thanks to @lukaszgryglicki who worked with me (via email) to pull a list of GH handles and email addresses associated with OTel commits... I think that can serve as the basis for the "members of standing" list we need to run the actual election. (The email addresses are pulled from the commit logs, to be clear)

note for the future - it will be great to document the process and a query used. Looking at [stats](https://opentelemetry.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All) there should be ~274 entries for members of standing. Also last year we mentioned accounts [without e-mails](https://github.com/open-telemetry/community/blob/master/elections/2019/governance-committee-election.md#user-content-appendix:~:text=For%20these%20accounts%20we%20didn't%20find%20e%2Dmails%20associated%20with%20the%20commits) explicitly.

**Comment by bhs** [comment]
Alright, so we're nearly done with the nomination period for GC candidates.

Thanks to @lukaszgryglicki, we have our "members of standing" list. @SergeyKanzhelev, per your request, here is the query that Lukasz used: https://github.com/cncf/devstats-reports#contributors-having-at-least-n

```
./contributors/contributors_with_n_dtrange.sh opentelemetry "now()-'1 year'::interval" 'now()' 20
```

Now, we need to do the following:
* Publicize the members-of-standing list given the above
* Determine which *single* email address to use for each one
* Make a best effort to get all of the above to fill out our annual member survey (without revealing their identity in the process since there is demographic info)
* Configure CIVS with the list of email addresses

My proposal to accomplish this:
1. Create a new GH issue in this repo that `@`-mentions every member of standing
1. Email everyone we have an email address for (via the commit logs harvested from the script above) in bcc telling them to go and read this new issue ^^^
1. Request that everyone reading the issue fills out **two** google forms: (i) a very short one that just asks for their GitHub handle and their preferred email address for CIVS voting, and (ii) an intentionally separate one to do the annual survey

We then use the email addresses from (i) for CIVS.

If we receive more than one email address for a given GH handle, we will manually determine which one is authentic. Hopefully people are honest and that doesn't happen.

cc @kateetak @SergeyKanzhelev since you've both been helping with process stuff here.

**Comment by bhs** [comment]
@kateetak @SergeyKanzhelev I've shared edit access to the proposed voter reg form just now. PTAL.

**Comment by SergeyKanzhelev** [comment]
Form LGTM. Last year we just picked the first e-mail and asked to fill out exception form if other e-mail needed to be used. But we didn't have 68 accounts without e-mail. So process totally makes sense.

**Comment by bhs** [comment]
@SergeyKanzhelev Yeah, and just glancing over the email addresses, some seem to be from former employers/etc, so I'd much prefer the fairness of requiring an explicit registration in this way.

**Comment by SergeyKanzhelev** [comment]
One note on the form - maybe we can add [this statement](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#user-content-voter-pre-registration:~:text=All%20pre%2Dregistrations%20are%20private.%20Only%20the,discarded%20one%20month%20after%20the%20election.) explicitly to the form: 

> All pre-registrations are private. Only the members of a current governance committee will have access to this information. Lists will be discarded one month after the election.

I wasn't able to find any lists - perhaps because I removed them, not because they stayed in my MS mailbox.

**Comment by bhs** [comment]
I added:

>Note that all registrations are private to the Election Committee and will not be used after the election is finished.

**Comment by bhs** [comment]
Ok! We have our (fully-ratified) candidate list.

The next step is to let the community know about it and to push on voter registration.

Here's the email I'd like to send with every ["member of standing" email address](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#appendix) we have bcc'd:

> *Subject: [PLEASE READ] Voting in the OpenTelemetry's 2020 Governance Committee Election*
>
> Hi there,
>
> If you're bcc'd on this message, it means that your email address was attached to a commit within an OpenTelemetry repo in the past year. Thank you for your contributions!
>
> As a [member of standing](https://github.com/open-telemetry/community/blob/master/governance-charter.md#members-of-standing), you are entitled to vote in the OpenTelemetry 2020 Governance Committee Election. Before you can do so, though, you must register by filling out this form:
>
>   [OpenTelemetry Voter Registration Form](https://forms.gle/X4XjnJsVyNauEq9U7)
>
> **If you don't explicitly register, you will not receive the invitation to vote (via the [CIVS](https://civs.cs.cornell.edu/) system) later this month.**
>
> There are four seats open in the election this year. You can read about the candidates here:
>
>    [2020 OpenTelemetry Governance Committee Candidates](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-candidates.md)
>
> If you'd like to learn more about the election, please read [this document](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md), and if you have questions or concerns, please raise them on [this GitHub issue](https://github.com/open-telemetry/community/issues/488).
>
> We thank you in advance for your participation in this important process!
> – The 2020 OTel Election Committee


Please let me know if there are any concerns or suggested edits to the above. If not, I'll send it out in 24-48h.

cc @kateetak @SergeyKanzhelev

**Comment by bhs** [comment]
(After sending the above, I'll send a very similar message (minus the first bit) to the overall OTel email list, Gitter, etc.)

**Comment by bhs** [comment]
(Email above sent, with current GC listserv bcc'd as well)

**Comment by bhs** [comment]
@SergeyKanzhelev @kateetak LGTY in terms of how to configure the poll? Again, this gets kicked off at 12:01am GMT on Oct 26.

![image](https://user-images.githubusercontent.com/2251553/97063070-966a9100-1552-11eb-9702-18c8cb4fc944.png)

![image](https://user-images.githubusercontent.com/2251553/97063081-9ec2cc00-1552-11eb-823e-71ef3239cee0.png)

I've removed Jaana per #546.

(We have 160 registered voters at the moment, btw.)

**Comment by SergeyKanzhelev** [comment]
- please check "Do not release results to all voters". Last time we discussed and the feedback was that we do not want to release exact score for every candidate, only a final yes/no results. See [here](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#user-content-results:~:text=Exact%20scores%20for%20each%20candidate%20will%20NOT%20be%20made%20public%20)
- I think "no opinion" should be checked. See [here](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#user-content-vote:~:text=The%20%E2%80%9CNo%20Opinion%E2%80%9D%20option%20will%20be%20enabled)

**Comment by bhs** [comment]
Done and done. Thanks for the keen :eyes:, @SergeyKanzhelev !

**Comment by bhs** [comment]
![image](https://user-images.githubusercontent.com/2251553/97063457-b56a2280-1554-11eb-9973-673aded93746.png)

^^ new settings.

**Comment by SergeyKanzhelev** [comment]
LGTM

**Comment by kateetak** [comment]
LGTM as well. Thanks  @bhs !

**Comment by bhs** [comment]
I've started the CIVS poll and added the (162) registered voters we have via the form.

Voters should see a message ostensibly from me (but actually from CIVS) in the inbox for the email address they designated.

**Comment by bhs** [comment]
We've received an additional 7 registrations from OTel members of standing since the CIVS poll was created... I've added those seven to the CIVS system just now.

**Comment by bhs** [comment]
Ok – it's now past `Oct 28, 12:01am GMT`, so I have ended the CIVS poll. Thanks to everyone who participated!

I will work with @SergeyKanzhelev and @kateetak to confirm the results, and we will announce winners on or before Oct 30 per [the schedule](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#schedule).

**Comment by bhs** [comment]
Recording for next year: I've received some helpful feedback that the timing is confusing with the mix of precise GMT times and plain-old dates (like "October 28"). Point taken. While the long-form version of the schedule is unambiguous, I think we'll be better served by (a) an 11:59pm GMT end time and (b) a little more clarity about timing in the email sent out by CIVS.

PS: If the k8s-sponsored, GH-auth'd ranked-choice voting thing is ready next year, maybe some of this subtlety will be automated for us...

**Comment by bhs** [comment]
Alright! `@here` (oh wait – wrong app), I'm pleased to report the results of the election. Here are the top-4 Condorcet winners per [CIVS](https://civs.cs.cornell.edu/) in alphabetical order:

* Alolita Sharma (@alolita)
* Daniel Dyla (@dyladan)
* Liz Fong-Jones (@lizthegrey)
* Morgan McLean (@mtwo)

Congratulations to all of the above! 👏 👏 👏 👏

**Election stats:** there were 297 members of standing ([see above](https://github.com/open-telemetry/community/issues/488#issuecomment-709513256) for methodology), 180 registered voters, and 128 votes cast. Next year (if we're still using CIVS), we will make efforts to improve conversion in both of the above stages.

**Comment by bhs** [comment]
Okay – given #555's merge, I think this issue can now be closed.

Thanks to everyone for their help, particularly @kateetak and @SergeyKanzhelev with election mechanics!
