### ISSUE TITLE
Publicize Government Committee and Technical Committee meeting notes doc and recordings

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#489]
Link to this doc needs to find a place on our readme: https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8/edit#heading=h.8mwlusiri5yp

Also this repo can point to [TC repo](https://github.com/open-telemetry/opentelemetry-specification#user-content-opentelemetry-specification:~:text=Escalations%20to%20technical%20committee%20may%20be,regular%20meetings%2C%20notes%20are%20held%20here.) that publicizes TC meeting notes document.

Currently we have issues organizing recordings upload for both - TC and GC. Perhaps we can start with no recordings? Let's add a note about it

**Comment by kateetak** [comment]
I can help with this.

About the recordings, @SergeyKanzhelev are you sure you want a note saying that they are available but not categorized in the README?
I've learned over the years that it is usually better not to add any details unless they contain useful information.
Another option could be to add the links to the recordings to the Google doc directly. This could help for all videos published to YouTube while the issues are addressed.

However,  if you think we need to publish that note, let me know.

**Comment by SergeyKanzhelev** [comment]
> I can help with this.
> 
> About the recordings, @SergeyKanzhelev are you sure you want a note saying that they are available but not categorized in the README?
> I've learned over the years that it is usually better not to add any details unless they contain useful information.
> Another option could be to add the links to the recordings to the Google doc directly. This could help for all videos published to YouTube while the issues are addressed.
> 
> However, if you think we need to publish that note, let me know.

agree, let's not mention recordings for now. We are working on it

**Comment by SergeyKanzhelev** [comment]
Now we have a playlist for Governance Committee meetings  https://www.youtube.com/playlist?list=PLVYDBkQ1Tdyzg1CuQgd9mdjwOUYg7ECYR that needs to be publicized as well. Reopening to preserve the context of the work

**Comment by kateetak** [comment]
👋 What do you think if we also update the link in this paragraph to go to the Playlist page (https://www.youtube.com/channel/UCHZDBZTIfdy94xMjMKz-_MA/playlists) instead of the channel Home?
"All meetings happen over Zoom, are recorded and available on YouTube, and have a meeting notes document."

**Comment by SergeyKanzhelev** [comment]
playlists are generally manually-handled. So there will be a lot of uncategorized recordings. So I'd suggest to keep pointing it to the home

**Comment by bhs** [comment]
@SergeyKanzhelev is there anything blocking close on this issue?

**Comment by SergeyKanzhelev** [comment]
nope
