### ISSUE TITLE
REQUEST: New membership for @atoulme

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#490]
### GitHub Username

@atoulme

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @bogdandrutu 
- @anuraaga

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/246
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/359
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/840
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/841
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/255
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/266
Still in progress:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/846
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/875

**Comment by SergeyKanzhelev** [comment]
> @tigrannajaryan
> @bogdandrutu

To ensure corporate diversity, please find a sponsor from other company

**Comment by atoulme** [comment]
@SergeyKanzhelev apologies, I had missed this requirement. I will close this request. Thank you for your prompt response.

**Comment by SergeyKanzhelev** [comment]
@atoulme I would be happy to welcome you in the org. We started enforcing corp diversity and this is the first issue after: https://github.com/open-telemetry/community/issues/465. 

I am sure it wouldn't be a problem to find a sponsor, OpenTelemetry is very welcoming community.

**Comment by atoulme** [comment]
I am reopening this issue. I have asked @anuraaga if he would consider sponsoring me, and he kindly agreed.

**Comment by anuraaga** [comment]
+1 happy to have @atoulme here :)

**Comment by tigrannajaryan** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @atoulme! invite sent.
