### ISSUE TITLE
REQUEST: New membership for amanbrar1999

### ISSUE THREAD

**Issue by amanbrar1999** [open-telemetry/community#492]
GitHub Username

@amanbrar1999

Organization you are requesting membership in

@open-telemetry

Requirements

   [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
   [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
   [✅] I have subscribed to the Gitter channel
   [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
   [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
   [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors

@mtwo
@jmacd

List of contributions to the OpenTelemetry project

* PRs reviewed / authored
    * https://github.com/open-telemetry/opentelemetry-ruby/pull/393
    * https://github.com/open-telemetry/opentelemetry-go-contrib/pull/356
* Issues responded to
    * https://github.com/open-telemetry/opentelemetry-go-contrib/issues/352
    * https://github.com/open-telemetry/opentelemetry-ruby/issues/240
* SIG projects I am involved with
    * https://github.com/open-telemetry/opentelemetry-ruby
    * https://github.com/open-telemetry/opentelemetry-go-contrib

cc - @alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @jmacd to react here. Please make sure you talked to sponsors and they aware of this request

> -[x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by jmacd** [comment]
Approved.

**Comment by mtwo** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @amanbrar1999!
