### ISSUE TITLE
REQUEST: New membership for Eunice98k

### ISSUE THREAD

**Issue by eunice98k** [open-telemetry/community#493]
GitHub Username

@eunice98k

Organization you are requesting membership in

@open-telemetry

Requirements

   [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
   [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
   [✅] I have subscribed to the Gitter channel
   [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
   [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
   [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors

@mtwo
@jmacd

List of contributions to the OpenTelemetry project

PRs reviewed / authored

- [Java PR 1661: Update Sampling result names](https://github.com/open-telemetry/opentelemetry-java/pull/1661)

- [Ruby PR 383: Documentation for Concurrent Ruby](https://github.com/open-telemetry/opentelemetry-ruby/pull/383)

SIG projects I am involved with

- [Ruby](https://github.com/open-telemetry/opentelemetry-ruby)

- [Java](https://github.com/open-telemetry/opentelemetry-java)

cc - @alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @jmacd to react here. Please make sure you talked to sponsors and they aware of this request

> -[x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by jmacd** [comment]
Approved.

**Comment by mtwo** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @eunice98k!
