### ISSUE TITLE
REQUEST: New membership for wilguo

### ISSUE THREAD

**Issue by wilguo** [open-telemetry/community#494]
### REQUEST: New membership for wilguo

**@wilguo**

### Organization you are requesting membership in

**@open-telemetry**

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mtwo
- @jmacd

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-python/pull/1124
  - https://github.com/open-telemetry/opentelemetry-python/pull/1141
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-python
  - https://github.com/open-telemetry/opentelemetry-python-contrib
  - https://github.com/open-telemetry/opentelemetry-go

cc - @alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @jmacd to react here. Please make sure you talked to sponsors and they aware of this request

> -[x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by jmacd** [comment]
Approved.

**Comment by mtwo** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @wilguo!
