### ISSUE TITLE
REQUEST: New membership for KKelvinLo

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/community#495]
**GitHub Username**

@KKelvinLo

**Organization you are requesting membership in**

@open-telemetry

**Requirements**

   [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
   [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
   [✅] I have subscribed to the Gitter channel
   [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
   [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
   [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Sponsors**

* [@jmacd](https://github.com/jmacd)
* [@anuraaga](https://github.com/anuraaga)

**List of contributions to the OpenTelemetry project**

**PRs reviewed / authored**

* https://github.com/open-o11y/opentelemetry-go-contrib/pull/114
* https://github.com/open-telemetry/opentelemetry-ruby/pull/389

**Issues Responded To:**

* https://github.com/open-telemetry/opentelemetry-go-contrib/issues/239
* https://github.com/open-telemetry/opentelemetry-ruby/issues/239

**SIG projects I am involved with**

* JS
* Metrics
* JS-contrib

cc:- @alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @jmacd to react here. Please make sure you talked to sponsors and they aware of this request

> -[x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by jmacd** [comment]
I approve. (BTW, these interns did check with me first! These requests landed in my "unimportant" folder, working on that...)

**Comment by KKelvinLo** [comment]
sponsor: @anuraaga

**Comment by alolita** [comment]
Hi @SergeyKanzhelev - yes our interns and I did reach out to the sponsors mentioned before filing for membership. @jmacd @anuraaga have approved.

**Comment by SergeyKanzhelev** [comment]
Welcome, @KKelvinLo!
