### ISSUE TITLE
REQUEST: New membership for ahlaw

### ISSUE THREAD

**Issue by ahlaw** [open-telemetry/community#496]
### GitHub Username

@ahlaw 

### Organization you are requesting membership in

@open-telemetry 

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@mtwo 
@jmacd 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-python/pull/1121
  - https://github.com/open-telemetry/opentelemetry-python/pull/1136
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-python

cc - @alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @jmacd to react here. Please make sure you talked to sponsors and they aware of this request

> -[x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by jmacd** [comment]
I approve. Thanks @ahlaw

**Comment by mtwo** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @ahlaw!
