### ISSUE TITLE
REQUEST: New membership for xukaren

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/community#498]
### GitHub Username

e.g. @xukaren

### Organization you are requesting membership in

e.g. @open-telemetry

### Requirements

- [ x ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ x ] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ x ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang 
- @jmacd 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored:
     * Ruby PR 235: https://github.com/open-telemetry/opentelemetry-ruby/pull/387 (Merged)
     * PHP PR 176:  https://github.com/open-telemetry/opentelemetry-php/pull/177 (Merged)
     * CPP PR 336: https://github.com/open-telemetry/opentelemetry-cpp/pull/336 (Merged) 

- Issues responded to:
     * https://github.com/open-telemetry/opentelemetry-ruby/issues/109

- SIG projects I am involved with
     * C++ SIG Meeting 
     * Go SIG Meeting 

@alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @jmacd to react here. Please make sure you talked to sponsors and they aware of this request

> -[x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by jmacd** [comment]
I support this membership. Thanks @xukaren

**Comment by alolita** [comment]
Hi @SergeyKanzhelev @jmacd and @reyang have approved our intern @xukaren 's membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @xukaren!
