### ISSUE TITLE
REQUEST: New membership for MarkSeufert

### ISSUE THREAD

**Issue by MarkSeufert** [open-telemetry/community#499]
### GitHub Username

@markseufert

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [✅] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
- [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mtwo
- @dyladan

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-ruby/pull/390 (merged)
  - https://github.com/open-telemetry/opentelemetry-js/pull/1550 (discussing changes with reviewers before merge)
  - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/210 (approved to merge)

- Issues created
  - https://github.com/open-telemetry/opentelemetry-js-contrib/issues/207

- SIG projects I am involved with
  - C++ SIG Meeting
  - Metrics SIG Meeting

CC - @alolita

**Comment by SergeyKanzhelev** [comment]
I'm waiting on @mtwo @dyladan to react here. Please make sure you talked to sponsors and they aware of this request

> I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by alolita** [comment]
Hi @SergeyKanzhelev - @MarkSeufert our intern and I have both reached out to @reyang @anuraaga @mwto to sponsor his membership. @reyang @anuraaga have responded and approved.

**Comment by SergeyKanzhelev** [comment]
Perfect. I just needed some form of confirmation from sponsors on the issue. I’ll review all the requests later tonight

**Comment by dyladan** [comment]
I have no knowledge of this application. Please make sure you raise the issue privately with your potential sponsors before creating the public issue.

It looks to me like you reached out to @anuraaga and @mtwo, but copied an old application as a template which already had my name on it maybe?

In any case, I am happy to be your sponsor if you need one as you have been working on the JS repo.

**Comment by MarkSeufert** [comment]
Hey Danial, 
I used you on purpose since you are the reviewer of one of my PRs on the JS repo. I send you a gitter message a few days ago about using you as my sponsor, but I know you're busy so I think you haven't seen it yet. 

Thanks!

**Comment by SergeyKanzhelev** [comment]
Welcome, @MarkSeufert!
