### ISSUE TITLE
REQUEST: New membership for shovnik

### ISSUE THREAD

**Issue by shovnik** [open-telemetry/community#503]
GitHub Username
@shovnik

Organization you are requesting membership in
@open-telemetry

Requirements
   [✅] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
   [✅] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
   [✅] I have subscribed to the Gitter channel
   [✅] I am actively contributing to 1 or more OpenTelemetry subprojects
   [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
   [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
@mtwo
@jmacd

List of contributions to the OpenTelemetry Project
* PRs reviewed/authored
    * https://github.com/open-telemetry/opentelemetry-ruby/pull/386 (https://github.com/open-telemetry/opentelemetry-ruby/pull/394)
    * https://github.com/open-telemetry/opentelemetry-php/pull/182
* Issues responded to
    * https://github.com/open-telemetry/opentelemetry-ruby/issues/238
    * https://github.com/open-telemetry/opentelemetry-python/issues/1001
    * https://github.com/open-telemetry/opentelemetry-php/issues/86
* SIG projects I am involved with
    * https://github.com/open-telemetry/opentelemetry-specification
    * https://github.com/open-telemetry/opentelemetry-python
CC - @alolitas

**Comment by mtwo** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @shovnik!

**Comment by jmacd** [comment]
LGTM
