### ISSUE TITLE
Github repository for Helm charts

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/community#504]
We are adding a helm chart for opentelemetry-collector deployment in kubernetes environment. There is a draft PR of the initial version in contrib repo https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1026. It would be great to put it in its own repo right in the beginning. Having a repo will allow us to easily setup helm specific CI pipeline using Github Actions.

The repo can be called `open-telemetry/helm-charts`. 

Another ask as the next step would be to have a helm repository to host helm releases somewhere under opentelemetry.io domain. I can a separate ticket for that once this one is resolved.

**Comment by SergeyKanzhelev** [comment]
Would `open-telemetry/opentelemetry-helm-charts` work? Should permissions be copied from the opentelemetry-collector-contrib?

For the DNS and hosting - let's have a separate issue 

CC: @open-telemetry/collector-contrib-maintainer  @open-telemetry/collector-maintainers

**Comment by dmitryax** [comment]
I'm good with `open-telemetry/opentelemetry-helm-charts`, and we can start with the same permissions as set in opentelemetry-collector-contrib. Let's see what others think.

**Comment by tigrannajaryan** [comment]
@dmitryax do we intend to have other Otel Helm charts or this is only for the Collector? If it is only for the Collector we may want to reflect that in the repo name.

@SergeyKanzhelev Yes, copying collector-contrib permissions is a good starting point.

**Comment by dmitryax** [comment]
> @dmitryax do we intend to have other Otel Helm charts or this is only for the Collector? If it is only for the Collector we may want to reflect that in the repo name.

It's only opentelemetry-collector for now, but I think it would be good to have a generic name in case we ever have more k8s components in opentelemetry.

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan actually you are an organization owner now as a member of TC. Would you like to create it yourself following https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md? Let me know, I can definitely do it if needed

**Comment by dmitryax** [comment]
@tigrannajaryan also could you please give me permissions to merge in that repo at least in the beginning?

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev sure, I'll take care of it.

**Comment by tigrannajaryan** [comment]
@dmitryax https://github.com/open-telemetry/opentelemetry-helm-charts created. You are an admin for now so that you can setup everything as needed.

I am closing this issue, further refinements and decision on who gets what permissions can be discussed in the new repo.

**Comment by SergeyKanzhelev** [comment]
> @tigrannajaryan also could you please give me permissions to merge in that repo at least in the beginning?

Please make sure to NOT merge directly. All code should go thru PR & CLA process

**Comment by tigrannajaryan** [comment]
> > @tigrannajaryan also could you please give me permissions to merge in that repo at least in the beginning?
> 
> Please make sure to NOT merge directly. All code should go thru PR & CLA process

@dmitryax FYI ^^^.

**Comment by dmitryax** [comment]
> @dmitryax https://github.com/open-telemetry/opentelemetry-helm-charts created. You are an admin for now so that you can setup everything as needed.
> 
> I am closing this issue, further refinements and decision on who gets what permissions can be discussed in the new repo.

Thank you Tigran!
