### ISSUE TITLE
REQUEST: New membership for @debugthings

### ISSUE THREAD

**Issue by debugthings** [open-telemetry/community#507]
### GitHub Username

@debugthings

### Organization you are requesting membership in

@open-telemetry
opentelemetry-dotnet-instrumentation

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Mikhail-msft
- @pjanotti

### List of contributions to the OpenTelemetry project

- None, yet, still bootstrapping with opentelemetry-dotnet-instrumentation

**Comment by macrogreg** [comment]
LGTM

**Comment by SergeyKanzhelev** [comment]
Welcome, @debugthings!
