### ISSUE TITLE
REQUEST: New membership for @huikang

### ISSUE THREAD

**Issue by huikang** [open-telemetry/community#509]
### GitHub Username

@huikang

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@MrAlias
@Aneurysm9

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-go/pull/1208
https://github.com/open-telemetry/opentelemetry-go/pull/397
https://github.com/open-telemetry/opentelemetry-go/pull/415
https://github.com/open-telemetry/opentelemetry-go/pull/1186
https://github.com/open-telemetry/opentelemetry-go/pull/1198
https://github.com/open-telemetry/opentelemetry-collector/pull/1805
https://github.com/open-telemetry/opentelemetry-collector/pull/524

- Issues responded to
Will get more involved in responding to issues.

- SIG projects I am involved with
opentelemetry-go

**Comment by Aneurysm9** [comment]
+1

**Comment by Oberon00** [comment]
Please update the issue title.

**Comment by huikang** [comment]
> Please update the issue title.

Done. Thanks.

**Comment by SergeyKanzhelev** [comment]
Welcome, @huikang!
