### ISSUE TITLE
REQUEST: New membership for frigus02

### ISSUE THREAD

**Issue by frigus02** [open-telemetry/community#510]
### GitHub Username

@frigus02

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jtescher 
- @TommyCpp

### List of contributions to the OpenTelemetry project

- [PRs reviewed / authored](https://github.com/search?q=org%3Aopen-telemetry+author%3Afrigus02&type=Commits)
- [Issues responded to](https://github.com/search?q=org%3Aopen-telemetry+author%3Afrigus02&type=Issues)
- SIG projects I am involved with: https://github.com/open-telemetry/opentelemetry-rust

**Comment by SergeyKanzhelev** [comment]
Welcome, @frigus02!

**Comment by jtescher** [comment]
@SergeyKanzhelev thanks, can you add @frigus02 to @open-telemetry/rust-approvers  as well?

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev thanks, can you add @frigus02 to @open-telemetry/rust-approvers as well?

It is self service. All the power is yours to add approvers and maintainers. You are a maintainer for both teams.

![Uploading image.png…]()

**Comment by jtescher** [comment]
Ok great, thanks @SergeyKanzhelev
