### ISSUE TITLE
Youtube uploader tool: governance meetings have a title and should only be prepended with the date

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#515]
In the tool, need to make sure not to rename Governance Committee meetings as they are named already. Just prepend with the date

![image](https://user-images.githubusercontent.com/9950081/94842193-f47edb00-03cf-11eb-8676-1eea074bcd96.png)

CC: @eddynaka

**Comment by SergeyKanzhelev** [comment]
screenshot is from the test recording

**Comment by eddynaka** [comment]
ok! I will create an update to the tool and add that string as const! thanks for the heads up

**Comment by eddynaka** [comment]
If we have this condition:
- name starts with: Governance Committee
- visibility: private
- time: < 3 minutes

Should we exclude?

**Comment by SergeyKanzhelev** [comment]
edited this one manually:

![image](https://user-images.githubusercontent.com/9950081/94844613-5bea5a00-03d3-11eb-9aff-ef914149c1d2.png)



> If we have this condition:
> 
> * name starts with: Governance Committee
> * visibility: private
> * time: < 3 minutes
> 
> Should we exclude?

Yes! And potentially - make it easy configurable so we can add more exceptions in future

**Comment by SergeyKanzhelev** [comment]
please make sure to add a date in front of the name. It will be helpful browsing-wise
