### ISSUE TITLE
CNCF Community Awards nominations

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#518]
@open-telemetry/governance-committee any idea on good candidates for nominations below? Anybody wants to take an action item to bring this to maintainers meeting?

- [CNCF Top Ambassador](https://forms.gle/uvm6994aGXPD2Kyk9): A champion for the cloud native space, this individual helps spread awareness of the
CNCF (and its incubated projects). The CNCF Ambassador leverages multiple platforms, both online as well as speaking engagements, driving interest and excitement around the project.
- [CNCF Top Committer](https://forms.gle/QjEZpjU1qen4UF2c9): This will recognize excellence in technical contributions to CNCF and its projects.
The CNCF Top Committer has made key commits to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.
- [CNCF Chop Wood Carry Water](https://forms.gle/TGeefrKMtiAaEFfT7): This is given to a community member who helps behind the scenes, dedicating
countless hours of their time to open source projects + completing often thankless tasks for the ecosystem’s benefit. The winner of this award will be chosen by the TOC and CNCF Staff.

Nominations will open today, and close on October 16nd. We'll be announcing the
awards at KubeCon + CloudNativeCon Virtual North America. Voting (open from October 19 through October 26th) will be performed using the CIVS tool, using emails from the CNCF database for the following groups:

[CNCF Ambassadors](https://www.cncf.io/people/ambassadors/) are eligible to vote for the Top Ambassador
[CNCF Maintainers](https://docs.google.com/spreadsheets/d/1Pr8cyp8RLrNGx9WBAgQvBzUUmqyOv69R7QAFKhacJEM/edit) are eligible to vote for the Top Committer

**Comment by bogdandrutu** [comment]
This is outdated :)
