### ISSUE TITLE
REQUEST: New membership for @awiede

### ISSUE THREAD

**Issue by awiede** [open-telemetry/community#522]
### GitHub Username

@awiede

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jtescher 
- @TommyCpp

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - open-telemetry/opentelemetry-rust#173
  - open-telemetry/opentelemetry-rust#175
  - open-telemetry/opentelemetry-rust#200
  - open-telemetry/opentelemetry-rust#201
  - open-telemetry/opentelemetry-rust#202
  - open-telemetry/opentelemetry-rust#203
  - open-telemetry/opentelemetry-rust#206
  - open-telemetry/opentelemetry-rust#217
  - open-telemetry/opentelemetry-rust#244
- Issues responded to
  - open-telemetry/opentelemetry-rust#161
  - open-telemetry/opentelemetry-rust#194
  - open-telemetry/opentelemetry-rust#198
  - open-telemetry/opentelemetry-rust#211
  - open-telemetry/opentelemetry-rust#235
- SIG projects I am involved with
  - [opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust)

**Comment by SergeyKanzhelev** [comment]
Welcome, @awiede! Invite sent
