### ISSUE TITLE
Can't add a triager team to opentelemetry-php repo

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#525]
I was unable to add the triager team to the opentelemetry-php repo:

https://github.com/orgs/open-telemetry/teams/php-triagers/repositories.

I believe I don't have enough admin privilege to accomplish this task.

cc:\ @SergeyKanzhelev @jodeev

**Comment by tigrannajaryan** [comment]
I have https://github.com/orgs/open-telemetry/teams/php-triagers a Triage role on https://github.com/open-telemetry/opentelemetry-php

**Comment by jodeev** [comment]
@tigrannajaryan maybe the triager permissions are not set properly? For instance, I still do not have permissions to open a new project or assign Issues

**Comment by tigrannajaryan** [comment]
![image](https://user-images.githubusercontent.com/4194920/95612085-cc772380-0a30-11eb-988f-c3fad5bf77cf.png)

**Comment by tigrannajaryan** [comment]
![image](https://user-images.githubusercontent.com/4194920/95612135-e153b700-0a30-11eb-9b21-59dd934c236d.png)

**Comment by bobstrecansky** [comment]
@tigrannajaryan - Jodee is still unable to Triage our project.  Do you see anything else that could be blocking her from doing so?  We're both stumped!

**Comment by SergeyKanzhelev** [comment]
double checked, everything looks fine. Hi @jodeev! What are you trying to do specifically? Here is the list of permissions of Triage role: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level

**Comment by SergeyKanzhelev** [comment]
Let me know if this is blocking and I can make triager team "write" permissions to unblock.

**Comment by jodeev** [comment]
Hi @SergeyKanzhelev !  I'd like to be able to add cards to existing projects, create milestones, create new projects .... currently, I can't do any of those things.

**Comment by SergeyKanzhelev** [comment]
Oh, I see. You need a projects access, not the repository access. Projects are org-wide, are they? I never done it before, how many projects do you need?

**Comment by SergeyKanzhelev** [comment]
Couldnt find documentation on permissions required. Changed triager role to "Write". Does it work now?

**Comment by jodeev** [comment]
It does, many thanks!  Projects can be org-wide, but the CPP and PHP SIGs are using them just within their repos.
