### ISSUE TITLE
Tracking issue for RC + GA announcements

### ISSUE THREAD

**Issue by mtwo** [open-telemetry/community#526]
_For RC and GA process / tracking, please join the maintainers meeting or refer to the [GA planning blog post](https://medium.com/opentelemetry/ga-planning-f0f6d7b5302)._

This issue will track our announcement plans for the upcoming GA release candidates and final GA release. We are currently putting together plans for the release candidate, and we'll begin strategizing the GA announcement process after the RC announcement is complete.

### RC Announcement Plan
OpenTelemetry will have several release candidates:

1. The tracing specification release candidate (spec lock), which will occur within the next two weeks. We'll determine the date at next Monday's maintainers' meeting.
2. Tracing release candidates for each of the SDKs, Collector, and auto-instrumentation components. Some components may publish multiple release candidates prior to the GA.
3. The metrics specification release candidate (spec lock). We'll determine the date after the tracing specification release candidate is published.
4. Metrics release candidates for each of the SDKs, Collector, and auto-instrumentation components (which at this point will already include tracing RC code). Some components may publish multiple release candidates prior to the GA.

We'll follow a process similar to the beta announcement, where we publish a story on the OpenTelemetry Medium blog once major RC milestones occur, including:

- The tracing specification RC (blog post being drafted now)
- The metrics specification RC
- Various component RCs (each may attract less visibility than the spec announcements, but they are worth posting and some contributors may still wish to cross-post them)

Each of these blog posts will detail the following:

- The status of the spec and implementations
- What's now frozen, what isn't
- What this means (instrumentation providers can integrate with the RC APIs)
- Any exceptions to the freeze 
- What's next

### GA Announcement Plan
We'll try to schedule this around Kubecon and the OpenTelemetry community day if we're able to meet our development goals by then. Not much planning has yet been done around the announcement, but I'm anticipating the following:

- Announcement about how we'll handle breaking changes and versioning post-GA (we still need to determine how this will work)
- Development update blog posts as we approach the release date
- A large panel discussion at the OpenTelemetry community day that includes maintainers, the governance committee, and the drivers of the release process (Andrew)
- A cross-posted announcement blog post
- Followup blog posts about using OpenTelemetry, customer stories, guides, etc.
- Analyst and press interviews that we'll need to coordinate as we get closer to the GA date
- Pre-shared quotes about the project from contributors that can be used in subsequent announcements

Here's a proposed outline for the GA announcement blog post:
- Extremely succinct description of OpenTelemetry and the value that it brings to readers
- What it means to be GA (end-users and vendors can depend on OpenTelemetry)
- What components are GA
- Where OpenTelemetry is supported (which Cloud Providers, which backends, highlight certain instrumentation, etc.)
- Link to getting started guides and documentation
- Who and which organizations were involved

**Comment by bhs** [comment]
> we'll begin strategizing the GA announcement process after the RC announcement is complete.

IMO we would be well-served by some light planning for the GA announcement, which *should* be "bigger" than the RC announcements. I'm particularly concerned that those who aren't following the project closely will simply misunderstand what the various announcements actually mean.

I guess I would propose that we write the 5-bullet summary version of each of the major announcements we're planning (independent of dates) just to make sure we have our stories straight, and that a non-OTel-expert will be able to tell them apart. :)  Does that make sense? (I'm also happy to carry water on this, but want to get alignment on whether we *want* these summaries first)

**Comment by mtwo** [comment]
> I guess I would propose that we write the 5-bullet summary version of each of the major announcements we're planning (independent of dates) just to make sure we have our stories straight, and that a non-OTel-expert will be able to tell them apart.

Good call, I'll get started on this today

**Comment by cxhansen** [comment]
Thanks for the clarification and detail, @mtwo! I would also be happy to chop wood on this. I don't think it's too early to draft the blog post so that we have plenty of time to refine, and use it in the spirit of Amazon's _working backwards_.

Also, I suggest that the GA blog post also include:
- What's Next (preview of Logs, other work that was pushed to post-GA)
- A call to action. Likely pointing to getting started documentation.

**Comment by alolita** [comment]
@mtwo Thanks for starting this thread. Look forward to discussing the upcoming RC steps and release dates locked in. 

Once the RC blog post is completed, then would be great to start the GA post and add detail as milestones get finalized.

**Comment by trask** [comment]
@mtwo is it ok to close this? thx!

**Comment by mtwo** [comment]
Yep! Thanks for clearing through all of these!
