### ISSUE TITLE
REQUEST: New membership for @cxhansen

### ISSUE THREAD

**Issue by cxhansen** [open-telemetry/community#527]
### GitHub Username

@cxhansen

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias
- @jkwatson

### List of contributions to the OpenTelemetry project

- Supported the inception of OpenTelemetry as a member of the “OpenConsensus” meeting in October 2018.
- Advocated for OpenTelemetry and open standards at conferences such as Monitorama
- Advocated for New Relic’s involvement in OpenTelemetry
- Occasionally dropped in and contributed to the conversation in the Metrics and Errors SIGs and Maintainers meeting
- Commented and thumb-voted on issues and PRs including [this](https://github.com/open-telemetry/opentelemetry-specification/pull/810)

**Comment by SergeyKanzhelev** [comment]
Welcome, @cxhansen! Invite sent

**Comment by cxhansen** [comment]
Thanks!
