### ISSUE TITLE
REQUEST: New membership for jsuereth

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/community#528]
### GitHub Username

@jsuereth

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang
- @bogdandrutu 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/358
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/331
- SIG projects I am involved with
  - C++
  - Communications (pending, sent first request to discuss)
  - Specification (mostly listening so far)

**Comment by reyang** [comment]
Welcome @jsuereth!

**Comment by bogdandrutu** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @jsuereth! Invite sent.
