### ISSUE TITLE
Ensure all current "Members of Standing" are aware of the 2020 GC Election registration process

### ISSUE THREAD

**Issue by bhs** [open-telemetry/community#543]
Per #488, and particularly [this comment](https://github.com/open-telemetry/community/issues/488#issuecomment-709513256), we need to make a best effort to get the attention of all known [members of standing](https://github.com/open-telemetry/community/blob/master/governance-charter.md#members-of-standing).

I'm going to do that the old-fashioned way by `@`-mentioning all of them here. Before I do, a brief preamble:

> As a [member of standing](https://github.com/open-telemetry/community/blob/master/governance-charter.md#members-of-standing), you are entitled to vote in the OpenTelemetry 2020 Governance Committee Election. Before you can do so, though, you must register by filling out this form:
>
>   [OpenTelemetry Voter Registration Form](https://forms.gle/X4XjnJsVyNauEq9U7)
>
> **If you don't explicitly register, you will not receive the invitation to vote (via the [CIVS](https://civs.cs.cornell.edu/) system) later this month.**
>
> There are four seats open in the election this year. You can read about the candidates here:
>
>    [2020 OpenTelemetry Governance Committee Candidates](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-candidates.md)
>
> If you'd like to learn more about the election, please read [this document](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md), and if you have questions or concerns, please raise them on [this GitHub issue](https://github.com/open-telemetry/community/issues/488).
>
> We thank you in advance for your participation in this important process!
> – The 2020 OTel Election Committee

Without further ado, here is a list of all current members of standing, in alphabetical order by GitHub handle: @0x4b, @aabmass, @adriancole, @ahlaw, @alanwest, @alexeyzimarev, @alexvaluyskiy, @alolita, @AndrewAXue, @AndrewGrachov, @andrewhsu, @Aneurysm9, @ankit-bhargava, @annanay25, @anniefu, @anuraaga, @aravinsiva, @arminru, @artem-prozorov, @astorm, @asuresh4, @atoulme, @austinlparker, @awiede, @axw, @beniamin, @bg451, @Bhargavamacha, @bhs, @BlumAmir, @blumamir, @bobstrecansky, @bogdandrutu, @Brandon-Kimberly, @bruno-garcia, @bryannaegele, @c24t, @carlosalberto, @carolinee21, @ccaraman, @chris-smith-zocdoc, @christopher-taormina-zocdoc, @churanchen, @cijothomas, @clsung, @cnnradams, @code-haven, @CodeBlanch, @codeboten, @codesmith14, @connorlindsey, @CunjunWang, @cyrille-leclerc, @czs1993, @danielkhan, @darwhs, @davebarda, @davidwitten, @DazedDreamer, @dazuma, @dbarbashov, @dengliming, @devinsba, @dgzlopes, @dinooliva, @djaglowski, @dmitryax, @dneray, @DotSpy, @draffensperger, @duonoid, @dyladan, @ecourreges-orange, @eddynaka, @EdZou, @ejsmith, @elskwid, @eran-levy, @ercl, @erichsueh3, @ericmustin, @evantorrie, @fbogsany, @ferd, @ferhatelmas, @ffe4, @fhwang, @flands, @Flarna, @FrankSpitulski, @freeformz, @freeformzSFDC, @frigus02, @g-easy, @garthk, @genebean, @gfuller1, @godev-learner, @grantbdev, @hauleth, @hectorhdzg, @hencrice, @heyams, @HiveTraum, @Hongbo-Miao, @hossain-rayhan, @HudsonHumphries, @huikang, @huntc, @huyan0, @ibawt, @IlyaKobelevskiy, @imavroukakis, @iNikem, @iredelmeier, @jajanet, @jakemalachowski, @james-bebbington, @JamesNK, @jan25, @jarebudev, @JasonXZLiu, @jchengsfx, @jeffalder, @JingboWangGoogle, @jkwatson, @jmacd, @joe-elliott, @johananl, @johnbley, @jonahrosenblum, @joshuahlang, @jpkrohling, @jrcamp, @jtescher, @justinfoote, @Kanwaldeep, @katzchang, @kbrockhoff, @keitwb, @kenfinnigan, @kichristensen, @kintel, @kmanghat, @krnowak, @kubawach, @lalitb, @legendecas, @liamawhite, @lizthegrey, @lkmfwe, @lmolkova, @longility, @lukasz-pyrzyk, @lupengamzn, @lykkin, @lzchen, @mabdinur, @macrogreg, @majorgreys, @malafeev, @mar-kolya, @mariojonke, @markwolff, @marwan-at-work, @mat-rumian, @matej-g, @mateuszrzeszutek, @mauriciovasquezbernal, @maxgolov, @mayurkale22, @mbakalov, @michaelgoin, @michaelorr, @MikeGoldsmith, @MitchellDumovic, @morigs, @morrisonlevi, @MrAlias, @mtwo, @mujtaba-ahmed12, @mwear, @mwlang, @mx-psi, @mxiamxia, @nacho-undefinedlabs, @nachoBonafonte, @nadiaciobanu, @naseemkullah, @NathanielRN, @nenad, @nholbrook, @Nicolas-MacBeth, @nilebox, @nirsky, @nmbro, @noahfalk, @nstawski, @obecny, @Oberon00, @objectiser, @ocelotl, @ocervell, @OlivierAlbertini, @oulin-coder, @owais, @paivagustavo, @pauldraper, @paulosman, @pavolloffay, @pcwiese, @PettitWesley, @pjanotti, @pmcollins, @pmm-sumo, @prondubuisi, @prydin, @pyohannes, @rajkumar-rangaraj, @rakyll, @randomanderson, @RashmiRam, @reggiemcdonald, @reyang, @rezakrimi, @rghetia, @richardstartin, @rmfitzpatrick, @rnburn, @robertlaurin, @romil-punetha, @romilpunetha, @rubenvp8510, @safris, @samvaity, @satac2, @saturnism, @seh, @SergeyKanzhelev, @SevaSafris, @sfriberg, @shaochengwang, @shengxil, @shirou, @shivkanya9146, @shovnik, @siyopao, @sjbrunst, @Skeen, @sleighzy, @snehilchopra, @sonofachamp, @sribalakumar, @srjames90, @stefanprisca, @svrnm, @SychevIgor, @tarekgh, @tedpennings, @tedsuo, @tensorchen, @thisthat, @ThomsonTan, @Tianlin-Zhao, @tigrannajaryan, @TommyCpp, @toumorokoshi, @trask, @tsloughter, @tylerbenson, @udekel, @vikrambe, @VineethReddy02, @vmarchaud, @vmihailenco, @wangzlei, @wilguo, @williamhu99, @wingyplus, @wtong98, @wtyanan, @xiang17, @xiao-lix, @XSAM, @xukaren, @YANYZP, @yatender-oktalk, @ymotongpoo, @youngbupark, @yue9944882, @yurishkuro, @yyyogev, @z1c0, @zeitlinger, @zenmoto, @ZhaoTianlin990121, @ziqizh

Please vote! :)

**Comment by bhs** [comment]
Hmm, that didn't seem to "work" – GitHub only recognized the first 50. I'll batch them, I guess. 😭

**Comment by bhs** [comment]
Please read the post at the top of this issue, @CunjunWang @cyrille-leclerc @czs1993 @danielkhan @darwhs @davebarda @davidwitten @DazedDreamer @dazuma @dbarbashov @dengliming @devinsba @dgzlopes @dinooliva @djaglowski @dmitryax @dneray @DotSpy @draffensperger @duonoid @dyladan @ecourreges-orange @eddynaka @EdZou @ejsmith @elskwid @eran-levy @ercl @erichsueh3 @ericmustin @evantorrie @fbogsany @ferd @ferhatelmas @ffe4 @fhwang @flands @Flarna @FrankSpitulski @freeformz @freeformzSFDC @frigus02 @g-easy @garthk @genebean @gfuller1 @godev-learner @grantbdev @hauleth @hectorhdzg

**Comment by bhs** [comment]
Please read the post at the top of this issue, @hencrice @heyams @HiveTraum @Hongbo-Miao @hossain-rayhan @HudsonHumphries @huikang @huntc @huyan0 @ibawt @IlyaKobelevskiy @imavroukakis @iNikem @iredelmeier @jajanet @jakemalachowski @james-bebbington @JamesNK @jan25 @jarebudev @JasonXZLiu @jchengsfx @jeffalder @JingboWangGoogle @jkwatson @jmacd @joe-elliott @johananl @johnbley @jonahrosenblum @joshuahlang @jpkrohling @jrcamp @jtescher @justinfoote @Kanwaldeep @katzchang @kbrockhoff @keitwb @kenfinnigan @kichristensen @kintel @kmanghat @krnowak @kubawach @lalitb @legendecas @liamawhite @lizthegrey @lkmfwe

**Comment by bhs** [comment]
Please read the post at the top of this issue, @lmolkova @longility @lukasz-pyrzyk @lupengamzn @lykkin @lzchen @mabdinur @macrogreg @majorgreys @malafeev @mar-kolya @mariojonke @markwolff @marwan-at-work @mat-rumian @matej-g @mateuszrzeszutek @mauriciovasquezbernal @maxgolov @mayurkale22 @mbakalov @michaelgoin @michaelorr @MikeGoldsmith @MitchellDumovic @morigs @morrisonlevi @MrAlias @mtwo @mujtaba-ahmed12 @mwear @mwlang @mx-psi @mxiamxia @nacho-undefinedlabs @nachoBonafonte @nadiaciobanu @naseemkullah @NathanielRN @nenad @nholbrook @Nicolas-MacBeth @nilebox @nirsky @nmbro @noahfalk @nstawski @obecny @Oberon00 @objectiser

**Comment by bhs** [comment]
Please read the post at the top of this issue, @ocelotl @ocervell @OlivierAlbertini @oulin-coder @owais @paivagustavo @pauldraper @paulosman @pavolloffay @pcwiese @PettitWesley @pjanotti @pmcollins @pmm-sumo @prondubuisi @prydin @pyohannes @rajkumar-rangaraj @rakyll @randomanderson @RashmiRam @reggiemcdonald @reyang @rezakrimi @rghetia @richardstartin @rmfitzpatrick @rnburn @robertlaurin @romil-punetha @romilpunetha @rubenvp8510 @safris @samvaity @satac2 @saturnism @seh @SergeyKanzhelev @SevaSafris @sfriberg @shaochengwang @shengxil @shirou @shivkanya9146 @shovnik @siyopao @sjbrunst @Skeen @sleighzy @snehilchopra

**Comment by bhs** [comment]
Please read the post at the top of this issue, @sonofachamp @sribalakumar @srjames90 @stefanprisca @svrnm @SychevIgor @tarekgh @tedpennings @tedsuo @tensorchen @thisthat @ThomsonTan @Tianlin-Zhao @tigrannajaryan @TommyCpp @toumorokoshi @trask @tsloughter @tylerbenson @udekel @vikrambe @VineethReddy02 @vmarchaud @vmihailenco @wangzlei @wilguo @williamhu99 @wingyplus @wtong98 @wtyanan @xiang17 @xiao-lix @XSAM @xukaren @YANYZP @yatender-oktalk @ymotongpoo @youngbupark @yue9944882 @yurishkuro @yyyogev @z1c0 @zeitlinger @zenmoto @ZhaoTianlin990121 @ziqizh

**Comment by bhs** [comment]
😅 ... I guess that worked? Sorry for the spam. I will close this issue when the registration period is over next week.

**Comment by adriancole** [comment]
I'm not sure how the "members of standing" list was created, but I'd like to be removed from it.

**Comment by bhs** [comment]
@adriancole, re:

>I'm not sure how the "members of standing" list was created, but I'd like to be removed from it.

The set of "members of standing" for this election was populated programmatically with the query here: https://github.com/open-telemetry/community/issues/488#issuecomment-709513256

Aside from this issue and the email that preceded it by a few minutes, there is no other "list" to be removed from.

**Comment by astorm** [comment]
@bhs What's the call to action here?  I followed the links and started reading, got a bit of a headache, and decided I'd just ask instead :) 

What are you asking ~members of standing~ people who have contributed in the past year to do?

**Comment by bhs** [comment]
@astorm TL;DR **[fill out this form](https://forms.gle/X4XjnJsVyNauEq9U7)**.

(BTW, the definition for "members of standing" is a bit more elaborate than "having contributed in the past year," for better or worse... the formula/query is borrowed from k8s and can be found in the comment linked in the message above yours in this thread)

**Comment by astorm** [comment]
> BTW, the definition for "members of standing" is a bit more elaborate than "having contributed in the past year,"

@bhs -- hopefully this will be taken in the light hearted yet snarky manner in which it's intended, but 

> the formula/query is borrowed from k8s and can be found in the comment linked in the message above yours in this thread)

I followed [that link](https://github.com/open-telemetry/community/issues/488#issuecomment-709513256)

and found a ~cryptic~ terse shell script

    ./contributors/contributors_with_n_dtrange.sh opentelemetry "now()-'1 year'::interval" 'now()' 20
    
Above that shell script was a [link to an equally ~cryptic~ terse repository  ](https://github.com/cncf/devstats-reports#contributors-having-at-least-n) with a bunch of shell scripts and SQL queries and a mention of a _DevStats databases_ but no definition of what the DevStats databases are.

I did find [that shell script though](https://github.com/cncf/devstats-reports/blob/master/contributors/contributors_with_n_dtrange.sh) and saw it's mostly an alias for this

```
GHA2DB_LOCAL=1 GHA2DB_SKIPTIME=1 GHA2DB_SKIPLOG=1 PG_DB="${1}" GHA2DB_CSVOUT="/data/${1}_contributors_with_${4}.csv" runq contributors/sql/contributors_with_n_dtrange.sql {{exclude_bots}} "$bots" {{from}} "${2}" {{to}} "${3}" {{n}} "${4}"
```

This seems to run [this sql query](https://github.com/cncf/devstats-reports/blob/master/contributors/sql/contributors_with_n_dtrange.sql) against some unmentioned database.  It's hard to say without knowing where the database came from, but it seems like that query is looking for users with github "events" in the following categories 

    'PullRequestReviewCommentEvent', 'PushEvent', 'PullRequestEvent',
    'IssuesEvent', 'IssueCommentEvent', 'CommitCommentEvent'
    
so -- maybe _some sort of activity_ would have been a better phrase than _commits_. ;) 

I guess [devstats is this](https://devstats.cncf.io/)? Which [led me here](https://github.com/cncf/devstatscode#api) and then the thought of kubing and helming up for a SQL dump made me dizzy so I stopped. 

I love you'all and wish only success for the the project -- but _maybe_ let up the complexity a bit?  Both here and in the project in general?  

Or, if that's not an option, [insert Groucho quote here](https://opentelemetry.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m). :heart:

**Comment by andrewhsu** [comment]
If you're curious about a specific user (as I was) you can approximate the github activity in `open-telemetry` org with a date range via a github UI search (likely not the same formula borrowed from k8s), e.g. https://github.com/issues?q=org%3Aopen-telemetry+involves%3Aandrewhsu+created%3A%3E2020-01-01+

It uses the [involves qualifier](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request):
> You can use the involves qualifier to find issues that in some way involve a certain user. The involves qualifier is a logical OR between the author, assignee, mentions, and commenter qualifiers for a single user. In other words, this qualifier finds issues and pull requests that were either created by a certain user, assigned to that user, mention that user, or were commented on by that user.

**Comment by Oberon00** [comment]
Can this be closed? That election is over 😃

**Comment by bhs** [comment]
@Oberon00 thanks! Yes, for sure, just an oversight.
