### ISSUE TITLE
create public repository called .github for default community health files

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/community#544]
Several of the open-telemetry repos don't have community files like SECURITY.md, CODE_OF_CONDUCT.md, [etc](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types).

I suggest creating a public repo https://github.com/open-telemetry/.github to host [default community health files](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file). This will save from having to update 30+ [repos](https://github.com/open-telemetry/?q=&type=source&language=) with the same files.

For reference, other CNCF projects that do this:
* https://github.com/kubernetes/.github
* https://github.com/containerd/.github

**Comment by SergeyKanzhelev** [comment]
cross link: https://github.com/open-telemetry/community/issues/401

**Comment by arminru** [comment]
Sounds good to me, thanks for bringing this up, @andrewhsu!

@open-telemetry/technical-committee @open-telemetry/governance-committee any objections?
Otherwise we could use it right away to publish the responsible disclosure guidelines proposed by @jpkrohling in https://github.com/open-telemetry/opentelemetry-specification/pull/990.

**Comment by jpkrohling** [comment]
Is such a repository treated differently by GitHub? Any docs on that?

**Comment by arminru** [comment]
@jpkrohling The doc is linked in the issue description. If I understand it correctly, Github would display the `SECURITY.md` placed in a repo called `open-telemetry/.github` in each repo's security policy section (e.g., https://github.com/open-telemetry/opentelemetry-java/security/policy).

**Comment by bogdandrutu** [comment]
Repo created

**Comment by andrewhsu** [comment]
LGTM https://github.com/open-telemetry/.github
