### ISSUE TITLE
Add whitespace linter for PR requests

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/community#55]

**Comment by SergeyKanzhelev** [comment]
can you give more details? I like the linters!!!

**Comment by iredelmeier** [comment]
@SergeyKanzhelev sorry for the delay 😅 I started looking but haven't yet found the ready-made solution I was kind of expecting to be out there.

For a scope that includes but is bigger than this issue, I suggest we use something like [danger](https://danger.systems/) to automate things like this.

**Comment by iredelmeier** [comment]
BTW I don't seem to be able to add labels? Hoping to add a `low priority` one for this.

**Comment by SergeyKanzhelev** [comment]
We have the same issue at Specification repo. https://github.com/open-telemetry/opentelemetry-specification/issues/15 Let's decide and solve it there and than will apply to other repositories.

I'll close this issue for now. Just to keep the number of active issues down.
