### ISSUE TITLE
REQUEST: New membership for @mx-psi

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/community#554]
### GitHub Username

@mx-psi

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jrcamp (Splunk)
- @ericmustin (Datadog)

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

cc to @tigrannajaryan who suggested this on open-telemetry/opentelemetry-collector-contrib#1373

### List of contributions to the OpenTelemetry project

Most of my contributions are on the OpenTelemetry Collector subproject:

-  I have contributed the Datadog metrics exporter and other bits that are common with the traces exporter (open-telemetry/opentelemetry-collector-contrib#1142, open-telemetry/opentelemetry-collector-contrib#1178, open-telemetry/opentelemetry-collector-contrib#1212, open-telemetry/opentelemetry-collector-contrib#1285, open-telemetry/opentelemetry-collector-contrib#1340, open-telemetry/opentelemetry-collector-contrib#1352). 
- I am an approver of this component (see [CODEOWNERS](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/.github/CODEOWNERS#L22)) and I have reviewed most PRs that modified it. 
- I have made a contribution to the Resource detection processor (open-telemetry/opentelemetry-collector-contrib#1324) and I have discussed new features (open-telemetry/opentelemetry-collector-contrib#1292) which I plan to contribute to.
- I participate in discussions on the Gitter channel and Github issues related to the component that I maintain.

**Comment by jrcamp** [comment]
I support

**Comment by ericmustin** [comment]
I confirm my support for @mx-psi

**Comment by SergeyKanzhelev** [comment]
Welcome, @mx-psi! Invite sent
