### ISSUE TITLE
GHCR Image request - java-test-containers

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#556]
With the Docker Hub pull limits coming up, there is a realistic chance that our CI, which relies heavily on Docker-based integration tests that pull from Docker Hub, to become flaky. We're considering rehosting the images we use in tests to GitHub Container Registry, which allows easy permission management with our existing GitHub teams.

Creating an image requires organization admin privileges - can someone create an image called `java-test-containers`? Then we can push different containers as different tags to this one image.

https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry

I think the process for this is

One time setup - navigate to the organization's [member_privileges](https://github.com/organizations/open-telemetry/settings/member_privileges) and enable Public package creation

1) docker login ghcr.io - enter username and GitHub PAT as password
2) docker pull scratch
3) docker tag scratch ghcr.io/open-telemetry/java-test-containers
4) docker push ghcr.io/open-telemetry-java-test-containers

Navigate to [package settings](https://github.com/users/open-telemetry/packages/container/java-test-containers) and add open-telemetry/java-maintainers and open-telemetry/java-instrumentation-maintainers as admin access to this package.

Let me know if this makes sense or I can help with anything.

**Comment by anuraaga** [comment]
By the way, my plan for rehosting the images in case it's interesting is to have a nightly GitHub Actions workflow that runs docker pull / tag / push to ghcr.io.

**Comment by trask** [comment]
@open-telemetry/technical-committee can someone help us with this?

**Comment by arminru** [comment]
@anuraaga @trask Done!
https://github.com/users/open-telemetry/packages/container/package/java-test-containers
