### ISSUE TITLE
REQUEST: New membership for @matej-g

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/community#557]
### GitHub Username

@matej-g

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias 
- @Aneurysm9 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

Mainly authored PRs in `open-telemetry/opentelemetry-go` and `open-telemetry/opentelemetry-go-contrib` repositories; occasionally also responding to issues. Some of the selected contributions:
- In the area of trace and metric exporters (https://github.com/open-telemetry/opentelemetry-go/pull/944, https://github.com/open-telemetry/opentelemetry-go/pull/1037)
- Go SDK (https://github.com/open-telemetry/opentelemetry-go/pull/1153, https://github.com/open-telemetry/opentelemetry-go/pull/1170)
- Instrumentation (https://github.com/open-telemetry/opentelemetry-go-contrib/pull/204)
- Some code-base "clean-up" tasks (https://github.com/open-telemetry/opentelemetry-go-contrib/pull/381, https://github.com/open-telemetry/opentelemetry-go/pull/1172, https://github.com/open-telemetry/opentelemetry-go-contrib/pull/412)

**Comment by MrAlias** [comment]
I support this request :tada:

**Comment by SergeyKanzhelev** [comment]
@matej-g I'm waiting on @Aneurysm9 to confirm this request

**Comment by Aneurysm9** [comment]
I support this request!

**Comment by SergeyKanzhelev** [comment]
Welcome, @matej-g! Invite sent
