### ISSUE TITLE
REQUEST: New membership for @djaglowski

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/community#558]
### GitHub Username

@djaglowski

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan (Splunk)
- @kumoroku (Sumo Logic)

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

Most of my contributions have been on the Collector subproject, and specifically on the [stanza Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/stanzareceiver).

I have authored a number of PRs
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1096
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1117
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1124
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1125
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1267

I have addressed feedback on issues related to the stanza Receiver
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1420
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1438

I regularly take part in the Collector and Logs SIGs meetings, and engage in the associated gitters 

I have made substantial contributions to the [stanza](https://github.com/observIQ/stanza) project. While the stanza project is independent of OpenTelemetry, it is increasingly developed with support of the OpenTelemetry project in mind.

**Comment by tigrannajaryan** [comment]
I support.

**Comment by kumoroku** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @djaglowski! Invite sent.
