### ISSUE TITLE
remove old sig mtg youtube videos

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/community#562]
I like the idea that we record our OpenTelemetry SIG meetings and post them to youtube so people who cannot attend the meeting can keep current. I've reviewed old videos before to catch up on missed meetings. However, since the videos are unedited and the fact that we're not all seasoned youtube personalities, there are bound to be some embarrassing moments or accidental slip of sensitive information.

I'd like to suggest a video retention policy that deletes old SIG meeting videos. I recommend deleting videos older than 6 months since most of what we discuss is obsolete in 6 months anyways and any important information or decision to be retained should end up in github or google doc.

**Comment by mtwo** [comment]
I’ve never thought about this before but I think that it’s a good idea

________________________________

**Comment by SergeyKanzhelev** [comment]
Is this request based on some complains, legal considerations, or just a suggestion? Trying to understand how the 6 month was decided on and what else should be cleaned up? Should meeting notes be also cleaned up? Also, related question, if somebody accidentally slipped some sensitive information or just do not like the recoding, would it be enough reason to take it down and compromise the transparency?

Regarding 6 month, we have a postmortem discussion on GC 2020 election in one of the recordings. Would be nice to keep it for the next election for the reference - ~1 year. I don't have many other examples where the recordings so long in the pat might be definitely useful. Perhaps some specs decision refresher? I can also see how 6 month might be too long for the embarrassing moment to stay online. So wonder if the 6 month a well-balanced timeframe?

**Comment by andrewhsu** [comment]
@SergeyKanzhelev I filed the issue as a suggestion. Not urgent, no complaints, and no legal considerations were on my mind.

I initially suggested 6 months retention for SIG meeting recordings because it seemed to me generally reasonable to start with, but I'm personally flexible on the timeline. I see oopsies of recordings of shared screens (showing browsing history and such) and I feel it is just too minor for somebody to go through the trouble of censoring or reviewing requests to take down. A data retention policy would ease people's minds.

I'm only suggesting a data retention for OpenTelemetry SIG meetings since they are very frequent. There are also a lot of new people joining who may not know the ramifications of sharing their screen or video at the meeting, even though we have disclaimers at the top of most SIG meeting notes.

**Comment by SergeyKanzhelev** [comment]
Thank you for clarification on urgency of the request! Adding retention is an extra work and also raises the questions I listed before. In general it would be nice to have a write up about this topic. If anybody has examples in mind on how it's don on other projects - please comment.

**Comment by andrewhsu** [comment]
I feel it is unnecessary to clean up meeting notes because there is an opportunity for people to edit their content before posting into the document. Whereas if during a SIG meeting my hard-of-hearing grandfather blurts out his SSN in the background of a recording, there's less of a chance to censor (not that that's happened).
> Should meeting notes be also cleaned up?

It seems to me a lot of work to scrub through 1 hour of a SIG mtg recording to remove the bits that are undesirable. It may be easier to just honor takedown requests if they are rare, but I could be wrong.
> Also, related question, if somebody accidentally slipped some sensitive information or just do not like the recoding, would it be enough reason to take it down and compromise the transparency?

I see the "OPS Live" videos on the OpenTelemetry channel as a more professionally-produced, deliberate recording that could have value for retaining longer than a SIG meeting recording.
> Regarding 6 month, we have a postmortem discussion on GC 2020 election in one of the recordings. Would be nice to keep it for the next election for the reference - ~1 year. I don't have many other examples where the recordings so long in the pat might be definitely useful. Perhaps some specs decision refresher?

If you wanted to accommodate for the hypothetical use case of community members taking a 2-week vacation and returning to the internet to catch up on missed SIG mtgs, at least that as a lower-bound? Perhaps youtube analytics can show how long after upload a recording is viewed to arrive at a better decision.
> I can also see how 6 month might be too long for the embarrassing moment to stay online. So wonder if the 6 month a well-balanced timeframe?

**Comment by andrewhsu** [comment]
My quick scan of other CNCF graduated projects only came up with this doc on k8s regarding how they handle zoom recordings: https://github.com/kubernetes/community/blob/2f634399ed689e3c5185ef383c24d85c2a86ddce/communication/zoom-guidelines.md#meeting-recordings

**Comment by SergeyKanzhelev** [comment]
> Whereas if during a SIG meeting my hard-of-hearing grandfather blurts out his SSN in the background of a recording, there's less of a chance to censor

History got preserved on meeting notes documents. So accidental copy/paste will stay forever. But I agree it's not that visible in the docs - I asked about meeting notes just in case it's some legal protection where we do not want to keep the recording of specific people presence on the meeting. 

> My quick scan of other CNCF graduated projects only came up with this doc on k8s regarding how they handle zoom recordings: https://github.com/kubernetes/community/blob/2f634399ed689e3c5185ef383c24d85c2a86ddce/communication/zoom-guidelines.md#meeting-recordings

they keep their meetings forever though. And there is no guidance on how to request editing. It only talks about editing out content that violates the CoC.

> 2-week vacation and returning to the internet to catch up on missed SIG mtgs

would people be interested to catch up after 3 month parental leave? I personally was overwhelmed so didn't watch videos. But it is nice to have an option.

Again, I'm not arguing, just trying to come up with some reasoning to go with either of approaches and what are the right policies.

**Comment by jmacd** [comment]
I support this motion. I think it's important to limit the scope of document discovery in case of an intellectual property dispute in the future. For example, 1993 asking 1987: "did anyone say 'but LZW is patented?'"

**Comment by SergeyKanzhelev** [comment]
Today this was discussed on GC meeting and the general agreement was that we will be better off by providing a written instructions on how to request video edits. So we keep our work transparent.

> I support this motion. I think it's important to limit the scope of document discovery in case of an intellectual property dispute in the future. For example, 1993 asking 1987: "did anyone say 'but LZW is patented?'"

This is a new argument. I wonder why k8s is not doing it then. Do you have some links to read about this or use to ask CNCF legal about it?

**Comment by Oberon00** [comment]
I would simply feel more comfortable if I know that most likely the recording will not be publicly available forever. If that is counts as an argument. 😃

**Comment by austinlparker** [comment]
Just closing the loop here after a few years -

- We stopped publishing recordings to YouTube a while ago (in July 2023).
- Meeting recordings are kept in the Zoom account. They are not crawlable, but they are discoverable via a [spreadsheet](https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s).
- At this time, we are not aging out recordings in Zoom.
- All SIG meetings have been deleted from YouTube.
