### ISSUE TITLE
Change repository license for website repo

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#565]
In the interests of making it easier for the community to re-use documentation and website content, we'd like to re-license to CC BY 4.0 (which is what the Kubernetes website uses) in lieu of Apache2.

See [here](https://creativecommons.org/licenses/by/4.0/) for details on the license.

I'm not sure the exact process on this, but imagine that we would need some governance members to OK it?

**Comment by SergeyKanzhelev** [comment]
Created https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-607?created=true for advice. Adding to the GC meeting agenda.

**Comment by yurishkuro** [comment]
@austinlparker it would be good if you could summarize the reasons for switching and what differences there are between the licenses.

**Comment by austinlparker** [comment]
Briefly, CC BY 4.0 and Apache2 are similar (except for patentability - CC doesn't extend a patent grant) but CC BY is significantly more permissive in accommodating commercial use. As we anticipate the website containing a greater number of visual aids, code, and other assets that commercial interests may wish to adapt for their own purposes (training, workshops, etc.) CC BY allows for this with a simple attribution notice rather than the inclusion of the full license.

**Comment by dyladan** [comment]
The practical result is that tracing and platform vendors and consultation firms will be able to more easily reuse website content when writing blog posts, docs, and similar.

**Comment by SergeyKanzhelev** [comment]
Reply from cncf:

> There’s no issue as all CNCF projects are bound by: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
>
> You could leave that LICENSE there and add a “LICENSE-DOCS” file that is CC-BY 4.0 as sometimes websites have code like JS that should be under Apache v2.0, but the content itself should be CC-BY 4.0

**Comment by SergeyKanzhelev** [comment]
Discussed at GC meeting today and there were no concerns. @yurishkuro please confirm you ok with the clarification from  @austinlparker and @dyladan.

Once @yurishkuro is ok, we should be good to go.

**Comment by austinlparker** [comment]
Works for me, thanks!

**Comment by yurishkuro** [comment]
sgtm
