### ISSUE TITLE
Request: repository for the OpenTelemetry Collector Builder

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#568]
From: https://github.com/open-telemetry/opentelemetry-collector/issues/2129

The [OpenTelemetry Collector Builder](https://github.com/observatorium/opentelemetry-collector-builder) is a CLI tool that generates OpenTelemetry Collector binaries based on a manifest.  It has been incubating in another organization (`observatorium`) for a while. I believe it's stable enough by now and could be useful to a wider audience, so, I'd like to ask whether it would be in this community's interest to host the main repository for the project.

cc @open-telemetry/collector-maintainers and @open-telemetry/collector-approvers for opinions.

**Comment by jpkrohling** [comment]
Any feedback about this one?

**Comment by tigrannajaryan** [comment]
@jpkrohling what do you think if we put it in the Collector contrib repo? Now that you are an approver I think it will work since you can also take the ownership of it.

**Comment by jpkrohling** [comment]
I think @bogdandrutu also suggested placing it in the contrib repository, but my concern is that it would then be tied to the release cycles and procedures for the collector-contrib. Right now, the builder can be released independently and the process is well automated (and [documented](https://github.com/observatorium/opentelemetry-collector-builder/blob/master/RELEASE.md)).

We have a similar experience with the `tracegen`, and if I were to decide today, I think I would have kept it outside of the contrib for the same reasons.

**Comment by tigrannajaryan** [comment]
> I think @bogdandrutu also suggested placing it in the contrib repository, but my concern is that it would then be tied to the release cycles and procedures for the collector-contrib. Right now, the builder can be released independently and the process is well automated (and [documented](https://github.com/observatorium/opentelemetry-collector-builder/blob/master/RELEASE.md)).

@jpkrohling OK, makes sense to me. @bogdandrutu what do you think?

**Comment by SergeyKanzhelev** [comment]
what's the status of this request?

**Comment by jpkrohling** [comment]
Waiting on @bogdandrutu.

**Comment by jpkrohling** [comment]
Bump?

**Comment by bogdandrutu** [comment]
Repo created, easycla enabled. 

@jpkrohling please file an issue in that repo and propose maintainers approvers.
