### ISSUE TITLE
Create GitHub repository for OpenTelemetry C++ contrib

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/community#570]
All languages other than C++ presently have their `contrib` repo.

The ask is to create: https://github.com/open-telemetry/opentelemetry-cpp-contrib

which can be populated with the following contents -- multiple projects:
- practical integration examples, e.g. how to instrument certain library or product with OpenTelemetry C++ SDK.
- shim layers for popular logging libraries, e.g. log4cxx.
- visualization tools that might be helpful to enhance dev experience: end-to-end guidelines and code how to emit with C++ SDK and forward to exporter of choice (OTLP, ETW, Logstash, etc.).
- incubating new features for zPages, e.g. enhancing zPages implementation in C++ with log viewer.
- student projects that are functional, but not ready for inclusion as part of official OpenTelemetry C++ SDK.

Initial set of approvers / admins for the repo - `@open-telemetry/cpp-approvers`

**Comment by tigrannajaryan** [comment]
Done.

I replicated the permissions from https://github.com/open-telemetry/opentelemetry-cpp, let me know if any changes are needed.

**Comment by maxgolov** [comment]
@SergeyKanzhelev - https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main - `main` branch created, with just `LICENSE` file (Apache License 2.0) in it for now.

**Comment by SergeyKanzhelev** [comment]
@lizthegrey, @bogdandrutu can you please enable EasyCLA for the new repo?

**Comment by SergeyKanzhelev** [comment]
Updated creation repo instructions: https://github.com/open-telemetry/community/pull/571

**Comment by lizthegrey** [comment]
Updated easycla.

**Comment by tigrannajaryan** [comment]
> need to make sure CLA is enforced. Let's keep the issue open. @maxgolov ping when `main` branch will be created

Thanks, I was too quick.

**Comment by SergeyKanzhelev** [comment]
Thank you @lizthegrey!

@tigrannajaryan no worries. Ideally we need some automation here to detect violations like CLA not enabled instead of requiring people to learn this.

**Comment by maxgolov** [comment]
@SergeyKanzhelev @tigrannajaryan @lizthegrey - thank you folks for such a quick turnaround on this!
