### ISSUE TITLE
Document Docker Hub accounts in managed assets

### ISSUE THREAD

**Issue by arminru** [open-telemetry/community#573]
Our Docker Hub profile `otel` and user `opentelemetrybot` are missing in `assets.md`:
https://hub.docker.com/r/otel/
https://hub.docker.com/u/opentelemetrybot

**Comment by SergeyKanzhelev** [comment]
cross reference: https://github.com/open-telemetry/community/issues/353

**Comment by trask** [comment]
@open-telemetry/collector-maintainers @open-telemetry/collector-contrib-maintainer do you own the Docker Hub accounts?

**Comment by codeboten** [comment]
pinging @tigrannajaryan and @bogdandrutu who I *think* set it up

**Comment by atoulme** [comment]
cross reference: https://github.com/open-telemetry/community/issues/1348

**Comment by codeboten** [comment]
The accounts initially mentioned in the issue are now document here: https://github.com/open-telemetry/community/blob/main/assets.md#docker-hub, can this issue be closed?
