### ISSUE TITLE
Create new repository for OTel Prometheus Sidecar

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/community#575]
I would like to create a new Github repository to house a Prometheus sidecar for exporting data from a Prometheus server to an OTLP endpoint. This tool helps OpenTelemetry users migrate to an OpenTelemetry-based system while continuing to run their Prometheus setup.

The code for this new repository resides here: https://github.com/lightstep/opentelemetry-prometheus-sidecar. See the README for a description of this software.

This will be a community owned part of the OpenTelemetry metrics ecosystem. I propose the name `open-telemetry/prometheus-sidecar`.

**Comment by jmacd** [comment]
I created https://github.com/open-telemetry/prometheus-sidecar

**Comment by bogdandrutu** [comment]
The repo does not include change to use otlp.

**Comment by jmacd** [comment]
I made the repo private while I migrate commits. I've frozen the Lightstep repo and will begin that soon.

**Comment by SergeyKanzhelev** [comment]
> I made the repo private while I migrate commits. 

we need to make sure that all commits are under CNCF CLA. The direct migration of commits is discourged.

**Comment by SergeyKanzhelev** [comment]
I believe you can merge commits via the merge PR under your name with the signed CLA

**Comment by jmacd** [comment]
Thanks for pointing this out. I will be merging only my commits, however this raises a question, I suppose, about the other collaborators with existing commits reflected in the history. Is there a problem with forked code, generally, for OTel w.r.t. the CNCF?

**Comment by jmacd** [comment]
I imagine that because this is Google-owned source code, you could help if there is a problem @SergeyKanzhelev. I hope this is something Stackdriver will endose.

**Comment by SergeyKanzhelev** [comment]
not a layer..

My understanding is that it is enough that somebody who "owns" code merged changes under CLA. Not sure what is the ownership of code in lightstep repo.

If something needed from me, happy to help or involve the right people from Google.

**Comment by jmacd** [comment]
I cloned the code in the current http://github.com/open-telemetry/prometheus-sidecar from https://github.com/Stackdriver/stackdriver-prometheus-sidecar, which is owned by Google I presume. The rest of the changes are mine, and I imagine that both Google and Lightstep support this, but the authors of the 199 existing commits are past/present Google employees--do we need to do anything to "legally" clone these commits into an OTel repo?

**Comment by SergeyKanzhelev** [comment]
@mtwo do you know what team owns it?

**Comment by SergeyKanzhelev** [comment]
It seems that @mtwo is out of office till Dec 3rd. And we will not have GC meeting for another week. @jmacd how soon do you need this? Can it wait for another week?

**Comment by mtwo** [comment]
Sergey, I _think_ that the original code was authored by Joe’s team

________________________________

**Comment by jmacd** [comment]
This is not urgent.

**Comment by jmacd** [comment]
Thanks @SergeyKanzhelev and @mtwo.

**Comment by jmacd** [comment]
@SergeyKanzhelev I'd like to renew my request for Google to formally donate the Stackdriver Prometheus Sidecar commits so I can migrate the OTel variation to recognize those commits.

**Comment by SergeyKanzhelev** [comment]
Funny enough, my meeting with OSS team got cancelled tonight, but they promised to come back to me tomorrow morning.

**Comment by SergeyKanzhelev** [comment]
ok, got a reply. I just need to sign off on PR brining the code. Please go ahead!

**Comment by BrianChristie** [comment]
Wanted to check in on this, is there an update on getting things migrated to https://github.com/open-telemetry/prometheus-sidecar?
Thanks!

**Comment by trask** [comment]
@jmacd is this still an open issue? thx!

**Comment by jmacd** [comment]
The OTC Prometheus receiver has effectively replaced the need for this project by now.
