### ISSUE TITLE
Asset request: browserstack

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#576]
The JS SIG would like access to Browserstack. Browserstack is free for open source projects but before just signing up I wanted to see if there is an official process for creating a community resource like this or should I just go ahead and sign up on my own?

https://www.browserstack.com/open-source

**Comment by SergeyKanzhelev** [comment]
I think general recommendation here is if you think having service account would be best - ask for one. If it's better managed with individual e-mails, go ahead and register it, would be great if you can  update the https://github.com/open-telemetry/community/blob/master/assets.md so people would know who to ask in case something it needed

**Comment by trask** [comment]
@dyladan is this still an open issue? thx!

**Comment by dyladan** [comment]
Technically yes, but there is another group working on the browser specific things right now

**Comment by trask** [comment]
@MSNev is that you? 😄

**Comment by MSNev** [comment]
`another group working on the browser specific things right now` -- yes, browserstack request no (at least not yet)

**Comment by trask** [comment]
@dyladan is it ok to close this?
