### ISSUE TITLE
Create new repository for Otel Lambda Extension layer

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#577]
This issue is to track the creation of a new repository in the OpenTelemetry organization to house a Lambda extension that embeds an OpenTelemetry collector to support collecting telemetry data from Lambda functions.

The code for this new repository can be found here: https://github.com/lightstep/opentelemetry-lambda-extension

**Comment by Oberon00** [comment]
I'm curious: What is the advantage of going via a collector extension in AWS Lambda? Are you able to circumvent the "function might be suspended at any time" problem with this?

**Comment by codeboten** [comment]
@Oberon00 it's probably worth reading this article https://aws.amazon.com/blogs/compute/building-extensions-for-aws-lambda-in-preview/ but the lambda extension get initialized before the lambda function and are also able to receive a shutdown signal, to perform any flushing of the data.

**Comment by rakyll** [comment]
cc @alolita @dennisyuan98 @ntyrewalla

**Comment by Oberon00** [comment]
@codeboten Now if only the lambda itself could also get a callback for that... Then we wouldn't need another process 😃

**Comment by codeboten** [comment]
Ideally we'd like to create a SIG around Lambda's as well.

**Comment by tedsuo** [comment]
@carlosalberto mind setting up the repo? I can add a SIG meeting to the calendar. I've discussed this with @ntyrewalla and AWS is interested, we just need to pick a time.

**Comment by alolita** [comment]
Thanks @tedsuo @carlosalberto - please let us know once the repo is set up. Also would like to get the time confirmed for the Sampling SIG - can we get a time on Tuesday or Thursday afternoons (APAC friendly - 4p or 5p PST) - many thanks.

**Comment by SergeyKanzhelev** [comment]
@carlosalberto created the repo, there are still CLA and things needs to be enabled on it: https://github.com/open-telemetry/opentelemetry-lambda-extension/

It would be great for the new repositories to start with the understanding that we have a companies-diverse set of committed maintainers for all the code we host in this organization. It seems that all the right conversations are happening, thank you!

**Comment by carlosalberto** [comment]
@alolita @tedsuo Please review the initial code import PR: https://github.com/open-telemetry/opentelemetry-lambda-extension/pull/1

@alolita Do you have an update on the time for this new SIG?

**Comment by bogdandrutu** [comment]
this is done correct? @alolita feel free to reopen if anything needed
