### ISSUE TITLE
Grant create_package permission to maintainers

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/community#579]
java-instrumentation repo uses GitHub Container Register to publish docker images used in testing. Currently we have a single package created for us: https://github.com/orgs/open-telemetry/packages/container/package/java-test-containers. Although we do manage to achieve our goals with it, it is quite convoluted to use single package name for many diverse docker images that we want to publish.

Is it possible to grant admin/create_package permission to java-instrumentation repo maintainers? I imagine that other SIGs may be interested in this as well.

**Comment by SergeyKanzhelev** [comment]
This is the packages permissions page:

![image](https://user-images.githubusercontent.com/9950081/101078677-54723900-355b-11eb-9758-9321c2b62262.png)

Do you know if this is possible to grant package publish permissions to specific team?

I see that specific package can be ACLd so happy to create packages while this investigation on the right permissions is happening:

![image](https://user-images.githubusercontent.com/9950081/101078805-81bee700-355b-11eb-8771-b171bb980269.png)

**Comment by SergeyKanzhelev** [comment]
Please re-open if this is still a problem and suggest what permissions needs to be granted
