### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#580]
GitHub Discussions is more generally available starting today - should we enable this? It's basically a forum/q&a/etc. space that can be added per-repo. I surmise there's a permission that needs to be enabled at the organization level (or maybe I just don't have the right permissions on the website repo). 

My 0.02 is that I think this would solve the problem of user q&a getting lost in the shuffle of gitter while also keeping it out of repo issues. Should each repo have its own discussions or should we consolidate discussions into a single repo, though? A single discussion can have multiple categories, so we could probably consolidate.

I'm also not entirely sure how discussions moderation/etc. work - I assume it follows repository ownership/admin rules and roles.

**Comment by tigrannajaryan** [comment]
+1 for trying. Gitter is not searchable, Github issues are not suitable for Q&A because they are mixed wig bugs and feature requests. If Github discussions are like Stackoverflow it can be useful.

**Comment by dyladan** [comment]
+1 for anything that gets me one step closer to ditching gitter

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/governance-committee anything blocks us from using github discussions? Forum-like format is definitely better than either Gitter or Slack so it is orthogonal to previous decision to wait for GA for the chat switch decision.

**Comment by alolita** [comment]
+1 for testing GH discussions! Like the format and integration. Could be a good alternative for us!

**Comment by austinlparker** [comment]
I see Discussions have been enabled for this repo - I suppose we should try it out and move the discussion about discussions over there?

**Comment by sarahnovotny** [comment]
:D

**Comment by SergeyKanzhelev** [comment]
Discussion about discussions has moved to the discussions, let's have discussions in discussions than.
