### ISSUE TITLE
REQUEST: New membership for dashpole

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/community#584]
### GitHub Username

@dashpole

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias 
- @james-bebbington 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [PRs authored](https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3Adashpole+archived%3Afalse+org%3Aopen-telemetry): 8
- [PRs reviewed](https://github.com/pulls?q=is%3Apr+archived%3Afalse+org%3Aopen-telemetry+commenter%3Adashpole+-author%3Adashpole+): 27
- [Issues created/responded to](https://github.com/issues?q=is%3Aissue+archived%3Afalse+org%3Aopen-telemetry+commenter%3Adashpole+): 4
- SIG projects I am involved with: OpenCensus migration, Versioning discussion

**Comment by james-bebbington** [comment]
I support

**Comment by MrAlias** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @dashpole! Invite sent
