### ISSUE TITLE
REQUEST: New membership for breedx-splk

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/community#585]
### GitHub Username

@breedx-splk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jkwatson
- @trask 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-java/commits?author=breedx-splk
- https://github.com/open-telemetry/opentelemetry-java/issues?q=commenter%3Abreedx-splk+
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues?q=is%3Aissue+commenter%3Abreedx-splk
- SIG opentelemetry-java
- SIG opentelemetry-java-instrumentation

**Comment by jkwatson** [comment]
*I support*

**Comment by trask** [comment]
👍

**Comment by SergeyKanzhelev** [comment]
Sorry for delay. Welcome, @breedx-splk! Invite sent
