### ISSUE TITLE
Zoom accounts passcodes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#588]
Zoom meetings need to have a passcode. I suggest we follow k8s and set the passcode for all our accounts to **77777**.

Need to communicate this change widely and start changing links to include the passcode.

See https://github.com/kubernetes/community/issues/5146 for details.

**Comment by bhs** [comment]
Just a very brief note from the GC meeting that's happening right now: TL;DR "we're doing this" (due to our first zoom-bombing, which took place last week 🎂 )

**Comment by mtwo** [comment]
Further followup, we’ll implement a password starting next Tuesday. I’ll be updating the community page and calendars with the password (77777, same as Kubernetes).

**Comment by alolita** [comment]
Thanks! @SergeyKanzhelev @mtwo

**Comment by mtwo** [comment]
I've updated our three Zoom accounts to require a passcode on all meetings, set the personal meeting passcode to 77777, and required a passcode even for people connecting via telephone. I've updated all calendar and meeting notes doc links to embed the passcode and am adding it to relevant GitHub pages.

I also enabled HD video, as it was disabled for some reason!
