### ISSUE TITLE
Request for setup of Prometheus workgroup

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#590]
I’d like to request the formation of a workgroup focused on interoperability between Prometheus and OpenTelemetry formats. We would like to improve the functionality of the Prometheus components in the Collector and in the language SDKs. We invite all open source contributors and observability experts to participate. 

We’ve already discussed the formation of this workgroup in the specification meeting. We request a weekly meeting be scheduled every Tuesday from 10:30-11:30 PST. I'd be happy to facilitate the weekly meeting.

@andrewhsu @bogdandrutu @tigrannajaryan @rakyll

**Comment by SergeyKanzhelev** [comment]
CC @jmacd, @RichiH

**Comment by SergeyKanzhelev** [comment]
> every Tuesday from 10:30-11:30 PST

any chance we can survey for more time slots? I'd be interested to participate, but time slot is not ideal.

**Comment by alolita** [comment]
@SergeyKanzhelev I suggested this slot since it is Europe friendly and @RichiH can join in at that time slot. We have the spec meeting from 8am-9am PST on Tuesdays. We could do 9am-10am PST too. Would that time work for you?

**Comment by SergeyKanzhelev** [comment]
9-10 works better.

**Comment by tigrannajaryan** [comment]
FYI, @jrcamp if you want to participate.

**Comment by alolita** [comment]
@SergeyKanzhelev Great! Let's do 9-10 PST on Tuesdays.

**Comment by robskillington** [comment]
I know OpenMetrics would love to participate, looking forward to joining if that's possible.

**Comment by kakkoyun** [comment]
cc @bwplotka @brancz @lilic

**Comment by lilic** [comment]
Sounds great, would be interested in joining as well!

**Comment by roidelapluie** [comment]
> @SergeyKanzhelev Great! Let's do 9-10 PST on Tuesdays.

can you edit the first message?

**Comment by ArthurSens** [comment]
Not sure if I can be useful to the working group, but if that's ok I'd like to participate in the weekly meetings :)

**Comment by bwplotka** [comment]
I think  9-10 PST clashes with [the CNCF SIG Observability meetings](https://www.cncf.io/calendar/) - otherwise sounds good 🤗

**Comment by brancz** [comment]
Would love to participate as well. European friendly call would indeed be appreciated :)

**Comment by tigrannajaryan** [comment]
Hint: if one time every week doesn't work for everyone, you can alternate times every other week. That's what we do in other SIGs.

**Comment by alolita** [comment]
Hi @tigrannajaryan good suggestion.
 
@bwplotka  - will make sure not to conflict w the CNCF observability meeting 

and plan to be EU timezone friendly

**Comment by rakyll** [comment]
I'll adjust my cal based on other people's availability. I'm flexible.

**Comment by jrcamp** [comment]
Please add me as well. All the times discussed work for me.

**Comment by ranton256** [comment]
I'd like to be participate in the WG.

**Comment by alolita** [comment]
Hi everyone, I've created an meeting series for the Prometheus workgroup to meet on Wednesdays 9-10am PST which is 1700-1800 UTC. I hope this time works for everyone interested in joining. I could not find a time that works for everyone interested on Tuesday mornings PST. The first meeting will be held on January 27, 2021 and has a Google Meet link for the first meeting until I can get a Zoom call created for this weekly session. 

Looking forward to having everyone join in. We've lots to do!

**Comment by SergeyKanzhelev** [comment]
pls use one of the existing rooms, @mtwo will secure them with the password on Tuesday.

https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md

**Comment by alolita** [comment]
The Prometheus workgroup meeting calendar invite is now set up for every week on Wednesdays at 8am-9am PT (1600-1700 UTC).

**Comment by bogdandrutu** [comment]
this is done correct? @alolita feel free to reopen if anything needed
