### ISSUE TITLE
Create repository for JS API

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#592]
The JS SIG would like to be able to track the stable API separately from other packages. Since we don't expect the API to change often we would prefer not to complicate the CI for the other packages still in very active development in order to build the API package with an entirely separate process. This will also allow us to have stricter merge/release rules for the API package more easily and more easily track API changes to ensure we are not breaking and so on.

Suggested name: `opentelemetry-js-api`

/cc @open-telemetry/javascript-maintainers

**Comment by dyladan** [comment]
Hmm it appears there isn't consensus on this idea yet. I'm going to close this. I'll reopen if we decide to go this route.

**Comment by dyladan** [comment]
At the SIG we discussed this and would like to move forward with a separate repo for the API unless the @open-telemetry/technical-committee has an objection.

**Comment by yurishkuro** [comment]
> At the SIG we discussed this

Any summary of the discussion? What changed since the last time? (not that I have objections to creating a repo)

**Comment by dyladan** [comment]
There is some summary here, but we mostly discussed it in-person at the SIG meeting https://github.com/open-telemetry/opentelemetry-js/discussions/1810

The main reasons:

- More easily version it separately from the SDK modules. Github releases and tags don't allow us to only release/tag one folder.
- Automated changelog tools will be able to generate a changelog for the API separate from the main changelog.
- Changes to the API should be more careful and intentional. Keeping the API in a separate module will allow us to apply different rules and access controls (branch protections, review rules, etc) to the API than the other modules.
- Simplify the build/release pipeline. If the API is kept in the main repo, we will need to do some sort of check if the API folder is updated to build/test/release it.

**Comment by yurishkuro** [comment]
created https://github.com/open-telemetry/opentelemetry-js-api/

@lizthegrey, @bogdandrutu - please enable EasyCLA

**Comment by bogdandrutu** [comment]
enabled
