### ISSUE TITLE
REQUEST: New membership for Austin-Tan

### ISSUE THREAD

**Issue by Austin-Tan** [open-telemetry/community#593]
### GitHub Username

@Austin-Tan

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas 
- @alanwest 

*New!*: Each sponsor should reply to this issue with the comment "I support".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - The [entire list](https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+author%3AAustin-Tan). Some recent highlights include:
  - Adapting spec changes to Zipkin's exporter (don't populate tags from Resource)
  - Assisting the unification of package/dependency versioning (draw each version from a single properties file).

- Issues responded to
  - The aforementioned issues are all linked in their respective PRs. The Zipkin changes for instance respond to [OTel .NET issue #1656](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1656) which addresses [OTel Spec issue #1185](https://github.com/open-telemetry/opentelemetry-specification/pull/1185).
- SIG projects I am involved with
  - Primarily the [OTel .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet).

**Comment by cijothomas** [comment]
I support

**Comment by alanwest** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @Austin-Tan! Invite sent.
