### ISSUE TITLE
REQUEST: New membership for djc

### ISSUE THREAD

**Issue by djc** [open-telemetry/community#599]
### GitHub Username

@djc

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jtescher
- @TommyCpp

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-rust/pulls?q=is%3Apr+is%3Aclosed+author%3Adjc

**Comment by TommyCpp** [comment]
I support

**Comment by jtescher** [comment]
@djc welcome to otel 🎉

**Comment by SergeyKanzhelev** [comment]
Welcome, @djc! Invite sent
