### ISSUE TITLE
Move community conversations from Gitter to GitHub discussions

### ISSUE THREAD

**Issue by mtwo** [open-telemetry/community#622]
We debated switching from Gitter to GitHub discussions during the maintainers meeting today.

As a followup, I plan to close down the community Gitter on February 1st (next Monday) and I'll immediately update our community Readme.md to point people to GitHub discussions. I'll also see if I can find a way to preserve readonly access to Gitter.

If you have any concerns or objections, please reply here!

**Comment by bhs** [comment]
Hey @mtwo : does this also mean that we're closing the door on slack (per #53 and elsewhere)?

There had been talk of "waiting for GA" before moving to Slack. I am personally totally happy to have us all just use GitHub discussions, but I do want to be somewhat confident we're not "migrating twice."

**Comment by mtwo** [comment]
I didn't ask this during the maintainers meeting, but my sense is that GitHub discussions are preferred over Slack as well, and we won't have to migrate twice.

If anyone has an opinion on this, please post it here!

**Comment by SergeyKanzhelev** [comment]
> I didn't ask this during the maintainers meeting, but my sense is that GitHub discussions are preferred over Slack as well, and we won't have to migrate twice.

Is there a way to export the history as text and dump it into this repository? If there are volunteers to create a scraper, this would be handy to preserve for history and transparency.

**Comment by dyladan** [comment]
@mtwo there are definitely some cases where discussions isn't enough. instant messaging is a much easier way to go back and forth with someone when trying to design an implementation for something or ask a quick question about something. There is also no way to have private discussion in discussions.

**Comment by alolita** [comment]
Agree @dyladan there is no way to have a 1:1 chat on a GitHub discussion. Does that mean we should consider Slack?

A related question: Why can we not use the CNCF Slack workspace - is that not an option due to cost?

**Comment by mtwo** [comment]
@alolita we can, we just chose to postpone the migration until after GA. Based on the comments here, I'll hold off on shutting down the Gitter community room, but will merge in the links on the readme so that they point to GitHub discussions. Sound good?

**Comment by Anirudh-alb** [comment]
bruh
