### ISSUE TITLE
Create repo for OpenTelemetry Lambda support

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#626]
AWS Lambda (referred to as Lambda hereon) is a compute service that lets the user build serverless applications, where the user’s Lambda function code runs in a sandbox environment provisioned and is managed by Lambda. As users do not control the environment, running an OpenTelemetry SDK and Collector in Lambda needs additional effort. For example, launching OpenTelemetry Collector and enabling auto-instrumentation in Lambda are not as straightforward as locally on Linux. 

I’d like to request a repo for the implementation which aims to provide a seamless OpenTelemetry user experience for Lambda users. The proposed repository name is *opentelemetry-lambda*

I propose that this repo will host the source code and development for the following:

- Lambda build layer supporting the OpenTelemetry Collector 
- Lambda build layer supporting the OpenTelemetry Python SDK
- Lambda build layer supporting the OpenTelemetry JavaScript SDK (NodeJS)
- Lambda apps for building OpenTelemetry Lambda layer using AWS CloudFormation
- Sample apps for how to use the OpenTelemetry Lambda layers for Collector and SDKs

*Repository structure*
I recommend a centralized repository for the OpenTelemetry Lambda support which supports both the Collector and the language SDKs as well as provides a great developer experience with sample apps and documentation. This repository structure also supports long-term maintenance including testing and releasing.

Here is the directory structure we are proposing:

*Directory*

open-telemetry/opentelemetry-lambda
                               |_ collector
                               |_ java
                               |_ python
                               |_ javascript
                               |_ ...

cc: @wangzlei

**Comment by wangzlei** [comment]
Thanks for raising proposal. AWS Lambda is a sandbox environment different with normal platform, we want this repo for supporting running OpenTelemetry Collector and language SDKs in AWS Lambda.

**Comment by alolita** [comment]
@SergeyKanzhelev please advise if I need to do anything else to get this repo setup 🙏

**Comment by SergeyKanzhelev** [comment]
Is it different from https://github.com/open-telemetry/opentelemetry-lambda-extension?

**Comment by codeboten** [comment]
As discussed in the Lambda working group meeting, the plan is to use the existing https://github.com/open-telemetry/opentelemetry-lambda repo. I think this issue can be closed if @wangzlei and @alolita are ok with it.

**Comment by bogdandrutu** [comment]
this is done correct? @alolita feel free to reopen if anything needed

**Comment by alolita** [comment]
Thanks @bogdandrutu we are working with @codeboten on using the current repo.
