### ISSUE TITLE
Create simple cases repositories for Open Telemetry by different language. 

### ISSUE THREAD

**Issue by chenmudu** [open-telemetry/community#627]
Open telemetry instrumentation libraries of different languages do not have an official warehouse group for how to use and observe the corresponding enhancement effect. Can we Create simple cases repositories for Open Telemetry instrumentation by different language? My personal views are as follows:

-  Help more people to understand the use of Otel, because the official introduction article is too simple.

-  There should be a repository of OpenTelemetry capabilities for each language, It should not be those example case directories.

-  These repositories should have more developers to contribute, as they can significantly increase Otel's influence from an official point of view.

Maybe like this warehouse ([Java case library based on SpringBoot](https://github.com/chenmudu/open-telemetry-java-guides)), this warehouse along with [docs-cn](https://github.com/open-telemetry/docs-cn/blob/main/README.md#%E7%9B%AE%E5%BD%95%E7%B4%A2%E5%BC%95) and [Chinese cloud native community Observability SIG](https://github.com/cloudnativeto/sig-observability) has helped a lot of Chinese who are not familiar with Open Telemetry. If possible, I hope I can contribute this warehouse to the otel community and maintain it.

Looking forward to official reply. Thanks a lot.

**Comment by paulsbruce** [comment]
@chenmudu In discussing with the OTel comms SIG today, I realize I'd love to clarify how I'm synthesizing your thoughts here. Would you be looking for 'tutorials' (as separate from feature docs), indicated by 'case library' and use cases topics? This would be a different ask than 'do we have a reference app with some instructions', which would also be useful but not the same as asking about tutorials, yes?

**Comment by chenmudu** [comment]
@paulsbruce 

Thank you very much for your reply. I'm sorry that my English is not very fluent. ❤

Yes, my personal point is that there is a lot of attention on Otel right now (at least from the Chinese people around me), but a lot of people are focused on what Otel can do for them (who may not know much about Otel), what it can bring to them personally or as a team, and best practices and recommendations.

I am grateful for the Read Me documentation in each warehouse, which helped me quickly set up at the beginning, when I was barely familiar with Otel.But there was so much more I wanted to know that I still had to go through the code(java/golang/others), which led me to ask a lot of questions that now seem silly. 😅

Some people might have the same problem, so I wrote a tutorial project on Otel to help others understand and contribute code to the community. 

So, I personally feel that there still need to be different guides project for different languages, just like the [sofa stack guides](https://github.com/sofastack-guides/).

Personally, I think such benefits are obvious, and I also hope to participate in the promotion of Otel to help more people. 

Finally, hope to get the official reply again. Thanks a lot. ❤

**Comment by trask** [comment]
hi @chenmudu! does the new(-ish) https://github.com/open-telemetry/opentelemetry-demo repository address your thoughts above?

**Comment by chenmudu** [comment]
> hi @chenmudu! does the new(-ish) https://github.com/open-telemetry/opentelemetry-demo repository address your thoughts above?

 LGMT. Thanks for remembering this issue.
