### ISSUE TITLE
About using licensed/non-OSS software in tests

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/community#629]
Java instrumentation repo uses different application servers for [its smoke tests](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/smoke-tests/matrix). Currently we use only open sourced servers on Ubuntu Linux. We build and host corresponding Docker images in GitHub Container Registry.

Now we want to add both Windows-based docker images and application servers that require accepting the EULA (namely [JBoss EAP](https://developers.redhat.com/products/eap/overview) and [Oracle WebLogic](https://www.oracle.com/middleware/technologies/weblogic.html)). Are there any legal objections to that? Can we build such images, publish them to GitHub Container Registry and use in our tests run as GitHub Actions?

If this is not the right place for such question, please advice.

**Comment by mtwo** [comment]
I'm not certain or the rules or guidance around this, but I'm guessing that one of @lizthegrey @sarahnovotny @tedsuo or @caniszczyk will know more

**Comment by lizthegrey** [comment]
As long as we are not distributing non-Apache licensed code with binaries, I believe it should be fine in general, however, which entity/who is accepting the EULA and publishing to container registry? That's going to be the sticking point, as you can't actually bind the opentelemetry project to the EULA...

**Comment by iNikem** [comment]
> which entity/who is accepting the EULA and publishing to container registry? That's going to be the sticking point, as you can't actually bind the opentelemetry project to the EULA...

Yes, this is exactly my concern. What we can do is to let one of the maintainers to accept EULA, build docker image locally and push to ghcr.io under OpenTelemetry org. To be used later for testing by CI.

**Comment by trask** [comment]
> we want to add both Windows-based docker images and application servers that require accepting the EULA (namely [JBoss EAP](https://developers.redhat.com/products/eap/overview) and [Oracle WebLogic](https://www.oracle.com/middleware/technologies/weblogic.html))

Windows is fine

We are not using any application servers that require accepting a EULA at this point (years later), and so closing this, but I think it's still an open question and so if anyone needs to accept a EULA it would be worth opening a new issue about it
