### ISSUE TITLE
REQUEST: New membership for Oberon00

### ISSUE THREAD

**Issue by AloisReitbauer** [open-telemetry/community#63]
### GitHub Username

@Oberon00

### Organization you are requesting membership in

open-telemetry/opentelemetry-python

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
Welcome @Oberon00
