### ISSUE TITLE
Request for a Workgroups repo for Prometheus and Lambda workgroups

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#631]
Based on the discussions in the governance committee, it was recommended to have a workgroups repo to file issues and track progress on these areas with project boards. I'd like to request a workgroup repo to track ongoing issues, relate to PRs and use project boards for each area of work. 

@andrewhsu @SergeyKanzhelev @tedsuo can you help create a workgroup repo wg-prometheus?

See a similar model being used in the Kubernetes project: https://github.com/kubernetes/community/tree/master/sig-security

**Comment by alolita** [comment]
To clarify, we will use https://github.com/open-telemetry/opentelemetry-lambda-extension as the wg-lambda repo. cc: @codeboten 

This request is only for the wg-prometheus repo.

**Comment by SergeyKanzhelev** [comment]
Created:

- team: https://github.com/orgs/open-telemetry/teams/wg-prometheus
- team has maintain permissions for https://github.com/open-telemetry/wg-prometheus/ so participants can manage boards
- merge is currently limited to technical-committee before the EasyCLA enabled

@alolita you are a maintainer of the team so you can add people to the working group

@bogdandrutu @lizthegrey please enable EasyCLA.

**Comment by alolita** [comment]
Thanks so much @SergeyKanzhelev
