### ISSUE TITLE
Restart Sampling SIG

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/community#632]
We had a sampling WG, but we paused it due to lack of interest/attendance. Interest seems to be back, so I would like to start the Sampling SIG it up again.

We need at least two kinds of members for this to work:
* Sampling experts who can triage requests and synthesize them into something coherent.
* Implementors who are willing to prototype collector/client implementations.

What we need to solve/avoid for this to work:
* Insistence that sampling should exactly match what company X is currently doing. We have found from past experience that no two existing backend implementations share the exact same sampling implementations. This creates a blocker for moving forwards on any form of sampling beyond backend-specific plugins. So we need participants who are willing to find a balance between ideal sampling algorithms for future implementations that can handle OTLP natively, and sampling algorithms that will be useful for currently existing backends.

For those who are interested, please respond with how you would like to contribute, and what your general availability is for zoom meetings.

**Comment by pyohannes** [comment]
I'd like to contribute.

I have experience in the sampling domain, but wouldn't call myself an expert. I could do prototyping work; I'm involved in the C++ SIG, and I'm also using the C# SDK quite extensively.

9am or 4pm PST would be ideal for me, no matter what day.

**Comment by tedsuo** [comment]
Thanks @pyohannes!

**Comment by alolita** [comment]
Hi @tedsuo +1 to restarting the sampling SIG. We've got some areas we're interested in contributing to e.g. different types of sampling - head-based, tail-based, dynamic. 

Times in late afternoon PST preferred.

**Comment by pmm-sumo** [comment]
Thank you @tedsuo for opening the issue. 

I am more focused on collector-side sampling, built some [custom extensions](https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/main/processor/cascadingfilterprocessor) with adaptive tail-sampling capabilities and others that were missing. I saw some other attempts at solving various related pain-points and would love if all of this could converge into a solid community-backed solution.

Unfortunately, for me the afternoon PST might be late (preferably, anything before 9pm CET would work, which is around noon PT)

**Comment by oertl** [comment]
Hi @tedsuo, I would like to contribute. I know very well the problems of consuming and extrapolating sampled data for which the sampling steps in the data processing chain are uncoordinated or not well defined. I live in the CET time zone, but otherwise I am flexible.

**Comment by tedsuo** [comment]
Thanks everyone for the interest! For those responding, would 9am Pacific on Friday work as a time? That slot is currently available and is CET-friendly. Is there anyone from Australia/Pacfic Rim looking to join? @alolita Is that why you were requesting late afternoon?

**Comment by oertl** [comment]
@tedsuo, time is okay but I would prefer any other day over Fridays.

**Comment by alolita** [comment]
@tedsuo I would like to recommend we alternate meetings between US West coast friendly and APAC friendly times if we cannot do 4-430p or 430-5p PT as the weekly time. I had recommended this time so that @anuraaga and others on APAC time could also join in.

**Comment by jpkrohling** [comment]
I would attend some sessions when they are in a friendly timezone to me (CET).

**Comment by pyohannes** [comment]
9am any day works for me any day. Alternating times (9am and 4pm) would work too, but preferably not 4pm Friday.

**Comment by carlosalberto** [comment]
Ping @tedsuo

**Comment by tedsuo** [comment]
Sorry for the hold up! :)

**Comment by paulosman** [comment]
I'd be happy to join as an implementor. I'm on central time and any of the suggested times work for me.

**Comment by carlosalberto** [comment]
What's the status of this?

**Comment by tedsuo** [comment]
Ok y'all, finally happening, we're starting the sampling SIG back up. The time which appears to work best is Thursday, 8am Pacific, so we will start with that time slot. First meeting will be next week, 7/8/2021. I'll follow up with everyone who said they were interested.

Agenda: https://docs.google.com/document/d/1gASMhmxNt9qCa8czEMheGlUW2xpORiYoD7dBD7aNtbQ/

**Comment by alolita** [comment]
This SIG has restarted. Closing issue.
