### ISSUE TITLE
REQUEST: New membership for andykellr

### ISSUE THREAD

**Issue by andykellr** [open-telemetry/community#634]
### GitHub Username

@andykellr 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @tigrannajaryan 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

Contributions to Stanza before move to OpenTelemetry
https://github.com/open-telemetry/opentelemetry-log-collection

https://github.com/observIQ/stanza/pull/243
https://github.com/observIQ/stanza/pull/242
https://github.com/observIQ/stanza/pull/237
https://github.com/observIQ/stanza/pull/234
https://github.com/observIQ/stanza/pull/232
https://github.com/observIQ/stanza/pull/231
https://github.com/observIQ/stanza/pull/171
https://github.com/observIQ/stanza/pull/154

- Issues responded to

- SIG projects I am involved with

Collector
Logs

**Comment by djaglowski** [comment]
I support.

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @andykellr!
