### ISSUE TITLE
REQUEST: New membership for jsirianni

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/community#635]
### GitHub Username

@jsirianni 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @tigrannajaryan 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

Contributions to Stanza before move to [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-log-collection)

- PRs reviewed / authored
  - https://github.com/observIQ/stanza/pull/239
  - https://github.com/observIQ/stanza/pull/240
  - https://github.com/observIQ/stanza/pull/244
  - https://github.com/observIQ/stanza/pull/245
  - https://github.com/observIQ/stanza/pull/247
- Issues responded to
  - https://github.com/observIQ/stanza/issues/238
- SIG projects I am involved with
  - Logs 

I work at observIQ where my responsibilities include maintaining Stanza by working directly with customers, developers, and product teams to implement new features and test bug fixes.

**Comment by djaglowski** [comment]
I support.

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @jsirianni!
