### ISSUE TITLE
REQUEST: New membership for tydhot

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/community#636]
### GitHub Username

@tydhot

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @anuraaga
- @tensorchen 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Aall+is%3Apr+author%3Atydhot+
https://github.com/open-telemetry/docs-cn/pulls?q=is%3Aall+is%3Apr+author%3Atydhot+

**Comment by anuraaga** [comment]
I support - thanks @tydhot for bringing the Chinese community to Java!

**Comment by tensorchen** [comment]
I support this request! Thank you @tydhot  for your contributions.

**Comment by SergeyKanzhelev** [comment]
Welcome, @tydhot! Invite sent
