### ISSUE TITLE
REQUEST: New membership for discostu105

### ISSUE THREAD

**Issue by AloisReitbauer** [open-telemetry/community#64]
### GitHub Username

@discostu105

### Organization you are requesting membership in

@open-telemetry/opentelemetry-dotnet

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @SergeyKanzhelev 
- @bogdandrutu

**Comment by discostu105** [comment]
:+1:

**Comment by SergeyKanzhelev** [comment]
@discostu105 welcome! I sent an invite to join the org
