### ISSUE TITLE
Grant following members edit rights in wg-prometheus repo

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#640]
@SergeyKanzhelev @mtwo 

Can you please grant the following members edit rights in the wg-prometheus repo? We are all triaging, approving and editing our OTel Prometheus tasks backlog and would like to have these rights. Please let me know if you need any other info.

rakyll@
punya@
jseureth@
dashpole@
RichiH@
tomwilkie@

**Comment by SergeyKanzhelev** [comment]
@alolita you are a maintainer of the working group

![image](https://user-images.githubusercontent.com/9950081/107393449-ac737180-6aaf-11eb-93c5-93ae3bcad281.png)

Just go here: https://github.com/orgs/open-telemetry/teams/wg-prometheus/members and grant permissions. Membership permissions to members and maintainer to maintainers.

**Comment by alolita** [comment]
Thanks @SergeyKanzhelev
