### ISSUE TITLE
REQUEST: New membership for @punya

### ISSUE THREAD

**Issue by punya** [open-telemetry/community#641]
### GitHub Username

@punya

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita
- @MrAlias

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Contributed [specification#1328](https://github.com/open-telemetry/opentelemetry-specification/pull/1328), [go#1481](https://github.com/open-telemetry/opentelemetry-go/pull/1481)
- Reviewed [go#1420](https://github.com/open-telemetry/opentelemetry-go/pull/1420), [go#1421](https://github.com/open-telemetry/opentelemetry-go/pull/1421), [go#1424](https://github.com/open-telemetry/opentelemetry-go/pull/1424)
- Currently working on [go#1467](https://github.com/open-telemetry/opentelemetry-go/issues/1467)

**Comment by MrAlias** [comment]
I support :+1:

**Comment by alolita** [comment]
I support Punya's membership.

**Comment by mtwo** [comment]
I support

________________________________

**Comment by bogdandrutu** [comment]
Invite sent
