### ISSUE TITLE
REQUEST: New membership for @richih

### ISSUE THREAD

**Issue by RichiH** [open-telemetry/community#642]
### GitHub Username

@richih

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

* @alolita 
* @SergeyKanzhelev 

### List of contributions to the OpenTelemetry project

* SIG Metrics
* Prometheus WG

**Comment by bogdandrutu** [comment]
I support this even if I was not added as a sponsor :)

**Comment by alolita** [comment]
I support @RichiH for membership. 🎉

**Comment by mtwo** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Invite sent! Welcome!

**Comment by RichiH** [comment]
Thanks, everyone :)
