### ISSUE TITLE
REQUEST: New membership for rakyll

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/community#643]
### GitHub Username

rakyll

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @SergeyKanzhelev 
- @bogdandrutu 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored: https://github.com/open-telemetry/opentelemetry-collector/commits?author=rakyll, https://github.com/open-telemetry/opentelemetry-go/commits?author=rakyll
- Issues responded to: https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+involves%3Arakyll+is%3Aclosed https://github.com/open-telemetry/opentelemetry-specification/issues?q=is%3Aissue+is%3Aopen+involves%3Arakyll https://github.com/open-telemetry/opentelemetry-go/issues?q=is%3Aissue+is%3Aopen+involves%3Arakyll
- SIG projects I am involved with: http://github.com/open-telemetry/wg-prometheus/

**Comment by alolita** [comment]
I strongly support one of the original contributors to our now "Collector" for membership to the project. Welcome Jaana!!! 🎉

**Comment by mtwo** [comment]
I support! Welcome back Jaana!

**Comment by bogdandrutu** [comment]
Invite sent, welcome @rakyll

**Comment by rakyll** [comment]
Thank you all!
