### ISSUE TITLE
REQUEST: New membership for srprash

### ISSUE THREAD

**Issue by srprash** [open-telemetry/community#644]
### GitHub Username

@srprash

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @cijothomas 
- @alolita 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-dotnet/pull/1436
- https://github.com/open-telemetry/opentelemetry-dotnet/pull/1618
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/59
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/61
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/63
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/64
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/66

#### Issues responded to
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/57

#### SIG projects I am involved with
- OpenTelemetry .Net SIG

**Comment by cijothomas** [comment]
I support

**Comment by alolita** [comment]
I support Prashant's membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @srprash! Invite sent

**Comment by srprash** [comment]
Thank you all! :)

**Comment by srprash** [comment]
Hey @SergeyKanzhelev 
I can't seem to find the invite in my attached email inbox. Can you verify the invite and re-send it? Thanks.

**Comment by srprash** [comment]
Oh wait. NVM. Found it on the OpenTelemetry-CNCF page as a popup. I'm in! :D
