### ISSUE TITLE
REQUEST: New membership for @lonewolf3739

### ISSUE THREAD

**Issue by lonewolf3739** [open-telemetry/community#645]
### GitHub Username

@lonewolf3739

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lzchen 
- @aabmass 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Authored [20+ PRs in opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python/pulls?q=is%3Amerged+is%3Apr+author%3Alonewolf3739+) and [15+ PRs in opentelemetry-python-contrib](https://github.com/open-telemetry/opentelemetry-python-contrib/pulls?q=is%3Amerged+is%3Apr+author%3Alonewolf3739+)
- [Reviewed PRs](https://github.com/search?q=org:open-telemetry+is:pr+reviewed-by:lonewolf3739)
- [Issues responded to](https://github.com/search?q=org:open-telemetry+is:issue+commenter:lonewolf3739)
- SIG projects I am involved with: `opentelemetry-python` and `opentelemetry-python-contrib`

**Comment by lzchen** [comment]
I support

**Comment by aabmass** [comment]
I support

**Comment by bogdandrutu** [comment]
Invite sent, welcome @lonewolf3739
