### ISSUE TITLE
REQUEST: New membership for TomRoSystems

### ISSUE THREAD

**Issue by TomRoSystems** [open-telemetry/community#647]
### GitHub Username

TomRoSystems

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lalitb
- @jkwatson

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  1. [otel-cpp #523 Adding B3 propagator](https://github.com/open-telemetry/opentelemetry-cpp/pull/523)
  2. [otel-cpp #447 Improvement for OTLP example](https://github.com/open-telemetry/opentelemetry-cpp/pull/447)
  3. [otel-cpp #522 OTLP change default port number](https://github.com/open-telemetry/opentelemetry-cpp/pull/522)
- Issues responded to
  1. [otel-cpp Rename HTTPTextFormat to TextMapPropagator #536](https://github.com/open-telemetry/opentelemetry-cpp/issues/536)
- SIG projects I am involved with
`opentelemetry-cpp`

**Comment by jkwatson** [comment]
I approve! 👍

**Comment by lalitb** [comment]
Approved

**Comment by bogdandrutu** [comment]
Welcome @TomRoSystems , invitation sent, you will receive a notification/email to accept it.
