### ISSUE TITLE
REQUEST: New membership for @gramidt

### ISSUE THREAD

**Issue by gramidt** [open-telemetry/community#648]
### GitHub Username

@gramidt

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu
- @anuraaga

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - opentelemetry/opentelemetry-collector-contrib
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2262
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2292
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2285
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1965
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2131
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2024
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1929
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1928
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1900
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1849
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1914
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1892
    - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1891
  - opentelemetry/opentelemetry-collector
    - https://github.com/open-telemetry/opentelemetry-collector/pull/2157
  - opentelemetry/opentelemetry-operator
    - https://github.com/open-telemetry/opentelemetry-operator/pull/171
  - opentelemetry/community
    - https://github.com/open-telemetry/community/pull/637
  - opentelemetry/opentelemetry.io
    - https://github.com/open-telemetry/opentelemetry.io/pull/368
    - https://github.com/open-telemetry/opentelemetry.io/pull/369
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-operator/issues/170
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1894
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1963
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1964
  - https://github.com/open-telemetry/opentelemetry-operator/issues/128
  - https://github.com/open-telemetry/opentelemetry-operator/issues/56
  - https://github.com/open-telemetry/opentelemetry-operator/issues/35
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2289
  - https://github.com/open-telemetry/opentelemetry-operator/issues/128
- SIG projects I am involved with
  - I have been attending the following SIGs regularly for ~2 months.
    - Agent/Collector SIG
    - Golang SIG
    - Specs SIG
    - Metrics SIG
- Plus, I have helped out multiple community members within Gitter and I have held multiple Zoom calls to help them troubleshoot their issues.

**Comment by anuraaga** [comment]
I support - thanks for looking through so many aspects of the collector @gramidt!

**Comment by bogdandrutu** [comment]
+1

**Comment by bogdandrutu** [comment]
Welcome @gramidt, invitation sent
