### ISSUE TITLE
REQUEST: New membership for @tomwilkie

### ISSUE THREAD

**Issue by tomwilkie** [open-telemetry/community#658]
### GitHub Username

@tomwilkie

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita
- @SergeyKanzhelev 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Issues responded to: see https://github.com/open-telemetry/wg-prometheus/issues
- SIG projects I am involved with: metrics & prometheus

**Comment by SergeyKanzhelev** [comment]
Happy to sponsor you.

**Comment by tomwilkie** [comment]
Thanks you @SergeyKanzhelev!

**Comment by alolita** [comment]
+1 I support Tom's membership!

**Comment by SergeyKanzhelev** [comment]
Welcome, @tomwilkie! Invite sent
