### ISSUE TITLE
REQUEST: New membership for MSNev

### ISSUE THREAD

**Issue by MSNev** [open-telemetry/community#666]
### GitHub Username
@MSNev

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan 
- @lzchen

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - Authored 4 - https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+author%3AMSNev+
  - Reviewed lots (30+) - https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+reviewed-by%3AMSNev
    - and https://github.com/open-telemetry/opentelemetry-js-api/pulls?q=is%3Apr+commenter%3AMSNev+
    
- Issues responded to
  - Commenter: (10) - https://github.com/open-telemetry/opentelemetry-js/issues?q=is%3Aissue+commenter%3AMSNev
  - Created: https://github.com/open-telemetry/opentelemetry-js/issues/created_by/MSNev
  - Mentions: https://github.com/open-telemetry/opentelemetry-js/issues?q=is%3Aissue+MSNev+mentions%3AMSNev

- SIG projects I am involved with
  - OpenTelementry-Node/Browser (JS)
  - OpenTelemetry-Metrics
  - OpenTelemetry-Logs
  - Specs & Maintainers sync's

**Comment by MSNev** [comment]
@dyladan and @lzchen

**Comment by dyladan** [comment]
I support

**Comment by lzchen** [comment]
I support this man.

**Comment by SergeyKanzhelev** [comment]
welcome, @MSNev! Invite sent
