### ISSUE TITLE
Propose creation of new SIG for OpenTelemetry-Swift SDK

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/community#668]
I'd like to start a SIG meeting for maintainers/contributors of the [OpenTelemetry-Swift SDK](https://github.com/open-telemetry/opentelemetry-swift). 

Here are a few topics a SIG could address:

- Adherence to Open Telemetry Spec
- Instrumentation discussion
- Implementation details discussion
- Roadmap discussion
- Getting additional input from TC

I would like to propose starting with a meeting every other week initially. 

@nachoBonafonte, adding you for input :)

**Comment by nachoBonafonte** [comment]
Yes, I like the idea. Until now I had been the only stable contributor to the project, so I saw no need to organize it. But if there is more people interested in contributing regularly to the project I think is completely needed. 
I would propose moving this organization to the CNCF slack channel for [otel-swift] (https://cloud-native.slack.com/archives/C01NCHR19SB), just for fluidity.

**Comment by nachoBonafonte** [comment]
I propose doing the first SIG  meeting next Thursday 17:00 GMT, that i think works for all who show interest in slack. I will ask how to create the event and links for it.

**Comment by SergeyKanzhelev** [comment]
> I will ask how to create the event and links for it.

https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md

**Comment by nachoBonafonte** [comment]
Hi @SergeyKanzhelev, I have been able to create the event at the calendar but have not been able to connect to the `tomato` Zoom room (I think it is clashing with my own company zoom account and shows our rooms ) or add `OpenTelemetry Calendar Invites Google Group` as a participant.

**Comment by SergeyKanzhelev** [comment]
Maybe just paste a link to the Otel zoom in description?

**Comment by nachoBonafonte** [comment]
Yes, that was it, I was expecting some more integration, sorry

**Comment by nachoBonafonte** [comment]
SIG meeting is ready, i think all configuration is already done:
[https://calendar.google.com/calendar/event?eid=MzZiMXFuYnY2cnUycjdydG5lZjRiNXZ0a2YgZ29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBn](https://calendar.google.com/calendar/event?eid=MzZiMXFuYnY2cnUycjdydG5lZjRiNXZ0a2YgZ29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBn)

Thanks for the help

**Comment by SergeyKanzhelev** [comment]
np. I wouldn't be able to join, let me know if any help is needed.

**Comment by SergeyKanzhelev** [comment]
this is complete
