### ISSUE TITLE
REQUEST: New membership for jcchavezs

### ISSUE THREAD

**Issue by jcchavezs** [open-telemetry/community#669]
### GitHub Username

@jcchavezs

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu
- @anuraaga

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/484
- https://github.com/open-telemetry/opentelemetry-collector/issues/2443
- https://github.com/open-telemetry/opentelemetry-go/pull/1328
- https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Ajcchavezs+is%3Aclosed

**Comment by anuraaga** [comment]
I support - good to see you here @jcchavezs

**Comment by bogdandrutu** [comment]
Invite sent, thank you

**Comment by jcchavezs** [comment]
Thanks guys!

José Carlos Chávez


ons. 3. mar. 2021 kl. 17:20 skrev Bogdan Drutu <notifications@github.com>:
