### ISSUE TITLE
REQUEST: New membership for wph95

### ISSUE THREAD

**Issue by WPH95** [open-telemetry/community#670]
### GitHub Username

@wph95 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @XSAM 
- @djaglowski 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

https://github.com/pulls?q=author%3AWPH95+org%3Aopen-telemetry

- PRs reviewed / authored

  https://github.com/pulls?q=is%3Apr+author%3AWPH95+org%3Aopen-telemetry [28 PRs]

- Issues responded to

  https://github.com/issues?q=is%3Aissue+author%3AWPH95+org%3Aopen-telemetry  [5 Issues]

- SIG projects I am involved with
	- SIG Website
	- SIG Specification: Logs

**Comment by djaglowski** [comment]
I support

**Comment by XSAM** [comment]
I support WPH95's membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @WPH95! Invite sent
