### ISSUE TITLE
REQUEST: New membership for MadVikingGod

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/community#671]
### GitHub Username

@MadVikingGod

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias 
- @Aneurysm9 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-proto-go/pull/1
  - https://github.com/open-telemetry/opentelemetry-proto-go/pull/5
  - https://github.com/open-telemetry/opentelemetry-go/pull/1586
  - https://github.com/open-telemetry/opentelemetry-go-vanityurls/pull/11
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-go/issues/1632
  - https://github.com/open-telemetry/opentelemetry-go/issues/1603
- SIG projects I am involved with
  - go sig

**Comment by Aneurysm9** [comment]
I support this membership application!

**Comment by MrAlias** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @MadVikingGod! Invite sent
