### ISSUE TITLE
Ruby SIG meeting time seems incorrect in README

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#673]
Otel Calendar shows Ruby meeting on Tuesdays 9am PT, [README](https://github.com/open-telemetry/community#special-interest-groups) shows Thursday.

**Comment by tigrannajaryan** [comment]
@fbogsany can you please clarify?

**Comment by fbogsany** [comment]
Sorry, I will update the README. The Otel Calendar is correct.
