### ISSUE TITLE
REQUEST: New membership for <zsistla>

### ISSUE THREAD

**Issue by zsistla** [open-telemetry/community#675]
### GitHub Username

@zsistla

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bobstrecansky 
- @beniamin

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-php/pull/250
https://github.com/open-telemetry/opentelemetry-php/pull/215
https://github.com/open-telemetry/opentelemetry-php/pull/204
https://github.com/open-telemetry/opentelemetry-php/pull/141
https://github.com/open-telemetry/opentelemetry-php/pull/94
https://github.com/open-telemetry/opentelemetry-php/pull/158
https://github.com/open-telemetry/opentelemetry-php/pull/157
https://github.com/open-telemetry/opentelemetry-php/pull/276
https://github.com/open-telemetry/opentelemetry-php/pull/275

- Issues responded to
https://github.com/open-telemetry/opentelemetry-php/issues/141
https://github.com/open-telemetry/opentelemetry-php/issues/118
https://github.com/open-telemetry/opentelemetry-php/issues/117
https://github.com/open-telemetry/opentelemetry-php/issues/115
https://github.com/open-telemetry/opentelemetry-php/issues/93
https://github.com/open-telemetry/opentelemetry-php/issues/238

- SIG projects I am involved with
PHP SIG

**Comment by bobstrecansky** [comment]
I support this membership application!

**Comment by beniamin** [comment]
I support this membership application!

**Comment by SergeyKanzhelev** [comment]
Welcome, @zsistla! Invite sent
