### ISSUE TITLE
REQUEST: New membership for mxiamxia

### ISSUE THREAD

**Issue by mxiamxia** [open-telemetry/community#677]
### GitHub Username
@mxiamxia

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @bogdandrutu 

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs reviewed / authored
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2317
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2271
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2196
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1256
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1730
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1623
* ...
#### Issues responded to
- https://github.com/open-telemetry/opentelemetry-specification/issues/617
- https://github.com/open-telemetry/opentelemetry-collector/issues/2209
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1395
#### SIG projects I am involved with
* Opentelemetry Collector
* Opentelemetry Metrics
* Opentelemetry Prometheus
* Opentelemetry Lambda

**Comment by alolita** [comment]
+1 Welcome Min!

**Comment by bogdandrutu** [comment]
Invite sent
