### ISSUE TITLE
REQUEST: New membership for pellared

### ISSUE THREAD

**Issue by pellared** [open-telemetry/community#678]
### GitHub Username

@pellared

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pjanotti
- @tonyredondo

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [PRs authored](https://github.com/pulls?q=author%3Apellared+org%3Aopen-telemetry+is%3Apr)
- [PRs reviewed](https://github.com/pulls?q=reviewed-by%3Apellared+org%3Aopen-telemetry+is%3Apr) 
- [Issues responded to](https://github.com/issues?q=org%3Aopen-telemetry+commenter%3Apellared+is%3Aissue)
- SIG projects I am involved with: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

**Comment by tonyredondo** [comment]
Approve

**Comment by pjanotti** [comment]
I support

**Comment by jkwatson** [comment]
We need to get the `gitter channel` out of here, and replace it with slack, I think.

Also, I support this.

**Comment by SergeyKanzhelev** [comment]
> We need to get the `gitter channel` out of here, and replace it with slack, I think.

already done

**Comment by SergeyKanzhelev** [comment]
Welcome, @pellared! Invite sent
