### ISSUE TITLE
REQUEST: New membership for wangzlei

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/community#679]
### GitHub Username

@wangzlei

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alrex
- @anuraaga 

#### PRs reviewed / authored
- https://github.com/open-telemetry/opentelemetry-java/pull/1369
- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/621
#### Issues responded to
- https://github.com/open-telemetry/opentelemetry-python-contrib/issues/298

**Comment by anuraaga** [comment]
+1 - thanks for the help @wangzlei!

**Comment by alolita** [comment]
+1 Welcome @wangzlei

**Comment by SergeyKanzhelev** [comment]
can you pls clarify @Alrex eligibility for being a sponsor.

**Comment by anuraaga** [comment]
@codeboten Can you take a look at this? Looks like Lei got the username wrong

**Comment by codeboten** [comment]
+1 happy to have @wangzlei join OpenTelemetry

**Comment by SergeyKanzhelev** [comment]
Welcome, @wangzlei! Invite sent

**Comment by wangzlei** [comment]
@SergeyKanzhelev Please re-send the invite, sorry that the previous one is expired.

**Comment by SergeyKanzhelev** [comment]
Done

**Comment by wangzlei** [comment]
Joined, thank!
