### ISSUE TITLE
REQUEST: New membership for fbogsany

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/community#68]
### GitHub Username

@fbogsany

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [x] I ~am~ will be actively contributing to 1 or more OpenTelemetry subprojects
  - I will actively contribute to the OpenTelemetry Ruby subproject
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu
- @flands

**Comment by flands** [comment]
Approved

**Comment by bogdandrutu** [comment]
+1

Before we start we need to find:
1. One of the TC members to help with monitoring the overall changes.
1. Another maintainer + 1 approver to form the SIG.

**Comment by SergeyKanzhelev** [comment]
@fbogsany welcome!

**Comment by fbogsany** [comment]
Thank you!
