### ISSUE TITLE
Consider allowing instrumentation to be maintained in external repos.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/community#680]
There have been discussions regarding maintaining/shipping instrumentation from repos outside the main OpenTelemetry organization, given that:

- There are only so many maintainers/approvers, which may result in constant bottlenecks regarding code approvals and releases.
- There can be instrumentation code for _everything_ out there, including components for rather **exotic** or **experimental** components, with exponential growth, component count wise.

Because of this, it may be important to define that:

1. Instrumentation for many well-used components (think of Django/Flask for Python or Spring/Okhttp for Java) resides within the OpenTelemetry repos.
2. Additional instrumentation for further components (think of some new, experimental OSS library) can be released as a 'contrib' package, while being maintained in an external organization/repo.

The OpenTelemetry Registry hence would become a **core** component (which probably already is). 

An alternative would be to have an approach similar to the Collector Contrib repo, where you have CODEOWNERS per directory, but there's the fear this approach just won't work nor scale well for instrumentation components.

**Comment by iNikem** [comment]
My current proposal as to how we can move forward with this issue is [documented here](https://docs.google.com/document/d/1YNRCg9fdjJgZRs56vvf7rfFPk06mhp781sWHYypOaAk/edit#heading=h.xdwfdouv37cn)

**Comment by mtwo** [comment]
I left comments on @iNikem's proposal, as has @dyladan has as well. Once we get a few other reviews in the doc, then I suggest that we turn this into an OTep / PR.

**Comment by SergeyKanzhelev** [comment]
CC @jsuereth

**Comment by iNikem** [comment]
@carlosalberto can we now close this issue as we have accepted OTEP https://github.com/open-telemetry/oteps/blob/main/text/0155-external-modules.md?
