### ISSUE TITLE
REQUEST: New membership for @mattmccleary

### ISSUE THREAD

**Issue by mattmccleary** [open-telemetry/community#682]
### GitHub Username
@mattmccleary
Requesting access to global triagers.

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tedsuo 
- @reyang

**New!**: Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

**PRs reviewed / authored**
- https://github.com/open-telemetry/opentelemetry-specification/pull/1335

Issues created/responded to
- https://github.com/open-telemetry/community/issues/681

SIG projects I am involved with
- Convenience API
- User Research Proposal
- Maintainer, Spec SIGs

**Comment by reyang** [comment]
Welcome @mattmccleary!

**Comment by SergeyKanzhelev** [comment]
Happy to sponsor as well!

Welcome, @mattmccleary! Invite sent
