### ISSUE TITLE
REQUEST: New membership for willarmiros

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/community#686]
### GitHub Username

@willarmiros

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @anuraaga
- @dyladan

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

   * https://github.com/open-telemetry/opentelemetry-js-contrib/pull/366
   * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1585
   * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1428
   * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1360
   * https://github.com/open-telemetry/opentelemetry-collector/pull/2365
   * https://github.com/open-telemetry/opentelemetry-collector/pull/1994
   * https://github.com/open-telemetry/opentelemetry-specification/pull/1112
   * https://github.com/open-telemetry/opentelemetry-specification/pull/1099
   * https://github.com/open-telemetry/opentelemetry-specification/pull/1422 (review)
   * https://github.com/open-telemetry/opentelemetry-specification/pull/1442 (review)

- Issues responded to

  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1355
  * https://github.com/open-telemetry/opentelemetry-js-contrib/issues/345
  * https://github.com/open-telemetry/opentelemetry-js-contrib/issues/333
  * https://github.com/open-telemetry/opentelemetry-specification/issues/1151
  * https://github.com/open-telemetry/opentelemetry-specification/issues/1098

- SIG projects I am involved with
  * OTel JS SIG
  * OTel Collector SIG

**Comment by dyladan** [comment]
I support

**Comment by anuraaga** [comment]
I support - thanks @willarmiros !

**Comment by SergeyKanzhelev** [comment]
Welcome, @willarmiros! Invite sent
