### ISSUE TITLE
Need an org-scoped access token for docs automation

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#690]
We're implementing a solution for allowing authoritative website docs to live in each SIG repository, but the automation will need a PAT or other token that can create PR's in the website repository. You can see the issue in this PR: https://github.com/open-telemetry/opentelemetry-java/pull/3080

**Comment by SergeyKanzhelev** [comment]
Here we discussed that PAT from one of SIG members may be used: https://github.com/open-telemetry/community/issues/551 Or SIG-specific bot account created. SIG members are in the best position to maintain this.

If you have a better idea in mind on how to manage this - please comment.

**Comment by anuraaga** [comment]
Hi @SergeyKanzhelev - to give more context, this is about the shared docs repo at https://github.com/open-telemetry/opentelemetry.io and not quite a SIG-specific request. Each SIG will host their language's documentation in their repo, but we will have automation to push the code changes into that shared repo for deployment to opentelemetry.io. So we need a token with push access to the shared repo - I don't think we should expect SIGs to have to maintain this. As it stands, for example, Java maintainers do not have write access to that repo, so there's not really anything we can do to make the automation work.

I'd recommend as this is an open-telemetry shared process / account, there be an organization secret with a TC member PAT in it (I guess TC members would have write access to all the repos including opentelemetry.io) and expose that to language repos for use in this workflow. Does it make sense?

**Comment by SergeyKanzhelev** [comment]
I understand the context, but wouldn't any website's SIG member token work for the purpose of merging to website repository? Or create a PR so it may be manually approved.

I'm advocating for less dependencies and more independence.

**Comment by trask** [comment]
@austinlparker do you still have this need?
