### ISSUE TITLE
REQUEST: New membership for dszmigielski

### ISSUE THREAD

**Issue by dszmigielski** [open-telemetry/community#692]
### GitHub Username

@dszmigielski

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pjanotti 
- @nrcventura

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [PRs authored](https://github.com/pulls?q=author%3Adszmigielski+org%3Aopen-telemetry+is%3Apr)
- [PRs reviewed](https://github.com/pulls?q=reviewed-by%3Adszmigielski+org%3Aopen-telemetry+is%3Apr)
- SIG projects I am involved with: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

**Comment by pjanotti** [comment]
I support

**Comment by nrcventura** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @dszmigielski! Invite sent
