### ISSUE TITLE
CNCF AWS account - OpentelemetryJava instrumentation integration tests usage

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/community#693]
Java instrumentation got access to CNCF sponsored AWS account in of #392 
As a part of an effort to enhance and stabilise integration tests (specifically - AWS SDK, Apache Camel) we'd like to create a separate suite, run along with the Nightly build and operating on a "live" AWS instance (as opposed to current localstack / elasticmq approach). This has been described here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2585
I did a rough cost calculation, it's available here: https://calculator.aws/#/estimate?id=da24f17fb99cdef7e7ac794e1e0b381e64b41ddb Costs are not high as there are only a few tests that would currently need to run with live AWS.
Kindly let me know how to proceed with the approval.

**Comment by SergeyKanzhelev** [comment]
CC: @mtwo @alolita you were working on enabling this, correct? Perhaps, the process can be documented somewhere in community repository. Perhaps, https://github.com/open-telemetry/community/blob/main/assets.md can be updated?

**Comment by mtwo** [comment]
I think that @iNikem and @trask have access to accounts that we already use use (see #392). Happy to add this to https://github.com/open-telemetry/community/blob/main/assets.md.

Is the best process for me to contact the CNCF service desk and add @kubawach's email address as a user? Or do we have a shared account that we share credentials for? I assume that the first option is correct but I want to confirm.

**Comment by kubawach** [comment]
@mtwo AFAIK credentials of the CNCF AWS account are added as secret to opentelemetry-java-instrumentation CI so I could easily use them, once the ask is approved.

**Comment by mtwo** [comment]
Ah, understood. In that case, I'm good with it as long as one of the other Java maintainers signs off. @jkwatson @anuraaga, do you approve?

**Comment by anuraaga** [comment]
@mtwo Yeah this request is good, thanks!

**Comment by mtwo** [comment]
Thanks, approved! Jakub, do you need anything else from us to proceed?

________________________________

**Comment by kubawach** [comment]
I guess that's it, just needed an official approval for (very slightly) increased costs of the AWS account. Thanks, will proceed with implementation then :)

**Comment by kubawach** [comment]
I guess that's it, just needed an official approval for (very slightly) increased costs of the AWS account. Thanks, will proceed with implementation then :)
