### ISSUE TITLE
REQUEST: New membership for jack-berg

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/community#694]
### GitHub Username

@jack-berg

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alanwest
- @nrcventura
- @jkwatson
- @a-feld

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java/pull/3086) - Fix bug where AsynchronousInstrumentAccumulator does not call configured LabelProcessorFactory. (#3085)
- [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java/pull/3079) - Add autoconfiguration SdkMeterProviderConfigurer SPI. (#3060)
- [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java/pull/3071) - Move registerView from SdkMeterProvider to SdkMeterProviderBuilder. (#3060)
- [opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java/pull/3067) - Convert DoubleSummaryData to DoubleSummary protos. (#3066)

**Comment by a-feld** [comment]
I support

**Comment by jkwatson** [comment]
I support as well!

**Comment by alanwest** [comment]
Whoohoo! I support this.

**Comment by nrcventura** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @jack-berg! invite sent
