### ISSUE TITLE
REQUEST: New membership for seh

### ISSUE THREAD

**Issue by seh** [open-telemetry/community#695]
### GitHub Username

@seh

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias
- @Aneurysm9 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - open-telemetry/opentelemetry-go#627 
  - open-telemetry/opentelemetry-go#656
  - open-telemetry/opentelemetry-go#698
  - open-telemetry/opentelemetry-go#701
  - open-telemetry/opentelemetry-go#1078
  - open-telemetry/opentelemetry-go#1258
  - open-telemetry/opentelemetry-go#1261
  - open-telemetry/opentelemetry-go#1608
  - open-telemetry/opentelemetry-go#1612
  - open-telemetry/opentelemetry-go#1702
  - open-telemetry/opentelemetry-go#1733
  - open-telemetry/opentelemetry-go-contrib#505
- Issues responded to
  - open-telemetry/opentelemetry-go-contrib#399
  - open-telemetry/opentelemetry-specification#586
  - open-telemetry/opentelemetry-specification#948
  - open-telemetry/opentelemetry-specification#1073
  - open-telemetry/opentelemetry-specification#1089
  - open-telemetry/oteps#148
- [SIG projects](https://github.com/open-telemetry/community#special-interest-groups) I am involved with
  - Go language SDK

**Comment by MrAlias** [comment]
I approve

**Comment by Aneurysm9** [comment]
I approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @seh! Invite sent
