### ISSUE TITLE
REQUEST: New membership for seemk

### ISSUE THREAD

**Issue by seemk** [open-telemetry/community#699]
### GitHub Username

seemk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lalitb
- @iNikem 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- [opentelemetry-cpp-contrib](https://github.com/open-telemetry/opentelemetry-cpp-contrib) - [nginx instrumentation](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx) (https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/5, https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/6, https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/10)
- [opentelemetry-cpp](https://github.com/open-telemetry/opentelemetry-cpp) - jaeger propagator (https://github.com/open-telemetry/opentelemetry-cpp/pull/599)
- [opentelemetry-cpp](https://github.com/open-telemetry/opentelemetry-cpp) - propagators refactor (https://github.com/open-telemetry/opentelemetry-cpp/pull/608)
- [opentelemetry-js-contrib](https://github.com/open-telemetry/opentelemetry-js-contrib) - [net instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-net) (https://github.com/open-telemetry/opentelemetry-js-contrib/pull/389)
- [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js) - fix http instrumentation's child span linking (https://github.com/open-telemetry/opentelemetry-js/pull/2046)
- [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python) - fix auto instrumentation with OTLP exporter (https://github.com/open-telemetry/opentelemetry-python/pull/1657)

**Comment by iNikem** [comment]
I support

**Comment by lalitb** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @seemk! Invite sent
