### ISSUE TITLE
REQUEST: New membership for trwegner

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#70]
### GitHub Username

e.g. @trwegner

### Organization you are requesting membership in

e.g. (at)open-telemetry .NET SIG

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @SergeyKanzhelev 
- @austinlparker

### List of contributions to the OpenTelemetry project

https://github.com/open-telemetry/opentelemetry-dotnet/pull/36
https://github.com/open-telemetry/opentelemetry-dotnet/pull/37
https://github.com/open-telemetry/opentelemetry-dotnet/pull/38

**Comment by austinlparker** [comment]
OK with me
