### ISSUE TITLE
REQUEST: New membership for humivo

### ISSUE THREAD

**Issue by humivo** [open-telemetry/community#701]
### GitHub Username

@humivo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @MrAlias 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Modify ForceFlush to abort after timeout/cancellation [Issue #1618](https://github.com/open-telemetry/opentelemetry-go/issues/1618).  Resolved this issue and it was merged into the main repo. PR: [PR #1757](https://github.com/open-telemetry/opentelemetry-go/pull/1757)
- Make ExportSpans for Jaeger Exporter honor deadline [Issue #1730](https://github.com/open-telemetry/opentelemetry-go/issues/1730).  Resolved this issue and it was merged into the main repo. PR: [PR #1773](https://github.com/open-telemetry/opentelemetry-go/pull/1773)
- Change constants in obsreport_exporter.go to private and add getter methods [Issue #2641](https://github.com/open-telemetry/opentelemetry-collector/issues/2641). Opened up a PR for this issue against the main repo and awaiting approval. PR: [PR #2895](https://github.com/open-telemetry/opentelemetry-collector/pull/2895)
- Regularly participate in the following weekly meetings:
    * OpenTelemetry Specification SIG
    * OpenTelemetry Data Model SIG
    * Prometheus WG
    * Agent/Collector SIG
    * OpenTelemetry Metrics API/SDK SIG
    * Golang SIG

**Comment by MrAlias** [comment]
I approve

**Comment by alolita** [comment]
I support membership for @humivo

**Comment by SergeyKanzhelev** [comment]
Welcome, @humivo! Invite sent
