### ISSUE TITLE
REQUEST: New membership for cynthiakedu

### ISSUE THREAD

**Issue by cynthiakedu** [open-telemetry/community#702]
GitHub Username

@cynthiakedu

Requirements

* [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
* [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
* [X] Slack channel (https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
* [X] I am actively contributing to 1 or more OpenTelemetry subprojects
* [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
* [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors

* @alolita
* @MrAlias

List of contributions to the OpenTelemetry project

* PRs reviewed / authored
    * https://github.com/open-telemetry/opentelemetry-go/pull/1772
    * https://github.com/open-telemetry/opentelemetry-python-contrib/pull/413
* SIG Projects and Meetings I participate in
    * specifications
        * Metrics Data Model
        * Metrics API/SDK 
    * Agent/Collector
    * Golang

**Comment by MrAlias** [comment]
I approve

**Comment by alolita** [comment]
I approve membership for @cynthiakedu

**Comment by SergeyKanzhelev** [comment]
Welcome, @cynthiakedu! Invite sent
