### ISSUE TITLE
REQUEST: New membership for IrisTuntun

### ISSUE THREAD

**Issue by IrisTuntun** [open-telemetry/community#703]
### GitHub Username

@IrisTuntun

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @MrAlias 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - https://github.com/open-telemetry/opentelemetry-go/pull/1753
   - https://github.com/open-telemetry/opentelemetry-go/pull/1776
   - https://github.com/open-telemetry/opentelemetry-specification/pull/1602
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-go/issues/1699
  - https://github.com/open-telemetry/opentelemetry-go/issues/1762
  - https://github.com/open-telemetry/opentelemetry-java/issues/3084
- SIG meetings I participate in: 
  -  Specification: General
  -  Specification: Metrics Data Model
  -  OpenTelemetry Prometheus Workgroup
  -  Agent/Collector
  - Golang

**Comment by harshita19244** [comment]
Just a question, are you only applying for membership or are you an outreachy contributor?

**Comment by MrAlias** [comment]
I approve

**Comment by alolita** [comment]
I approve membership for @IrisTuntun

**Comment by SergeyKanzhelev** [comment]
Welcome, @IrisTuntun! Invite sent
