### ISSUE TITLE
REQUEST: New membership for paulsbruce

### ISSUE THREAD

**Issue by paulsbruce** [open-telemetry/community#705]
### GitHub Username

e.g. @paulsbruce

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @austinlparker 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Request from Austin for help to approve PRs on the community project
- Issues responded to (None)
- SIG projects I am involved with (None)

**Comment by austinlparker** [comment]
approved

**Comment by austinlparker** [comment]
This should be for @open-telemetry/docs-approvers

**Comment by paulsbruce** [comment]
Per the Communications SIG meetings I've been attending, there are a few things that Austin says he could use help on. This would be my first significant contribution activity.

**Comment by SergeyKanzhelev** [comment]
assuming @mtwo support as well.

Welcome, @paulsbruce! Invite sent

**Comment by paulsbruce** [comment]
@SergeyKanzhelev so sorry for this, but the invite went too junk and now it's expired. can you re-send?

**Comment by SergeyKanzhelev** [comment]
done
