### ISSUE TITLE
REQUEST: New membership for @shelbyspees

### ISSUE THREAD

**Issue by shelbyspees** [open-telemetry/community#706]
### GitHub Username

@shelbyspees

I would like to be added to @open-telemetry/docs-approvers.

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @austinlparker
- @mtwo

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- helped deliver OpenTelemetry workshop and contributed content updates
- contributions to observability SIG whitepaper

**Comment by austinlparker** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @shelbyspees! Invite sent.

@mtwo please type "I support" next time. This provides better notification so the membership will be updated faster.
