### ISSUE TITLE
REQUEST: New membership for vishiy

### ISSUE THREAD

**Issue by vishiy** [open-telemetry/community#708]
### GitHub Username

vishiy

### Requirements

- [* ] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [* ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [* ] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [* ] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ *] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [* ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @reyang 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

**Comment by reyang** [comment]
I support :)

**Comment by alolita** [comment]
I support @vishiy for membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @vishiy! Invite sent
