### ISSUE TITLE
REQUEST: New membership for dhruv-vora

### ISSUE THREAD

**Issue by dhruv-vora** [open-telemetry/community#709]
### GitHub Username

@dhruv-vora 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @MrAlias

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-o11y/opentelemetry-go/pull/69
  - https://github.com/open-telemetry/community/pull/691
  - https://github.com/open-o11y/opentelemetry-collector/pull/46
  - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/417
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-go/issues/1689
  - https://github.com/open-telemetry/opentelemetry-collector/issues/2540
  - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/414
  - https://github.com/open-telemetry/opentelemetry-collector/issues/2547
- SIG projects I am involved with
  - OpenTelemetry Specification SIG
  - OpenTelemetry Data Model SIG
  - Prometheus WG
  - Agent/Collector SIG
  - OpenTelemetry Metrics API/SDK SIG
  - Golang SIG

**Comment by MrAlias** [comment]
I approve

**Comment by alolita** [comment]
I approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @dhruv-vora! Invite sent
