### ISSUE TITLE
Update membership to clarify who can merge approved PRs.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/community#71]
https://github.com/open-telemetry/community/blob/master/community-membership.md

**Comment by SergeyKanzhelev** [comment]
It's covered in https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md#policies

> Repository MUST enforce Restrict who can push to matching branches setting to only allow the members of foo-maintainers to push to the master branch.

Created PR

**Comment by lizthegrey** [comment]
I feel there's a difference between maintainers setting _policy_ vs personally needing to merge every non-controversial commit...

**Comment by SergeyKanzhelev** [comment]
@lizthegrey we have two options: make it less convenient for maintainers as they need to merge all PRs or make it less comfortable for maintainer when the "unwanted" PR is being merged just before release. Also there was a concern that if approvers can merge - it makes easy for a few approvers to "take over" the project as they will be able to merge anything.

I just recording what we are doing today.

**Comment by lizthegrey** [comment]
> @lizthegrey we have two options: make it less convenient for maintainers as they need to merge all PRs or make it less comfortable for maintainer when the "unwanted" PR is being merged just before release. Also there was a concern that if approvers can merge - it makes easy for a few approvers to "take over" the project as they will be able to merge anything.
> 
> I just recording what we are doing today.

If maintainers can't trust their approvers to follow direction, there's a bigger problem :) at end of day we as approvers serve at the maintainers' pleasure. The fact maintainers administer the approver list I feel is the check here to ensure policy is followed.

**Comment by SergeyKanzhelev** [comment]
I never said it's a trust issue. It is a balance between how easy one can become an approver vs. how comfortable maintainers are to keep the subproject healthy. We have relaxed the requirement for becoming an approver so more people feel empowered to contribute and have a say in a project.

In any case, this is just documenting of what's currently in place. Just wanted to get the old issue out of the way and clean up. Happy to discuss the topic further if you believe this needs to be changed

**Comment by lizthegrey** [comment]
Let's discuss tomorrow.

**Comment by lizthegrey** [comment]
As per Governance meeting notes:
```
Who can merge PRs https://github.com/open-telemetry/community/pull/308
Is it mechanically enforced, or community enforced? Options for either.
Do maintainers need to review every substantial change? Yes. (but they may not need to personally click 'merge')
Do maintainers need to review trivial changes? Likely discretion applies, but that means approvers need to have merge rights so they can exercise discretion.
How do maintainers prevent approvers from going rogue? Remove rogue approver, unwind the commits.
Sarah: Prow for k8s repos can handle this enforcement.
Ted: It's a bit heavyweight for our scale.
Consensus: we'll step in if maintainers see interpersonal conflict over this, but otherwise we should take the cultural approach.
except: every spec change is nontrivial, so we can enforce hard rules there.
```
