### ISSUE TITLE
REQUEST: New membership for victlu

### ISSUE THREAD

**Issue by victlu** [open-telemetry/community#710]
### GitHub Username

@victlu

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jmacd 
- @jsuereth

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - [#1578](https://github.com/open-telemetry/opentelemetry-specification/pull/1578)
  - [#1590](https://github.com/open-telemetry/opentelemetry-specification/pull/1590)
  - [#1366](https://github.com/open-telemetry/opentelemetry-specification/issues/1366)
  - [#264](https://github.com/open-telemetry/opentelemetry-proto/issues/264)
  - [#1831](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1831)
  - [#1962](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1962)

- Issues responded to
  - [#1954](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1954)
  - [#287](https://github.com/open-telemetry/opentelemetry-proto/issues/287)
  - [#1685](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1685)
  - [#1650](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1650)

- SIG projects I am involved with
  - opentelemetry-specification
  - opentelemetry-proto
  - opentelemetry-dotnet

**Comment by jmacd** [comment]
I approve!

**Comment by jsuereth** [comment]
I support / approve

**Comment by SergeyKanzhelev** [comment]
Welcome, @victlu! Invite sent
