### ISSUE TITLE
REQUEST: New membership for bryan-aguilar

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/community#711]
### GitHub Username

@bryan-aguilar

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @MrAlias 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-go/pull/1798
https://github.com/open-telemetry/odpentelemetry-go/pull/1750

- Issues responded to
https://github.com/open-telemetry/opentelemetry-go/issues/1664
https://github.com/open-telemetry/odpentelemetry-go/pull/1750

- SIG projects I am involved with
OpenTelemetry Specification SIG
Prometheus WG
OpenTelemetry GO SIG
OpenTelemetry Collector SIG

**Comment by MrAlias** [comment]
I approve

**Comment by alolita** [comment]
I approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @bryan-aguilar! Invite sent
