### ISSUE TITLE
REQUEST: New membership for odeke-em

### ISSUE THREAD

**Issue by odeke-em** [open-telemetry/community#716]
### GitHub Username
@odeke-em

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @jmacd 

Thank you Alolita and Josh for proposing to sponsor me!

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Authored many parts of the Collector even from the early days [collector-commits](https://github.com/open-telemetry/opentelemetry-collector/commits?author=odeke-em), working on firstly stabilizing Prometheus support
- Issues responded to: inside [collector](https://github.com/open-telemetry/opentelemetry-collector/issues?q=is%3Aissue+commenter%3Aodeke-em+) [prometheus work group](https://github.com/open-telemetry/wg-prometheus/issues?q=is%3Aissue+commenter%3Aodeke-em+)
- SIG projects I am involved with: wg-prometheus, collector

**Comment by mtwo** [comment]
I support

From: Emmanuel T ***@***.***>
Sent: Wednesday, April 14, 2021 12:33 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [open-telemetry/community] REQUEST: New membership for odeke-em (#716)

GitHub Username

@odeke-em<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fodeke-em&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171579857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uf9LFov%2BUHqHDtgmrK9BpoonwywaAMlKWgjtCTnYDts%3D&reserved=0>

Requirements

  *   [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fcommunity%2Fblob%2Fmaster%2Fcommunity-membership.md&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171579857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NctsYVPS7jd%2F8NYRzSGmfupSUslGzMd8wFHe7EchnCQ%3D&reserved=0>)
  *   [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsettings%2Fsecurity&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171589855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t%2FyelFod91a2XWcxCV0JTgC9OIKtIyCKuH3WBdMBNps%3D&reserved=0>
  *   [ x] I have subscribed to the Slack channel<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud-native.slack.com%2Farchives%2FCJFCJHG4Q&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171589855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D637eT17n5go1y2ssdXqekUdMDeeN3bhPXYSa6jBEu8%3D&reserved=0> (use http://slack.cncf.io/<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fslack.cncf.io%2F&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171599844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WvNJ9Ak7LvOBQp3OchzC2LEo66K6AXKGNg%2Br6Bo6SaY%3D&reserved=0> to get an invite)
  *   [X] I am actively contributing to 1 or more OpenTelemetry subprojects
  *   [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
  *   [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors

  *   @alolita<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falolita&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171599844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i4R%2BNJTOfR0DFgBrcTW6oTWaacbB1E%2Fqt2DvmPMJJIM%3D&reserved=0>
  *   @jmacd<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjmacd&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171599844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S9ibQ3CHlPmuNmYqqTHF28m9%2FiXXzoTZ2mX4loWCGNY%3D&reserved=0>

Thank you Alolita and Josh for proposing to sponsor me!

Each sponsor should reply to this issue with the comment "I support".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

List of contributions to the OpenTelemetry project

  *   Authored many parts of the Collector even from the early days collector-commits<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry-collector%2Fcommits%3Fauthor%3Dodeke-em&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171609838%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FbLZsJN4usNrcDtQQvWvvI7S7jdIqZGMI6vNZrcA5jA%3D&reserved=0>, working on firstly stabilizing Prometheus support
  *   Issues responded to: inside collector<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry-collector%2Fissues%3Fq%3Dis%253Aissue%2Bcommenter%253Aodeke-em%2B&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171609838%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BKQ5ZnXZd7X%2FR5Ncj%2F52ww13jeRGKM8NPNoY%2FRTZ9Ag%3D&reserved=0> prometheus work group<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fwg-prometheus%2Fissues%3Fq%3Dis%253Aissue%2Bcommenter%253Aodeke-em%2B&data=04%7C01%7C%7C5d735d431ad1416e958108d8ff7c327f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540256171619833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FRau9TA6ejk6K4KjEuUfRcM3KZYvj8cqrDLaEzgn5Uw%3D&reserved=0>
  *   SIG projects I am involved with: wg-prometheus, collector

**Comment by odeke-em** [comment]
@mtwo thank you, and great to catch you here!!

**Comment by SergeyKanzhelev** [comment]
Hi, @odeke-em! I support as well

**Comment by SergeyKanzhelev** [comment]
Welcome, @odeke-em! Invite sent

**Comment by odeke-em** [comment]
Thank you @SergeyKanzhelev and @mtwo! Cheers, upwards and onwards!
