### ISSUE TITLE
Add Write permission for opentelemetry-cpp-contrib

### ISSUE THREAD

**Issue by TomRoSystems** [open-telemetry/community#718]
Hi,

We are planning to start releasing https://github.com/open-telemetry/opentelemetry-cpp-contrib for instrumenting httpd (Apache) and NGINX.

Would it be possible to give `Write` permission on this repo for users:
@TomRoSystems and @seemk 

to help with https://github.com/open-telemetry/opentelemetry-cpp-contrib/issues/11 ?

**Comment by SergeyKanzhelev** [comment]
@TomRoSystems is part of @open-telemetry/cpp-contrib-approvers and should have Write permissions

I have added @open-telemetry/cpp-contrib-approvers to have Write permissions to the repo and @open-telemetry/cpp-contrib-maintainers to have Maintain permissions. For some reason only @open-telemetry/cpp-approvers and @open-telemetry/cpp-maintainers were listed there before:

![image](https://user-images.githubusercontent.com/9950081/116163841-650f8100-a6ad-11eb-9676-f08c9de7ee5d.png)

We also have [triager role](https://github.com/open-telemetry/community/blob/main/community-membership.md#triager), if one needs to be created for cpp-contrib, let me know.

Please re-open ticket if more permissions needs fixing
