### ISSUE TITLE
New maintainer/approval teams needed for the opentelemetry-proto-go repo

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#720]
The [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go) repository is a centralized location for tthe Go code generated from the [OTLP](https://github.com/open-telemetry/opentelemetry-proto). This repository is a dependency for the OTel Go SIG and the users of that SIGs projects, additionally the collector may one day also depend on this repository.

Currently, the repository is managed as a side task for the OTel Go SIG and collector SIG maintainers. This is not adequately serving this project. We need more organizational structure to help progress the project, meaning we need a dedicated maintainer and approver team for this.

### Proposal

- Create a `proto-go-approvers` team:
   - seed this team with (please add a check by your username if you would like to be included here):
      - [x] @MrAlias (myself)
      - [ ] @Aneurysm9 
      - [ ] @tigrannajaryan 
      - [ ] @bogdandrutu 
      - [x] @MikeGoldsmith 
      - [x] @MadVikingGod 
- Give the `proto-go-approvers` team write access to https://github.com/open-telemetry/opentelemetry-proto-go
- Create a `proto-go-maintainers` team:
   - seed this team with (please add a check by your username if you would like to be included here):
      - [x] @MrAlias (myself)
      - [x] @MikeGoldsmith 
- Give the `proto-go-maintainers` team admin access to https://github.com/open-telemetry/opentelemetry-proto-go

**Comment by MikeGoldsmith** [comment]
@MrAlias yes on both accounts for me - I don't have access to check my box though 😄

**Comment by MadVikingGod** [comment]
I tried to check, but couldn't.  But, you can add me also.

**Comment by SergeyKanzhelev** [comment]
Created teams:

- https://github.com/orgs/open-telemetry/teams/proto-go-approvers/
- https://github.com/orgs/open-telemetry/teams/proto-go-maintainers

@MrAlias and @MikeGoldsmith, you can add whoever needs to be an approver.

Repository currently has @open-telemetry/go-maintainers configured as Admins. I kept it for now. @MrAlias you as a member of that team can remove it from the repository if needed.

I configured Maintain permissions, not Admin for @open-telemetry/proto-go-maintainers as documented [here](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#:~:text=the%20team%20foo-maintainers%20has%20maintain%20permissions%20for%20the%20repository.).

Please re-open if anything else is needed.
