### ISSUE TITLE
REQUEST: New membership for NickSulistio

### ISSUE THREAD

**Issue by NickSulistio** [open-telemetry/community#721]
### GitHub Username

@NickSulistio

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @lzchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/416
- Issues responded to
   - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/410 
   - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/416 
   - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/138
- SIG projects I am involved with
   - OpenTelemetry Specification SIG
   - Prometheus WG
   - OpenTelemetry GO SIG
   - OpenTelemetry Collector SIG

**Comment by lzchen** [comment]
I approve of the sponsorship.

**Comment by alolita** [comment]
I support @NickSulistio's membership. Please approve.

**Comment by SergeyKanzhelev** [comment]
Welcome, @NickSulistio! Invite sent
