### ISSUE TITLE
Craft a formal mission and vision

### ISSUE THREAD

**Issue by bhs** [open-telemetry/community#722]
While OpenTelemetry has a number of public presentations and documents where we've described our (informal) vision in one way or another, we have not, as a community, determined our "official" mission and vision as a project.

This is not urgent, but it is important. Here is how I propose we move forward:

1. Someone creates a GitHub issue in our community repo about crafting a formal mission and vision ✅ :)
2. We create [a public google doc](https://docs.google.com/document/d/1L92ThlgvSxYlQixpBNEovz8NnyOZfKu1E3zTT2gxaCY/edit#) where anyone and everyone can contribute suggestions for OpenTelemetry Mission and Vision statements (including some guidelines at the top about the purpose of each). As part of this, we encourage comments from anyone about any of the proposals.
3. <Wait, publicly advertise the process to encourage participation, iterate, etc>
4. The OpenTelemetry GC will look at the options and comments in the doc, make a decision, and document their rationale.

In terms of timelines, I'd suggest that we aim for a finalized OpenTelemetry Mission+Vision statement before Aug 1, 2021.

**Link to public google doc:** https://docs.google.com/document/d/1L92ThlgvSxYlQixpBNEovz8NnyOZfKu1E3zTT2gxaCY/edit#

*Needless to say, if there are questions or concerns about the above process, please raise them here – none of the above opinions are strongly-held.*

**Comment by tigrannajaryan** [comment]
Here is a public google doc to work on https://docs.google.com/document/d/1Z8kKA4U0bAwlCAlrzKKS_J9-ro1cz_18DZHIZYa-Gzk/edit

I took the liberty to seed it with a draft vision to get the ball rolling. :-)

**Comment by dyladan** [comment]
Doc is not editable. It is also not completely clear from the doc what is boilerplate and what is your submission as an idea for the mission/vision. Suggest you put it under a heading like `Submission from Tigran` or something to make it absolutely clear

**Comment by mtwo** [comment]
@tigrannajaryan can you give me edit access and then I'll add the GC and TC members

**Comment by tigrannajaryan** [comment]
> Doc is not editable. It is also not completely clear from the doc what is boilerplate and what is your submission as an idea for the mission/vision. Suggest you put it under a heading like `Submission from Tigran` or something to make it absolutely clear

It is open for commenting, you should be able to suggest any edits.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan can you give me edit access and then I'll add the GC and TC members

@mtwo done.

**Comment by tigrannajaryan** [comment]
I am not sure if we want to open it for public editing. I guess public commenting is sufficient, right?

**Comment by mtwo** [comment]
Yeah, I figured editing by TC and GC with public comments

**Comment by bhs** [comment]
Eek – I was working on a doc link and came back to find Tigran's example already out there...

Can we use this? https://docs.google.com/document/d/1L92ThlgvSxYlQixpBNEovz8NnyOZfKu1E3zTT2gxaCY/edit#

@tigrannajaryan feel free to copy-paste your text over, or just keep the link I hastily added just now.

**Comment by tigrannajaryan** [comment]
> Eek – I was working on a doc link and came back to find Tigran's example already out there...
> 
> Can we use this? https://docs.google.com/document/d/1L92ThlgvSxYlQixpBNEovz8NnyOZfKu1E3zTT2gxaCY/edit#
> 
> @tigrannajaryan feel free to copy-paste your text over, or just keep the link I hastily added just now.

@bhs Sure. Let me delete my link to avoid confusion. Let's use your doc.

**Comment by SergeyKanzhelev** [comment]
I've appended Values section to the end of the document. In discussions we realized that writing the Vision we often want to talk about the Values. So these two should be authored together.

CC: @open-telemetry/technical-committee

**Comment by tigrannajaryan** [comment]
> I've appended Values section to the end of the document. In discussions we realized that writing the Vision we often want to talk about the Values. So these two should be authored together.
> 
> CC: @open-telemetry/technical-committee

I reviewed and I like it.

I suggest that we start publishing the values and the vision. Let's start with what we have in the doc and we can refine as needed.

**Comment by bogdandrutu** [comment]
@bhs should this issue be closed?

**Comment by bhs** [comment]
Yes :)

Thanks.
