### ISSUE TITLE
REQUEST: New membership for @arielvalentin

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/community#723]
### GitHub Username

@arielvalentin

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mwear 
- @fbogsany 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs [reviewed](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=is%3Apr+reviewed-by%3A%40me+is%3Aclosed) / [authored](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=is%3Apr+is%3Aclosed+author%3Aarielvalentin)
- Issues responded to [closed](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+is%3Aclosed+arielvalentin)/[opened](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+arielvalentin+is%3Aopen)
- SIG projects I am involved with are... only the [Ruby SDK](https://github.com/open-telemetry/opentelemetry-ruby) for the time being

**Comment by mwear** [comment]
I support

**Comment by fbogsany** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @arielvalentin! Invite sent
