### ISSUE TITLE
REQUEST: New membership for robbkidd

### ISSUE THREAD

**Issue by robbkidd** [open-telemetry/community#724]
### GitHub Username

@robbkidd

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] [I have spoken to my sponsors ahead of this application](https://cloud-native.slack.com/archives/C01NWKKMKMY/p1619542981149800), and they have agreed to sponsor my application

### [Sponsors](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/CODEOWNERS#L15)

- @mwear
- @fbogsany

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- SIG projects I am involved with
    - OpenTelemetry Ruby - regularly attending the SIG and helping scribe [the meeting notes](https://docs.google.com/document/d/1D15bO8o340sQm2CVZiukEJuCO_XMMHKPuTznoEhyFqE/edit).
- PRs [reviewed](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=is%3Apr+reviewed-by%3Arobbkidd) / authored (0)
- [Issues responded to](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+robbkidd)
    - also [Release a 1.0 Release Candidate for Tracing](https://github.com/open-telemetry/opentelemetry-ruby/issues/731) which doesn't turn up in search for whatever reason
- Discussions
    - [Change how we create our release notes](https://github.com/open-telemetry/opentelemetry-ruby/discussions/721)

**Comment by mwear** [comment]
I support

**Comment by fbogsany** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @robbkidd! Invite sent
