### ISSUE TITLE
Loki integration with Grafana agent hosted in Docker 

### ISSUE THREAD

**Issue by it2008018** [open-telemetry/community#725]
I am trying to send logs to Loki Grafana cloud via Grafana agent hosted in Docker. I am following this instructions where the grafana agent is hosted in Linux Node, however I have hosted my agent in docker (attached docker-compose and agent-config file). I can see the traces are getting projected in Tempo but logs are not projected in Loki.
Is there any configuration missing in the docker files which need to be done for docker instance or this instruction is specifically for linux machines? 

Code in startup.cs:

![image](https://user-images.githubusercontent.com/51204924/116666968-3ae5e980-a961-11eb-8709-8b17e8be353e.png)
Nuget packages installed:

![image](https://user-images.githubusercontent.com/51204924/116667021-4df8b980-a961-11eb-9458-f284e4675e75.png)

Docker files:

[agent-config.txt](https://github.com/open-telemetry/community/files/6404468/agent-config.txt)
[docker-compose.txt](https://github.com/open-telemetry/community/files/6403786/docker-compose.txt)

![image](https://user-images.githubusercontent.com/51204924/116666472-98c60180-a960-11eb-8cac-eef2c45a4bd2.png)

Tempo showing traces:

![image](https://user-images.githubusercontent.com/51204924/116666594-beeba180-a960-11eb-9e31-bdb8923973c8.png)

No logs grabbed in Loki:

![image](https://user-images.githubusercontent.com/51204924/116666699-e2aee780-a960-11eb-914a-bf9a6314c237.png)

Console window showing logs and traces:

![image](https://user-images.githubusercontent.com/51204924/116666766-fb1f0200-a960-11eb-9327-9b651241e37c.png)

**Comment by mapno** [comment]
Hi @it2008018, this seems to be a [Grafana Agent](https://github.com/grafana/agent) issue. Maybe we can move the conversation there if you want.

Also, it appears that you have shared some credentials in the grafana agent config file. Consider rotating them as soon as possible.

**Comment by mapno** [comment]
In the config you shared, you're pushing logs to `http://localhost:3100/loki/api/v1/push`, which is probably why you're not seeing them in Grafana. Can you try to push them to the Grafana Cloud endpoint?

**Comment by it2008018** [comment]
> Hi @it2008018, this seems to be a [Grafana Agent](https://github.com/grafana/agent) issue. Maybe we can move the conversation there if you want.
> 
> Also, it appears that you have shared some credentials in the grafana agent config file. Consider rotating them as soon as possible.

Sure @mapno,I have removed the correct values now.

**Comment by it2008018** [comment]
> In the config you shared, you're pushing logs to `http://localhost:3100/loki/api/v1/push`, which is probably why you're not seeing them in Grafana. Can you try to push them to the Grafana Cloud endpoint?

Even if I change theat to grafana loki's url, it doesn't work.

**Comment by mapno** [comment]
> > In the config you shared, you're pushing logs to `http://localhost:3100/loki/api/v1/push`, which is probably why you're not seeing them in Grafana. Can you try to push them to the Grafana Cloud endpoint?
> 
> Even if I change theat to grafana loki's url, it doesn't work.

Not sure what may be the issue without more info. Can you share the logs of the Agent? We should see error from the loki component if the Agent is failing to push the logs to the corresponding backend.

**Comment by it2008018** [comment]
> > > In the config you shared, you're pushing logs to `http://localhost:3100/loki/api/v1/push`, which is probably why you're not seeing them in Grafana. Can you try to push them to the Grafana Cloud endpoint?
> > 
> > 
> > Even if I change theat to grafana loki's url, it doesn't work.
> 
> Not sure what may be the issue without more info. Can you share the logs of the Agent? We should see error from the loki component if the Agent is failing to push the logs to the corresponding backend.

[Grafana_agent_logs.txt](https://github.com/open-telemetry/community/files/6405102/Grafana_agent_logs.txt)
Please see attached.

**Comment by mapno** [comment]
> > > > In the config you shared, you're pushing logs to `http://localhost:3100/loki/api/v1/push`, which is probably why you're not seeing them in Grafana. Can you try to push them to the Grafana Cloud endpoint?
> > > 
> > > 
> > > Even if I change theat to grafana loki's url, it doesn't work.
> > 
> > 
> > Not sure what may be the issue without more info. Can you share the logs of the Agent? We should see error from the loki component if the Agent is failing to push the logs to the corresponding backend.
> 
> [Grafana_agent_logs.txt](https://github.com/open-telemetry/community/files/6405102/Grafana_agent_logs.txt)
> Please see attached.

I don't see any errors besides the localhost pushes at the beginning. Can you make sure you're writing to the files in `/var/log`?

**Comment by it2008018** [comment]
Thanks a lot @mapno 
I can see the logs in Loki now. Though the datetime logged is not quite correct(I am running the application on 3rd May 2021 whereas log timestamp is 2021-05-01 01:02:03), I am looking what is causing this difference in datetime.
