### ISSUE TITLE
Allow deleting issues

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#728]
We've gotten NSFW spam issues in our repos lately and would like to delete them. I can't find the link for it so believe it's not enabled for the `open-telemetry` organization. Can an org admin enable it?

https://docs.github.com/en/organizations/managing-organization-settings/allowing-people-to-delete-issues-in-your-organization

It will allow repository admins to delete issues, which should effectively mean language maintainers are allowed to delete issues and no one else.

**Comment by dyladan** [comment]
I think officially maintainers are not supposed to be repository admins. Is this time sensitive or can it wait for GC meeting (thursday)

**Comment by anuraaga** [comment]
I believe @jkwatson and @bogdandrutu discussed this a while ago and determined that maintainers are supposed to be repository admins. Presumably "repo ownership in GitHub" here

https://github.com/open-telemetry/community/blob/main/community-membership.md

At that point the Java maintainers were made admins of the repo so we could set up secrets for GitHub workflows - many maintenance tasks would be very difficult without that access (deleting spam issues is also one such task :) ).

I think whether maintainers should be admins is orthogonal from repo admins are allowed to delete issues, so maybe it could be enabled in good faith anyways? The issues have been closed so have low visibility and isn't super-urgent though so a couple of days is ok.

**Comment by Oberon00** [comment]
> The issues have been closed so have low visibility and isn't super-urgent though so a couple of days is ok.

Also, I reported the issue in question to GitHub yesterday using the report button. I think as an additional measure you could edit the issue to replace the content of the description with "Spam removed" or something.

**Comment by Oberon00** [comment]
> I think as an additional measure you could edit the issue to replace the content of the description with "Spam removed" or something.

I that just now and also locked the conversation on the issue "as spam".

**Comment by SergeyKanzhelev** [comment]
Yep, one more reason to change `Maintain` to `Admin` https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md for maintainers. GH permissions model is far from ideal for sure.

**Comment by anuraaga** [comment]
> I that just now and also locked the conversation on the issue "as spam".

Thanks @Oberon00, very obvious step to minimize more the visibility that hadn't come to mind.

**Comment by anuraaga** [comment]
Hey @dyladan @SergeyKanzhelev any resolution from the GC meeting? Don't see anything in the notes about this. Hoping we can enable deleting of issues to let maintainers keep the issue list clean.

**Comment by anuraaga** [comment]
We're still getting spam and need to be able to address it - @open-telemetry/technical-committee can we get a quick resolution here? Enabling the flag to delete issues seems to have no reason to be controversial.

**Comment by SergeyKanzhelev** [comment]
I enabled the option to delete issues. Which repo is experiencing spam now?

**Comment by mtwo** [comment]
@anuraaga are we ok to close this now?

**Comment by SergeyKanzhelev** [comment]
We still need to make people admins for repos. Pls let me know which ones for short term resolution and we will need to discuss long term approach

**Comment by anuraaga** [comment]
Thanks @SergeyKanzhelev - yeah apparently I'm something that's not Admin. Can manage secrets, but still no delete issue button. The repo is `opentelemetry-java` - https://github.com/open-telemetry/opentelemetry-java/issues?q=is%3Aissue+is%3Aclosed+label%3Aspam

**Comment by SergeyKanzhelev** [comment]
You are in java-maintainers team. Team has Admin access:

![image](https://user-images.githubusercontent.com/9950081/118220678-1560e180-b431-11eb-9da2-153aa3dac86c.png)

Issue deletion is enabled:

![image](https://user-images.githubusercontent.com/9950081/118220778-45a88000-b431-11eb-9a97-8ceadc2dfe08.png)

I see the delete button:

![image](https://user-images.githubusercontent.com/9950081/118220853-78527880-b431-11eb-9766-6f799b2c5852.png)

Can you please try again? I am not sure why you don't see it.

**Comment by anuraaga** [comment]
Thanks for confirming! I did look at that page and it wasn't there, but now it is :O Evils of memcache presumably, but will clean this stuff up now.

**Comment by anuraaga** [comment]
Cleaned up the issues and that check box from my original post is enabled so will close out this issue. Thanks again.

**Comment by SergeyKanzhelev** [comment]
Thank you! As a follow up we will need to change policy so maintainers are admins on repositories.
