### ISSUE TITLE
Tempo availability for grafana agent on windows

### ISSUE THREAD

**Issue by it2008018** [open-telemetry/community#729]
I have installed grafana-agent-installer on my system and has successfully configured Loki with it. I can see the logs from my logs files to Grafana Loki. However I want to see traces as well and want to configure Tempo with grafana agent which is hosted as service in my system.
This is the agent config file which I am using:
[agent-config.txt](https://github.com/open-telemetry/community/files/6420231/agent-config.txt)

In startup.cs i have added this block of code:

![image](https://user-images.githubusercontent.com/51204924/116987014-22910a00-ac94-11eb-9730-9a394afeb66a.png)

The same setup is working fine for Docker hosting of Grafana agent, but doesn't work in Windows hosted agent. Can someone please help me here what is wrong with my config file or otlp endpoint ?

I have followed this for my setup:
https://github.com/grafana/agent/blob/main/docs/windows.md

**Comment by trask** [comment]
hi @it2008018, sorry for the late reply, hopefully you were able to figure this out, if not I'd recommend reaching out to the grafana community.
