### ISSUE TITLE
Initial milestones and backlog triage

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/community#73]
OpenTelemetry is a big project. In order to stay on track and feeling cohesive – while working in parallel – it is important to understand our initial goals, and our process for achieving them. Two things which would raise awareness and created commonality across all SIGs:

* A set of initial milestones which flush out the goals defined in [a Roadmap to Convergence](https://medium.com/opentracing/a-roadmap-to-convergence-b074e5815289).
* A common baseline for backlog management. This allows us to define the membership roles more concretely, attach SLAs to responses, and feel comfortable moving between SIGs.

I've created two PRS, one for each document:

**Initial Milestones:** https://github.com/open-telemetry/community/pull/50
**Backlog Management:** https://github.com/open-telemetry/community/pull/52/

Now OpenTelemetry is underway, it would be great if we could get the first draft of these docs resolved in the next days, to assist with SIG bootstrapping.

**Comment by SergeyKanzhelev** [comment]
tracked in specs repository now
