### ISSUE TITLE
Create Prometheus Approvers list in Collector and Collector-Contrib Repos

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#740]
A number of contributors are working on Prometheus specific components in the Collector and Collector-Contrib repos. PRs being submitted for the Prometheus receiver and exporters are queued for approver reviews for a couple of weeks or more at times and merging. 

Based on the discussion in the May 19 Collector SIG meeting, the Collector maintainers (@bogdandrutu, @tigrannajaryan) agreed to create a prometheus-approvers list which can approve and merge PRs for the specific Prometheus components.

I nominate the following reviewers to be included in the @open-telemetry/collector-prometheus-approvers list:
@Aneurysm9 
@dashpole 
@rakyll 
@alolita

All the folks mentioned above are working actively on Prometheus and metrics components. Please create this list with limited permissions to unblock approver reviews for incoming Prometheus PRs.

**Comment by bogdandrutu** [comment]
Let's give a try to codeowners approach first.
