### ISSUE TITLE
REQUEST: New membership for eddyleelin

### ISSUE THREAD

**Issue by eddyleelin** [open-telemetry/community#743]
### GitHub Username

@eddyleelin

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects (python and collector)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lzchen 
- @lonewolf3739 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-python/pull/1869
  - https://github.com/open-telemetry/opentelemetry-python/pull/1855
  - https://github.com/open-telemetry/opentelemetry-python/pull/1854
  - https://github.com/open-telemetry/opentelemetry-collector/pull/3270
  - https://github.com/open-telemetry/opentelemetry-collector/pull/3269
  - https://github.com/open-telemetry/opentelemetry-collector/pull/3268
  - https://github.com/open-o11y/opentelemetry-collector/pull/50 (WIP)
- Issues responded to
  - open-telemetry/opentelemetry-python/issues/1852
  - open-telemetry/opentelemetry-python/issues/1851
  - open-telemetry/opentelemetry-collector/issues/3191
  - open-telemetry/opentelemetry-collector/issues/3175
- SIG projects I am involved with
  - Collector
  - Python

**Comment by lonewolf3739** [comment]
I support

**Comment by lzchen** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @eddyleelin! Invite sent.
