### ISSUE TITLE
Recommendation for shared credentials

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#744]
The Python maintainers have a need to share credentials for a pypi account used by the CI for publishing packages and would love to know what the community recommends here.

**Comment by SergeyKanzhelev** [comment]
@amye I know CNCF can grant 1Password subscriptions for this use. Do any other projects use password managers successfully for scenarios like this?

**Comment by amye** [comment]
https://github.com/1Password/1password-teams-open-source is what we've directed projects to in the past, but it's somewhat up to them for how they manage their accounts.

**Comment by SergeyKanzhelev** [comment]
@amye do you have any feedback on how flexible the permissions model there? Or maybe has contacts with people using it? 1Password looks like a great solution and we may want to adopt it for opentelemetry.

**Comment by amye** [comment]
Recommend reaching out to Prometheus, who I know got set up with this!

**Comment by SergeyKanzhelev** [comment]
@RichiH can you share what was your experience setting up 1Password? Was it flexible enough, do you use it for sub-groups?

**Comment by codeboten** [comment]
I created a PR to add OpenTelemetry to the list of projects here: https://github.com/1Password/1password-teams-open-source/pull/364
