### ISSUE TITLE
REQUEST: New membership for bryce-b

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/community#746]
### GitHub Username

@bryce-b

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel]( ) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @nachoBonafonte 
- @SergeyKanzhelev 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - [merged opentelemetry-swift PRs](https://github.com/open-telemetry/opentelemetry-swift/pulls?q=is%3Apr+is%3Amerged+author%3Abryce-b+)
  - [reviewed opentelementry-swift PRs](https://github.com/open-telemetry/opentelemetry-swift/pulls?q=is%3Apr+is%3Aclosed+commenter%3Abryce-b+-author%3Abryce-b+)

- SIG projects I am involved with
  - Proposed and participate in Swift SIG

**Comment by nachoBonafonte** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @bryce-b! Invite sent
