### ISSUE TITLE
REQUEST: New membership for pmm-sumo

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/community#749]
### GitHub Username

@pmm-sumo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tigrannajaryan 
- @djaglowski 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored

https://github.com/open-telemetry/opentelemetry-collector/pull/609
https://github.com/open-telemetry/opentelemetry-collector/pull/2454
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1744
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1792
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2635
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2556
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1051
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1038
https://github.com/open-telemetry/opentelemetry-specification/pull/1727
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/329

- Issues responded to
 
https://github.com/open-telemetry/opentelemetry-collector/issues/1884
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/964
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1146
https://github.com/open-telemetry/opentelemetry-specification/issues/1613
https://github.com/open-telemetry/opentelemetry-specification/issues/1633
https://github.com/open-telemetry/opentelemetry-specification/issues/1377
https://github.com/open-telemetry/opentelemetry-specification/issues/1115

- SIG projects I am involved with

I regularly take part in Collector/Agent, Logs and Specification meetings and engage on Slack and gitter (while it was still being used)

**Comment by djaglowski** [comment]
I support.

**Comment by arminru** [comment]
I support.

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcom, @pmm-sumo! Invite sent

**Comment by pmm-sumo** [comment]
Thank you very much!
