### ISSUE TITLE
REQUEST: Octobox support

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/community#75]
The [Octobox app](https://github.com/marketplace/octobox) has a free plan for orgs. We should add it so that Octobox users can have better OpenTelemetry notifications :)

**Comment by SergeyKanzhelev** [comment]
What permissiosn Octobox need? Is it just `GitHub's notification scope`? If so - I see no harm.

Any other opinions here?

**Comment by bai** [comment]
👍 for Octobox.

**Comment by SergeyKanzhelev** [comment]
It is enabled now.
