### ISSUE TITLE
Error : TraceID has no field or method String

### ISSUE THREAD

**Issue by androna-xm** [open-telemetry/community#752]
I am using go.opentelemetry.io/otel/trace v0.20.0 and i am trying to extract the TraceID by 
`traceID := trace.SpanContextFromContext(ctx).TraceID.String()` 
(as i saw from a tutorial, with probably a previous version )
Now, however, i get this error 
`"go.opentelemetry.io/otel/trace".SpanContextFromContext(ctx).TraceID.String undefined (type func() "go.opentelemetry.io/otel/trace".TraceID has no field or method String)`
I checked and the return type of trace.SpanContextFromContext(ctx).TraceID is not string , so how could i get the traceID as a string?

**Comment by bhs** [comment]
Thanks for raising this! That said, could you refile in https://github.com/open-telemetry/opentelemetry-go ?

(FWIW, there is a `TraceID.String()` method at head, so I suspect some other oddness... Maybe you could post a gist that recreates the issue??)

I'm going to close here in the community repo for now.
