### ISSUE TITLE
REQUEST: New membership for paulosman

### ISSUE THREAD

**Issue by paulosman** [open-telemetry/community#753]
### GitHub Username

@paulosman

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Aneurysm9 
- @tigrannajaryan 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

PRs:
- opentelemetry-go
  - https://github.com/open-telemetry/opentelemetry-go/pull/1233
- opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector/pull/2723
- opentelemetry-collector-contrib
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2729
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/135
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/164
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/200
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/248
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/271
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/305

OTEPs:
- https://github.com/open-telemetry/oteps/pull/148 (Participant / Reviewer)

**Comment by Aneurysm9** [comment]
+1

**Comment by tigrannajaryan** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
Welcome, @paulosman! Invite sent
