### ISSUE TITLE
REQUEST: New membership for ohamuy

### ISSUE THREAD

**Issue by ohamuy** [open-telemetry/community#754]
### GitHub Username

@ohamuy

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @bobstrecansky 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Reviewed PR: https://github.com/open-o11y/opentelemetry-php/pull/4
- Merged authored PR: https://github.com/open-telemetry/opentelemetry-cpp/pull/833
- Issue commented on: https://github.com/open-telemetry/opentelemetry-cpp/issues/812
- OpenTelemetry PHP SIG: https://docs.google.com/document/d/1WLDZGLY24rk5fRudjdQAcx_u81ZQWCF3zxiNT-sz7DI/edit#
- OTEL Agent/Collector: https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit?ts=5de972a2#heading=h.qk3cxz6tlvpa

**Comment by alolita** [comment]
I approve membership for @ohamuy

**Comment by bobstrecansky** [comment]
I approve this membership for @ohamuy

**Comment by SergeyKanzhelev** [comment]
Welcome, @ohamuy! Invite sent
