### ISSUE TITLE
PHP contrib repository

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#757]
A repository to keep PHP instrumentation, propagation, exporters, etc is needed. Suggested name: opentelemetry-php-contrib

The same teams, @open-telemetry/php-maintainers and @open-telemetry/php-approvers , should have rights for merging and approving, respectively.

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu @lizthegrey please enable easyCLA for the new repository https://github.com/open-telemetry/opentelemetry-php-contrib/pull/1

**Comment by lizthegrey** [comment]
Done.
