### ISSUE TITLE
Update OpenTelemetry Public Calendar meeting invites to have full Zoom ID in calendar invite title and body

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#759]
The following invites are missing Zoom IDs in the body:
* Go SIG
* Log SIG
* Lambda WG
* Spec SIG
* Rust SIG
* Maintainers meeting

@mtwo can you please update these invites? Else I think I may have calendar access so will try to fix too. This fix will help folks to easily access the zoom link for meetings from the calendar invite body.

**Comment by SergeyKanzhelev** [comment]
this is how to get permissions: https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md#:~:text=all%20sig%20maintainers%20have%20permission%20to%20edit%20the%20public%20opentelemetry%20calendar.%20 if you don't have it

**Comment by danielgblanco** [comment]
Closing as we now have all meetings with Zoom links
