### ISSUE TITLE
REQUEST: Ruby SIG approver for bai

### ISSUE THREAD

**Issue by bai** [open-telemetry/community#76]
### GitHub Username

@bai

### Organization you are requesting membership in

@open-telemetry

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Gitter channel](https://gitter.im/open-telemetry/community)
- [ ] I ~am~ actively contributing to 1 or more OpenTelemetry subprojects
    - [x] I will actively contribute to the OpenTelemetry Ruby subproject
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @fbogsany

**Comment by fbogsany** [comment]
👍 approved.

**Comment by SergeyKanzhelev** [comment]
@fbogsany I also assume nominating as an Approver for Ruby in initial set of contributors file?

**Comment by SergeyKanzhelev** [comment]
welcome, @bai! I sent invite

**Comment by bai** [comment]
Many thanks!
