### ISSUE TITLE
REQUEST: New membership for @vreynolds

### ISSUE THREAD

**Issue by vreynolds** [open-telemetry/community#760]
### GitHub Username

@vreynolds

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @dyladan 
- @vmarchaud 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- JS SIG attendee
- https://github.com/open-telemetry/opentelemetry-js/pulls?q=author%3Avreynolds+
- https://github.com/open-telemetry/opentelemetry-js/issues?q=is%3Aissue+commenter%3Avreynolds
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues?q=is%3Aissue+commenter%3Avreynolds
- https://github.com/open-telemetry/opentelemetry-js-api/issues?q=is%3Aissue+commenter%3Avreynolds

**Comment by vmarchaud** [comment]
I support !

**Comment by dyladan** [comment]
I support!

**Comment by SergeyKanzhelev** [comment]
Welcome, @vreynolds! Invite sent
