### ISSUE TITLE
REQUEST: New membership for VineethReddy02

### ISSUE THREAD

**Issue by VineethReddy02** [open-telemetry/community#761]
### GitHub Username

@VineethReddy02

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jpkrohling
- @tigrannajaryan

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed/authored
  * https://github.com/open-telemetry/opentelemetry-operator/pull/302
  * https://github.com/open-telemetry/opentelemetry-operator/pull/307
  * https://github.com/open-telemetry/opentelemetry-operator/pull/312
  * https://github.com/open-telemetry/opentelemetry-operator/pull/313
  * https://github.com/open-telemetry/opentelemetry-operator/pull/314
  * https://github.com/open-telemetry/opentelemetry-operator/pull/315
  * https://github.com/open-telemetry/opentelemetry-operator/pull/304
  * https://github.com/open-telemetry/opentelemetry-operator/pull/327
- Issues responded to
  * https://github.com/open-telemetry/opentelemetry-operator/issues/12
- SIG projects I am involved with
  * Agent/Collector SIG

**Comment by tigrannajaryan** [comment]
I support.

**Comment by jpkrohling** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @VineethReddy02! Invite sent
