### ISSUE TITLE
Set opentelemetry-java-contrib-maintainers as admins of open-telemetry/opentelemetry-java-contrib

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#762]
In the -java and -java-instrumentation repos, the maintainers are set as Admins of the repos to be able to maintain things like the continuous build (for example, setting publishing secrets) and content moderation. This doesn't seem to be the case for java-contrib where I will be setting up some publishing stuff. Can we make the change to java-contrib too for consistency with the other repos?

**Comment by anuraaga** [comment]
Can anyone help with this?

**Comment by trask** [comment]
cc @open-telemetry/technical-committee

**Comment by yurishkuro** [comment]
Done
![image](https://user-images.githubusercontent.com/3523016/124049869-60d24d80-d9e7-11eb-8f12-850819ef8239.png)
