### ISSUE TITLE
Need more zoom meeting rooms

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/community#763]
Currently, we have three [zoom meeting rooms](https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md) (banana, blueberry, tomato). Thursday 9am pacific we have three simultaneous meetings. Adding the sampling SIG to Thursday 8am Pacific guarantees that we will overlap with one of the existing meetings.

So, it looks like we need at least one more meeting room which automatically records and uploads to YouTube. @SergeyKanzhelev you've set these up before, is this something you could do?

**Comment by SergeyKanzhelev** [comment]
@amye set those up. @amye would it be possible to have one more account for OpenTelemetry? We can keep the pattern of e-mails: cncf-opentelemetry-meeting-3(at)cncf.io.

**Comment by amye** [comment]
Drop a ticket into servicedesk and we'll get you taken care of!

**Comment by SergeyKanzhelev** [comment]
https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-856?created=true

**Comment by SergeyKanzhelev** [comment]
@eddynaka is updating settings for the account... Thank you, @eddynaka!

**Comment by SergeyKanzhelev** [comment]
this is done
