### ISSUE TITLE
REQUEST: New membership for NathanielRN

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/community#777]
### GitHub Username

e.g. (at)example_user

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @codeboten 
- @lzchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs reviewed / authored

- opentelemetry-python
  - Make Ids Generation Customizable
    - Implemented default RandomIdsGenerator + Interface
      - Links
        - https://github.com/open-telemetry/opentelemetry-python/pull/1153
      - Allow opentelemetry-sdk package to be extended
        - Before this PR, no SDK extensions could exist
      - Links
        - https://github.com/open-telemetry/opentelemetry-python/pull/1205
  - Remove non-specification required packages from this repository
      - Removed 30,000+ lines of code in 1 PR :)
      - Seperated repos so that barrier of requirements for new packages would be a lot lower in Contrib repo! This will allow vendors to put their packages in an easy to find place for users and hopefully motivate continuous integration with OTel Python
      - Set up CI workflow that would test change across the repositories using GitHub actions for Continuous Integration
      - Preserved all the Git history in the move
      - Links
          https://github.com/open-telemetry/opentelemetry-python/issues/1233
          https://github.com/open-telemetry/opentelemetry-python/pull/1258
          https://github.com/open-telemetry/opentelemetry-python/pull/1357
  - Add performance tests workflow
      - Fully automated performance tests
      - Fails tests if performance gets too bad
      - Performance tests published in nice intractable graph at https://open-telemetry.github.io/opentelemetry-python/benchmarks/index.html
      - Links
            https://github.com/open-telemetry/opentelemetry-python/pull/1443
            https://github.com/open-telemetry/opentelemetry-python/pull/1469
            https://github.com/open-telemetry/opentelemetry-python/pull/1473
            https://github.com/open-telemetry/opentelemetry-python/pull/1468
  - Make auto instrumentation Ids Generator configurable

- opentelemetry-python-contrib
    - Move non-specification required packages to this repository
        - Same as above
        - Split PRs across many PRs to faciliate reviewing
        - Links
            - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/126
            - Several PRs from https://github.com/open-telemetry/opentelemetry-python-contrib/pull/49 to https://github.com/open-telemetry/opentelemetry-python-contrib/pull/131
    - Make botocore instrumentation comply with specifications
        - Links
            - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/150
    - Add performance tests workflow
        - Same as above
         - Links
             - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/243
             - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/250

- opentelemetry-specification
    - Require SDKs to make Ids Generation Customizable
        - Managed to convince the maintainers of the urgency of requiring this change before GA so as to not break compatibility with vendors
        - Links
            - https://github.com/open-telemetry/opentelemetry-specification/pull/1006

- Issues responded to
  - See above for issues!
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-python

**Comment by lzchen** [comment]
I support this.

**Comment by codeboten** [comment]
I support this as well!

**Comment by SergeyKanzhelev** [comment]
Welcome, @NathanielRN! Invite sent
