### ISSUE TITLE
Enable joining Zoom meetings with web clients

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#785]
I tried joining the SIG Collector today with a browser instead of the app, and I wasn't able to. Apparently, the meetings for OpenTelemetry require the usage of app clients. The reason I want to use the web client, besides the lower permission requirements and privacy concerns, is that sharing my screen with the app is always strange. On the screen, I have a code editor and a terminal, but people can only see the code editor. Joining with a browser solves this problem.

**Comment by SergeyKanzhelev** [comment]
@eddynaka is it something you can help with? Perhaps some settings are messed up. Maybe the setting that require authenticated users is enabled on one of accounts?

**Comment by mtwo** [comment]
Odd, I thought that we have some people who join regularly via the web client (Google employees). Can you paste the text of the error? If it's a permissions issue, try using the password 77777.

**Comment by SergeyKanzhelev** [comment]
@mtwo there are three accounts and it may be one of them got some settings incorrectly. Definitely more information will help pinpoint the issue faster

**Comment by jpkrohling** [comment]
I think someone from Google mentioned that they were logged in, which seemed to be the trigger to allow people to join with the web client.

**Comment by mtwo** [comment]
Actually, that may have been intentional then. When we were getting zoom bombed I think that we started requiring some amount of authentication to join a meeting, so that people can be kicked without the ability to immediately rejoin (I’m going from memory here, could be wrong).

Can you try logging into the zoom website (even with a free account) and then joining?
________________________________

**Comment by jpkrohling** [comment]
Sorry for the noise, I sorted it out: I had a link handler in Firefox, which caused the meetings to automatically open in the app. Removing that, and clicking on "Join meeting" will open the prompt to open the link in the app, but canceling that popup causes the "Join with a web browser" to appear.
