### ISSUE TITLE
request for a workgroup repo for ebpf workgroup

### ISSUE THREAD

**Issue by yonch** [open-telemetry/community#788]
Regarding the [donation of "flowmill-collector" ](https://github.com/open-telemetry/community/issues/733)(contemplated to be contributed as opentelemetry-ebpf):
* The technical committee has [completed its due diligence](https://docs.google.com/document/d/1CRY-GU4ENgjC9suJu4RRA984HvJ3Gxxa5e7mKx4t8ss/edit#heading=h.pwdftsvax4ni)
* The [governance committee agreed to create an ebpf working group](https://github.com/open-telemetry/community/issues/733#issuecomment-881696046) and conditionally approve the donation "based on this WG agreement on alternative back end and extensibility design".

I'd like to request a working group repo (e.g., `wg-ebpf`) to track ongoing issues (similar to [wg-prometheus](https://github.com/open-telemetry/community/issues/631)).

@tigrannajaryan can you please help with this?

**Comment by tigrannajaryan** [comment]
Repo https://github.com/open-telemetry/wg-ebpf created, team https://github.com/orgs/open-telemetry/teams/wg-ebpf, I invited @yonch to the team.

@bogdandrutu or @lizthegrey please setup the EasyCLA for the repo.

**Comment by lizthegrey** [comment]
done.

**Comment by tigrannajaryan** [comment]
@yonch initial setup done.
