### ISSUE TITLE
REQUEST: New membership for @bhautikpip

### ISSUE THREAD

**Issue by bhautikpip** [open-telemetry/community#790]
### GitHub Username

@bhautikpip (https://github.com/bhautikpip)

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @anuraaga
- @Aneurysm9 
- @MrAlias 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1935
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/569
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/575
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/812
https://github.com/open-telemetry/opentelemetry-go/pull/2010
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3280
https://github.com/open-telemetry/opentelemetry-collector/pull/3070
https://github.com/open-telemetry/opentelemetry-collector/pull/3090
https://github.com/open-telemetry/opentelemetry-go/pull/2115

- Issues responded to

- SIG projects I am involved with
OpenTelemetry Go

**Comment by Aneurysm9** [comment]
I support this membership application.  @bhautikpip has been advised to seek an additional sponsor as both @anuraaga and I are from AWS.

**Comment by MrAlias** [comment]
I support this membership application! :clap:

**Comment by anuraaga** [comment]
I support - thanks!

**Comment by SergeyKanzhelev** [comment]
Welcome, @bhautikpip! Invite sent
