### ISSUE TITLE
EasyCLA check failing

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#795]
Have tried closing/re-opening PRs multiple times with no luck.

Not sure how to escalate, maybe @lizthegrey?

**Comment by trask** [comment]
oh! I found CNCF #easycla slack channel, and someone from gRPC is also reporting EasyCLA stuck today, I'll report there for us also, but probably nothing for anyone to do here

**Comment by cijothomas** [comment]
Reporting same from Otel .NET repo as well.

**Comment by lalitb** [comment]
Not stuck anymore, but failing on validation:

![error_cla](https://user-images.githubusercontent.com/1196320/127733735-f0b82acb-cdd9-40d9-931a-63a22f574f2d.JPG)

**Comment by trask** [comment]
> Not stuck anymore, but failing on validation

Ya, we're seeing this now also in https://github.com/open-telemetry/opentelemetry-java-instrumentation, e.g.

* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3743
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3739

Although somehow it worked for:

* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3736

I reported the new error to the CNCF #easycla channel, I'll keep you posted.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2209 partially working.
![image](https://user-images.githubusercontent.com/5232798/127746367-9a42c3a7-ea63-46fd-9b90-bac3bf532b80.png)

**Comment by trask** [comment]
The EasyCLA team just deployed a fix.

Adding `/easycla` comment, or closing-reopening PR should resolve the issue.
