### ISSUE TITLE
REQUEST: New membership for @chenqi0805

### ISSUE THREAD

**Issue by chenqi0805** [open-telemetry/community#796]
https://github.com/chenqi0805

### GitHub Username
chenqi0805

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @Aneurysm9 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by arminru** [comment]
Thanks for your request, @chenqi0805!
@alolita @Aneurysm9 Please confirm your sponsorship.

**Comment by alolita** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
It looks like both sponsors has the same vendor affiliation. Please make sure to find sponsors a sponsor from other company and re-open the request

> Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
