### ISSUE TITLE
Calendar link for .NET Instrumentation is incorrect

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/community#797]
The text in the description of the .NET Instrumentation meeting is correct but the respective url still points to the old meeting. The location itself is correct but since some people use the description link they end up in the wrong zoom meeting.

**Comment by SergeyKanzhelev** [comment]
would you please send a PR to fix?

**Comment by pjanotti** [comment]
The error is actually on the calendar not on the README.md - I will ask to join opentelemetry-calendar-contributors so I can fix there directly.

**Comment by pjanotti** [comment]
I got access and fixed the calendar. Thanks.
