### ISSUE TITLE
REQUEST: New membership for @alexperez52

### ISSUE THREAD

**Issue by alexperez52** [open-telemetry/community#800]
### GitHub Username

@alexperez52

Requirements

* [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
* [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
* [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
* [x] I am actively contributing to 1 or more OpenTelemetry subprojects
* [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
* [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors

* @alolita
* @bobstrecansky

Each sponsor should reply to this issue with the comment "I support".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

List of contributions to the OpenTelemetry project

* PRs reviewed / authored
    * https://github.com/open-telemetry/opentelemetry-php/pull/351
    * https://github.com/open-telemetry/opentelemetry-operator/pull/354
    * https://github.com/open-telemetry/opentelemetry-operator/pull/351
* Issues responded to
    * https://github.com/open-telemetry/opentelemetry-php/issues/184
    * https://github.com/open-telemetry/wg-prometheus/issues/60
* SIG projects I am involved with
    * https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit?ts=5de972a2#heading=h.qk3cxz6tlvpa
    * https://docs.google.com/document/d/19bnXziPn2MZ9wO6684UoI4D-LCjGL5bTJkGhux29bx8/edit

**Comment by alolita** [comment]
I support @alexperez52 for OpenTelemetry membership.

**Comment by bobstrecansky** [comment]
I support @alexperez52 for OpenTelemetry membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @alexperez52! Invite sent
