### ISSUE TITLE
Create repository for component-owners GHA

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#801]
Last week I started working on a github action which allows ownership over subcomponents/directories of a repository to be defined in a configuration file similar to CODEOWNERS but without requiring write access to the repo.

I brought it up in the maintainers SIG today as well as the maintainers slack and it seems like other maintainers are interested in using it. I think if multiple SIGs will depend on it, I would like it to be in the open-telemetry org so I would like a repository for it.

I don't know if it is easier to create an empty repository and I can push all history onto it or to transfer ownership of the repo. Either is fine with me.

Action: https://github.com/dyladan/component-owners

**Comment by dyladan** [comment]
@open-telemetry/technical-committee not sure if I should be doing anything to drive this more? After discussion in the maintainers and spec sig this week it seems like most maintainers were in support

**Comment by yurishkuro** [comment]
I can create a repo. Do you have a name in mind? Could it be in build-tools?

**Comment by dyladan** [comment]
A github action can't be in a subdirectory. We could put it in the root of the build-tools repo but then the action would be named `open-telemetry/build-tools` instead of `component-owners` which I think is more descriptive. Maybe `component-owners-action` if we want to make it clear what it is at a glance?

**Comment by dyladan** [comment]
I'm not sure if the term "owner" is a problem either, if it implies too much power and responsibility. Maybe `component-contributor-action` or `component-assignment-action` or something? Personally I like `component-owners` but I'm open to other ideas.

**Comment by yurishkuro** [comment]
I would suggest `assign-reviewers-action`, which describes the main function without getting into details of how reviewers are selected (which I presume may evolve over time by extending config capabilities).

**Comment by dyladan** [comment]
It also adds assignees and i'm currently working on functionality to add `approved-by-owner` and `author-is-owner` labels automatically.

**Comment by yurishkuro** [comment]
https://github.com/open-telemetry/assign-reviewers-action
