### ISSUE TITLE
Request for the OpenTelemetry Instrumentation SIG 

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#802]
OpenTelemetry is only as good as its instrumentation. This is a large effort which iterates over time and continuously improves. Over the long term, the work to manage and maintain instrumentation is larger than the work to build and maintain the clients.

We are requesting a formal Instrumentation SIG with a weekly community meeting for working on instrumentation conventions, design and implementation of components as well as responding to any questions contributors may have.

Once approved, we'd like to have the weekly meeting on Tuesdays in an APAC friendly time at 1600 Pacific Time (which is 8am in Japan - @anuraaga)

**Projects we would like to focus on include:**

- Improve the quality of our instrumentation guidelines, to ensure we are comparable (or better) than what is currently provided by other projects. This includes semantic conventions.
- Develop stability guarantees for telemetry data and semantic conventions.
- Develop a coherent approach for instrumentation configuration.
- Develop a coherent approach to the management and ownership of instrumentation code.
- Documentation to assist new contributors in writing instrumentation.
- Test harness to assist contributors and reviewers with verifying instrumentation quality.

**Target Personas:**

- Instrumentation authors: Authors of instrumentation.
- Library authors: OSS library authors adding native instrumentation.
- Application owners: Installers of instrumentation.

For more details see - https://docs.google.com/document/d/1YNRCg9fdjJgZRs56vvf7rfFPk06mhp781sWHYypOaAk/edit#heading=h.f7ta67ofb8f

cc: @pyohannes @productml-ai @tedsuo

**Comment by alolita** [comment]
Once approved, I can create the calendar event on the OTEL calendar.

**Comment by tedsuo** [comment]
Just FYI, 1600 Pacific on Tuesday is the Asia/Pacific spec SIG meeting. We've already been using that meeting as the de facto instrumentation SIG meeting, so it is probably fine to officially convert it. But @anuraaga let us know if you feel like you need an additional time slot to discuss non-instrumentation spec items.

**Comment by obecny** [comment]
thumbs up

**Comment by ocelotl** [comment]
:sunglasses:

**Comment by tedsuo** [comment]
Following up on this issue, now have an instrumentation SIG. We currently have two meetings per week; meeting details can be found on the [OpenTelemetry calendar](https://github.com/open-telemetry/community#special-interest-groups).

Also, please join the [#otel-instrumentation](https://cloud-native.slack.com/archives/C01QZFGMLQ7) slack channel to get alerted to new issues/PRs and have async discussions.
