### ISSUE TITLE
Request for an Instrumentation Semantic Conventions workgroup

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#803]
A telemetry system is only as good as the data it emits. OpenTelemetry provides APIs for recording traces, metrics, and logs. Currently, only the tracing API is stable. The metrics API is expected to be stable at the end of 2021, followed by the logging API in Q1 of 2022.

For every type of common software component (HTTP, gRPC, SQL, Kafka, etc), OpenTelemetry also provides definitions for the specific keys and values which must be recorded. This ensures that the data OpenTelemetry produces is as useful as possible, and is consistent across languages and libraries. These definitions are called semantic conventions.

Today, these semantic conventions are incomplete. They must be reviewed by subject matter experts to ensure that the emitted data is high quality and correct, and the configuration options provide sufficient customization for real world usage. Until this happens, the semantic conventions are marked as experimental.

Once these conventions are stable, instrumentation must be written for every major open source framework and library. OpenTelemetry will not be fully mature until this instrumentation exists and becomes stable.

In this workgroup, we'd like to focus on defining semantic conventions for instrumentation. 

The proposed time for this workgroup is: **Mondays at 1130 AM - Noon Pacific Time.**

For more details on Instrumentation semantic conventions work done so far, please see https://docs.google.com/document/d/1gAD5wqqf74XNLtTL6CbB7kHfooh9kovbFI8pQhhYrzE/edit#

For general Instrumentation discussions so far, please see: https://docs.google.com/document/d/1YNRCg9fdjJgZRs56vvf7rfFPk06mhp781sWHYypOaAk/edit#heading=h.f7ta67ofb8f

For reference please see request for Instrumentation SIG at https://github.com/open-telemetry/community/issues/802

cc: @pyohannes @productml-ai @jsuereth @tedsuo

**Comment by alolita** [comment]
Once approved, I can create the calendar event on the OTEL calendar.

**Comment by tedsuo** [comment]
That time slot works for me!

**Comment by jsuereth** [comment]
Suprisingly, this works for me too!  Looking forward to this sig.

**Comment by jamesmoessis** [comment]
Are there other APAC-friendly SIGs where the semantic convention is being discussed? There is significant interest in the semantic convention from my side, but this time (4.30am AEST) doesn't really work for APAC.

**Comment by cobly** [comment]
I would also be interested in an Australian friendly time.

**Comment by hstan** [comment]
I'm interested and also work from Australia (AEST)

**Comment by tedsuo** [comment]
FYI there is also an APAC-friendly meeting being discussed: https://github.com/open-telemetry/community/issues/802

**Comment by jamesmoessis** [comment]
Great, I suppose the APAC folk can attend that one. Thanks @tedsuo!

**Comment by tedsuo** [comment]
No prob!

**Comment by Oberon00** [comment]
Would this be a WG of the instrumentation SIG (#802) or the existing spec SIG?

**Comment by ocelotl** [comment]
:sunglasses:

**Comment by pyohannes** [comment]
> Would this be a WG of the proposed instrumentation SIG (#802) or the existing spec SIG?

@Oberon00 This would be a workgroup of the instrumentation SIG proposed in #802.

**Comment by productml-ai** [comment]
Given that we have instrumentation SIG on Tuesday #802, it was discussed that we don't need the additional Monday 11:30 AM PST meeting. @alolita can assist with removing it from the public calendar?

**Comment by tedsuo** [comment]
Following up on this issue, now have an instrumentation SIG. We currently have two meetings per week; meeting details can be found on the [OpenTelemetry calendar](https://github.com/open-telemetry/community#special-interest-groups). (@productml-ai I've removed the Monday meeting from the calendar.)

Everyone interested, please join the [#otel-instrumentation](https://cloud-native.slack.com/archives/C01QZFGMLQ7) slack channel to get alerted to new issues/PRs and have async discussions.
