### ISSUE TITLE
REQUEST: New membership for productml-ai

### ISSUE THREAD

**Issue by productml-ai** [open-telemetry/community#804]
### GitHub Username

e.g. @productml-ai

### Requirements

- [Y] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [Y] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [Y] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [Y] I am actively contributing to 1 or more OpenTelemetry subprojects
- [Y] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [Y] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @pyohannes
- @alolita 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with: Instrumentation, Semantic Conventions, Messaging

**Comment by pyohannes** [comment]
I support @productml-ai for OpenTelemetry membership.

**Comment by tedsuo** [comment]
+1 I endorse.

**Comment by SergeyKanzhelev** [comment]
Welcome, @productml-ai! Invite sent
