### ISSUE TITLE
Request for a messaging semantic conventions for tracing workgroup

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/community#805]
While a variety of different messaging systems exist, most of them have similar concepts, and [standardization efforts exist](https://github.com/cloudevents/spec). Messaging systems play an important part in many observability scenarios, and it is important that OpenTelemetry provides stable conventions and guidelines for instrumenting those systems.

[Semantic conventions for messaging systems](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md) are available, but are in an experimental state. Related to the general semantic conventions workgroup requested in #803, we would like to request an additional workgroup that exclusively focuses on bringing semantic conventions for messaging into a stable state.

We plan to discuss the following areas and capture the results in an OTEP:
- Terminology/Definitions
- Scenarios
- Context propagation
- Conventions
- Attributes

The proposed time for this workgroup is **Thursday 8am PST**.

For reference please see request for an Instrumentation SIG in #802, and the request for a Semantic Convention workgroup in #803.

cc: @productml-ai @alolita @lmolkova

**Comment by tedsuo** [comment]
FYI Thursday 8am overlaps with the Sampling WG. If that is difficult for anyone, please let us know.

**Comment by mtwo** [comment]
@tedsuo shall I add this to the calendar?

**Comment by pyohannes** [comment]
@alolita wanted to join and expressed a preference for the Thursday 8am slot.

**Comment by pyohannes** [comment]
cc @clemensv

**Comment by tedsuo** [comment]
I checked with the Sampling SIG and it does not look like the overlap will be a problem, so we are good to go! 

@mtwo I believe we just added a fourth zoom meeting ID, I suggest using that one since all the other meetings are in use in the time slot immediately after.

**Comment by ocelotl** [comment]
:sunglasses:
