### ISSUE TITLE
REQUEST: New membership for chalin

### ISSUE THREAD

**Issue by chalin** [open-telemetry/community#807]
### GitHub Username

- @chalin

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects -- [open-telemetry/opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tedsuo 
- @mtwo

/cc @bhs @caniszczyk

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Issues: https://github.com/open-telemetry/opentelemetry.io/issues?q=+is%3Aissue+author%3Achalin+
- PRs: https://github.com/open-telemetry/opentelemetry.io/pulls?q=+is%3Apr+author%3Achalin
- SIG projects I am involved with: [Comms / website](https://github.com/open-telemetry/opentelemetry.io)

**Comment by tedsuo** [comment]
I support!

**Comment by mtwo** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @chalin! Invite sent
