### ISSUE TITLE
Add `github-actions[bot]` to EasyCLA allowlist

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#809]
Similar to https://github.com/open-telemetry/community/issues/306 which was resolved by @lizthegrey  making a request to the CNCF: https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-1388

I would make a similar request myself (as a member of the GC) but I'm honestly not sure if I have the authority to do so without official approval of the GC or TC.

Example PR with failing CLA https://github.com/open-telemetry/opentelemetry-js/pull/2409

**Comment by lizthegrey** [comment]
@open-telemetry/governance-committee can we get a vote please?

**Comment by lizthegrey** [comment]
that's certainly unanimous. submitting ticket.

**Comment by dyladan** [comment]
Is there any update on this?

**Comment by lizthegrey** [comment]
EasyCLA ticket marked as work in progress

**Comment by dyladan** [comment]
Should I be worried the CNCF might deny this request? I hadn't expected it to take more than a week after the ticket was created in their system.

**Comment by lizthegrey** [comment]
No, they just have never had a request for github-actions[bot] to be exempted whereas they have had dependabot added before.

**Comment by bogdandrutu** [comment]
@lizthegrey any update on this?

**Comment by trask** [comment]
> The issue is that if we approve this set of actions for your repo, then that would potentially approve any set of actions created for any repos under the CNCF cla group.

To address this concern, is it an option to create our own bot account(s), scoped either to opentelemetry, or even to a specific opentelemetry repository?

**Comment by lizthegrey** [comment]
Yes, that would be better, then CNCF could approve that specific bot.

**Comment by dyladan** [comment]
So the workaround is to register a user in github, give that user permission, and generate a token to perform actions on behalf of that user. CNCF can then allowlist the user as a bot user.
