### ISSUE TITLE
REQUEST: approver status for chalin

### ISSUE THREAD

**Issue by chalin** [open-telemetry/community#811]
While I have maintainer status, this request is for approver status.

### GitHub Username

@chalin

### Sponsors

- @tedsuo 
- @caniszczyk 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

**Comment by mtwo** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
what is the request specifically? Membership issue is used for org membership, individual SIGs maintainers are self-service. 

Teams mambership and codeowners files needs to be kept in-sync:

![image](https://user-images.githubusercontent.com/9950081/129270231-bace2586-edb0-45cd-bfd8-909a4b8981a5.png)


https://github.com/open-telemetry/opentelemetry.io#contributing

**Comment by SergeyKanzhelev** [comment]
lmk if help is needed
