### ISSUE TITLE
REQUEST: New membership for zhyChesterCheung

### ISSUE THREAD

**Issue by zhyChesterCheung** [open-telemetry/community#813]
### GitHub Username

@zhyChesterCheung

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @MrAlias 
- @jmacd 

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
    - [open-telemetry/opentelemetry-go#2022](https://github.com/open-telemetry/opentelemetry-go/pull/2022)
    - [open-telemetry/opentelemetry-go#2097](https://github.com/open-telemetry/opentelemetry-go/pull/2097)
    - [open-telemetry/opentelemetry-go#1973](https://github.com/open-telemetry/opentelemetry-go/pull/1973)
- Issues responded to
- SIG projects I am involved with
    - https://github.com/open-telemetry/opentelemetry-go

**Comment by MrAlias** [comment]
I approve.

**Comment by jmacd** [comment]
I approve!

**Comment by SergeyKanzhelev** [comment]
Welcome, @zhyChesterCheung! invite sent
