### ISSUE TITLE
Create team for assign-reviewers-action-maintainers

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#814]
So far I have been the sole author of the assign-reviewers-action. It was created in my own account and migrated to https://github.com/open-telemetry/assign-reviewers-action. I have asked for additional maintenance help and @obecny and @Rauno56 both agreed.

Please made a new team assign-reviewers-action-maintainers with the following users:

- @dyladan 
- @obecny 
- @Rauno56 

Team should have access to https://github.com/open-telemetry/assign-reviewers-action repository

**Comment by obecny** [comment]
confirm +1

**Comment by SergeyKanzhelev** [comment]
team: https://github.com/orgs/open-telemetry/teams/assign-reviewers-action-maintainers/members

**Comment by SergeyKanzhelev** [comment]
Access given
