### ISSUE TITLE
REQUEST: New membership for Enkelian

### ISSUE THREAD

**Issue by Enkelian** [open-telemetry/community#817]
### GitHub Username

@Enkelian

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mateuszrzeszutek 
- @trask 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
   - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3717
   - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3683
   - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3585
   - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3539
   - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3506
   - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3946
   - https://github.com/open-telemetry/opentelemetry-java/pull/3396
- Issues responded to
   - see above PRs for linked issues
   - created https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3706

**Comment by mateuszrzeszutek** [comment]
I support this application - welcome! 🚀

**Comment by trask** [comment]
I support as well 👍

**Comment by SergeyKanzhelev** [comment]
Welcome, @Enkelian! Invite sent
