### ISSUE TITLE
Back-to-back meetings on same zoom channel

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#824]
Hey all,

The new Instrumentation: Messaging SIG uses the same zoom channel as, and occurs right before, the Java SIG on Thu morning.

I think we were able to reset the recording this morning by having everyone log out and log back into the meeting, but would be great if we can avoid this.

Given the number of Thu morning meetings, maybe we need another Zoom room?

Thanks,
Trask

**Comment by mtwo** [comment]
Shoot, yeah, with our current set of three Zoom rooms we can’t make any improvement. Given that we have two simultaneous meetings at 8:00 AM PT and three simultaneous meetings at 9:00 AM PT, we will need five Zoom rooms.

@amye is it possible for us to get two more Zoom rooms, or are we maxed out at three? If we're able to get more, shall I file a CNCF helpdesk ticket?

**Comment by amye** [comment]
Servicedesk please, someone will be able to look into this for you.

**Comment by mtwo** [comment]
Will do

**Comment by SergeyKanzhelev** [comment]
hm, we have 4 now: https://github.com/open-telemetry/community/issues/763

**Comment by SergeyKanzhelev** [comment]
I see, there are 5 meetings back to back or the same time

**Comment by trask** [comment]
@mtwo any update on this?

**Comment by amye** [comment]
Servicedesk.cncf.io is where this should be filed, we cannot track GH

**Comment by mtwo** [comment]
@trask apologies, this fell off of my radar. Filing today.

**Comment by mtwo** [comment]
Looks like my service desk account was tied to my old work email address. I've put in a request to get an account tied to my personal email address, and I'll request the two Zoom rooms once I gain access.

**Comment by mtwo** [comment]
I'm in (thanks @amye)! Filed CNCFSD-937.

**Comment by arminru** [comment]
@mtwo Please make sure that the Zoom account host keys referenced in the document added in #618 still continue to work in case we have to mute or kick any Zoom bombers.

**Comment by mtwo** [comment]
Will do - currently investigating whether we can use a Google calendar integration for unique meeting codes. It turns out that the Kubernetes community is having the same challenge as us too, but so far they’re sticking with Zoom rooms and a very large number of Zoom accounts (same as what we do today).
________________________________

**Comment by trask** [comment]
@mtwo checking in on progress, as this continues to be a problem on Thursday mornings, thx

**Comment by trask** [comment]
@mtwo bump, we continue to have problems on Thu mornings with back-to-back Messaging SIG and Java SIG meetings using the same zoon channel

**Comment by mtwo** [comment]
After a few weeks of testing (ensuring that simultaneous meetings work, etc.), I created a shiny new Google account for the project last night (it's tied to the GC mailing list) and I just finished generating unique IDs for each meeting!

This should now be fixed. I'm going to close the issue and I will remove the Zoom links in our community pages later today. Please ping me on Slack if a meeting doesn't work.
