### ISSUE TITLE
REQUEST: New membership for Yun-Ting

### ISSUE THREAD

**Issue by Yun-Ting** [open-telemetry/community#825]
### GitHub Username
@Yun-Ting

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@cijothomas 
@alanwest 

### List of contributions to the OpenTelemetry project
- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2302
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2296
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2299
- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-dotnet

**Comment by cijothomas** [comment]
I Support.

**Comment by alanwest** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @Yun-Ting! Invite sent

**Comment by Yun-Ting** [comment]
Thanks @cijothomas, @alanwest and @SergeyKanzhelev!
I accepted the invite and now I'm a member of Opentelemetry.
