### ISSUE TITLE
Proposal to create a SIG for Real User Monitoring

### ISSUE THREAD

**Issue by martinkuba** [open-telemetry/community#830]
Hello! I would like to propose that a new SIG is created for Real User Monitoring use cases.

The goal of this group, I think, should be standardizing how RUM data is represented, so that RUM instrumentation is portable across different backends/vendors.

Example use cases
* representing user session
* representing user interaction
* representing events with no duration (e.g. paint timing, network change event) 

There is a recent [OTEP proposal](https://github.com/open-telemetry/oteps/issues/169) that attempts to address these use cases by introducing a new signal in the OpenTelemetry data model. Based on the comments on this proposal, there seems to be a number of different opinions on how it should be tackled.

There is also an existing [Slack channel for client-side telemetry](https://cloud-native.slack.com/archives/C0239SYARD2) where some of this has also been discussed.

The immediate focus of this group would be
* decide whether a new signal is needed
* decide which signals make sense for different use cases
* define semantic conventions

If anyone else is interested, please comment.

**Comment by jkwatson** [comment]
Yes please!

**Comment by scheler** [comment]
Yes, please include me.

**Comment by stefaneberl** [comment]
Yes, please include me.

**Comment by rr0214** [comment]
yes, yes. I am interested.

**Comment by svrnm** [comment]
+1

**Comment by martinkuba** [comment]
I would like to propose meeting on **Wednesdays 8am Pacific Time**, which would work for European time zones. Please thumbs up if that works for you, or propose a different time.

**Comment by scheler** [comment]
8.30am PT is preferable for me (after the school drop off)

**Comment by svrnm** [comment]
If the meeting is scheduled for longer than 1hr, 8:30am Wednesday would conflict with the JS SIG, that starts at 9am (not sure how many people are interested in both)

**Comment by jkwatson** [comment]
> If the meeting is scheduled for longer than 1hr, 8:30am Wednesday would conflict with the JS SIG, that starts at 9am (not sure how many people are interested in both)

I would think that the overlap would be quite high, given the need for browser-based RUM.

**Comment by martinkuba** [comment]
1/2 hour weekly might be good enough, but a few other options I can think of

1. Thursdays 9am Pacific - would conflict with Java, Python, and Swift, but probably ok?
2. Tuesdays 10am - seems open, less ideal for EU folks
3. Mondays 10am - same as above

**Comment by jkwatson** [comment]
> 1. Thursdays 9am Pacific - would conflict with Java, Python, and Swift, but probably ok?

Conflicting with Java & Swift seems very problematic...given iOS and Android. ;)

**Comment by ssidhu-apm** [comment]
Very interested in joining. 8 / 8.30 am PT on Wednesdays for 30 minutes would be great (already added 👍 for both comments).

**Comment by ivomagi** [comment]
Interested in joining 8 or 830 AM PT on Wed would match my European calendar

**Comment by martinkuba** [comment]
Let's go with 8:30 on Wednesdays for 1/2 hour to start with. If we consistently need more time, then we can revisit.

**Comment by scheler** [comment]
Sounds good to me.

**Comment by martinkuba** [comment]
@tedsuo Would you be able to help us with putting this on the calendar?

**Comment by mtwo** [comment]
Creating this now

**Comment by mtwo** [comment]
Crap, we already have three meetings during that period and we only have three Zoom accounts. I'll contact the CNCF to make another account. For now I'm going to set the meeting to start at 9:00 so that it doesn't overlap.

**Comment by mtwo** [comment]
Done. We can adjust the time to 8:30 once we get more Zoom accounts.

**Comment by kalyansai99** [comment]
I am interested in joining too. Please include me. Thanks.

**Comment by jkwatson** [comment]
> I am interested in joining too. Please include me. Thanks.

The meetings will be fully public, so feel free to join in! All are welcome.

**Comment by SergeyKanzhelev** [comment]
> Crap, we already have three meetings during that period and we only have three Zoom accounts. I'll contact the CNCF to make another account. For now I'm going to set the meeting to start at 9:00 so that it doesn't overlap.

there are four accounts. Please check the document

**Comment by mtwo** [comment]
> there are four accounts. Please check the document

Nice! I'll update this then. I've reduced my ask on #824 to only request one additional account.

**Comment by flands** [comment]
Hey folks -- can someone add this to the SIG table in the README?

**Comment by mtwo** [comment]
Created #879 to add this to the list
