### ISSUE TITLE
Add Slack GitHub App to either org or Java repos

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#836]
I'd like to set up automatically posting to our Slack channel when we create a GitHub release. AFAIK, CNCF slack already has the GitHub integration available and it is ready, but we need to install an app on the GitHub side too.

https://github.com/apps/slack/

Is it possible to install this for `opentelemetry-java`, `opentelemetry-java-instrumentation`, `opentelemetry-java-contrib` at least, if not for the entire org?

**Comment by anuraaga** [comment]
@SergeyKanzhelev or anyone, just wondering if you could get a chance to look at this. Thanks!

**Comment by SergeyKanzhelev** [comment]
In general our policy to not install any extensions. I'd bring it to the discussion today at GC meeting, I feel it may be useful

**Comment by SergeyKanzhelev** [comment]
Approved. Installed. Also created https://github.com/open-telemetry/community/pull/841
