### ISSUE TITLE
REQUEST: New membership for hyunuk

### ISSUE THREAD

**Issue by hyunuk** [open-telemetry/community#839]
### GitHub Username

@hyunuk

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
 https://github.com/open-telemetry/opentelemetry-collector/pull/3956
 https://github.com/open-telemetry/opentelemetry-collector/pull/4020
 https://github.com/open-telemetry/opentelemetry-collector/pull/4055
 https://github.com/open-telemetry/opentelemetry-collector/pull/4083
 https://github.com/open-telemetry/opentelemetry-collector/pull/4088
 https://github.com/open-telemetry/opentelemetry-collector/pull/4441
 https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5186
 https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5466
 https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5454
 https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5539
 https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5540
 https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5541
- Issues responded to
 https://github.com/open-telemetry/opentelemetry-collector/issues/2548
 https://github.com/open-telemetry/opentelemetry-collector/issues/2704
 https://github.com/open-telemetry/opentelemetry-collector/issues/3875
 https://github.com/open-telemetry/opentelemetry-collector/issues/3876
 https://github.com/open-telemetry/opentelemetry-collector/issues/3998
 https://github.com/open-telemetry/opentelemetry-collector/issues/2766
 https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5433
 https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5385

- SIG projects I am involved with
[Notes: OpenTelemetry Prometheus Workgroup](https://docs.google.com/document/d/19bnXziPn2MZ9wO6684UoI4D-LCjGL5bTJkGhux29bx8/edit#heading=h.twuztjjsq6rr)
[OpenTelemetry SIG: Agent/Collector](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.am4gwetk416e)
[OpenTelemetry SIG: specifications](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.fg5sud5g9pgx)

**Comment by SergeyKanzhelev** [comment]
> Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company

It looks like both sponsors are affiliated with the same company. Please find another sponsor and re-open the request.

**Comment by jpkrohling** [comment]
I support @hyunuk's membership and look forward for the future contributions!

**Comment by alolita** [comment]
I support this membership. @SergeyKanzhelev thanks for reopening the issue.

**Comment by SergeyKanzhelev** [comment]
Welcome, @hyunuk! Invite sent
