### ISSUE TITLE
REQUEST: New membership for @KSerrania

### ISSUE THREAD

**Issue by KSerrania** [open-telemetry/community#846]
### GitHub Username

@KSerrania

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @mx-psi 
- @ericmustin

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

PRs authored:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5417
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1897
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1782

PRs reviewed:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5265
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5082
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4605
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4597
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3797

**Comment by mx-psi** [comment]
I support

**Comment by ericmustin** [comment]
I support @KSerrania membership

**Comment by SergeyKanzhelev** [comment]
Similar to https://github.com/open-telemetry/community/issues/490#issuecomment-695091868 and https://github.com/open-telemetry/community/issues/839#issuecomment-919434582 it appears that both sponsors are from the same company. Please re-open once you find a new sponsor

**Comment by mx-psi** [comment]
@SergeyKanzhelev while we both used to work at Datadog, each sponsor works at a different company today (I remain at Datadog while @ericmustin has a different employer now). 

I will let Eric speak for himself but I believe this issue should be reopened :)

**Comment by SergeyKanzhelev** [comment]
I'm using https://opentelemetry.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1 to check for affiliation. @ericmustin please confirm.

(btw, you can correct devstats affiliation here: https://github.com/cncf/gitdm#addingupdating-affiliation)

**Comment by ericmustin** [comment]
@mx-psi @SergeyKanzhelev yup i'm at shopify now, not datadog. i'll update the devstats affiliation when i get a sec.

**Comment by SergeyKanzhelev** [comment]
Thank you for confirmation!

Welcome, @KSerrania! Invite sent.

**Comment by ericmustin** [comment]
@SergeyKanzhelev would you mind 👍 when u have a momen or pointing me to the appropriate reviewert? https://github.com/cncf/gitdm/pull/790
