### ISSUE TITLE
List areas of interest of TC members

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#848]
Besides broad project-wide responsibilities many TC members also have specific areas of interest at OpenTelemetry and often lead initiative for the particular area. We would like to show this information more visibly for 2 reasons:
- Make it easy for the community to find the right person for a topic of interest (e.g. seek feedback on an issue by tagging them explicitly).
- Highlight the areas which are looking for someone to lead the particular area and encourage experienced members to take the lead. These do not necessarily have to be TC members but can be any person interested in driving this topic.

This information should be linked from the ["how to" contributing guides](https://github.com/open-telemetry/opentelemetry-specification/issues/1961) so that contributors can seek help if they need it. Encourage members to ask the right TC Member for help directly if necessary.

**Comment by lizthegrey** [comment]
I'm very very excited about this as we differentiate more functional leadership, both within and outside the TC
