### ISSUE TITLE
Clarify ad hoc workgroup operation

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#849]
Write a document that encourages contributors to form ad hoc workgroups for topics that currently don't have one and which require discussion and will result in an OpenTelemetry proposal (OTEP). Ad hoc workgroups can be formed by members who want to work on a particular problem and do not require a permission from OpenTelemetry (but see the next paragraphs on how to set up for success). The document should describe the common practices that workgroups typically follow (recurring meetings, meeting notes document, etc).

The document must clearly outline that the expectation from ad hoc workgroups is a proposal, which will then follow the proposals (OTEPs) process and that forming an ad hoc workgroup does not automatically give the workgroup a mandate to make unilateral decisions for a particular area.

Encourage ad hoc workgroups to seek early and regular participation from a TC member or a spec approver in order to get feedback and help getting steered in the right OpenTelemetry-centric direction to avoid last minute surprise rejections.

**Comment by trask** [comment]
I think this can be closed now by https://github.com/open-telemetry/community/blob/main/project-management.md
