### ISSUE TITLE
SQLCommenter: call for maintainers

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#854]
As per https://github.com/open-telemetry/community/issues/783 we plan to create a repository for code transfer and this isa call for maintainers/approvers interested to join this sub-project.

POR:
- Transfer code with the updated Copyright
- Rename google-branded packages to opentelemetry branded
- Configure everything to ensure a first release from the opentelemetry repo
- Start work on unification/standardization of SqlCommenter

Initial maintainers: @sjs994,

**Comment by lonewolf3739** [comment]
I can volunteer to help with py/js parts of the project.

**Comment by SergeyKanzhelev** [comment]
https://github.com/open-telemetry/opentelemetry-sqlcommenter

Created. Both @sjs994, and @lonewolf3739 are maintainers. Keeping this issue open if anybody wants to join this project

**Comment by aabmass** [comment]
@SergeyKanzhelev I'm happy to help out as well!

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev I'm happy to help out as well!

thank you! Added you as a maintainer

**Comment by jsuereth** [comment]
I'm happy to help as an approver

**Comment by weyert** [comment]
I would be happy to assist with this project. I was planning to add support for TypeORM anyways :)

**Comment by SergeyKanzhelev** [comment]
> I would be happy to assist with this project. I was planning to add support for TypeORM anyways :)

Welcome! Maintainer or approver? Responsibilities differ, find out at https://github.com/open-telemetry/community/blob/main/community-membership.md

**Comment by SergeyKanzhelev** [comment]
Added both. Thank you!
