### ISSUE TITLE
Request for repository - opentelemetry-proto-java

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#855]
To allow users a way to consume the OTLP proto in Java builds, we'd like to officially publish the protos for Java in a new repository.

https://github.com/open-telemetry/opentelemetry-proto/issues/335

This repository would essentially have a version that tracks the one in `opentelemetry-proto` and a simple build script / release workflow for publishing the protos to Maven Central.

The maintainers / approvers for this repo can match the ones for `opentelemetry-java`.

**Comment by tigrannajaryan** [comment]
We need the following information to create a new repo:
- The repo name. For Go a similar role is served by opentelemetry-proto-go, so I suppose opentelemetry-proto-java is fine?
- The initial list of maintainers and approvers.
- Any special repo settings, if needed.

**Comment by anuraaga** [comment]
> The repo name. For Go a similar role is served by opentelemetry-proto-go, so I suppose opentelemetry-proto-java is fine?

Yeah `opentelemetry-proto-java`

> The initial list of maintainers and approvers.

Is it possible to just have the new teams delegate to the existing ones for `opentelemetry-java`? So `opentelemetry-proto-java-maintainers` -> `opentelemetry-java-maintainers`, etc?

> Any special repo settings, if needed.

Don't think so as long as the maintainers have admin access, like the other Java repos.

**Comment by tigrannajaryan** [comment]
`opentelemetry-proto-java` created and `java-approvers` and `java-maintainers` have the same rights as in `opentelemetry-java`.

There are 2 deviations from what is recommended in https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md:
- It uses approvers and maintainers from another repo instead of its own. I think this is OK to do since the 2 repos are really tied together.
- Maintainers have Admin rights (like in `opentelemetry-java`) , but the guidelines recommend Maintainer rights only. I think Admin rights are needed for initial setup, don't know if we are OK with keeping the rights permanently.

@open-telemetry/technical-committee are you OK with this deviations from the guidelines?

**Comment by tigrannajaryan** [comment]
@lizthegrey @bogdandrutu please setup EasyCLA in `opentelemetry-proto-java`.

**Comment by anuraaga** [comment]
Thanks @tigrannajaryan!

> I think Admin rights are needed for initial setup, don't know if we are OK with keeping the rights permanently.

The critical part is indeed setup, in particular storing my personal credentials for publishing to Maven Central.

But I believe maintainers do need to be able to break glass in exceptional cases and deserve that freedom / trust for the work to put in. My recommendation is changing that default to giving Admin rights and implementing a periodic CI workflow that checks settings of the org's repos to verify compliance to core requirements if that is a concern. It may result in fix forward situations but seems fair.

**Comment by lizthegrey** [comment]
> @lizthegrey @bogdandrutu please setup EasyCLA in `opentelemetry-proto-java`.

it should be automatically configured as per the new EasyCLA tooling; let me know if the branch checks don't appear

**Comment by SergeyKanzhelev** [comment]
> @open-telemetry/technical-committee are you OK with this deviations from the guidelines?

It is not uncommon that admin permissions are given to maintainers. We need to re-visit that document. Lack of admin permissions is mostly a safety concern over loosing code completely (accidental delete like we had with the gitter rooms) and un-configuring EasyCLA and allowing "dangerous" code (again, by mistake, without malicious intention). This limitation is hovwer creates too much friction. So maybe we can address these concern some other way, by regular backups and automatic restoring of Easy CLA by robot.

To answer @tigrannajaryan , I agree with the deviation

**Comment by lizthegrey** [comment]
EasyCLA is now auto-robot-managed. I have no objections to giving maintainers admin if that's the only reason

**Comment by tigrannajaryan** [comment]
@lizthegrey @SergeyKanzhelev thanks! 

Closing the ticket, all done.
