### ISSUE TITLE
REQUEST: New membership for @BinaryFissionGames

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/community#859]
### GitHub Username

@BinaryFissionGames

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski
- @tigrannajaryan

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

PRs authored:
* https://github.com/open-telemetry/opentelemetry-log-collection/pull/283
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3803
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3884
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4113
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5376

PRs reviewed (informally):
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5540

**Comment by djaglowski** [comment]
I support

**Comment by tigrannajaryan** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @BinaryFissionGames! Invite sent
