### ISSUE TITLE
Agent Management Workgroup formation

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#860]
I'd like to start an Agent Management Workgroup to work on [Agent Management](https://github.com/open-telemetry/opentelemetry-collector/issues/4165), [Remote Configuration](https://github.com/open-telemetry/opentelemetry-collector/issues/2374) and related topics. I invite all interested open source contributors and observability experts to participate.

I will run a survey to choose a time for a regular workgroup meeting once we have the list of interested participants.

The need for a separate Github repository will be likely clarified after the first workgroup meeting.

(cc @alolita @bogdandrutu @mtwo @Aneurysm9 @pmm-sumo @portertech @zenmoto @pmm-sumo @jodeev).

**Comment by djaglowski** [comment]
👍  I'm interested

**Comment by mtwo** [comment]
I'm interested, and I know that @aunshc will be as well

**Comment by alolita** [comment]
Thanks @tigrannajaryan +100 Look forward to participating and continuing to work towards making Collector management easier for developers and end-users.

**Comment by pavankrish123** [comment]
Thank you @tigrannajaryan ! Count us in +1

**Comment by tigrannajaryan** [comment]
Hi everyone.

Here is a pool for a meeting time for this workgroup: https://doodle.com/poll/ft38udvwy6fgit5n

Please make sure you select all times that work for you on Mon, Tue, Thu. Tick the checkboxes twice to select "Yes, if need be" vote.

I think we can start with a biweekly and adjust as needed.
