### ISSUE TITLE
Rename opentelemetry-java-contrib-* groups

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#861]
Can someone with permissions (@open-telemetry/technical-committee I think?) rename these two groups to match the normal group naming convention?

* @open-telemetry/opentelemetry-java-contrib-maintainers -> @open-telemetry/java-contrib-maintainers 
* @open-telemetry/opentelemetry-java-contrib-approvers -> @open-telemetry/java-contrib-approvers

(btw it looks like there are a couple of other groups that have the extra `opentelemetry-` prefix: https://github.com/orgs/open-telemetry/teams?query=opentelemetry-)

thx!

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/opentelemetry-python-contrib-approvers do you want a rename?

**Comment by aabmass** [comment]
Discussed at the Python SIG, we want to just leave the team names as they are. I noticed it breaks \@mentions of the old team names so are happy to live with it.
