### ISSUE TITLE
Meeting recordings not being uploaded to Youtube: migrate the tool to a GH action

### ISSUE THREAD

**Issue by rauno56** [open-telemetry/community#863]
It seems the uploads of meeting recordings have stopped. The last one is from more than a month ago:

Looking at here: https://www.youtube.com/channel/UCHZDBZTIfdy94xMjMKz-_MA/videos

**Comment by eddynaka** [comment]
Hi @SergeyKanzhelev ,

I just started again.
We should create a plan to move to GH actions or something like that that executes every day?

**Comment by SergeyKanzhelev** [comment]
reviving this thread. This happened again

@eddynaka have you thought of moving the tool to a GH action?

**Comment by eddynaka** [comment]
Hi @SergeyKanzhelev , i haven't had much time to take a look at that.
Sorry.

**Comment by SergeyKanzhelev** [comment]
no worries. I updated the bug title and marked as help wanted. Can you please restart the tool locally for now to catch up on recordings, please?

**Comment by tedsuo** [comment]
fyi OTel changed how the zoom meetings are being generated: https://github.com/open-telemetry/community/blob/main/docs/how-to-handle-public-calendar.md

**Comment by alanwest** [comment]
I can try resolving this issue. My understanding of how things used to work is that [this tool](https://github.com/open-telemetry/community/tree/main/tools/OpenTelemetryYoutube) was somehow run on a schedule (or manually?).

I assume I'd need credentials to access the YouTube channel. Is this something someone can grant me access to? Or is there a better way to provide this access?

**Comment by SergeyKanzhelev** [comment]
@alanwest send me your gmail account and I will give you permissions for the Youtube channel. From there you will need to get your account token and use it in the tool
