### ISSUE TITLE
Update opentelemetry.io/status with latest progress as of October 2021

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#869]
@tedsuo can you please update opentelemetry.io/status page with the latest progress on OTEL Collector, APIs, SDKs... 

Please use the updated text below.

Tracing

API: stable
SDK: stable
Protocol: stable
Collector: stable

- The tracing specification is now completely stable, and covered by long term support.
- The tracing specification is still extensible, but only in a backwards compatible manner.
- OpenTelemetry clients are versioned to v1.0 once their tracing implementation is complete.

Metrics

Protocol: stable 
Collector: experimental 
API: experimental
SDK: experimental

- OpenTelemetry Metrics is currently under active development.
- The data model is stable and released as part of the OTLP protocol.
- Experimental support for metric pipelines are available in the Collector.
- Collector support for Prometheus is under development, in collaboration with the Prometheus community.
- The metric API and SDK specification is currently being prototyped in Java, .NET, and Python.

Logging

API: draft
SDK: experimental
Protocol: beta
Collector: experimental
    
- OpenTelemetry Logging is currently under active development.
- The data model is experimental and released as part of the OTLP protocol.
- Log processing for many data formats has been added to the Collector, thanks to the donation of Stanza to the the OpenTelemetry project.
- Log appenders are currently under develop in many languages. Log appenders allow OpenTelemetry tracing data, such as trace and span IDs, to be appended to existing logging systems.
- An OpenTelemetry logging SDK is currently under development. This allows OpenTelemetry clients to ingest logging data from existing logging systems, outputting logs as part of OTLP along with tracing and metrics.
- An OpenTelemetry logging API is not currently under development. We are focusing first on integration with existing logging systems. When metrics is stable, focus will shift to development of an OpenTelemetry logging API.

**Comment by trask** [comment]
this looks like it has been completed now

I see the above notes under the specification status now

@alolita is it ok to close this?
