### ISSUE TITLE
REQUEST: New membership for @JamesJHPark

### ISSUE THREAD

**Issue by JamesJHPark** [open-telemetry/community#900]
### GitHub Username

@JamesJHPark

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita
- @dashpole

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project
- PRs reviewed / authored
   * https://github.com/open-telemetry/opentelemetry-python/pull/2237
   * https://github.com/open-telemetry/opentelemetry-python/pull/2154
   * https://github.com/open-telemetry/opentelemetry-helm-charts/pull/93
   * https://github.com/open-telemetry/opentelemetry-collector/pull/4137
   * https://github.com/open-telemetry/opentelemetry-collector/pull/4087 
   * https://github.com/open-telemetry/opentelemetry-collector/pull/4082 
   * https://github.com/open-telemetry/opentelemetry-js-api/pull/132
   * https://github.com/open-telemetry/opentelemetry-js/pull/2604
   * https://github.com/open-telemetry/opentelemetry-js/pull/2463 
- Issues responded to
please see above reviewed PRs for linked issues 
- SIG projects I am involved with
    * [OpenTelemetry Collector SIG](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.am4gwetk416e)
    * [OpenTelemetry Prometheus Workgroup](https://docs.google.com/document/d/19bnXziPn2MZ9wO6684UoI4D-LCjGL5bTJkGhux29bx8/edit)

**Comment by SergeyKanzhelev** [comment]
Thank you for interest to join the project! You'd need two sponsors. Please re-open when two sponsors are listed.

**Comment by dashpole** [comment]
I support

**Comment by alolita** [comment]
I support this membership. Thanks @SergeyKanzhelev for your help.

**Comment by SergeyKanzhelev** [comment]
Welcome, @JamesJHPark! Invite sent
