### ISSUE TITLE
Request for OpenTelemetry JVM Monitoring Working Group

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/community#901]
The Java instrumentation SiG current owns all forms of instrumentation across Java applications. With the stabilization of Metrics and the public availability of Java Flight Recorder, we'd like to form a working group across major Java monitoring solutions where we can define and stabilize semantic conventions for key JVM-specific observability.

## Audience

This group should include:
- JVM experts (GC authors, JVM impelmenters, etc.)
- Java Monitoring experts and Communities (Micrometer, Prometheus, OpenTelemetry, etc.)
- Users of Java monitoring solutions.

## Projects

- Define "T-shaped" set of semantic conventions with a "minimal" set of metrics available and "expanded" set of metrics for specific JVM impelmentation/technologies.
   - Garbage Collection
   - CPU Usage and Locking
   - possibly more, in the future.
- Prototype implementations leveraging:
  - Java Flight Recorder
  - JMX
  
This Working-Group would be lead by @kittylyst and @ebullient

## Proposed Time

For now proposing a PDT / EU Friendly times (with least conflict on other OTel meetings): 

- Mondays @ 10am PDT
- Tuesdays @ 10am PDT
- Fridays @ 9am PDT

Please vote in comments (or propose alternative times!)

**Comment by thegreystone** [comment]
Are we talking monitoring or profiling?

**Comment by jsuereth** [comment]
Initially just monitoring.  Profiling may enter in as a topic to be discussed, but out-of-scope initially

**Comment by kittylyst** [comment]
> Are we talking monitoring or profiling?

Definitely just monitoring for now - profiling is a whole different kettle of fish. Essentially, my concept for this is just taking data from JFR or another source and bridging it into the OTel API.

**Comment by breedx-splk** [comment]
Voting for Mondays @ 10am PDT

**Comment by kittylyst** [comment]
Voting for Mondays @ 10h00 in America/Los_Angeles (Canonical & unambiguous TZ names FTW)

**Comment by shakuzen** [comment]
I may be interested in participating in some form, but if PDT / EU friendly time is a goal, that will be mutually exclusive with a friendly time to my time zone (UTC+9).

**Comment by thegreystone** [comment]
Is it possible to lurk a little bit? :)

**Comment by kittylyst** [comment]
@shakuzen Apologies - we already have firm commitments from folks who are in both of those regions. Sadly a TZ that can accommodate us all globally does not exist. :(

**Comment by kittylyst** [comment]
> Is it possible to lurk a little bit? :)

Of course! Your input is most welcome and actively sought.

**Comment by marcingrzejszczak** [comment]
Hey @kittylyst , since @shakuzen is the lead of Micrometer I guess his presence is quite critical? I mean he's literally doing Micrometer... :shrug:

**Comment by kittylyst** [comment]
> Hey @kittylyst , since @shakuzen is the lead of Micrometer I guess his presence is quite critical? I mean he's literally doing Micrometer... 🤷

@marcingrzejszczak  I'm very happy to hear suggestions of times which will accommodate all of UTC + 9, UTC + 1 & UTC - 8.

**Comment by marcingrzejszczak** [comment]
It's not me that mentioned Micrometer in the list :shrug: . Maybe you can arrange 2 meetings? I have no idea, I'm not responsible for arranging these meetings. I'm just pointing out that one hand you want a Micrometer expert but on the other hand when the lead of that project chimed in you told him that he can't join.

**Comment by kittylyst** [comment]
> It's not me that mentioned Micrometer in the list 🤷 . Maybe you can arrange 2 meetings? I have no idea, I'm not responsible for arranging these meetings. I'm just pointing out that one hand you want a Micrometer expert but on the other hand when the lead of that project chimed in you told him that he can't join.

When did I say that he can't join? These are public meetings, scheduled at a time convenient for the largest number of engineers who are actively committing time and resources to the project.

It is unfortunate that this makes the time inconvenient for others, but a perfect solution does not exist, and we're doing the best we can. Many people manage to contribute very successfully to OpenTelemetry projects despite these types of timezone issues and I don't really see what you're suggesting as an alternative.

**Comment by jsuereth** [comment]
I'd be happy to have an every-other week schedule to be more accommodating of timezones.

@kittylyst IF we had an UTC +1, UTC+9 friendly time once very 2 weeks, and then a UTC-8, UTC+1 friendly time once every 2 weeks (but offset against the first) would that be acceptable?  I think you'd need to be the bridge (I"m UTC-5, so not in the best timezone for UTC+1/UTC+9 meetings).

**Comment by kittylyst** [comment]
> IF we had an UTC +1, UTC+9 friendly time once very 2 weeks, and then a UTC-8, UTC+1 friendly time once every 2 weeks (but offset against the first) would that be acceptable?

I'm totally happy with that if you & @ebullient are. As noted, mine is the easy timezone.

**Comment by ebullient** [comment]
@marcingrzejszczak ... Time zones and scheduling are always a pain. I think we'll have good coverage for micrometer between @shakuzen, @jonatan-ivanov and myself (though I realize I barely count). An alternating time slot is a good plan to ensure Tommy can participate directly, but I anticipate that Joni and I will tag-team to make sure Tommy stays in the loop.

**Comment by thegreystone** [comment]
> > Is it possible to lurk a little bit? :)
> Of course! Your input is most welcome and actively sought.

Excellent! Once you start scheduling meetings, please invite me  - marcus(at)datadoghq.com.

**Comment by kittylyst** [comment]
> > > Is it possible to lurk a little bit? :)
> > Of course! Your input is most welcome and actively sought.
> 
> Excellent! Once you start scheduling meetings, please invite me - marcus(at)datadoghq.com.

Are you happy with the proposal for alternating meetings, to accommodate both APAC & US West Coast folks? Please vote if so!

**Comment by kittylyst** [comment]
Looks like we never actually settled on a time for the meetings for the UTC +1 / UTC+9 weeks. How about:

Mon 10h00 CET / 18h00 JST
Wed 10h00 CET / 18h00 JST

@shakuzen - are either of those a good time for you? @anuraaga would you also be interested in attending?

**Comment by anuraaga** [comment]
@kittylyst - Thanks for pinging. Monday is a bit challenging for me, Wed would be better. If 9h00 CET / 17h00 JST is on the table, it could be a bit easier to join with 18h00 being a bit late, though 18h00 is still doable. Either way, I would prioritize @shakuzen's availability over mine :)

**Comment by kittylyst** [comment]
@anuraaga The only issue I can see with 09h00 CET / 17h00 JST (apart from making a really long day for me once a fortnight, which isn't going to kill me) is that it will be at 08h00 for UK / Ireland / Portugal folks, which may put it out of reach for any contributors from there.

But, to the original point, we need to prioritise the people who can definitely make it. @shakuzen - what's your availability like at those times? Is Wednesday at either 17h00 or 18h00 JST good for you? Or should we look for a set of alternative times?

**Comment by shakuzen** [comment]
> Is Wednesday at either 17h00 or 18h00 JST good for you?

Yes, either of those are doable for me.

**Comment by kittylyst** [comment]
> > Is Wednesday at either 17h00 or 18h00 JST good for you?
> 
> Yes, either of those are doable for me.

Perfect. @anuraaga are you OK with 18h00 JST just to leave the door open for UK / Ireland / Portugal folks to join as well?

**Comment by anuraaga** [comment]
@kittylyst Yeah I'm fine with 18h00 - cheers

**Comment by kittylyst** [comment]
Closed by #912
