### ISSUE TITLE
Request for repository: opentelemetry-java-docs

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/community#907]
Java currently has two primary repos, `opentelemetry-java` and `opentelemetry-java-instrumentation`. We currently have docs written in each repo for their respective focus areas, but there is a lot of correlation and overlap between the two - with the split docs though it's hard to provide a cohesive explanation to users. We'd like to have a single repo, `-java-docs` to hold a cohesive documentation and example code for Java users, explaining the SDK and instrumentation together.

Please assign
Approvers: `java-approvers`, `java-instrumentation-approvers`
Maintainers: `java-maintainers`, `java-instrumentation-maintainers`

**Comment by SergeyKanzhelev** [comment]
Done https://github.com/open-telemetry/opentelemetry-java-docs
