### ISSUE TITLE
C++ library?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [open-telemetry/community#91]
OpenCensus has a C++ library (https://github.com/census-instrumentation/opencensus-cpp), but C++ is not mentioned as a language implementation for OpenTelemetry. Is that just something you have overlooked, or is C++ not intended to be ported to OpenTelemetry?

**Comment by bogdandrutu** [comment]
We will support that, we are looking to form a SIG for this.

**Comment by SergeyKanzhelev** [comment]
@MarkusTeufelberger it's not in the first wave unless we have enough enthusiasts to help with it =).

**Comment by SergeyKanzhelev** [comment]
Closing for now. Let's open when we are ready to roll

**Comment by MarkusTeufelberger** [comment]
Thanks for the information and looking forward to either the second wave or that SIG action. :-)
