### ISSUE TITLE
Request for a subdomain

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/community#911]
OpenTelemetry Java Instrumentation SIG wants to trial a tool called [Gradle Enterprise](https://gradle.com/enterprise-customers/oss-projects/). As part of the onboarding process they require a subdomain/DNS name to point to an instance of the tool running on their premises. In our case that would be `ge.opentelemetry.io`. Is it possible to create such subdomain and point to a specific IP address?

**Comment by mtwo** [comment]
@austinlparker is this a thing that we can do?

**Comment by austinlparker** [comment]
Yes, we can do subdomain aliases. Go SIG has one, for example.

**Comment by iNikem** [comment]
@austinlparker What should I do to make it happen?

**Comment by austinlparker** [comment]
I guess just let me know what the IP address you need that domain pointed at and I can get it added.

**Comment by iNikem** [comment]
Can you please make a CNAME entry to `hosted-ge-opentelemetry.gradle.com`?

**Comment by austinlparker** [comment]
Yep, will post here when it’s done

**Comment by austinlparker** [comment]
OK, `ge.opentelemetry.io` has that CNAME you specified set up. Please give it a bit for DNS propagation.

**Comment by iNikem** [comment]
Everything works fine, thank you!
