### ISSUE TITLE
REQUEST: New membership for @esigo

### ISSUE THREAD

**Issue by esigo** [open-telemetry/community#919]
https://github.com/esigo
### GitHub Username

esigo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lalitb 
- @jsuereth

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-cpp/pull/1077
https://github.com/open-telemetry/opentelemetry-cpp/pull/1083
https://github.com/open-telemetry/opentelemetry-cpp/pull/1075
https://github.com/open-telemetry/opentelemetry-cpp/pull/1074
https://github.com/open-telemetry/opentelemetry-cpp/pull/1062
https://github.com/open-telemetry/opentelemetry-cpp/pull/1064
https://github.com/open-telemetry/opentelemetry-cpp/pull/1063
https://github.com/open-telemetry/opentelemetry-cpp/pull/1056
https://github.com/open-telemetry/opentelemetry-cpp/pull/1055
https://github.com/open-telemetry/opentelemetry-cpp/pull/1031
https://github.com/open-telemetry/opentelemetry-cpp/pull/1050
https://github.com/open-telemetry/opentelemetry-cpp/pull/1044
https://github.com/open-telemetry/opentelemetry-cpp/pull/1043
https://github.com/open-telemetry/opentelemetry-cpp/pull/910
https://github.com/open-telemetry/opentelemetry-cpp/pull/899

- Issues responded to
- SIG projects I am involved with

**Comment by SergeyKanzhelev** [comment]
To satisfy the membership application requirements, sponsors must be representing different vendors. If I'm not mistaken, both sponsor are from Microsoft. Please re-open the issue once this requirement is satisfied and we will be happy to welcome you to OpenTelemetry as a member.

**Comment by esigo** [comment]
> To satisfy the membership application requirements, sponsors must be representing different vendors. If I'm not mistaken, both sponsor are from Microsoft. Please re-open the issue once this requirement is satisfied and we will be happy to welcome you to OpenTelemetry as a member.

@SergeyKanzhelev  thanks for the feedback. I have another sponsor from Google. I edited my request. Could you please re-open the issue.
Thanks

**Comment by SergeyKanzhelev** [comment]
Great, waiting for "I support" from sponsors. Thank you!

**Comment by lalitb** [comment]
I support.

**Comment by jsuereth** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @esigo! Invite sent
