### ISSUE TITLE
REQUEST: New membership for @owent

### ISSUE THREAD

**Issue by owent** [open-telemetry/community#920]
https://github.com/owent

### GitHub Username

owent

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @lalitb 
- @tensorchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/1082
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/1080
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/1030
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/1029
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/1026
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/983
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/915
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/893
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/853
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/850
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/835
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/827
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/810
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/805
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/742
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/725
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/645
  - https://github.com/open-telemetry/opentelemetry-cpp/pull/432
  - https://github.com/open-telemetry/docs-cn/pull/58
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/424
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/665
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/724
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/740
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/741
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/803
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/804
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/826
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/834
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/849
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/892
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/914
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/1024
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/1025
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/1028
  - https://github.com/open-telemetry/opentelemetry-cpp/issues/1081
  - https://github.com/open-telemetry/docs-cn/issues/59
- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-cpp
  - https://github.com/open-telemetry/docs-cn

**Comment by lalitb** [comment]
I support

**Comment by tensorchen** [comment]
I support this request! Thank you @owent  for your contributions.

**Comment by SergeyKanzhelev** [comment]
Welcome, @owent! Invite sent
