### ISSUE TITLE
REQUEST: New membership for @mustafain117

### ISSUE THREAD

**Issue by mustafain117** [open-telemetry/community#921]
### GitHub Username

@mustafain117

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6202
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5600
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6150
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6362
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6369
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6407
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6409
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6430
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5537
  - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/689
  - https://github.com/open-telemetry/opentelemetry-js/pull/2491
  - https://github.com/open-telemetry/opentelemetry-js/pull/2494
  - https://github.com/open-telemetry/opentelemetry-js/pull/2504
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5752
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4045
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5997
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5995
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5996
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5998
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6106
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5510
  - https://github.com/open-telemetry/opentelemetry-js/issues/2278
  - https://github.com/open-telemetry/opentelemetry-js/issues/2489
  - https://github.com/open-telemetry/opentelemetry-js/issues/2145
  - https://github.com/open-telemetry/opentelemetry-js/issues/2278
- SIG projects I am involved with
  - Collector Prometheus Workgroup
  - Collector SIG

**Comment by alolita** [comment]
I support this membership.

**Comment by jpkrohling** [comment]
I also support this membership.

**Comment by jpkrohling** [comment]
@SergeyKanzhelev, it looks like I can't add folks to the organization, and I think I should:

> Once your sponsors have responded, your request will be reviewed by the Governance Committee. Any GC member can review the requirements and add Members to the GitHub org.

https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements

![image](https://user-images.githubusercontent.com/13387/143408247-fc087884-ceff-41c5-a0b2-76fecac5c380.png)

**Comment by SergeyKanzhelev** [comment]
Welcome, @mustafain117! Invite sent

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev, it looks like I can't add folks to the organization, and I think I should:
> 
> > Once your sponsors have responded, your request will be reviewed by the Governance Committee. Any GC member can review the requirements and add Members to the GitHub org.
> 
> https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements
> 
> ![image](https://user-images.githubusercontent.com/13387/143408247-fc087884-ceff-41c5-a0b2-76fecac5c380.png)

Created: https://github.com/open-telemetry/community/pull/923
