### ISSUE TITLE
REQUEST: New membership for pirgeo

### ISSUE THREAD

**Issue by pirgeo** [open-telemetry/community#926]
### GitHub Username

@pirgeo

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @reyang 
- @jsuereth
- @jmacd 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/oteps/pull/187
https://github.com/open-telemetry/opentelemetry-specification/pull/1837
https://github.com/open-telemetry/opentelemetry-specification/pull/1842
https://github.com/open-telemetry/opentelemetry-specification/pull/1935
https://github.com/open-telemetry/opentelemetry-specification/pull/1958
https://github.com/open-telemetry/opentelemetry-specification/pull/2002
https://github.com/open-telemetry/opentelemetry-specification/pull/2013
https://github.com/open-telemetry/opentelemetry-specification/pull/2104
https://github.com/open-telemetry/opentelemetry-specification/pull/2131
https://github.com/open-telemetry/opentelemetry-specification/pull/2153
https://github.com/open-telemetry/opentelemetry-specification/pull/2161
https://github.com/open-telemetry/opentelemetry-specification/pull/2162
https://github.com/open-telemetry/opentelemetry-specification/pull/2163
https://github.com/open-telemetry/opentelemetry-specification/pull/2164
https://github.com/open-telemetry/opentelemetry-specification/pull/1716
https://github.com/open-telemetry/opentelemetry-specification/pull/1815
https://github.com/open-telemetry/opentelemetry-go/pull/2350
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2634
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2452
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2207
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2093
https://github.com/open-telemetry/opentelemetry-python/pull/1887
https://github.com/open-telemetry/opentelemetry-python/pull/2234
https://github.com/open-telemetry/opentelemetry-js/pull/2523
https://github.com/open-telemetry/opentelemetry-js/pull/2496
https://github.com/open-telemetry/opentelemetry-js/pull/2638
https://github.com/open-telemetry/opentelemetry-js/pull/2634
https://github.com/open-telemetry/opentelemetry-js/pull/2601
https://github.com/open-telemetry/opentelemetry-js/pull/2569
- Issues responded to
https://github.com/open-telemetry/opentelemetry-specification/issues/1794
https://github.com/open-telemetry/opentelemetry-specification/issues/2065
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2627
- SIG projects I am involved with
  - SIG Metrics
  - SIG Spec

**Comment by reyang** [comment]
+1, I support 👍

**Comment by jsuereth** [comment]
+1, I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @pirgeo! Invite sent
