### ISSUE TITLE
REQUEST: New membership for brettmc

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/community#928]
### GitHub Username
@brrettmc

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@bobstrecansky 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-php/pulls?q=is%3Apr+author%3Abrettmc
https://github.com/open-telemetry/opentelemetry-specification/pull/2108
- Issues responded to
https://github.com/open-telemetry/opentelemetry-php/issues/382#issuecomment-975927000

- SIG projects I am involved with
opentelemetry-php

**Comment by SergeyKanzhelev** [comment]
@brettmc you'd need to sponsors for this application. I understand php may be understaffed. Perhaps somebody from @open-telemetry/php-approvers can sponsor?

**Comment by bobstrecansky** [comment]
I support!

**Comment by SergeyKanzhelev** [comment]
synced up with @bobstrecansky . I support the membership as a second sponsor. 

Welcome, @brettmc! Invite sent
