### ISSUE TITLE
REQUEST: New membership for @tidal

### ISSUE THREAD

**Issue by tidal** [open-telemetry/community#930]
### GitHub Username

@tidal

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have ~~two~~ one sponsor~~s~~ that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bobstrecansky

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-php/pulls?q=+is%3Apr+involves%3Atidal
  - https://github.com/open-telemetry/opentelemetry-php-contrib/pulls?q=+is%3Apr+involves%3Atidal
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-php/issues?q=is%3Aissue+involves%3Atidal
  - https://github.com/open-telemetry/opentelemetry-php-contrib/issues?q=is%3Aissue+involves%3Atidal
- SIG projects I am involved with
https://github.com/open-telemetry/opentelemetry-php

**Comment by bobstrecansky** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
I support as a second sponsor.

**Comment by SergeyKanzhelev** [comment]
Welcome, @tidal! Invite sent
