### ISSUE TITLE
Meeting links seem flaky

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#931]
At the JS meeting today, nobody was able to get into the meeting. Some people go the error "The meeting is scheduled for Thu Jan 1, 2099" and some people got the error "The host has another meeting in progress." I created a temporary zoom room for us to have the meeting, and about 5-10 minutes after the meeting started the meeting room started working again so we moved over there in order to preserve the recording.

@aabmass mentioned they have had similar issues in the python SIG

Could this be related to some limit on our zoom account?

**Comment by SergeyKanzhelev** [comment]
@mtwo can you please take a look?

@dyladan were you able to use one of the old meeting rooms?

**Comment by aabmass** [comment]
We are facing this right now in the Python SIG. The calendar link zoom page shows this:
<img width="1792" alt="Screen Shot 2021-12-09 at 12 04 55 PM" src="https://user-images.githubusercontent.com/1510004/145442507-b09fcf13-1726-48ae-97ad-f63b2fb71e86.png">

**Comment by sanketmehta28** [comment]
the issue seems to be with zoom update. After installing latest update from zoom, the meeting link was working fine.

**Comment by dyladan** [comment]
In JS we had the same issue and I am on the latest zoom. For some reason, the room just starts working after some (unpredictable) period of time

**Comment by aabmass** [comment]
I am using the web client fwiw (and my company won't let me install the desktop app). Other folks in the meeting were seeing a different error, something about "1/1/2099". What's weird is today the calendar link didn't start working after 5-10 min so we just used the old room.

**Comment by mtwo** [comment]
Discussed this over Slack this morning, apologies for not responding earlier! I reproduced this on the Python and Swift SIGs after getting notified by @bryce-b over Slack. I think that the 1/1/2099 error is related to how Zoom handles recurring meetings created from Google Calendar and that the "Meeting owner is in another call" is the true error.

I checked / changed our Zoom settings this morning after the meetings took place and regenerated the links. Summary of what I did:

- I attempted to join the meetings and confirmed that I saw these errors. I saw the 1/1/2099 error in the Zoom app and the "Meeting owner is in another call" error when joining from the web client.
- I confirmed that our meetings are configured to allow people to join without the host. This was already the case.
- I found a setting that controls how early non-owners can join a meeting and set it to 15 minutes. It was previously zero.
- I regenerated the Zoom links and tested that I could join the calls.

I'm hoping that this fixes it, though I'm concerned that it may not have. Worst case we can get more Zoom accounts from the CNCF and go back to our old model. Let's try this for the next few weeks; please ping me on this issue (by re-opening it and @ mentioning me) or on Slack (with an @ mention) ASAP if it reoccurs.

**Comment by aabmass** [comment]
🙌 thanks @mtwo!

One small question

> I found a setting that controls how early non-owners can join a meeting and set it to 15 minutes. It was previously zero.

Who is owner in this case and when do the meetings "start"? We were running into this during the meeting also, not just before.

**Comment by mtwo** [comment]
Good question, I had the same thoughts, which is why I'm not confident that I understand the root cause of the issue. The owner is a zoom account called cncf-opentelemetry-1, which nobody should be signed in as. Basically, this owner has never joined any meeting, but we only started running into trouble yesterday for some reason.

**Comment by codeboten** [comment]
Ran into this problem again this morning at the Python SIG meeting :(

**Comment by mtwo** [comment]
Looks like this also occurred for PHP today

**Comment by bobstrecansky** [comment]
Yup; @mtwo - thank you for fixing our link in the calendar.

**Comment by mtwo** [comment]
Unfortunately I'm no closer to understanding why this is happening. The only course of action that is guaranteed to fix this is going back to multiple Zoom accounts and spacing out our meetings. I'll try to debug this further before pursuing that.

**Comment by cijothomas** [comment]
+1 - We hit this issue in .NET SIG meeting today as well. We used a temporary zoom meeting link from past to workaround temporarily.

**Comment by dyladan** [comment]
Do we have a contact at zoom that can help us out with troubleshooting? If not, should we try to get one?

**Comment by dyladan** [comment]
JS meeting had the issue again. This is the issue I see:

> # The meeting is scheduled for Thu, Jan 1 , 2099.
> Start at 3:00 AM
> This is a calendar meeting

**Comment by codeboten** [comment]
Python today :(
![Screen Shot 2022-01-13 at 9 02 27 AM](https://user-images.githubusercontent.com/223565/149375382-636742bd-fc87-4d85-8c5f-22201799d398.png)

**Comment by dyladan** [comment]
JS was not able to have our meeting on the regular zoom call at all yesterday and I had to generate a link on my own. Because of that the call was not recorded.

![image](https://user-images.githubusercontent.com/1612643/151368501-bbbb5636-96ad-4e5b-ad40-373a9fc8ef61.png)
