### ISSUE TITLE
REQUEST: New membership for @PaurushGarg

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/community#934]
### GitHub Username

@PaurushGarg

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @alolita 
- @dashpole

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored
  * collector-contrib: (Prometheus Receiver Tests)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6219 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6681 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6705 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6706 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6707 Merged
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6708 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6709 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6710 (Approved, Ready to Merge)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6711 (Merged)
  * collector-contrib: (Prometheus Receiver)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6696 (Merged)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6794 (Approved, Ready to Merge)
  * collector-contrib: (Prometheus Exporter)
      * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6697 (Merged)
  * opentelemtry-cpp:
      * https://github.com/open-telemetry/opentelemetry-cpp/pull/1008 (Merged)
  * opentelemetry-js:
      * https://github.com/open-telemetry/opentelemetry-js/pull/2499 (Merged)

- Issues created:
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6000
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6085
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6090
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6083
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6087
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6151
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6212
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6360
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6376
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6405
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6400

- Issues responded to:
  * https://github.com/open-telemetry/opentelemetry-cpp/issues/368
  * https://github.com/open-telemetry/opentelemetry-js/issues/2389
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6228
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5233
  * https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5415

- SIG projects I am involved in:
  * Collector Prometheus Workgroup 
  * Collector SIG

**Comment by dashpole** [comment]
I support

**Comment by alolita** [comment]
I support this membership.

**Comment by SergeyKanzhelev** [comment]
Welcome, @PaurushGarg! Invite sent
