### ISSUE TITLE
How are maintainers nominated?

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#936]
In https://github.com/open-telemetry/community/blob/main/community-membership.md it states:

>The process for becoming a Maintainer should be defined in the SIG charter of the SIG owning the subproject.

But as far as I can tell, no SIG actually has such a charter defined. I looked in a few SIG repositories and looked through this repository. If I'm just missing it somewhere, please let me know. If not, we either need to change this wording or create charter documents for each SIG.

**Comment by SergeyKanzhelev** [comment]
I'd say we can update the wording. Generally SIG maintainers have all the powers to appoint triagers, approvers, and maintainers, including making exceptions for the formal requirements listed in the membership document. Writing charter document may be an overkill for smaller SIGs. For bigger SIGs, the charter document with the formal SIG-specific requirements for maintainers and approvers may be a good idea, but it would be best to write a template charter document for SIGs to adopt.

**Comment by dyladan** [comment]
At the least we need to update the community-membership.md because it references charters that don't currently exist.

**Comment by alolita** [comment]
@SergeyKanzhelev the bigger SIGs definitely need some process. Imo, we're running into a feast or famine situation on the project. 

The big SIGs may have a reasonable flow of steady contributing members but no clear achievement milestones and (possibly reasonable evaluation time periods e.g. 3-6 months) for graduating contributing members to become triagers, approvers or maintainers. 

The smaller SIGs which may not have enough steady contributors and members would benefit from having some achievement milestones for participation.

I feel all project maintainers need to opine on this thread to have equal representation for all project SIGs.

**Comment by bhs** [comment]
I agree with Alolita re wanting more feedback from project maintainers here.

One idea would be a "default SIG charter" at the project level, with SIGs free to amend/extend/etc as they see fit.

**Comment by dyladan** [comment]
For what it's worth, the JS SIG decided to follow the established process of "existing maintainers vote" and we promoted some new maintainers this week. We will likely be doing the same for a few new approvers. I also took an action item to write a minimal charter for JS which codifies these things for our SIG because the existing community documentation definitely implies there should be one and I don't see any reason not to have one really.

**Comment by trask** [comment]
> One idea would be a "default SIG charter" at the project level, with SIGs free to amend/extend/etc as they see fit.

I like this idea. One thing I'd like to see included is that folks who are interested in Triager, Approver, or Maintainer roles should reach out to existing maintainer(s) to mention their interest (e.g. DM on Slack). It's not always clear who is interested in these roles, and while we try to proactively reach out, if we know that someone is interested early on, we can help them along the path.

**Comment by tigrannajaryan** [comment]
Very briefly, my personal criteria for nominating someone as a maintainer is usually the following:
- Quality of past contributions. Do they demonstrate the engineering and technical excellence in the form of PRs/issues/design documents/PR reviews/etc?
- Quantity and duration of past contributions. Did they have a chance to acquire sufficient experience with the project/codebase?
- Time commitment. Are they willing/able to reliably contribute X hours every week for the next Y months?
- Maintainer attitude: do they only work on "cool" new features or they care about the codebase and submit PRs that clean up the codebase, fix flaky tests, improve the CI, refactor awkward corners, etc.
- OSS-readiness :-) Do they show ability to communicate nicely in the community? Have they been able to navigate non-trivial situations where different conflicting opinions are coming from different vendors? Can they say "no" when pressed to say "yes"?
- There is probably more that I think of subconsciously, but these are top of my mind at the moment.

The majority of these are very subjective. We can indeed capture them in some sort of document, but if there is an expectation of codifying these in some objectively evaluable form then I don't think it is fully possible.

**Comment by dyladan** [comment]
I'm not really asking for the specific requirements to be codified as much as the specific process. Do the existing maintainers vote? Does the TC need to approve it? Etc.

**Comment by SergeyKanzhelev** [comment]
> Do the existing maintainers vote? Does the TC need to approve it? 

As it was designed, no TC or GC involvement is required for declaring triagers, approvers, or maintainers. GC maintains the membership requirements document. TC makes an initial kick off of the project by setting up initial teams and repositories. As it designed, SIG maintainers are maintainers of all the corresponding GH teams and can add/remove people as needed.

As for voting process, this is for maintainers to decide.

**Comment by dyladan** [comment]
This was identified in a meeting about collector health as an important bottleneck in the project. The action item agreed on was "Update project-wide maintainer requirements. The official process in the community repo references charters that don’t exist, these need to be rewritten." I agreed to write a draft PR to the community repo for this. Assigning myself.

**Comment by tigrannajaryan** [comment]
@dyladan I think https://github.com/open-telemetry/community/pull/960 resolves this. Or do you plan to add more?
