### ISSUE TITLE
Request to create open-telemetry/java-contrib-triagers and update open-telemetry/java-instrumentation-triagers

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#941]
@open-telemetry/technical-committee can someone create an `open-telemetry/java-contrib-triagers` team, and add me with maintainer rights so I can set up the rest?

And can you add me with maintainer rights to the (already existing) `open-telemetry/java-instrumentation-triagers` team?

thx

**Comment by SergeyKanzhelev** [comment]
Done and done
