### ISSUE TITLE
Advice on CODEOWNERS for contrib repos

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#942]
From https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners:

> The people you choose as code owners must have write permissions for the repository

I'm not sure if there's any point in using CODEOWNERS if we don't give the users in that file write permission(?)

Does anyone have recommendations for managing reviews / workflows in "contrib" repos?

A couple of options
* Give write permissions for the repo to users in the CODEOWNERS file
* Have repo approvers manually request reviews from module owners (we could keep the module owner list in the CODEOWNERS file, though that seems sort of confusing to me since they aren't real CODEOWNERS in that case)

**Comment by dyladan** [comment]
JS and Python have experimented with using a github action to give some level of ownership of individual modules/directories to org members even if they are not approvers. Seems to be going well so far. The action is very basic and doesn't have many features right now, but in JS at least it drastically sped up our review process in contrib.

**Comment by trask** [comment]
nice! we'll give it a try in java-contrib

**Comment by trask** [comment]
closing, thx @dyladan 👍

**Comment by dyladan** [comment]
@trask let me know how it goes. the action doesn't get a lot of development, but i'm happy to add features that make sense and obviously fix bugs
