### ISSUE TITLE
REQUEST: New membership for @cyrille-leclerc

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/community#943]
### GitHub Username

@cyrille-leclerc

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @anuraaga

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- Creator and maintainer of the [OpenTelemetry Maven Extension](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/maven-extension)
   - Component: https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/maven-extension
   - PRs: https://github.com/open-telemetry/opentelemetry-java-contrib/pulls?q=is%3Apr+author%3Acyrille-leclerc
   - Commits: https://github.com/open-telemetry/opentelemetry-java-contrib/commits?author=cyrille-leclerc
   - Issues: https://github.com/open-telemetry/opentelemetry-java-contrib/issues?q=is%3Aissue+%22Maven+Extension%22+OR+%22maven-extension%22
- SIG projects I am involved with: 
   - opentelemetry-java-contrib/maven-extension
   - Note that I am also the creator and maintainer of the [Jenkins OpenTelemetry Plugin](https://github.com/jenkinsci/opentelemetry-plugin)

**Comment by anuraaga** [comment]
I support - thanks for all the help @cyrille-leclerc!

**Comment by trask** [comment]
I support also!

**Comment by SergeyKanzhelev** [comment]
Welcome, @cyrille-leclerc! Invite sent
