### ISSUE TITLE
REQUEST: New membership for @Mrod1598

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/community#945]
### GitHub Username

@Mrod1598

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @trask 
- @anuraag

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6916
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/155
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/137
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/43
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5755
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5755
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5861
- SIG projects I am involved with
JVM Metrics
Collector

**Comment by trask** [comment]
I support!

**Comment by anuraaga** [comment]
I support - thanks @Mrod1598!

**Comment by SergeyKanzhelev** [comment]
Welcome, @Mrod1598!

Invite sent
