### ISSUE TITLE
REQUEST: New membership for @Frefreak

### ISSUE THREAD

**Issue by Frefreak** [open-telemetry/community#949]
### GitHub Username

@Frefreak

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @bogdandrutu 
- @tensorchen 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - opentelemetry-collector
    https://github.com/open-telemetry/opentelemetry-collector/pull/3166
    https://github.com/open-telemetry/opentelemetry-collector/pull/3452
    https://github.com/open-telemetry/opentelemetry-collector/pull/4066
  - opentelemetry-go-contrib
    https://github.com/open-telemetry/opentelemetry-go-contrib/pull/870
  - opentelemetry-rust
    https://github.com/open-telemetry/opentelemetry-rust/pull/579

- Issues responded to
  - opentelemetry-collector
    https://github.com/open-telemetry/opentelemetry-collector/issues/3162
    https://github.com/open-telemetry/opentelemetry-collector/issues/3628
    https://github.com/open-telemetry/opentelemetry-collector/issues/4046
    https://github.com/open-telemetry/opentelemetry-collector/issues/4109
    https://github.com/open-telemetry/opentelemetry-collector/issues/4669
  - opentelemetry-collector-contrib
    https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5436
  - opentelemetry-go
    https://github.com/open-telemetry/opentelemetry-go/issues/1924

- SIG projects I am involved with
  https://github.com/open-telemetry/opentelemetry-collector

**Comment by bogdandrutu** [comment]
I support this. Thank you for all your contributions

**Comment by tensorchen** [comment]
I support this request!

**Comment by SergeyKanzhelev** [comment]
Welcome, @Frefreak! Invite sent
