### ISSUE TITLE
Create @open-telemetry/go-triagers team

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#952]
Please look at Java or .Net repos for reusing the maintainers--> approvers --> triagers structure.

cc: @Aneurysm9 @MrAlias @MadVikingGod (aka @open-telemetry/go-maintainers)

**Comment by MrAlias** [comment]
I support this.

**Comment by SergeyKanzhelev** [comment]
done

**Comment by MrAlias** [comment]
Looks like I no longer have permissions to set that created team as triager of open-telemetry/opentelemetry-go. @SergeyKanzhelev can you set these permissions?

**Comment by dyladan** [comment]
Think only TC members have access to do those things @open-telemetry/technical-committee

**Comment by dyladan** [comment]
Reopening until the permission is resolved

**Comment by SergeyKanzhelev** [comment]
done
