### ISSUE TITLE
Create a blog-approvers team in the OpenTelemetry organization.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#953]
In order to support the OpenTelemetry blog being hosted out of the opentelemetry.io repository, we need a team of blog approvers that can be codeowners of new blog content.

**Comment by alolita** [comment]
Hi @austinlparker Please add me as a blog post reviewer/approver.

**Comment by SergeyKanzhelev** [comment]
Created https://github.com/orgs/open-telemetry/teams/blog-approvers, made @austinlparker and @alolita the initial maintainers of the group.
