### ISSUE TITLE
Add opentelemetry-java-bot to EasyCLA allowlist

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#954]
Based on the discussion at https://github.com/open-telemetry/community/issues/809#issuecomment-1016522419, can we get @opentelemetry-java-bot added to the EasyCLA allowlist? we would like to use it to push some automatically-generated, non-copyrightable code as part of release automation.

(and thanks to @bobstrecansky and @austinlparker who alerted me to the cool OTel language icons)

**Comment by bogdandrutu** [comment]
@trask  https://github.com/opentelemetry-java-bot is an org, you need to setup the right permissions for CNCF admins, etc. Why not a repo in this org?

**Comment by trask** [comment]
@bogdandrutu it's not meant to be a repository, it's a bot user account (see @dyladan's comment linked above)

**Comment by dyladan** [comment]
When i go to https://github.com/opentelemetry-java-bot I get a 404. Is the account private or did you delete it?

**Comment by trask** [comment]
😞 github flagged and hid the account b/c I already had one "machine" account. trying to get it fixed, will post here once it's back online

**Comment by trask** [comment]
@opentelemetry-java-bot account is unflagged and ready for EasyCLA allowlisting 🙏

**Comment by dyladan** [comment]
@bogdandrutu what made you think its an org? Looks like a user to me

**Comment by trask** [comment]
bump 🙏

**Comment by dyladan** [comment]
I'm not sure what the process is to get this done. Last time we had something allowlisted I think @lizthegrey helped us so maybe she can help here?

**Comment by trask** [comment]
I realized that since its our own bot account, I can just log in to it and sign the CLA (using my real name on the CLA signature)
