### ISSUE TITLE
REQUEST: New membership for @JonathanWamsley

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/community#955]
### GitHub Username

@JonathanWamsley

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (@djaglowski  )sponsor-1
- (@dmitryax )sponsor-2

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6815
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6878
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6880
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7131
- Issues responded to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6896
- I've attended the Agent/Collector SIG

**Comment by djaglowski** [comment]
I support.

**Comment by SergeyKanzhelev** [comment]
Welcome, @JonathanWamsley! Invite sent
