### ISSUE TITLE
Create OpenTelemetry End-User Working Group

### ISSUE THREAD

**Issue by sharrmander** [open-telemetry/community#956]
## Proposed goal:

We (@sharrmander, @alolita) are proposing the creation of a new end-user working group under the OTEL Communications SIG. Sharr Creeden and Alolita Sharma are volunteering to like to facilitate this workgroup. Our goals include ensuring a welcoming space for OpenTelemetry end users to discuss challenges, solutions, best practices and to learn from and help each other. Due to the nature of the potential workstreams identified, we feel these efforts are best coordinated under the existing Communications SIG structure. Other OTEL contributors who are, or may be, interested in this topic include @tedsuo , @lizthegrey , @mattmccleary, @SergeyKanzhelev 

The primary goal of this proposed end-user working group is to foster a sense of vendor-agnostic community for OpenTelemetry end-users; a space where they can connect with each other to share best practices for adoption and/or ask for help. By facilitating end-user engagement opportunities, we hope to reduce the burden on maintainers while simultaneously establishing or improving end-user feedback cycles to influence priorities of OTel SIGs. We discourage promotion of vendor-specific solutions and desire to focus on OpenTelemetry core technologies, adoption and usage. We plan to encourage all end-users to participate in the wider OpenTelemetry community and SIGs but pragmatically understand that not all end-users are in a position to be able to engage at a deeper level, and hope this working group can especially benefit these types of users.

## Examples of potential workstreams covered by an end-user working group: 

- Creation and maintenance of end-user research assets such as OpenTelemetry surveys [Example Survey & Results]
- Coordinate work with the end user community https://www.cncf.io/enduser/ 
- Coordinate creation of educational materials like blog posts, docs, etc, as well as announcements made by Comms SIG.
- Creation and/or coordination and/or promotion of end-user learning opportunities such as Office Hours
    - Regarding Office Hours: We want to encourage all discussions to become available on GitHub issues or in an appropriate CNCF slack channel so that everyone can benefit from the discussion. 
- Creation and/or coordination and/or promotion of end-user events such as CNCF’s Observability Practitioners Summit
- Creation and/or facilitation of processes which help bring the voice of end-users into OTel SIG discussions such as feedback survey summaries and roadmap/feature/documentation requests

## Proposed meeting schedule: 

- Twice monthly working group discussion to happen on off weeks from the existing communication SIG meetings to review in-flight initiatives and plan upcoming events or other end-user visibility workstream activity  
   - Thursdays at 10:30am  
- Monthly end-user Office Hours to be held in US and EMEA friendly timezones

## Proposed communication channels: 

- (existing resource) Github working group communications will happen under the OTel community repo
- (new) CNCF slack #otel-end-users
    - Purpose: foster sense of end-user community
- (existing resource) CNCF slack #otel-userresearch
    - Purpose: Coordinate end user research

## Proposed timeline:

We are interested in kicking off the first working group meeting in February 2022 (likely February 17th 10:30am PST)

**Comment by austinlparker** [comment]
We can discuss this at the next Comms SIG meeting as well! Our calendar invite disappeared but the next one should be on 1/27.

**Comment by sharrmander** [comment]
> We can discuss this at the next Comms SIG meeting as well! Our calendar invite disappeared but the next one should be on 1/27.

Thanks @austinlparker I am hoping to show up to the Comms SIG to discuss it with y'all this week too; thanks for confirming that there will be a meeting -- I'll watch the calendar for an updated meeting since they disappeared

**Comment by alolita** [comment]
Sorry - did not see the Comms SIG meeting link in time for 1/27. Are there meeting notes and AIs? @sharrmander

**Comment by sharrmander** [comment]
Hey @alolita and followers!

We're going to have our first meeting on February 17th at 10:30am PST; meeting invite will fall under the Communications SIG calendar events.

**Comment by dyladan** [comment]
I don't see that meeting on the public otel calendar. Is the calendar just not yet updated?

**Comment by punya** [comment]
I'd like to attend this as well, if the calendar/Zoom invite can be shared.

**Comment by nemerkab** [comment]
The event is now on the public calendar https://github.com/open-telemetry/community#calendar  

You should be able to see the attached Zoom meeting on the event today. I am not sharing the information here directly in case it changes between now and the meeting. The calendar should have the information you need.

**Comment by arminru** [comment]
Great to see this, thank you for organizing it @sharrmander and @alolita!

Could you also please update https://github.com/open-telemetry/community/blob/main/README.md to list the WG, meeting time, agenda/meeting notes and Slack channel (unless the generic _#opentelemetry_ one seems appropriate enough) there?

**Comment by arminru** [comment]
^ While I was at it I created #985, PTAL regarding meeting time and Slack channel. Thanks!

**Comment by trask** [comment]
hey @sharrmander! i'm just doing some triage, is it ok to close this issue?
