### ISSUE TITLE
Request: Contrib Repo for OpenTelemetry Ruby

### ISSUE THREAD

**Issue by mwear** [open-telemetry/community#959]
The Ruby SIG would like to start separating packages into a contrib repo. Can we have a contrib repo created at: https://github.com/open-telemetry/opentelemetry-ruby-contrib? 

We would to have the maintainers from the main repo: @open-telemetry/ruby-maintainers along with @arielvalentin and @ericmustin.

**Comment by SergeyKanzhelev** [comment]
Created: https://github.com/orgs/open-telemetry/teams/ruby-contrib-maintainers/ and https://github.com/open-telemetry/opentelemetry-ruby-contrib

Updated permissions. Let me know if any adjustments are needed

**Comment by mwear** [comment]
👀 good! Thank you @SergeyKanzhelev!
