### ISSUE TITLE
REQUEST: New membership for cpheps

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/community#962]
### GitHub Username

@cpheps

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

**PRs**:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7046
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7239
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7280
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7299
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7378

**Issues**:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7241
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7358
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7238
- https://github.com/open-telemetry/opentelemetry-java-contrib/issues/153
- https://github.com/open-telemetry/opentelemetry-java/issues/4094

**SIG projects I am involved with**:
- collector-contrib
- java-contrib

**Comment by jpkrohling** [comment]
I support

**Comment by djaglowski** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @cpheps! Invite sent
