### ISSUE TITLE
REQUEST: New membership for schmikei

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/community#966]
### GitHub Username
@schmikei

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @djaglowski 
- @jpkrohling 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs authored

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6972
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7125
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7163
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7175

#### SIG projects I am involved with

- collector-contrib

**Comment by jpkrohling** [comment]
I support this membership.

**Comment by djaglowski** [comment]
I support
