### ISSUE TITLE
REQUEST: New membership for vasireddy99

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/community#971]
## GitHub Username

@vasireddy99

### Requirements

* [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
* [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
* [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
* [x] I am actively contributing to 1 or more OpenTelemetry subprojects
* [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
* [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
    

### Sponsors

- @alolita
- @lalitb

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

List of contributions to openTelemetry Project:

opentelemtry - lambda

https://github.com/open-telemetry/opentelemetry-lambda/pull/202
https://github.com/open-telemetry/opentelemetry-lambda/pull/203
https://github.com/open-telemetry/opentelemetry-lambda/pull/204
https://github.com/open-telemetry/opentelemetry-lambda/pull/205

opentemetry-cpp

https://github.com/open-telemetry/opentelemetry-cpp/pull/1152
https://github.com/open-telemetry/opentelemetry-cpp/pull/1136

SIG projects I am involved in:

 * [Collector Prometheus Workgroup](https://docs.google.com/document/d/19bnXziPn2MZ9wO6684UoI4D-LCjGL5bTJkGhux29bx8/edit) 
* [Collector SIG](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.am4gwetk416e) 
* [CPP SIG](https://docs.google.com/document/d/1i1E4-_y4uJ083lCutKGDhkpi3n4_e774SBLi9hPLocw/edit#heading=h.9tngw7jdwd6b)

**Comment by lalitb** [comment]
I support.

**Comment by alolita** [comment]
I support this membership.
