### ISSUE TITLE
REQUEST: Consult on opentelemetry-dart

### ISSUE THREAD

**Issue by dustinlessard-wf** [open-telemetry/community#974]
Hi! We have begun developing an OpenTelemetry Dart client and would like to ensure that our aim for open sourcing it aligns with the OTEL project as a whole.  I would like some direction on who I may discuss this with in more detail.  Thank you!

**Comment by arminru** [comment]
Hi @dustinlessard-wf. Thank you for your proposal!
Can you please give some more details on your efforts? What's the current state of the implementation? Do you have a team of steady contributors that are willing to commit to maintaining the client if it would be adopted by the OpenTelemetry project? If that's not the case, it would be best to reach out within the OTel community first (both here and on Slack) to find contributors willing to commit, ideally also among members who are already active within the project.
In general we are open to accept new implementations but we would like to avoid raising expectations by adding it to the OTel organization if we are not able to ensure it will be well-maintained or reach a working state.

**Comment by SergeyKanzhelev** [comment]
Also please look at https://github.com/open-telemetry/community/blob/4b53b7ffb6390e57850e9a916bd63253349a7770/CONTRIBUTING.md#donations
