### ISSUE TITLE
Get Go SIG meeting notes doc link in the Community README file

### ISSUE THREAD

**Issue by thomashchan1** [open-telemetry/community#98]
Can we get the Go SIG [meeting notes doc](https://docs.google.com/document/d/1A63zSWX0x2CyCK_LoNhmQC4rqhLpYXJzXbEPDUQ2n6w/edit#) on our Community README under Golang SDK section?

**Comment by thomashchan1** [comment]
Making this request generic for all SIGs. Here is the [meeting notes for Python](url): https://docs.google.com/document/d/1CIMGoIOZ-c3-igzbd6_Pnxx1SjAkjwqoYSUWxPY8XIs/edit?usp=sharing need to put this under Python SDK section. Happy to do this via a PR if appropriate. Thanks in advance.

**Comment by SergeyKanzhelev** [comment]
Can you please send PRs?

**Comment by thomashchan1** [comment]
Here it is: https://github.com/open-telemetry/community/pull/99

**Comment by SergeyKanzhelev** [comment]
closing the issue
