### ISSUE TITLE
enabling Sonarcloud in open-telemetry

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#986]
@lalitb you sent a request to install the SonarCloud into Open-telemetry organization. Can you please comment on the need for it following this instruction: https://github.com/open-telemetry/community/blob/main/docs/using-github-extensions.md#requesting-installing-of-apps-extensions-or-bots

**Comment by SergeyKanzhelev** [comment]
request link for admins: https://github.com/apps/sonarcloud/installations/new/permissions?request_id=317052&target_id=49998002

**Comment by lalitb** [comment]
Oh, that was a mistake. It was not meant to be for OpenTelemetry org. Can we ignore, or cancel the request.

**Comment by SergeyKanzhelev** [comment]
Cancelled, no worries
