### ISSUE TITLE
REQUEST: New membership for dmathieu

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/community#988]
### GitHub Username

@dmathieu

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

* @Aneurysm9 
* @MrAlias 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
  - https://github.com/open-telemetry/opentelemetry-go/pull/2522
  - https://github.com/open-telemetry/opentelemetry-go/pull/2559
  - https://github.com/open-telemetry/opentelemetry-go/pull/2560
  - https://github.com/open-telemetry/opentelemetry-go/pull/2594
  - https://github.com/open-telemetry/opentelemetry-go/pull/2627
  - https://github.com/open-telemetry/opentelemetry-go/pull/2608
- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-go/issues/2642
  - https://github.com/open-telemetry/opentelemetry-go/pull/2622
  - https://github.com/open-telemetry/opentelemetry-go/issues/2595
  - https://github.com/open-telemetry/opentelemetry-go/issues/2552
  - https://github.com/open-telemetry/opentelemetry-go/issues/2508
- SIG projects I am involved with
  - [OpenTelemetry Go](https://github.com/open-telemetry/opentelemetry-go) (though I am not joining the meeting at this time, because it's quite late for my timezone).

**Comment by MrAlias** [comment]
I support :+1:

**Comment by Aneurysm9** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @dmathieu! Invite sent
