### ISSUE TITLE
Missing Go SIG meets on Youtube

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/community#989]
I found some Go SIG meetings are not shown on the Youtube channel. Like `February 24, 2022, 13:00 PT`, `February 17, 2022, 13:00 PT` and `February 10, 2022, 13:00 PT`.

**Comment by MrAlias** [comment]
cc @mtwo

**Comment by mtwo** [comment]
@SergeyKanzhelev do you know why this could be happening? I don't know much about how the video uploads work :(

**Comment by SergeyKanzhelev** [comment]
Posted instructions: https://github.com/open-telemetry/community/pull/990

What zoom link was used?

**Comment by SergeyKanzhelev** [comment]
@alanwest are you running the upload tool on regular basis? Just checking

**Comment by alanwest** [comment]
Yes, it's been running it regularly. Still on my todo list to automize it via GitHub actions - will solve this soon.

> I found some Go SIG meetings are not shown on the Youtube channel. Like `February 24, 2022, 13:00 PT`, `February 17, 2022, 13:00 PT` and `February 10, 2022, 13:00 PT`.

The tool that publicizes the videos filters out [meetings less than 20 minutes](https://github.com/open-telemetry/community/blob/main/tools/OpenTelemetryYoutube/OpenTelemetryYoutube/Program.cs#L126). There are a fair amount of videos on these days that are only a few minutes or even few seconds long. Though maybe the 20 minute threshold is too aggressive?

Does anyone know offhand whether the Go SIG meeting on these dates was particularly short? Videos can be manually publicized, but unfortunately it is not easy to tell which videos go which with SIG meeting.

**Comment by alanwest** [comment]
Ah ha, I think I found 2/10's Go SIG meeting - came in just under the wire at 19 minutes 39 seconds. It's now been publicized. I found nothing but very short meetings for 2/17 and 2/24.

**Comment by SergeyKanzhelev** [comment]
@alanwest thank you for digging into this. also if you have anything to add in this PR it will be helpful: https://github.com/open-telemetry/community/pull/990
