### ISSUE TITLE
REQUEST: New membership for https://github.com/laziobird

### ISSUE THREAD

**Issue by laziobird** [open-telemetry/community#994]
### GitHub Username

laziobird@gmail.com

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite) 
Slack user name is Tim Green
- [X] I am actively contributing to 1 or more OpenTelemetry subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @sunface 
- @tydhot 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs reviewed / authored
https://github.com/open-telemetry/docs-cn/blob/main/community/opentelemtryCollector/kubernetes-guide.md
- Issues responded to
https://github.com/open-telemetry/docs-cn/issues/45
https://github.com/open-telemetry/docs-cn/issues/51
- SIG projects I am involved with 
The docs-cn group of open-telemetry

**Comment by tydhot** [comment]
I support

**Comment by sunface** [comment]
I support

**Comment by SergeyKanzhelev** [comment]
Welcome, @laziobird! Invite sent
