### ISSUE TITLE
REQUEST: New membership for sanketmehta28

### ISSUE THREAD

**Issue by sanketmehta28** [open-telemetry/community#995]
### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (@srikanthccv)
- (@owais)

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

- PRs authored:

1. https://github.com/open-telemetry/opentelemetry-python-contrib/pull/832
2. https://github.com/open-telemetry/opentelemetry-python-contrib/pull/869
3. https://github.com/open-telemetry/opentelemetry-python-contrib/pull/899
4. https://github.com/open-telemetry/opentelemetry-python-contrib/pull/903

- PRs reviewed:

1. https://github.com/open-telemetry/opentelemetry-python-contrib/pull/925

- SIG projects I am involved with:
[Opentelemetry Python Contrib](https://github.com/open-telemetry/opentelemetry-python-contrib)

**Comment by srikanthccv** [comment]
I support.

**Comment by owais** [comment]
I support.

**Comment by arminru** [comment]
Welcome, @sanketmehta28! Invite sent.

**Comment by sanketmehta28** [comment]
Thank you @arminru . It will be an honor to be a member of this community.
