### ISSUE TITLE
REQUEST: New membership for kishannsangani

### ISSUE THREAD

**Issue by kishannsangani** [open-telemetry/community#996]
### GitHub Username

@kishannsangani

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/CJFCJHG4Q) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenTelemetry subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tidal 
- @bobstrecansky 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the OpenTelemetry project

PRs authored
- https://github.com/open-telemetry/opentelemetry-php/pull/591
- https://github.com/open-telemetry/opentelemetry-php/pull/592
- https://github.com/open-telemetry/opentelemetry-php/pull/594
- https://github.com/open-telemetry/opentelemetry-php/pull/598
- https://github.com/open-telemetry/opentelemetry-php/pull/600

SIG projects I am involved with
- [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php)

**Comment by tidal** [comment]
I support

**Comment by bobstrecansky** [comment]
I support!

**Comment by arminru** [comment]
Welcome, @kishannsangani! Invite sent.
